/* SPDX-License-Identifier: GPL-2.0-only OR BSD-3-Clause */
/******************************************************************************
 *
 * This file is provided under a dual license.  When you use or
 * distribute this software, you may choose to be licensed under
 * version 2 of the GNU General Public License ("GPLv2 License")
 * or BSD License.
 *
 * GPLv2 License
 *
 * Copyright(C) 2019 MediaTek Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of version 2 of the GNU General Public License as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See http://www.gnu.org/licenses/gpl-2.0.html for more details.
 *
 * BSD LICENSE
 *
 * Copyright(C) 2019 MediaTek Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *****************************************************************************/

// This file is generated by script file, please do not edit it directly
#ifndef _MSD95NRTW8_H_
#define _MSD95NRTW8_H_

#define PAD_NC   9999
#define PAD_GND  0

#define BALL_B1 PAD_IRIN
#define PAD_IRIN 1
#define GPIO_PAD_1 GPIO0
#ifndef BALL_B1_IS_GPIO
#define BALL_B1_IS_GPIO 0
#endif
#ifndef PAD_IRIN_IS_GPIO
#define PAD_IRIN_IS_GPIO BALL_B1_IS_GPIO
#endif

#define BALL_E8 PAD_DDCDC_CK
#define PAD_DDCDC_CK 22
#define GPIO_PAD_22 GPIO21
#ifndef BALL_E8_IS_GPIO
#define BALL_E8_IS_GPIO 0
#endif
#ifndef PAD_DDCDC_CK_IS_GPIO
#define PAD_DDCDC_CK_IS_GPIO BALL_E8_IS_GPIO
#endif

#define BALL_D10 PAD_DDCDC_DA
#define PAD_DDCDC_DA 23
#define GPIO_PAD_23 GPIO22
#ifndef BALL_D10_IS_GPIO
#define BALL_D10_IS_GPIO 0
#endif
#ifndef PAD_DDCDC_DA_IS_GPIO
#define PAD_DDCDC_DA_IS_GPIO BALL_D10_IS_GPIO
#endif

#define PAD_DDCDD_CK 9999
#ifndef PAD_DDCDD_CK_IS_GPIO
#define PAD_DDCDD_CK_IS_GPIO 0
#endif

#define PAD_DDCDD_DA 9999
#ifndef PAD_DDCDD_DA_IS_GPIO
#define PAD_DDCDD_DA_IS_GPIO 0
#endif

#define BALL_F7 PAD_DDCDB_CK
#define PAD_DDCDB_CK 20
#define GPIO_PAD_20 GPIO19
#ifndef BALL_F7_IS_GPIO
#define BALL_F7_IS_GPIO 0
#endif
#ifndef PAD_DDCDB_CK_IS_GPIO
#define PAD_DDCDB_CK_IS_GPIO BALL_F7_IS_GPIO
#endif

#define BALL_F8 PAD_DDCDB_DA
#define PAD_DDCDB_DA 21
#define GPIO_PAD_21 GPIO20
#ifndef BALL_F8_IS_GPIO
#define BALL_F8_IS_GPIO 0
#endif
#ifndef PAD_DDCDB_DA_IS_GPIO
#define PAD_DDCDB_DA_IS_GPIO BALL_F8_IS_GPIO
#endif

#define BALL_D5 PAD_DDCDA_CK
#define PAD_DDCDA_CK 18
#define GPIO_PAD_18 GPIO17
#ifndef BALL_D5_IS_GPIO
#define BALL_D5_IS_GPIO 0
#endif
#ifndef PAD_DDCDA_CK_IS_GPIO
#define PAD_DDCDA_CK_IS_GPIO BALL_D5_IS_GPIO
#endif

#define BALL_E5 PAD_DDCDA_DA
#define PAD_DDCDA_DA 19
#define GPIO_PAD_19 GPIO18
#ifndef BALL_E5_IS_GPIO
#define BALL_E5_IS_GPIO 0
#endif
#ifndef PAD_DDCDA_DA_IS_GPIO
#define PAD_DDCDA_DA_IS_GPIO BALL_E5_IS_GPIO
#endif

#define BALL_L7 PAD_DDCA_CK
#define PAD_DDCA_CK 4
#define GPIO_PAD_4 GPIO3
#ifndef BALL_L7_IS_GPIO
#define BALL_L7_IS_GPIO 0
#endif
#ifndef PAD_DDCA_CK_IS_GPIO
#define PAD_DDCA_CK_IS_GPIO BALL_L7_IS_GPIO
#endif

#define BALL_L6 PAD_DDCA_DA
#define PAD_DDCA_DA 5
#define GPIO_PAD_5 GPIO4
#ifndef BALL_L6_IS_GPIO
#define BALL_L6_IS_GPIO 0
#endif
#ifndef PAD_DDCA_DA_IS_GPIO
#define PAD_DDCA_DA_IS_GPIO BALL_L6_IS_GPIO
#endif

#define BALL_M7 PAD_PWM_PM
#define PAD_PWM_PM 3
#define GPIO_PAD_3 GPIO2
#ifndef BALL_M7_IS_GPIO
#define BALL_M7_IS_GPIO 0
#endif
#ifndef PAD_PWM_PM_IS_GPIO
#define PAD_PWM_PM_IS_GPIO BALL_M7_IS_GPIO
#endif

#define BALL_F5 PAD_CEC0
#define PAD_CEC0 2
#define GPIO_PAD_2 GPIO1
#ifndef BALL_F5_IS_GPIO
#define BALL_F5_IS_GPIO 0
#endif
#ifndef PAD_CEC0_IS_GPIO
#define PAD_CEC0_IS_GPIO BALL_F5_IS_GPIO
#endif

#define BALL_C3 PAD_USB_CTRL
#define PAD_USB_CTRL 9
#define GPIO_PAD_9 GPIO8
#ifndef BALL_C3_IS_GPIO
#define BALL_C3_IS_GPIO 0
#endif
#ifndef PAD_USB_CTRL_IS_GPIO
#define PAD_USB_CTRL_IS_GPIO BALL_C3_IS_GPIO
#endif

#define PAD_WOL_INT_OUT 9999
#ifndef PAD_WOL_INT_OUT_IS_GPIO
#define PAD_WOL_INT_OUT_IS_GPIO 0
#endif

#define BALL_L5 PAD_GPIO5_PM
#define PAD_GPIO5_PM 10
#define GPIO_PAD_10 GPIO9
#ifndef BALL_L5_IS_GPIO
#define BALL_L5_IS_GPIO 0
#endif
#ifndef PAD_GPIO5_PM_IS_GPIO
#define PAD_GPIO5_PM_IS_GPIO BALL_L5_IS_GPIO
#endif

#define BALL_F12 PAD_GPIO0_PM
#define PAD_GPIO0_PM 6
#define GPIO_PAD_6 GPIO5
#ifndef BALL_F12_IS_GPIO
#define BALL_F12_IS_GPIO 0
#endif
#ifndef PAD_GPIO0_PM_IS_GPIO
#define PAD_GPIO0_PM_IS_GPIO BALL_F12_IS_GPIO
#endif

#define BALL_B2 PAD_GPIO6_PM
#define PAD_GPIO6_PM 11
#define GPIO_PAD_11 GPIO10
#ifndef BALL_B2_IS_GPIO
#define BALL_B2_IS_GPIO 0
#endif
#ifndef PAD_GPIO6_PM_IS_GPIO
#define PAD_GPIO6_PM_IS_GPIO BALL_B2_IS_GPIO
#endif

#define BALL_L4 PAD_GPIO1_PM
#define PAD_GPIO1_PM 7
#define GPIO_PAD_7 GPIO6
#ifndef BALL_L4_IS_GPIO
#define BALL_L4_IS_GPIO 0
#endif
#ifndef PAD_GPIO1_PM_IS_GPIO
#define PAD_GPIO1_PM_IS_GPIO BALL_L4_IS_GPIO
#endif

#define PAD_GPIO7_PM 9999
#ifndef PAD_GPIO7_PM_IS_GPIO
#define PAD_GPIO7_PM_IS_GPIO 0
#endif

#define BALL_W2 PAD_GPIO2_PM
#define PAD_GPIO2_PM 8
#define GPIO_PAD_8 GPIO7
#ifndef BALL_W2_IS_GPIO
#define BALL_W2_IS_GPIO 0
#endif
#ifndef PAD_GPIO2_PM_IS_GPIO
#define PAD_GPIO2_PM_IS_GPIO BALL_W2_IS_GPIO
#endif

#define PAD_GPIO8_PM 9999
#ifndef PAD_GPIO8_PM_IS_GPIO
#define PAD_GPIO8_PM_IS_GPIO 0
#endif

#define BALL_P4 PAD_VID0
#define PAD_VID0 32
#define GPIO_PAD_32 GPIO31
#ifndef BALL_P4_IS_GPIO
#define BALL_P4_IS_GPIO 0
#endif
#ifndef PAD_VID0_IS_GPIO
#define PAD_VID0_IS_GPIO BALL_P4_IS_GPIO
#endif

#define BALL_Y3 PAD_GPIO9_PM
#define PAD_GPIO9_PM 14
#define GPIO_PAD_14 GPIO13
#ifndef BALL_Y3_IS_GPIO
#define BALL_Y3_IS_GPIO 0
#endif
#ifndef PAD_GPIO9_PM_IS_GPIO
#define PAD_GPIO9_PM_IS_GPIO BALL_Y3_IS_GPIO
#endif

#define BALL_P5 PAD_VID1
#define PAD_VID1 33
#define GPIO_PAD_33 GPIO32
#ifndef BALL_P5_IS_GPIO
#define BALL_P5_IS_GPIO 0
#endif
#ifndef PAD_VID1_IS_GPIO
#define PAD_VID1_IS_GPIO BALL_P5_IS_GPIO
#endif

#define BALL_Y2 PAD_GPIO10_PM
#define PAD_GPIO10_PM 15
#define GPIO_PAD_15 GPIO14
#ifndef BALL_Y2_IS_GPIO
#define BALL_Y2_IS_GPIO 0
#endif
#ifndef PAD_GPIO10_PM_IS_GPIO
#define PAD_GPIO10_PM_IS_GPIO BALL_Y2_IS_GPIO
#endif

#define PAD_VID2 9999
#ifndef PAD_VID2_IS_GPIO
#define PAD_VID2_IS_GPIO 0
#endif

#define PAD_GPIO11_PM 9999
#ifndef PAD_GPIO11_PM_IS_GPIO
#define PAD_GPIO11_PM_IS_GPIO 0
#endif

#define PAD_VID3 9999
#ifndef PAD_VID3_IS_GPIO
#define PAD_VID3_IS_GPIO 0
#endif

#define PAD_GPIO12_PM 9999
#ifndef PAD_GPIO12_PM_IS_GPIO
#define PAD_GPIO12_PM_IS_GPIO 0
#endif

#define BALL_F6 PAD_HDMIRX_ARCTX
#define PAD_HDMIRX_ARCTX 52
#define GPIO_PAD_52 GPIO51
#ifndef BALL_F6_IS_GPIO
#define BALL_F6_IS_GPIO 0
#endif
#ifndef PAD_HDMIRX_ARCTX_IS_GPIO
#define PAD_HDMIRX_ARCTX_IS_GPIO BALL_F6_IS_GPIO
#endif

#define PAD_GPIO8 9999
#ifndef PAD_GPIO8_IS_GPIO
#define PAD_GPIO8_IS_GPIO 0
#endif

#define PAD_GPIO9 9999
#ifndef PAD_GPIO9_IS_GPIO
#define PAD_GPIO9_IS_GPIO 0
#endif

#define PAD_GPIO10 9999
#ifndef PAD_GPIO10_IS_GPIO
#define PAD_GPIO10_IS_GPIO 0
#endif

#define PAD_GPIO11 9999
#ifndef PAD_GPIO11_IS_GPIO
#define PAD_GPIO11_IS_GPIO 0
#endif

#define PAD_GPIO12 9999
#ifndef PAD_GPIO12_IS_GPIO
#define PAD_GPIO12_IS_GPIO 0
#endif

#define PAD_GPIO13 9999
#ifndef PAD_GPIO13_IS_GPIO
#define PAD_GPIO13_IS_GPIO 0
#endif

#define PAD_GPIO14 9999
#ifndef PAD_GPIO14_IS_GPIO
#define PAD_GPIO14_IS_GPIO 0
#endif

#define BALL_AC4 PAD_GPIO15
#define PAD_GPIO15 48
#define GPIO_PAD_48 GPIO47
#ifndef BALL_AC4_IS_GPIO
#define BALL_AC4_IS_GPIO 0
#endif
#ifndef PAD_GPIO15_IS_GPIO
#define PAD_GPIO15_IS_GPIO BALL_AC4_IS_GPIO
#endif

#define PAD_GPIO16 9999
#ifndef PAD_GPIO16_IS_GPIO
#define PAD_GPIO16_IS_GPIO 0
#endif

#define PAD_GPIO17 9999
#ifndef PAD_GPIO17_IS_GPIO
#define PAD_GPIO17_IS_GPIO 0
#endif

#define BALL_AB4 PAD_GPIO18
#define PAD_GPIO18 51
#define GPIO_PAD_51 GPIO50
#ifndef BALL_AB4_IS_GPIO
#define BALL_AB4_IS_GPIO 0
#endif
#ifndef PAD_GPIO18_IS_GPIO
#define PAD_GPIO18_IS_GPIO BALL_AB4_IS_GPIO
#endif

#define PAD_TGPIO0 9999
#ifndef PAD_TGPIO0_IS_GPIO
#define PAD_TGPIO0_IS_GPIO 0
#endif

#define PAD_TGPIO1 9999
#ifndef PAD_TGPIO1_IS_GPIO
#define PAD_TGPIO1_IS_GPIO 0
#endif

#define BALL_AC5 PAD_TGPIO2
#define PAD_TGPIO2 118
#define GPIO_PAD_118 GPIO117
#ifndef BALL_AC5_IS_GPIO
#define BALL_AC5_IS_GPIO 0
#endif
#ifndef PAD_TGPIO2_IS_GPIO
#define PAD_TGPIO2_IS_GPIO BALL_AC5_IS_GPIO
#endif

#define BALL_AB5 PAD_TGPIO3
#define PAD_TGPIO3 119
#define GPIO_PAD_119 GPIO118
#ifndef BALL_AB5_IS_GPIO
#define BALL_AB5_IS_GPIO 0
#endif
#ifndef PAD_TGPIO3_IS_GPIO
#define PAD_TGPIO3_IS_GPIO BALL_AB5_IS_GPIO
#endif

#define BALL_AA12 PAD_TS0_D7
#define PAD_TS0_D7 128
#define GPIO_PAD_128 GPIO127
#ifndef BALL_AA12_IS_GPIO
#define BALL_AA12_IS_GPIO 0
#endif
#ifndef PAD_TS0_D7_IS_GPIO
#define PAD_TS0_D7_IS_GPIO BALL_AA12_IS_GPIO
#endif

#define BALL_AB15 PAD_TS0_D6
#define PAD_TS0_D6 127
#define GPIO_PAD_127 GPIO126
#ifndef BALL_AB15_IS_GPIO
#define BALL_AB15_IS_GPIO 0
#endif
#ifndef PAD_TS0_D6_IS_GPIO
#define PAD_TS0_D6_IS_GPIO BALL_AB15_IS_GPIO
#endif

#define BALL_AC14 PAD_TS0_D5
#define PAD_TS0_D5 126
#define GPIO_PAD_126 GPIO125
#ifndef BALL_AC14_IS_GPIO
#define BALL_AC14_IS_GPIO 0
#endif
#ifndef PAD_TS0_D5_IS_GPIO
#define PAD_TS0_D5_IS_GPIO BALL_AC14_IS_GPIO
#endif

#define BALL_AA15 PAD_TS0_D4
#define PAD_TS0_D4 125
#define GPIO_PAD_125 GPIO124
#ifndef BALL_AA15_IS_GPIO
#define BALL_AA15_IS_GPIO 0
#endif
#ifndef PAD_TS0_D4_IS_GPIO
#define PAD_TS0_D4_IS_GPIO BALL_AA15_IS_GPIO
#endif

#define BALL_Y15 PAD_TS0_D3
#define PAD_TS0_D3 124
#define GPIO_PAD_124 GPIO123
#ifndef BALL_Y15_IS_GPIO
#define BALL_Y15_IS_GPIO 0
#endif
#ifndef PAD_TS0_D3_IS_GPIO
#define PAD_TS0_D3_IS_GPIO BALL_Y15_IS_GPIO
#endif

#define BALL_Y14 PAD_TS0_D2
#define PAD_TS0_D2 123
#define GPIO_PAD_123 GPIO122
#ifndef BALL_Y14_IS_GPIO
#define BALL_Y14_IS_GPIO 0
#endif
#ifndef PAD_TS0_D2_IS_GPIO
#define PAD_TS0_D2_IS_GPIO BALL_Y14_IS_GPIO
#endif

#define BALL_AA14 PAD_TS0_D1
#define PAD_TS0_D1 122
#define GPIO_PAD_122 GPIO121
#ifndef BALL_AA14_IS_GPIO
#define BALL_AA14_IS_GPIO 0
#endif
#ifndef PAD_TS0_D1_IS_GPIO
#define PAD_TS0_D1_IS_GPIO BALL_AA14_IS_GPIO
#endif

#define BALL_AB14 PAD_TS0_D0
#define PAD_TS0_D0 121
#define GPIO_PAD_121 GPIO120
#ifndef BALL_AB14_IS_GPIO
#define BALL_AB14_IS_GPIO 0
#endif
#ifndef PAD_TS0_D0_IS_GPIO
#define PAD_TS0_D0_IS_GPIO BALL_AB14_IS_GPIO
#endif

#define BALL_AC12 PAD_TS0_VLD
#define PAD_TS0_VLD 130
#define GPIO_PAD_130 GPIO129
#ifndef BALL_AC12_IS_GPIO
#define BALL_AC12_IS_GPIO 0
#endif
#ifndef PAD_TS0_VLD_IS_GPIO
#define PAD_TS0_VLD_IS_GPIO BALL_AC12_IS_GPIO
#endif

#define BALL_AB12 PAD_TS0_SYNC
#define PAD_TS0_SYNC 129
#define GPIO_PAD_129 GPIO128
#ifndef BALL_AB12_IS_GPIO
#define BALL_AB12_IS_GPIO 0
#endif
#ifndef PAD_TS0_SYNC_IS_GPIO
#define PAD_TS0_SYNC_IS_GPIO BALL_AB12_IS_GPIO
#endif

#define BALL_W14 PAD_TS0_CLK
#define PAD_TS0_CLK 120
#define GPIO_PAD_120 GPIO119
#ifndef BALL_W14_IS_GPIO
#define BALL_W14_IS_GPIO 0
#endif
#ifndef PAD_TS0_CLK_IS_GPIO
#define PAD_TS0_CLK_IS_GPIO BALL_W14_IS_GPIO
#endif

#define BALL_AA19 PAD_PCM_CD_N
#define PAD_PCM_CD_N 88
#define GPIO_PAD_88 GPIO87
#ifndef BALL_AA19_IS_GPIO
#define BALL_AA19_IS_GPIO 0
#endif
#ifndef PAD_PCM_CD_N_IS_GPIO
#define PAD_PCM_CD_N_IS_GPIO BALL_AA19_IS_GPIO
#endif

#define BALL_U23 PAD_PCM_REG_N
#define PAD_PCM_REG_N 102
#define GPIO_PAD_102 GPIO101
#ifndef BALL_U23_IS_GPIO
#define BALL_U23_IS_GPIO 0
#endif
#ifndef PAD_PCM_REG_N_IS_GPIO
#define PAD_PCM_REG_N_IS_GPIO BALL_U23_IS_GPIO
#endif

#define BALL_AB22 PAD_PCM_CE_N
#define PAD_PCM_CE_N 89
#define GPIO_PAD_89 GPIO88
#ifndef BALL_AB22_IS_GPIO
#define BALL_AB22_IS_GPIO 0
#endif
#ifndef PAD_PCM_CE_N_IS_GPIO
#define PAD_PCM_CE_N_IS_GPIO BALL_AB22_IS_GPIO
#endif

#define BALL_AB23 PAD_PCM_OE_N
#define PAD_PCM_OE_N 101
#define GPIO_PAD_101 GPIO100
#ifndef BALL_AB23_IS_GPIO
#define BALL_AB23_IS_GPIO 0
#endif
#ifndef PAD_PCM_OE_N_IS_GPIO
#define PAD_PCM_OE_N_IS_GPIO BALL_AB23_IS_GPIO
#endif

#define BALL_AC23 PAD_PCM_IORD_N
#define PAD_PCM_IORD_N 98
#define GPIO_PAD_98 GPIO97
#ifndef BALL_AC23_IS_GPIO
#define BALL_AC23_IS_GPIO 0
#endif
#ifndef PAD_PCM_IORD_N_IS_GPIO
#define PAD_PCM_IORD_N_IS_GPIO BALL_AC23_IS_GPIO
#endif

#define BALL_AA22 PAD_PCM_IOWR_N
#define PAD_PCM_IOWR_N 99
#define GPIO_PAD_99 GPIO98
#ifndef BALL_AA22_IS_GPIO
#define BALL_AA22_IS_GPIO 0
#endif
#ifndef PAD_PCM_IOWR_N_IS_GPIO
#define PAD_PCM_IOWR_N_IS_GPIO BALL_AA22_IS_GPIO
#endif

#define BALL_W21 PAD_PCM_WE_N
#define PAD_PCM_WE_N 105
#define GPIO_PAD_105 GPIO104
#ifndef BALL_W21_IS_GPIO
#define BALL_W21_IS_GPIO 0
#endif
#ifndef PAD_PCM_WE_N_IS_GPIO
#define PAD_PCM_WE_N_IS_GPIO BALL_W21_IS_GPIO
#endif

#define BALL_W22 PAD_PCM_IRQA_N
#define PAD_PCM_IRQA_N 100
#define GPIO_PAD_100 GPIO99
#ifndef BALL_W22_IS_GPIO
#define BALL_W22_IS_GPIO 0
#endif
#ifndef PAD_PCM_IRQA_N_IS_GPIO
#define PAD_PCM_IRQA_N_IS_GPIO BALL_W22_IS_GPIO
#endif

#define BALL_V22 PAD_PCM_RESET
#define PAD_PCM_RESET 103
#define GPIO_PAD_103 GPIO102
#ifndef BALL_V22_IS_GPIO
#define BALL_V22_IS_GPIO 0
#endif
#ifndef PAD_PCM_RESET_IS_GPIO
#define PAD_PCM_RESET_IS_GPIO BALL_V22_IS_GPIO
#endif

#define BALL_V23 PAD_PCM_WAIT_N
#define PAD_PCM_WAIT_N 104
#define GPIO_PAD_104 GPIO103
#ifndef BALL_V23_IS_GPIO
#define BALL_V23_IS_GPIO 0
#endif
#ifndef PAD_PCM_WAIT_N_IS_GPIO
#define PAD_PCM_WAIT_N_IS_GPIO BALL_V23_IS_GPIO
#endif

#define PAD_PCM2_WAIT_N 9999
#ifndef PAD_PCM2_WAIT_N_IS_GPIO
#define PAD_PCM2_WAIT_N_IS_GPIO 0
#endif

#define PAD_PCM2_RESET 9999
#ifndef PAD_PCM2_RESET_IS_GPIO
#define PAD_PCM2_RESET_IS_GPIO 0
#endif

#define PAD_PCM2_CD_N 9999
#ifndef PAD_PCM2_CD_N_IS_GPIO
#define PAD_PCM2_CD_N_IS_GPIO 0
#endif

#define PAD_PCM2_CE_N 9999
#ifndef PAD_PCM2_CE_N_IS_GPIO
#define PAD_PCM2_CE_N_IS_GPIO 0
#endif

#define PAD_PCM2_IRQA_N 9999
#ifndef PAD_PCM2_IRQA_N_IS_GPIO
#define PAD_PCM2_IRQA_N_IS_GPIO 0
#endif

#define BALL_W15 PAD_PCM_A0
#define PAD_PCM_A0 73
#define GPIO_PAD_73 GPIO72
#ifndef BALL_W15_IS_GPIO
#define BALL_W15_IS_GPIO 0
#endif
#ifndef PAD_PCM_A0_IS_GPIO
#define PAD_PCM_A0_IS_GPIO BALL_W15_IS_GPIO
#endif

#define BALL_V15 PAD_PCM_A1
#define PAD_PCM_A1 74
#define GPIO_PAD_74 GPIO73
#ifndef BALL_V15_IS_GPIO
#define BALL_V15_IS_GPIO 0
#endif
#ifndef PAD_PCM_A1_IS_GPIO
#define PAD_PCM_A1_IS_GPIO BALL_V15_IS_GPIO
#endif

#define BALL_W18 PAD_PCM_A2
#define PAD_PCM_A2 75
#define GPIO_PAD_75 GPIO74
#ifndef BALL_W18_IS_GPIO
#define BALL_W18_IS_GPIO 0
#endif
#ifndef PAD_PCM_A2_IS_GPIO
#define PAD_PCM_A2_IS_GPIO BALL_W18_IS_GPIO
#endif

#define BALL_Y18 PAD_PCM_A3
#define PAD_PCM_A3 76
#define GPIO_PAD_76 GPIO75
#ifndef BALL_Y18_IS_GPIO
#define BALL_Y18_IS_GPIO 0
#endif
#ifndef PAD_PCM_A3_IS_GPIO
#define PAD_PCM_A3_IS_GPIO BALL_Y18_IS_GPIO
#endif

#define BALL_AA18 PAD_PCM_A4
#define PAD_PCM_A4 77
#define GPIO_PAD_77 GPIO76
#ifndef BALL_AA18_IS_GPIO
#define BALL_AA18_IS_GPIO 0
#endif
#ifndef PAD_PCM_A4_IS_GPIO
#define PAD_PCM_A4_IS_GPIO BALL_AA18_IS_GPIO
#endif

#define BALL_AC18 PAD_PCM_A5
#define PAD_PCM_A5 78
#define GPIO_PAD_78 GPIO77
#ifndef BALL_AC18_IS_GPIO
#define BALL_AC18_IS_GPIO 0
#endif
#ifndef PAD_PCM_A5_IS_GPIO
#define PAD_PCM_A5_IS_GPIO BALL_AC18_IS_GPIO
#endif

#define BALL_AB18 PAD_PCM_A6
#define PAD_PCM_A6 79
#define GPIO_PAD_79 GPIO78
#ifndef BALL_AB18_IS_GPIO
#define BALL_AB18_IS_GPIO 0
#endif
#ifndef PAD_PCM_A6_IS_GPIO
#define PAD_PCM_A6_IS_GPIO BALL_AB18_IS_GPIO
#endif

#define BALL_AB19 PAD_PCM_A7
#define PAD_PCM_A7 80
#define GPIO_PAD_80 GPIO79
#ifndef BALL_AB19_IS_GPIO
#define BALL_AB19_IS_GPIO 0
#endif
#ifndef PAD_PCM_A7_IS_GPIO
#define PAD_PCM_A7_IS_GPIO BALL_AB19_IS_GPIO
#endif

#define BALL_Y21 PAD_PCM_A8
#define PAD_PCM_A8 81
#define GPIO_PAD_81 GPIO80
#ifndef BALL_Y21_IS_GPIO
#define BALL_Y21_IS_GPIO 0
#endif
#ifndef PAD_PCM_A8_IS_GPIO
#define PAD_PCM_A8_IS_GPIO BALL_Y21_IS_GPIO
#endif

#define BALL_AA21 PAD_PCM_A9
#define PAD_PCM_A9 82
#define GPIO_PAD_82 GPIO81
#ifndef BALL_AA21_IS_GPIO
#define BALL_AA21_IS_GPIO 0
#endif
#ifndef PAD_PCM_A9_IS_GPIO
#define PAD_PCM_A9_IS_GPIO BALL_AA21_IS_GPIO
#endif

#define BALL_AC22 PAD_PCM_A10
#define PAD_PCM_A10 83
#define GPIO_PAD_83 GPIO82
#ifndef BALL_AC22_IS_GPIO
#define BALL_AC22_IS_GPIO 0
#endif
#ifndef PAD_PCM_A10_IS_GPIO
#define PAD_PCM_A10_IS_GPIO BALL_AC22_IS_GPIO
#endif

#define BALL_AA23 PAD_PCM_A11
#define PAD_PCM_A11 84
#define GPIO_PAD_84 GPIO83
#ifndef BALL_AA23_IS_GPIO
#define BALL_AA23_IS_GPIO 0
#endif
#ifndef PAD_PCM_A11_IS_GPIO
#define PAD_PCM_A11_IS_GPIO BALL_AA23_IS_GPIO
#endif

#define BALL_V21 PAD_PCM_A12
#define PAD_PCM_A12 85
#define GPIO_PAD_85 GPIO84
#ifndef BALL_V21_IS_GPIO
#define BALL_V21_IS_GPIO 0
#endif
#ifndef PAD_PCM_A12_IS_GPIO
#define PAD_PCM_A12_IS_GPIO BALL_V21_IS_GPIO
#endif

#define BALL_Y22 PAD_PCM_A13
#define PAD_PCM_A13 86
#define GPIO_PAD_86 GPIO85
#ifndef BALL_Y22_IS_GPIO
#define BALL_Y22_IS_GPIO 0
#endif
#ifndef PAD_PCM_A13_IS_GPIO
#define PAD_PCM_A13_IS_GPIO BALL_Y22_IS_GPIO
#endif

#define BALL_Y23 PAD_PCM_A14
#define PAD_PCM_A14 87
#define GPIO_PAD_87 GPIO86
#ifndef BALL_Y23_IS_GPIO
#define BALL_Y23_IS_GPIO 0
#endif
#ifndef PAD_PCM_A14_IS_GPIO
#define PAD_PCM_A14_IS_GPIO BALL_Y23_IS_GPIO
#endif

#define BALL_U22 PAD_PCM_D0
#define PAD_PCM_D0 90
#define GPIO_PAD_90 GPIO89
#ifndef BALL_U22_IS_GPIO
#define BALL_U22_IS_GPIO 0
#endif
#ifndef PAD_PCM_D0_IS_GPIO
#define PAD_PCM_D0_IS_GPIO BALL_U22_IS_GPIO
#endif

#define BALL_U21 PAD_PCM_D1
#define PAD_PCM_D1 91
#define GPIO_PAD_91 GPIO90
#ifndef BALL_U21_IS_GPIO
#define BALL_U21_IS_GPIO 0
#endif
#ifndef PAD_PCM_D1_IS_GPIO
#define PAD_PCM_D1_IS_GPIO BALL_U21_IS_GPIO
#endif

#define BALL_U20 PAD_PCM_D2
#define PAD_PCM_D2 92
#define GPIO_PAD_92 GPIO91
#ifndef BALL_U20_IS_GPIO
#define BALL_U20_IS_GPIO 0
#endif
#ifndef PAD_PCM_D2_IS_GPIO
#define PAD_PCM_D2_IS_GPIO BALL_U20_IS_GPIO
#endif

#define BALL_Y19 PAD_PCM_D3
#define PAD_PCM_D3 93
#define GPIO_PAD_93 GPIO92
#ifndef BALL_Y19_IS_GPIO
#define BALL_Y19_IS_GPIO 0
#endif
#ifndef PAD_PCM_D3_IS_GPIO
#define PAD_PCM_D3_IS_GPIO BALL_Y19_IS_GPIO
#endif

#define BALL_W19 PAD_PCM_D4
#define PAD_PCM_D4 94
#define GPIO_PAD_94 GPIO93
#ifndef BALL_W19_IS_GPIO
#define BALL_W19_IS_GPIO 0
#endif
#ifndef PAD_PCM_D4_IS_GPIO
#define PAD_PCM_D4_IS_GPIO BALL_W19_IS_GPIO
#endif

#define BALL_V19 PAD_PCM_D5
#define PAD_PCM_D5 95
#define GPIO_PAD_95 GPIO94
#ifndef BALL_V19_IS_GPIO
#define BALL_V19_IS_GPIO 0
#endif
#ifndef PAD_PCM_D5_IS_GPIO
#define PAD_PCM_D5_IS_GPIO BALL_V19_IS_GPIO
#endif

#define BALL_V18 PAD_PCM_D6
#define PAD_PCM_D6 96
#define GPIO_PAD_96 GPIO95
#ifndef BALL_V18_IS_GPIO
#define BALL_V18_IS_GPIO 0
#endif
#ifndef PAD_PCM_D6_IS_GPIO
#define PAD_PCM_D6_IS_GPIO BALL_V18_IS_GPIO
#endif

#define BALL_AB21 PAD_PCM_D7
#define PAD_PCM_D7 97
#define GPIO_PAD_97 GPIO96
#ifndef BALL_AB21_IS_GPIO
#define BALL_AB21_IS_GPIO 0
#endif
#ifndef PAD_PCM_D7_IS_GPIO
#define PAD_PCM_D7_IS_GPIO BALL_AB21_IS_GPIO
#endif

#define BALL_Y24 PAD_TS1_D7
#define PAD_TS1_D7 139
#define GPIO_PAD_139 GPIO138
#ifndef BALL_Y24_IS_GPIO
#define BALL_Y24_IS_GPIO 0
#endif
#ifndef PAD_TS1_D7_IS_GPIO
#define PAD_TS1_D7_IS_GPIO BALL_Y24_IS_GPIO
#endif

#define BALL_W24 PAD_TS1_D6
#define PAD_TS1_D6 138
#define GPIO_PAD_138 GPIO137
#ifndef BALL_W24_IS_GPIO
#define BALL_W24_IS_GPIO 0
#endif
#ifndef PAD_TS1_D6_IS_GPIO
#define PAD_TS1_D6_IS_GPIO BALL_W24_IS_GPIO
#endif

#define BALL_V24 PAD_TS1_D5
#define PAD_TS1_D5 137
#define GPIO_PAD_137 GPIO136
#ifndef BALL_V24_IS_GPIO
#define BALL_V24_IS_GPIO 0
#endif
#ifndef PAD_TS1_D5_IS_GPIO
#define PAD_TS1_D5_IS_GPIO BALL_V24_IS_GPIO
#endif

#define BALL_V26 PAD_TS1_D4
#define PAD_TS1_D4 136
#define GPIO_PAD_136 GPIO135
#ifndef BALL_V26_IS_GPIO
#define BALL_V26_IS_GPIO 0
#endif
#ifndef PAD_TS1_D4_IS_GPIO
#define PAD_TS1_D4_IS_GPIO BALL_V26_IS_GPIO
#endif

#define BALL_U26 PAD_TS1_D3
#define PAD_TS1_D3 135
#define GPIO_PAD_135 GPIO134
#ifndef BALL_U26_IS_GPIO
#define BALL_U26_IS_GPIO 0
#endif
#ifndef PAD_TS1_D3_IS_GPIO
#define PAD_TS1_D3_IS_GPIO BALL_U26_IS_GPIO
#endif

#define BALL_U24 PAD_TS1_D2
#define PAD_TS1_D2 134
#define GPIO_PAD_134 GPIO133
#ifndef BALL_U24_IS_GPIO
#define BALL_U24_IS_GPIO 0
#endif
#ifndef PAD_TS1_D2_IS_GPIO
#define PAD_TS1_D2_IS_GPIO BALL_U24_IS_GPIO
#endif

#define BALL_T26 PAD_TS1_D1
#define PAD_TS1_D1 133
#define GPIO_PAD_133 GPIO132
#ifndef BALL_T26_IS_GPIO
#define BALL_T26_IS_GPIO 0
#endif
#ifndef PAD_TS1_D1_IS_GPIO
#define PAD_TS1_D1_IS_GPIO BALL_T26_IS_GPIO
#endif

#define BALL_T25 PAD_TS1_D0
#define PAD_TS1_D0 132
#define GPIO_PAD_132 GPIO131
#ifndef BALL_T25_IS_GPIO
#define BALL_T25_IS_GPIO 0
#endif
#ifndef PAD_TS1_D0_IS_GPIO
#define PAD_TS1_D0_IS_GPIO BALL_T25_IS_GPIO
#endif

#define BALL_U25 PAD_TS1_VLD
#define PAD_TS1_VLD 141
#define GPIO_PAD_141 GPIO140
#ifndef BALL_U25_IS_GPIO
#define BALL_U25_IS_GPIO 0
#endif
#ifndef PAD_TS1_VLD_IS_GPIO
#define PAD_TS1_VLD_IS_GPIO BALL_U25_IS_GPIO
#endif

#define BALL_T24 PAD_TS1_SYNC
#define PAD_TS1_SYNC 140
#define GPIO_PAD_140 GPIO139
#ifndef BALL_T24_IS_GPIO
#define BALL_T24_IS_GPIO 0
#endif
#ifndef PAD_TS1_SYNC_IS_GPIO
#define PAD_TS1_SYNC_IS_GPIO BALL_T24_IS_GPIO
#endif

#define BALL_V25 PAD_TS1_CLK
#define PAD_TS1_CLK 131
#define GPIO_PAD_131 GPIO130
#ifndef BALL_V25_IS_GPIO
#define BALL_V25_IS_GPIO 0
#endif
#ifndef PAD_TS1_CLK_IS_GPIO
#define PAD_TS1_CLK_IS_GPIO BALL_V25_IS_GPIO
#endif

#define PAD_TS2_D0 9999
#ifndef PAD_TS2_D0_IS_GPIO
#define PAD_TS2_D0_IS_GPIO 0
#endif

#define PAD_TS2_VLD 9999
#ifndef PAD_TS2_VLD_IS_GPIO
#define PAD_TS2_VLD_IS_GPIO 0
#endif

#define PAD_TS2_SYNC 9999
#ifndef PAD_TS2_SYNC_IS_GPIO
#define PAD_TS2_SYNC_IS_GPIO 0
#endif

#define PAD_TS2_CLK 9999
#ifndef PAD_TS2_CLK_IS_GPIO
#define PAD_TS2_CLK_IS_GPIO 0
#endif

#define BALL_C15 PAD_TCON4
#define PAD_TCON4 115
#define GPIO_PAD_115 GPIO114
#ifndef BALL_C15_IS_GPIO
#define BALL_C15_IS_GPIO 0
#endif
#ifndef PAD_TCON4_IS_GPIO
#define PAD_TCON4_IS_GPIO BALL_C15_IS_GPIO
#endif

#define BALL_B15 PAD_TCON3
#define PAD_TCON3 114
#define GPIO_PAD_114 GPIO113
#ifndef BALL_B15_IS_GPIO
#define BALL_B15_IS_GPIO 0
#endif
#ifndef PAD_TCON3_IS_GPIO
#define PAD_TCON3_IS_GPIO BALL_B15_IS_GPIO
#endif

#define BALL_C16 PAD_TCON2
#define PAD_TCON2 113
#define GPIO_PAD_113 GPIO112
#ifndef BALL_C16_IS_GPIO
#define BALL_C16_IS_GPIO 0
#endif
#ifndef PAD_TCON2_IS_GPIO
#define PAD_TCON2_IS_GPIO BALL_C16_IS_GPIO
#endif

#define BALL_B16 PAD_TCON1
#define PAD_TCON1 112
#define GPIO_PAD_112 GPIO111
#ifndef BALL_B16_IS_GPIO
#define BALL_B16_IS_GPIO 0
#endif
#ifndef PAD_TCON1_IS_GPIO
#define PAD_TCON1_IS_GPIO BALL_B16_IS_GPIO
#endif

#define BALL_A16 PAD_TCON0
#define PAD_TCON0 111
#define GPIO_PAD_111 GPIO110
#ifndef BALL_A16_IS_GPIO
#define BALL_A16_IS_GPIO 0
#endif
#ifndef PAD_TCON0_IS_GPIO
#define PAD_TCON0_IS_GPIO BALL_A16_IS_GPIO
#endif

#define BALL_E15 PAD_I2S_IN_DIN1
#define PAD_I2S_IN_DIN1 55
#define GPIO_PAD_55 GPIO54
#ifndef BALL_E15_IS_GPIO
#define BALL_E15_IS_GPIO 0
#endif
#ifndef PAD_I2S_IN_DIN1_IS_GPIO
#define PAD_I2S_IN_DIN1_IS_GPIO BALL_E15_IS_GPIO
#endif

#define BALL_E14 PAD_I2S_IN_DIN0
#define PAD_I2S_IN_DIN0 54
#define GPIO_PAD_54 GPIO53
#ifndef BALL_E14_IS_GPIO
#define BALL_E14_IS_GPIO 0
#endif
#ifndef PAD_I2S_IN_DIN0_IS_GPIO
#define PAD_I2S_IN_DIN0_IS_GPIO BALL_E14_IS_GPIO
#endif

#define BALL_D15 PAD_I2S_IN_WCK
#define PAD_I2S_IN_WCK 57
#define GPIO_PAD_57 GPIO56
#ifndef BALL_D15_IS_GPIO
#define BALL_D15_IS_GPIO 0
#endif
#ifndef PAD_I2S_IN_WCK_IS_GPIO
#define PAD_I2S_IN_WCK_IS_GPIO BALL_D15_IS_GPIO
#endif

#define BALL_D16 PAD_I2S_IN_MCK
#define PAD_I2S_IN_MCK 56
#define GPIO_PAD_56 GPIO55
#ifndef BALL_D16_IS_GPIO
#define BALL_D16_IS_GPIO 0
#endif
#ifndef PAD_I2S_IN_MCK_IS_GPIO
#define PAD_I2S_IN_MCK_IS_GPIO BALL_D16_IS_GPIO
#endif

#define BALL_E16 PAD_I2S_IN_BCK
#define PAD_I2S_IN_BCK 53
#define GPIO_PAD_53 GPIO52
#ifndef BALL_E16_IS_GPIO
#define BALL_E16_IS_GPIO 0
#endif
#ifndef PAD_I2S_IN_BCK_IS_GPIO
#define PAD_I2S_IN_BCK_IS_GPIO BALL_E16_IS_GPIO
#endif

#define BALL_C14 PAD_DDCR_CK
#define PAD_DDCR_CK 37
#define GPIO_PAD_37 GPIO36
#ifndef BALL_C14_IS_GPIO
#define BALL_C14_IS_GPIO 0
#endif
#ifndef PAD_DDCR_CK_IS_GPIO
#define PAD_DDCR_CK_IS_GPIO BALL_C14_IS_GPIO
#endif

#define BALL_B14 PAD_DDCR_DA
#define PAD_DDCR_DA 38
#define GPIO_PAD_38 GPIO37
#ifndef BALL_B14_IS_GPIO
#define BALL_B14_IS_GPIO 0
#endif
#ifndef PAD_DDCR_DA_IS_GPIO
#define PAD_DDCR_DA_IS_GPIO BALL_B14_IS_GPIO
#endif

#define BALL_B13 PAD_PWM0
#define PAD_PWM0 106
#define GPIO_PAD_106 GPIO105
#ifndef BALL_B13_IS_GPIO
#define BALL_B13_IS_GPIO 0
#endif
#ifndef PAD_PWM0_IS_GPIO
#define PAD_PWM0_IS_GPIO BALL_B13_IS_GPIO
#endif

#define BALL_C13 PAD_PWM1
#define PAD_PWM1 107
#define GPIO_PAD_107 GPIO106
#ifndef BALL_C13_IS_GPIO
#define BALL_C13_IS_GPIO 0
#endif
#ifndef PAD_PWM1_IS_GPIO
#define PAD_PWM1_IS_GPIO BALL_C13_IS_GPIO
#endif

#define BALL_G10 PAD_PWM2
#define PAD_PWM2 108
#define GPIO_PAD_108 GPIO107
#ifndef BALL_G10_IS_GPIO
#define BALL_G10_IS_GPIO 0
#endif
#ifndef PAD_PWM2_IS_GPIO
#define PAD_PWM2_IS_GPIO BALL_G10_IS_GPIO
#endif

#define BALL_G9 PAD_GPIO0
#define PAD_GPIO0 39
#define GPIO_PAD_39 GPIO38
#ifndef BALL_G9_IS_GPIO
#define BALL_G9_IS_GPIO 0
#endif
#ifndef PAD_GPIO0_IS_GPIO
#define PAD_GPIO0_IS_GPIO BALL_G9_IS_GPIO
#endif

#define BALL_D14 PAD_GPIO1
#define PAD_GPIO1 40
#define GPIO_PAD_40 GPIO39
#ifndef BALL_D14_IS_GPIO
#define BALL_D14_IS_GPIO 0
#endif
#ifndef PAD_GPIO1_IS_GPIO
#define PAD_GPIO1_IS_GPIO BALL_D14_IS_GPIO
#endif

#define BALL_E13 PAD_LD_SPI_CK
#define PAD_LD_SPI_CK 64
#define GPIO_PAD_64 GPIO63
#ifndef BALL_E13_IS_GPIO
#define BALL_E13_IS_GPIO 0
#endif
#ifndef PAD_LD_SPI_CK_IS_GPIO
#define PAD_LD_SPI_CK_IS_GPIO BALL_E13_IS_GPIO
#endif

#define BALL_E12 PAD_LD_SPI_MOSI
#define PAD_LD_SPI_MOSI 67
#define GPIO_PAD_67 GPIO66
#ifndef BALL_E12_IS_GPIO
#define BALL_E12_IS_GPIO 0
#endif
#ifndef PAD_LD_SPI_MOSI_IS_GPIO
#define PAD_LD_SPI_MOSI_IS_GPIO BALL_E12_IS_GPIO
#endif

#define BALL_D13 PAD_LD_SPI_CS
#define PAD_LD_SPI_CS 65
#define GPIO_PAD_65 GPIO64
#ifndef BALL_D13_IS_GPIO
#define BALL_D13_IS_GPIO 0
#endif
#ifndef PAD_LD_SPI_CS_IS_GPIO
#define PAD_LD_SPI_CS_IS_GPIO BALL_D13_IS_GPIO
#endif

#define BALL_D12 PAD_LD_SPI_MISO
#define PAD_LD_SPI_MISO 66
#define GPIO_PAD_66 GPIO65
#ifndef BALL_D12_IS_GPIO
#define BALL_D12_IS_GPIO 0
#endif
#ifndef PAD_LD_SPI_MISO_IS_GPIO
#define PAD_LD_SPI_MISO_IS_GPIO BALL_D12_IS_GPIO
#endif

#define BALL_A12 PAD_I2S_OUT_MCK
#define PAD_I2S_OUT_MCK 59
#define GPIO_PAD_59 GPIO58
#ifndef BALL_A12_IS_GPIO
#define BALL_A12_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_MCK_IS_GPIO
#define PAD_I2S_OUT_MCK_IS_GPIO BALL_A12_IS_GPIO
#endif

#define BALL_C12 PAD_I2S_OUT_BCK
#define PAD_I2S_OUT_BCK 58
#define GPIO_PAD_58 GPIO57
#ifndef BALL_C12_IS_GPIO
#define BALL_C12_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_BCK_IS_GPIO
#define PAD_I2S_OUT_BCK_IS_GPIO BALL_C12_IS_GPIO
#endif

#define BALL_A11 PAD_I2S_OUT_WCK
#define PAD_I2S_OUT_WCK 63
#define GPIO_PAD_63 GPIO62
#ifndef BALL_A11_IS_GPIO
#define BALL_A11_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_WCK_IS_GPIO
#define PAD_I2S_OUT_WCK_IS_GPIO BALL_A11_IS_GPIO
#endif

#define BALL_B11 PAD_I2S_OUT_SD0
#define PAD_I2S_OUT_SD0 60
#define GPIO_PAD_60 GPIO59
#ifndef BALL_B11_IS_GPIO
#define BALL_B11_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_SD0_IS_GPIO
#define PAD_I2S_OUT_SD0_IS_GPIO BALL_B11_IS_GPIO
#endif

#define BALL_C11 PAD_I2S_OUT_SD1
#define PAD_I2S_OUT_SD1 61
#define GPIO_PAD_61 GPIO60
#ifndef BALL_C11_IS_GPIO
#define BALL_C11_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_SD1_IS_GPIO
#define PAD_I2S_OUT_SD1_IS_GPIO BALL_C11_IS_GPIO
#endif

#define BALL_B10 PAD_I2S_OUT_SD2
#define PAD_I2S_OUT_SD2 62
#define GPIO_PAD_62 GPIO61
#ifndef BALL_B10_IS_GPIO
#define BALL_B10_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_SD2_IS_GPIO
#define PAD_I2S_OUT_SD2_IS_GPIO BALL_B10_IS_GPIO
#endif

#define PAD_SPDIF_IN 9999
#ifndef PAD_SPDIF_IN_IS_GPIO
#define PAD_SPDIF_IN_IS_GPIO 0
#endif

#define BALL_C10 PAD_SPDIF_OUT
#define PAD_SPDIF_OUT 110
#define GPIO_PAD_110 GPIO109
#ifndef BALL_C10_IS_GPIO
#define BALL_C10_IS_GPIO 0
#endif
#ifndef PAD_SPDIF_OUT_IS_GPIO
#define PAD_SPDIF_OUT_IS_GPIO BALL_C10_IS_GPIO
#endif

#define BALL_C7 PAD_SAR0
#define PAD_SAR0 26
#define GPIO_PAD_26 GPIO25
#ifndef BALL_C7_IS_GPIO
#define BALL_C7_IS_GPIO 0
#endif
#ifndef PAD_SAR0_IS_GPIO
#define PAD_SAR0_IS_GPIO BALL_C7_IS_GPIO
#endif

#define BALL_B6 PAD_SAR1
#define PAD_SAR1 27
#define GPIO_PAD_27 GPIO26
#ifndef BALL_B6_IS_GPIO
#define BALL_B6_IS_GPIO 0
#endif
#ifndef PAD_SAR1_IS_GPIO
#define PAD_SAR1_IS_GPIO BALL_B6_IS_GPIO
#endif

#define BALL_C6 PAD_SAR2
#define PAD_SAR2 28
#define GPIO_PAD_28 GPIO27
#ifndef BALL_C6_IS_GPIO
#define BALL_C6_IS_GPIO 0
#endif
#ifndef PAD_SAR2_IS_GPIO
#define PAD_SAR2_IS_GPIO BALL_C6_IS_GPIO
#endif

#define PAD_SAR3 9999
#ifndef PAD_SAR3_IS_GPIO
#define PAD_SAR3_IS_GPIO 0
#endif

#define PAD_SAR4 9999
#ifndef PAD_SAR4_IS_GPIO
#define PAD_SAR4_IS_GPIO 0
#endif

#define BALL_B5 PAD_VPLUGIN
#define PAD_VPLUGIN 31
#define GPIO_PAD_31 GPIO30
#ifndef BALL_B5_IS_GPIO
#define BALL_B5_IS_GPIO 0
#endif
#ifndef PAD_VPLUGIN_IS_GPIO
#define PAD_VPLUGIN_IS_GPIO BALL_B5_IS_GPIO
#endif

#define BALL_P6 PADA_HSYNC1
#define PADA_HSYNC1 155
#define GPIO_PAD_155 GPIO154
#ifndef BALL_P6_IS_GPIO
#define BALL_P6_IS_GPIO 0
#endif
#ifndef PADA_HSYNC1_IS_GPIO
#define PADA_HSYNC1_IS_GPIO BALL_P6_IS_GPIO
#endif

#define BALL_P7 PADA_VSYNC1
#define PADA_VSYNC1 157
#define GPIO_PAD_157 GPIO156
#ifndef BALL_P7_IS_GPIO
#define BALL_P7_IS_GPIO 0
#endif
#ifndef PADA_VSYNC1_IS_GPIO
#define PADA_VSYNC1_IS_GPIO BALL_P7_IS_GPIO
#endif

// PADS group name to index
#define PADS_PCMCONFIG_MODE1        1223
#define PADS_PCMCONFIG_MODE2        1224
#define PADS_PCMCONFIG1_MODE1       1225
#define PADS_PCMCONFIG1_MODE2       1226
#define PADS_PCMCONFIG1_MODE3       1227
#define PADS_PCM2CONFIG_MODE1       1228
#define PADS_PCM2CONFIG_MODE2       1229
#define PADS_PCM2CONFIG_MODE3       1230
#define PADS_PCM2CONFIG1_MODE1      1231
#define PADS_PCM2CONFIG1_MODE2      1232
#define PADS_ET_MODE1               1233
#define PADS_ET_MODE2               1234
#define PADS_DDCR                   1235
#define PADS_DDCR2                  1236
#define PADS_PCM                    1237

// chip capbilities
#define CHIP_HAS_BT656_IN           0
#define CHIP_HAS_TS0                1
#define CHIP_HAS_TS1                0
#define CHIP_HAS_LVDS_10BIT_X2      1
#define CHIP_HAS_LVDS_8BIT_X2       1
#define CHIP_HAS_LVDS_8BIT_X1       1
#define CHIP_HAS_CIMAX              0
#define CHIP_HAS_USB_P0             1
#define CHIP_HAS_USB_P1             1
#define CHIP_HAS_USBVBUS0           0
#define CHIP_HAS_USBVBUS1           0
#define CHIP_HAS_UART1_MODE1        1
#define CHIP_HAS_UART1_MODE2        1
#define CHIP_HAS_UART1_MODE3        1
#define CHIP_HAS_PCMCIA1            0
#define CHIP_HAS_PCMCIA2            0
#define CHIP_HAS_PCMCIA             0
#define CHIP_HAS_UART2_MODE1        1
#define CHIP_HAS_UART2_MODE2        1
#define CHIP_HAS_UART2_MODE3        1
#define CHIP_HAS_RGB_A              1
#define CHIP_HAS_RGB_B              1
#define CHIP_HAS_RGB_C              1
#define CHIP_HAS_HDMI_A             1
#define CHIP_HAS_HDMI_B             1
#define CHIP_HAS_HDMI_C             1
#define CHIP_HAS_SPI_CZ1            1
#define CHIP_HAS_SPI_CZ2            0
#define CHIP_HAS_SPI_CZ3            0
#define CHIP_HAS_DDCR               1
#define CHIP_HAS_DDCR2              1
#define CHIP_HAS_TCON               1
#define CHIP_HAS_ET_MODE0_MII       1
#define CHIP_HAS_ET_MODE0_RMII      1
#define CHIP_HAS_ET_MODE1_MII       1
#define CHIP_HAS_ET_MODE1_RMII      1
#define CHIP_HAS_ET_MODE2_MII       1
#define CHIP_HAS_ET_MODE2_RMII      1
#define CHIP_HAS_I2S_IN             0
#define CHIP_HAS_I2S_OUT            0
#define CHIP_HAS_SPDIF_IN           0
#define CHIP_HAS_SPDIF_OUT          0
#define CHIP_HAS_DDR_A_CMD          1
#define CHIP_HAS_DDR_A_DATA         1
#define CHIP_HAS_DDR_B_CMD          1
#define CHIP_HAS_DDR_B_DATA         1
#define CHIP_USE_PCM_CDN_IN_PCM2    0
#define CHIP_USE_I2S_IN_IN_PCM      0
#define CHIP_USE_I2S_OUT_IN_PCM     0
#define CHIP_USE_SPDIF_IN_IN_PCM    0
#define CHIP_USE_SPDIF_OUT_IN_PCM   0
#define CHIP_USE_IIC_IN_DDCR2       0
#define CHIP_USE_PWM2_IN_GPIO14     0
#define CHIP_USE_PWM3_IN_GPIO15     0

// chip additional information
#define CHIP_FAMILY_TYPE            CHIP_FAMILY_M7322

#endif /* _MSD95NRTW8_H_*/
