#!bin/bash

################################################################################
#
#  mk_config
#
#  Copyright (c) 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
################################################################################

################################################################################
# NOTE: You must fill in the following with the path to a copy of an
#       linaro-aarch64_linux-2014.09
################################################################################
#CROSS_COMPILER_PATH="/gcc/linux-x86/arm/linaro-4.9.3-2014.11-arm-linux-gnueabihf/bin"
KERNEL_CONFIG=${PWD}/arch/arm/configs/t31_user_defconfig
GENLINK_KERNEL=${PWD}/genlink_kernel.sh
CROSS_COMPILER_PATH=../../../../prebuilts/gcc/linux-x86/arm/linaro-4.9.3-2014.11-arm-linux-gnueabihf
