/* SPDX-License-Identifier: GPL-2.0-only OR BSD-3-Clause */
/******************************************************************************
 *
 * This file is provided under a dual license.  When you use or
 * distribute this software, you may choose to be licensed under
 * version 2 of the GNU General Public License ("GPLv2 License")
 * or BSD License.
 *
 * GPLv2 License
 *
 * Copyright(C) 2019 MediaTek Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of version 2 of the GNU General Public License as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See http://www.gnu.org/licenses/gpl-2.0.html for more details.
 *
 * BSD LICENSE
 *
 * Copyright(C) 2019 MediaTek Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *****************************************************************************/

// This file is generated by script, please do not edit it directly
#ifndef _MSD92LJBN_H_
#define _MSD92LJBN_H_

#define PAD_NC 9999
#define PAD_GND 0

#define PAD_RX0N_A 9999
#ifndef PAD_RX0N_A_IS_GPIO
#define PAD_RX0N_A_IS_GPIO 0
#endif

#define PAD_RXCN_A 9999
#ifndef PAD_RXCN_A_IS_GPIO
#define PAD_RXCN_A_IS_GPIO 0
#endif

#define PAD_RX0P_A 9999
#ifndef PAD_RX0P_A_IS_GPIO
#define PAD_RX0P_A_IS_GPIO 0
#endif

#define PAD_RXCP_A 9999
#ifndef PAD_RXCP_A_IS_GPIO
#define PAD_RXCP_A_IS_GPIO 0
#endif

#define PAD_RX2N_A 9999
#ifndef PAD_RX2N_A_IS_GPIO
#define PAD_RX2N_A_IS_GPIO 0
#endif

#define PAD_RX1N_A 9999
#ifndef PAD_RX1N_A_IS_GPIO
#define PAD_RX1N_A_IS_GPIO 0
#endif

#define PAD_RX2P_A 9999
#ifndef PAD_RX2P_A_IS_GPIO
#define PAD_RX2P_A_IS_GPIO 0
#endif

#define PAD_RX1P_A 9999
#ifndef PAD_RX1P_A_IS_GPIO
#define PAD_RX1P_A_IS_GPIO 0
#endif

#define PADA_BIN0M 9999
#ifndef PADA_BIN0M_IS_GPIO
#define PADA_BIN0M_IS_GPIO 0
#endif

#define PIN_132 PADA_HSYNC0
#define PADA_HSYNC0 172
#define GPIO_PAD_172 GPIO171
#ifndef PIN_132_IS_GPIO
#define PIN_132_IS_GPIO 0
#endif
#ifndef PADA_HSYNC0_IS_GPIO
#define PADA_HSYNC0_IS_GPIO PIN_132_IS_GPIO
#endif

#define PIN_133 PADA_BIN0P
#define PADA_BIN0P 190
#define GPIO_PAD_190 GPIO189
#ifndef PIN_133_IS_GPIO
#define PIN_133_IS_GPIO 0
#endif
#ifndef PADA_BIN0P_IS_GPIO
#define PADA_BIN0P_IS_GPIO PIN_133_IS_GPIO
#endif

#define PIN_134 PADA_GIN0P
#define PADA_GIN0P 184
#define GPIO_PAD_184 GPIO183
#ifndef PIN_134_IS_GPIO
#define PIN_134_IS_GPIO 0
#endif
#ifndef PADA_GIN0P_IS_GPIO
#define PADA_GIN0P_IS_GPIO PIN_134_IS_GPIO
#endif

#define PIN_135 PADA_GIN0M
#define PADA_GIN0M 187
#define GPIO_PAD_187 GPIO186
#ifndef PIN_135_IS_GPIO
#define PIN_135_IS_GPIO 0
#endif
#ifndef PADA_GIN0M_IS_GPIO
#define PADA_GIN0M_IS_GPIO PIN_135_IS_GPIO
#endif

#define PIN_136 PADA_RIN0P
#define PADA_RIN0P 178
#define GPIO_PAD_178 GPIO177
#ifndef PIN_136_IS_GPIO
#define PIN_136_IS_GPIO 0
#endif
#ifndef PADA_RIN0P_IS_GPIO
#define PADA_RIN0P_IS_GPIO PIN_136_IS_GPIO
#endif

#define PIN_137 PADA_VSYNC0
#define PADA_VSYNC0 175
#define GPIO_PAD_175 GPIO174
#ifndef PIN_137_IS_GPIO
#define PIN_137_IS_GPIO 0
#endif
#ifndef PADA_VSYNC0_IS_GPIO
#define PADA_VSYNC0_IS_GPIO PIN_137_IS_GPIO
#endif

#define PADA_RIN0M 9999
#ifndef PADA_RIN0M_IS_GPIO
#define PADA_RIN0M_IS_GPIO 0
#endif

#define PADA_HSYNC1 9999
#ifndef PADA_HSYNC1_IS_GPIO
#define PADA_HSYNC1_IS_GPIO 0
#endif

#define PADA_BIN1P 9999
#ifndef PADA_BIN1P_IS_GPIO
#define PADA_BIN1P_IS_GPIO 0
#endif

#define PADA_BIN1M 9999
#ifndef PADA_BIN1M_IS_GPIO
#define PADA_BIN1M_IS_GPIO 0
#endif

#define PADA_GIN1P 9999
#ifndef PADA_GIN1P_IS_GPIO
#define PADA_GIN1P_IS_GPIO 0
#endif

#define PADA_GIN1M 9999
#ifndef PADA_GIN1M_IS_GPIO
#define PADA_GIN1M_IS_GPIO 0
#endif

#define PADA_RIN1P 9999
#ifndef PADA_RIN1P_IS_GPIO
#define PADA_RIN1P_IS_GPIO 0
#endif

#define PADA_RIN1M 9999
#ifndef PADA_RIN1M_IS_GPIO
#define PADA_RIN1M_IS_GPIO 0
#endif

#define PADA_VSYNC1 9999
#ifndef PADA_VSYNC1_IS_GPIO
#define PADA_VSYNC1_IS_GPIO 0
#endif

#define PADA_BIN2M 9999
#ifndef PADA_BIN2M_IS_GPIO
#define PADA_BIN2M_IS_GPIO 0
#endif

#define PADA_HSYNC2 9999
#ifndef PADA_HSYNC2_IS_GPIO
#define PADA_HSYNC2_IS_GPIO 0
#endif

#define PADA_BIN2P 9999
#ifndef PADA_BIN2P_IS_GPIO
#define PADA_BIN2P_IS_GPIO 0
#endif

#define PADA_GIN2P 9999
#ifndef PADA_GIN2P_IS_GPIO
#define PADA_GIN2P_IS_GPIO 0
#endif

#define PADA_GIN2M 9999
#ifndef PADA_GIN2M_IS_GPIO
#define PADA_GIN2M_IS_GPIO 0
#endif

#define PADA_RIN2P 9999
#ifndef PADA_RIN2P_IS_GPIO
#define PADA_RIN2P_IS_GPIO 0
#endif

#define PADA_VSYNC2 9999
#ifndef PADA_VSYNC2_IS_GPIO
#define PADA_VSYNC2_IS_GPIO 0
#endif

#define PADA_RIN2M 9999
#ifndef PADA_RIN2M_IS_GPIO
#define PADA_RIN2M_IS_GPIO 0
#endif

#define PAD_GPIO30 9999
#ifndef PAD_GPIO30_IS_GPIO
#define PAD_GPIO30_IS_GPIO 0
#endif

#define PAD_GPIO31 9999
#ifndef PAD_GPIO31_IS_GPIO
#define PAD_GPIO31_IS_GPIO 0
#endif

#define PAD_GPIO32 9999
#ifndef PAD_GPIO32_IS_GPIO
#define PAD_GPIO32_IS_GPIO 0
#endif

#define PAD_GPIO33 9999
#ifndef PAD_GPIO33_IS_GPIO
#define PAD_GPIO33_IS_GPIO 0
#endif

#define PAD_GPIO34 9999
#ifndef PAD_GPIO34_IS_GPIO
#define PAD_GPIO34_IS_GPIO 0
#endif

#define PAD_GPIO35 9999
#ifndef PAD_GPIO35_IS_GPIO
#define PAD_GPIO35_IS_GPIO 0
#endif

#define PIN_143 PAD_LINEIN_L1
#define PAD_LINEIN_L1 196
#define GPIO_PAD_196 GPIO195
#ifndef PIN_143_IS_GPIO
#define PIN_143_IS_GPIO 0
#endif
#ifndef PAD_LINEIN_L1_IS_GPIO
#define PAD_LINEIN_L1_IS_GPIO PIN_143_IS_GPIO
#endif

#define PIN_144 PAD_LINEIN_R1
#define PAD_LINEIN_R1 197
#define GPIO_PAD_197 GPIO196
#ifndef PIN_144_IS_GPIO
#define PIN_144_IS_GPIO 0
#endif
#ifndef PAD_LINEIN_R1_IS_GPIO
#define PAD_LINEIN_R1_IS_GPIO PIN_144_IS_GPIO
#endif

#define PAD_LINEIN_R2 9999
#ifndef PAD_LINEIN_R2_IS_GPIO
#define PAD_LINEIN_R2_IS_GPIO 0
#endif

#define PAD_LINEIN_L2 9999
#ifndef PAD_LINEIN_L2_IS_GPIO
#define PAD_LINEIN_L2_IS_GPIO 0
#endif

#define PAD_LINEIN_R3 9999
#ifndef PAD_LINEIN_R3_IS_GPIO
#define PAD_LINEIN_R3_IS_GPIO 0
#endif

#define PAD_LINEIN_L3 9999
#ifndef PAD_LINEIN_L3_IS_GPIO
#define PAD_LINEIN_L3_IS_GPIO 0
#endif

#define PAD_LINEIN_L4 9999
#ifndef PAD_LINEIN_L4_IS_GPIO
#define PAD_LINEIN_L4_IS_GPIO 0
#endif

#define PAD_LINEIN_R4 9999
#ifndef PAD_LINEIN_R4_IS_GPIO
#define PAD_LINEIN_R4_IS_GPIO 0
#endif

#define PAD_LINEIN_L5 9999
#ifndef PAD_LINEIN_L5_IS_GPIO
#define PAD_LINEIN_L5_IS_GPIO 0
#endif

#define PAD_LINEIN_R5 9999
#ifndef PAD_LINEIN_R5_IS_GPIO
#define PAD_LINEIN_R5_IS_GPIO 0
#endif

#define PAD_GPIO25 9999
#ifndef PAD_GPIO25_IS_GPIO
#define PAD_GPIO25_IS_GPIO 0
#endif

#define PAD_GPIO24 9999
#ifndef PAD_GPIO24_IS_GPIO
#define PAD_GPIO24_IS_GPIO 0
#endif

#define PIN_5 PAD_GPIO0
#define PAD_GPIO0 45
#define GPIO_PAD_45 GPIO44
#ifndef PIN_5_IS_GPIO
#define PIN_5_IS_GPIO 0
#endif
#ifndef PAD_GPIO0_IS_GPIO
#define PAD_GPIO0_IS_GPIO PIN_5_IS_GPIO
#endif

#define PIN_6 PAD_GPIO1
#define PAD_GPIO1 46
#define GPIO_PAD_46 GPIO45
#ifndef PIN_6_IS_GPIO
#define PIN_6_IS_GPIO 0
#endif
#ifndef PAD_GPIO1_IS_GPIO
#define PAD_GPIO1_IS_GPIO PIN_6_IS_GPIO
#endif

#define PAD_GPIO2 9999
#ifndef PAD_GPIO2_IS_GPIO
#define PAD_GPIO2_IS_GPIO 0
#endif

#define PAD_GPIO3 9999
#ifndef PAD_GPIO3_IS_GPIO
#define PAD_GPIO3_IS_GPIO 0
#endif

#define PIN_7 PAD_GPIO4
#define PAD_GPIO4 49
#define GPIO_PAD_49 GPIO48
#ifndef PIN_7_IS_GPIO
#define PIN_7_IS_GPIO 0
#endif
#ifndef PAD_GPIO4_IS_GPIO
#define PAD_GPIO4_IS_GPIO PIN_7_IS_GPIO
#endif

#define PAD_GPIO5 9999
#ifndef PAD_GPIO5_IS_GPIO
#define PAD_GPIO5_IS_GPIO 0
#endif

#define PAD_GPIO6 9999
#ifndef PAD_GPIO6_IS_GPIO
#define PAD_GPIO6_IS_GPIO 0
#endif

#define PAD_GPIO7 9999
#ifndef PAD_GPIO7_IS_GPIO
#define PAD_GPIO7_IS_GPIO 0
#endif

#define PAD_GPIO8 9999
#ifndef PAD_GPIO8_IS_GPIO
#define PAD_GPIO8_IS_GPIO 0
#endif

#define PAD_GPIO9 9999
#ifndef PAD_GPIO9_IS_GPIO
#define PAD_GPIO9_IS_GPIO 0
#endif

#define PIN_11 PAD_PCM_RESET
#define PAD_PCM_RESET 128
#define GPIO_PAD_128 GPIO127
#ifndef PIN_11_IS_GPIO
#define PIN_11_IS_GPIO 0
#endif
#ifndef PAD_PCM_RESET_IS_GPIO
#define PAD_PCM_RESET_IS_GPIO PIN_11_IS_GPIO
#endif

#define PIN_12 PAD_PCM_IRQA_N
#define PAD_PCM_IRQA_N 129
#define GPIO_PAD_129 GPIO128
#ifndef PIN_12_IS_GPIO
#define PIN_12_IS_GPIO 0
#endif
#ifndef PAD_PCM_IRQA_N_IS_GPIO
#define PAD_PCM_IRQA_N_IS_GPIO PIN_12_IS_GPIO
#endif

#define PIN_13 PAD_PCM_CD_N
#define PAD_PCM_CD_N 130
#define GPIO_PAD_130 GPIO129
#ifndef PIN_13_IS_GPIO
#define PIN_13_IS_GPIO 0
#endif
#ifndef PAD_PCM_CD_N_IS_GPIO
#define PAD_PCM_CD_N_IS_GPIO PIN_13_IS_GPIO
#endif

#define PIN_14 PAD_PCM_REG_N
#define PAD_PCM_REG_N 131
#define GPIO_PAD_131 GPIO130
#ifndef PIN_14_IS_GPIO
#define PIN_14_IS_GPIO 0
#endif
#ifndef PAD_PCM_REG_N_IS_GPIO
#define PAD_PCM_REG_N_IS_GPIO PIN_14_IS_GPIO
#endif

#define PIN_15 PAD_PCM_CE_N
#define PAD_PCM_CE_N 132
#define GPIO_PAD_132 GPIO131
#ifndef PIN_15_IS_GPIO
#define PIN_15_IS_GPIO 0
#endif
#ifndef PAD_PCM_CE_N_IS_GPIO
#define PAD_PCM_CE_N_IS_GPIO PIN_15_IS_GPIO
#endif

#define PIN_16 PAD_PCM_OE_N
#define PAD_PCM_OE_N 133
#define GPIO_PAD_133 GPIO132
#ifndef PIN_16_IS_GPIO
#define PIN_16_IS_GPIO 0
#endif
#ifndef PAD_PCM_OE_N_IS_GPIO
#define PAD_PCM_OE_N_IS_GPIO PIN_16_IS_GPIO
#endif

#define PIN_17 PAD_PCM_WE_N
#define PAD_PCM_WE_N 134
#define GPIO_PAD_134 GPIO133
#ifndef PIN_17_IS_GPIO
#define PIN_17_IS_GPIO 0
#endif
#ifndef PAD_PCM_WE_N_IS_GPIO
#define PAD_PCM_WE_N_IS_GPIO PIN_17_IS_GPIO
#endif

#define PIN_18 PAD_PCM_WAIT_N
#define PAD_PCM_WAIT_N 135
#define GPIO_PAD_135 GPIO134
#ifndef PIN_18_IS_GPIO
#define PIN_18_IS_GPIO 0
#endif
#ifndef PAD_PCM_WAIT_N_IS_GPIO
#define PAD_PCM_WAIT_N_IS_GPIO PIN_18_IS_GPIO
#endif

#define PIN_19 PAD_PCM_IORD_N
#define PAD_PCM_IORD_N 136
#define GPIO_PAD_136 GPIO135
#ifndef PIN_19_IS_GPIO
#define PIN_19_IS_GPIO 0
#endif
#ifndef PAD_PCM_IORD_N_IS_GPIO
#define PAD_PCM_IORD_N_IS_GPIO PIN_19_IS_GPIO
#endif

#define PIN_20 PAD_PCM_IOWR_N
#define PAD_PCM_IOWR_N 234
#define GPIO_PAD_234 GPIO233
#ifndef PIN_20_IS_GPIO
#define PIN_20_IS_GPIO 0
#endif
#ifndef PAD_PCM_IOWR_N_IS_GPIO
#define PAD_PCM_IOWR_N_IS_GPIO PIN_20_IS_GPIO
#endif

#define PIN_21 PAD_PCM_D0
#define PAD_PCM_D0 137
#define GPIO_PAD_137 GPIO136
#ifndef PIN_21_IS_GPIO
#define PIN_21_IS_GPIO 0
#endif
#ifndef PAD_PCM_D0_IS_GPIO
#define PAD_PCM_D0_IS_GPIO PIN_21_IS_GPIO
#endif

#define PIN_22 PAD_PCM_D1
#define PAD_PCM_D1 138
#define GPIO_PAD_138 GPIO137
#ifndef PIN_22_IS_GPIO
#define PIN_22_IS_GPIO 0
#endif
#ifndef PAD_PCM_D1_IS_GPIO
#define PAD_PCM_D1_IS_GPIO PIN_22_IS_GPIO
#endif

#define PIN_23 PAD_PCM_D2
#define PAD_PCM_D2 139
#define GPIO_PAD_139 GPIO138
#ifndef PIN_23_IS_GPIO
#define PIN_23_IS_GPIO 0
#endif
#ifndef PAD_PCM_D2_IS_GPIO
#define PAD_PCM_D2_IS_GPIO PIN_23_IS_GPIO
#endif

#define PIN_24 PAD_PCM_D3
#define PAD_PCM_D3 140
#define GPIO_PAD_140 GPIO139
#ifndef PIN_24_IS_GPIO
#define PIN_24_IS_GPIO 0
#endif
#ifndef PAD_PCM_D3_IS_GPIO
#define PAD_PCM_D3_IS_GPIO PIN_24_IS_GPIO
#endif

#define PIN_25 PAD_PCM_D4
#define PAD_PCM_D4 141
#define GPIO_PAD_141 GPIO140
#ifndef PIN_25_IS_GPIO
#define PIN_25_IS_GPIO 0
#endif
#ifndef PAD_PCM_D4_IS_GPIO
#define PAD_PCM_D4_IS_GPIO PIN_25_IS_GPIO
#endif

#define PIN_26 PAD_PCM_D5
#define PAD_PCM_D5 142
#define GPIO_PAD_142 GPIO141
#ifndef PIN_26_IS_GPIO
#define PIN_26_IS_GPIO 0
#endif
#ifndef PAD_PCM_D5_IS_GPIO
#define PAD_PCM_D5_IS_GPIO PIN_26_IS_GPIO
#endif

#define PIN_27 PAD_PCM_D6
#define PAD_PCM_D6 143
#define GPIO_PAD_143 GPIO142
#ifndef PIN_27_IS_GPIO
#define PIN_27_IS_GPIO 0
#endif
#ifndef PAD_PCM_D6_IS_GPIO
#define PAD_PCM_D6_IS_GPIO PIN_27_IS_GPIO
#endif

#define PIN_28 PAD_PCM_D7
#define PAD_PCM_D7 144
#define GPIO_PAD_144 GPIO143
#ifndef PIN_28_IS_GPIO
#define PIN_28_IS_GPIO 0
#endif
#ifndef PAD_PCM_D7_IS_GPIO
#define PAD_PCM_D7_IS_GPIO PIN_28_IS_GPIO
#endif

#define PIN_29 PAD_PCM_A14
#define PAD_PCM_A14 127
#define GPIO_PAD_127 GPIO126
#ifndef PIN_29_IS_GPIO
#define PIN_29_IS_GPIO 0
#endif
#ifndef PAD_PCM_A14_IS_GPIO
#define PAD_PCM_A14_IS_GPIO PIN_29_IS_GPIO
#endif

#define PIN_30 PAD_PCM_A13
#define PAD_PCM_A13 126
#define GPIO_PAD_126 GPIO125
#ifndef PIN_30_IS_GPIO
#define PIN_30_IS_GPIO 0
#endif
#ifndef PAD_PCM_A13_IS_GPIO
#define PAD_PCM_A13_IS_GPIO PIN_30_IS_GPIO
#endif

#define PIN_31 PAD_PCM_A12
#define PAD_PCM_A12 125
#define GPIO_PAD_125 GPIO124
#ifndef PIN_31_IS_GPIO
#define PIN_31_IS_GPIO 0
#endif
#ifndef PAD_PCM_A12_IS_GPIO
#define PAD_PCM_A12_IS_GPIO PIN_31_IS_GPIO
#endif

#define PIN_32 PAD_PCM_A11
#define PAD_PCM_A11 124
#define GPIO_PAD_124 GPIO123
#ifndef PIN_32_IS_GPIO
#define PIN_32_IS_GPIO 0
#endif
#ifndef PAD_PCM_A11_IS_GPIO
#define PAD_PCM_A11_IS_GPIO PIN_32_IS_GPIO
#endif

#define PIN_33 PAD_PCM_A10
#define PAD_PCM_A10 123
#define GPIO_PAD_123 GPIO122
#ifndef PIN_33_IS_GPIO
#define PIN_33_IS_GPIO 0
#endif
#ifndef PAD_PCM_A10_IS_GPIO
#define PAD_PCM_A10_IS_GPIO PIN_33_IS_GPIO
#endif

#define PIN_34 PAD_PCM_A9
#define PAD_PCM_A9 122
#define GPIO_PAD_122 GPIO121
#ifndef PIN_34_IS_GPIO
#define PIN_34_IS_GPIO 0
#endif
#ifndef PAD_PCM_A9_IS_GPIO
#define PAD_PCM_A9_IS_GPIO PIN_34_IS_GPIO
#endif

#define PIN_35 PAD_PCM_A8
#define PAD_PCM_A8 121
#define GPIO_PAD_121 GPIO120
#ifndef PIN_35_IS_GPIO
#define PIN_35_IS_GPIO 0
#endif
#ifndef PAD_PCM_A8_IS_GPIO
#define PAD_PCM_A8_IS_GPIO PIN_35_IS_GPIO
#endif

#define PIN_36 PAD_PCM_A7
#define PAD_PCM_A7 120
#define GPIO_PAD_120 GPIO119
#ifndef PIN_36_IS_GPIO
#define PIN_36_IS_GPIO 0
#endif
#ifndef PAD_PCM_A7_IS_GPIO
#define PAD_PCM_A7_IS_GPIO PIN_36_IS_GPIO
#endif

#define PIN_37 PAD_PCM_A6
#define PAD_PCM_A6 119
#define GPIO_PAD_119 GPIO118
#ifndef PIN_37_IS_GPIO
#define PIN_37_IS_GPIO 0
#endif
#ifndef PAD_PCM_A6_IS_GPIO
#define PAD_PCM_A6_IS_GPIO PIN_37_IS_GPIO
#endif

#define PIN_38 PAD_PCM_A5
#define PAD_PCM_A5 118
#define GPIO_PAD_118 GPIO117
#ifndef PIN_38_IS_GPIO
#define PIN_38_IS_GPIO 0
#endif
#ifndef PAD_PCM_A5_IS_GPIO
#define PAD_PCM_A5_IS_GPIO PIN_38_IS_GPIO
#endif

#define PIN_39 PAD_PCM_A4
#define PAD_PCM_A4 117
#define GPIO_PAD_117 GPIO116
#ifndef PIN_39_IS_GPIO
#define PIN_39_IS_GPIO 0
#endif
#ifndef PAD_PCM_A4_IS_GPIO
#define PAD_PCM_A4_IS_GPIO PIN_39_IS_GPIO
#endif

#define PIN_40 PAD_PCM_A3
#define PAD_PCM_A3 116
#define GPIO_PAD_116 GPIO115
#ifndef PIN_40_IS_GPIO
#define PIN_40_IS_GPIO 0
#endif
#ifndef PAD_PCM_A3_IS_GPIO
#define PAD_PCM_A3_IS_GPIO PIN_40_IS_GPIO
#endif

#define PIN_41 PAD_PCM_A2
#define PAD_PCM_A2 115
#define GPIO_PAD_115 GPIO114
#ifndef PIN_41_IS_GPIO
#define PIN_41_IS_GPIO 0
#endif
#ifndef PAD_PCM_A2_IS_GPIO
#define PAD_PCM_A2_IS_GPIO PIN_41_IS_GPIO
#endif

#define PIN_42 PAD_PCM_A1
#define PAD_PCM_A1 114
#define GPIO_PAD_114 GPIO113
#ifndef PIN_42_IS_GPIO
#define PIN_42_IS_GPIO 0
#endif
#ifndef PAD_PCM_A1_IS_GPIO
#define PAD_PCM_A1_IS_GPIO PIN_42_IS_GPIO
#endif

#define PIN_43 PAD_PCM_A0
#define PAD_PCM_A0 113
#define GPIO_PAD_113 GPIO112
#ifndef PIN_43_IS_GPIO
#define PIN_43_IS_GPIO 0
#endif
#ifndef PAD_PCM_A0_IS_GPIO
#define PAD_PCM_A0_IS_GPIO PIN_43_IS_GPIO
#endif

#define PAD_NAND_AD7 9999
#ifndef PAD_NAND_AD7_IS_GPIO
#define PAD_NAND_AD7_IS_GPIO 0
#endif

#define PAD_NAND_AD6 9999
#ifndef PAD_NAND_AD6_IS_GPIO
#define PAD_NAND_AD6_IS_GPIO 0
#endif

#define PAD_NAND_AD5 9999
#ifndef PAD_NAND_AD5_IS_GPIO
#define PAD_NAND_AD5_IS_GPIO 0
#endif

#define PAD_NAND_AD4 9999
#ifndef PAD_NAND_AD4_IS_GPIO
#define PAD_NAND_AD4_IS_GPIO 0
#endif

#define PAD_NAND_AD3 9999
#ifndef PAD_NAND_AD3_IS_GPIO
#define PAD_NAND_AD3_IS_GPIO 0
#endif

#define PAD_NAND_AD2 9999
#ifndef PAD_NAND_AD2_IS_GPIO
#define PAD_NAND_AD2_IS_GPIO 0
#endif

#define PAD_NAND_AD1 9999
#ifndef PAD_NAND_AD1_IS_GPIO
#define PAD_NAND_AD1_IS_GPIO 0
#endif

#define PAD_NAND_AD0 9999
#ifndef PAD_NAND_AD0_IS_GPIO
#define PAD_NAND_AD0_IS_GPIO 0
#endif

#define PIN_44 PAD_TS0_CLK
#define PAD_TS0_CLK 155
#define GPIO_PAD_155 GPIO154
#ifndef PIN_44_IS_GPIO
#define PIN_44_IS_GPIO 0
#endif
#ifndef PAD_TS0_CLK_IS_GPIO
#define PAD_TS0_CLK_IS_GPIO PIN_44_IS_GPIO
#endif

#define PIN_45 PAD_TS0_SYNC
#define PAD_TS0_SYNC 154
#define GPIO_PAD_154 GPIO153
#ifndef PIN_45_IS_GPIO
#define PIN_45_IS_GPIO 0
#endif
#ifndef PAD_TS0_SYNC_IS_GPIO
#define PAD_TS0_SYNC_IS_GPIO PIN_45_IS_GPIO
#endif

#define PIN_46 PAD_TS0_VLD
#define PAD_TS0_VLD 153
#define GPIO_PAD_153 GPIO152
#ifndef PIN_46_IS_GPIO
#define PIN_46_IS_GPIO 0
#endif
#ifndef PAD_TS0_VLD_IS_GPIO
#define PAD_TS0_VLD_IS_GPIO PIN_46_IS_GPIO
#endif

#define PIN_47 PAD_TS0_D7
#define PAD_TS0_D7 152
#define GPIO_PAD_152 GPIO151
#ifndef PIN_47_IS_GPIO
#define PIN_47_IS_GPIO 0
#endif
#ifndef PAD_TS0_D7_IS_GPIO
#define PAD_TS0_D7_IS_GPIO PIN_47_IS_GPIO
#endif

#define PIN_48 PAD_TS0_D6
#define PAD_TS0_D6 151
#define GPIO_PAD_151 GPIO150
#ifndef PIN_48_IS_GPIO
#define PIN_48_IS_GPIO 0
#endif
#ifndef PAD_TS0_D6_IS_GPIO
#define PAD_TS0_D6_IS_GPIO PIN_48_IS_GPIO
#endif

#define PIN_49 PAD_TS0_D5
#define PAD_TS0_D5 150
#define GPIO_PAD_150 GPIO149
#ifndef PIN_49_IS_GPIO
#define PIN_49_IS_GPIO 0
#endif
#ifndef PAD_TS0_D5_IS_GPIO
#define PAD_TS0_D5_IS_GPIO PIN_49_IS_GPIO
#endif

#define PIN_50 PAD_TS0_D4
#define PAD_TS0_D4 149
#define GPIO_PAD_149 GPIO148
#ifndef PIN_50_IS_GPIO
#define PIN_50_IS_GPIO 0
#endif
#ifndef PAD_TS0_D4_IS_GPIO
#define PAD_TS0_D4_IS_GPIO PIN_50_IS_GPIO
#endif

#define PIN_51 PAD_TS0_D3
#define PAD_TS0_D3 148
#define GPIO_PAD_148 GPIO147
#ifndef PIN_51_IS_GPIO
#define PIN_51_IS_GPIO 0
#endif
#ifndef PAD_TS0_D3_IS_GPIO
#define PAD_TS0_D3_IS_GPIO PIN_51_IS_GPIO
#endif

#define PIN_52 PAD_TS0_D2
#define PAD_TS0_D2 147
#define GPIO_PAD_147 GPIO146
#ifndef PIN_52_IS_GPIO
#define PIN_52_IS_GPIO 0
#endif
#ifndef PAD_TS0_D2_IS_GPIO
#define PAD_TS0_D2_IS_GPIO PIN_52_IS_GPIO
#endif

#define PIN_53 PAD_TS0_D1
#define PAD_TS0_D1 146
#define GPIO_PAD_146 GPIO145
#ifndef PIN_53_IS_GPIO
#define PIN_53_IS_GPIO 0
#endif
#ifndef PAD_TS0_D1_IS_GPIO
#define PAD_TS0_D1_IS_GPIO PIN_53_IS_GPIO
#endif

#define PIN_54 PAD_TS0_D0
#define PAD_TS0_D0 145
#define GPIO_PAD_145 GPIO144
#ifndef PIN_54_IS_GPIO
#define PIN_54_IS_GPIO 0
#endif
#ifndef PAD_TS0_D0_IS_GPIO
#define PAD_TS0_D0_IS_GPIO PIN_54_IS_GPIO
#endif

#define PIN_55 PAD_TS1_CLK
#define PAD_TS1_CLK 166
#define GPIO_PAD_166 GPIO165
#ifndef PIN_55_IS_GPIO
#define PIN_55_IS_GPIO 0
#endif
#ifndef PAD_TS1_CLK_IS_GPIO
#define PAD_TS1_CLK_IS_GPIO PIN_55_IS_GPIO
#endif

#define PIN_56 PAD_TS1_SYNC
#define PAD_TS1_SYNC 165
#define GPIO_PAD_165 GPIO164
#ifndef PIN_56_IS_GPIO
#define PIN_56_IS_GPIO 0
#endif
#ifndef PAD_TS1_SYNC_IS_GPIO
#define PAD_TS1_SYNC_IS_GPIO PIN_56_IS_GPIO
#endif

#define PIN_57 PAD_TS1_VLD
#define PAD_TS1_VLD 164
#define GPIO_PAD_164 GPIO163
#ifndef PIN_57_IS_GPIO
#define PIN_57_IS_GPIO 0
#endif
#ifndef PAD_TS1_VLD_IS_GPIO
#define PAD_TS1_VLD_IS_GPIO PIN_57_IS_GPIO
#endif

#define PIN_58 PAD_TS1_D7
#define PAD_TS1_D7 163
#define GPIO_PAD_163 GPIO162
#ifndef PIN_58_IS_GPIO
#define PIN_58_IS_GPIO 0
#endif
#ifndef PAD_TS1_D7_IS_GPIO
#define PAD_TS1_D7_IS_GPIO PIN_58_IS_GPIO
#endif

#define PIN_59 PAD_TS1_D6
#define PAD_TS1_D6 162
#define GPIO_PAD_162 GPIO161
#ifndef PIN_59_IS_GPIO
#define PIN_59_IS_GPIO 0
#endif
#ifndef PAD_TS1_D6_IS_GPIO
#define PAD_TS1_D6_IS_GPIO PIN_59_IS_GPIO
#endif

#define PIN_60 PAD_TS1_D5
#define PAD_TS1_D5 161
#define GPIO_PAD_161 GPIO160
#ifndef PIN_60_IS_GPIO
#define PIN_60_IS_GPIO 0
#endif
#ifndef PAD_TS1_D5_IS_GPIO
#define PAD_TS1_D5_IS_GPIO PIN_60_IS_GPIO
#endif

#define PIN_61 PAD_TS1_D4
#define PAD_TS1_D4 160
#define GPIO_PAD_160 GPIO159
#ifndef PIN_61_IS_GPIO
#define PIN_61_IS_GPIO 0
#endif
#ifndef PAD_TS1_D4_IS_GPIO
#define PAD_TS1_D4_IS_GPIO PIN_61_IS_GPIO
#endif

#define PIN_62 PAD_TS1_D3
#define PAD_TS1_D3 159
#define GPIO_PAD_159 GPIO158
#ifndef PIN_62_IS_GPIO
#define PIN_62_IS_GPIO 0
#endif
#ifndef PAD_TS1_D3_IS_GPIO
#define PAD_TS1_D3_IS_GPIO PIN_62_IS_GPIO
#endif

#define PIN_63 PAD_TS1_D2
#define PAD_TS1_D2 158
#define GPIO_PAD_158 GPIO157
#ifndef PIN_63_IS_GPIO
#define PIN_63_IS_GPIO 0
#endif
#ifndef PAD_TS1_D2_IS_GPIO
#define PAD_TS1_D2_IS_GPIO PIN_63_IS_GPIO
#endif

#define PIN_64 PAD_TS1_D1
#define PAD_TS1_D1 157
#define GPIO_PAD_157 GPIO156
#ifndef PIN_64_IS_GPIO
#define PIN_64_IS_GPIO 0
#endif
#ifndef PAD_TS1_D1_IS_GPIO
#define PAD_TS1_D1_IS_GPIO PIN_64_IS_GPIO
#endif

#define PIN_65 PAD_TS1_D0
#define PAD_TS1_D0 156
#define GPIO_PAD_156 GPIO155
#ifndef PIN_65_IS_GPIO
#define PIN_65_IS_GPIO 0
#endif
#ifndef PAD_TS1_D0_IS_GPIO
#define PAD_TS1_D0_IS_GPIO PIN_65_IS_GPIO
#endif

#define PAD_TS2_CLK 9999
#ifndef PAD_TS2_CLK_IS_GPIO
#define PAD_TS2_CLK_IS_GPIO 0
#endif

#define PAD_TS2_SYNC 9999
#ifndef PAD_TS2_SYNC_IS_GPIO
#define PAD_TS2_SYNC_IS_GPIO 0
#endif

#define PAD_TS2_VLD 9999
#ifndef PAD_TS2_VLD_IS_GPIO
#define PAD_TS2_VLD_IS_GPIO 0
#endif

#define PAD_TS2_D0 9999
#ifndef PAD_TS2_D0_IS_GPIO
#define PAD_TS2_D0_IS_GPIO 0
#endif

#define PIN_68 PAD_B_ODD0
#define PAD_B_ODD0 44
#define GPIO_PAD_44 GPIO43
#ifndef PIN_68_IS_GPIO
#define PIN_68_IS_GPIO 0
#endif
#ifndef PAD_B_ODD0_IS_GPIO
#define PAD_B_ODD0_IS_GPIO PIN_68_IS_GPIO
#endif

#define PIN_69 PAD_B_ODD1
#define PAD_B_ODD1 43
#define GPIO_PAD_43 GPIO42
#ifndef PIN_69_IS_GPIO
#define PIN_69_IS_GPIO 0
#endif
#ifndef PAD_B_ODD1_IS_GPIO
#define PAD_B_ODD1_IS_GPIO PIN_69_IS_GPIO
#endif

#define PIN_70 PAD_B_ODD2
#define PAD_B_ODD2 42
#define GPIO_PAD_42 GPIO41
#ifndef PIN_70_IS_GPIO
#define PIN_70_IS_GPIO 0
#endif
#ifndef PAD_B_ODD2_IS_GPIO
#define PAD_B_ODD2_IS_GPIO PIN_70_IS_GPIO
#endif

#define PIN_71 PAD_B_ODD3
#define PAD_B_ODD3 41
#define GPIO_PAD_41 GPIO40
#ifndef PIN_71_IS_GPIO
#define PIN_71_IS_GPIO 0
#endif
#ifndef PAD_B_ODD3_IS_GPIO
#define PAD_B_ODD3_IS_GPIO PIN_71_IS_GPIO
#endif

#define PIN_72 PAD_B_ODD4
#define PAD_B_ODD4 40
#define GPIO_PAD_40 GPIO39
#ifndef PIN_72_IS_GPIO
#define PIN_72_IS_GPIO 0
#endif
#ifndef PAD_B_ODD4_IS_GPIO
#define PAD_B_ODD4_IS_GPIO PIN_72_IS_GPIO
#endif

#define PIN_73 PAD_B_ODD5
#define PAD_B_ODD5 39
#define GPIO_PAD_39 GPIO38
#ifndef PIN_73_IS_GPIO
#define PIN_73_IS_GPIO 0
#endif
#ifndef PAD_B_ODD5_IS_GPIO
#define PAD_B_ODD5_IS_GPIO PIN_73_IS_GPIO
#endif

#define PIN_74 PAD_B_ODD6
#define PAD_B_ODD6 38
#define GPIO_PAD_38 GPIO37
#ifndef PIN_74_IS_GPIO
#define PIN_74_IS_GPIO 0
#endif
#ifndef PAD_B_ODD6_IS_GPIO
#define PAD_B_ODD6_IS_GPIO PIN_74_IS_GPIO
#endif

#define PIN_75 PAD_B_ODD7
#define PAD_B_ODD7 37
#define GPIO_PAD_37 GPIO36
#ifndef PIN_75_IS_GPIO
#define PIN_75_IS_GPIO 0
#endif
#ifndef PAD_B_ODD7_IS_GPIO
#define PAD_B_ODD7_IS_GPIO PIN_75_IS_GPIO
#endif

#define PIN_76 PAD_G_ODD0
#define PAD_G_ODD0 36
#define GPIO_PAD_36 GPIO35
#ifndef PIN_76_IS_GPIO
#define PIN_76_IS_GPIO 0
#endif
#ifndef PAD_G_ODD0_IS_GPIO
#define PAD_G_ODD0_IS_GPIO PIN_76_IS_GPIO
#endif

#define PIN_77 PAD_G_ODD1
#define PAD_G_ODD1 35
#define GPIO_PAD_35 GPIO34
#ifndef PIN_77_IS_GPIO
#define PIN_77_IS_GPIO 0
#endif
#ifndef PAD_G_ODD1_IS_GPIO
#define PAD_G_ODD1_IS_GPIO PIN_77_IS_GPIO
#endif

#define PIN_78 PAD_G_ODD2
#define PAD_G_ODD2 34
#define GPIO_PAD_34 GPIO33
#ifndef PIN_78_IS_GPIO
#define PIN_78_IS_GPIO 0
#endif
#ifndef PAD_G_ODD2_IS_GPIO
#define PAD_G_ODD2_IS_GPIO PIN_78_IS_GPIO
#endif

#define PIN_79 PAD_G_ODD3
#define PAD_G_ODD3 33
#define GPIO_PAD_33 GPIO32
#ifndef PIN_79_IS_GPIO
#define PIN_79_IS_GPIO 0
#endif
#ifndef PAD_G_ODD3_IS_GPIO
#define PAD_G_ODD3_IS_GPIO PIN_79_IS_GPIO
#endif

#define PIN_80 PAD_G_ODD4
#define PAD_G_ODD4 32
#define GPIO_PAD_32 GPIO31
#ifndef PIN_80_IS_GPIO
#define PIN_80_IS_GPIO 0
#endif
#ifndef PAD_G_ODD4_IS_GPIO
#define PAD_G_ODD4_IS_GPIO PIN_80_IS_GPIO
#endif

#define PIN_81 PAD_G_ODD5
#define PAD_G_ODD5 31
#define GPIO_PAD_31 GPIO30
#ifndef PIN_81_IS_GPIO
#define PIN_81_IS_GPIO 0
#endif
#ifndef PAD_G_ODD5_IS_GPIO
#define PAD_G_ODD5_IS_GPIO PIN_81_IS_GPIO
#endif

#define PIN_82 PAD_G_ODD6
#define PAD_G_ODD6 30
#define GPIO_PAD_30 GPIO29
#ifndef PIN_82_IS_GPIO
#define PIN_82_IS_GPIO 0
#endif
#ifndef PAD_G_ODD6_IS_GPIO
#define PAD_G_ODD6_IS_GPIO PIN_82_IS_GPIO
#endif

#define PIN_83 PAD_G_ODD7
#define PAD_G_ODD7 29
#define GPIO_PAD_29 GPIO28
#ifndef PIN_83_IS_GPIO
#define PIN_83_IS_GPIO 0
#endif
#ifndef PAD_G_ODD7_IS_GPIO
#define PAD_G_ODD7_IS_GPIO PIN_83_IS_GPIO
#endif

#define PIN_84 PAD_R_ODD0
#define PAD_R_ODD0 28
#define GPIO_PAD_28 GPIO27
#ifndef PIN_84_IS_GPIO
#define PIN_84_IS_GPIO 0
#endif
#ifndef PAD_R_ODD0_IS_GPIO
#define PAD_R_ODD0_IS_GPIO PIN_84_IS_GPIO
#endif

#define PIN_85 PAD_R_ODD1
#define PAD_R_ODD1 27
#define GPIO_PAD_27 GPIO26
#ifndef PIN_85_IS_GPIO
#define PIN_85_IS_GPIO 0
#endif
#ifndef PAD_R_ODD1_IS_GPIO
#define PAD_R_ODD1_IS_GPIO PIN_85_IS_GPIO
#endif

#define PIN_86 PAD_R_ODD2
#define PAD_R_ODD2 26
#define GPIO_PAD_26 GPIO25
#ifndef PIN_86_IS_GPIO
#define PIN_86_IS_GPIO 0
#endif
#ifndef PAD_R_ODD2_IS_GPIO
#define PAD_R_ODD2_IS_GPIO PIN_86_IS_GPIO
#endif

#define PIN_87 PAD_R_ODD3
#define PAD_R_ODD3 25
#define GPIO_PAD_25 GPIO24
#ifndef PIN_87_IS_GPIO
#define PIN_87_IS_GPIO 0
#endif
#ifndef PAD_R_ODD3_IS_GPIO
#define PAD_R_ODD3_IS_GPIO PIN_87_IS_GPIO
#endif

#define PIN_89 PAD_R_ODD4
#define PAD_R_ODD4 24
#define GPIO_PAD_24 GPIO23
#ifndef PIN_89_IS_GPIO
#define PIN_89_IS_GPIO 0
#endif
#ifndef PAD_R_ODD4_IS_GPIO
#define PAD_R_ODD4_IS_GPIO PIN_89_IS_GPIO
#endif

#define PIN_90 PAD_R_ODD5
#define PAD_R_ODD5 23
#define GPIO_PAD_23 GPIO22
#ifndef PIN_90_IS_GPIO
#define PIN_90_IS_GPIO 0
#endif
#ifndef PAD_R_ODD5_IS_GPIO
#define PAD_R_ODD5_IS_GPIO PIN_90_IS_GPIO
#endif

#define PIN_91 PAD_R_ODD6
#define PAD_R_ODD6 22
#define GPIO_PAD_22 GPIO21
#ifndef PIN_91_IS_GPIO
#define PIN_91_IS_GPIO 0
#endif
#ifndef PAD_R_ODD6_IS_GPIO
#define PAD_R_ODD6_IS_GPIO PIN_91_IS_GPIO
#endif

#define PIN_92 PAD_R_ODD7
#define PAD_R_ODD7 21
#define GPIO_PAD_21 GPIO20
#ifndef PIN_92_IS_GPIO
#define PIN_92_IS_GPIO 0
#endif
#ifndef PAD_R_ODD7_IS_GPIO
#define PAD_R_ODD7_IS_GPIO PIN_92_IS_GPIO
#endif

#define PAD_LCK 9999
#ifndef PAD_LCK_IS_GPIO
#define PAD_LCK_IS_GPIO 0
#endif

#define PAD_LDE 9999
#ifndef PAD_LDE_IS_GPIO
#define PAD_LDE_IS_GPIO 0
#endif

#define PAD_LHSYNC 9999
#ifndef PAD_LHSYNC_IS_GPIO
#define PAD_LHSYNC_IS_GPIO 0
#endif

#define PAD_LVSYNC 9999
#ifndef PAD_LVSYNC_IS_GPIO
#define PAD_LVSYNC_IS_GPIO 0
#endif

#define PAD_GPIO13 9999
#ifndef PAD_GPIO13_IS_GPIO
#define PAD_GPIO13_IS_GPIO 0
#endif

#define PAD_GPIO12 9999
#ifndef PAD_GPIO12_IS_GPIO
#define PAD_GPIO12_IS_GPIO 0
#endif

#define PAD_TCON7 9999
#ifndef PAD_TCON7_IS_GPIO
#define PAD_TCON7_IS_GPIO 0
#endif

#define PAD_TCON6 9999
#ifndef PAD_TCON6_IS_GPIO
#define PAD_TCON6_IS_GPIO 0
#endif

#define PAD_TCON5 9999
#ifndef PAD_TCON5_IS_GPIO
#define PAD_TCON5_IS_GPIO 0
#endif

#define PAD_TCON4 9999
#ifndef PAD_TCON4_IS_GPIO
#define PAD_TCON4_IS_GPIO 0
#endif

#define PAD_TCON3 9999
#ifndef PAD_TCON3_IS_GPIO
#define PAD_TCON3_IS_GPIO 0
#endif

#define PIN_93 PAD_TCON2
#define PAD_TCON2 3
#define GPIO_PAD_3 GPIO2
#ifndef PIN_93_IS_GPIO
#define PIN_93_IS_GPIO 0
#endif
#ifndef PAD_TCON2_IS_GPIO
#define PAD_TCON2_IS_GPIO PIN_93_IS_GPIO
#endif

#define PAD_TCON1 9999
#ifndef PAD_TCON1_IS_GPIO
#define PAD_TCON1_IS_GPIO 0
#endif

#define PIN_94 PAD_TCON0
#define PAD_TCON0 1
#define GPIO_PAD_1 GPIO0
#ifndef PIN_94_IS_GPIO
#define PIN_94_IS_GPIO 0
#endif
#ifndef PAD_TCON0_IS_GPIO
#define PAD_TCON0_IS_GPIO PIN_94_IS_GPIO
#endif

#define PIN_95 PAD_PWM0
#define PAD_PWM0 16
#define GPIO_PAD_16 GPIO15
#ifndef PIN_95_IS_GPIO
#define PIN_95_IS_GPIO 0
#endif
#ifndef PAD_PWM0_IS_GPIO
#define PAD_PWM0_IS_GPIO PIN_95_IS_GPIO
#endif

#define PIN_96 PAD_PWM1
#define PAD_PWM1 15
#define GPIO_PAD_15 GPIO14
#ifndef PIN_96_IS_GPIO
#define PIN_96_IS_GPIO 0
#endif
#ifndef PAD_PWM1_IS_GPIO
#define PAD_PWM1_IS_GPIO PIN_96_IS_GPIO
#endif

#define PAD_INT 9999
#ifndef PAD_INT_IS_GPIO
#define PAD_INT_IS_GPIO 0
#endif

#define PIN_99 PAD_NAND_CEZ
#define PAD_NAND_CEZ 101
#define GPIO_PAD_101 GPIO100
#ifndef PIN_99_IS_GPIO
#define PIN_99_IS_GPIO 0
#endif
#ifndef PAD_NAND_CEZ_IS_GPIO
#define PAD_NAND_CEZ_IS_GPIO PIN_99_IS_GPIO
#endif

#define PAD_NAND_CLE 9999
#ifndef PAD_NAND_CLE_IS_GPIO
#define PAD_NAND_CLE_IS_GPIO 0
#endif

#define PIN_100 PAD_NAND_REZ
#define PAD_NAND_REZ 98
#define GPIO_PAD_98 GPIO97
#ifndef PIN_100_IS_GPIO
#define PIN_100_IS_GPIO 0
#endif
#ifndef PAD_NAND_REZ_IS_GPIO
#define PAD_NAND_REZ_IS_GPIO PIN_100_IS_GPIO
#endif

#define PAD_NAND_WEZ 9999
#ifndef PAD_NAND_WEZ_IS_GPIO
#define PAD_NAND_WEZ_IS_GPIO 0
#endif

#define PAD_NAND_WPZ 9999
#ifndef PAD_NAND_WPZ_IS_GPIO
#define PAD_NAND_WPZ_IS_GPIO 0
#endif

#define PIN_101 PAD_NAND_ALE
#define PAD_NAND_ALE 99
#define GPIO_PAD_99 GPIO98
#ifndef PIN_101_IS_GPIO
#define PIN_101_IS_GPIO 0
#endif
#ifndef PAD_NAND_ALE_IS_GPIO
#define PAD_NAND_ALE_IS_GPIO PIN_101_IS_GPIO
#endif

#define PIN_102 PAD_NAND_RBZ
#define PAD_NAND_RBZ 104
#define GPIO_PAD_104 GPIO103
#ifndef PIN_102_IS_GPIO
#define PIN_102_IS_GPIO 0
#endif
#ifndef PAD_NAND_RBZ_IS_GPIO
#define PAD_NAND_RBZ_IS_GPIO PIN_102_IS_GPIO
#endif

#define PAD_PM_SPI_CZ2 9999
#ifndef PAD_PM_SPI_CZ2_IS_GPIO
#define PAD_PM_SPI_CZ2_IS_GPIO 0
#endif

#define PAD_PM_SPI_CZ1 9999
#ifndef PAD_PM_SPI_CZ1_IS_GPIO
#define PAD_PM_SPI_CZ1_IS_GPIO 0
#endif

#define PIN_106 PAD_MHL_DET
#define PAD_MHL_DET 95
#define GPIO_PAD_95 GPIO94
#ifndef PIN_106_IS_GPIO
#define PIN_106_IS_GPIO 0
#endif
#ifndef PAD_MHL_DET_IS_GPIO
#define PAD_MHL_DET_IS_GPIO PIN_106_IS_GPIO
#endif

#define PAD_DDCDC_CLK 9999
#ifndef PAD_DDCDC_CLK_IS_GPIO
#define PAD_DDCDC_CLK_IS_GPIO 0
#endif

#define PAD_DDCDC_DAT 9999
#ifndef PAD_DDCDC_DAT_IS_GPIO
#define PAD_DDCDC_DAT_IS_GPIO 0
#endif

#define PAD_GPIO26 9999
#ifndef PAD_GPIO26_IS_GPIO
#define PAD_GPIO26_IS_GPIO 0
#endif

#define PAD_GPIO27 9999
#ifndef PAD_GPIO27_IS_GPIO
#define PAD_GPIO27_IS_GPIO 0
#endif

#define PAD_GPIO28 9999
#ifndef PAD_GPIO28_IS_GPIO
#define PAD_GPIO28_IS_GPIO 0
#endif

#define PAD_GPIO29 9999
#ifndef PAD_GPIO29_IS_GPIO
#define PAD_GPIO29_IS_GPIO 0
#endif

#define PIN_108 PAD_SAR0
#define PAD_SAR0 85
#define GPIO_PAD_85 GPIO84
#ifndef PIN_108_IS_GPIO
#define PIN_108_IS_GPIO 0
#endif
#ifndef PAD_SAR0_IS_GPIO
#define PAD_SAR0_IS_GPIO PIN_108_IS_GPIO
#endif

#define PIN_109 PAD_SAR1
#define PAD_SAR1 84
#define GPIO_PAD_84 GPIO83
#ifndef PIN_109_IS_GPIO
#define PIN_109_IS_GPIO 0
#endif
#ifndef PAD_SAR1_IS_GPIO
#define PAD_SAR1_IS_GPIO PIN_109_IS_GPIO
#endif

#define PAD_SAR2 9999
#ifndef PAD_SAR2_IS_GPIO
#define PAD_SAR2_IS_GPIO 0
#endif

#define PAD_RN 9999
#ifndef PAD_RN_IS_GPIO
#define PAD_RN_IS_GPIO 0
#endif

#define PAD_RP 9999
#ifndef PAD_RP_IS_GPIO
#define PAD_RP_IS_GPIO 0
#endif

#define PAD_TN 9999
#ifndef PAD_TN_IS_GPIO
#define PAD_TN_IS_GPIO 0
#endif

#define PAD_TP 9999
#ifndef PAD_TP_IS_GPIO
#define PAD_TP_IS_GPIO 0
#endif

#define PAD_GPIO11 9999
#ifndef PAD_GPIO11_IS_GPIO
#define PAD_GPIO11_IS_GPIO 0
#endif

#define PAD_GPIO10 9999
#ifndef PAD_GPIO10_IS_GPIO
#define PAD_GPIO10_IS_GPIO 0
#endif

#define PIN_114 PAD_DDCDB_DAT
#define PAD_DDCDB_DAT 90
#define GPIO_PAD_90 GPIO89
#ifndef PIN_114_IS_GPIO
#define PIN_114_IS_GPIO 0
#endif
#ifndef PAD_DDCDB_DAT_IS_GPIO
#define PAD_DDCDB_DAT_IS_GPIO PIN_114_IS_GPIO
#endif

#define PIN_115 PAD_DDCDB_CLK
#define PAD_DDCDB_CLK 89
#define GPIO_PAD_89 GPIO88
#ifndef PIN_115_IS_GPIO
#define PIN_115_IS_GPIO 0
#endif
#ifndef PAD_DDCDB_CLK_IS_GPIO
#define PAD_DDCDB_CLK_IS_GPIO PIN_115_IS_GPIO
#endif

#define PAD_DDCDA_DAT 9999
#ifndef PAD_DDCDA_DAT_IS_GPIO
#define PAD_DDCDA_DAT_IS_GPIO 0
#endif

#define PAD_DDCDA_CLK 9999
#ifndef PAD_DDCDA_CLK_IS_GPIO
#define PAD_DDCDA_CLK_IS_GPIO 0
#endif

#define PIN_116 PAD_CEC
#define PAD_CEC 82
#define GPIO_PAD_82 GPIO81
#ifndef PIN_116_IS_GPIO
#define PIN_116_IS_GPIO 0
#endif
#ifndef PAD_CEC_IS_GPIO
#define PAD_CEC_IS_GPIO PIN_116_IS_GPIO
#endif

#define PIN_117 PAD_HOTPLUG_C
#define PAD_HOTPLUG_C 94
#define GPIO_PAD_94 GPIO93
#ifndef PIN_117_IS_GPIO
#define PIN_117_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUG_C_IS_GPIO
#define PAD_HOTPLUG_C_IS_GPIO PIN_117_IS_GPIO
#endif

#define PIN_118 PAD_HOTPLUG_B
#define PAD_HOTPLUG_B 91
#define GPIO_PAD_91 GPIO90
#ifndef PIN_118_IS_GPIO
#define PIN_118_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUG_B_IS_GPIO
#define PAD_HOTPLUG_B_IS_GPIO PIN_118_IS_GPIO
#endif

#define PAD_HOTPLUG_A 9999
#ifndef PAD_HOTPLUG_A_IS_GPIO
#define PAD_HOTPLUG_A_IS_GPIO 0
#endif

#define PIN_121 PAD_ARC
#define PAD_ARC 171
#define GPIO_PAD_171 GPIO170
#ifndef PIN_121_IS_GPIO
#define PIN_121_IS_GPIO 0
#endif
#ifndef PAD_ARC_IS_GPIO
#define PAD_ARC_IS_GPIO PIN_121_IS_GPIO
#endif

#define PAD_RXCN_D 9999
#ifndef PAD_RXCN_D_IS_GPIO
#define PAD_RXCN_D_IS_GPIO 0
#endif

#define PAD_RX0N_D 9999
#ifndef PAD_RX0N_D_IS_GPIO
#define PAD_RX0N_D_IS_GPIO 0
#endif

#define PAD_RXCP_D 9999
#ifndef PAD_RXCP_D_IS_GPIO
#define PAD_RXCP_D_IS_GPIO 0
#endif

#define PAD_RX0P_D 9999
#ifndef PAD_RX0P_D_IS_GPIO
#define PAD_RX0P_D_IS_GPIO 0
#endif

#define PAD_RX1N_D 9999
#ifndef PAD_RX1N_D_IS_GPIO
#define PAD_RX1N_D_IS_GPIO 0
#endif

#define PAD_RX2N_D 9999
#ifndef PAD_RX2N_D_IS_GPIO
#define PAD_RX2N_D_IS_GPIO 0
#endif

#define PAD_RX1P_D 9999
#ifndef PAD_RX1P_D_IS_GPIO
#define PAD_RX1P_D_IS_GPIO 0
#endif

#define PAD_RX2P_D 9999
#ifndef PAD_RX2P_D_IS_GPIO
#define PAD_RX2P_D_IS_GPIO 0
#endif

#define PIN_125 PAD_RX0N_B
#define PAD_RX0N_B 215
#define GPIO_PAD_215 GPIO214
#ifndef PIN_125_IS_GPIO
#define PIN_125_IS_GPIO 0
#endif
#ifndef PAD_RX0N_B_IS_GPIO
#define PAD_RX0N_B_IS_GPIO PIN_125_IS_GPIO
#endif

#define PIN_123 PAD_RXCN_B
#define PAD_RXCN_B 214
#define GPIO_PAD_214 GPIO213
#ifndef PIN_123_IS_GPIO
#define PIN_123_IS_GPIO 0
#endif
#ifndef PAD_RXCN_B_IS_GPIO
#define PAD_RXCN_B_IS_GPIO PIN_123_IS_GPIO
#endif

#define PIN_126 PAD_RX0P_B
#define PAD_RX0P_B 219
#define GPIO_PAD_219 GPIO218
#ifndef PIN_126_IS_GPIO
#define PIN_126_IS_GPIO 0
#endif
#ifndef PAD_RX0P_B_IS_GPIO
#define PAD_RX0P_B_IS_GPIO PIN_126_IS_GPIO
#endif

#define PIN_124 PAD_RXCP_B
#define PAD_RXCP_B 218
#define GPIO_PAD_218 GPIO217
#ifndef PIN_124_IS_GPIO
#define PIN_124_IS_GPIO 0
#endif
#ifndef PAD_RXCP_B_IS_GPIO
#define PAD_RXCP_B_IS_GPIO PIN_124_IS_GPIO
#endif

#define PIN_129 PAD_RX2N_B
#define PAD_RX2N_B 217
#define GPIO_PAD_217 GPIO216
#ifndef PIN_129_IS_GPIO
#define PIN_129_IS_GPIO 0
#endif
#ifndef PAD_RX2N_B_IS_GPIO
#define PAD_RX2N_B_IS_GPIO PIN_129_IS_GPIO
#endif

#define PIN_127 PAD_RX1N_B
#define PAD_RX1N_B 216
#define GPIO_PAD_216 GPIO215
#ifndef PIN_127_IS_GPIO
#define PIN_127_IS_GPIO 0
#endif
#ifndef PAD_RX1N_B_IS_GPIO
#define PAD_RX1N_B_IS_GPIO PIN_127_IS_GPIO
#endif

#define PIN_130 PAD_RX2P_B
#define PAD_RX2P_B 221
#define GPIO_PAD_221 GPIO220
#ifndef PIN_130_IS_GPIO
#define PIN_130_IS_GPIO 0
#endif
#ifndef PAD_RX2P_B_IS_GPIO
#define PAD_RX2P_B_IS_GPIO PIN_130_IS_GPIO
#endif

#define PIN_128 PAD_RX1P_B
#define PAD_RX1P_B 220
#define GPIO_PAD_220 GPIO219
#ifndef PIN_128_IS_GPIO
#define PIN_128_IS_GPIO 0
#endif
#ifndef PAD_RX1P_B_IS_GPIO
#define PAD_RX1P_B_IS_GPIO PIN_128_IS_GPIO
#endif


// PADS group name to index
#define PADS_DDCR           1223
#define PADS_DDCR2          1224
#define PADS_TS0            1225
#define PADS_TS1            1226
#define PADS_GPIO1_GPIO2    1227
#define PADS_LHSYNC2_LVSYNC2 1228
#define PADS_PCI_AD20_AD21  1229
#define PADS_PCI            1230
#define PADS_PCM            1231
#define PADS_SAR            1232
#define PADS_DOUT           1233
#define PADS_DIN            1234
#define PADS_I2S            1235
#define PADS_PF             1236
#define PADS_EMAC           1237
#define PADS_TCON           1238
#define PADS_UART1_MODE1    1239
#define PADS_UART1_MODE2    1240
#define PADS_UART1_MODE3    1241
#define PADS_UART2_MODE1    1242
#define PADS_UART2_MODE2    1243
#define PADS_UART2_MODE3    1244
#define PADS_ET_MODE0       1245
#define PADS_ET_MODE1       1246
#define PADS_ET_MODE2       1247
#define PADS_ET_MODE3       1248
#define PADS_MIIC           1249
#define PADS_PF_MODE1       1250
#define PADS_PF_MODE2       1251
#define PADS_PF_MODE3       1252
#define PADS_SPI_CZ1        1253
#define PADS_SPI_CZ2        1254
#define PADS_SPI_CZ3        1255
#define PADS_DDCR3          1256

// chip capbilities
#define CHIP_HAS_BT656_IN          0
#define CHIP_HAS_TS0               1
#define CHIP_HAS_TS1               0
#define CHIP_HAS_LVDS_10BIT_X2     1
#define CHIP_HAS_LVDS_8BIT_X2      1
#define CHIP_HAS_LVDS_8BIT_X1      1
#define CHIP_HAS_CIMAX             0
#define CHIP_HAS_USB_P0            1
#define CHIP_HAS_USB_P1            1
#define CHIP_HAS_USBVBUS0          0
#define CHIP_HAS_USBVBUS1          0
#define CHIP_HAS_UART1_MODE1       1
#define CHIP_HAS_UART1_MODE2       1
#define CHIP_HAS_UART1_MODE3       1
#define CHIP_HAS_PCMCIA1           0
#define CHIP_HAS_PCMCIA2           0
#define CHIP_HAS_PCMCIA            0
#define CHIP_HAS_UART2_MODE1       1
#define CHIP_HAS_UART2_MODE2       1
#define CHIP_HAS_UART2_MODE3       1
#define CHIP_HAS_RGB_A             1
#define CHIP_HAS_RGB_B             1
#define CHIP_HAS_RGB_C             1
#define CHIP_HAS_HDMI_A            1
#define CHIP_HAS_HDMI_B            1
#define CHIP_HAS_HDMI_C            1
#define CHIP_HAS_SPI_CZ1           1
#define CHIP_HAS_SPI_CZ2           0
#define CHIP_HAS_SPI_CZ3           0
#define CHIP_HAS_DDCR              1
#define CHIP_HAS_DDCR2             1
#define CHIP_HAS_TCON              1
#define CHIP_HAS_ET_MODE0_MII      1
#define CHIP_HAS_ET_MODE0_RMII     1
#define CHIP_HAS_ET_MODE1_MII      1
#define CHIP_HAS_ET_MODE1_RMII     1
#define CHIP_HAS_ET_MODE2_MII      1
#define CHIP_HAS_ET_MODE2_RMII     1
#define CHIP_HAS_I2S_IN            1
#define CHIP_HAS_I2S_OUT           1
#define CHIP_HAS_SPDIF_IN          0
#define CHIP_HAS_SPDIF_OUT         1
#define CHIP_HAS_DDR_A_CMD         1
#define CHIP_HAS_DDR_A_DATA        1
#define CHIP_HAS_DDR_B_CMD         1
#define CHIP_HAS_DDR_B_DATA        1
#define CHIP_USE_PCM_CDN_IN_PCM2   0
#define CHIP_USE_I2S_IN_IN_PCM     0
#define CHIP_USE_I2S_OUT_IN_PCM    0
#define CHIP_USE_SPDIF_IN_IN_PCM   0
#define CHIP_USE_SPDIF_OUT_IN_PCM  0
#define CHIP_USE_IIC_IN_DDCR2      0
#define CHIP_USE_PWM2_IN_GPIO14    0
#define CHIP_USE_PWM3_IN_GPIO15    0

// chip additional information
#define CHIP_FAMILY_TYPE           CHIP_FAMILY_MARLON

#endif/* _MSD92LJBN_H_*/
