/* SPDX-License-Identifier: GPL-2.0-only OR BSD-3-Clause */
/******************************************************************************
 *
 * This file is provided under a dual license.  When you use or
 * distribute this software, you may choose to be licensed under
 * version 2 of the GNU General Public License ("GPLv2 License")
 * or BSD License.
 *
 * GPLv2 License
 *
 * Copyright(C) 2019 MediaTek Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of version 2 of the GNU General Public License as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See http://www.gnu.org/licenses/gpl-2.0.html for more details.
 *
 * BSD LICENSE
 *
 * Copyright(C) 2019 MediaTek Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *****************************************************************************/

// This file is generated by script file, please do not edit it directly 
#ifndef _MT5870GYYTYY_H_
#define _MT5870GYYTYY_H_

#define PAD_NC   9999
#define PAD_GND  0

#define BALL_C17 PAD_TCON0
#define PAD_TCON0 136
#define GPIO_PAD_136 GPIO135
#ifndef BALL_C17_IS_GPIO
#define BALL_C17_IS_GPIO 0
#endif 
#ifndef PAD_TCON0_IS_GPIO
#define PAD_TCON0_IS_GPIO BALL_C17_IS_GPIO
#endif 

#define BALL_C18 PAD_TCON3
#define PAD_TCON3 139
#define GPIO_PAD_139 GPIO138
#ifndef BALL_C18_IS_GPIO
#define BALL_C18_IS_GPIO 0
#endif 
#ifndef PAD_TCON3_IS_GPIO
#define PAD_TCON3_IS_GPIO BALL_C18_IS_GPIO
#endif 

#define BALL_B18 PAD_TCON1
#define PAD_TCON1 137
#define GPIO_PAD_137 GPIO136
#ifndef BALL_B18_IS_GPIO
#define BALL_B18_IS_GPIO 0
#endif 
#ifndef PAD_TCON1_IS_GPIO
#define PAD_TCON1_IS_GPIO BALL_B18_IS_GPIO
#endif 

#define BALL_A19 PAD_TCON4
#define PAD_TCON4 140
#define GPIO_PAD_140 GPIO139
#ifndef BALL_A19_IS_GPIO
#define BALL_A19_IS_GPIO 0
#endif 
#ifndef PAD_TCON4_IS_GPIO
#define PAD_TCON4_IS_GPIO BALL_A19_IS_GPIO
#endif 

#define BALL_A18 PAD_TCON2
#define PAD_TCON2 138
#define GPIO_PAD_138 GPIO137
#ifndef BALL_A18_IS_GPIO
#define BALL_A18_IS_GPIO 0
#endif 
#ifndef PAD_TCON2_IS_GPIO
#define PAD_TCON2_IS_GPIO BALL_A18_IS_GPIO
#endif 

#define BALL_D16 PAD_GPIO0
#define PAD_GPIO0 61
#define GPIO_PAD_61 GPIO60
#ifndef BALL_D16_IS_GPIO
#define BALL_D16_IS_GPIO 0
#endif 
#ifndef PAD_GPIO0_IS_GPIO
#define PAD_GPIO0_IS_GPIO BALL_D16_IS_GPIO
#endif 

#define PAD_GPIO8 9999
#ifndef PAD_GPIO8_IS_GPIO
#define PAD_GPIO8_IS_GPIO 0
#endif 

#define BALL_F14 PAD_LD_SPI_MOSI
#define PAD_LD_SPI_MOSI 88
#define GPIO_PAD_88 GPIO87
#ifndef BALL_F14_IS_GPIO
#define BALL_F14_IS_GPIO 0
#endif 
#ifndef PAD_LD_SPI_MOSI_IS_GPIO
#define PAD_LD_SPI_MOSI_IS_GPIO BALL_F14_IS_GPIO
#endif 

#define PAD_GPIO13 9999
#ifndef PAD_GPIO13_IS_GPIO
#define PAD_GPIO13_IS_GPIO 0
#endif 

#define PAD_GPIO16 9999
#ifndef PAD_GPIO16_IS_GPIO
#define PAD_GPIO16_IS_GPIO 0
#endif 

#define BALL_F15 PAD_LD_SPI_CK
#define PAD_LD_SPI_CK 85
#define GPIO_PAD_85 GPIO84
#ifndef BALL_F15_IS_GPIO
#define BALL_F15_IS_GPIO 0
#endif 
#ifndef PAD_LD_SPI_CK_IS_GPIO
#define PAD_LD_SPI_CK_IS_GPIO BALL_F15_IS_GPIO
#endif 

#define BALL_D17 PAD_DDCR_CK
#define PAD_DDCR_CK 55
#define GPIO_PAD_55 GPIO54
#ifndef BALL_D17_IS_GPIO
#define BALL_D17_IS_GPIO 0
#endif 
#ifndef PAD_DDCR_CK_IS_GPIO
#define PAD_DDCR_CK_IS_GPIO BALL_D17_IS_GPIO
#endif 

#define BALL_E16 PAD_DDCR_DA
#define PAD_DDCR_DA 56
#define GPIO_PAD_56 GPIO55
#ifndef BALL_E16_IS_GPIO
#define BALL_E16_IS_GPIO 0
#endif 
#ifndef PAD_DDCR_DA_IS_GPIO
#define PAD_DDCR_DA_IS_GPIO BALL_E16_IS_GPIO
#endif 

#define BALL_E15 PAD_LD_SPI_MISO
#define PAD_LD_SPI_MISO 87
#define GPIO_PAD_87 GPIO86
#ifndef BALL_E15_IS_GPIO
#define BALL_E15_IS_GPIO 0
#endif 
#ifndef PAD_LD_SPI_MISO_IS_GPIO
#define PAD_LD_SPI_MISO_IS_GPIO BALL_E15_IS_GPIO
#endif 

#define BALL_D15 PAD_LD_SPI_CS
#define PAD_LD_SPI_CS 86
#define GPIO_PAD_86 GPIO85
#ifndef BALL_D15_IS_GPIO
#define BALL_D15_IS_GPIO 0
#endif 
#ifndef PAD_LD_SPI_CS_IS_GPIO
#define PAD_LD_SPI_CS_IS_GPIO BALL_D15_IS_GPIO
#endif 

#define BALL_B17 PAD_PWM0
#define PAD_PWM0 131
#define GPIO_PAD_131 GPIO130
#ifndef BALL_B17_IS_GPIO
#define BALL_B17_IS_GPIO 0
#endif 
#ifndef PAD_PWM0_IS_GPIO
#define PAD_PWM0_IS_GPIO BALL_B17_IS_GPIO
#endif 

#define BALL_D12 PAD_MIC_SD2
#define PAD_MIC_SD2 92
#define GPIO_PAD_92 GPIO91
#ifndef BALL_D12_IS_GPIO
#define BALL_D12_IS_GPIO 0
#endif 
#ifndef PAD_MIC_SD2_IS_GPIO
#define PAD_MIC_SD2_IS_GPIO BALL_D12_IS_GPIO
#endif 

#define BALL_B16 PAD_PWM2
#define PAD_PWM2 133
#define GPIO_PAD_133 GPIO132
#ifndef BALL_B16_IS_GPIO
#define BALL_B16_IS_GPIO 0
#endif 
#ifndef PAD_PWM2_IS_GPIO
#define PAD_PWM2_IS_GPIO BALL_B16_IS_GPIO
#endif 

#define BALL_D13 PAD_MIC_BCK
#define PAD_MIC_BCK 89
#define GPIO_PAD_89 GPIO88
#ifndef BALL_D13_IS_GPIO
#define BALL_D13_IS_GPIO 0
#endif 
#ifndef PAD_MIC_BCK_IS_GPIO
#define PAD_MIC_BCK_IS_GPIO BALL_D13_IS_GPIO
#endif 

#define BALL_C16 PAD_PWM1
#define PAD_PWM1 132
#define GPIO_PAD_132 GPIO131
#ifndef BALL_C16_IS_GPIO
#define BALL_C16_IS_GPIO 0
#endif 
#ifndef PAD_PWM1_IS_GPIO
#define PAD_PWM1_IS_GPIO BALL_C16_IS_GPIO
#endif 

#define BALL_F12 PAD_MIC_SD0
#define PAD_MIC_SD0 90
#define GPIO_PAD_90 GPIO89
#ifndef BALL_F12_IS_GPIO
#define BALL_F12_IS_GPIO 0
#endif 
#ifndef PAD_MIC_SD0_IS_GPIO
#define PAD_MIC_SD0_IS_GPIO BALL_F12_IS_GPIO
#endif 

#define BALL_E12 PAD_MIC_SD1
#define PAD_MIC_SD1 91
#define GPIO_PAD_91 GPIO90
#ifndef BALL_E12_IS_GPIO
#define BALL_E12_IS_GPIO 0
#endif 
#ifndef PAD_MIC_SD1_IS_GPIO
#define PAD_MIC_SD1_IS_GPIO BALL_E12_IS_GPIO
#endif 

#define BALL_F5 PAD_I2S_OUT_BCK
#define PAD_I2S_OUT_BCK 79
#define GPIO_PAD_79 GPIO78
#ifndef BALL_F5_IS_GPIO
#define BALL_F5_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_BCK_IS_GPIO
#define PAD_I2S_OUT_BCK_IS_GPIO BALL_F5_IS_GPIO
#endif 

#define BALL_H5 PAD_I2S_IN_BCK
#define PAD_I2S_IN_BCK 74
#define GPIO_PAD_74 GPIO73
#ifndef BALL_H5_IS_GPIO
#define BALL_H5_IS_GPIO 0
#endif 
#ifndef PAD_I2S_IN_BCK_IS_GPIO
#define PAD_I2S_IN_BCK_IS_GPIO BALL_H5_IS_GPIO
#endif 

#define BALL_F4 PAD_I2S_OUT_MCK
#define PAD_I2S_OUT_MCK 80
#define GPIO_PAD_80 GPIO79
#ifndef BALL_F4_IS_GPIO
#define BALL_F4_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_MCK_IS_GPIO
#define PAD_I2S_OUT_MCK_IS_GPIO BALL_F4_IS_GPIO
#endif 

#define BALL_E5 PAD_I2S_OUT_SD0
#define PAD_I2S_OUT_SD0 81
#define GPIO_PAD_81 GPIO80
#ifndef BALL_E5_IS_GPIO
#define BALL_E5_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_SD0_IS_GPIO
#define PAD_I2S_OUT_SD0_IS_GPIO BALL_E5_IS_GPIO
#endif 

#define PAD_I2S_IN_DIN0 9999
#ifndef PAD_I2S_IN_DIN0_IS_GPIO
#define PAD_I2S_IN_DIN0_IS_GPIO 0
#endif 

#define BALL_H8 PAD_I2S_OUT_SD1
#define PAD_I2S_OUT_SD1 82
#define GPIO_PAD_82 GPIO81
#ifndef BALL_H8_IS_GPIO
#define BALL_H8_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_SD1_IS_GPIO
#define PAD_I2S_OUT_SD1_IS_GPIO BALL_H8_IS_GPIO
#endif 

#define PAD_I2S_IN_DIN1 9999
#ifndef PAD_I2S_IN_DIN1_IS_GPIO
#define PAD_I2S_IN_DIN1_IS_GPIO 0
#endif 

#define BALL_H4 PAD_I2S_IN_WCK
#define PAD_I2S_IN_WCK 78
#define GPIO_PAD_78 GPIO77
#ifndef BALL_H4_IS_GPIO
#define BALL_H4_IS_GPIO 0
#endif 
#ifndef PAD_I2S_IN_WCK_IS_GPIO
#define PAD_I2S_IN_WCK_IS_GPIO BALL_H4_IS_GPIO
#endif 

#define PAD_GPIO9 9999
#ifndef PAD_GPIO9_IS_GPIO
#define PAD_GPIO9_IS_GPIO 0
#endif 

#define PAD_GPIO11 9999
#ifndef PAD_GPIO11_IS_GPIO
#define PAD_GPIO11_IS_GPIO 0
#endif 

#define PAD_GPIO10 9999
#ifndef PAD_GPIO10_IS_GPIO
#define PAD_GPIO10_IS_GPIO 0
#endif 

#define BALL_H6 PAD_SPDIF_IN
#define PAD_SPDIF_IN 134
#define GPIO_PAD_134 GPIO133
#ifndef BALL_H6_IS_GPIO
#define BALL_H6_IS_GPIO 0
#endif 
#ifndef PAD_SPDIF_IN_IS_GPIO
#define PAD_SPDIF_IN_IS_GPIO BALL_H6_IS_GPIO
#endif 

#define PAD_GPIO12 9999
#ifndef PAD_GPIO12_IS_GPIO
#define PAD_GPIO12_IS_GPIO 0
#endif 

#define BALL_J8 PAD_I2S_OUT_SD2
#define PAD_I2S_OUT_SD2 83
#define GPIO_PAD_83 GPIO82
#ifndef BALL_J8_IS_GPIO
#define BALL_J8_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_SD2_IS_GPIO
#define PAD_I2S_OUT_SD2_IS_GPIO BALL_J8_IS_GPIO
#endif 

#define BALL_H7 PAD_SPDIF_OUT
#define PAD_SPDIF_OUT 135
#define GPIO_PAD_135 GPIO134
#ifndef BALL_H7_IS_GPIO
#define BALL_H7_IS_GPIO 0
#endif 
#ifndef PAD_SPDIF_OUT_IS_GPIO
#define PAD_SPDIF_OUT_IS_GPIO BALL_H7_IS_GPIO
#endif 

#define BALL_E4 PAD_I2S_OUT_WCK
#define PAD_I2S_OUT_WCK 84
#define GPIO_PAD_84 GPIO83
#ifndef BALL_E4_IS_GPIO
#define BALL_E4_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_WCK_IS_GPIO
#define PAD_I2S_OUT_WCK_IS_GPIO BALL_E4_IS_GPIO
#endif 

#define PAD_I2S_IN_DIN2 9999
#ifndef PAD_I2S_IN_DIN2_IS_GPIO
#define PAD_I2S_IN_DIN2_IS_GPIO 0
#endif 

#define BALL_J6 PAD_PWM_PM
#define PAD_PWM_PM 5
#define GPIO_PAD_5 GPIO04
#ifndef BALL_J6_IS_GPIO
#define BALL_J6_IS_GPIO 0
#endif 
#ifndef PAD_PWM_PM_IS_GPIO
#define PAD_PWM_PM_IS_GPIO BALL_J6_IS_GPIO
#endif 

#define BALL_T7 PAD_USB_CTRL
#define PAD_USB_CTRL 10
#define GPIO_PAD_10 GPIO09
#ifndef BALL_T7_IS_GPIO
#define BALL_T7_IS_GPIO 0
#endif 
#ifndef PAD_USB_CTRL_IS_GPIO
#define PAD_USB_CTRL_IS_GPIO BALL_T7_IS_GPIO
#endif 

#define BALL_J5 PAD_IRIN
#define PAD_IRIN 4
#define GPIO_PAD_4 GPIO03
#ifndef BALL_J5_IS_GPIO
#define BALL_J5_IS_GPIO 0
#endif 
#ifndef PAD_IRIN_IS_GPIO
#define PAD_IRIN_IS_GPIO BALL_J5_IS_GPIO
#endif 

#define BALL_L6 PAD_GPIO1_PM
#define PAD_GPIO1_PM 8
#define GPIO_PAD_8 GPIO07
#ifndef BALL_L6_IS_GPIO
#define BALL_L6_IS_GPIO 0
#endif 
#ifndef PAD_GPIO1_PM_IS_GPIO
#define PAD_GPIO1_PM_IS_GPIO BALL_L6_IS_GPIO
#endif 

#define BALL_J7 PAD_GPIO0_PM
#define PAD_GPIO0_PM 7
#define GPIO_PAD_7 GPIO06
#ifndef BALL_J7_IS_GPIO
#define BALL_J7_IS_GPIO 0
#endif 
#ifndef PAD_GPIO0_PM_IS_GPIO
#define PAD_GPIO0_PM_IS_GPIO BALL_J7_IS_GPIO
#endif 

#define BALL_L4 PAD_GPIO2_PM
#define PAD_GPIO2_PM 9
#define GPIO_PAD_9 GPIO08
#ifndef BALL_L4_IS_GPIO
#define BALL_L4_IS_GPIO 0
#endif 
#ifndef PAD_GPIO2_PM_IS_GPIO
#define PAD_GPIO2_PM_IS_GPIO BALL_L4_IS_GPIO
#endif 

#define BALL_M7 PAD_DDCA_CK
#define PAD_DDCA_CK 2
#define GPIO_PAD_2 GPIO01
#ifndef BALL_M7_IS_GPIO
#define BALL_M7_IS_GPIO 0
#endif 
#ifndef PAD_DDCA_CK_IS_GPIO
#define PAD_DDCA_CK_IS_GPIO BALL_M7_IS_GPIO
#endif 

#define BALL_L7 PAD_GPIO5_PM
#define PAD_GPIO5_PM 11
#define GPIO_PAD_11 GPIO10
#ifndef BALL_L7_IS_GPIO
#define BALL_L7_IS_GPIO 0
#endif 
#ifndef PAD_GPIO5_PM_IS_GPIO
#define PAD_GPIO5_PM_IS_GPIO BALL_L7_IS_GPIO
#endif 

#define BALL_M6 PAD_DDCA_DA
#define PAD_DDCA_DA 3
#define GPIO_PAD_3 GPIO02
#ifndef BALL_M6_IS_GPIO
#define BALL_M6_IS_GPIO 0
#endif 
#ifndef PAD_DDCA_DA_IS_GPIO
#define PAD_DDCA_DA_IS_GPIO BALL_M6_IS_GPIO
#endif 

#define BALL_Y6 PAD_GPIO6_PM
#define PAD_GPIO6_PM 12
#define GPIO_PAD_12 GPIO11
#ifndef BALL_Y6_IS_GPIO
#define BALL_Y6_IS_GPIO 0
#endif 
#ifndef PAD_GPIO6_PM_IS_GPIO
#define PAD_GPIO6_PM_IS_GPIO BALL_Y6_IS_GPIO
#endif 

#define BALL_P6 PAD_GPIO7_PM
#define PAD_GPIO7_PM 13
#define GPIO_PAD_13 GPIO12
#ifndef BALL_P6_IS_GPIO
#define BALL_P6_IS_GPIO 0
#endif 
#ifndef PAD_GPIO7_PM_IS_GPIO
#define PAD_GPIO7_PM_IS_GPIO BALL_P6_IS_GPIO
#endif 

#define BALL_P7 PAD_GPIO8_PM
#define PAD_GPIO8_PM 14
#define GPIO_PAD_14 GPIO13
#ifndef BALL_P7_IS_GPIO
#define BALL_P7_IS_GPIO 0
#endif 
#ifndef PAD_GPIO8_PM_IS_GPIO
#define PAD_GPIO8_PM_IS_GPIO BALL_P7_IS_GPIO
#endif 

#define BALL_L5 PAD_GPIO9_PM
#define PAD_GPIO9_PM 15
#define GPIO_PAD_15 GPIO14
#ifndef BALL_L5_IS_GPIO
#define BALL_L5_IS_GPIO 0
#endif 
#ifndef PAD_GPIO9_PM_IS_GPIO
#define PAD_GPIO9_PM_IS_GPIO BALL_L5_IS_GPIO
#endif 

#define BALL_M5 PAD_GPIO10_PM
#define PAD_GPIO10_PM 16
#define GPIO_PAD_16 GPIO15
#ifndef BALL_M5_IS_GPIO
#define BALL_M5_IS_GPIO 0
#endif 
#ifndef PAD_GPIO10_PM_IS_GPIO
#define PAD_GPIO10_PM_IS_GPIO BALL_M5_IS_GPIO
#endif 

#define PAD_GPIO11_PM 9999
#ifndef PAD_GPIO11_PM_IS_GPIO
#define PAD_GPIO11_PM_IS_GPIO 0
#endif 

#define PAD_GPIO12_PM 9999
#ifndef PAD_GPIO12_PM_IS_GPIO
#define PAD_GPIO12_PM_IS_GPIO 0
#endif 

#define BALL_AA7 PAD_DDCDA_CK
#define PAD_DDCDA_CK 35
#define GPIO_PAD_35 GPIO34
#ifndef BALL_AA7_IS_GPIO
#define BALL_AA7_IS_GPIO 0
#endif 
#ifndef PAD_DDCDA_CK_IS_GPIO
#define PAD_DDCDA_CK_IS_GPIO BALL_AA7_IS_GPIO
#endif 

#define BALL_AB7 PAD_DDCDA_DA
#define PAD_DDCDA_DA 36
#define GPIO_PAD_36 GPIO35
#ifndef BALL_AB7_IS_GPIO
#define BALL_AB7_IS_GPIO 0
#endif 
#ifndef PAD_DDCDA_DA_IS_GPIO
#define PAD_DDCDA_DA_IS_GPIO BALL_AB7_IS_GPIO
#endif 

#define PAD_WOL_INT_OUT 9999
#ifndef PAD_WOL_INT_OUT_IS_GPIO
#define PAD_WOL_INT_OUT_IS_GPIO 0
#endif 

#define BALL_Y10 PAD_DDCDB_CK
#define PAD_DDCDB_CK 37
#define GPIO_PAD_37 GPIO36
#ifndef BALL_Y10_IS_GPIO
#define BALL_Y10_IS_GPIO 0
#endif 
#ifndef PAD_DDCDB_CK_IS_GPIO
#define PAD_DDCDB_CK_IS_GPIO BALL_Y10_IS_GPIO
#endif 

#define PAD_GPIO13_PM 9999
#ifndef PAD_GPIO13_PM_IS_GPIO
#define PAD_GPIO13_PM_IS_GPIO 0
#endif 

#define BALL_Y11 PAD_DDCDB_DA
#define PAD_DDCDB_DA 38
#define GPIO_PAD_38 GPIO37
#ifndef BALL_Y11_IS_GPIO
#define BALL_Y11_IS_GPIO 0
#endif 
#ifndef PAD_DDCDB_DA_IS_GPIO
#define PAD_DDCDB_DA_IS_GPIO BALL_Y11_IS_GPIO
#endif 

#define PAD_GPIO14_PM 9999
#ifndef PAD_GPIO14_PM_IS_GPIO
#define PAD_GPIO14_PM_IS_GPIO 0
#endif 

#define PAD_DDCDC_CK 9999
#ifndef PAD_DDCDC_CK_IS_GPIO
#define PAD_DDCDC_CK_IS_GPIO 0
#endif 

#define PAD_GPIO15_PM 9999
#ifndef PAD_GPIO15_PM_IS_GPIO
#define PAD_GPIO15_PM_IS_GPIO 0
#endif 

#define PAD_DDCDC_DA 9999
#ifndef PAD_DDCDC_DA_IS_GPIO
#define PAD_DDCDC_DA_IS_GPIO 0
#endif 

#define PAD_GPIO16_PM 9999
#ifndef PAD_GPIO16_PM_IS_GPIO
#define PAD_GPIO16_PM_IS_GPIO 0
#endif 

#define BALL_AA12 PAD_DDCDD_CK
#define PAD_DDCDD_CK 41
#define GPIO_PAD_41 GPIO40
#ifndef BALL_AA12_IS_GPIO
#define BALL_AA12_IS_GPIO 0
#endif 
#ifndef PAD_DDCDD_CK_IS_GPIO
#define PAD_DDCDD_CK_IS_GPIO BALL_AA12_IS_GPIO
#endif 

#define PAD_GPIO17_PM 9999
#ifndef PAD_GPIO17_PM_IS_GPIO
#define PAD_GPIO17_PM_IS_GPIO 0
#endif 

#define PAD_GPIO18_PM 9999
#ifndef PAD_GPIO18_PM_IS_GPIO
#define PAD_GPIO18_PM_IS_GPIO 0
#endif 

#define BALL_AB12 PAD_DDCDD_DA
#define PAD_DDCDD_DA 42
#define GPIO_PAD_42 GPIO41
#ifndef BALL_AB12_IS_GPIO
#define BALL_AB12_IS_GPIO 0
#endif 
#ifndef PAD_DDCDD_DA_IS_GPIO
#define PAD_DDCDD_DA_IS_GPIO BALL_AB12_IS_GPIO
#endif 

#define PAD_GPIO19_PM 9999
#ifndef PAD_GPIO19_PM_IS_GPIO
#define PAD_GPIO19_PM_IS_GPIO 0
#endif 

#define PAD_GPIO26_PM 9999
#ifndef PAD_GPIO26_PM_IS_GPIO
#define PAD_GPIO26_PM_IS_GPIO 0
#endif 

#define PAD_GPIO20_PM 9999
#ifndef PAD_GPIO20_PM_IS_GPIO
#define PAD_GPIO20_PM_IS_GPIO 0
#endif 

#define PAD_GPIO25_PM 9999
#ifndef PAD_GPIO25_PM_IS_GPIO
#define PAD_GPIO25_PM_IS_GPIO 0
#endif 

#define PAD_GPIO21_PM 9999
#ifndef PAD_GPIO21_PM_IS_GPIO
#define PAD_GPIO21_PM_IS_GPIO 0
#endif 

#define BALL_T2 PAD_VID0
#define PAD_VID0 51
#define GPIO_PAD_51 GPIO50
#ifndef BALL_T2_IS_GPIO
#define BALL_T2_IS_GPIO 0
#endif 
#ifndef PAD_VID0_IS_GPIO
#define PAD_VID0_IS_GPIO BALL_T2_IS_GPIO
#endif 

#define PAD_GPIO22_PM 9999
#ifndef PAD_GPIO22_PM_IS_GPIO
#define PAD_GPIO22_PM_IS_GPIO 0
#endif 

#define BALL_V3 PAD_VID1
#define PAD_VID1 52
#define GPIO_PAD_52 GPIO51
#ifndef BALL_V3_IS_GPIO
#define BALL_V3_IS_GPIO 0
#endif 
#ifndef PAD_VID1_IS_GPIO
#define PAD_VID1_IS_GPIO BALL_V3_IS_GPIO
#endif 

#define PAD_GPIO23_PM 9999
#ifndef PAD_GPIO23_PM_IS_GPIO
#define PAD_GPIO23_PM_IS_GPIO 0
#endif 

#define PAD_VID2 9999
#ifndef PAD_VID2_IS_GPIO
#define PAD_VID2_IS_GPIO 0
#endif 

#define PAD_GPIO24_PM 9999
#ifndef PAD_GPIO24_PM_IS_GPIO
#define PAD_GPIO24_PM_IS_GPIO 0
#endif 

#define BALL_Y8 PAD_CEC0
#define PAD_CEC0 6
#define GPIO_PAD_6 GPIO05
#ifndef BALL_Y8_IS_GPIO
#define BALL_Y8_IS_GPIO 0
#endif 
#ifndef PAD_CEC0_IS_GPIO
#define PAD_CEC0_IS_GPIO BALL_Y8_IS_GPIO
#endif 

#define BALL_P4 PAD_SAR0
#define PAD_SAR0 43
#define GPIO_PAD_43 GPIO42
#ifndef BALL_P4_IS_GPIO
#define BALL_P4_IS_GPIO 0
#endif 
#ifndef PAD_SAR0_IS_GPIO
#define PAD_SAR0_IS_GPIO BALL_P4_IS_GPIO
#endif 

#define BALL_P5 PAD_SAR1
#define PAD_SAR1 44
#define GPIO_PAD_44 GPIO43
#ifndef BALL_P5_IS_GPIO
#define BALL_P5_IS_GPIO 0
#endif 
#ifndef PAD_SAR1_IS_GPIO
#define PAD_SAR1_IS_GPIO BALL_P5_IS_GPIO
#endif 

#define BALL_R5 PAD_SAR2
#define PAD_SAR2 45
#define GPIO_PAD_45 GPIO44
#ifndef BALL_R5_IS_GPIO
#define BALL_R5_IS_GPIO 0
#endif 
#ifndef PAD_SAR2_IS_GPIO
#define PAD_SAR2_IS_GPIO BALL_R5_IS_GPIO
#endif 

#define BALL_R6 PAD_SAR3
#define PAD_SAR3 46
#define GPIO_PAD_46 GPIO45
#ifndef BALL_R6_IS_GPIO
#define BALL_R6_IS_GPIO 0
#endif 
#ifndef PAD_SAR3_IS_GPIO
#define PAD_SAR3_IS_GPIO BALL_R6_IS_GPIO
#endif 

#define PAD_SAR4 9999
#ifndef PAD_SAR4_IS_GPIO
#define PAD_SAR4_IS_GPIO 0
#endif 

#define BALL_R7 PAD_VPLUGIN
#define PAD_VPLUGIN 48
#define GPIO_PAD_48 GPIO47
#ifndef BALL_R7_IS_GPIO
#define BALL_R7_IS_GPIO 0
#endif 
#ifndef PAD_VPLUGIN_IS_GPIO
#define PAD_VPLUGIN_IS_GPIO BALL_R7_IS_GPIO
#endif 

#define BALL_W12 PAD_HDMIRX_ARCTX
#define PAD_HDMIRX_ARCTX 182
#define GPIO_PAD_182 GPIO181
#ifndef BALL_W12_IS_GPIO
#define BALL_W12_IS_GPIO 0
#endif 
#ifndef PAD_HDMIRX_ARCTX_IS_GPIO
#define PAD_HDMIRX_ARCTX_IS_GPIO BALL_W12_IS_GPIO
#endif 

#define BALL_AD18 PAD_TGPIO3
#define PAD_TGPIO3 144
#define GPIO_PAD_144 GPIO143
#ifndef BALL_AD18_IS_GPIO
#define BALL_AD18_IS_GPIO 0
#endif 
#ifndef PAD_TGPIO3_IS_GPIO
#define PAD_TGPIO3_IS_GPIO BALL_AD18_IS_GPIO
#endif 

#define BALL_AE18 PAD_TGPIO2
#define PAD_TGPIO2 143
#define GPIO_PAD_143 GPIO142
#ifndef BALL_AE18_IS_GPIO
#define BALL_AE18_IS_GPIO 0
#endif 
#ifndef PAD_TGPIO2_IS_GPIO
#define PAD_TGPIO2_IS_GPIO BALL_AE18_IS_GPIO
#endif 

#define PAD_TGPIO1 9999
#ifndef PAD_TGPIO1_IS_GPIO
#define PAD_TGPIO1_IS_GPIO 0
#endif 

#define PAD_TGPIO0 9999
#ifndef PAD_TGPIO0_IS_GPIO
#define PAD_TGPIO0_IS_GPIO 0
#endif 

#define BALL_AC19 PAD_PCM2_IRQA_N
#define PAD_PCM2_IRQA_N 95
#define GPIO_PAD_95 GPIO94
#ifndef BALL_AC19_IS_GPIO
#define BALL_AC19_IS_GPIO 0
#endif 
#ifndef PAD_PCM2_IRQA_N_IS_GPIO
#define PAD_PCM2_IRQA_N_IS_GPIO BALL_AC19_IS_GPIO
#endif 

#define PAD_PCM2_WAIT_N 9999
#ifndef PAD_PCM2_WAIT_N_IS_GPIO
#define PAD_PCM2_WAIT_N_IS_GPIO 0
#endif 

#define BALL_AD19 PAD_PCM2_RESET
#define PAD_PCM2_RESET 96
#define GPIO_PAD_96 GPIO95
#ifndef BALL_AD19_IS_GPIO
#define BALL_AD19_IS_GPIO 0
#endif 
#ifndef PAD_PCM2_RESET_IS_GPIO
#define PAD_PCM2_RESET_IS_GPIO BALL_AD19_IS_GPIO
#endif 

#define BALL_AC18 PAD_PCM2_CE_N
#define PAD_PCM2_CE_N 94
#define GPIO_PAD_94 GPIO93
#ifndef BALL_AC18_IS_GPIO
#define BALL_AC18_IS_GPIO 0
#endif 
#ifndef PAD_PCM2_CE_N_IS_GPIO
#define PAD_PCM2_CE_N_IS_GPIO BALL_AC18_IS_GPIO
#endif 

#define BALL_AD20 PAD_PCM2_CD_N
#define PAD_PCM2_CD_N 93
#define GPIO_PAD_93 GPIO92
#ifndef BALL_AD20_IS_GPIO
#define BALL_AD20_IS_GPIO 0
#endif 
#ifndef PAD_PCM2_CD_N_IS_GPIO
#define PAD_PCM2_CD_N_IS_GPIO BALL_AD20_IS_GPIO
#endif 

#define PAD_TS2_D7 9999
#ifndef PAD_TS2_D7_IS_GPIO
#define PAD_TS2_D7_IS_GPIO 0
#endif 

#define PAD_TS2_D5 9999
#ifndef PAD_TS2_D5_IS_GPIO
#define PAD_TS2_D5_IS_GPIO 0
#endif 

#define PAD_TS2_D6 9999
#ifndef PAD_TS2_D6_IS_GPIO
#define PAD_TS2_D6_IS_GPIO 0
#endif 

#define PAD_TS2_D4 9999
#ifndef PAD_TS2_D4_IS_GPIO
#define PAD_TS2_D4_IS_GPIO 0
#endif 

#define BALL_U21 PAD_PCM_CD_N
#define PAD_PCM_CD_N 113
#define GPIO_PAD_113 GPIO112
#ifndef BALL_U21_IS_GPIO
#define BALL_U21_IS_GPIO 0
#endif 
#ifndef PAD_PCM_CD_N_IS_GPIO
#define PAD_PCM_CD_N_IS_GPIO BALL_U21_IS_GPIO
#endif 

#define PAD_TS2_D3 9999
#ifndef PAD_TS2_D3_IS_GPIO
#define PAD_TS2_D3_IS_GPIO 0
#endif 

#define BALL_AB20 PAD_PCM_REG_N
#define PAD_PCM_REG_N 127
#define GPIO_PAD_127 GPIO126
#ifndef BALL_AB20_IS_GPIO
#define BALL_AB20_IS_GPIO 0
#endif 
#ifndef PAD_PCM_REG_N_IS_GPIO
#define PAD_PCM_REG_N_IS_GPIO BALL_AB20_IS_GPIO
#endif 

#define PAD_TS2_D2 9999
#ifndef PAD_TS2_D2_IS_GPIO
#define PAD_TS2_D2_IS_GPIO 0
#endif 

#define BALL_W21 PAD_PCM_OE_N
#define PAD_PCM_OE_N 126
#define GPIO_PAD_126 GPIO125
#ifndef BALL_W21_IS_GPIO
#define BALL_W21_IS_GPIO 0
#endif 
#ifndef PAD_PCM_OE_N_IS_GPIO
#define PAD_PCM_OE_N_IS_GPIO BALL_W21_IS_GPIO
#endif 

#define PAD_TS2_D1 9999
#ifndef PAD_TS2_D1_IS_GPIO
#define PAD_TS2_D1_IS_GPIO 0
#endif 

#define BALL_T20 PAD_PCM_IRQA_N
#define PAD_PCM_IRQA_N 125
#define GPIO_PAD_125 GPIO124
#ifndef BALL_T20_IS_GPIO
#define BALL_T20_IS_GPIO 0
#endif 
#ifndef PAD_PCM_IRQA_N_IS_GPIO
#define PAD_PCM_IRQA_N_IS_GPIO BALL_T20_IS_GPIO
#endif 

#define BALL_AD21 PAD_TS2_D0
#define PAD_TS2_D0 168
#define GPIO_PAD_168 GPIO167
#ifndef BALL_AD21_IS_GPIO
#define BALL_AD21_IS_GPIO 0
#endif 
#ifndef PAD_TS2_D0_IS_GPIO
#define PAD_TS2_D0_IS_GPIO BALL_AD21_IS_GPIO
#endif 

#define BALL_AB19 PAD_PCM_IOWR_N
#define PAD_PCM_IOWR_N 124
#define GPIO_PAD_124 GPIO123
#ifndef BALL_AB19_IS_GPIO
#define BALL_AB19_IS_GPIO 0
#endif 
#ifndef PAD_PCM_IOWR_N_IS_GPIO
#define PAD_PCM_IOWR_N_IS_GPIO BALL_AB19_IS_GPIO
#endif 

#define BALL_AE21 PAD_TS2_CLK
#define PAD_TS2_CLK 167
#define GPIO_PAD_167 GPIO166
#ifndef BALL_AE21_IS_GPIO
#define BALL_AE21_IS_GPIO 0
#endif 
#ifndef PAD_TS2_CLK_IS_GPIO
#define PAD_TS2_CLK_IS_GPIO BALL_AE21_IS_GPIO
#endif 

#define BALL_AA21 PAD_PCM_IORD_N
#define PAD_PCM_IORD_N 123
#define GPIO_PAD_123 GPIO122
#ifndef BALL_AA21_IS_GPIO
#define BALL_AA21_IS_GPIO 0
#endif 
#ifndef PAD_PCM_IORD_N_IS_GPIO
#define PAD_PCM_IORD_N_IS_GPIO BALL_AA21_IS_GPIO
#endif 

#define BALL_R20 PAD_PCM_CE_N
#define PAD_PCM_CE_N 114
#define GPIO_PAD_114 GPIO113
#ifndef BALL_R20_IS_GPIO
#define BALL_R20_IS_GPIO 0
#endif 
#ifndef PAD_PCM_CE_N_IS_GPIO
#define PAD_PCM_CE_N_IS_GPIO BALL_R20_IS_GPIO
#endif 

#define BALL_AB21 PAD_PCM_D2
#define PAD_PCM_D2 117
#define GPIO_PAD_117 GPIO116
#ifndef BALL_AB21_IS_GPIO
#define BALL_AB21_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D2_IS_GPIO
#define PAD_PCM_D2_IS_GPIO BALL_AB21_IS_GPIO
#endif 

#define BALL_AC21 PAD_TS2_VLD
#define PAD_TS2_VLD 177
#define GPIO_PAD_177 GPIO176
#ifndef BALL_AC21_IS_GPIO
#define BALL_AC21_IS_GPIO 0
#endif 
#ifndef PAD_TS2_VLD_IS_GPIO
#define PAD_TS2_VLD_IS_GPIO BALL_AC21_IS_GPIO
#endif 

#define BALL_R21 PAD_PCM_D1
#define PAD_PCM_D1 116
#define GPIO_PAD_116 GPIO115
#ifndef BALL_R21_IS_GPIO
#define BALL_R21_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D1_IS_GPIO
#define PAD_PCM_D1_IS_GPIO BALL_R21_IS_GPIO
#endif 

#define BALL_AC20 PAD_TS2_SYNC
#define PAD_TS2_SYNC 176
#define GPIO_PAD_176 GPIO175
#ifndef BALL_AC20_IS_GPIO
#define BALL_AC20_IS_GPIO 0
#endif 
#ifndef PAD_TS2_SYNC_IS_GPIO
#define PAD_TS2_SYNC_IS_GPIO BALL_AC20_IS_GPIO
#endif 

#define BALL_Y22 PAD_PCM_D0
#define PAD_PCM_D0 115
#define GPIO_PAD_115 GPIO114
#ifndef BALL_Y22_IS_GPIO
#define BALL_Y22_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D0_IS_GPIO
#define PAD_PCM_D0_IS_GPIO BALL_Y22_IS_GPIO
#endif 

#define BALL_U20 PAD_PCM_WE_N
#define PAD_PCM_WE_N 130
#define GPIO_PAD_130 GPIO129
#ifndef BALL_U20_IS_GPIO
#define BALL_U20_IS_GPIO 0
#endif 
#ifndef PAD_PCM_WE_N_IS_GPIO
#define PAD_PCM_WE_N_IS_GPIO BALL_U20_IS_GPIO
#endif 

#define BALL_U24 PAD_PCM_A14
#define PAD_PCM_A14 112
#define GPIO_PAD_112 GPIO111
#ifndef BALL_U24_IS_GPIO
#define BALL_U24_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A14_IS_GPIO
#define PAD_PCM_A14_IS_GPIO BALL_U24_IS_GPIO
#endif 

#define BALL_T22 PAD_PCM_WAIT_N
#define PAD_PCM_WAIT_N 129
#define GPIO_PAD_129 GPIO128
#ifndef BALL_T22_IS_GPIO
#define BALL_T22_IS_GPIO 0
#endif 
#ifndef PAD_PCM_WAIT_N_IS_GPIO
#define PAD_PCM_WAIT_N_IS_GPIO BALL_T22_IS_GPIO
#endif 

#define BALL_W22 PAD_PCM_A13
#define PAD_PCM_A13 111
#define GPIO_PAD_111 GPIO110
#ifndef BALL_W22_IS_GPIO
#define BALL_W22_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A13_IS_GPIO
#define PAD_PCM_A13_IS_GPIO BALL_W22_IS_GPIO
#endif 

#define BALL_V20 PAD_PCM_RESET
#define PAD_PCM_RESET 128
#define GPIO_PAD_128 GPIO127
#ifndef BALL_V20_IS_GPIO
#define BALL_V20_IS_GPIO 0
#endif 
#ifndef PAD_PCM_RESET_IS_GPIO
#define PAD_PCM_RESET_IS_GPIO BALL_V20_IS_GPIO
#endif 

#define BALL_R22 PAD_PCM_A12
#define PAD_PCM_A12 110
#define GPIO_PAD_110 GPIO109
#ifndef BALL_R22_IS_GPIO
#define BALL_R22_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A12_IS_GPIO
#define PAD_PCM_A12_IS_GPIO BALL_R22_IS_GPIO
#endif 

#define BALL_U22 PAD_PCM_D7
#define PAD_PCM_D7 122
#define GPIO_PAD_122 GPIO121
#ifndef BALL_U22_IS_GPIO
#define BALL_U22_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D7_IS_GPIO
#define PAD_PCM_D7_IS_GPIO BALL_U22_IS_GPIO
#endif 

#define BALL_AB22 PAD_PCM_A11
#define PAD_PCM_A11 109
#define GPIO_PAD_109 GPIO108
#ifndef BALL_AB22_IS_GPIO
#define BALL_AB22_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A11_IS_GPIO
#define PAD_PCM_A11_IS_GPIO BALL_AB22_IS_GPIO
#endif 

#define BALL_W20 PAD_PCM_D6
#define PAD_PCM_D6 121
#define GPIO_PAD_121 GPIO120
#ifndef BALL_W20_IS_GPIO
#define BALL_W20_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D6_IS_GPIO
#define PAD_PCM_D6_IS_GPIO BALL_W20_IS_GPIO
#endif 

#define BALL_AA19 PAD_PCM_A10
#define PAD_PCM_A10 108
#define GPIO_PAD_108 GPIO107
#ifndef BALL_AA19_IS_GPIO
#define BALL_AA19_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A10_IS_GPIO
#define PAD_PCM_A10_IS_GPIO BALL_AA19_IS_GPIO
#endif 

#define BALL_Y19 PAD_PCM_D5
#define PAD_PCM_D5 120
#define GPIO_PAD_120 GPIO119
#ifndef BALL_Y19_IS_GPIO
#define BALL_Y19_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D5_IS_GPIO
#define PAD_PCM_D5_IS_GPIO BALL_Y19_IS_GPIO
#endif 

#define BALL_T21 PAD_PCM_A9
#define PAD_PCM_A9 107
#define GPIO_PAD_107 GPIO106
#ifndef BALL_T21_IS_GPIO
#define BALL_T21_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A9_IS_GPIO
#define PAD_PCM_A9_IS_GPIO BALL_T21_IS_GPIO
#endif 

#define BALL_Y20 PAD_PCM_D4
#define PAD_PCM_D4 119
#define GPIO_PAD_119 GPIO118
#ifndef BALL_Y20_IS_GPIO
#define BALL_Y20_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D4_IS_GPIO
#define PAD_PCM_D4_IS_GPIO BALL_Y20_IS_GPIO
#endif 

#define BALL_AA20 PAD_PCM_A8
#define PAD_PCM_A8 106
#define GPIO_PAD_106 GPIO105
#ifndef BALL_AA20_IS_GPIO
#define BALL_AA20_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A8_IS_GPIO
#define PAD_PCM_A8_IS_GPIO BALL_AA20_IS_GPIO
#endif 

#define BALL_Y21 PAD_PCM_D3
#define PAD_PCM_D3 118
#define GPIO_PAD_118 GPIO117
#ifndef BALL_Y21_IS_GPIO
#define BALL_Y21_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D3_IS_GPIO
#define PAD_PCM_D3_IS_GPIO BALL_Y21_IS_GPIO
#endif 

#define BALL_Y24 PAD_PCM_A7
#define PAD_PCM_A7 105
#define GPIO_PAD_105 GPIO104
#ifndef BALL_Y24_IS_GPIO
#define BALL_Y24_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A7_IS_GPIO
#define PAD_PCM_A7_IS_GPIO BALL_Y24_IS_GPIO
#endif 

#define BALL_W24 PAD_PCM_A3
#define PAD_PCM_A3 101
#define GPIO_PAD_101 GPIO100
#ifndef BALL_W24_IS_GPIO
#define BALL_W24_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A3_IS_GPIO
#define PAD_PCM_A3_IS_GPIO BALL_W24_IS_GPIO
#endif 

#define BALL_V24 PAD_PCM_A6
#define PAD_PCM_A6 104
#define GPIO_PAD_104 GPIO103
#ifndef BALL_V24_IS_GPIO
#define BALL_V24_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A6_IS_GPIO
#define PAD_PCM_A6_IS_GPIO BALL_V24_IS_GPIO
#endif 

#define BALL_W25 PAD_PCM_A2
#define PAD_PCM_A2 100
#define GPIO_PAD_100 GPIO99
#ifndef BALL_W25_IS_GPIO
#define BALL_W25_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A2_IS_GPIO
#define PAD_PCM_A2_IS_GPIO BALL_W25_IS_GPIO
#endif 

#define BALL_W23 PAD_PCM_A5
#define PAD_PCM_A5 103
#define GPIO_PAD_103 GPIO102
#ifndef BALL_W23_IS_GPIO
#define BALL_W23_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A5_IS_GPIO
#define PAD_PCM_A5_IS_GPIO BALL_W23_IS_GPIO
#endif 

#define BALL_V23 PAD_PCM_A1
#define PAD_PCM_A1 99
#define GPIO_PAD_99 GPIO98
#ifndef BALL_V23_IS_GPIO
#define BALL_V23_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A1_IS_GPIO
#define PAD_PCM_A1_IS_GPIO BALL_V23_IS_GPIO
#endif 

#define BALL_U23 PAD_PCM_A4
#define PAD_PCM_A4 102
#define GPIO_PAD_102 GPIO101
#ifndef BALL_U23_IS_GPIO
#define BALL_U23_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A4_IS_GPIO
#define PAD_PCM_A4_IS_GPIO BALL_U23_IS_GPIO
#endif 

#define BALL_V25 PAD_PCM_A0
#define PAD_PCM_A0 98
#define GPIO_PAD_98 GPIO97
#ifndef BALL_V25_IS_GPIO
#define BALL_V25_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A0_IS_GPIO
#define PAD_PCM_A0_IS_GPIO BALL_V25_IS_GPIO
#endif 

#define BALL_Y18 PAD_TS0_D7
#define PAD_TS0_D7 153
#define GPIO_PAD_153 GPIO152
#ifndef BALL_Y18_IS_GPIO
#define BALL_Y18_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D7_IS_GPIO
#define PAD_TS0_D7_IS_GPIO BALL_Y18_IS_GPIO
#endif 

#define BALL_Y17 PAD_TS0_D6
#define PAD_TS0_D6 152
#define GPIO_PAD_152 GPIO151
#ifndef BALL_Y17_IS_GPIO
#define BALL_Y17_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D6_IS_GPIO
#define PAD_TS0_D6_IS_GPIO BALL_Y17_IS_GPIO
#endif 

#define BALL_Y14 PAD_TS0_D5
#define PAD_TS0_D5 151
#define GPIO_PAD_151 GPIO150
#ifndef BALL_Y14_IS_GPIO
#define BALL_Y14_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D5_IS_GPIO
#define PAD_TS0_D5_IS_GPIO BALL_Y14_IS_GPIO
#endif 

#define BALL_AB17 PAD_TS0_D4
#define PAD_TS0_D4 150
#define GPIO_PAD_150 GPIO149
#ifndef BALL_AB17_IS_GPIO
#define BALL_AB17_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D4_IS_GPIO
#define PAD_TS0_D4_IS_GPIO BALL_AB17_IS_GPIO
#endif 

#define BALL_Y16 PAD_TS0_D3
#define PAD_TS0_D3 149
#define GPIO_PAD_149 GPIO148
#ifndef BALL_Y16_IS_GPIO
#define BALL_Y16_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D3_IS_GPIO
#define PAD_TS0_D3_IS_GPIO BALL_Y16_IS_GPIO
#endif 

#define BALL_AB16 PAD_TS0_D2
#define PAD_TS0_D2 148
#define GPIO_PAD_148 GPIO147
#ifndef BALL_AB16_IS_GPIO
#define BALL_AB16_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D2_IS_GPIO
#define PAD_TS0_D2_IS_GPIO BALL_AB16_IS_GPIO
#endif 

#define BALL_Y15 PAD_TS0_D1
#define PAD_TS0_D1 147
#define GPIO_PAD_147 GPIO146
#ifndef BALL_Y15_IS_GPIO
#define BALL_Y15_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D1_IS_GPIO
#define PAD_TS0_D1_IS_GPIO BALL_Y15_IS_GPIO
#endif 

#define BALL_AA17 PAD_TS0_D0
#define PAD_TS0_D0 146
#define GPIO_PAD_146 GPIO145
#ifndef BALL_AA17_IS_GPIO
#define BALL_AA17_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D0_IS_GPIO
#define PAD_TS0_D0_IS_GPIO BALL_AA17_IS_GPIO
#endif 

#define BALL_AB15 PAD_TS0_VLD
#define PAD_TS0_VLD 155
#define GPIO_PAD_155 GPIO154
#ifndef BALL_AB15_IS_GPIO
#define BALL_AB15_IS_GPIO 0
#endif 
#ifndef PAD_TS0_VLD_IS_GPIO
#define PAD_TS0_VLD_IS_GPIO BALL_AB15_IS_GPIO
#endif 

#define BALL_AA16 PAD_TS0_SYNC
#define PAD_TS0_SYNC 154
#define GPIO_PAD_154 GPIO153
#ifndef BALL_AA16_IS_GPIO
#define BALL_AA16_IS_GPIO 0
#endif 
#ifndef PAD_TS0_SYNC_IS_GPIO
#define PAD_TS0_SYNC_IS_GPIO BALL_AA16_IS_GPIO
#endif 

#define BALL_AA15 PAD_TS0_CLK
#define PAD_TS0_CLK 145
#define GPIO_PAD_145 GPIO144
#ifndef BALL_AA15_IS_GPIO
#define BALL_AA15_IS_GPIO 0
#endif 
#ifndef PAD_TS0_CLK_IS_GPIO
#define PAD_TS0_CLK_IS_GPIO BALL_AA15_IS_GPIO
#endif 

#define BALL_T23 PAD_TS1_D7
#define PAD_TS1_D7 164
#define GPIO_PAD_164 GPIO163
#ifndef BALL_T23_IS_GPIO
#define BALL_T23_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D7_IS_GPIO
#define PAD_TS1_D7_IS_GPIO BALL_T23_IS_GPIO
#endif 

#define BALL_R24 PAD_TS1_D6
#define PAD_TS1_D6 163
#define GPIO_PAD_163 GPIO162
#ifndef BALL_R24_IS_GPIO
#define BALL_R24_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D6_IS_GPIO
#define PAD_TS1_D6_IS_GPIO BALL_R24_IS_GPIO
#endif 

#define BALL_R23 PAD_TS1_D5
#define PAD_TS1_D5 162
#define GPIO_PAD_162 GPIO161
#ifndef BALL_R23_IS_GPIO
#define BALL_R23_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D5_IS_GPIO
#define PAD_TS1_D5_IS_GPIO BALL_R23_IS_GPIO
#endif 

#define BALL_P24 PAD_TS1_D4
#define PAD_TS1_D4 161
#define GPIO_PAD_161 GPIO160
#ifndef BALL_P24_IS_GPIO
#define BALL_P24_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D4_IS_GPIO
#define PAD_TS1_D4_IS_GPIO BALL_P24_IS_GPIO
#endif 

#define BALL_P23 PAD_TS1_D3
#define PAD_TS1_D3 160
#define GPIO_PAD_160 GPIO159
#ifndef BALL_P23_IS_GPIO
#define BALL_P23_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D3_IS_GPIO
#define PAD_TS1_D3_IS_GPIO BALL_P23_IS_GPIO
#endif 

#define BALL_N25 PAD_TS1_D2
#define PAD_TS1_D2 159
#define GPIO_PAD_159 GPIO158
#ifndef BALL_N25_IS_GPIO
#define BALL_N25_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D2_IS_GPIO
#define PAD_TS1_D2_IS_GPIO BALL_N25_IS_GPIO
#endif 

#define BALL_N24 PAD_TS1_D1
#define PAD_TS1_D1 158
#define GPIO_PAD_158 GPIO157
#ifndef BALL_N24_IS_GPIO
#define BALL_N24_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D1_IS_GPIO
#define PAD_TS1_D1_IS_GPIO BALL_N24_IS_GPIO
#endif 

#define BALL_N23 PAD_TS1_D0
#define PAD_TS1_D0 157
#define GPIO_PAD_157 GPIO156
#ifndef BALL_N23_IS_GPIO
#define BALL_N23_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D0_IS_GPIO
#define PAD_TS1_D0_IS_GPIO BALL_N23_IS_GPIO
#endif 

#define BALL_M25 PAD_TS1_VLD
#define PAD_TS1_VLD 166
#define GPIO_PAD_166 GPIO165
#ifndef BALL_M25_IS_GPIO
#define BALL_M25_IS_GPIO 0
#endif 
#ifndef PAD_TS1_VLD_IS_GPIO
#define PAD_TS1_VLD_IS_GPIO BALL_M25_IS_GPIO
#endif 

#define BALL_M24 PAD_TS1_SYNC
#define PAD_TS1_SYNC 165
#define GPIO_PAD_165 GPIO164
#ifndef BALL_M24_IS_GPIO
#define BALL_M24_IS_GPIO 0
#endif 
#ifndef PAD_TS1_SYNC_IS_GPIO
#define PAD_TS1_SYNC_IS_GPIO BALL_M24_IS_GPIO
#endif 

#define BALL_M23 PAD_TS1_CLK
#define PAD_TS1_CLK 156
#define GPIO_PAD_156 GPIO155
#ifndef BALL_M23_IS_GPIO
#define BALL_M23_IS_GPIO 0
#endif 
#ifndef PAD_TS1_CLK_IS_GPIO
#define PAD_TS1_CLK_IS_GPIO BALL_M23_IS_GPIO
#endif 


// PADS group name to index
#define PADS_PCMCONFIG_MODE1        1223
#define PADS_PCMCONFIG_MODE2        1224
#define PADS_PCMCONFIG1_MODE1       1225
#define PADS_PCMCONFIG1_MODE2       1226
#define PADS_PCMCONFIG1_MODE3       1227
#define PADS_PCM2CONFIG_MODE1       1228
#define PADS_PCM2CONFIG_MODE2       1229
#define PADS_PCM2CONFIG_MODE3       1230
#define PADS_PCM2CONFIG1_MODE1      1231
#define PADS_PCM2CONFIG1_MODE2      1232
#define PADS_ET_MODE1               1233
#define PADS_ET_MODE2               1234
#define PADS_DDCR                   1235
#define PADS_DDCR2                  1236
#define PADS_PCM                    1237

// chip capbilities
#define CHIP_HAS_BT656_IN           0
#define CHIP_HAS_TS0                1
#define CHIP_HAS_TS1                0
#define CHIP_HAS_LVDS_10BIT_X2      1
#define CHIP_HAS_LVDS_8BIT_X2       1
#define CHIP_HAS_LVDS_8BIT_X1       1
#define CHIP_HAS_CIMAX              0
#define CHIP_HAS_USB_P0             1
#define CHIP_HAS_USB_P1             1
#define CHIP_HAS_USBVBUS0           0
#define CHIP_HAS_USBVBUS1           0
#define CHIP_HAS_UART1_MODE1        1
#define CHIP_HAS_UART1_MODE2        1
#define CHIP_HAS_UART1_MODE3        1
#define CHIP_HAS_PCMCIA1            0
#define CHIP_HAS_PCMCIA2            0
#define CHIP_HAS_PCMCIA             0
#define CHIP_HAS_UART2_MODE1        1
#define CHIP_HAS_UART2_MODE2        1
#define CHIP_HAS_UART2_MODE3        1
#define CHIP_HAS_RGB_A              1
#define CHIP_HAS_RGB_B              1
#define CHIP_HAS_RGB_C              1
#define CHIP_HAS_HDMI_A             1
#define CHIP_HAS_HDMI_B             1
#define CHIP_HAS_HDMI_C             1
#define CHIP_HAS_SPI_CZ1            1
#define CHIP_HAS_SPI_CZ2            0
#define CHIP_HAS_SPI_CZ3            0
#define CHIP_HAS_DDCR               1
#define CHIP_HAS_DDCR2              1
#define CHIP_HAS_TCON               1
#define CHIP_HAS_ET_MODE0_MII       1
#define CHIP_HAS_ET_MODE0_RMII      1
#define CHIP_HAS_ET_MODE1_MII       1
#define CHIP_HAS_ET_MODE1_RMII      1
#define CHIP_HAS_ET_MODE2_MII       1
#define CHIP_HAS_ET_MODE2_RMII      1
#define CHIP_HAS_I2S_IN             0
#define CHIP_HAS_I2S_OUT            0
#define CHIP_HAS_SPDIF_IN           0
#define CHIP_HAS_SPDIF_OUT          0
#define CHIP_HAS_DDR_A_CMD          1
#define CHIP_HAS_DDR_A_DATA         1
#define CHIP_HAS_DDR_B_CMD          1
#define CHIP_HAS_DDR_B_DATA         1
#define CHIP_USE_PCM_CDN_IN_PCM2    0
#define CHIP_USE_I2S_IN_IN_PCM      0
#define CHIP_USE_I2S_OUT_IN_PCM     0
#define CHIP_USE_SPDIF_IN_IN_PCM    0
#define CHIP_USE_SPDIF_OUT_IN_PCM   0
#define CHIP_USE_IIC_IN_DDCR2       0
#define CHIP_USE_PWM2_IN_GPIO14     0
#define CHIP_USE_PWM3_IN_GPIO15     0

// chip additional information
#define CHIP_FAMILY_TYPE            CHIP_FAMILY_M7332

#endif /* _MT5870GYYTYY_H_*/
