#include "halSEAL.h"
#include "../../drvSEAL.h"

#define __delay() ()

//Non PM IP group
#define SEAL_NON_PM_GROUP0 \
    E_SEAL_RIU_DBG_PROT_NONPM, \
    E_SEAL_POR_STATUS_PROT_NONPM , \
    E_SEAL_INTR_CPUINT_PROT_NONPM, \
    E_SEAL_MIU2_PROT_NONPM, \
    E_SEAL_USB0_PROT_NONPM, \
    E_SEAL_USB1_PROT_NONPM, \
    E_SEAL_UPLL0_PROT_NONPM, \
    E_SEAL_UPLL1_PROT_NONPM, \
    E_SEAL_BDMA_CH0_PROT_NONPM, \
    E_SEAL_BDMA_CH1_PROT_NONPM, \
    E_SEAL_UART3_PROT_NONPM, \
    E_SEAL_UART0_PROT_NONPM, \
    E_SEAL_CLKGEN2_PROT_NONPM, \
    E_SEAL_CLKGEN0_PROT_NONPM, \
    E_SEAL_DSCRMB_PROT_NONPM, \
    E_SEAL_UHC1_PROT_NONPM

#define SEAL_NON_PM_GROUP1 \
    E_SEAL_ACP_PROT_NONPM, \
    E_SEAL_SPI_PRE_ARB_PROT_NONPM, \
    E_SEAL_INTR_CTRL1_PROT_NONPM, \
    E_SEAL_MVD_PROT_NONPM, \
    E_SEAL_MIU_PROT_NONPM, \
    E_SEAL_MVOPSUB_PROT_NONPM, \
    E_SEAL_MVOP_PROT_NONPM, \
    E_SEAL_TSP0_PROT_NONPM, \
    E_SEAL_TSP1_PROT_NONPM, \
    E_SEAL_TSP_SPARE_PROT_NONPM, \
    E_SEAL_SEMAPH_PROT_NONPM ,\
    E_SEAL_L3_AXI_PROT_NONPM, \
    E_SEAL_INTR_CTRL_PROT_NONPM, \
    E_SEAL_BYTE2WORD_PROT_PM, \
    E_SEAL_HVD_PROT_NONPM, \
    E_SEAL_TSP2_PROT_NONPM

#define SEAL_NON_PM_GROUP2 \
    E_SEAL_MCU_ARM_PROT_NONPM, \
    E_SEAL_CHIP_PROT_NONPM, \
    E_SEAL_GOP_PROT_NONPM, \
    E_SEAL_EMAC0_PROT_NONPM, \
    E_SEAL_EMAC1_PROT_NONPM, \
    E_SEAL_EMAC2_PROT_NONPM, \
    E_SEAL_EMAC3_PROT_NONPM, \
    E_SEAL_UHC0_PROT_NONPM,  \
    E_SEAL_ADC_ATOP_PROT_NONPM, \
    E_SEAL_ADC_DTOP_PROT_NONPM, \
    E_SEAL_CODEC_SPARE_PROT_NONPM, \
    E_SEAL_GE0_PROT_NONPM, \
    E_SEAL_SMART_PROT_NONPM, \
    E_SEAL_MHEG5_SPARE_PROT_NONPM, \
    E_SEAL_CHIPGPIO_PROT_NONPM, \
    E_SEAL_FSC1_PROT_PM

#define SEAL_NON_PM_GROUP3 \
    E_SEAL_LDM_DMA0_PROT_NONPM, \
    E_SEAL_LDM_DMA1_PROT_NONPM, \
    E_SEAL_SC0_PROT_NONPM, \
    E_SEAL_SC1_PROT_NONPM, \
    E_SEAL_SC2_PROT_NONPM, \
    E_SEAL_SC3_PROT_NONPM, \
    E_SEAL_SC4_PROT_NONPM, \
    E_SEAL_CLKGEN1_PROT_NONPM,  \
    E_SEAL_MAILBOX_PROT_NONPM, \
    E_SEAL_PCM_PROT_NONPM, \
    E_SEAL_VDMCU51_IF_PROT_NONPM, \
    E_SEAL_DMDMCU51_IF_PROT_NONPM, \
    E_SEAL_URDMA_PROT_NONPM, \
    E_SEAL_AFEC_PROT_NONPM, \
    E_SEAL_COMB_PROT_NONPM, \
    E_SEAL_VBI_PROT_NONPM

#define SEAL_NON_PM_GROUP4 \
    E_SEAL_SCM_PROT_NONPM, \
    E_SEAL_UTMI2_PROT_NONPM, \
    E_SEAL_PATGEN_PROT_NONPM, \
    E_SEAL_UTMI1_PROT_NONPM, \
    E_SEAL_UTMI_PROT_NONPM, \
    E_SEAL_VE_0_PROT_NONPM,  \
    E_SEAL_REG_PIU_NONPM_PROT_NONPM, \
    E_SEAL_ADC_ATOPB_PROT_NONPM, \
    E_SEAL_VE_1_PROT_NONPM, \
    E_SEAL_VE_2_PROT_NONPM, \
    E_SEAL_SC_GP1_NONPM, \
    E_SEAL_CHIPGPIO1_NONPM, \
    E_SEAL_CCI400_PROT_NONPM, \
    E_SEAL_UART1_PROT_NONPM, \
    E_SEAL_UART2_PROT_NONPM, \
    E_SEAL_FUART_PROT_NONPM

#define SEAL_NON_PM_GROUP5 \
    E_SEAL_UART4_PROT_NONPM, \
    E_SEAL_GE1_PROT_NONPM, \
    E_SEAL_GPU_NONPM,  \
    E_SEAL_ARM_CA72_PROT_NONPM, \
    E_SEAL_TS_SAMPLE_NONPM,\
    E_SEAL_ANA_MISC2_NONPM, \
    E_SEAL_SCPLL_PROT_NONPM, \
    E_SEAL_ANA_MISC_PROT_NONPM, \
    E_SEAL_ANA_MISC_GMAC_PROT_NONPM, \
    E_SEAL_MIU_ATOP_PROT_NONPM, \
    E_SEAL_TOP_SPARE0_PROT_NONPM, \
    E_SEAL_TOP_SPARE1_PROT_NONPM, \
    E_SEAL_MFE0_PROT_NONPM, \
    E_SEAL_MFE1_PROT_NONPM, \
    E_SEAL_ADC_DTOPB_PROT_NONPM, \
    E_SEAL_NFIE0_PROT_NONPM

#define SEAL_NON_PM_GROUP6 \
    E_SEAL_NFIE1_PROT_NONPM, \
    E_SEAL_NFIE2_PROT_NONPM, \
    E_SEAL_MIPSPLL_2_PROT_NONPM, \
    E_SEAL_DMD_MCU2_PROT_NONPM, \
    E_SEAL_MIIC0_PROT_NONPM, \
    E_SEAL_MIIC1_PROT_NONPM, \
    E_SEAL_MIIC2_PROT_NONPM, \
    E_SEAL_MIIC3_PROT_NONPM, \
    E_SEAL_USB30PHY_DTOP_M_0_PROT_NONPM, \
    E_SEAL_MOD2_PROT_NONPM, \
    E_SEAL_CLKGEN_DMD_PROT_NONPM, \
    E_SEAL_DEMOD_0_PROT_NONPM, \
    E_SEAL_DEMOD_1_PROT_NONPM, \
    E_SEAL_DEMOD_2_PROT_NONPM, \
    E_SEAL_DEMOD_3_PROT_NONPM, \
    E_SEAL_DEMOD_4_PROT_NONPM

#define SEAL_NON_PM_GROUP7 \
    E_SEAL_DEMOD_5_PROT_NONPM, \
    E_SEAL_DEMOD_6_PROT_NONPM, \
    E_SEAL_DEMOD_7_PROT_NONPM, \
    E_SEAL_DMD_ANA_MISC_PROT_NONPM, \
    E_SEAL_AU_R2_PROT_NONPM, \
    E_SEAL_VIVALDI0_PROT_NONPM, \
    E_SEAL_VIVALDI1_PROT_NONPM, \
    E_SEAL_VIVALDI2_PROT_NONPM, \
    E_SEAL_VIVALDI3_PROT_NONPM, \
    E_SEAL_VIVALDI4_PROT_NONPM, \
    E_SEAL_VIVALDI5_PROT_NONPM, \
    E_SEAL_AU_MAU_NONPM, \
    E_SEAL_GOP_AFBC_PROT_NONPM, \
    E_SEAL_CLKGEN_SC_FE, \
    E_SEAL_CLKGEN_SC_BE, \
    E_SEAL_CLKGEN_SC_GP2

#define SEAL_NON_PM_GROUP8 \
    E_SEAL_SC_GPLUS, \
    E_SEAL_SC_GPLUS_TOP_PROT_NONPM, \
    E_SEAL_USB2_PROT_NONPM, \
    E_SEAL_UHC2_PROT_NONPM, \
    E_SEAL_TSO_PROT_NONPM, \
    E_SEAL_DRM_SECURE_PROT_NONPM, \
    E_SEAL_DSCRMB2_PROT_NONPM, \
    E_SEAL_DSCRMB3_PROT_NONPM, \
    E_SEAL_GPD0_PROT_NONPM, \
    E_SEAL_GPD1_PROT_NONPM, \
    E_SEAL_GOP0G_0_PROT_NONPM, \
    E_SEAL_GOP0G_1_PROT_NONPM, \
    E_SEAL_GOP0G_ST_PROT_NONPM, \
    E_SEAL_GOP1G_0_PROT_NONPM, \
    E_SEAL_GOP1G_1_PROT_NONPM, \
    E_SEAL_GOP1G_ST_PROT_NONPM

#define SEAL_NON_PM_GROUP9 \
    E_SEAL_GOP2G_0_PROT_NONPM, \
    E_SEAL_GOP2G_1_PROT_NONPM, \
    E_SEAL_GOP2G_ST_PROT_NONPM, \
    E_SEAL_GOP3G_0_PROT_NONPM, \
    E_SEAL_GOP3G_1_PROT_NONPM, \
    E_SEAL_GOP3G_ST_PROT_NONPM, \
    E_SEAL_GOPD_PROT_NONPM, \
    E_SEAL_SDIO0_PROT_NONPM, \
    E_SEAL_SDIO_PLL_PROT_NONPM, \
    E_SEAL_SPARE1_PROT_NONPM, \
    E_SEAL_SPARE2_PROT_NONPM, \
    E_SEAL_SPARE3_PROT_NONPM, \
    E_SEAL_MIU_ARB256_PROT_NONPM, \
    E_SEAL_SECURERANGE2_NONPM, \
    E_SEAL_TZPC_NONPM2_NONPM, \
    E_SEAL_GOP4G_0_PROT_NONPM

#define SEAL_NON_PM_GROUP10 \
    E_SEAL_MIIC4_PROT_NONPM, \
    E_SEAL_MIIC5_PROT_NONPM, \
    E_SEAL_GOP4G_1_PROT_NONPM, \
    E_SEAL_GOP4G_ST_PROT_NONPM, \
    E_SEAL_USB30PHY_ATOP_M_0_PROT_NONPM, \
    E_SEAL_UTMISS0_PROT_NONPM, \
    E_SEAL_UTMISS1_PROT_NONPM, \
    E_SEAL_DSCRMB23_PROT_NONPM, \
    E_SEAL_USB3TOP_PROT_NONPM, \
    E_SEAL_DSCRMB24_PROT_NONPM, \
    E_SEAL_SDIO1_PROT_NONPM, \
    E_SEAL_SDIO2_PROT_NONPM, \
    E_SEAL_SEC_R2_PROT_NONPM, \
    E_SEAL_SEC_MAU0_PROT_NONPM, \
    E_SEAL_DSCRMB4_PROT_NONPM, \
    E_SEAL_OTP_LDO_PROT_PM

#define SEAL_NON_PM_GROUP11 \
    E_SEAL_MOBF_PROT_NONPM, \
    E_SEAL_DC_SCL_PROT_NONPM, \
    E_SEAL_MFT_PROT_NONPM, \
    E_SEAL_JPD_PROT_NONPM, \
    E_SEAL_CMDQ_SUB_PROT_NONPM, \
    E_SEAL_CMDQ_PROT_NONPM, \
    E_SEAL_USBBC0_PROT_NONPM, \
    E_SEAL_USBBC1_PROT_NONPM, \
    E_SEAL_USBBC2_PROT_NONPM, \
    E_SEAL_USB3_BC0_PROT_NONPM, \
    E_SEAL_USB3_BC1_PROT_NONPM, \
    E_SEAL_SECURERANGE0_PROT_NONPM, \
    E_SEAL_SECURERANGE1_PROT_NONPM, \
    E_SEAL_TZPC_NONPM_PROT_NONPM, \
    E_SEAL_ONEWAY_PROT_NONPM, \
    E_SEAL_NFIE3_PROT_NONPM

#define SEAL_NON_PM_GROUP12 \
    E_SEAL_DSCRMB5_PROT_NONPM, \
    E_SEAL_TSO1_NONPM, \
    E_SEAL_EMMC_PLL_PROT_NONPM, \
    E_SEAL_MSC_PROT_NONPM, \
    E_SEAL_MFSC_PROT_NONPM, \
    E_SEAL_PATGEN_CODEC_PROT_NONPM, \
    E_SEAL_PATGEN_VIV_PROT_NONPM, \
    E_SEAL_PATGEN_CPU_PROT_NONPM, \
    E_SEAL_PATGEN_GPU_PROT_NONPM, \
    E_SEAL_PATGEN_DEMOD_PROT_NONPM, \
    E_SEAL_PATGEN_TSP_PROT_NONPM, \
    E_SEAL_PATGEN_DEMOD1_PROT_NONPM, \
    E_SEAL_PATGEN_DVI_PROT_NONPM, \
    E_SEAL_PATGEN_EVD_PROT_NONPM, \
    E_SEAL_PATGEN_SC0_PROT_NONPM, \
    E_SEAL_PATGEN_SC1_PROT_NONPM

#define SEAL_NON_PM_GROUP13 \
    E_SEAL_PATGEN_FSC_PROT_NONPM, \
    E_SEAL_PATGEN_GPU_DIE_PROT_NONPM, \
    E_SEAL_MIU_ARBB_NONPM, \
    E_SEAL_MIU_ARBB2_NONPM, \
    E_SEAL_MIU_ARBB3_NONPM, \
    E_SEAL_MIU_ARBB4_NONPM, \
    E_SEAL_COMB1_PROT_NONPM, \
    E_SEAL_COMB2_PROT_NONPM, \
    E_SEAL_COMB3_PROT_NONPM, \
    E_SEAL_COMB4_PROT_NONPM, \
    E_SEAL_COMB5_PROT_NONPM, \
    E_SEAL_DEMOD_8_PROT_NONPM, \
    E_SEAL_DEMOD_9_PROT_NONPM, \
    E_SEAL_MIU_DIG_E_PROT_NONPM, \
    E_SEAL_MIU_DIG_E2_PROT_NONPM, \
    E_SEAL_MIU_DIG_E3_PROT_NONPM

#define SEAL_NON_PM_GROUP14 \
    E_SEAL_MIU_DIG_E4_PROT_NONPM, \
    E_SEAL_DMD_TOP_1_PROT_NONPM, \
    E_SEAL_USB30HS_UHC_PROT_NONPM, \
    E_SEAL_USB30HS1_UHC_PROT_NONPM, \
    E_SEAL_USB30HS1_USBC_PROT_NONPM, \
    E_SEAL_USB30HS_USBC_PROT_NONPM, \
    E_SEAL_USB30PHY1_DTOP_M_0_PROT_NONPM, \
    E_SEAL_USB30PHY1_ATOP_M_0_NONPM, \
    E_SEAL_USB30_HS1_MIUPROT2_PROT_NONPM, \
    E_SEAL_USB30_HS0_MIUPROT1_PROT_NONPM, \
    E_SEAL_USB30_SS_MIUPROT0_PROT_NONPM, \
    E_SEAL_USB0_MIUPROT_PROT_NONPM, \
    E_SEAL_USB1_MIUPROT_PROT_NONPM, \
    E_SEAL_USB2_MIUPROT_PROT_NONPM, \
    E_SEAL_TSO2_PROT_NONPM, \
    E_SEAL_MSPI0_PROT_NONPM

#define SEAL_NON_PM_GROUP15 \
    E_SEAL_MSPI1_PROT_NONPM, \
    E_SEAL_MSPI_MCARD_PROT_NONPM, \
    E_SEAL_VIVALDId_PROT_NONPM, \
    E_SEAL_VIVALDIe_PROT_NONPM, \
    E_SEAL_VIVALDIf_PROT_NONPM, \
    E_SEAL_VIVALDI6_PROT_NONPM, \
    E_SEAL_VIVALDI7_PROT_NONPM, \
    E_SEAL_GMAC0_PROT_NONPM, \
    E_SEAL_GMAC1_PROT_NONPM, \
    E_SEAL_GMAC2_PROT_NONPM, \
    E_SEAL_GMAC3_PROT_NONPM, \
    E_SEAL_GMAC4_PROT_NONPM, \
    E_SEAL_PCM2_PROT_NONPM, \
    E_SEAL_TSP3_PROT_NONPM, \
    E_SEAL_EVD_NONPM, \
    E_SEAL_EMACMIUPROT_PROT_NONPM

#define SEAL_NON_PM_GROUP16 \
    E_SEAL_GPU2MIU_MASK_PROT_NONPM, \
    E_SEAL_GPU_PLL_PROT_NONPM, \
    E_SEAL_MIU_ARB_SC_NONPM, \
    E_SEAL_MIU_ARB2_SC_NONPM, \
    E_SEAL_MIU_ARB3_SC_NONPM, \
    E_SEAL_CODEC_MRQ_PROT_NONPM, \
    E_SEAL_MIU_ARB_NONPM, \
    E_SEAL_MIU_ATOP2_PROT_NONPM, \
    E_SEAL_TSP4_NONPM, \
    E_SEAL_DSCRMB25_PROT_NONPM, \
    E_SEAL_DSCRMB26_PROT_NONPM, \
    E_SEAL_DSCRMB27_PROT_NONPM, \
    E_SEAL_TSP6_PROT_NONPM, \
    E_SEAL_MIU3_NONPM, \
    E_SEAL_MIU_ATOP3_NONPM, \
    E_SEAL_MIU_ARB2_NONPM

#define SEAL_NON_PM_GROUP17 \
    E_SEAL_MIU_ARB3_NONPM, \
    E_SEAL_MIU4_NONPM, \
    E_SEAL_MIU_ATOP4_NONPM, \
    E_SEAL_MIU_ARB4_NONPM, \
    E_SEAL_VIVALDIc_PROT_NONPM, \
    E_SEAL_GE2_NONPM, \
    E_SEAL_GE3_NONPM, \
    E_SEAL_MIU_ARB_FRC_NONPM, \
    E_SEAL_MIU_ARB2_FRC_NONPM, \
    E_SEAL_MIU_ARB3_FRC_NONPM, \
    E_SEAL_AU_R2_1_NONPM, \
    E_SEAL_AU_MAU_1_NONPM, \
    E_SEAL_VD_EVD_R2_NONPM, \
    E_SEAL_MAU_EVD_NONPM, \
    E_SEAL_HIREG_EVD_PROT_NONPM, \
    E_SEAL_MAU_EVD_LV2_0_NONPM

#define SEAL_NON_PM_GROUP18 \
    E_SEAL_MAU_EVD_LV2_1_NONPM, \
    E_SEAL_SEC_MAU_LV2_0_NONPM, \
    E_SEAL_SEC_MAU_LV2_1_NONPM, \
    E_SEAL_TSP5_NONPM, \
    E_SEAL_VIVALDI8_PROT_NONPM, \
    E_SEAL_VIVALDI9_PROT_NONPM, \
    E_SEAL_VIVALDIa_0_PROT_NONPM, \
    E_SEAL_VIVALDIa_1_PROT_NONPM, \
    E_SEAL_VIVALDIa_2_PROT_NONPM, \
    E_SEAL_VIVALDIa_3_PROT_NONPM, \
    E_SEAL_VIVALDIa_6_PROT_NONPM, \
    E_SEAL_VIVALDIb_0_PROT_NONPM, \
    E_SEAL_VIVALDIb_1_PROT_NONPM, \
    E_SEAL_VIVALDIb_2_PROT_NONPM, \
    E_SEAL_VIVALDIb_3_PROT_NONPM, \
    E_SEAL_COMBO_PHY0_P0_PROT_NONPM

#define SEAL_NON_PM_GROUP19 \
    E_SEAL_COMBO_PHY1_P0_PROT_NONPM, \
    E_SEAL_COMBO_PHY0_P1_PROT_NONPM, \
    E_SEAL_COMBO_PHY1_P1_PROT_NONPM, \
    E_SEAL_COMBO_PHY0_P2_PROT_NONPM, \
    E_SEAL_COMBO_PHY1_P2_PROT_NONPM, \
    E_SEAL_COMBO_PHY0_P3_PROT_NONPM, \
    E_SEAL_COMBO_PHY1_P3_PROT_NONPM, \
    E_SEAL_MHL_ECBUS_PROT_NONPM, \
    E_SEAL_DVI_DTOP_DUAL_P0_PROT_NONPM, \
    E_SEAL_DVI_RSV_DUAL_P0_PROT_NONPM, \
    E_SEAL_HDCP_DUAL_P0_PROT_NONPM, \
    E_SEAL_DVI_DTOP_DUAL_P1_PROT_NONPM, \
    E_SEAL_DVI_RSV_DUAL_P1_PROT_NONPM, \
    E_SEAL_HDCP_DUAL_P1_PROT_NONPM, \
    E_SEAL_DVI_DTOP_DUAL_P2_PROT_NONPM, \
    E_SEAL_DVI_RSV_DUAL_P2_PROT_NONPM

#define SEAL_NON_PM_GROUP20 \
    E_SEAL_HDCP_DUAL_P2_PROT_NONPM, \
    E_SEAL_DVI_DTOP_DUAL_P3_PROT_NONPM, \
    E_SEAL_DVI_RSV_DUAL_P3_PROT_NONPM, \
    E_SEAL_HDCP_DUAL_P3_PROT_NONPM, \
    E_SEAL_HDMI_DUAL_0_PROT_NONPM, \
    E_SEAL_HDMI2_DUAL_0_PROT_NONPM, \
    E_SEAL_HDMI_DUAL_1_PROT_NONPM, \
    E_SEAL_HDMI2_DUAL_1_PROT_NONPM, \
    E_SEAL_HDMI3_DUAL_0_PROT_NONPM, \
    E_SEAL_HDMI3_DUAL_1_PROT_NONPM, \
    E_SEAL_HDCPKEY_PROT_NONPM, \
    E_SEAL_COMBO_GP_TOP_PROT_NONPM, \
    E_SEAL_SECURE_TZPC_PROT_NONPM, \
    E_SEAL_CBUS_AUDIO_PROT_NONPM, \
    E_SEAL_MHL_ECBUS_PHY_PROT_NONPM, \
    E_SEAL_DSCRMB6_PROT_NONPM

#define SEAL_NON_PM_GROUP21 \
    E_SEAL_DSCRMB7_PROT_NONPM, \
    E_SEAL_CRI_KL_PROT_NONPM, \
    E_SEAL_CERT_KL_PROT_NONPM, \
    E_SEAL_X32_USB3XHCI_NONPM, \
    E_SEAL_X32_GPUAPB0_NONPM, \
    E_SEAL_X32_GPUAPB1_NONPM, \
    E_SEAL_X32_GPUAPB2_NONPM, \
    E_SEAL_X32_CRI_APB_PROT_NONPM, \
    E_SEAL_X32_CERT_PROT_NONPM, \
    E_SEAL_X32_PKA_APB_PROT_NONPM, \
    E_SEAL_DUMMY, \
    E_SEAL_DUMMY, \
    E_SEAL_DUMMY, \
    E_SEAL_DUMMY, \
    E_SEAL_DUMMY, \
    E_SEAL_DUMMY

#define SEAL_NON_PM_GROUP22 \
    E_SEAL_DUMMY, \
    E_SEAL_DUMMY, \
    E_SEAL_DUMMY, \
    E_SEAL_DUMMY, \
    E_SEAL_DUMMY, \
    E_SEAL_DUMMY, \
    E_SEAL_DUMMY, \
    E_SEAL_DUMMY, \
    E_SEAL_DUMMY, \
    E_SEAL_DUMMY, \
    E_SEAL_DUMMY, \
    E_SEAL_DUMMY, \
    E_SEAL_DUMMY, \
    E_SEAL_DUMMY, \
    E_SEAL_DUMMY, \
    E_SEAL_DUMMY

#define SEAL_NON_PM_GROUP23 \
    E_SEAL_DUMMY, \
    E_SEAL_DUMMY, \
    E_SEAL_DUMMY, \
    E_SEAL_DUMMY, \
    E_SEAL_DUMMY, \
    E_SEAL_DUMMY, \
    E_SEAL_DUMMY, \
    E_SEAL_DUMMY, \
    E_SEAL_DUMMY, \
    E_SEAL_DUMMY, \
    E_SEAL_DUMMY, \
    E_SEAL_DUMMY, \
    E_SEAL_DUMMY, \
    E_SEAL_DIP_PROT_NONPM, \
    E_SEAL_PDW0_PROT_NONPM, \
    E_SEAL_PDW1_PROT_NONPM


//lock group
#define SEAL_LOCK_GROUP_DUMMY \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY

#define SEAL_LOCK_GROUP0 \
    E_SEAL_SC_WP_DIPW, \
    E_SEAL_SC_RP_DIPW, \
    E_SEAL_SC_WP_DIPR, \
    E_SEAL_SC_RP_DIPR, \
    E_SEAL_AUDIO_LCL_R2_WR_PROTN_0, \
    E_SEAL_AUDIO_LCL_R2_WR_PROTN_1, \
    E_SEAL_AUDIO_LCL_R2_WR_PROTN_2, \
    E_SEAL_AUDIO_LCL_R2_WR_PROTN_3, \
    E_SEAL_AUDIO_SCL_R2_WR_PROTN_0, \
    E_SEAL_AUDIO_SCL_R2_WR_PROTN_1, \
    E_SEAL_AUDIO_SCL_R2_WR_PROTN_2, \
    E_SEAL_AUDIO_SCL_R2_WR_PROTN_3, \
    E_SEAL_SECURE_R2_WR_PROTN_0, \
    E_SEAL_SECURE_R2_WR_PROTN_1, \
    E_SEAL_SECURE_R2_WR_PROTN_2, \
    E_SEAL_SECURE_R2_WR_PROTN_3

#define SEAL_LOCK_GROUP1 \
    E_SEAL_CIPHERENG_WP_SYSKEY, \
    E_SEAL_CIPHERENG_RP_SYSKEY, \
    E_SEAL_DSCRMB_WP_RIV0, \
    E_SEAL_DSCRMB_RP_RIV0, \
    E_SEAL_DSCRMB_WP_RIV1, \
    E_SEAL_DSCRMB_RP_RIV1, \
    E_SEAL_DSCRMB_WP_WDATA, \
    E_SEAL_DSCRMB_RP_WDATA, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_MVOP_WP_TLB, \
    E_SEAL_AUDIO_PAS_PROTN

#define SEAL_LOCK_GROUP2 \
    E_SEAL_DSCRMB_RP_RDATA, \
    E_SEAL_CRI_KL_WP_N, \
    E_SEAL_PCIERC_IBWP_PROTN, \
    E_SEAL_PCIERC_OBWP_PROTN, \
    E_SEAL_RNG_PROTECT, \
    E_SEAL_RSA_PROTECT, \
    E_SEAL_SHA_PROTECT, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_EVD_R2_WR_PROTN_0, \
    E_SEAL_EVD_R2_WR_PROTN_1, \
    E_SEAL_EVD_R2_WR_PROTN_2, \
    E_SEAL_EVD_R2_WR_PROTN_3, \
    E_SEAL_HVD_R2_WR_PROTN_0, \
    E_SEAL_HVD_R2_WR_PROTN_1, \
    E_SEAL_HVD_R2_WR_PROTN_2, \
    E_SEAL_HVD_R2_WR_PROTN_3

#define SEAL_LOCK_GROUP3 \
    E_SEAL_HVD_ES0_BUF, \
    E_SEAL_HVD_ES1_BUF, \
    E_SEAL_HVD_ES2_BUF, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_MFE0_ES_BUF, \
    E_SEAL_MVD_WR_PROTN_0, \
    E_SEAL_MVD_WR_PROTN_1, \
    E_SEAL_MVD_WR_PROTN_2, \
    E_SEAL_EVD_0_WR_PROTN_0, \
    E_SEAL_EVD_1_WR_PROTN_0, \
    E_SEAL_MHEG5_WR_PROTN_0, \
    E_SEAL_AUDIO_DSP_ES_PROTN, \
    E_SEAL_AUDIO_DSP_CACHE_PROTN, \
    E_SEAL_EVD_0_WR_PROTN_1, \
    E_SEAL_EVD_1_WR_PROTN_1, \
    E_SEAL_VP9_TOP

#define SEAL_LOCK_GROUP4 \
    E_SEAL_TSO_WP_TSOFI, \
    E_SEAL_TSO_RP_TSOFI, \
    E_SEAL_MMFI_WP_MMFI0, \
    E_SEAL_MMFI_RP_MMFI0, \
    E_SEAL_MMFI_WP_MMFI1, \
    E_SEAL_MMFI_RP_MMFI1, \
    E_SEAL_TSP0_WP_PVR, \
    E_SEAL_TSP0_RP_PVR, \
    E_SEAL_TSP0_WP_PVR1, \
    E_SEAL_TSP0_RP_PVR1, \
    E_SEAL_TSP0_WP_FILEIN, \
    E_SEAL_TSP0_RP_FILEIN, \
    E_SEAL_TSP0_WP_QMEM, \
    E_SEAL_TSP0_RP_QMEM, \
    E_SEAL_TSP0_WP_FW, \
    E_SEAL_TSP0_RP_FW

#define SEAL_LOCK_GROUP5 \
    E_SEAL_VE_WP, \
    E_SEAL_VE_RP, \
    E_SEAL_SC_WP_OD, \
    E_SEAL_SC_RP_OD, \
    E_SEAL_SC_WP_SCM_M, \
    E_SEAL_SC_RP_SCM_M, \
    E_SEAL_SC_WP_SCM_S, \
    E_SEAL_SC_RP_SCM_S, \
    E_SEAL_SC_WP_PDW0, \
    E_SEAL_SC_RP_PDW0, \
    E_SEAL_SC_WP_PDW1, \
    E_SEAL_SC_RP_PDW1, \
    E_SEAL_SC_WP_OPW, \
    E_SEAL_SC_RP_OPW, \
    E_SEAL_GOPD_PROTN, \
    E_SEAL_AUDIO_AL_PROTN

#define SEAL_LOCK_GROUP6 \
    E_SEAL_GE0_SB_PROTN, \
    E_SEAL_GE0_DB_PROTN, \
    E_SEAL_GE1_SB_PROTN, \
    E_SEAL_GE1_DB_PROTN, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY

#define SEAL_LOCK_GROUP7 \
    E_SEAL_TSP_WP_FILEIN1, \
    E_SEAL_TSP_RP_FILEIN1, \
    E_SEAL_TSP_WP_PVR3, \
    E_SEAL_TSP_RP_PVR3, \
    E_SEAL_TSP_WP_FIQ0, \
    E_SEAL_TSP_RP_FIQ0, \
    E_SEAL_TSP_WP_PVR4, \
    E_SEAL_TSP_RP_PVR4, \
    E_SEAL_TSP_WP_FILEIN2, \
    E_SEAL_TSP_RP_FILEIN2, \
    E_SEAL_TSP_WP_FILEIN3, \
    E_SEAL_TSP_RP_FILEIN3, \
    E_SEAL_TSP_WP_FILEIN4, \
    E_SEAL_TSP_RP_FILEIN4, \
    E_SEAL_TSP_WP_FILEIN5, \
    E_SEAL_TSP_RP_FILEIN5

#define SEAL_LOCK_GROUP8 \
    E_SEAL_USB_MIUPROT_WP_N, \
    E_SEAL_EMAC_MIUPROT_WP_N, \
    E_SEAL_PCIE_MIUPROT_WP_N, \
    E_SEAL_AU_HDMI_DMA_WP_N, \
    E_SEAL_TSP_WP_FIQ1, \
    E_SEAL_TSP_RP_FIQ1, \
    E_SEAL_TSP_WP_ORZ, \
    E_SEAL_TSP_RP_ORZ, \
    E_SEAL_TSP_WP_VQ, \
    E_SEAL_TSP_RP_VQ, \
    E_SEAL_TSP_WP_SEC, \
    E_SEAL_TSP_RP_SEC, \
    E_SEAL_TSP_WP_FIQ2, \
    E_SEAL_TSP_RP_FIQ2, \
    E_SEAL_TSP_WP_FIQ3, \
    E_SEAL_TSP_RP_FIQ3

#define SEAL_LOCK_GROUP9 \
    E_SEAL_EVD_LITE_0_WR_PROTN_0, \
    E_SEAL_EVD_LITE_1_WR_PROTN_1, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY

#define SEAL_LOCK_GROUP10 \
    E_SEAL_FCIE_WR_PROT_ENABLE_0, \
    E_SEAL_FCIE_WR_PROT_ENABLE_1, \
    E_SEAL_FCIE_WR_PROT_ENABLE_2, \
    E_SEAL_FCIE_WR_PROT_ENABLE_3, \
    E_SEAL_HDCP_RIU_R_PROTN, \
    E_SEAL_HDCP_XIU_R_PROTN, \
    E_SEAL_HDCP_RIU_W_PROTN, \
    E_SEAL_HDCP_XIU_W_PROTN, \
    E_SEAL_FCIE_WR_PROT_0_LOCK, \
    E_SEAL_FCIE_WR_PROT_1_LOCK, \
    E_SEAL_FCIE_WR_PROT_2_LOCK, \
    E_SEAL_FCIE_WR_PROT_3_LOCK, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY, \
    E_SEAL_LOCK_DUMMY


#define MIU0_PA_BASE               0x00000000UL
#define MIU1_PA_BASE               0x80000000UL
#define MIU2_PA_BASE               0xC0000000UL


const int NonPmIpTbl[SEAL_NONPM_TBL_IP_NUM] =
{
    SEAL_NON_PM_GROUP0, SEAL_NON_PM_GROUP1, SEAL_NON_PM_GROUP2,
    SEAL_NON_PM_GROUP3, SEAL_NON_PM_GROUP4, SEAL_NON_PM_GROUP5,
    SEAL_NON_PM_GROUP6, SEAL_NON_PM_GROUP7, SEAL_NON_PM_GROUP8,
    SEAL_NON_PM_GROUP9, SEAL_NON_PM_GROUP10, SEAL_NON_PM_GROUP11,
    SEAL_NON_PM_GROUP12, SEAL_NON_PM_GROUP13, SEAL_NON_PM_GROUP14,
    SEAL_NON_PM_GROUP15, SEAL_NON_PM_GROUP16, SEAL_NON_PM_GROUP17,
    SEAL_NON_PM_GROUP18, SEAL_NON_PM_GROUP19, SEAL_NON_PM_GROUP20,
    SEAL_NON_PM_GROUP21, SEAL_NON_PM_GROUP22, SEAL_NON_PM_GROUP23
};

const int LockTbl[SEAL_TBL_LOCK_NUM] =
{
    SEAL_LOCK_GROUP10, /*0x64*/
    SEAL_LOCK_GROUP_DUMMY,
    SEAL_LOCK_GROUP_DUMMY,
    SEAL_LOCK_GROUP_DUMMY,
    SEAL_LOCK_GROUP_DUMMY,
    SEAL_LOCK_GROUP_DUMMY,
    SEAL_LOCK_GROUP_DUMMY,
    SEAL_LOCK_GROUP_DUMMY,
    SEAL_LOCK_GROUP_DUMMY,
    SEAL_LOCK_GROUP_DUMMY,
    SEAL_LOCK_GROUP_DUMMY,
    SEAL_LOCK_GROUP_DUMMY,
    SEAL_LOCK_GROUP_DUMMY,
    SEAL_LOCK_GROUP_DUMMY,
    SEAL_LOCK_GROUP_DUMMY,
    SEAL_LOCK_GROUP_DUMMY,
    SEAL_LOCK_GROUP0, /*0x74*/
    SEAL_LOCK_GROUP1,
    SEAL_LOCK_GROUP2,
    SEAL_LOCK_GROUP3,
    SEAL_LOCK_GROUP4,
    SEAL_LOCK_GROUP5,
    SEAL_LOCK_GROUP6,
    SEAL_LOCK_GROUP7,
    SEAL_LOCK_GROUP8,
    SEAL_LOCK_GROUP9
};

static unsigned long long __PA2BA(unsigned long long u64PhyAddr)
{
    unsigned long long u64BusAddr = 0x0;

    if( (u64PhyAddr >= MIU0_PA_BASE) && (u64PhyAddr < MIU1_PA_BASE) ) // MIU0
        u64BusAddr = u64PhyAddr - MIU0_PA_BASE + CONFIG_MIU0_BUSADDR;
    else if ( (u64PhyAddr >= MIU1_PA_BASE) && (u64PhyAddr < MIU2_PA_BASE) ) // MIU1
        u64BusAddr = u64PhyAddr - MIU1_PA_BASE + CONFIG_MIU1_BUSADDR;
    else // MIU2
        u64BusAddr = u64PhyAddr - MIU2_PA_BASE + CONFIG_MIU2_BUSADDR;

    return u64BusAddr;
}

int HAL_SEAL_GetNonPmIpIdx(int eNonPmIP)
{
    int s32HwIdx;
    for (s32HwIdx = 0; s32HwIdx < SEAL_NONPM_TBL_IP_NUM; s32HwIdx++)
    {
        if(eNonPmIP == NonPmIpTbl[s32HwIdx])
        {
            return s32HwIdx;
        }
    }
    return (-1);
}

int HAL_SEAL_GetLockIdx(int eLockId)
{
    int s32HwIdx;
    for (s32HwIdx = 0; s32HwIdx < SEAL_TBL_LOCK_NUM; s32HwIdx++)
    {
        if(eLockId == LockTbl[s32HwIdx])
        {
            return s32HwIdx;
        }
    }
    return (-1);
}


int HAL_SEAL_SetSecureRange(unsigned long long startAddr, unsigned long long endAddr, int attr)
{
    unsigned int bankBase;
    unsigned int startRegOffset;
    unsigned int endRegOffset;
    unsigned int attrRegOffset;
    unsigned int miuSel;
    unsigned long long startOffset;
    unsigned long long endOffset;
    unsigned int offset;
    int i, free;

    _phy_to_miu_offset(miuSel, startOffset, startAddr);
    _phy_to_miu_offset(miuSel, endOffset, endAddr);

    if (miuSel==0)
    {
        bankBase = SEAL_SECURE0_RANGE0;
    }
    else if (miuSel==1)
    {
        bankBase = SEAL_SECURE1_RANGE0;
    }
    else if (miuSel==2)
    {
        bankBase = SEAL_SECURE2_RANGE0;
    }
    else
    {
        return 0;
    }

    // check same range
    for (i=0; i<REG_SECURE_RANGE_NUM; i++)
    {
        unsigned int offset = i*REG_SECURE_RANGE_OFFSET;
        unsigned int startRegOffset = REG_SECURE_RANGE0_START_ADDR + offset;
        unsigned int endRegOffset = REG_SECURE_RANGE0_END_ADDR + offset;
        unsigned int attrRegOffset = REG_SECURE_RANGE0_ATTRIBUTE + offset;
        unsigned long long start = 0;
        unsigned long long end = 0;
        start |= RIU[bankBase + startRegOffset + 4];
        start <<= 16;
        start |= RIU[bankBase + startRegOffset + 2];
        start <<= 16;
        start |= RIU[bankBase + startRegOffset];
        end |= RIU[bankBase + endRegOffset + 4];
        end <<= 16;
        end |= RIU[bankBase + endRegOffset + 2];
        end <<= 16;
        end |= RIU[bankBase + endRegOffset];

        // same range, only set attribute
        if ( ((RIU[bankBase + REG_SECURE0_DETECT_ENABLE]) & (1<<i))
            && (start == startOffset)
            && (end == endOffset) )
        {
            RIU[bankBase + attrRegOffset] = attr;
            return 1;
        }
    }

    // find an unused range
    for (free=0; free<REG_SECURE_RANGE_NUM; free++)
    {
        if ( ! ((RIU[bankBase + REG_SECURE0_DETECT_ENABLE]) & (1<<free)) )
        {
            break;
        }
    }

    if (free >= REG_SECURE_RANGE_NUM) // no free range
    {
        return 0;
    }

    offset = free*REG_SECURE_RANGE_OFFSET;
    startRegOffset = REG_SECURE_RANGE0_START_ADDR + offset;
    endRegOffset = REG_SECURE_RANGE0_END_ADDR + offset;
    attrRegOffset = REG_SECURE_RANGE0_ATTRIBUTE + offset;

    RIU[bankBase + startRegOffset] = (startOffset & 0xFFFFULL);
    RIU[bankBase + startRegOffset + 2] = ((startOffset>>16) & 0xFFFFULL);
    RIU[bankBase + startRegOffset + 4] = ((startOffset>>32) & 0xFFFFULL);

    RIU[bankBase + endRegOffset] = (endOffset & 0xFFFFULL);
    RIU[bankBase + endRegOffset + 2] = ((endOffset>>16) & 0xFFFFULL);
    RIU[bankBase + endRegOffset + 4] = ((endOffset>>32) & 0xFFFFULL);

    RIU[bankBase + attrRegOffset] = attr;
    (RIU[bankBase + REG_SECURE0_DETECT_ENABLE]) |= (1<<free);

    return 1;
}

int HAL_SEAL_DisableRIUBridges(void)
{
    // set hosts of PM RIU bridge to non-secure
    RIU[SEAL_TZPC_PM_BASE + REG_PM_RIU_BRIDGE] = (0x5555);

    // set hosts of NONPM RIU bridge to non-secure (except ARM)
    RIU[SEAL_TZPC_NONPM_BASE + REG_NONPM_RIU_BRIDGE] = (0x5555);

    // Set ARM to non-secure
    (RIU[REG_TZPC_LEGACY_SECUREPROCESSOR]) |= (FLAG_TZPC_NONSECURE_ARM);

    return 1;
}

int HAL_SEAL_Init(void)
{
    // Disable ejtag to TEE debugging capability
    (RIU[SEAL_TZPC_NONPM_BASE + (0x02<<1)]) &= (0x00ff);

    // mask decode error when non-secure CPU access miu secure range
    // mask decode error when non-secure CPU access secure riu register bank
    // mask decode error when CPU access undefined address area
    (RIU[SEAL_TZPC_NONPM_BASE + (0x7e<<1)]) |= (0x000e);

    // protect watermark control registers
    (RIU[SEAL_TZPC_NONPM_BASE + (0x7d<<1)]) &= ~(1<<15);

    // secure AESDMA, FCIE
    HAL_SEAL_SetRIUBank(E_SEAL_DSCRMB3_PROT_NONPM, 1);
    HAL_SEAL_SetMIUHost(E_SEAL_DSCRMB3_PROT_NONPM, 1);
    HAL_SEAL_SetMIUHost(E_SEAL_DSCRMB5_PROT_NONPM, 1);
    HAL_SEAL_SetMIUHost(E_SEAL_NFIE0_PROT_NONPM, 1);
    HAL_SEAL_SetMIUHost(E_SEAL_NFIE1_PROT_NONPM, 1);
    HAL_SEAL_SetMIUHost(E_SEAL_NFIE2_PROT_NONPM, 1);
    HAL_SEAL_SetMIUHost(E_SEAL_NFIE3_PROT_NONPM, 1);

    // Set hosts of RIU bridge to non-secure (except ARM and DB_BUS)
    RIU[SEAL_TZPC_PM_BASE + REG_PM_RIU_BRIDGE] = (0x5554);
    RIU[SEAL_TZPC_NONPM_BASE + REG_NONPM_RIU_BRIDGE] = (0x5554);

    return 1;
}

int HAL_SEAL_SetMIUHost(int swIdx, int bSecure)
{
    int hwIdx = HAL_SEAL_GetNonPmIpIdx(swIdx);

    if (hwIdx < 0)
    {
        return 0;
    }

    if (bSecure)
        (RIU[REG_TZPC_NONPM_MIU_HOST + ((hwIdx>>4)<<1)]) &= ~(1<<(hwIdx&15));
    else
        (RIU[REG_TZPC_NONPM_MIU_HOST + ((hwIdx>>4)<<1)]) |= (1<<(hwIdx&15));

    return 1;
}

int HAL_SEAL_SetRIUBank(int swIdx, int bSecure)
{
    int hwIdx = HAL_SEAL_GetNonPmIpIdx(swIdx);
    if (hwIdx < 0)
    {
        return 0;
    }

    if (bSecure)
        (RIU[REG_TZPC_NONPM_SECURE_BANK + ((hwIdx>>4)<<1)]) &= ~(1<<(hwIdx&15));
    else
        (RIU[REG_TZPC_NONPM_SECURE_BANK + ((hwIdx>>4)<<1)]) |= (1<<(hwIdx&15));

    return 1;
}


int HAL_SEAL_SetRIURegister(int swIdx, int bSecure)
{
    int hwIdx = HAL_SEAL_GetLockIdx(swIdx);
    if (hwIdx < 0)
    {
        return 0;
    }

    if (bSecure)
        (RIU[REG_TZPC_NONPM_SECURE_REG + ((hwIdx>>4)<<1)]) &= ~(1<<(hwIdx&15));
    else
        (RIU[REG_TZPC_NONPM_SECURE_REG + ((hwIdx>>4)<<1)]) |= (1<<(hwIdx&15));
    return 1;
}


int HAL_SEAL_Cleanup(void)
{
    //reg_rom_security_oneway_prot
	  (RIU[0x101800+(0x59<<1)]) |= 1;

    // non-secure FCIE
    HAL_SEAL_SetMIUHost(E_SEAL_DSCRMB5_PROT_NONPM, 0);
    HAL_SEAL_SetMIUHost(E_SEAL_NFIE0_PROT_NONPM, 0);
    HAL_SEAL_SetMIUHost(E_SEAL_NFIE1_PROT_NONPM, 0);
    HAL_SEAL_SetMIUHost(E_SEAL_NFIE2_PROT_NONPM, 0);
    HAL_SEAL_SetMIUHost(E_SEAL_NFIE3_PROT_NONPM, 0);
    return 1;
}
