/* SPDX-License-Identifier: GPL-2.0-only OR BSD-3-Clause */
/******************************************************************************
 *
 * This file is provided under a dual license.  When you use or
 * distribute this software, you may choose to be licensed under
 * version 2 of the GNU General Public License ("GPLv2 License")
 * or BSD License.
 *
 * GPLv2 License
 *
 * Copyright(C) 2019 MediaTek Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of version 2 of the GNU General Public License as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See http://www.gnu.org/licenses/gpl-2.0.html for more details.
 *
 * BSD LICENSE
 *
 * Copyright(C) 2019 MediaTek Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *****************************************************************************/

// This file is generated by script file, please do not edit it directly 
#ifndef _MSD96AWD_H_
#define _MSD96AWD_H_

#define PAD_NC   9999
#define PAD_GND  0

#define BALL_L2 PAD_GPIO0_PM
#define PAD_GPIO0_PM 10
#define GPIO_PAD_10 GPIO9
#ifndef BALL_L2_IS_GPIO
#define BALL_L2_IS_GPIO 0
#endif 
#ifndef PAD_GPIO0_PM_IS_GPIO
#define PAD_GPIO0_PM_IS_GPIO BALL_L2_IS_GPIO
#endif 

#define BALL_AJ3 PAD_GPIO1_PM
#define PAD_GPIO1_PM 11
#define GPIO_PAD_11 GPIO10
#ifndef BALL_AJ3_IS_GPIO
#define BALL_AJ3_IS_GPIO 0
#endif 
#ifndef PAD_GPIO1_PM_IS_GPIO
#define PAD_GPIO1_PM_IS_GPIO BALL_AJ3_IS_GPIO
#endif 

#define BALL_M7 PAD_GPIO2_PM
#define PAD_GPIO2_PM 12
#define GPIO_PAD_12 GPIO11
#ifndef BALL_M7_IS_GPIO
#define BALL_M7_IS_GPIO 0
#endif 
#ifndef PAD_GPIO2_PM_IS_GPIO
#define PAD_GPIO2_PM_IS_GPIO BALL_M7_IS_GPIO
#endif 

#define PAD_GPIO3_PM 9999
#ifndef PAD_GPIO3_PM_IS_GPIO
#define PAD_GPIO3_PM_IS_GPIO 0
#endif 

#define PAD_GPIO22_PM 9999
#ifndef PAD_GPIO22_PM_IS_GPIO
#define PAD_GPIO22_PM_IS_GPIO 0
#endif 

#define PAD_GPIO23_PM 9999
#ifndef PAD_GPIO23_PM_IS_GPIO
#define PAD_GPIO23_PM_IS_GPIO 0
#endif 

#define BALL_AK1 PAD_GPIO5_PM
#define PAD_GPIO5_PM 14
#define GPIO_PAD_14 GPIO13
#ifndef BALL_AK1_IS_GPIO
#define BALL_AK1_IS_GPIO 0
#endif 
#ifndef PAD_GPIO5_PM_IS_GPIO
#define PAD_GPIO5_PM_IS_GPIO BALL_AK1_IS_GPIO
#endif 

#define BALL_P3 PAD_GPIO6_PM
#define PAD_GPIO6_PM 15
#define GPIO_PAD_15 GPIO14
#ifndef BALL_P3_IS_GPIO
#define BALL_P3_IS_GPIO 0
#endif 
#ifndef PAD_GPIO6_PM_IS_GPIO
#define PAD_GPIO6_PM_IS_GPIO BALL_P3_IS_GPIO
#endif 

#define BALL_L3 PAD_GPIO8_PM
#define PAD_GPIO8_PM 17
#define GPIO_PAD_17 GPIO16
#ifndef BALL_L3_IS_GPIO
#define BALL_L3_IS_GPIO 0
#endif 
#ifndef PAD_GPIO8_PM_IS_GPIO
#define PAD_GPIO8_PM_IS_GPIO BALL_L3_IS_GPIO
#endif 

#define BALL_M5 PAD_GPIO7_PM
#define PAD_GPIO7_PM 16
#define GPIO_PAD_16 GPIO15
#ifndef BALL_M5_IS_GPIO
#define BALL_M5_IS_GPIO 0
#endif 
#ifndef PAD_GPIO7_PM_IS_GPIO
#define PAD_GPIO7_PM_IS_GPIO BALL_M5_IS_GPIO
#endif 

#define BALL_N7 PAD_GPIO9_PM
#define PAD_GPIO9_PM 18
#define GPIO_PAD_18 GPIO17
#ifndef BALL_N7_IS_GPIO
#define BALL_N7_IS_GPIO 0
#endif 
#ifndef PAD_GPIO9_PM_IS_GPIO
#define PAD_GPIO9_PM_IS_GPIO BALL_N7_IS_GPIO
#endif 

#define PAD_GPIO10_PM 9999
#ifndef PAD_GPIO10_PM_IS_GPIO
#define PAD_GPIO10_PM_IS_GPIO 0
#endif 

#define PAD_GPIO12_PM 9999
#ifndef PAD_GPIO12_PM_IS_GPIO
#define PAD_GPIO12_PM_IS_GPIO 0
#endif 

#define BALL_M6 PAD_GPIO11_PM
#define PAD_GPIO11_PM 20
#define GPIO_PAD_20 GPIO19
#ifndef BALL_M6_IS_GPIO
#define BALL_M6_IS_GPIO 0
#endif 
#ifndef PAD_GPIO11_PM_IS_GPIO
#define PAD_GPIO11_PM_IS_GPIO BALL_M6_IS_GPIO
#endif 

#define PAD_GPIO13_PM 9999
#ifndef PAD_GPIO13_PM_IS_GPIO
#define PAD_GPIO13_PM_IS_GPIO 0
#endif 

#define PAD_GPIO17_PM 9999
#ifndef PAD_GPIO17_PM_IS_GPIO
#define PAD_GPIO17_PM_IS_GPIO 0
#endif 

#define BALL_AD5 PAD_GPIO14_PM
#define PAD_GPIO14_PM 23
#define GPIO_PAD_23 GPIO22
#ifndef BALL_AD5_IS_GPIO
#define BALL_AD5_IS_GPIO 0
#endif 
#ifndef PAD_GPIO14_PM_IS_GPIO
#define PAD_GPIO14_PM_IS_GPIO BALL_AD5_IS_GPIO
#endif 

#define PAD_GPIO18_PM 9999
#ifndef PAD_GPIO18_PM_IS_GPIO
#define PAD_GPIO18_PM_IS_GPIO 0
#endif 

#define PAD_GPIO16_PM 9999
#ifndef PAD_GPIO16_PM_IS_GPIO
#define PAD_GPIO16_PM_IS_GPIO 0
#endif 

#define PAD_GPIO19_PM 9999
#ifndef PAD_GPIO19_PM_IS_GPIO
#define PAD_GPIO19_PM_IS_GPIO 0
#endif 

#define BALL_AB6 PAD_HOTPLUGA
#define PAD_HOTPLUGA 36
#define GPIO_PAD_36 GPIO35
#ifndef BALL_AB6_IS_GPIO
#define BALL_AB6_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGA_IS_GPIO
#define PAD_HOTPLUGA_IS_GPIO BALL_AB6_IS_GPIO
#endif 

#define PAD_GPIO20_PM 9999
#ifndef PAD_GPIO20_PM_IS_GPIO
#define PAD_GPIO20_PM_IS_GPIO 0
#endif 

#define BALL_AC6 PAD_HOTPLUGA_HDMI20_5V
#define PAD_HOTPLUGA_HDMI20_5V 40
#define GPIO_PAD_40 GPIO39
#ifndef BALL_AC6_IS_GPIO
#define BALL_AC6_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGA_HDMI20_5V_IS_GPIO
#define PAD_HOTPLUGA_HDMI20_5V_IS_GPIO BALL_AC6_IS_GPIO
#endif 

#define PAD_GPIO21_PM 9999
#ifndef PAD_GPIO21_PM_IS_GPIO
#define PAD_GPIO21_PM_IS_GPIO 0
#endif 

#define PAD_HOTPLUGC 9999
#ifndef PAD_HOTPLUGC_IS_GPIO
#define PAD_HOTPLUGC_IS_GPIO 0
#endif 

#define PAD_GPIO24_PM 9999
#ifndef PAD_GPIO24_PM_IS_GPIO
#define PAD_GPIO24_PM_IS_GPIO 0
#endif 

#define PAD_HOTPLUGC_HDMI20_5V 9999
#ifndef PAD_HOTPLUGC_HDMI20_5V_IS_GPIO
#define PAD_HOTPLUGC_HDMI20_5V_IS_GPIO 0
#endif 

#define BALL_AG4 PAD_GPIO15_PM
#define PAD_GPIO15_PM 24
#define GPIO_PAD_24 GPIO23
#ifndef BALL_AG4_IS_GPIO
#define BALL_AG4_IS_GPIO 0
#endif 
#ifndef PAD_GPIO15_PM_IS_GPIO
#define PAD_GPIO15_PM_IS_GPIO BALL_AG4_IS_GPIO
#endif 

#define BALL_Y5 PAD_HOTPLUGB
#define PAD_HOTPLUGB 37
#define GPIO_PAD_37 GPIO36
#ifndef BALL_Y5_IS_GPIO
#define BALL_Y5_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGB_IS_GPIO
#define PAD_HOTPLUGB_IS_GPIO BALL_Y5_IS_GPIO
#endif 

#define BALL_Y4 PAD_HOTPLUGB_HDMI20_5V
#define PAD_HOTPLUGB_HDMI20_5V 41
#define GPIO_PAD_41 GPIO40
#ifndef BALL_Y4_IS_GPIO
#define BALL_Y4_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGB_HDMI20_5V_IS_GPIO
#define PAD_HOTPLUGB_HDMI20_5V_IS_GPIO BALL_Y4_IS_GPIO
#endif 

#define BALL_W6 PAD_HOTPLUGD
#define PAD_HOTPLUGD 39
#define GPIO_PAD_39 GPIO38
#ifndef BALL_W6_IS_GPIO
#define BALL_W6_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGD_IS_GPIO
#define PAD_HOTPLUGD_IS_GPIO BALL_W6_IS_GPIO
#endif 

#define BALL_Y6 PAD_HOTPLUGD_HDMI20_5V
#define PAD_HOTPLUGD_HDMI20_5V 43
#define GPIO_PAD_43 GPIO42
#ifndef BALL_Y6_IS_GPIO
#define BALL_Y6_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGD_HDMI20_5V_IS_GPIO
#define PAD_HOTPLUGD_HDMI20_5V_IS_GPIO BALL_Y6_IS_GPIO
#endif 

#define BALL_AB4 PAD_DDCDA_CK
#define PAD_DDCDA_CK 44
#define GPIO_PAD_44 GPIO43
#ifndef BALL_AB4_IS_GPIO
#define BALL_AB4_IS_GPIO 0
#endif 
#ifndef PAD_DDCDA_CK_IS_GPIO
#define PAD_DDCDA_CK_IS_GPIO BALL_AB4_IS_GPIO
#endif 

#define BALL_AB5 PAD_DDCDA_DA
#define PAD_DDCDA_DA 45
#define GPIO_PAD_45 GPIO44
#ifndef BALL_AB5_IS_GPIO
#define BALL_AB5_IS_GPIO 0
#endif 
#ifndef PAD_DDCDA_DA_IS_GPIO
#define PAD_DDCDA_DA_IS_GPIO BALL_AB5_IS_GPIO
#endif 

#define BALL_AA6 PAD_DDCDB_CK
#define PAD_DDCDB_CK 46
#define GPIO_PAD_46 GPIO45
#ifndef BALL_AA6_IS_GPIO
#define BALL_AA6_IS_GPIO 0
#endif 
#ifndef PAD_DDCDB_CK_IS_GPIO
#define PAD_DDCDB_CK_IS_GPIO BALL_AA6_IS_GPIO
#endif 

#define BALL_AA5 PAD_DDCDB_DA
#define PAD_DDCDB_DA 47
#define GPIO_PAD_47 GPIO46
#ifndef BALL_AA5_IS_GPIO
#define BALL_AA5_IS_GPIO 0
#endif 
#ifndef PAD_DDCDB_DA_IS_GPIO
#define PAD_DDCDB_DA_IS_GPIO BALL_AA5_IS_GPIO
#endif 

#define PAD_DDCDC_CK 9999
#ifndef PAD_DDCDC_CK_IS_GPIO
#define PAD_DDCDC_CK_IS_GPIO 0
#endif 

#define PAD_DDCDC_DA 9999
#ifndef PAD_DDCDC_DA_IS_GPIO
#define PAD_DDCDC_DA_IS_GPIO 0
#endif 

#define BALL_W4 PAD_DDCDD_CK
#define PAD_DDCDD_CK 50
#define GPIO_PAD_50 GPIO49
#ifndef BALL_W4_IS_GPIO
#define BALL_W4_IS_GPIO 0
#endif 
#ifndef PAD_DDCDD_CK_IS_GPIO
#define PAD_DDCDD_CK_IS_GPIO BALL_W4_IS_GPIO
#endif 

#define BALL_W5 PAD_DDCDD_DA
#define PAD_DDCDD_DA 51
#define GPIO_PAD_51 GPIO50
#ifndef BALL_W5_IS_GPIO
#define BALL_W5_IS_GPIO 0
#endif 
#ifndef PAD_DDCDD_DA_IS_GPIO
#define PAD_DDCDD_DA_IS_GPIO BALL_W5_IS_GPIO
#endif 

#define BALL_AK2 PAD_DDCA_CK
#define PAD_DDCA_CK 8
#define GPIO_PAD_8 GPIO7
#ifndef BALL_AK2_IS_GPIO
#define BALL_AK2_IS_GPIO 0
#endif 
#ifndef PAD_DDCA_CK_IS_GPIO
#define PAD_DDCA_CK_IS_GPIO BALL_AK2_IS_GPIO
#endif 

#define BALL_AL1 PAD_DDCA_DA
#define PAD_DDCA_DA 9
#define GPIO_PAD_9 GPIO8
#ifndef BALL_AL1_IS_GPIO
#define BALL_AL1_IS_GPIO 0
#endif 
#ifndef PAD_DDCA_DA_IS_GPIO
#define PAD_DDCA_DA_IS_GPIO BALL_AL1_IS_GPIO
#endif 

#define BALL_R1 PAD_PM_SPI_DI
#define PAD_PM_SPI_DI 3
#define GPIO_PAD_3 GPIO2
#ifndef BALL_R1_IS_GPIO
#define BALL_R1_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_DI_IS_GPIO
#define PAD_PM_SPI_DI_IS_GPIO BALL_R1_IS_GPIO
#endif 

#define BALL_P2 PAD_PM_SPI_DO
#define PAD_PM_SPI_DO 4
#define GPIO_PAD_4 GPIO3
#ifndef BALL_P2_IS_GPIO
#define BALL_P2_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_DO_IS_GPIO
#define PAD_PM_SPI_DO_IS_GPIO BALL_P2_IS_GPIO
#endif 

#define BALL_P1 PAD_PM_SPI_CK
#define PAD_PM_SPI_CK 2
#define GPIO_PAD_2 GPIO1
#ifndef BALL_P1_IS_GPIO
#define BALL_P1_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_CK_IS_GPIO
#define PAD_PM_SPI_CK_IS_GPIO BALL_P1_IS_GPIO
#endif 

#define BALL_AG5 PAD_PWM_PM
#define PAD_PWM_PM 7
#define GPIO_PAD_7 GPIO6
#ifndef BALL_AG5_IS_GPIO
#define BALL_AG5_IS_GPIO 0
#endif 
#ifndef PAD_PWM_PM_IS_GPIO
#define PAD_PWM_PM_IS_GPIO BALL_AG5_IS_GPIO
#endif 

#define BALL_AM2 PAD_IRIN
#define PAD_IRIN 5
#define GPIO_PAD_5 GPIO4
#ifndef BALL_AM2_IS_GPIO
#define BALL_AM2_IS_GPIO 0
#endif 
#ifndef PAD_IRIN_IS_GPIO
#define PAD_IRIN_IS_GPIO BALL_AM2_IS_GPIO
#endif 

#define BALL_AC4 PAD_CEC0
#define PAD_CEC0 6
#define GPIO_PAD_6 GPIO5
#ifndef BALL_AC4_IS_GPIO
#define BALL_AC4_IS_GPIO 0
#endif 
#ifndef PAD_CEC0_IS_GPIO
#define PAD_CEC0_IS_GPIO BALL_AC4_IS_GPIO
#endif 

#define BALL_AD6 PAD_WOL_INT_OUT
#define PAD_WOL_INT_OUT 62
#define GPIO_PAD_62 GPIO61
#ifndef BALL_AD6_IS_GPIO
#define BALL_AD6_IS_GPIO 0
#endif 
#ifndef PAD_WOL_INT_OUT_IS_GPIO
#define PAD_WOL_INT_OUT_IS_GPIO BALL_AD6_IS_GPIO
#endif 

#define BALL_T4 PAD_LED0
#define PAD_LED0 34
#define GPIO_PAD_34 GPIO33
#ifndef BALL_T4_IS_GPIO
#define BALL_T4_IS_GPIO 0
#endif 
#ifndef PAD_LED0_IS_GPIO
#define PAD_LED0_IS_GPIO BALL_T4_IS_GPIO
#endif 

#define BALL_U4 PAD_LED1
#define PAD_LED1 35
#define GPIO_PAD_35 GPIO34
#ifndef BALL_U4_IS_GPIO
#define BALL_U4_IS_GPIO 0
#endif 
#ifndef PAD_LED1_IS_GPIO
#define PAD_LED1_IS_GPIO BALL_U4_IS_GPIO
#endif 

#define BALL_AL3 PAD_VID0
#define PAD_VID0 58
#define GPIO_PAD_58 GPIO57
#ifndef BALL_AL3_IS_GPIO
#define BALL_AL3_IS_GPIO 0
#endif 
#ifndef PAD_VID0_IS_GPIO
#define PAD_VID0_IS_GPIO BALL_AL3_IS_GPIO
#endif 

#define BALL_AM3 PAD_VID1
#define PAD_VID1 59
#define GPIO_PAD_59 GPIO58
#ifndef BALL_AM3_IS_GPIO
#define BALL_AM3_IS_GPIO 0
#endif 
#ifndef PAD_VID1_IS_GPIO
#define PAD_VID1_IS_GPIO BALL_AM3_IS_GPIO
#endif 

#define PAD_VID2 9999
#ifndef PAD_VID2_IS_GPIO
#define PAD_VID2_IS_GPIO 0
#endif 

#define PAD_VID3 9999
#ifndef PAD_VID3_IS_GPIO
#define PAD_VID3_IS_GPIO 0
#endif 

#define BALL_N2 PAD_VPLUGIN
#define PAD_VPLUGIN 57
#define GPIO_PAD_57 GPIO56
#ifndef BALL_N2_IS_GPIO
#define BALL_N2_IS_GPIO 0
#endif 
#ifndef PAD_VPLUGIN_IS_GPIO
#define PAD_VPLUGIN_IS_GPIO BALL_N2_IS_GPIO
#endif 

#define PAD_SAR4 9999
#ifndef PAD_SAR4_IS_GPIO
#define PAD_SAR4_IS_GPIO 0
#endif 

#define BALL_N3 PAD_SAR3
#define PAD_SAR3 55
#define GPIO_PAD_55 GPIO54
#ifndef BALL_N3_IS_GPIO
#define BALL_N3_IS_GPIO 0
#endif 
#ifndef PAD_SAR3_IS_GPIO
#define PAD_SAR3_IS_GPIO BALL_N3_IS_GPIO
#endif 

#define BALL_M3 PAD_SAR2
#define PAD_SAR2 54
#define GPIO_PAD_54 GPIO53
#ifndef BALL_M3_IS_GPIO
#define BALL_M3_IS_GPIO 0
#endif 
#ifndef PAD_SAR2_IS_GPIO
#define PAD_SAR2_IS_GPIO BALL_M3_IS_GPIO
#endif 

#define BALL_M2 PAD_SAR1
#define PAD_SAR1 53
#define GPIO_PAD_53 GPIO52
#ifndef BALL_M2_IS_GPIO
#define BALL_M2_IS_GPIO 0
#endif 
#ifndef PAD_SAR1_IS_GPIO
#define PAD_SAR1_IS_GPIO BALL_M2_IS_GPIO
#endif 

#define BALL_M1 PAD_SAR0
#define PAD_SAR0 52
#define GPIO_PAD_52 GPIO51
#ifndef BALL_M1_IS_GPIO
#define BALL_M1_IS_GPIO 0
#endif 
#ifndef PAD_SAR0_IS_GPIO
#define PAD_SAR0_IS_GPIO BALL_M1_IS_GPIO
#endif 

#define BALL_AC5 PAD_HDMIRX_ARCTX
#define PAD_HDMIRX_ARCTX 103
#define GPIO_PAD_103 GPIO102
#ifndef BALL_AC5_IS_GPIO
#define BALL_AC5_IS_GPIO 0
#endif 
#ifndef PAD_HDMIRX_ARCTX_IS_GPIO
#define PAD_HDMIRX_ARCTX_IS_GPIO BALL_AC5_IS_GPIO
#endif 

#define BALL_AH5 PAD_TS2_D0
#define PAD_TS2_D0 186
#define GPIO_PAD_186 GPIO185
#ifndef BALL_AH5_IS_GPIO
#define BALL_AH5_IS_GPIO 0
#endif 
#ifndef PAD_TS2_D0_IS_GPIO
#define PAD_TS2_D0_IS_GPIO BALL_AH5_IS_GPIO
#endif 

#define PAD_TS2_D1 9999
#ifndef PAD_TS2_D1_IS_GPIO
#define PAD_TS2_D1_IS_GPIO 0
#endif 

#define PAD_TS2_D2 9999
#ifndef PAD_TS2_D2_IS_GPIO
#define PAD_TS2_D2_IS_GPIO 0
#endif 

#define PAD_TS2_D3 9999
#ifndef PAD_TS2_D3_IS_GPIO
#define PAD_TS2_D3_IS_GPIO 0
#endif 

#define PAD_TS2_D4 9999
#ifndef PAD_TS2_D4_IS_GPIO
#define PAD_TS2_D4_IS_GPIO 0
#endif 

#define PAD_TS2_D5 9999
#ifndef PAD_TS2_D5_IS_GPIO
#define PAD_TS2_D5_IS_GPIO 0
#endif 

#define PAD_TS2_D6 9999
#ifndef PAD_TS2_D6_IS_GPIO
#define PAD_TS2_D6_IS_GPIO 0
#endif 

#define PAD_TS2_D7 9999
#ifndef PAD_TS2_D7_IS_GPIO
#define PAD_TS2_D7_IS_GPIO 0
#endif 

#define BALL_AJ5 PAD_TS2_VLD
#define PAD_TS2_VLD 195
#define GPIO_PAD_195 GPIO194
#ifndef BALL_AJ5_IS_GPIO
#define BALL_AJ5_IS_GPIO 0
#endif 
#ifndef PAD_TS2_VLD_IS_GPIO
#define PAD_TS2_VLD_IS_GPIO BALL_AJ5_IS_GPIO
#endif 

#define BALL_AJ4 PAD_TS2_CLK
#define PAD_TS2_CLK 185
#define GPIO_PAD_185 GPIO184
#ifndef BALL_AJ4_IS_GPIO
#define BALL_AJ4_IS_GPIO 0
#endif 
#ifndef PAD_TS2_CLK_IS_GPIO
#define PAD_TS2_CLK_IS_GPIO BALL_AJ4_IS_GPIO
#endif 

#define BALL_AH4 PAD_TS2_SYNC
#define PAD_TS2_SYNC 194
#define GPIO_PAD_194 GPIO193
#ifndef BALL_AH4_IS_GPIO
#define BALL_AH4_IS_GPIO 0
#endif 
#ifndef PAD_TS2_SYNC_IS_GPIO
#define PAD_TS2_SYNC_IS_GPIO BALL_AH4_IS_GPIO
#endif 

#define PAD_TS3_SYNC 9999
#ifndef PAD_TS3_SYNC_IS_GPIO
#define PAD_TS3_SYNC_IS_GPIO 0
#endif 

#define PAD_TS3_VLD 9999
#ifndef PAD_TS3_VLD_IS_GPIO
#define PAD_TS3_VLD_IS_GPIO 0
#endif 

#define PAD_TS3_CLK 9999
#ifndef PAD_TS3_CLK_IS_GPIO
#define PAD_TS3_CLK_IS_GPIO 0
#endif 

#define PAD_TS3_D0 9999
#ifndef PAD_TS3_D0_IS_GPIO
#define PAD_TS3_D0_IS_GPIO 0
#endif 

#define PAD_TS3_D1 9999
#ifndef PAD_TS3_D1_IS_GPIO
#define PAD_TS3_D1_IS_GPIO 0
#endif 

#define PAD_TS3_D2 9999
#ifndef PAD_TS3_D2_IS_GPIO
#define PAD_TS3_D2_IS_GPIO 0
#endif 

#define PAD_TS3_D3 9999
#ifndef PAD_TS3_D3_IS_GPIO
#define PAD_TS3_D3_IS_GPIO 0
#endif 

#define PAD_TS3_D4 9999
#ifndef PAD_TS3_D4_IS_GPIO
#define PAD_TS3_D4_IS_GPIO 0
#endif 

#define PAD_TS3_D5 9999
#ifndef PAD_TS3_D5_IS_GPIO
#define PAD_TS3_D5_IS_GPIO 0
#endif 

#define PAD_TS3_D6 9999
#ifndef PAD_TS3_D6_IS_GPIO
#define PAD_TS3_D6_IS_GPIO 0
#endif 

#define PAD_TS3_D7 9999
#ifndef PAD_TS3_D7_IS_GPIO
#define PAD_TS3_D7_IS_GPIO 0
#endif 

#define BALL_R7 PAD_GPIO8
#define PAD_GPIO8 77
#define GPIO_PAD_77 GPIO76
#ifndef BALL_R7_IS_GPIO
#define BALL_R7_IS_GPIO 0
#endif 
#ifndef PAD_GPIO8_IS_GPIO
#define PAD_GPIO8_IS_GPIO BALL_R7_IS_GPIO
#endif 

#define BALL_P7 PAD_GPIO7
#define PAD_GPIO7 76
#define GPIO_PAD_76 GPIO75
#ifndef BALL_P7_IS_GPIO
#define BALL_P7_IS_GPIO 0
#endif 
#ifndef PAD_GPIO7_IS_GPIO
#define PAD_GPIO7_IS_GPIO BALL_P7_IS_GPIO
#endif 

#define PAD_GPIO6 9999
#ifndef PAD_GPIO6_IS_GPIO
#define PAD_GPIO6_IS_GPIO 0
#endif 

#define PAD_GPIO1 9999
#ifndef PAD_GPIO1_IS_GPIO
#define PAD_GPIO1_IS_GPIO 0
#endif 

#define PAD_GPIO0 9999
#ifndef PAD_GPIO0_IS_GPIO
#define PAD_GPIO0_IS_GPIO 0
#endif 

#define BALL_AG6 PAD_SPDIF_OUT
#define PAD_SPDIF_OUT 158
#define GPIO_PAD_158 GPIO157
#ifndef BALL_AG6_IS_GPIO
#define BALL_AG6_IS_GPIO 0
#endif 
#ifndef PAD_SPDIF_OUT_IS_GPIO
#define PAD_SPDIF_OUT_IS_GPIO BALL_AG6_IS_GPIO
#endif 

#define BALL_AF16 PAD_PWM3
#define PAD_PWM3 155
#define GPIO_PAD_155 GPIO154
#ifndef BALL_AF16_IS_GPIO
#define BALL_AF16_IS_GPIO 0
#endif 
#ifndef PAD_PWM3_IS_GPIO
#define PAD_PWM3_IS_GPIO BALL_AF16_IS_GPIO
#endif 

#define BALL_AE16 PAD_PWM2
#define PAD_PWM2 154
#define GPIO_PAD_154 GPIO153
#ifndef BALL_AE16_IS_GPIO
#define BALL_AE16_IS_GPIO 0
#endif 
#ifndef PAD_PWM2_IS_GPIO
#define PAD_PWM2_IS_GPIO BALL_AE16_IS_GPIO
#endif 

#define BALL_AL2 PAD_PWM1
#define PAD_PWM1 153
#define GPIO_PAD_153 GPIO152
#ifndef BALL_AL2_IS_GPIO
#define BALL_AL2_IS_GPIO 0
#endif 
#ifndef PAD_PWM1_IS_GPIO
#define PAD_PWM1_IS_GPIO BALL_AL2_IS_GPIO
#endif 

#define BALL_AK3 PAD_PWM0
#define PAD_PWM0 152
#define GPIO_PAD_152 GPIO151
#ifndef BALL_AK3_IS_GPIO
#define BALL_AK3_IS_GPIO 0
#endif 
#ifndef PAD_PWM0_IS_GPIO
#define PAD_PWM0_IS_GPIO BALL_AK3_IS_GPIO
#endif 

#define PAD_GPIO13 9999
#ifndef PAD_GPIO13_IS_GPIO
#define PAD_GPIO13_IS_GPIO 0
#endif 

#define PAD_GPIO14 9999
#ifndef PAD_GPIO14_IS_GPIO
#define PAD_GPIO14_IS_GPIO 0
#endif 

#define PAD_GPIO24 9999
#ifndef PAD_GPIO24_IS_GPIO
#define PAD_GPIO24_IS_GPIO 0
#endif 

#define BALL_AK4 PAD_GPIO25
#define PAD_GPIO25 94
#define GPIO_PAD_94 GPIO93
#ifndef BALL_AK4_IS_GPIO
#define BALL_AK4_IS_GPIO 0
#endif 
#ifndef PAD_GPIO25_IS_GPIO
#define PAD_GPIO25_IS_GPIO BALL_AK4_IS_GPIO
#endif 

#define BALL_AM4 PAD_GPIO26
#define PAD_GPIO26 95
#define GPIO_PAD_95 GPIO94
#ifndef BALL_AM4_IS_GPIO
#define BALL_AM4_IS_GPIO 0
#endif 
#ifndef PAD_GPIO26_IS_GPIO
#define PAD_GPIO26_IS_GPIO BALL_AM4_IS_GPIO
#endif 

#define PAD_GPIO27 9999
#ifndef PAD_GPIO27_IS_GPIO
#define PAD_GPIO27_IS_GPIO 0
#endif 

#define PAD_GPIO28 9999
#ifndef PAD_GPIO28_IS_GPIO
#define PAD_GPIO28_IS_GPIO 0
#endif 

#define PAD_GPIO29 9999
#ifndef PAD_GPIO29_IS_GPIO
#define PAD_GPIO29_IS_GPIO 0
#endif 

#define PAD_GPIO30 9999
#ifndef PAD_GPIO30_IS_GPIO
#define PAD_GPIO30_IS_GPIO 0
#endif 

#define PAD_GPIO31 9999
#ifndef PAD_GPIO31_IS_GPIO
#define PAD_GPIO31_IS_GPIO 0
#endif 

#define PAD_GPIO17 9999
#ifndef PAD_GPIO17_IS_GPIO
#define PAD_GPIO17_IS_GPIO 0
#endif 

#define PAD_GPIO18 9999
#ifndef PAD_GPIO18_IS_GPIO
#define PAD_GPIO18_IS_GPIO 0
#endif 

#define BALL_R3 PAD_GPIO19
#define PAD_GPIO19 88
#define GPIO_PAD_88 GPIO87
#ifndef BALL_R3_IS_GPIO
#define BALL_R3_IS_GPIO 0
#endif 
#ifndef PAD_GPIO19_IS_GPIO
#define PAD_GPIO19_IS_GPIO BALL_R3_IS_GPIO
#endif 

#define BALL_R2 PAD_GPIO20
#define PAD_GPIO20 89
#define GPIO_PAD_89 GPIO88
#ifndef BALL_R2_IS_GPIO
#define BALL_R2_IS_GPIO 0
#endif 
#ifndef PAD_GPIO20_IS_GPIO
#define PAD_GPIO20_IS_GPIO BALL_R2_IS_GPIO
#endif 

#define PAD_GPIO21 9999
#ifndef PAD_GPIO21_IS_GPIO
#define PAD_GPIO21_IS_GPIO 0
#endif 

#define PAD_GPIO22 9999
#ifndef PAD_GPIO22_IS_GPIO
#define PAD_GPIO22_IS_GPIO 0
#endif 

#define PAD_GPIO23 9999
#ifndef PAD_GPIO23_IS_GPIO
#define PAD_GPIO23_IS_GPIO 0
#endif 

#define PAD_GPIO36 9999
#ifndef PAD_GPIO36_IS_GPIO
#define PAD_GPIO36_IS_GPIO 0
#endif 

#define PAD_GPIO37 9999
#ifndef PAD_GPIO37_IS_GPIO
#define PAD_GPIO37_IS_GPIO 0
#endif 

#define BALL_AF18 PAD_TGPIO0
#define PAD_TGPIO0 159
#define GPIO_PAD_159 GPIO158
#ifndef BALL_AF18_IS_GPIO
#define BALL_AF18_IS_GPIO 0
#endif 
#ifndef PAD_TGPIO0_IS_GPIO
#define PAD_TGPIO0_IS_GPIO BALL_AF18_IS_GPIO
#endif 

#define BALL_AF19 PAD_TGPIO1
#define PAD_TGPIO1 160
#define GPIO_PAD_160 GPIO159
#ifndef BALL_AF19_IS_GPIO
#define BALL_AF19_IS_GPIO 0
#endif 
#ifndef PAD_TGPIO1_IS_GPIO
#define PAD_TGPIO1_IS_GPIO BALL_AF19_IS_GPIO
#endif 

#define BALL_AK7 PAD_TGPIO2
#define PAD_TGPIO2 161
#define GPIO_PAD_161 GPIO160
#ifndef BALL_AK7_IS_GPIO
#define BALL_AK7_IS_GPIO 0
#endif 
#ifndef PAD_TGPIO2_IS_GPIO
#define PAD_TGPIO2_IS_GPIO BALL_AK7_IS_GPIO
#endif 

#define BALL_AM7 PAD_TGPIO3
#define PAD_TGPIO3 162
#define GPIO_PAD_162 GPIO161
#ifndef BALL_AM7_IS_GPIO
#define BALL_AM7_IS_GPIO 0
#endif 
#ifndef PAD_TGPIO3_IS_GPIO
#define PAD_TGPIO3_IS_GPIO BALL_AM7_IS_GPIO
#endif 

#define PAD_GPIO12 9999
#ifndef PAD_GPIO12_IS_GPIO
#define PAD_GPIO12_IS_GPIO 0
#endif 

#define PAD_GPIO11 9999
#ifndef PAD_GPIO11_IS_GPIO
#define PAD_GPIO11_IS_GPIO 0
#endif 

#define PAD_GPIO10 9999
#ifndef PAD_GPIO10_IS_GPIO
#define PAD_GPIO10_IS_GPIO 0
#endif 

#define PAD_GPIO9 9999
#ifndef PAD_GPIO9_IS_GPIO
#define PAD_GPIO9_IS_GPIO 0
#endif 

#define PAD_GPIO15 9999
#ifndef PAD_GPIO15_IS_GPIO
#define PAD_GPIO15_IS_GPIO 0
#endif 

#define BALL_AG9 PAD_TS0_D7
#define PAD_TS0_D7 171
#define GPIO_PAD_171 GPIO170
#ifndef BALL_AG9_IS_GPIO
#define BALL_AG9_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D7_IS_GPIO
#define PAD_TS0_D7_IS_GPIO BALL_AG9_IS_GPIO
#endif 

#define BALL_AJ8 PAD_TS0_D6
#define PAD_TS0_D6 170
#define GPIO_PAD_170 GPIO169
#ifndef BALL_AJ8_IS_GPIO
#define BALL_AJ8_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D6_IS_GPIO
#define PAD_TS0_D6_IS_GPIO BALL_AJ8_IS_GPIO
#endif 

#define BALL_AH9 PAD_TS0_D5
#define PAD_TS0_D5 169
#define GPIO_PAD_169 GPIO168
#ifndef BALL_AH9_IS_GPIO
#define BALL_AH9_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D5_IS_GPIO
#define PAD_TS0_D5_IS_GPIO BALL_AH9_IS_GPIO
#endif 

#define BALL_AJ9 PAD_TS0_D4
#define PAD_TS0_D4 168
#define GPIO_PAD_168 GPIO167
#ifndef BALL_AJ9_IS_GPIO
#define BALL_AJ9_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D4_IS_GPIO
#define PAD_TS0_D4_IS_GPIO BALL_AJ9_IS_GPIO
#endif 

#define BALL_AJ10 PAD_TS0_D3
#define PAD_TS0_D3 167
#define GPIO_PAD_167 GPIO166
#ifndef BALL_AJ10_IS_GPIO
#define BALL_AJ10_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D3_IS_GPIO
#define PAD_TS0_D3_IS_GPIO BALL_AJ10_IS_GPIO
#endif 

#define BALL_AJ6 PAD_TS0_D2
#define PAD_TS0_D2 166
#define GPIO_PAD_166 GPIO165
#ifndef BALL_AJ6_IS_GPIO
#define BALL_AJ6_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D2_IS_GPIO
#define PAD_TS0_D2_IS_GPIO BALL_AJ6_IS_GPIO
#endif 

#define BALL_AH6 PAD_TS0_D1
#define PAD_TS0_D1 165
#define GPIO_PAD_165 GPIO164
#ifndef BALL_AH6_IS_GPIO
#define BALL_AH6_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D1_IS_GPIO
#define PAD_TS0_D1_IS_GPIO BALL_AH6_IS_GPIO
#endif 

#define BALL_AJ7 PAD_TS0_D0
#define PAD_TS0_D0 164
#define GPIO_PAD_164 GPIO163
#ifndef BALL_AJ7_IS_GPIO
#define BALL_AJ7_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D0_IS_GPIO
#define PAD_TS0_D0_IS_GPIO BALL_AJ7_IS_GPIO
#endif 

#define BALL_AG8 PAD_TS0_CLK
#define PAD_TS0_CLK 163
#define GPIO_PAD_163 GPIO162
#ifndef BALL_AG8_IS_GPIO
#define BALL_AG8_IS_GPIO 0
#endif 
#ifndef PAD_TS0_CLK_IS_GPIO
#define PAD_TS0_CLK_IS_GPIO BALL_AG8_IS_GPIO
#endif 

#define BALL_AH7 PAD_TS0_SYNC
#define PAD_TS0_SYNC 172
#define GPIO_PAD_172 GPIO171
#ifndef BALL_AH7_IS_GPIO
#define BALL_AH7_IS_GPIO 0
#endif 
#ifndef PAD_TS0_SYNC_IS_GPIO
#define PAD_TS0_SYNC_IS_GPIO BALL_AH7_IS_GPIO
#endif 

#define BALL_AG7 PAD_TS0_VLD
#define PAD_TS0_VLD 173
#define GPIO_PAD_173 GPIO172
#ifndef BALL_AG7_IS_GPIO
#define BALL_AG7_IS_GPIO 0
#endif 
#ifndef PAD_TS0_VLD_IS_GPIO
#define PAD_TS0_VLD_IS_GPIO BALL_AG7_IS_GPIO
#endif 

#define BALL_AL18 PAD_TS1_D6
#define PAD_TS1_D6 181
#define GPIO_PAD_181 GPIO180
#ifndef BALL_AL18_IS_GPIO
#define BALL_AL18_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D6_IS_GPIO
#define PAD_TS1_D6_IS_GPIO BALL_AL18_IS_GPIO
#endif 

#define BALL_AK18 PAD_TS1_D7
#define PAD_TS1_D7 182
#define GPIO_PAD_182 GPIO181
#ifndef BALL_AK18_IS_GPIO
#define BALL_AK18_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D7_IS_GPIO
#define PAD_TS1_D7_IS_GPIO BALL_AK18_IS_GPIO
#endif 

#define BALL_AM18 PAD_TS1_D5
#define PAD_TS1_D5 180
#define GPIO_PAD_180 GPIO179
#ifndef BALL_AM18_IS_GPIO
#define BALL_AM18_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D5_IS_GPIO
#define PAD_TS1_D5_IS_GPIO BALL_AM18_IS_GPIO
#endif 

#define BALL_AL19 PAD_TS1_D4
#define PAD_TS1_D4 179
#define GPIO_PAD_179 GPIO178
#ifndef BALL_AL19_IS_GPIO
#define BALL_AL19_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D4_IS_GPIO
#define PAD_TS1_D4_IS_GPIO BALL_AL19_IS_GPIO
#endif 

#define BALL_AK20 PAD_TS1_D3
#define PAD_TS1_D3 178
#define GPIO_PAD_178 GPIO177
#ifndef BALL_AK20_IS_GPIO
#define BALL_AK20_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D3_IS_GPIO
#define PAD_TS1_D3_IS_GPIO BALL_AK20_IS_GPIO
#endif 

#define BALL_AL20 PAD_TS1_D2
#define PAD_TS1_D2 177
#define GPIO_PAD_177 GPIO176
#ifndef BALL_AL20_IS_GPIO
#define BALL_AL20_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D2_IS_GPIO
#define PAD_TS1_D2_IS_GPIO BALL_AL20_IS_GPIO
#endif 

#define BALL_AK21 PAD_TS1_D1
#define PAD_TS1_D1 176
#define GPIO_PAD_176 GPIO175
#ifndef BALL_AK21_IS_GPIO
#define BALL_AK21_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D1_IS_GPIO
#define PAD_TS1_D1_IS_GPIO BALL_AK21_IS_GPIO
#endif 

#define BALL_AL21 PAD_TS1_D0
#define PAD_TS1_D0 175
#define GPIO_PAD_175 GPIO174
#ifndef BALL_AL21_IS_GPIO
#define BALL_AL21_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D0_IS_GPIO
#define PAD_TS1_D0_IS_GPIO BALL_AL21_IS_GPIO
#endif 

#define BALL_AK19 PAD_TS1_CLK
#define PAD_TS1_CLK 174
#define GPIO_PAD_174 GPIO173
#ifndef BALL_AK19_IS_GPIO
#define BALL_AK19_IS_GPIO 0
#endif 
#ifndef PAD_TS1_CLK_IS_GPIO
#define PAD_TS1_CLK_IS_GPIO BALL_AK19_IS_GPIO
#endif 

#define BALL_AM21 PAD_TS1_SYNC
#define PAD_TS1_SYNC 183
#define GPIO_PAD_183 GPIO182
#ifndef BALL_AM21_IS_GPIO
#define BALL_AM21_IS_GPIO 0
#endif 
#ifndef PAD_TS1_SYNC_IS_GPIO
#define PAD_TS1_SYNC_IS_GPIO BALL_AM21_IS_GPIO
#endif 

#define BALL_AM19 PAD_TS1_VLD
#define PAD_TS1_VLD 184
#define GPIO_PAD_184 GPIO183
#ifndef BALL_AM19_IS_GPIO
#define BALL_AM19_IS_GPIO 0
#endif 
#ifndef PAD_TS1_VLD_IS_GPIO
#define PAD_TS1_VLD_IS_GPIO BALL_AM19_IS_GPIO
#endif 

#define BALL_AG10 PAD_PCM2_IRQA_N
#define PAD_PCM2_IRQA_N 116
#define GPIO_PAD_116 GPIO115
#ifndef BALL_AG10_IS_GPIO
#define BALL_AG10_IS_GPIO 0
#endif 
#ifndef PAD_PCM2_IRQA_N_IS_GPIO
#define PAD_PCM2_IRQA_N_IS_GPIO BALL_AG10_IS_GPIO
#endif 

#define BALL_AH10 PAD_PCM2_CE_N
#define PAD_PCM2_CE_N 115
#define GPIO_PAD_115 GPIO114
#ifndef BALL_AH10_IS_GPIO
#define BALL_AH10_IS_GPIO 0
#endif 
#ifndef PAD_PCM2_CE_N_IS_GPIO
#define PAD_PCM2_CE_N_IS_GPIO BALL_AH10_IS_GPIO
#endif 

#define PAD_PCM2_RESET 9999
#ifndef PAD_PCM2_RESET_IS_GPIO
#define PAD_PCM2_RESET_IS_GPIO 0
#endif 

#define PAD_PCM2_WAIT_N 9999
#ifndef PAD_PCM2_WAIT_N_IS_GPIO
#define PAD_PCM2_WAIT_N_IS_GPIO 0
#endif 

#define PAD_PCM2_CD_N 9999
#ifndef PAD_PCM2_CD_N_IS_GPIO
#define PAD_PCM2_CD_N_IS_GPIO 0
#endif 

#define BALL_AJ13 PAD_PCM_D7
#define PAD_PCM_D7 143
#define GPIO_PAD_143 GPIO142
#ifndef BALL_AJ13_IS_GPIO
#define BALL_AJ13_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D7_IS_GPIO
#define PAD_PCM_D7_IS_GPIO BALL_AJ13_IS_GPIO
#endif 

#define BALL_AJ12 PAD_PCM_D6
#define PAD_PCM_D6 142
#define GPIO_PAD_142 GPIO141
#ifndef BALL_AJ12_IS_GPIO
#define BALL_AJ12_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D6_IS_GPIO
#define PAD_PCM_D6_IS_GPIO BALL_AJ12_IS_GPIO
#endif 

#define BALL_AH12 PAD_PCM_D5
#define PAD_PCM_D5 141
#define GPIO_PAD_141 GPIO140
#ifndef BALL_AH12_IS_GPIO
#define BALL_AH12_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D5_IS_GPIO
#define PAD_PCM_D5_IS_GPIO BALL_AH12_IS_GPIO
#endif 

#define BALL_AJ11 PAD_PCM_D4
#define PAD_PCM_D4 140
#define GPIO_PAD_140 GPIO139
#ifndef BALL_AJ11_IS_GPIO
#define BALL_AJ11_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D4_IS_GPIO
#define PAD_PCM_D4_IS_GPIO BALL_AJ11_IS_GPIO
#endif 

#define BALL_AG12 PAD_PCM_D3
#define PAD_PCM_D3 139
#define GPIO_PAD_139 GPIO138
#ifndef BALL_AG12_IS_GPIO
#define BALL_AG12_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D3_IS_GPIO
#define PAD_PCM_D3_IS_GPIO BALL_AG12_IS_GPIO
#endif 

#define BALL_AH22 PAD_PCM_D2
#define PAD_PCM_D2 138
#define GPIO_PAD_138 GPIO137
#ifndef BALL_AH22_IS_GPIO
#define BALL_AH22_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D2_IS_GPIO
#define PAD_PCM_D2_IS_GPIO BALL_AH22_IS_GPIO
#endif 

#define BALL_AJ23 PAD_PCM_D1
#define PAD_PCM_D1 137
#define GPIO_PAD_137 GPIO136
#ifndef BALL_AJ23_IS_GPIO
#define BALL_AJ23_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D1_IS_GPIO
#define PAD_PCM_D1_IS_GPIO BALL_AJ23_IS_GPIO
#endif 

#define BALL_AJ22 PAD_PCM_D0
#define PAD_PCM_D0 136
#define GPIO_PAD_136 GPIO135
#ifndef BALL_AJ22_IS_GPIO
#define BALL_AJ22_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D0_IS_GPIO
#define PAD_PCM_D0_IS_GPIO BALL_AJ22_IS_GPIO
#endif 

#define BALL_AJ17 PAD_PCM_WAIT_N
#define PAD_PCM_WAIT_N 150
#define GPIO_PAD_150 GPIO149
#ifndef BALL_AJ17_IS_GPIO
#define BALL_AJ17_IS_GPIO 0
#endif 
#ifndef PAD_PCM_WAIT_N_IS_GPIO
#define PAD_PCM_WAIT_N_IS_GPIO BALL_AJ17_IS_GPIO
#endif 

#define BALL_AG20 PAD_PCM_RESET
#define PAD_PCM_RESET 149
#define GPIO_PAD_149 GPIO148
#ifndef BALL_AG20_IS_GPIO
#define BALL_AG20_IS_GPIO 0
#endif 
#ifndef PAD_PCM_RESET_IS_GPIO
#define PAD_PCM_RESET_IS_GPIO BALL_AG20_IS_GPIO
#endif 

#define BALL_AG17 PAD_PCM_WE_N
#define PAD_PCM_WE_N 151
#define GPIO_PAD_151 GPIO150
#ifndef BALL_AG17_IS_GPIO
#define BALL_AG17_IS_GPIO 0
#endif 
#ifndef PAD_PCM_WE_N_IS_GPIO
#define PAD_PCM_WE_N_IS_GPIO BALL_AG17_IS_GPIO
#endif 

#define BALL_AH15 PAD_PCM_IOWR_N
#define PAD_PCM_IOWR_N 145
#define GPIO_PAD_145 GPIO144
#ifndef BALL_AH15_IS_GPIO
#define BALL_AH15_IS_GPIO 0
#endif 
#ifndef PAD_PCM_IOWR_N_IS_GPIO
#define PAD_PCM_IOWR_N_IS_GPIO BALL_AH15_IS_GPIO
#endif 

#define BALL_AH13 PAD_PCM_CE_N
#define PAD_PCM_CE_N 135
#define GPIO_PAD_135 GPIO134
#ifndef BALL_AH13_IS_GPIO
#define BALL_AH13_IS_GPIO 0
#endif 
#ifndef PAD_PCM_CE_N_IS_GPIO
#define PAD_PCM_CE_N_IS_GPIO BALL_AH13_IS_GPIO
#endif 

#define BALL_AG14 PAD_PCM_IORD_N
#define PAD_PCM_IORD_N 144
#define GPIO_PAD_144 GPIO143
#ifndef BALL_AG14_IS_GPIO
#define BALL_AG14_IS_GPIO 0
#endif 
#ifndef PAD_PCM_IORD_N_IS_GPIO
#define PAD_PCM_IORD_N_IS_GPIO BALL_AG14_IS_GPIO
#endif 

#define BALL_AG15 PAD_PCM_OE_N
#define PAD_PCM_OE_N 147
#define GPIO_PAD_147 GPIO146
#ifndef BALL_AG15_IS_GPIO
#define BALL_AG15_IS_GPIO 0
#endif 
#ifndef PAD_PCM_OE_N_IS_GPIO
#define PAD_PCM_OE_N_IS_GPIO BALL_AG15_IS_GPIO
#endif 

#define BALL_AG18 PAD_PCM_IRQA_N
#define PAD_PCM_IRQA_N 146
#define GPIO_PAD_146 GPIO145
#ifndef BALL_AG18_IS_GPIO
#define BALL_AG18_IS_GPIO 0
#endif 
#ifndef PAD_PCM_IRQA_N_IS_GPIO
#define PAD_PCM_IRQA_N_IS_GPIO BALL_AG18_IS_GPIO
#endif 

#define BALL_AG11 PAD_PCM_CD_N
#define PAD_PCM_CD_N 134
#define GPIO_PAD_134 GPIO133
#ifndef BALL_AG11_IS_GPIO
#define BALL_AG11_IS_GPIO 0
#endif 
#ifndef PAD_PCM_CD_N_IS_GPIO
#define PAD_PCM_CD_N_IS_GPIO BALL_AG11_IS_GPIO
#endif 

#define BALL_AJ20 PAD_PCM_REG_N
#define PAD_PCM_REG_N 148
#define GPIO_PAD_148 GPIO147
#ifndef BALL_AJ20_IS_GPIO
#define BALL_AJ20_IS_GPIO 0
#endif 
#ifndef PAD_PCM_REG_N_IS_GPIO
#define PAD_PCM_REG_N_IS_GPIO BALL_AJ20_IS_GPIO
#endif 

#define BALL_AG16 PAD_PCM_A14
#define PAD_PCM_A14 133
#define GPIO_PAD_133 GPIO132
#ifndef BALL_AG16_IS_GPIO
#define BALL_AG16_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A14_IS_GPIO
#define PAD_PCM_A14_IS_GPIO BALL_AG16_IS_GPIO
#endif 

#define BALL_AH16 PAD_PCM_A13
#define PAD_PCM_A13 132
#define GPIO_PAD_132 GPIO131
#ifndef BALL_AH16_IS_GPIO
#define BALL_AH16_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A13_IS_GPIO
#define PAD_PCM_A13_IS_GPIO BALL_AH16_IS_GPIO
#endif 

#define BALL_AH18 PAD_PCM_A12
#define PAD_PCM_A12 131
#define GPIO_PAD_131 GPIO130
#ifndef BALL_AH18_IS_GPIO
#define BALL_AH18_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A12_IS_GPIO
#define PAD_PCM_A12_IS_GPIO BALL_AH18_IS_GPIO
#endif 

#define BALL_AJ14 PAD_PCM_A11
#define PAD_PCM_A11 130
#define GPIO_PAD_130 GPIO129
#ifndef BALL_AJ14_IS_GPIO
#define BALL_AJ14_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A11_IS_GPIO
#define PAD_PCM_A11_IS_GPIO BALL_AJ14_IS_GPIO
#endif 

#define BALL_AG13 PAD_PCM_A10
#define PAD_PCM_A10 129
#define GPIO_PAD_129 GPIO128
#ifndef BALL_AG13_IS_GPIO
#define BALL_AG13_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A10_IS_GPIO
#define PAD_PCM_A10_IS_GPIO BALL_AG13_IS_GPIO
#endif 

#define BALL_AJ15 PAD_PCM_A9
#define PAD_PCM_A9 128
#define GPIO_PAD_128 GPIO127
#ifndef BALL_AJ15_IS_GPIO
#define BALL_AJ15_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A9_IS_GPIO
#define PAD_PCM_A9_IS_GPIO BALL_AJ15_IS_GPIO
#endif 

#define BALL_AJ16 PAD_PCM_A8
#define PAD_PCM_A8 127
#define GPIO_PAD_127 GPIO126
#ifndef BALL_AJ16_IS_GPIO
#define BALL_AJ16_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A8_IS_GPIO
#define PAD_PCM_A8_IS_GPIO BALL_AJ16_IS_GPIO
#endif 

#define BALL_AJ18 PAD_PCM_A7
#define PAD_PCM_A7 126
#define GPIO_PAD_126 GPIO125
#ifndef BALL_AJ18_IS_GPIO
#define BALL_AJ18_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A7_IS_GPIO
#define PAD_PCM_A7_IS_GPIO BALL_AJ18_IS_GPIO
#endif 

#define BALL_AJ19 PAD_PCM_A6
#define PAD_PCM_A6 125
#define GPIO_PAD_125 GPIO124
#ifndef BALL_AJ19_IS_GPIO
#define BALL_AJ19_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A6_IS_GPIO
#define PAD_PCM_A6_IS_GPIO BALL_AJ19_IS_GPIO
#endif 

#define BALL_AH19 PAD_PCM_A5
#define PAD_PCM_A5 124
#define GPIO_PAD_124 GPIO123
#ifndef BALL_AH19_IS_GPIO
#define BALL_AH19_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A5_IS_GPIO
#define PAD_PCM_A5_IS_GPIO BALL_AH19_IS_GPIO
#endif 

#define BALL_AG19 PAD_PCM_A4
#define PAD_PCM_A4 123
#define GPIO_PAD_123 GPIO122
#ifndef BALL_AG19_IS_GPIO
#define BALL_AG19_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A4_IS_GPIO
#define PAD_PCM_A4_IS_GPIO BALL_AG19_IS_GPIO
#endif 

#define BALL_AH20 PAD_PCM_A3
#define PAD_PCM_A3 122
#define GPIO_PAD_122 GPIO121
#ifndef BALL_AH20_IS_GPIO
#define BALL_AH20_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A3_IS_GPIO
#define PAD_PCM_A3_IS_GPIO BALL_AH20_IS_GPIO
#endif 

#define BALL_AG21 PAD_PCM_A2
#define PAD_PCM_A2 121
#define GPIO_PAD_121 GPIO120
#ifndef BALL_AG21_IS_GPIO
#define BALL_AG21_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A2_IS_GPIO
#define PAD_PCM_A2_IS_GPIO BALL_AG21_IS_GPIO
#endif 

#define BALL_AJ21 PAD_PCM_A1
#define PAD_PCM_A1 120
#define GPIO_PAD_120 GPIO119
#ifndef BALL_AJ21_IS_GPIO
#define BALL_AJ21_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A1_IS_GPIO
#define PAD_PCM_A1_IS_GPIO BALL_AJ21_IS_GPIO
#endif 

#define BALL_AH21 PAD_PCM_A0
#define PAD_PCM_A0 119
#define GPIO_PAD_119 GPIO118
#ifndef BALL_AH21_IS_GPIO
#define BALL_AH21_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A0_IS_GPIO
#define PAD_PCM_A0_IS_GPIO BALL_AH21_IS_GPIO
#endif 

#define PAD_DIM0 9999
#ifndef PAD_DIM0_IS_GPIO
#define PAD_DIM0_IS_GPIO 0
#endif 

#define PAD_DIM1 9999
#ifndef PAD_DIM1_IS_GPIO
#define PAD_DIM1_IS_GPIO 0
#endif 

#define PAD_DIM2 9999
#ifndef PAD_DIM2_IS_GPIO
#define PAD_DIM2_IS_GPIO 0
#endif 

#define PAD_DIM3 9999
#ifndef PAD_DIM3_IS_GPIO
#define PAD_DIM3_IS_GPIO 0
#endif 

#define BALL_E8 PAD_DDCR_CK
#define PAD_DDCR_CK 63
#define GPIO_PAD_63 GPIO62
#ifndef BALL_E8_IS_GPIO
#define BALL_E8_IS_GPIO 0
#endif 
#ifndef PAD_DDCR_CK_IS_GPIO
#define PAD_DDCR_CK_IS_GPIO BALL_E8_IS_GPIO
#endif 

#define BALL_F8 PAD_DDCR_DA
#define PAD_DDCR_DA 64
#define GPIO_PAD_64 GPIO63
#ifndef BALL_F8_IS_GPIO
#define BALL_F8_IS_GPIO 0
#endif 
#ifndef PAD_DDCR_DA_IS_GPIO
#define PAD_DDCR_DA_IS_GPIO BALL_F8_IS_GPIO
#endif 

#define BALL_F7 PAD_PWM4
#define PAD_PWM4 156
#define GPIO_PAD_156 GPIO155
#ifndef BALL_F7_IS_GPIO
#define BALL_F7_IS_GPIO 0
#endif 
#ifndef PAD_PWM4_IS_GPIO
#define PAD_PWM4_IS_GPIO BALL_F7_IS_GPIO
#endif 

#define BALL_D7 PAD_I2S_OUT_SD
#define PAD_I2S_OUT_SD 109
#define GPIO_PAD_109 GPIO108
#ifndef BALL_D7_IS_GPIO
#define BALL_D7_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_SD_IS_GPIO
#define PAD_I2S_OUT_SD_IS_GPIO BALL_D7_IS_GPIO
#endif 

#define BALL_E7 PAD_I2S_OUT_SD1
#define PAD_I2S_OUT_SD1 110
#define GPIO_PAD_110 GPIO109
#ifndef BALL_E7_IS_GPIO
#define BALL_E7_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_SD1_IS_GPIO
#define PAD_I2S_OUT_SD1_IS_GPIO BALL_E7_IS_GPIO
#endif 

#define BALL_D6 PAD_I2S_OUT_SD2
#define PAD_I2S_OUT_SD2 111
#define GPIO_PAD_111 GPIO110
#ifndef BALL_D6_IS_GPIO
#define BALL_D6_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_SD2_IS_GPIO
#define PAD_I2S_OUT_SD2_IS_GPIO BALL_D6_IS_GPIO
#endif 

#define BALL_E6 PAD_I2S_OUT_SD3
#define PAD_I2S_OUT_SD3 112
#define GPIO_PAD_112 GPIO111
#ifndef BALL_E6_IS_GPIO
#define BALL_E6_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_SD3_IS_GPIO
#define PAD_I2S_OUT_SD3_IS_GPIO BALL_E6_IS_GPIO
#endif 

#define BALL_D5 PAD_I2S_OUT_BCK
#define PAD_I2S_OUT_BCK 107
#define GPIO_PAD_107 GPIO106
#ifndef BALL_D5_IS_GPIO
#define BALL_D5_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_BCK_IS_GPIO
#define PAD_I2S_OUT_BCK_IS_GPIO BALL_D5_IS_GPIO
#endif 

#define BALL_E5 PAD_I2S_OUT_MCK
#define PAD_I2S_OUT_MCK 108
#define GPIO_PAD_108 GPIO107
#ifndef BALL_E5_IS_GPIO
#define BALL_E5_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_MCK_IS_GPIO
#define PAD_I2S_OUT_MCK_IS_GPIO BALL_E5_IS_GPIO
#endif 

#define BALL_D4 PAD_I2S_OUT_WS
#define PAD_I2S_OUT_WS 113
#define GPIO_PAD_113 GPIO112
#ifndef BALL_D4_IS_GPIO
#define BALL_D4_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_WS_IS_GPIO
#define PAD_I2S_OUT_WS_IS_GPIO BALL_D4_IS_GPIO
#endif 

#define PAD_VSYNC_Like 9999
#ifndef PAD_VSYNC_Like_IS_GPIO
#define PAD_VSYNC_Like_IS_GPIO 0
#endif 

#define PAD_GPIO5 9999
#ifndef PAD_GPIO5_IS_GPIO
#define PAD_GPIO5_IS_GPIO 0
#endif 

#define BALL_H6 PAD_GPIO4
#define PAD_GPIO4 73
#define GPIO_PAD_73 GPIO72
#ifndef BALL_H6_IS_GPIO
#define BALL_H6_IS_GPIO 0
#endif 
#ifndef PAD_GPIO4_IS_GPIO
#define PAD_GPIO4_IS_GPIO BALL_H6_IS_GPIO
#endif 

#define BALL_G6 PAD_GPIO3
#define PAD_GPIO3 72
#define GPIO_PAD_72 GPIO71
#ifndef BALL_G6_IS_GPIO
#define BALL_G6_IS_GPIO 0
#endif 
#ifndef PAD_GPIO3_IS_GPIO
#define PAD_GPIO3_IS_GPIO BALL_G6_IS_GPIO
#endif 

#define BALL_G5 PAD_GPIO2
#define PAD_GPIO2 71
#define GPIO_PAD_71 GPIO70
#ifndef BALL_G5_IS_GPIO
#define BALL_G5_IS_GPIO 0
#endif 
#ifndef PAD_GPIO2_IS_GPIO
#define PAD_GPIO2_IS_GPIO BALL_G5_IS_GPIO
#endif 

#define BALL_F6 PAD_SPDIF_IN
#define PAD_SPDIF_IN 157
#define GPIO_PAD_157 GPIO156
#ifndef BALL_F6_IS_GPIO
#define BALL_F6_IS_GPIO 0
#endif 
#ifndef PAD_SPDIF_IN_IS_GPIO
#define PAD_SPDIF_IN_IS_GPIO BALL_F6_IS_GPIO
#endif 

#define PAD_GPIO16 9999
#ifndef PAD_GPIO16_IS_GPIO
#define PAD_GPIO16_IS_GPIO 0
#endif 

#define BALL_F5 PAD_I2S_IN_BCK
#define PAD_I2S_IN_BCK 104
#define GPIO_PAD_104 GPIO103
#ifndef BALL_F5_IS_GPIO
#define BALL_F5_IS_GPIO 0
#endif 
#ifndef PAD_I2S_IN_BCK_IS_GPIO
#define PAD_I2S_IN_BCK_IS_GPIO BALL_F5_IS_GPIO
#endif 

#define BALL_E4 PAD_I2S_IN_SD
#define PAD_I2S_IN_SD 105
#define GPIO_PAD_105 GPIO104
#ifndef BALL_E4_IS_GPIO
#define BALL_E4_IS_GPIO 0
#endif 
#ifndef PAD_I2S_IN_SD_IS_GPIO
#define PAD_I2S_IN_SD_IS_GPIO BALL_E4_IS_GPIO
#endif 

#define BALL_F4 PAD_I2S_IN_WS
#define PAD_I2S_IN_WS 106
#define GPIO_PAD_106 GPIO105
#ifndef BALL_F4_IS_GPIO
#define BALL_F4_IS_GPIO 0
#endif 
#ifndef PAD_I2S_IN_WS_IS_GPIO
#define PAD_I2S_IN_WS_IS_GPIO BALL_F4_IS_GPIO
#endif 


// PADS group name to index
#define PADS_PCMCONFIG_MODE1        1223
#define PADS_PCMCONFIG_MODE2        1224
#define PADS_PCMCONFIG1_MODE1       1225
#define PADS_PCMCONFIG1_MODE2       1226
#define PADS_PCMCONFIG1_MODE3       1227
#define PADS_PCM2CONFIG_MODE1       1228
#define PADS_PCM2CONFIG_MODE2       1229
#define PADS_PCM2CONFIG_MODE3       1230
#define PADS_PCM2CONFIG1_MODE1      1231
#define PADS_PCM2CONFIG1_MODE2      1232
#define PADS_ET_MODE1               1233
#define PADS_ET_MODE2               1234
#define PADS_DDCR                   1235
#define PADS_DDCR2                  1236
#define PADS_PCM                    1237

// chip capbilities
#define CHIP_HAS_BT656_IN           0
#define CHIP_HAS_TS0                1
#define CHIP_HAS_TS1                0
#define CHIP_HAS_LVDS_10BIT_X2      1
#define CHIP_HAS_LVDS_8BIT_X2       1
#define CHIP_HAS_LVDS_8BIT_X1       1
#define CHIP_HAS_CIMAX              0
#define CHIP_HAS_USB_P0             1
#define CHIP_HAS_USB_P1             1
#define CHIP_HAS_USBVBUS0           0
#define CHIP_HAS_USBVBUS1           0
#define CHIP_HAS_UART1_MODE1        1
#define CHIP_HAS_UART1_MODE2        1
#define CHIP_HAS_UART1_MODE3        1
#define CHIP_HAS_PCMCIA1            0
#define CHIP_HAS_PCMCIA2            0
#define CHIP_HAS_PCMCIA             0
#define CHIP_HAS_UART2_MODE1        1
#define CHIP_HAS_UART2_MODE2        1
#define CHIP_HAS_UART2_MODE3        1
#define CHIP_HAS_RGB_A              1
#define CHIP_HAS_RGB_B              1
#define CHIP_HAS_RGB_C              1
#define CHIP_HAS_HDMI_A             1
#define CHIP_HAS_HDMI_B             1
#define CHIP_HAS_HDMI_C             1
#define CHIP_HAS_SPI_CZ1            1
#define CHIP_HAS_SPI_CZ2            0
#define CHIP_HAS_SPI_CZ3            0
#define CHIP_HAS_DDCR               1
#define CHIP_HAS_DDCR2              1
#define CHIP_HAS_TCON               1
#define CHIP_HAS_ET_MODE0_MII       1
#define CHIP_HAS_ET_MODE0_RMII      1
#define CHIP_HAS_ET_MODE1_MII       1
#define CHIP_HAS_ET_MODE1_RMII      1
#define CHIP_HAS_ET_MODE2_MII       1
#define CHIP_HAS_ET_MODE2_RMII      1
#define CHIP_HAS_I2S_IN             0
#define CHIP_HAS_I2S_OUT            0
#define CHIP_HAS_SPDIF_IN           0
#define CHIP_HAS_SPDIF_OUT          0
#define CHIP_HAS_DDR_A_CMD          1
#define CHIP_HAS_DDR_A_DATA         1
#define CHIP_HAS_DDR_B_CMD          1
#define CHIP_HAS_DDR_B_DATA         1
#define CHIP_USE_PCM_CDN_IN_PCM2    0
#define CHIP_USE_I2S_IN_IN_PCM      0
#define CHIP_USE_I2S_OUT_IN_PCM     0
#define CHIP_USE_SPDIF_IN_IN_PCM    0
#define CHIP_USE_SPDIF_OUT_IN_PCM   0
#define CHIP_USE_IIC_IN_DDCR2       0
#define CHIP_USE_PWM2_IN_GPIO14     0
#define CHIP_USE_PWM3_IN_GPIO15     0

// chip additional information
#define CHIP_FAMILY_TYPE            CHIP_FAMILY_MARCUS

#endif /* _MSD96AWD_H_*/
