/* SPDX-License-Identifier: GPL-2.0-only OR BSD-3-Clause */
/******************************************************************************
 *
 * This file is provided under a dual license.  When you use or
 * distribute this software, you may choose to be licensed under
 * version 2 of the GNU General Public License ("GPLv2 License")
 * or BSD License.
 *
 * GPLv2 License
 *
 * Copyright(C) 2019 MediaTek Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of version 2 of the GNU General Public License as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See http://www.gnu.org/licenses/gpl-2.0.html for more details.
 *
 * BSD LICENSE
 *
 * Copyright(C) 2019 MediaTek Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *****************************************************************************/

// This file is generated by script, please do not edit it directly
#ifndef _MSD91P1TMx_H_
#define _MSD91P1TMx_H_

#define PAD_NC 9999
#define PAD_GND 0

#define BALL_L6 PAD_DDCDA_CK
#define PAD_DDCDA_CK 37
#define GPIO_PAD_37 GPIO36
#ifndef BALL_L6_IS_GPIO
#define BALL_L6_IS_GPIO 0
#endif
#ifndef PAD_DDCDA_CK_IS_GPIO
#define PAD_DDCDA_CK_IS_GPIO BALL_L6_IS_GPIO
#endif

#define BALL_M5 PAD_DDCDA_DA
#define PAD_DDCDA_DA 38
#define GPIO_PAD_38 GPIO37
#ifndef BALL_M5_IS_GPIO
#define BALL_M5_IS_GPIO 0
#endif
#ifndef PAD_DDCDA_DA_IS_GPIO
#define PAD_DDCDA_DA_IS_GPIO BALL_M5_IS_GPIO
#endif

#define BALL_AA6 PAD_HOTPLUGB
#define PAD_HOTPLUGB 30
#define GPIO_PAD_30 GPIO29
#ifndef BALL_AA6_IS_GPIO
#define BALL_AA6_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGB_IS_GPIO
#define PAD_HOTPLUGB_IS_GPIO BALL_AA6_IS_GPIO
#endif

#define BALL_K5 PAD_DDCDB_CK
#define PAD_DDCDB_CK 39
#define GPIO_PAD_39 GPIO38
#ifndef BALL_K5_IS_GPIO
#define BALL_K5_IS_GPIO 0
#endif
#ifndef PAD_DDCDB_CK_IS_GPIO
#define PAD_DDCDB_CK_IS_GPIO BALL_K5_IS_GPIO
#endif

#define PAD_HOTPLUGC 9999
#ifndef PAD_HOTPLUGC_IS_GPIO
#define PAD_HOTPLUGC_IS_GPIO 0
#endif

#define BALL_L5 PAD_DDCDB_DA
#define PAD_DDCDB_DA 40
#define GPIO_PAD_40 GPIO39
#ifndef BALL_L5_IS_GPIO
#define BALL_L5_IS_GPIO 0
#endif
#ifndef PAD_DDCDB_DA_IS_GPIO
#define PAD_DDCDB_DA_IS_GPIO BALL_L5_IS_GPIO
#endif

#define BALL_AC6 PAD_HOTPLUGD
#define PAD_HOTPLUGD 32
#define GPIO_PAD_32 GPIO31
#ifndef BALL_AC6_IS_GPIO
#define BALL_AC6_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGD_IS_GPIO
#define PAD_HOTPLUGD_IS_GPIO BALL_AC6_IS_GPIO
#endif

#define PAD_DDCDC_CK 9999
#ifndef PAD_DDCDC_CK_IS_GPIO
#define PAD_DDCDC_CK_IS_GPIO 0
#endif

#define BALL_N6 PAD_HOTPLUGA_HDMI20_5V
#define PAD_HOTPLUGA_HDMI20_5V 33
#define GPIO_PAD_33 GPIO32
#ifndef BALL_N6_IS_GPIO
#define BALL_N6_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGA_HDMI20_5V_IS_GPIO
#define PAD_HOTPLUGA_HDMI20_5V_IS_GPIO BALL_N6_IS_GPIO
#endif

#define PAD_DDCDC_DA 9999
#ifndef PAD_DDCDC_DA_IS_GPIO
#define PAD_DDCDC_DA_IS_GPIO 0
#endif

#define BALL_N7 PAD_HOTPLUGB_HDMI20_5V
#define PAD_HOTPLUGB_HDMI20_5V 34
#define GPIO_PAD_34 GPIO33
#ifndef BALL_N7_IS_GPIO
#define BALL_N7_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGB_HDMI20_5V_IS_GPIO
#define PAD_HOTPLUGB_HDMI20_5V_IS_GPIO BALL_N7_IS_GPIO
#endif

#define BALL_AC7 PAD_DDCDD_CK
#define PAD_DDCDD_CK 43
#define GPIO_PAD_43 GPIO42
#ifndef BALL_AC7_IS_GPIO
#define BALL_AC7_IS_GPIO 0
#endif
#ifndef PAD_DDCDD_CK_IS_GPIO
#define PAD_DDCDD_CK_IS_GPIO BALL_AC7_IS_GPIO
#endif

#define PAD_HOTPLUGC_HDMI20_5V 9999
#ifndef PAD_HOTPLUGC_HDMI20_5V_IS_GPIO
#define PAD_HOTPLUGC_HDMI20_5V_IS_GPIO 0
#endif

#define BALL_AB7 PAD_DDCDD_DA
#define PAD_DDCDD_DA 44
#define GPIO_PAD_44 GPIO43
#ifndef BALL_AB7_IS_GPIO
#define BALL_AB7_IS_GPIO 0
#endif
#ifndef PAD_DDCDD_DA_IS_GPIO
#define PAD_DDCDD_DA_IS_GPIO BALL_AB7_IS_GPIO
#endif

#define BALL_M6 PAD_HOTPLUGD_HDMI20_5V
#define PAD_HOTPLUGD_HDMI20_5V 36
#define GPIO_PAD_36 GPIO35
#ifndef BALL_M6_IS_GPIO
#define BALL_M6_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGD_HDMI20_5V_IS_GPIO
#define PAD_HOTPLUGD_HDMI20_5V_IS_GPIO BALL_M6_IS_GPIO
#endif

#define BALL_J5 PAD_DDCA_CK
#define PAD_DDCA_CK 9
#define GPIO_PAD_9 GPIO8
#ifndef BALL_J5_IS_GPIO
#define BALL_J5_IS_GPIO 0
#endif
#ifndef PAD_DDCA_CK_IS_GPIO
#define PAD_DDCA_CK_IS_GPIO BALL_J5_IS_GPIO
#endif

#define BALL_AB6 PAD_GPIO_PM0
#define PAD_GPIO_PM0 11
#define GPIO_PAD_11 GPIO10
#ifndef BALL_AB6_IS_GPIO
#define BALL_AB6_IS_GPIO 0
#endif
#ifndef PAD_GPIO_PM0_IS_GPIO
#define PAD_GPIO_PM0_IS_GPIO BALL_AB6_IS_GPIO
#endif

#define BALL_J4 PAD_DDCA_DA
#define PAD_DDCA_DA 10
#define GPIO_PAD_10 GPIO9
#ifndef BALL_J4_IS_GPIO
#define BALL_J4_IS_GPIO 0
#endif
#ifndef PAD_DDCA_DA_IS_GPIO
#define PAD_DDCA_DA_IS_GPIO BALL_J4_IS_GPIO
#endif

#define BALL_N5 PAD_GPIO_PM1
#define PAD_GPIO_PM1 12
#define GPIO_PAD_12 GPIO11
#ifndef BALL_N5_IS_GPIO
#define BALL_N5_IS_GPIO 0
#endif
#ifndef PAD_GPIO_PM1_IS_GPIO
#define PAD_GPIO_PM1_IS_GPIO BALL_N5_IS_GPIO
#endif

#define BALL_C1 PAD_PM_SPI_DI
#define PAD_PM_SPI_DI 3
#define GPIO_PAD_3 GPIO2
#ifndef BALL_C1_IS_GPIO
#define BALL_C1_IS_GPIO 0
#endif
#ifndef PAD_PM_SPI_DI_IS_GPIO
#define PAD_PM_SPI_DI_IS_GPIO BALL_C1_IS_GPIO
#endif

#define PAD_GPIO_PM2 9999
#ifndef PAD_GPIO_PM2_IS_GPIO
#define PAD_GPIO_PM2_IS_GPIO 0
#endif

#define BALL_D2 PAD_PM_SPI_CZ
#define PAD_PM_SPI_CZ 1
#define GPIO_PAD_1 GPIO0
#ifndef BALL_D2_IS_GPIO
#define BALL_D2_IS_GPIO 0
#endif
#ifndef PAD_PM_SPI_CZ_IS_GPIO
#define PAD_PM_SPI_CZ_IS_GPIO BALL_D2_IS_GPIO
#endif

#define PAD_GPIO_PM3 9999
#ifndef PAD_GPIO_PM3_IS_GPIO
#define PAD_GPIO_PM3_IS_GPIO 0
#endif

#define BALL_D3 PAD_PM_SPI_DO
#define PAD_PM_SPI_DO 4
#define GPIO_PAD_4 GPIO3
#ifndef BALL_D3_IS_GPIO
#define BALL_D3_IS_GPIO 0
#endif
#ifndef PAD_PM_SPI_DO_IS_GPIO
#define PAD_PM_SPI_DO_IS_GPIO BALL_D3_IS_GPIO
#endif

#define BALL_AC5 PAD_GPIO_PM4
#define PAD_GPIO_PM4 15
#define GPIO_PAD_15 GPIO14
#ifndef BALL_AC5_IS_GPIO
#define BALL_AC5_IS_GPIO 0
#endif
#ifndef PAD_GPIO_PM4_IS_GPIO
#define PAD_GPIO_PM4_IS_GPIO BALL_AC5_IS_GPIO
#endif

#define BALL_E3 PAD_PM_SPI_CK
#define PAD_PM_SPI_CK 2
#define GPIO_PAD_2 GPIO1
#ifndef BALL_E3_IS_GPIO
#define BALL_E3_IS_GPIO 0
#endif
#ifndef PAD_PM_SPI_CK_IS_GPIO
#define PAD_PM_SPI_CK_IS_GPIO BALL_E3_IS_GPIO
#endif

#define BALL_N4 PAD_GPIO_PM5
#define PAD_GPIO_PM5 16
#define GPIO_PAD_16 GPIO15
#ifndef BALL_N4_IS_GPIO
#define BALL_N4_IS_GPIO 0
#endif
#ifndef PAD_GPIO_PM5_IS_GPIO
#define PAD_GPIO_PM5_IS_GPIO BALL_N4_IS_GPIO
#endif

#define BALL_AA8 PAD_PWM_PM
#define PAD_PWM_PM 8
#define GPIO_PAD_8 GPIO7
#ifndef BALL_AA8_IS_GPIO
#define BALL_AA8_IS_GPIO 0
#endif
#ifndef PAD_PWM_PM_IS_GPIO
#define PAD_PWM_PM_IS_GPIO BALL_AA8_IS_GPIO
#endif

#define BALL_Y3 PAD_GPIO_PM6
#define PAD_GPIO_PM6 17
#define GPIO_PAD_17 GPIO16
#ifndef BALL_Y3_IS_GPIO
#define BALL_Y3_IS_GPIO 0
#endif
#ifndef PAD_GPIO_PM6_IS_GPIO
#define PAD_GPIO_PM6_IS_GPIO BALL_Y3_IS_GPIO
#endif

#define BALL_F3 PAD_IRIN
#define PAD_IRIN 5
#define GPIO_PAD_5 GPIO4
#ifndef BALL_F3_IS_GPIO
#define BALL_F3_IS_GPIO 0
#endif
#ifndef PAD_IRIN_IS_GPIO
#define PAD_IRIN_IS_GPIO BALL_F3_IS_GPIO
#endif

#define PAD_GPIO_PM7 9999
#ifndef PAD_GPIO_PM7_IS_GPIO
#define PAD_GPIO_PM7_IS_GPIO 0
#endif

#define BALL_Y5 PAD_CEC0
#define PAD_CEC0 6
#define GPIO_PAD_6 GPIO5
#ifndef BALL_Y5_IS_GPIO
#define BALL_Y5_IS_GPIO 0
#endif
#ifndef PAD_CEC0_IS_GPIO
#define PAD_CEC0_IS_GPIO BALL_Y5_IS_GPIO
#endif

#define BALL_Y2 PAD_GPIO_PM8
#define PAD_GPIO_PM8 19
#define GPIO_PAD_19 GPIO18
#ifndef BALL_Y2_IS_GPIO
#define BALL_Y2_IS_GPIO 0
#endif
#ifndef PAD_GPIO_PM8_IS_GPIO
#define PAD_GPIO_PM8_IS_GPIO BALL_Y2_IS_GPIO
#endif

#define PAD_AV_LNK 9999
#ifndef PAD_AV_LNK_IS_GPIO
#define PAD_AV_LNK_IS_GPIO 0
#endif

#define PAD_GPIO_PM9 9999
#ifndef PAD_GPIO_PM9_IS_GPIO
#define PAD_GPIO_PM9_IS_GPIO 0
#endif

#define PAD_WOL_INT_OUT 9999
#ifndef PAD_WOL_INT_OUT_IS_GPIO
#define PAD_WOL_INT_OUT_IS_GPIO 0
#endif

#define PAD_GPIO_PM10 9999
#ifndef PAD_GPIO_PM10_IS_GPIO
#define PAD_GPIO_PM10_IS_GPIO 0
#endif

#define BALL_P4 PAD_LED0
#define PAD_LED0 27
#define GPIO_PAD_27 GPIO26
#ifndef BALL_P4_IS_GPIO
#define BALL_P4_IS_GPIO 0
#endif
#ifndef PAD_LED0_IS_GPIO
#define PAD_LED0_IS_GPIO BALL_P4_IS_GPIO
#endif

#define PAD_GPIO_PM11 9999
#ifndef PAD_GPIO_PM11_IS_GPIO
#define PAD_GPIO_PM11_IS_GPIO 0
#endif

#define BALL_P3 PAD_LED1
#define PAD_LED1 28
#define GPIO_PAD_28 GPIO27
#ifndef BALL_P3_IS_GPIO
#define BALL_P3_IS_GPIO 0
#endif
#ifndef PAD_LED1_IS_GPIO
#define PAD_LED1_IS_GPIO BALL_P3_IS_GPIO
#endif

#define PAD_GPIO_PM12 9999
#ifndef PAD_GPIO_PM12_IS_GPIO
#define PAD_GPIO_PM12_IS_GPIO 0
#endif

#define BALL_AA5 PAD_VID0
#define PAD_VID0 50
#define GPIO_PAD_50 GPIO49
#ifndef BALL_AA5_IS_GPIO
#define BALL_AA5_IS_GPIO 0
#endif
#ifndef PAD_VID0_IS_GPIO
#define PAD_VID0_IS_GPIO BALL_AA5_IS_GPIO
#endif

#define PAD_GPIO_PM13 9999
#ifndef PAD_GPIO_PM13_IS_GPIO
#define PAD_GPIO_PM13_IS_GPIO 0
#endif

#define PAD_VID1 9999
#ifndef PAD_VID1_IS_GPIO
#define PAD_VID1_IS_GPIO 0
#endif

#define PAD_GPIO_PM14 9999
#ifndef PAD_GPIO_PM14_IS_GPIO
#define PAD_GPIO_PM14_IS_GPIO 0
#endif

#define PAD_VID2 9999
#ifndef PAD_VID2_IS_GPIO
#define PAD_VID2_IS_GPIO 0
#endif

#define PAD_GPIO_PM15 9999
#ifndef PAD_GPIO_PM15_IS_GPIO
#define PAD_GPIO_PM15_IS_GPIO 0
#endif

#define PAD_VID3 9999
#ifndef PAD_VID3_IS_GPIO
#define PAD_VID3_IS_GPIO 0
#endif

#define BALL_AB4 PAD_ARC0
#define PAD_ARC0 55
#define GPIO_PAD_55 GPIO54
#ifndef BALL_AB4_IS_GPIO
#define BALL_AB4_IS_GPIO 0
#endif
#ifndef PAD_ARC0_IS_GPIO
#define PAD_ARC0_IS_GPIO BALL_AB4_IS_GPIO
#endif

#define PAD_GPIO8 9999
#ifndef PAD_GPIO8_IS_GPIO
#define PAD_GPIO8_IS_GPIO 0
#endif

#define PAD_GPIO9 9999
#ifndef PAD_GPIO9_IS_GPIO
#define PAD_GPIO9_IS_GPIO 0
#endif

#define PAD_GPIO10 9999
#ifndef PAD_GPIO10_IS_GPIO
#define PAD_GPIO10_IS_GPIO 0
#endif

#define PAD_GPIO11 9999
#ifndef PAD_GPIO11_IS_GPIO
#define PAD_GPIO11_IS_GPIO 0
#endif

#define PAD_GPIO12 9999
#ifndef PAD_GPIO12_IS_GPIO
#define PAD_GPIO12_IS_GPIO 0
#endif

#define PAD_GPIO13 9999
#ifndef PAD_GPIO13_IS_GPIO
#define PAD_GPIO13_IS_GPIO 0
#endif

#define PAD_GPIO14 9999
#ifndef PAD_GPIO14_IS_GPIO
#define PAD_GPIO14_IS_GPIO 0
#endif

#define BALL_AA4 PAD_GPIO15
#define PAD_GPIO15 73
#define GPIO_PAD_73 GPIO72
#ifndef BALL_AA4_IS_GPIO
#define BALL_AA4_IS_GPIO 0
#endif
#ifndef PAD_GPIO15_IS_GPIO
#define PAD_GPIO15_IS_GPIO BALL_AA4_IS_GPIO
#endif

#define PAD_GPIO16 9999
#ifndef PAD_GPIO16_IS_GPIO
#define PAD_GPIO16_IS_GPIO 0
#endif

#define PAD_GPIO17 9999
#ifndef PAD_GPIO17_IS_GPIO
#define PAD_GPIO17_IS_GPIO 0
#endif

#define PAD_GPIO18 9999
#ifndef PAD_GPIO18_IS_GPIO
#define PAD_GPIO18_IS_GPIO 0
#endif

#define PAD_GPIO28 9999
#ifndef PAD_GPIO28_IS_GPIO
#define PAD_GPIO28_IS_GPIO 0
#endif

#define PAD_GPIO29 9999
#ifndef PAD_GPIO29_IS_GPIO
#define PAD_GPIO29_IS_GPIO 0
#endif

#define PAD_GPIO30 9999
#ifndef PAD_GPIO30_IS_GPIO
#define PAD_GPIO30_IS_GPIO 0
#endif

#define PAD_GPIO31 9999
#ifndef PAD_GPIO31_IS_GPIO
#define PAD_GPIO31_IS_GPIO 0
#endif

#define PAD_GPIO32 9999
#ifndef PAD_GPIO32_IS_GPIO
#define PAD_GPIO32_IS_GPIO 0
#endif

#define PAD_GPIO33 9999
#ifndef PAD_GPIO33_IS_GPIO
#define PAD_GPIO33_IS_GPIO 0
#endif

#define PAD_GPIO34 9999
#ifndef PAD_GPIO34_IS_GPIO
#define PAD_GPIO34_IS_GPIO 0
#endif

#define PAD_GPIO35 9999
#ifndef PAD_GPIO35_IS_GPIO
#define PAD_GPIO35_IS_GPIO 0
#endif

#define PAD_GPIO36 9999
#ifndef PAD_GPIO36_IS_GPIO
#define PAD_GPIO36_IS_GPIO 0
#endif

#define PAD_GPIO37 9999
#ifndef PAD_GPIO37_IS_GPIO
#define PAD_GPIO37_IS_GPIO 0
#endif

#define BALL_M8 PAD_TGPIO0
#define PAD_TGPIO0 169
#define GPIO_PAD_169 GPIO168
#ifndef BALL_M8_IS_GPIO
#define BALL_M8_IS_GPIO 0
#endif
#ifndef PAD_TGPIO0_IS_GPIO
#define PAD_TGPIO0_IS_GPIO BALL_M8_IS_GPIO
#endif

#define BALL_M7 PAD_TGPIO1
#define PAD_TGPIO1 170
#define GPIO_PAD_170 GPIO169
#ifndef BALL_M7_IS_GPIO
#define BALL_M7_IS_GPIO 0
#endif
#ifndef PAD_TGPIO1_IS_GPIO
#define PAD_TGPIO1_IS_GPIO BALL_M7_IS_GPIO
#endif

#define BALL_U6 PAD_TGPIO2
#define PAD_TGPIO2 171
#define GPIO_PAD_171 GPIO170
#ifndef BALL_U6_IS_GPIO
#define BALL_U6_IS_GPIO 0
#endif
#ifndef PAD_TGPIO2_IS_GPIO
#define PAD_TGPIO2_IS_GPIO BALL_U6_IS_GPIO
#endif

#define BALL_U5 PAD_TGPIO3
#define PAD_TGPIO3 172
#define GPIO_PAD_172 GPIO171
#ifndef BALL_U5_IS_GPIO
#define BALL_U5_IS_GPIO 0
#endif
#ifndef PAD_TGPIO3_IS_GPIO
#define PAD_TGPIO3_IS_GPIO BALL_U5_IS_GPIO
#endif

#define BALL_AD13 PAD_EMMC_IO1
#define PAD_EMMC_IO1 118
#define GPIO_PAD_118 GPIO117
#ifndef BALL_AD13_IS_GPIO
#define BALL_AD13_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO1_IS_GPIO
#define PAD_EMMC_IO1_IS_GPIO BALL_AD13_IS_GPIO
#endif

#define BALL_AF9 PAD_EMMC_IO17
#define PAD_EMMC_IO17 113
#define GPIO_PAD_113 GPIO112
#ifndef BALL_AF9_IS_GPIO
#define BALL_AF9_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO17_IS_GPIO
#define PAD_EMMC_IO17_IS_GPIO BALL_AF9_IS_GPIO
#endif

#define BALL_AD12 PAD_EMMC_IO3
#define PAD_EMMC_IO3 167
#define GPIO_PAD_167 GPIO166
#ifndef BALL_AD12_IS_GPIO
#define BALL_AD12_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO3_IS_GPIO
#define PAD_EMMC_IO3_IS_GPIO BALL_AD12_IS_GPIO
#endif

#define BALL_AD11 PAD_EMMC_IO16
#define PAD_EMMC_IO16 112
#define GPIO_PAD_112 GPIO111
#ifndef BALL_AD11_IS_GPIO
#define BALL_AD11_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO16_IS_GPIO
#define PAD_EMMC_IO16_IS_GPIO BALL_AD11_IS_GPIO
#endif

#define BALL_AE14 PAD_EMMC_IO2
#define PAD_EMMC_IO2 119
#define GPIO_PAD_119 GPIO118
#ifndef BALL_AE14_IS_GPIO
#define BALL_AE14_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO2_IS_GPIO
#define PAD_EMMC_IO2_IS_GPIO BALL_AE14_IS_GPIO
#endif

#define BALL_AE11 PAD_EMMC_IO15
#define PAD_EMMC_IO15 114
#define GPIO_PAD_114 GPIO113
#ifndef BALL_AE11_IS_GPIO
#define BALL_AE11_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO15_IS_GPIO
#define PAD_EMMC_IO15_IS_GPIO BALL_AE11_IS_GPIO
#endif

#define BALL_AE13 PAD_EMMC_IO0
#define PAD_EMMC_IO0 168
#define GPIO_PAD_168 GPIO167
#ifndef BALL_AE13_IS_GPIO
#define BALL_AE13_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO0_IS_GPIO
#define PAD_EMMC_IO0_IS_GPIO BALL_AE13_IS_GPIO
#endif

#define BALL_AD10 PAD_EMMC_IO14
#define PAD_EMMC_IO14 110
#define GPIO_PAD_110 GPIO109
#ifndef BALL_AD10_IS_GPIO
#define BALL_AD10_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO14_IS_GPIO
#define PAD_EMMC_IO14_IS_GPIO BALL_AD10_IS_GPIO
#endif

#define PAD_EMMC_IO13 9999
#ifndef PAD_EMMC_IO13_IS_GPIO
#define PAD_EMMC_IO13_IS_GPIO 0
#endif

#define PAD_EMMC_IO12 9999
#ifndef PAD_EMMC_IO12_IS_GPIO
#define PAD_EMMC_IO12_IS_GPIO 0
#endif

#define BALL_AF15 PAD_EMMC_IO6
#define PAD_EMMC_IO6 121
#define GPIO_PAD_121 GPIO120
#ifndef BALL_AF15_IS_GPIO
#define BALL_AF15_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO6_IS_GPIO
#define PAD_EMMC_IO6_IS_GPIO BALL_AF15_IS_GPIO
#endif

#define BALL_AF12 PAD_EMMC_IO5
#define PAD_EMMC_IO5 122
#define GPIO_PAD_122 GPIO121
#ifndef BALL_AF12_IS_GPIO
#define BALL_AF12_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO5_IS_GPIO
#define PAD_EMMC_IO5_IS_GPIO BALL_AF12_IS_GPIO
#endif

#define BALL_AE9 PAD_EMMC_IO11
#define PAD_EMMC_IO11 115
#define GPIO_PAD_115 GPIO114
#ifndef BALL_AE9_IS_GPIO
#define BALL_AE9_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO11_IS_GPIO
#define PAD_EMMC_IO11_IS_GPIO BALL_AE9_IS_GPIO
#endif

#define BALL_AE12 PAD_EMMC_IO8
#define PAD_EMMC_IO8 116
#define GPIO_PAD_116 GPIO115
#ifndef BALL_AE12_IS_GPIO
#define BALL_AE12_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO8_IS_GPIO
#define PAD_EMMC_IO8_IS_GPIO BALL_AE12_IS_GPIO
#endif

#define BALL_AD14 PAD_EMMC_IO7
#define PAD_EMMC_IO7 120
#define GPIO_PAD_120 GPIO119
#ifndef BALL_AD14_IS_GPIO
#define BALL_AD14_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO7_IS_GPIO
#define PAD_EMMC_IO7_IS_GPIO BALL_AD14_IS_GPIO
#endif

#define BALL_AF13 PAD_EMMC_IO4
#define PAD_EMMC_IO4 166
#define GPIO_PAD_166 GPIO165
#ifndef BALL_AF13_IS_GPIO
#define BALL_AF13_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO4_IS_GPIO
#define PAD_EMMC_IO4_IS_GPIO BALL_AF13_IS_GPIO
#endif

#define BALL_AD9 PAD_EMMC_IO10
#define PAD_EMMC_IO10 111
#define GPIO_PAD_111 GPIO110
#ifndef BALL_AD9_IS_GPIO
#define BALL_AD9_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO10_IS_GPIO
#define PAD_EMMC_IO10_IS_GPIO BALL_AD9_IS_GPIO
#endif

#define BALL_AE10 PAD_EMMC_IO9
#define PAD_EMMC_IO9 108
#define GPIO_PAD_108 GPIO107
#ifndef BALL_AE10_IS_GPIO
#define BALL_AE10_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO9_IS_GPIO
#define PAD_EMMC_IO9_IS_GPIO BALL_AE10_IS_GPIO
#endif

#define BALL_AB16 PAD_TS0_CLK
#define PAD_TS0_CLK 183
#define GPIO_PAD_183 GPIO182
#ifndef BALL_AB16_IS_GPIO
#define BALL_AB16_IS_GPIO 0
#endif
#ifndef PAD_TS0_CLK_IS_GPIO
#define PAD_TS0_CLK_IS_GPIO BALL_AB16_IS_GPIO
#endif

#define BALL_AC14 PAD_TS0_SYNC
#define PAD_TS0_SYNC 182
#define GPIO_PAD_182 GPIO181
#ifndef BALL_AC14_IS_GPIO
#define BALL_AC14_IS_GPIO 0
#endif
#ifndef PAD_TS0_SYNC_IS_GPIO
#define PAD_TS0_SYNC_IS_GPIO BALL_AC14_IS_GPIO
#endif

#define BALL_AA16 PAD_TS0_VLD
#define PAD_TS0_VLD 181
#define GPIO_PAD_181 GPIO180
#ifndef BALL_AA16_IS_GPIO
#define BALL_AA16_IS_GPIO 0
#endif
#ifndef PAD_TS0_VLD_IS_GPIO
#define PAD_TS0_VLD_IS_GPIO BALL_AA16_IS_GPIO
#endif

#define BALL_AB17 PAD_TS0_D7
#define PAD_TS0_D7 180
#define GPIO_PAD_180 GPIO179
#ifndef BALL_AB17_IS_GPIO
#define BALL_AB17_IS_GPIO 0
#endif
#ifndef PAD_TS0_D7_IS_GPIO
#define PAD_TS0_D7_IS_GPIO BALL_AB17_IS_GPIO
#endif

#define BALL_AC18 PAD_TS0_D6
#define PAD_TS0_D6 179
#define GPIO_PAD_179 GPIO178
#ifndef BALL_AC18_IS_GPIO
#define BALL_AC18_IS_GPIO 0
#endif
#ifndef PAD_TS0_D6_IS_GPIO
#define PAD_TS0_D6_IS_GPIO BALL_AC18_IS_GPIO
#endif

#define BALL_AC15 PAD_TS0_D5
#define PAD_TS0_D5 178
#define GPIO_PAD_178 GPIO177
#ifndef BALL_AC15_IS_GPIO
#define BALL_AC15_IS_GPIO 0
#endif
#ifndef PAD_TS0_D5_IS_GPIO
#define PAD_TS0_D5_IS_GPIO BALL_AC15_IS_GPIO
#endif

#define BALL_AB18 PAD_TS0_D4
#define PAD_TS0_D4 177
#define GPIO_PAD_177 GPIO176
#ifndef BALL_AB18_IS_GPIO
#define BALL_AB18_IS_GPIO 0
#endif
#ifndef PAD_TS0_D4_IS_GPIO
#define PAD_TS0_D4_IS_GPIO BALL_AB18_IS_GPIO
#endif

#define BALL_AA18 PAD_TS0_D3
#define PAD_TS0_D3 176
#define GPIO_PAD_176 GPIO175
#ifndef BALL_AA18_IS_GPIO
#define BALL_AA18_IS_GPIO 0
#endif
#ifndef PAD_TS0_D3_IS_GPIO
#define PAD_TS0_D3_IS_GPIO BALL_AA18_IS_GPIO
#endif

#define BALL_AC19 PAD_TS0_D2
#define PAD_TS0_D2 175
#define GPIO_PAD_175 GPIO174
#ifndef BALL_AC19_IS_GPIO
#define BALL_AC19_IS_GPIO 0
#endif
#ifndef PAD_TS0_D2_IS_GPIO
#define PAD_TS0_D2_IS_GPIO BALL_AC19_IS_GPIO
#endif

#define BALL_AB19 PAD_TS0_D1
#define PAD_TS0_D1 174
#define GPIO_PAD_174 GPIO173
#ifndef BALL_AB19_IS_GPIO
#define BALL_AB19_IS_GPIO 0
#endif
#ifndef PAD_TS0_D1_IS_GPIO
#define PAD_TS0_D1_IS_GPIO BALL_AB19_IS_GPIO
#endif

#define BALL_AD15 PAD_TS0_D0
#define PAD_TS0_D0 173
#define GPIO_PAD_173 GPIO172
#ifndef BALL_AD15_IS_GPIO
#define BALL_AD15_IS_GPIO 0
#endif
#ifndef PAD_TS0_D0_IS_GPIO
#define PAD_TS0_D0_IS_GPIO BALL_AD15_IS_GPIO
#endif

#define BALL_AE16 PAD_PCM_WAIT_N
#define PAD_PCM_WAIT_N 149
#define GPIO_PAD_149 GPIO148
#ifndef BALL_AE16_IS_GPIO
#define BALL_AE16_IS_GPIO 0
#endif
#ifndef PAD_PCM_WAIT_N_IS_GPIO
#define PAD_PCM_WAIT_N_IS_GPIO BALL_AE16_IS_GPIO
#endif

#define BALL_AD16 PAD_PCM_RESET
#define PAD_PCM_RESET 159
#define GPIO_PAD_159 GPIO158
#ifndef BALL_AD16_IS_GPIO
#define BALL_AD16_IS_GPIO 0
#endif
#ifndef PAD_PCM_RESET_IS_GPIO
#define PAD_PCM_RESET_IS_GPIO BALL_AD16_IS_GPIO
#endif

#define BALL_AD17 PAD_PCM_IRQA_N
#define PAD_PCM_IRQA_N 144
#define GPIO_PAD_144 GPIO143
#ifndef BALL_AD17_IS_GPIO
#define BALL_AD17_IS_GPIO 0
#endif
#ifndef PAD_PCM_IRQA_N_IS_GPIO
#define PAD_PCM_IRQA_N_IS_GPIO BALL_AD17_IS_GPIO
#endif

#define BALL_AE17 PAD_PCM_WE_N
#define PAD_PCM_WE_N 143
#define GPIO_PAD_143 GPIO142
#ifndef BALL_AE17_IS_GPIO
#define BALL_AE17_IS_GPIO 0
#endif
#ifndef PAD_PCM_WE_N_IS_GPIO
#define PAD_PCM_WE_N_IS_GPIO BALL_AE17_IS_GPIO
#endif

#define BALL_Y21 PAD_PCM_IOWR_N
#define PAD_PCM_IOWR_N 139
#define GPIO_PAD_139 GPIO138
#ifndef BALL_Y21_IS_GPIO
#define BALL_Y21_IS_GPIO 0
#endif
#ifndef PAD_PCM_IOWR_N_IS_GPIO
#define PAD_PCM_IOWR_N_IS_GPIO BALL_Y21_IS_GPIO
#endif

#define BALL_AD18 PAD_PCM_IORD_N
#define PAD_PCM_IORD_N 137
#define GPIO_PAD_137 GPIO136
#ifndef BALL_AD18_IS_GPIO
#define BALL_AD18_IS_GPIO 0
#endif
#ifndef PAD_PCM_IORD_N_IS_GPIO
#define PAD_PCM_IORD_N_IS_GPIO BALL_AD18_IS_GPIO
#endif

#define BALL_AF19 PAD_PCM_OE_N
#define PAD_PCM_OE_N 135
#define GPIO_PAD_135 GPIO134
#ifndef BALL_AF19_IS_GPIO
#define BALL_AF19_IS_GPIO 0
#endif
#ifndef PAD_PCM_OE_N_IS_GPIO
#define PAD_PCM_OE_N_IS_GPIO BALL_AF19_IS_GPIO
#endif

#define BALL_AB20 PAD_PCM_CE_N
#define PAD_PCM_CE_N 133
#define GPIO_PAD_133 GPIO132
#ifndef BALL_AB20_IS_GPIO
#define BALL_AB20_IS_GPIO 0
#endif
#ifndef PAD_PCM_CE_N_IS_GPIO
#define PAD_PCM_CE_N_IS_GPIO BALL_AB20_IS_GPIO
#endif

#define BALL_AD19 PAD_PCM_REG_N
#define PAD_PCM_REG_N 153
#define GPIO_PAD_153 GPIO152
#ifndef BALL_AD19_IS_GPIO
#define BALL_AD19_IS_GPIO 0
#endif
#ifndef PAD_PCM_REG_N_IS_GPIO
#define PAD_PCM_REG_N_IS_GPIO BALL_AD19_IS_GPIO
#endif

#define BALL_AE18 PAD_PCM_CD_N
#define PAD_PCM_CD_N 160
#define GPIO_PAD_160 GPIO159
#ifndef BALL_AE18_IS_GPIO
#define BALL_AE18_IS_GPIO 0
#endif
#ifndef PAD_PCM_CD_N_IS_GPIO
#define PAD_PCM_CD_N_IS_GPIO BALL_AE18_IS_GPIO
#endif

#define BALL_AE19 PAD_PCM_A14
#define PAD_PCM_A14 142
#define GPIO_PAD_142 GPIO141
#ifndef BALL_AE19_IS_GPIO
#define BALL_AE19_IS_GPIO 0
#endif
#ifndef PAD_PCM_A14_IS_GPIO
#define PAD_PCM_A14_IS_GPIO BALL_AE19_IS_GPIO
#endif

#define BALL_AB21 PAD_PCM_A13
#define PAD_PCM_A13 141
#define GPIO_PAD_141 GPIO140
#ifndef BALL_AB21_IS_GPIO
#define BALL_AB21_IS_GPIO 0
#endif
#ifndef PAD_PCM_A13_IS_GPIO
#define PAD_PCM_A13_IS_GPIO BALL_AB21_IS_GPIO
#endif

#define BALL_AB22 PAD_PCM_A12
#define PAD_PCM_A12 145
#define GPIO_PAD_145 GPIO144
#ifndef BALL_AB22_IS_GPIO
#define BALL_AB22_IS_GPIO 0
#endif
#ifndef PAD_PCM_A12_IS_GPIO
#define PAD_PCM_A12_IS_GPIO BALL_AB22_IS_GPIO
#endif

#define BALL_AD20 PAD_PCM_A11
#define PAD_PCM_A11 136
#define GPIO_PAD_136 GPIO135
#ifndef BALL_AD20_IS_GPIO
#define BALL_AD20_IS_GPIO 0
#endif
#ifndef PAD_PCM_A11_IS_GPIO
#define PAD_PCM_A11_IS_GPIO BALL_AD20_IS_GPIO
#endif

#define BALL_AF20 PAD_PCM_A10
#define PAD_PCM_A10 134
#define GPIO_PAD_134 GPIO133
#ifndef BALL_AF20_IS_GPIO
#define BALL_AF20_IS_GPIO 0
#endif
#ifndef PAD_PCM_A10_IS_GPIO
#define PAD_PCM_A10_IS_GPIO BALL_AF20_IS_GPIO
#endif

#define BALL_AE20 PAD_PCM_A9
#define PAD_PCM_A9 138
#define GPIO_PAD_138 GPIO137
#ifndef BALL_AE20_IS_GPIO
#define BALL_AE20_IS_GPIO 0
#endif
#ifndef PAD_PCM_A9_IS_GPIO
#define PAD_PCM_A9_IS_GPIO BALL_AE20_IS_GPIO
#endif

#define BALL_AA23 PAD_PCM_A8
#define PAD_PCM_A8 140
#define GPIO_PAD_140 GPIO139
#ifndef BALL_AA23_IS_GPIO
#define BALL_AA23_IS_GPIO 0
#endif
#ifndef PAD_PCM_A8_IS_GPIO
#define PAD_PCM_A8_IS_GPIO BALL_AA23_IS_GPIO
#endif

#define BALL_Y23 PAD_PCM_A7
#define PAD_PCM_A7 146
#define GPIO_PAD_146 GPIO145
#ifndef BALL_Y23_IS_GPIO
#define BALL_Y23_IS_GPIO 0
#endif
#ifndef PAD_PCM_A7_IS_GPIO
#define PAD_PCM_A7_IS_GPIO BALL_Y23_IS_GPIO
#endif

#define BALL_AA19 PAD_PCM_A6
#define PAD_PCM_A6 147
#define GPIO_PAD_147 GPIO146
#ifndef BALL_AA19_IS_GPIO
#define BALL_AA19_IS_GPIO 0
#endif
#ifndef PAD_PCM_A6_IS_GPIO
#define PAD_PCM_A6_IS_GPIO BALL_AA19_IS_GPIO
#endif

#define BALL_AC22 PAD_PCM_A5
#define PAD_PCM_A5 148
#define GPIO_PAD_148 GPIO147
#ifndef BALL_AC22_IS_GPIO
#define BALL_AC22_IS_GPIO 0
#endif
#ifndef PAD_PCM_A5_IS_GPIO
#define PAD_PCM_A5_IS_GPIO BALL_AC22_IS_GPIO
#endif

#define BALL_V22 PAD_PCM_A4
#define PAD_PCM_A4 150
#define GPIO_PAD_150 GPIO149
#ifndef BALL_V22_IS_GPIO
#define BALL_V22_IS_GPIO 0
#endif
#ifndef PAD_PCM_A4_IS_GPIO
#define PAD_PCM_A4_IS_GPIO BALL_V22_IS_GPIO
#endif

#define BALL_AE21 PAD_PCM_A3
#define PAD_PCM_A3 151
#define GPIO_PAD_151 GPIO150
#ifndef BALL_AE21_IS_GPIO
#define BALL_AE21_IS_GPIO 0
#endif
#ifndef PAD_PCM_A3_IS_GPIO
#define PAD_PCM_A3_IS_GPIO BALL_AE21_IS_GPIO
#endif

#define BALL_W22 PAD_PCM_A2
#define PAD_PCM_A2 152
#define GPIO_PAD_152 GPIO151
#ifndef BALL_W22_IS_GPIO
#define BALL_W22_IS_GPIO 0
#endif
#ifndef PAD_PCM_A2_IS_GPIO
#define PAD_PCM_A2_IS_GPIO BALL_W22_IS_GPIO
#endif

#define BALL_AB23 PAD_PCM_A1
#define PAD_PCM_A1 154
#define GPIO_PAD_154 GPIO153
#ifndef BALL_AB23_IS_GPIO
#define BALL_AB23_IS_GPIO 0
#endif
#ifndef PAD_PCM_A1_IS_GPIO
#define PAD_PCM_A1_IS_GPIO BALL_AB23_IS_GPIO
#endif

#define BALL_AC23 PAD_PCM_A0
#define PAD_PCM_A0 155
#define GPIO_PAD_155 GPIO154
#ifndef BALL_AC23_IS_GPIO
#define BALL_AC23_IS_GPIO 0
#endif
#ifndef PAD_PCM_A0_IS_GPIO
#define PAD_PCM_A0_IS_GPIO BALL_AC23_IS_GPIO
#endif

#define BALL_Y22 PAD_PCM_D7
#define PAD_PCM_D7 132
#define GPIO_PAD_132 GPIO131
#ifndef BALL_Y22_IS_GPIO
#define BALL_Y22_IS_GPIO 0
#endif
#ifndef PAD_PCM_D7_IS_GPIO
#define PAD_PCM_D7_IS_GPIO BALL_Y22_IS_GPIO
#endif

#define BALL_AD21 PAD_PCM_D6
#define PAD_PCM_D6 131
#define GPIO_PAD_131 GPIO130
#ifndef BALL_AD21_IS_GPIO
#define BALL_AD21_IS_GPIO 0
#endif
#ifndef PAD_PCM_D6_IS_GPIO
#define PAD_PCM_D6_IS_GPIO BALL_AD21_IS_GPIO
#endif

#define BALL_AA22 PAD_PCM_D5
#define PAD_PCM_D5 130
#define GPIO_PAD_130 GPIO129
#ifndef BALL_AA22_IS_GPIO
#define BALL_AA22_IS_GPIO 0
#endif
#ifndef PAD_PCM_D5_IS_GPIO
#define PAD_PCM_D5_IS_GPIO BALL_AA22_IS_GPIO
#endif

#define BALL_W23 PAD_PCM_D4
#define PAD_PCM_D4 129
#define GPIO_PAD_129 GPIO128
#ifndef BALL_W23_IS_GPIO
#define BALL_W23_IS_GPIO 0
#endif
#ifndef PAD_PCM_D4_IS_GPIO
#define PAD_PCM_D4_IS_GPIO BALL_W23_IS_GPIO
#endif

#define BALL_AA21 PAD_PCM_D3
#define PAD_PCM_D3 128
#define GPIO_PAD_128 GPIO127
#ifndef BALL_AA21_IS_GPIO
#define BALL_AA21_IS_GPIO 0
#endif
#ifndef PAD_PCM_D3_IS_GPIO
#define PAD_PCM_D3_IS_GPIO BALL_AA21_IS_GPIO
#endif

#define BALL_AC20 PAD_PCM_D2
#define PAD_PCM_D2 158
#define GPIO_PAD_158 GPIO157
#ifndef BALL_AC20_IS_GPIO
#define BALL_AC20_IS_GPIO 0
#endif
#ifndef PAD_PCM_D2_IS_GPIO
#define PAD_PCM_D2_IS_GPIO BALL_AC20_IS_GPIO
#endif

#define BALL_AA20 PAD_PCM_D1
#define PAD_PCM_D1 157
#define GPIO_PAD_157 GPIO156
#ifndef BALL_AA20_IS_GPIO
#define BALL_AA20_IS_GPIO 0
#endif
#ifndef PAD_PCM_D1_IS_GPIO
#define PAD_PCM_D1_IS_GPIO BALL_AA20_IS_GPIO
#endif

#define BALL_V21 PAD_PCM_D0
#define PAD_PCM_D0 156
#define GPIO_PAD_156 GPIO155
#ifndef BALL_V21_IS_GPIO
#define BALL_V21_IS_GPIO 0
#endif
#ifndef PAD_PCM_D0_IS_GPIO
#define PAD_PCM_D0_IS_GPIO BALL_V21_IS_GPIO
#endif

#define BALL_P25 PAD_TS1_CLK
#define PAD_TS1_CLK 184
#define GPIO_PAD_184 GPIO183
#ifndef BALL_P25_IS_GPIO
#define BALL_P25_IS_GPIO 0
#endif
#ifndef PAD_TS1_CLK_IS_GPIO
#define PAD_TS1_CLK_IS_GPIO BALL_P25_IS_GPIO
#endif

#define BALL_N25 PAD_TS1_SYNC
#define PAD_TS1_SYNC 185
#define GPIO_PAD_185 GPIO184
#ifndef BALL_N25_IS_GPIO
#define BALL_N25_IS_GPIO 0
#endif
#ifndef PAD_TS1_SYNC_IS_GPIO
#define PAD_TS1_SYNC_IS_GPIO BALL_N25_IS_GPIO
#endif

#define BALL_N24 PAD_TS1_VLD
#define PAD_TS1_VLD 186
#define GPIO_PAD_186 GPIO185
#ifndef BALL_N24_IS_GPIO
#define BALL_N24_IS_GPIO 0
#endif
#ifndef PAD_TS1_VLD_IS_GPIO
#define PAD_TS1_VLD_IS_GPIO BALL_N24_IS_GPIO
#endif

#define BALL_P24 PAD_TS1_D7
#define PAD_TS1_D7 187
#define GPIO_PAD_187 GPIO186
#ifndef BALL_P24_IS_GPIO
#define BALL_P24_IS_GPIO 0
#endif
#ifndef PAD_TS1_D7_IS_GPIO
#define PAD_TS1_D7_IS_GPIO BALL_P24_IS_GPIO
#endif

#define BALL_M25 PAD_TS1_D6
#define PAD_TS1_D6 188
#define GPIO_PAD_188 GPIO187
#ifndef BALL_M25_IS_GPIO
#define BALL_M25_IS_GPIO 0
#endif
#ifndef PAD_TS1_D6_IS_GPIO
#define PAD_TS1_D6_IS_GPIO BALL_M25_IS_GPIO
#endif

#define BALL_M24 PAD_TS1_D5
#define PAD_TS1_D5 189
#define GPIO_PAD_189 GPIO188
#ifndef BALL_M24_IS_GPIO
#define BALL_M24_IS_GPIO 0
#endif
#ifndef PAD_TS1_D5_IS_GPIO
#define PAD_TS1_D5_IS_GPIO BALL_M24_IS_GPIO
#endif

#define BALL_M26 PAD_TS1_D4
#define PAD_TS1_D4 190
#define GPIO_PAD_190 GPIO189
#ifndef BALL_M26_IS_GPIO
#define BALL_M26_IS_GPIO 0
#endif
#ifndef PAD_TS1_D4_IS_GPIO
#define PAD_TS1_D4_IS_GPIO BALL_M26_IS_GPIO
#endif

#define BALL_P23 PAD_TS1_D3
#define PAD_TS1_D3 191
#define GPIO_PAD_191 GPIO190
#ifndef BALL_P23_IS_GPIO
#define BALL_P23_IS_GPIO 0
#endif
#ifndef PAD_TS1_D3_IS_GPIO
#define PAD_TS1_D3_IS_GPIO BALL_P23_IS_GPIO
#endif

#define BALL_P21 PAD_TS1_D2
#define PAD_TS1_D2 192
#define GPIO_PAD_192 GPIO191
#ifndef BALL_P21_IS_GPIO
#define BALL_P21_IS_GPIO 0
#endif
#ifndef PAD_TS1_D2_IS_GPIO
#define PAD_TS1_D2_IS_GPIO BALL_P21_IS_GPIO
#endif

#define BALL_N22 PAD_TS1_D1
#define PAD_TS1_D1 193
#define GPIO_PAD_193 GPIO192
#ifndef BALL_N22_IS_GPIO
#define BALL_N22_IS_GPIO 0
#endif
#ifndef PAD_TS1_D1_IS_GPIO
#define PAD_TS1_D1_IS_GPIO BALL_N22_IS_GPIO
#endif

#define BALL_P22 PAD_TS1_D0
#define PAD_TS1_D0 194
#define GPIO_PAD_194 GPIO193
#ifndef BALL_P22_IS_GPIO
#define BALL_P22_IS_GPIO 0
#endif
#ifndef PAD_TS1_D0_IS_GPIO
#define PAD_TS1_D0_IS_GPIO BALL_P22_IS_GPIO
#endif

#define BALL_T22 PAD_TS2_SYNC
#define PAD_TS2_SYNC 197
#define GPIO_PAD_197 GPIO196
#ifndef BALL_T22_IS_GPIO
#define BALL_T22_IS_GPIO 0
#endif
#ifndef PAD_TS2_SYNC_IS_GPIO
#define PAD_TS2_SYNC_IS_GPIO BALL_T22_IS_GPIO
#endif

#define BALL_T23 PAD_TS2_CLK
#define PAD_TS2_CLK 198
#define GPIO_PAD_198 GPIO197
#ifndef BALL_T23_IS_GPIO
#define BALL_T23_IS_GPIO 0
#endif
#ifndef PAD_TS2_CLK_IS_GPIO
#define PAD_TS2_CLK_IS_GPIO BALL_T23_IS_GPIO
#endif

#define BALL_T21 PAD_TS2_VLD
#define PAD_TS2_VLD 196
#define GPIO_PAD_196 GPIO195
#ifndef BALL_T21_IS_GPIO
#define BALL_T21_IS_GPIO 0
#endif
#ifndef PAD_TS2_VLD_IS_GPIO
#define PAD_TS2_VLD_IS_GPIO BALL_T21_IS_GPIO
#endif

#define BALL_R23 PAD_TS2_D0
#define PAD_TS2_D0 195
#define GPIO_PAD_195 GPIO194
#ifndef BALL_R23_IS_GPIO
#define BALL_R23_IS_GPIO 0
#endif
#ifndef PAD_TS2_D0_IS_GPIO
#define PAD_TS2_D0_IS_GPIO BALL_R23_IS_GPIO
#endif

#define PAD_PCM2_CE_N 9999
#ifndef PAD_PCM2_CE_N_IS_GPIO
#define PAD_PCM2_CE_N_IS_GPIO 0
#endif

#define PAD_PCM2_IRQA_N 9999
#ifndef PAD_PCM2_IRQA_N_IS_GPIO
#define PAD_PCM2_IRQA_N_IS_GPIO 0
#endif

#define PAD_GPIO20 9999
#ifndef PAD_GPIO20_IS_GPIO
#define PAD_GPIO20_IS_GPIO 0
#endif

#define PAD_GPIO19 9999
#ifndef PAD_GPIO19_IS_GPIO
#define PAD_GPIO19_IS_GPIO 0
#endif

#define PAD_GPIO22 9999
#ifndef PAD_GPIO22_IS_GPIO
#define PAD_GPIO22_IS_GPIO 0
#endif

#define PAD_GPIO21 9999
#ifndef PAD_GPIO21_IS_GPIO
#define PAD_GPIO21_IS_GPIO 0
#endif

#define PAD_GPIO24 9999
#ifndef PAD_GPIO24_IS_GPIO
#define PAD_GPIO24_IS_GPIO 0
#endif

#define PAD_GPIO23 9999
#ifndef PAD_GPIO23_IS_GPIO
#define PAD_GPIO23_IS_GPIO 0
#endif

#define PAD_GPIO26 9999
#ifndef PAD_GPIO26_IS_GPIO
#define PAD_GPIO26_IS_GPIO 0
#endif

#define PAD_GPIO25 9999
#ifndef PAD_GPIO25_IS_GPIO
#define PAD_GPIO25_IS_GPIO 0
#endif

#define PAD_GPIO27 9999
#ifndef PAD_GPIO27_IS_GPIO
#define PAD_GPIO27_IS_GPIO 0
#endif

#define PAD_PCM2_WAIT_N 9999
#ifndef PAD_PCM2_WAIT_N_IS_GPIO
#define PAD_PCM2_WAIT_N_IS_GPIO 0
#endif

#define PAD_PCM2_RESET 9999
#ifndef PAD_PCM2_RESET_IS_GPIO
#define PAD_PCM2_RESET_IS_GPIO 0
#endif

#define PAD_PCM2_CD_N 9999
#ifndef PAD_PCM2_CD_N_IS_GPIO
#define PAD_PCM2_CD_N_IS_GPIO 0
#endif

#define PAD_GPIO0 9999
#ifndef PAD_GPIO0_IS_GPIO
#define PAD_GPIO0_IS_GPIO 0
#endif

#define BALL_P6 PAD_GPIO2
#define PAD_GPIO2 60
#define GPIO_PAD_60 GPIO59
#ifndef BALL_P6_IS_GPIO
#define BALL_P6_IS_GPIO 0
#endif
#ifndef PAD_GPIO2_IS_GPIO
#define PAD_GPIO2_IS_GPIO BALL_P6_IS_GPIO
#endif

#define PAD_GPIO1 9999
#ifndef PAD_GPIO1_IS_GPIO
#define PAD_GPIO1_IS_GPIO 0
#endif

#define BALL_T4 PAD_GPIO4
#define PAD_GPIO4 62
#define GPIO_PAD_62 GPIO61
#ifndef BALL_T4_IS_GPIO
#define BALL_T4_IS_GPIO 0
#endif
#ifndef PAD_GPIO4_IS_GPIO
#define PAD_GPIO4_IS_GPIO BALL_T4_IS_GPIO
#endif

#define BALL_T5 PAD_GPIO3
#define PAD_GPIO3 61
#define GPIO_PAD_61 GPIO60
#ifndef BALL_T5_IS_GPIO
#define BALL_T5_IS_GPIO 0
#endif
#ifndef PAD_GPIO3_IS_GPIO
#define PAD_GPIO3_IS_GPIO BALL_T5_IS_GPIO
#endif

#define PAD_GPIO6 9999
#ifndef PAD_GPIO6_IS_GPIO
#define PAD_GPIO6_IS_GPIO 0
#endif

#define BALL_R6 PAD_GPIO5
#define PAD_GPIO5 63
#define GPIO_PAD_63 GPIO62
#ifndef BALL_R6_IS_GPIO
#define BALL_R6_IS_GPIO 0
#endif
#ifndef PAD_GPIO5_IS_GPIO
#define PAD_GPIO5_IS_GPIO BALL_R6_IS_GPIO
#endif

#define BALL_J6 PAD_DDCR_CK
#define PAD_DDCR_CK 57
#define GPIO_PAD_57 GPIO56
#ifndef BALL_J6_IS_GPIO
#define BALL_J6_IS_GPIO 0
#endif
#ifndef PAD_DDCR_CK_IS_GPIO
#define PAD_DDCR_CK_IS_GPIO BALL_J6_IS_GPIO
#endif

#define PAD_GPIO7 9999
#ifndef PAD_GPIO7_IS_GPIO
#define PAD_GPIO7_IS_GPIO 0
#endif

#define BALL_J7 PAD_DDCR_DA
#define PAD_DDCR_DA 56
#define GPIO_PAD_56 GPIO55
#ifndef BALL_J7_IS_GPIO
#define BALL_J7_IS_GPIO 0
#endif
#ifndef PAD_DDCR_DA_IS_GPIO
#define PAD_DDCR_DA_IS_GPIO BALL_J7_IS_GPIO
#endif

#define BALL_AC9 PAD_I2S_OUT_SD
#define PAD_I2S_OUT_SD 104
#define GPIO_PAD_104 GPIO103
#ifndef BALL_AC9_IS_GPIO
#define BALL_AC9_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_SD_IS_GPIO
#define PAD_I2S_OUT_SD_IS_GPIO BALL_AC9_IS_GPIO
#endif

#define PAD_I2S_OUT_SD2 9999
#ifndef PAD_I2S_OUT_SD2_IS_GPIO
#define PAD_I2S_OUT_SD2_IS_GPIO 0
#endif

#define PAD_I2S_OUT_SD1 9999
#ifndef PAD_I2S_OUT_SD1_IS_GPIO
#define PAD_I2S_OUT_SD1_IS_GPIO 0
#endif

#define PAD_I2S_OUT_SD3 9999
#ifndef PAD_I2S_OUT_SD3_IS_GPIO
#define PAD_I2S_OUT_SD3_IS_GPIO 0
#endif

#define BALL_AB10 PAD_PWM0
#define PAD_PWM0 161
#define GPIO_PAD_161 GPIO160
#ifndef BALL_AB10_IS_GPIO
#define BALL_AB10_IS_GPIO 0
#endif
#ifndef PAD_PWM0_IS_GPIO
#define PAD_PWM0_IS_GPIO BALL_AB10_IS_GPIO
#endif

#define BALL_AB8 PAD_I2S_OUT_BCK
#define PAD_I2S_OUT_BCK 103
#define GPIO_PAD_103 GPIO102
#ifndef BALL_AB8_IS_GPIO
#define BALL_AB8_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_BCK_IS_GPIO
#define PAD_I2S_OUT_BCK_IS_GPIO BALL_AB8_IS_GPIO
#endif

#define BALL_AC8 PAD_PWM1
#define PAD_PWM1 162
#define GPIO_PAD_162 GPIO161
#ifndef BALL_AC8_IS_GPIO
#define BALL_AC8_IS_GPIO 0
#endif
#ifndef PAD_PWM1_IS_GPIO
#define PAD_PWM1_IS_GPIO BALL_AC8_IS_GPIO
#endif

#define BALL_M4 PAD_SPDIF_OUT
#define PAD_SPDIF_OUT 100
#define GPIO_PAD_100 GPIO99
#ifndef BALL_M4_IS_GPIO
#define BALL_M4_IS_GPIO 0
#endif
#ifndef PAD_SPDIF_OUT_IS_GPIO
#define PAD_SPDIF_OUT_IS_GPIO BALL_M4_IS_GPIO
#endif

#define BALL_K9 PAD_PWM2
#define PAD_PWM2 163
#define GPIO_PAD_163 GPIO162
#ifndef BALL_K9_IS_GPIO
#define BALL_K9_IS_GPIO 0
#endif
#ifndef PAD_PWM2_IS_GPIO
#define PAD_PWM2_IS_GPIO BALL_K9_IS_GPIO
#endif

#define BALL_AB9 PAD_I2S_OUT_MCK
#define PAD_I2S_OUT_MCK 102
#define GPIO_PAD_102 GPIO101
#ifndef BALL_AB9_IS_GPIO
#define BALL_AB9_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_MCK_IS_GPIO
#define PAD_I2S_OUT_MCK_IS_GPIO BALL_AB9_IS_GPIO
#endif

#define BALL_K10 PAD_PWM3
#define PAD_PWM3 164
#define GPIO_PAD_164 GPIO163
#ifndef BALL_K10_IS_GPIO
#define BALL_K10_IS_GPIO 0
#endif
#ifndef PAD_PWM3_IS_GPIO
#define PAD_PWM3_IS_GPIO BALL_K10_IS_GPIO
#endif

#define BALL_AA9 PAD_I2S_OUT_WS
#define PAD_I2S_OUT_WS 101
#define GPIO_PAD_101 GPIO100
#ifndef BALL_AA9_IS_GPIO
#define BALL_AA9_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_WS_IS_GPIO
#define PAD_I2S_OUT_WS_IS_GPIO BALL_AA9_IS_GPIO
#endif

#define PAD_PWM4 9999
#ifndef PAD_PWM4_IS_GPIO
#define PAD_PWM4_IS_GPIO 0
#endif

#define BALL_L9 PAD_SPDIF_IN
#define PAD_SPDIF_IN 99
#define GPIO_PAD_99 GPIO98
#ifndef BALL_L9_IS_GPIO
#define BALL_L9_IS_GPIO 0
#endif
#ifndef PAD_SPDIF_IN_IS_GPIO
#define PAD_SPDIF_IN_IS_GPIO BALL_L9_IS_GPIO
#endif

#define BALL_M9 PAD_I2S_IN_WS
#define PAD_I2S_IN_WS 96
#define GPIO_PAD_96 GPIO95
#ifndef BALL_M9_IS_GPIO
#define BALL_M9_IS_GPIO 0
#endif
#ifndef PAD_I2S_IN_WS_IS_GPIO
#define PAD_I2S_IN_WS_IS_GPIO BALL_M9_IS_GPIO
#endif

#define BALL_K8 PAD_I2S_IN_SD
#define PAD_I2S_IN_SD 98
#define GPIO_PAD_98 GPIO97
#ifndef BALL_K8_IS_GPIO
#define BALL_K8_IS_GPIO 0
#endif
#ifndef PAD_I2S_IN_SD_IS_GPIO
#define PAD_I2S_IN_SD_IS_GPIO BALL_K8_IS_GPIO
#endif

#define BALL_L8 PAD_I2S_IN_BCK
#define PAD_I2S_IN_BCK 97
#define GPIO_PAD_97 GPIO96
#ifndef BALL_L8_IS_GPIO
#define BALL_L8_IS_GPIO 0
#endif
#ifndef PAD_I2S_IN_BCK_IS_GPIO
#define PAD_I2S_IN_BCK_IS_GPIO BALL_L8_IS_GPIO
#endif

#define BALL_B2 PAD_SAR0
#define PAD_SAR0 45
#define GPIO_PAD_45 GPIO44
#ifndef BALL_B2_IS_GPIO
#define BALL_B2_IS_GPIO 0
#endif
#ifndef PAD_SAR0_IS_GPIO
#define PAD_SAR0_IS_GPIO BALL_B2_IS_GPIO
#endif

#define BALL_B1 PAD_SAR1
#define PAD_SAR1 46
#define GPIO_PAD_46 GPIO45
#ifndef BALL_B1_IS_GPIO
#define BALL_B1_IS_GPIO 0
#endif
#ifndef PAD_SAR1_IS_GPIO
#define PAD_SAR1_IS_GPIO BALL_B1_IS_GPIO
#endif

#define BALL_E2 PAD_SAR2
#define PAD_SAR2 47
#define GPIO_PAD_47 GPIO46
#ifndef BALL_E2_IS_GPIO
#define BALL_E2_IS_GPIO 0
#endif
#ifndef PAD_SAR2_IS_GPIO
#define PAD_SAR2_IS_GPIO BALL_E2_IS_GPIO
#endif

#define BALL_L7 PAD_SAR3
#define PAD_SAR3 48
#define GPIO_PAD_48 GPIO47
#ifndef BALL_L7_IS_GPIO
#define BALL_L7_IS_GPIO 0
#endif
#ifndef PAD_SAR3_IS_GPIO
#define PAD_SAR3_IS_GPIO BALL_L7_IS_GPIO
#endif

#define PAD_SAR4 9999
#ifndef PAD_SAR4_IS_GPIO
#define PAD_SAR4_IS_GPIO 0
#endif

#define BALL_AA11 PAD_HOTPLUGA
#define PAD_HOTPLUGA 29
#define GPIO_PAD_29 GPIO28
#ifndef BALL_AA11_IS_GPIO
#define BALL_AA11_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGA_IS_GPIO
#define PAD_HOTPLUGA_IS_GPIO BALL_AA11_IS_GPIO
#endif


// PADS group name to index
#define PADS_DDCR           1223
#define PADS_DDCR2          1224
#define PADS_TS0            1225
#define PADS_TS1            1226
#define PADS_GPIO1_GPIO2    1227
#define PADS_LHSYNC2_LVSYNC2 1228
#define PADS_PCI_AD20_AD21  1229
#define PADS_PCI            1230
#define PADS_PCM            1231
#define PADS_SAR            1232
#define PADS_DOUT           1233
#define PADS_DIN            1234
#define PADS_I2S            1235
#define PADS_PF             1236
#define PADS_EMAC           1237
#define PADS_TCON           1238
#define PADS_UART1_MODE1    1239
#define PADS_UART1_MODE2    1240
#define PADS_UART1_MODE3    1241
#define PADS_UART2_MODE1    1242
#define PADS_UART2_MODE2    1243
#define PADS_UART2_MODE3    1244
#define PADS_ET_MODE0       1245
#define PADS_ET_MODE1       1246
#define PADS_ET_MODE2       1247
#define PADS_ET_MODE3       1248
#define PADS_MIIC           1249
#define PADS_PF_MODE1       1250
#define PADS_PF_MODE2       1251
#define PADS_PF_MODE3       1252
#define PADS_SPI_CZ1        1253
#define PADS_SPI_CZ2        1254
#define PADS_SPI_CZ3        1255
#define PADS_DDCR3          1256

// chip capbilities
#define CHIP_HAS_BT656_IN          0
#define CHIP_HAS_TS0               1
#define CHIP_HAS_TS1               0
#define CHIP_HAS_LVDS_10BIT_X2     1
#define CHIP_HAS_LVDS_8BIT_X2      1
#define CHIP_HAS_LVDS_8BIT_X1      1
#define CHIP_HAS_CIMAX             0
#define CHIP_HAS_USB_P0            1
#define CHIP_HAS_USB_P1            1
#define CHIP_HAS_USBVBUS0          0
#define CHIP_HAS_USBVBUS1          0
#define CHIP_HAS_UART1_MODE1       1
#define CHIP_HAS_UART1_MODE2       1
#define CHIP_HAS_UART1_MODE3       1
#define CHIP_HAS_PCMCIA1           0
#define CHIP_HAS_PCMCIA2           0
#define CHIP_HAS_PCMCIA            0
#define CHIP_HAS_UART2_MODE1       1
#define CHIP_HAS_UART2_MODE2       1
#define CHIP_HAS_UART2_MODE3       1
#define CHIP_HAS_RGB_A             1
#define CHIP_HAS_RGB_B             1
#define CHIP_HAS_RGB_C             1
#define CHIP_HAS_HDMI_A            1
#define CHIP_HAS_HDMI_B            1
#define CHIP_HAS_HDMI_C            1
#define CHIP_HAS_SPI_CZ1           1
#define CHIP_HAS_SPI_CZ2           0
#define CHIP_HAS_SPI_CZ3           0
#define CHIP_HAS_DDCR              1
#define CHIP_HAS_DDCR2             1
#define CHIP_HAS_TCON              1
#define CHIP_HAS_ET_MODE0_MII      1
#define CHIP_HAS_ET_MODE0_RMII     1
#define CHIP_HAS_ET_MODE1_MII      1
#define CHIP_HAS_ET_MODE1_RMII     1
#define CHIP_HAS_ET_MODE2_MII      1
#define CHIP_HAS_ET_MODE2_RMII     1
#define CHIP_HAS_I2S_IN            1
#define CHIP_HAS_I2S_OUT           1
#define CHIP_HAS_SPDIF_IN          0
#define CHIP_HAS_SPDIF_OUT         1
#define CHIP_HAS_DDR_A_CMD         1
#define CHIP_HAS_DDR_A_DATA        1
#define CHIP_HAS_DDR_B_CMD         1
#define CHIP_HAS_DDR_B_DATA        1
#define CHIP_USE_PCM_CDN_IN_PCM2   0
#define CHIP_USE_I2S_IN_IN_PCM     0
#define CHIP_USE_I2S_OUT_IN_PCM    0
#define CHIP_USE_SPDIF_IN_IN_PCM   0
#define CHIP_USE_SPDIF_OUT_IN_PCM  0
#define CHIP_USE_IIC_IN_DDCR2      0
#define CHIP_USE_PWM2_IN_GPIO14    0
#define CHIP_USE_PWM3_IN_GPIO15    0

// chip additional information
#define CHIP_FAMILY_TYPE           CHIP_FAMILY_MACAN

#endif/* _MSD91P1TMx_H_*/
