/* SPDX-License-Identifier: GPL-2.0-only OR BSD-3-Clause */
/******************************************************************************
 *
 * This file is provided under a dual license.  When you use or
 * distribute this software, you may choose to be licensed under
 * version 2 of the GNU General Public License ("GPLv2 License")
 * or BSD License.
 *
 * GPLv2 License
 *
 * Copyright(C) 2019 MediaTek Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of version 2 of the GNU General Public License as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See http://www.gnu.org/licenses/gpl-2.0.html for more details.
 *
 * BSD LICENSE
 *
 * Copyright(C) 2019 MediaTek Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *****************************************************************************/

// This file is generated by script, please do not edit it directly 
#ifndef _MSD93F0JMX_H_
#define _MSD93F0JMX_H_

#define PAD_NC 9999
#define PAD_GND 0

#define PAD_HOTPLUGB 9999
#ifndef PAD_HOTPLUGB_IS_GPIO
#define PAD_HOTPLUGB_IS_GPIO 0
#endif 

#define PIN_1 PAD_DDCDD_DA
#define PAD_DDCDD_DA 38
#define GPIO_PAD_38 GPIO37
#ifndef PIN_1_IS_GPIO
#define PIN_1_IS_GPIO 0
#endif 
#ifndef PAD_DDCDD_DA_IS_GPIO
#define PAD_DDCDD_DA_IS_GPIO PIN_1_IS_GPIO
#endif 

#define PAD_DDCDB_CK 9999
#ifndef PAD_DDCDB_CK_IS_GPIO
#define PAD_DDCDB_CK_IS_GPIO 0
#endif 

#define PIN_2 PAD_DDCDD_CK
#define PAD_DDCDD_CK 37
#define GPIO_PAD_37 GPIO36
#ifndef PIN_2_IS_GPIO
#define PIN_2_IS_GPIO 0
#endif 
#ifndef PAD_DDCDD_CK_IS_GPIO
#define PAD_DDCDD_CK_IS_GPIO PIN_2_IS_GPIO
#endif 

#define PAD_GPIO_PM11 9999
#ifndef PAD_GPIO_PM11_IS_GPIO
#define PAD_GPIO_PM11_IS_GPIO 0
#endif 

#define PAD_GPIO_PM1 9999
#ifndef PAD_GPIO_PM1_IS_GPIO
#define PAD_GPIO_PM1_IS_GPIO 0
#endif 

#define PAD_GPIO_PM12 9999
#ifndef PAD_GPIO_PM12_IS_GPIO
#define PAD_GPIO_PM12_IS_GPIO 0
#endif 

#define PIN_3 PAD_HOTPLUGD
#define PAD_HOTPLUGD 30
#define GPIO_PAD_30 GPIO29
#ifndef PIN_3_IS_GPIO
#define PIN_3_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGD_IS_GPIO
#define PAD_HOTPLUGD_IS_GPIO PIN_3_IS_GPIO
#endif 

#define PAD_GPIO_PM10 9999
#ifndef PAD_GPIO_PM10_IS_GPIO
#define PAD_GPIO_PM10_IS_GPIO 0
#endif 

#define PAD_VID0 9999
#ifndef PAD_VID0_IS_GPIO
#define PAD_VID0_IS_GPIO 0
#endif 

#define PAD_VID1 9999
#ifndef PAD_VID1_IS_GPIO
#define PAD_VID1_IS_GPIO 0
#endif 

#define PIN_22 PADA_HSYNC0
#define PADA_HSYNC0 240
#define GPIO_PAD_240 GPIO239
#ifndef PIN_22_IS_GPIO
#define PIN_22_IS_GPIO 0
#endif 
#ifndef PADA_HSYNC0_IS_GPIO
#define PADA_HSYNC0_IS_GPIO PIN_22_IS_GPIO
#endif 

#define PIN_23 PADA_BIN0P
#define PADA_BIN0P 250
#define GPIO_PAD_250 GPIO249
#ifndef PIN_23_IS_GPIO
#define PIN_23_IS_GPIO 0
#endif 
#ifndef PADA_BIN0P_IS_GPIO
#define PADA_BIN0P_IS_GPIO PIN_23_IS_GPIO
#endif 

#define PIN_24 PADA_GIN0P
#define PADA_GIN0P 248
#define GPIO_PAD_248 GPIO247
#ifndef PIN_24_IS_GPIO
#define PIN_24_IS_GPIO 0
#endif 
#ifndef PADA_GIN0P_IS_GPIO
#define PADA_GIN0P_IS_GPIO PIN_24_IS_GPIO
#endif 

#define PIN_25 PADA_GIN0M
#define PADA_GIN0M 252
#define GPIO_PAD_252 GPIO251
#ifndef PIN_25_IS_GPIO
#define PIN_25_IS_GPIO 0
#endif 
#ifndef PADA_GIN0M_IS_GPIO
#define PADA_GIN0M_IS_GPIO PIN_25_IS_GPIO
#endif 

#define PIN_26 PADA_RIN0P
#define PADA_RIN0P 246
#define GPIO_PAD_246 GPIO245
#ifndef PIN_26_IS_GPIO
#define PIN_26_IS_GPIO 0
#endif 
#ifndef PADA_RIN0P_IS_GPIO
#define PADA_RIN0P_IS_GPIO PIN_26_IS_GPIO
#endif 

#define PIN_27 PADA_VSYNC0
#define PADA_VSYNC0 241
#define GPIO_PAD_241 GPIO240
#ifndef PIN_27_IS_GPIO
#define PIN_27_IS_GPIO 0
#endif 
#ifndef PADA_VSYNC0_IS_GPIO
#define PADA_VSYNC0_IS_GPIO PIN_27_IS_GPIO
#endif 

#define PADA_HSYNC1 9999
#ifndef PADA_HSYNC1_IS_GPIO
#define PADA_HSYNC1_IS_GPIO 0
#endif 

#define PIN_28 PADA_BIN1P
#define PADA_BIN1P 251
#define GPIO_PAD_251 GPIO250
#ifndef PIN_28_IS_GPIO
#define PIN_28_IS_GPIO 0
#endif 
#ifndef PADA_BIN1P_IS_GPIO
#define PADA_BIN1P_IS_GPIO PIN_28_IS_GPIO
#endif 

#define PIN_29 PADA_GIN1P
#define PADA_GIN1P 249
#define GPIO_PAD_249 GPIO248
#ifndef PIN_29_IS_GPIO
#define PIN_29_IS_GPIO 0
#endif 
#ifndef PADA_GIN1P_IS_GPIO
#define PADA_GIN1P_IS_GPIO PIN_29_IS_GPIO
#endif 

#define PIN_30 PADA_GIN1M
#define PADA_GIN1M 253
#define GPIO_PAD_253 GPIO252
#ifndef PIN_30_IS_GPIO
#define PIN_30_IS_GPIO 0
#endif 
#ifndef PADA_GIN1M_IS_GPIO
#define PADA_GIN1M_IS_GPIO PIN_30_IS_GPIO
#endif 

#define PIN_31 PADA_RIN1P
#define PADA_RIN1P 247
#define GPIO_PAD_247 GPIO246
#ifndef PIN_31_IS_GPIO
#define PIN_31_IS_GPIO 0
#endif 
#ifndef PADA_RIN1P_IS_GPIO
#define PADA_RIN1P_IS_GPIO PIN_31_IS_GPIO
#endif 

#define PADA_VSYNC1 9999
#ifndef PADA_VSYNC1_IS_GPIO
#define PADA_VSYNC1_IS_GPIO 0
#endif 

#define PADA_HSYNC2 9999
#ifndef PADA_HSYNC2_IS_GPIO
#define PADA_HSYNC2_IS_GPIO 0
#endif 

#define PADA_VSYNC2 9999
#ifndef PADA_VSYNC2_IS_GPIO
#define PADA_VSYNC2_IS_GPIO 0
#endif 

#define PIN_36 PAD_LINEIN_L1
#define PAD_LINEIN_L1 230
#define GPIO_PAD_230 GPIO229
#ifndef PIN_36_IS_GPIO
#define PIN_36_IS_GPIO 0
#endif 
#ifndef PAD_LINEIN_L1_IS_GPIO
#define PAD_LINEIN_L1_IS_GPIO PIN_36_IS_GPIO
#endif 

#define PIN_37 PAD_LINEIN_R1
#define PAD_LINEIN_R1 231
#define GPIO_PAD_231 GPIO230
#ifndef PIN_37_IS_GPIO
#define PIN_37_IS_GPIO 0
#endif 
#ifndef PAD_LINEIN_R1_IS_GPIO
#define PAD_LINEIN_R1_IS_GPIO PIN_37_IS_GPIO
#endif 

#define PIN_41 PAD_LINEIN_R2
#define PAD_LINEIN_R2 233
#define GPIO_PAD_233 GPIO232
#ifndef PIN_41_IS_GPIO
#define PIN_41_IS_GPIO 0
#endif 
#ifndef PAD_LINEIN_R2_IS_GPIO
#define PAD_LINEIN_R2_IS_GPIO PIN_41_IS_GPIO
#endif 

#define PIN_42 PAD_LINEIN_L2
#define PAD_LINEIN_L2 232
#define GPIO_PAD_232 GPIO231
#ifndef PIN_42_IS_GPIO
#define PIN_42_IS_GPIO 0
#endif 
#ifndef PAD_LINEIN_L2_IS_GPIO
#define PAD_LINEIN_L2_IS_GPIO PIN_42_IS_GPIO
#endif 

#define PAD_LINEIN_R3 9999
#ifndef PAD_LINEIN_R3_IS_GPIO
#define PAD_LINEIN_R3_IS_GPIO 0
#endif 

#define PAD_LINEIN_L3 9999
#ifndef PAD_LINEIN_L3_IS_GPIO
#define PAD_LINEIN_L3_IS_GPIO 0
#endif 

#define PAD_LINEIN_R4 9999
#ifndef PAD_LINEIN_R4_IS_GPIO
#define PAD_LINEIN_R4_IS_GPIO 0
#endif 

#define PAD_LINEIN_L4 9999
#ifndef PAD_LINEIN_L4_IS_GPIO
#define PAD_LINEIN_L4_IS_GPIO 0
#endif 

#define PAD_LINEIN_R5 9999
#ifndef PAD_LINEIN_R5_IS_GPIO
#define PAD_LINEIN_R5_IS_GPIO 0
#endif 

#define PAD_LINEIN_L5 9999
#ifndef PAD_LINEIN_L5_IS_GPIO
#define PAD_LINEIN_L5_IS_GPIO 0
#endif 

#define PIN_54 PAD_DDCDC_DA
#define PAD_DDCDC_DA 36
#define GPIO_PAD_36 GPIO35
#ifndef PIN_54_IS_GPIO
#define PIN_54_IS_GPIO 0
#endif 
#ifndef PAD_DDCDC_DA_IS_GPIO
#define PAD_DDCDC_DA_IS_GPIO PIN_54_IS_GPIO
#endif 

#define PIN_55 PAD_DDCDC_CK
#define PAD_DDCDC_CK 35
#define GPIO_PAD_35 GPIO34
#ifndef PIN_55_IS_GPIO
#define PIN_55_IS_GPIO 0
#endif 
#ifndef PAD_DDCDC_CK_IS_GPIO
#define PAD_DDCDC_CK_IS_GPIO PIN_55_IS_GPIO
#endif 

#define PIN_57 PAD_HOTPLUGC
#define PAD_HOTPLUGC 29
#define GPIO_PAD_29 GPIO28
#ifndef PIN_57_IS_GPIO
#define PIN_57_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGC_IS_GPIO
#define PAD_HOTPLUGC_IS_GPIO PIN_57_IS_GPIO
#endif 

#define PAD_TGPIO0 9999
#ifndef PAD_TGPIO0_IS_GPIO
#define PAD_TGPIO0_IS_GPIO 0
#endif 

#define PAD_TGPIO1 9999
#ifndef PAD_TGPIO1_IS_GPIO
#define PAD_TGPIO1_IS_GPIO 0
#endif 

#define PAD_TGPIO2 9999
#ifndef PAD_TGPIO2_IS_GPIO
#define PAD_TGPIO2_IS_GPIO 0
#endif 

#define PAD_TGPIO3 9999
#ifndef PAD_TGPIO3_IS_GPIO
#define PAD_TGPIO3_IS_GPIO 0
#endif 

#define PIN_80 PAD_EMMC_IO0
#define PAD_EMMC_IO0 147
#define GPIO_PAD_147 GPIO146
#ifndef PIN_80_IS_GPIO
#define PIN_80_IS_GPIO 0
#endif 
#ifndef PAD_EMMC_IO0_IS_GPIO
#define PAD_EMMC_IO0_IS_GPIO PIN_80_IS_GPIO
#endif 

#define PAD_EMMC_IO1 9999
#ifndef PAD_EMMC_IO1_IS_GPIO
#define PAD_EMMC_IO1_IS_GPIO 0
#endif 

#define PIN_81 PAD_EMMC_IO2
#define PAD_EMMC_IO2 149
#define GPIO_PAD_149 GPIO148
#ifndef PIN_81_IS_GPIO
#define PIN_81_IS_GPIO 0
#endif 
#ifndef PAD_EMMC_IO2_IS_GPIO
#define PAD_EMMC_IO2_IS_GPIO PIN_81_IS_GPIO
#endif 

#define PAD_EMMC_IO3 9999
#ifndef PAD_EMMC_IO3_IS_GPIO
#define PAD_EMMC_IO3_IS_GPIO 0
#endif 

#define PIN_82 PAD_EMMC_IO4
#define PAD_EMMC_IO4 151
#define GPIO_PAD_151 GPIO150
#ifndef PIN_82_IS_GPIO
#define PIN_82_IS_GPIO 0
#endif 
#ifndef PAD_EMMC_IO4_IS_GPIO
#define PAD_EMMC_IO4_IS_GPIO PIN_82_IS_GPIO
#endif 

#define PAD_EMMC_IO5 9999
#ifndef PAD_EMMC_IO5_IS_GPIO
#define PAD_EMMC_IO5_IS_GPIO 0
#endif 

#define PIN_83 PAD_EMMC_IO6
#define PAD_EMMC_IO6 153
#define GPIO_PAD_153 GPIO152
#ifndef PIN_83_IS_GPIO
#define PIN_83_IS_GPIO 0
#endif 
#ifndef PAD_EMMC_IO6_IS_GPIO
#define PAD_EMMC_IO6_IS_GPIO PIN_83_IS_GPIO
#endif 

#define PAD_EMMC_IO7 9999
#ifndef PAD_EMMC_IO7_IS_GPIO
#define PAD_EMMC_IO7_IS_GPIO 0
#endif 

#define PAD_EMMC_IO12 9999
#ifndef PAD_EMMC_IO12_IS_GPIO
#define PAD_EMMC_IO12_IS_GPIO 0
#endif 

#define PAD_EMMC_IO13 9999
#ifndef PAD_EMMC_IO13_IS_GPIO
#define PAD_EMMC_IO13_IS_GPIO 0
#endif 

#define PIN_84 PAD_EMMC_IO8
#define PAD_EMMC_IO8 155
#define GPIO_PAD_155 GPIO154
#ifndef PIN_84_IS_GPIO
#define PIN_84_IS_GPIO 0
#endif 
#ifndef PAD_EMMC_IO8_IS_GPIO
#define PAD_EMMC_IO8_IS_GPIO PIN_84_IS_GPIO
#endif 

#define PAD_EMMC_IO14 9999
#ifndef PAD_EMMC_IO14_IS_GPIO
#define PAD_EMMC_IO14_IS_GPIO 0
#endif 

#define PAD_EMMC_IO9 9999
#ifndef PAD_EMMC_IO9_IS_GPIO
#define PAD_EMMC_IO9_IS_GPIO 0
#endif 

#define PAD_EMMC_IO15 9999
#ifndef PAD_EMMC_IO15_IS_GPIO
#define PAD_EMMC_IO15_IS_GPIO 0
#endif 

#define PIN_85 PAD_EMMC_IO10
#define PAD_EMMC_IO10 157
#define GPIO_PAD_157 GPIO156
#ifndef PIN_85_IS_GPIO
#define PIN_85_IS_GPIO 0
#endif 
#ifndef PAD_EMMC_IO10_IS_GPIO
#define PAD_EMMC_IO10_IS_GPIO PIN_85_IS_GPIO
#endif 

#define PAD_EMMC_IO16 9999
#ifndef PAD_EMMC_IO16_IS_GPIO
#define PAD_EMMC_IO16_IS_GPIO 0
#endif 

#define PAD_EMMC_IO11 9999
#ifndef PAD_EMMC_IO11_IS_GPIO
#define PAD_EMMC_IO11_IS_GPIO 0
#endif 

#define PAD_EMMC_IO17 9999
#ifndef PAD_EMMC_IO17_IS_GPIO
#define PAD_EMMC_IO17_IS_GPIO 0
#endif 

#define PAD_TS2_VLD 9999
#ifndef PAD_TS2_VLD_IS_GPIO
#define PAD_TS2_VLD_IS_GPIO 0
#endif 

#define PAD_TS2_SYNC 9999
#ifndef PAD_TS2_SYNC_IS_GPIO
#define PAD_TS2_SYNC_IS_GPIO 0
#endif 

#define PAD_TS2_D0 9999
#ifndef PAD_TS2_D0_IS_GPIO
#define PAD_TS2_D0_IS_GPIO 0
#endif 

#define PAD_TS2_D1 9999
#ifndef PAD_TS2_D1_IS_GPIO
#define PAD_TS2_D1_IS_GPIO 0
#endif 

#define PAD_TS2_D2 9999
#ifndef PAD_TS2_D2_IS_GPIO
#define PAD_TS2_D2_IS_GPIO 0
#endif 

#define PAD_TS2_D5 9999
#ifndef PAD_TS2_D5_IS_GPIO
#define PAD_TS2_D5_IS_GPIO 0
#endif 

#define PAD_TS2_D3 9999
#ifndef PAD_TS2_D3_IS_GPIO
#define PAD_TS2_D3_IS_GPIO 0
#endif 

#define PAD_TS2_D6 9999
#ifndef PAD_TS2_D6_IS_GPIO
#define PAD_TS2_D6_IS_GPIO 0
#endif 

#define PAD_TS2_D4 9999
#ifndef PAD_TS2_D4_IS_GPIO
#define PAD_TS2_D4_IS_GPIO 0
#endif 

#define PAD_TS2_D7 9999
#ifndef PAD_TS2_D7_IS_GPIO
#define PAD_TS2_D7_IS_GPIO 0
#endif 

#define PAD_TS2_CLK 9999
#ifndef PAD_TS2_CLK_IS_GPIO
#define PAD_TS2_CLK_IS_GPIO 0
#endif 

#define PAD_TS0_D6 9999
#ifndef PAD_TS0_D6_IS_GPIO
#define PAD_TS0_D6_IS_GPIO 0
#endif 

#define PAD_TS0_D7 9999
#ifndef PAD_TS0_D7_IS_GPIO
#define PAD_TS0_D7_IS_GPIO 0
#endif 

#define PAD_TS0_SYNC 9999
#ifndef PAD_TS0_SYNC_IS_GPIO
#define PAD_TS0_SYNC_IS_GPIO 0
#endif 

#define PIN_87 PAD_TS1_CLK
#define PAD_TS1_CLK 109
#define GPIO_PAD_109 GPIO108
#ifndef PIN_87_IS_GPIO
#define PIN_87_IS_GPIO 0
#endif 
#ifndef PAD_TS1_CLK_IS_GPIO
#define PAD_TS1_CLK_IS_GPIO PIN_87_IS_GPIO
#endif 

#define PAD_TS0_D0 9999
#ifndef PAD_TS0_D0_IS_GPIO
#define PAD_TS0_D0_IS_GPIO 0
#endif 

#define PIN_88 PAD_TS1_SYNC
#define PAD_TS1_SYNC 108
#define GPIO_PAD_108 GPIO107
#ifndef PIN_88_IS_GPIO
#define PIN_88_IS_GPIO 0
#endif 
#ifndef PAD_TS1_SYNC_IS_GPIO
#define PAD_TS1_SYNC_IS_GPIO PIN_88_IS_GPIO
#endif 

#define PAD_TS0_D1 9999
#ifndef PAD_TS0_D1_IS_GPIO
#define PAD_TS0_D1_IS_GPIO 0
#endif 

#define PIN_89 PAD_TS1_VLD
#define PAD_TS1_VLD 107
#define GPIO_PAD_107 GPIO106
#ifndef PIN_89_IS_GPIO
#define PIN_89_IS_GPIO 0
#endif 
#ifndef PAD_TS1_VLD_IS_GPIO
#define PAD_TS1_VLD_IS_GPIO PIN_89_IS_GPIO
#endif 

#define PAD_TS0_D2 9999
#ifndef PAD_TS0_D2_IS_GPIO
#define PAD_TS0_D2_IS_GPIO 0
#endif 

#define PAD_TS1_D0 9999
#ifndef PAD_TS1_D0_IS_GPIO
#define PAD_TS1_D0_IS_GPIO 0
#endif 

#define PAD_TS0_D3 9999
#ifndef PAD_TS0_D3_IS_GPIO
#define PAD_TS0_D3_IS_GPIO 0
#endif 

#define PAD_TS1_D1 9999
#ifndef PAD_TS1_D1_IS_GPIO
#define PAD_TS1_D1_IS_GPIO 0
#endif 

#define PAD_TS0_D4 9999
#ifndef PAD_TS0_D4_IS_GPIO
#define PAD_TS0_D4_IS_GPIO 0
#endif 

#define PAD_TS1_D2 9999
#ifndef PAD_TS1_D2_IS_GPIO
#define PAD_TS1_D2_IS_GPIO 0
#endif 

#define PAD_TS0_D5 9999
#ifndef PAD_TS0_D5_IS_GPIO
#define PAD_TS0_D5_IS_GPIO 0
#endif 

#define PAD_TS1_D3 9999
#ifndef PAD_TS1_D3_IS_GPIO
#define PAD_TS1_D3_IS_GPIO 0
#endif 

#define PAD_TS0_CLK 9999
#ifndef PAD_TS0_CLK_IS_GPIO
#define PAD_TS0_CLK_IS_GPIO 0
#endif 

#define PAD_TS1_D4 9999
#ifndef PAD_TS1_D4_IS_GPIO
#define PAD_TS1_D4_IS_GPIO 0
#endif 

#define PAD_TS0_VLD 9999
#ifndef PAD_TS0_VLD_IS_GPIO
#define PAD_TS0_VLD_IS_GPIO 0
#endif 

#define PAD_TS1_D5 9999
#ifndef PAD_TS1_D5_IS_GPIO
#define PAD_TS1_D5_IS_GPIO 0
#endif 

#define PAD_TS1_D6 9999
#ifndef PAD_TS1_D6_IS_GPIO
#define PAD_TS1_D6_IS_GPIO 0
#endif 

#define PAD_TS1_D7 9999
#ifndef PAD_TS1_D7_IS_GPIO
#define PAD_TS1_D7_IS_GPIO 0
#endif 

#define PIN_90 PAD_PCM_A0
#define PAD_PCM_A0 136
#define GPIO_PAD_136 GPIO135
#ifndef PIN_90_IS_GPIO
#define PIN_90_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A0_IS_GPIO
#define PAD_PCM_A0_IS_GPIO PIN_90_IS_GPIO
#endif 

#define PAD_PCM_WAIT_N 9999
#ifndef PAD_PCM_WAIT_N_IS_GPIO
#define PAD_PCM_WAIT_N_IS_GPIO 0
#endif 

#define PIN_91 PAD_PCM_A1
#define PAD_PCM_A1 135
#define GPIO_PAD_135 GPIO134
#ifndef PIN_91_IS_GPIO
#define PIN_91_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A1_IS_GPIO
#define PAD_PCM_A1_IS_GPIO PIN_91_IS_GPIO
#endif 

#define PAD_PCM_IRQA_N 9999
#ifndef PAD_PCM_IRQA_N_IS_GPIO
#define PAD_PCM_IRQA_N_IS_GPIO 0
#endif 

#define PIN_92 PAD_PCM_A2
#define PAD_PCM_A2 133
#define GPIO_PAD_133 GPIO132
#ifndef PIN_92_IS_GPIO
#define PIN_92_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A2_IS_GPIO
#define PAD_PCM_A2_IS_GPIO PIN_92_IS_GPIO
#endif 

#define PAD_PCM_D3 9999
#ifndef PAD_PCM_D3_IS_GPIO
#define PAD_PCM_D3_IS_GPIO 0
#endif 

#define PAD_PCM_A12 9999
#ifndef PAD_PCM_A12_IS_GPIO
#define PAD_PCM_A12_IS_GPIO 0
#endif 

#define PAD_PCM_D4 9999
#ifndef PAD_PCM_D4_IS_GPIO
#define PAD_PCM_D4_IS_GPIO 0
#endif 

#define PIN_93 PAD_PCM_A3
#define PAD_PCM_A3 132
#define GPIO_PAD_132 GPIO131
#ifndef PIN_93_IS_GPIO
#define PIN_93_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A3_IS_GPIO
#define PAD_PCM_A3_IS_GPIO PIN_93_IS_GPIO
#endif 

#define PAD_PCM_D6 9999
#ifndef PAD_PCM_D6_IS_GPIO
#define PAD_PCM_D6_IS_GPIO 0
#endif 

#define PIN_94 PAD_PCM_A4
#define PAD_PCM_A4 110
#define GPIO_PAD_110 GPIO109
#ifndef PIN_94_IS_GPIO
#define PIN_94_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A4_IS_GPIO
#define PAD_PCM_A4_IS_GPIO PIN_94_IS_GPIO
#endif 

#define PAD_PCM_A10 9999
#ifndef PAD_PCM_A10_IS_GPIO
#define PAD_PCM_A10_IS_GPIO 0
#endif 

#define PAD_PCM2_CD_N 9999
#ifndef PAD_PCM2_CD_N_IS_GPIO
#define PAD_PCM2_CD_N_IS_GPIO 0
#endif 

#define PAD_PCM_IOWR_N 9999
#ifndef PAD_PCM_IOWR_N_IS_GPIO
#define PAD_PCM_IOWR_N_IS_GPIO 0
#endif 

#define PIN_95 PAD_PCM_A5
#define PAD_PCM_A5 112
#define GPIO_PAD_112 GPIO111
#ifndef PIN_95_IS_GPIO
#define PIN_95_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A5_IS_GPIO
#define PAD_PCM_A5_IS_GPIO PIN_95_IS_GPIO
#endif 

#define PAD_PCM_OE_N 9999
#ifndef PAD_PCM_OE_N_IS_GPIO
#define PAD_PCM_OE_N_IS_GPIO 0
#endif 

#define PAD_PCM_CD_N 9999
#ifndef PAD_PCM_CD_N_IS_GPIO
#define PAD_PCM_CD_N_IS_GPIO 0
#endif 

#define PAD_PCM_D2 9999
#ifndef PAD_PCM_D2_IS_GPIO
#define PAD_PCM_D2_IS_GPIO 0
#endif 

#define PIN_96 PAD_PCM_A6
#define PAD_PCM_A6 113
#define GPIO_PAD_113 GPIO112
#ifndef PIN_96_IS_GPIO
#define PIN_96_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A6_IS_GPIO
#define PAD_PCM_A6_IS_GPIO PIN_96_IS_GPIO
#endif 

#define PAD_PCM_D5 9999
#ifndef PAD_PCM_D5_IS_GPIO
#define PAD_PCM_D5_IS_GPIO 0
#endif 

#define PAD_PCM2_WAIT_N 9999
#ifndef PAD_PCM2_WAIT_N_IS_GPIO
#define PAD_PCM2_WAIT_N_IS_GPIO 0
#endif 

#define PIN_97 PAD_PCM_A7
#define PAD_PCM_A7 114
#define GPIO_PAD_114 GPIO113
#ifndef PIN_97_IS_GPIO
#define PIN_97_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A7_IS_GPIO
#define PAD_PCM_A7_IS_GPIO PIN_97_IS_GPIO
#endif 

#define PAD_PCM_D7 9999
#ifndef PAD_PCM_D7_IS_GPIO
#define PAD_PCM_D7_IS_GPIO 0
#endif 

#define PAD_PCM_A8 9999
#ifndef PAD_PCM_A8_IS_GPIO
#define PAD_PCM_A8_IS_GPIO 0
#endif 

#define PAD_PCM_CE_N 9999
#ifndef PAD_PCM_CE_N_IS_GPIO
#define PAD_PCM_CE_N_IS_GPIO 0
#endif 

#define PAD_PCM_A9 9999
#ifndef PAD_PCM_A9_IS_GPIO
#define PAD_PCM_A9_IS_GPIO 0
#endif 

#define PAD_PCM_A11 9999
#ifndef PAD_PCM_A11_IS_GPIO
#define PAD_PCM_A11_IS_GPIO 0
#endif 

#define PAD_PCM_REG_N 9999
#ifndef PAD_PCM_REG_N_IS_GPIO
#define PAD_PCM_REG_N_IS_GPIO 0
#endif 

#define PAD_PCM_IORD_N 9999
#ifndef PAD_PCM_IORD_N_IS_GPIO
#define PAD_PCM_IORD_N_IS_GPIO 0
#endif 

#define PAD_PCM_WE_N 9999
#ifndef PAD_PCM_WE_N_IS_GPIO
#define PAD_PCM_WE_N_IS_GPIO 0
#endif 

#define PAD_PCM2_IRQA_N 9999
#ifndef PAD_PCM2_IRQA_N_IS_GPIO
#define PAD_PCM2_IRQA_N_IS_GPIO 0
#endif 

#define PAD_PCM_RESET 9999
#ifndef PAD_PCM_RESET_IS_GPIO
#define PAD_PCM_RESET_IS_GPIO 0
#endif 

#define PAD_PCM2_RESET 9999
#ifndef PAD_PCM2_RESET_IS_GPIO
#define PAD_PCM2_RESET_IS_GPIO 0
#endif 

#define PAD_PCM_D0 9999
#ifndef PAD_PCM_D0_IS_GPIO
#define PAD_PCM_D0_IS_GPIO 0
#endif 

#define PAD_PCM_A13 9999
#ifndef PAD_PCM_A13_IS_GPIO
#define PAD_PCM_A13_IS_GPIO 0
#endif 

#define PAD_PCM_D1 9999
#ifndef PAD_PCM_D1_IS_GPIO
#define PAD_PCM_D1_IS_GPIO 0
#endif 

#define PAD_PCM_A14 9999
#ifndef PAD_PCM_A14_IS_GPIO
#define PAD_PCM_A14_IS_GPIO 0
#endif 

#define PAD_PCM2_CE_N 9999
#ifndef PAD_PCM2_CE_N_IS_GPIO
#define PAD_PCM2_CE_N_IS_GPIO 0
#endif 

#define PIN_100 PAD_B_ODD0
#define PAD_B_ODD0 178
#define GPIO_PAD_178 GPIO177
#ifndef PIN_100_IS_GPIO
#define PIN_100_IS_GPIO 0
#endif 
#ifndef PAD_B_ODD0_IS_GPIO
#define PAD_B_ODD0_IS_GPIO PIN_100_IS_GPIO
#endif 

#define PIN_101 PAD_B_ODD1
#define PAD_B_ODD1 179
#define GPIO_PAD_179 GPIO178
#ifndef PIN_101_IS_GPIO
#define PIN_101_IS_GPIO 0
#endif 
#ifndef PAD_B_ODD1_IS_GPIO
#define PAD_B_ODD1_IS_GPIO PIN_101_IS_GPIO
#endif 

#define PIN_102 PAD_B_ODD2
#define PAD_B_ODD2 180
#define GPIO_PAD_180 GPIO179
#ifndef PIN_102_IS_GPIO
#define PIN_102_IS_GPIO 0
#endif 
#ifndef PAD_B_ODD2_IS_GPIO
#define PAD_B_ODD2_IS_GPIO PIN_102_IS_GPIO
#endif 

#define PIN_103 PAD_B_ODD3
#define PAD_B_ODD3 181
#define GPIO_PAD_181 GPIO180
#ifndef PIN_103_IS_GPIO
#define PIN_103_IS_GPIO 0
#endif 
#ifndef PAD_B_ODD3_IS_GPIO
#define PAD_B_ODD3_IS_GPIO PIN_103_IS_GPIO
#endif 

#define PIN_104 PAD_B_ODD4
#define PAD_B_ODD4 182
#define GPIO_PAD_182 GPIO181
#ifndef PIN_104_IS_GPIO
#define PIN_104_IS_GPIO 0
#endif 
#ifndef PAD_B_ODD4_IS_GPIO
#define PAD_B_ODD4_IS_GPIO PIN_104_IS_GPIO
#endif 

#define PIN_105 PAD_B_ODD5
#define PAD_B_ODD5 183
#define GPIO_PAD_183 GPIO182
#ifndef PIN_105_IS_GPIO
#define PIN_105_IS_GPIO 0
#endif 
#ifndef PAD_B_ODD5_IS_GPIO
#define PAD_B_ODD5_IS_GPIO PIN_105_IS_GPIO
#endif 

#define PIN_106 PAD_B_ODD6
#define PAD_B_ODD6 184
#define GPIO_PAD_184 GPIO183
#ifndef PIN_106_IS_GPIO
#define PIN_106_IS_GPIO 0
#endif 
#ifndef PAD_B_ODD6_IS_GPIO
#define PAD_B_ODD6_IS_GPIO PIN_106_IS_GPIO
#endif 

#define PIN_107 PAD_B_ODD7
#define PAD_B_ODD7 185
#define GPIO_PAD_185 GPIO184
#ifndef PIN_107_IS_GPIO
#define PIN_107_IS_GPIO 0
#endif 
#ifndef PAD_B_ODD7_IS_GPIO
#define PAD_B_ODD7_IS_GPIO PIN_107_IS_GPIO
#endif 

#define PIN_108 PAD_G_ODD0
#define PAD_G_ODD0 186
#define GPIO_PAD_186 GPIO185
#ifndef PIN_108_IS_GPIO
#define PIN_108_IS_GPIO 0
#endif 
#ifndef PAD_G_ODD0_IS_GPIO
#define PAD_G_ODD0_IS_GPIO PIN_108_IS_GPIO
#endif 

#define PIN_109 PAD_G_ODD1
#define PAD_G_ODD1 187
#define GPIO_PAD_187 GPIO186
#ifndef PIN_109_IS_GPIO
#define PIN_109_IS_GPIO 0
#endif 
#ifndef PAD_G_ODD1_IS_GPIO
#define PAD_G_ODD1_IS_GPIO PIN_109_IS_GPIO
#endif 

#define PIN_110 PAD_G_ODD2
#define PAD_G_ODD2 188
#define GPIO_PAD_188 GPIO187
#ifndef PIN_110_IS_GPIO
#define PIN_110_IS_GPIO 0
#endif 
#ifndef PAD_G_ODD2_IS_GPIO
#define PAD_G_ODD2_IS_GPIO PIN_110_IS_GPIO
#endif 

#define PIN_111 PAD_G_ODD3
#define PAD_G_ODD3 189
#define GPIO_PAD_189 GPIO188
#ifndef PIN_111_IS_GPIO
#define PIN_111_IS_GPIO 0
#endif 
#ifndef PAD_G_ODD3_IS_GPIO
#define PAD_G_ODD3_IS_GPIO PIN_111_IS_GPIO
#endif 

#define PIN_112 PAD_G_ODD4
#define PAD_G_ODD4 190
#define GPIO_PAD_190 GPIO189
#ifndef PIN_112_IS_GPIO
#define PIN_112_IS_GPIO 0
#endif 
#ifndef PAD_G_ODD4_IS_GPIO
#define PAD_G_ODD4_IS_GPIO PIN_112_IS_GPIO
#endif 

#define PIN_113 PAD_G_ODD5
#define PAD_G_ODD5 191
#define GPIO_PAD_191 GPIO190
#ifndef PIN_113_IS_GPIO
#define PIN_113_IS_GPIO 0
#endif 
#ifndef PAD_G_ODD5_IS_GPIO
#define PAD_G_ODD5_IS_GPIO PIN_113_IS_GPIO
#endif 

#define PIN_114 PAD_G_ODD6
#define PAD_G_ODD6 192
#define GPIO_PAD_192 GPIO191
#ifndef PIN_114_IS_GPIO
#define PIN_114_IS_GPIO 0
#endif 
#ifndef PAD_G_ODD6_IS_GPIO
#define PAD_G_ODD6_IS_GPIO PIN_114_IS_GPIO
#endif 

#define PIN_115 PAD_G_ODD7
#define PAD_G_ODD7 193
#define GPIO_PAD_193 GPIO192
#ifndef PIN_115_IS_GPIO
#define PIN_115_IS_GPIO 0
#endif 
#ifndef PAD_G_ODD7_IS_GPIO
#define PAD_G_ODD7_IS_GPIO PIN_115_IS_GPIO
#endif 

#define PIN_116 PAD_R_ODD0
#define PAD_R_ODD0 194
#define GPIO_PAD_194 GPIO193
#ifndef PIN_116_IS_GPIO
#define PIN_116_IS_GPIO 0
#endif 
#ifndef PAD_R_ODD0_IS_GPIO
#define PAD_R_ODD0_IS_GPIO PIN_116_IS_GPIO
#endif 

#define PIN_117 PAD_R_ODD1
#define PAD_R_ODD1 195
#define GPIO_PAD_195 GPIO194
#ifndef PIN_117_IS_GPIO
#define PIN_117_IS_GPIO 0
#endif 
#ifndef PAD_R_ODD1_IS_GPIO
#define PAD_R_ODD1_IS_GPIO PIN_117_IS_GPIO
#endif 

#define PIN_119 PAD_R_ODD2
#define PAD_R_ODD2 196
#define GPIO_PAD_196 GPIO195
#ifndef PIN_119_IS_GPIO
#define PIN_119_IS_GPIO 0
#endif 
#ifndef PAD_R_ODD2_IS_GPIO
#define PAD_R_ODD2_IS_GPIO PIN_119_IS_GPIO
#endif 

#define PIN_118 PAD_R_ODD3
#define PAD_R_ODD3 197
#define GPIO_PAD_197 GPIO196
#ifndef PIN_118_IS_GPIO
#define PIN_118_IS_GPIO 0
#endif 
#ifndef PAD_R_ODD3_IS_GPIO
#define PAD_R_ODD3_IS_GPIO PIN_118_IS_GPIO
#endif 

#define PIN_121 PAD_R_ODD4
#define PAD_R_ODD4 198
#define GPIO_PAD_198 GPIO197
#ifndef PIN_121_IS_GPIO
#define PIN_121_IS_GPIO 0
#endif 
#ifndef PAD_R_ODD4_IS_GPIO
#define PAD_R_ODD4_IS_GPIO PIN_121_IS_GPIO
#endif 

#define PIN_120 PAD_R_ODD5
#define PAD_R_ODD5 199
#define GPIO_PAD_199 GPIO198
#ifndef PIN_120_IS_GPIO
#define PIN_120_IS_GPIO 0
#endif 
#ifndef PAD_R_ODD5_IS_GPIO
#define PAD_R_ODD5_IS_GPIO PIN_120_IS_GPIO
#endif 

#define PIN_123 PAD_R_ODD6
#define PAD_R_ODD6 200
#define GPIO_PAD_200 GPIO199
#ifndef PIN_123_IS_GPIO
#define PIN_123_IS_GPIO 0
#endif 
#ifndef PAD_R_ODD6_IS_GPIO
#define PAD_R_ODD6_IS_GPIO PIN_123_IS_GPIO
#endif 

#define PIN_122 PAD_R_ODD7
#define PAD_R_ODD7 201
#define GPIO_PAD_201 GPIO200
#ifndef PIN_122_IS_GPIO
#define PIN_122_IS_GPIO 0
#endif 
#ifndef PAD_R_ODD7_IS_GPIO
#define PAD_R_ODD7_IS_GPIO PIN_122_IS_GPIO
#endif 

#define PIN_125 PAD_LCK
#define PAD_LCK 202
#define GPIO_PAD_202 GPIO201
#ifndef PIN_125_IS_GPIO
#define PIN_125_IS_GPIO 0
#endif 
#ifndef PAD_LCK_IS_GPIO
#define PAD_LCK_IS_GPIO PIN_125_IS_GPIO
#endif 

#define PIN_124 PAD_LDE
#define PAD_LDE 203
#define GPIO_PAD_203 GPIO202
#ifndef PIN_124_IS_GPIO
#define PIN_124_IS_GPIO 0
#endif 
#ifndef PAD_LDE_IS_GPIO
#define PAD_LDE_IS_GPIO PIN_124_IS_GPIO
#endif 

#define PIN_127 PAD_LHSYNC
#define PAD_LHSYNC 204
#define GPIO_PAD_204 GPIO203
#ifndef PIN_127_IS_GPIO
#define PIN_127_IS_GPIO 0
#endif 
#ifndef PAD_LHSYNC_IS_GPIO
#define PAD_LHSYNC_IS_GPIO PIN_127_IS_GPIO
#endif 

#define PIN_126 PAD_LVSYNC
#define PAD_LVSYNC 205
#define GPIO_PAD_205 GPIO204
#ifndef PIN_126_IS_GPIO
#define PIN_126_IS_GPIO 0
#endif 
#ifndef PAD_LVSYNC_IS_GPIO
#define PAD_LVSYNC_IS_GPIO PIN_126_IS_GPIO
#endif 

#define PAD_GPIO11 9999
#ifndef PAD_GPIO11_IS_GPIO
#define PAD_GPIO11_IS_GPIO 0
#endif 

#define PAD_TCON7 9999
#ifndef PAD_TCON7_IS_GPIO
#define PAD_TCON7_IS_GPIO 0
#endif 

#define PAD_GPIO10 9999
#ifndef PAD_GPIO10_IS_GPIO
#define PAD_GPIO10_IS_GPIO 0
#endif 

#define PAD_TCON6 9999
#ifndef PAD_TCON6_IS_GPIO
#define PAD_TCON6_IS_GPIO 0
#endif 

#define PAD_GPIO9 9999
#ifndef PAD_GPIO9_IS_GPIO
#define PAD_GPIO9_IS_GPIO 0
#endif 

#define PAD_TCON5 9999
#ifndef PAD_TCON5_IS_GPIO
#define PAD_TCON5_IS_GPIO 0
#endif 

#define PAD_I2S_IN_SD 9999
#ifndef PAD_I2S_IN_SD_IS_GPIO
#define PAD_I2S_IN_SD_IS_GPIO 0
#endif 

#define PAD_TCON4 9999
#ifndef PAD_TCON4_IS_GPIO
#define PAD_TCON4_IS_GPIO 0
#endif 

#define PAD_TCON3 9999
#ifndef PAD_TCON3_IS_GPIO
#define PAD_TCON3_IS_GPIO 0
#endif 

#define PAD_I2S_IN_BCK 9999
#ifndef PAD_I2S_IN_BCK_IS_GPIO
#define PAD_I2S_IN_BCK_IS_GPIO 0
#endif 

#define PIN_129 PAD_TCON2
#define PAD_TCON2 213
#define GPIO_PAD_213 GPIO212
#ifndef PIN_129_IS_GPIO
#define PIN_129_IS_GPIO 0
#endif 
#ifndef PAD_TCON2_IS_GPIO
#define PAD_TCON2_IS_GPIO PIN_129_IS_GPIO
#endif 

#define PAD_VSYNC_LIKE 9999
#ifndef PAD_VSYNC_LIKE_IS_GPIO
#define PAD_VSYNC_LIKE_IS_GPIO 0
#endif 

#define PAD_TCON1 9999
#ifndef PAD_TCON1_IS_GPIO
#define PAD_TCON1_IS_GPIO 0
#endif 

#define PAD_PWM2 9999
#ifndef PAD_PWM2_IS_GPIO
#define PAD_PWM2_IS_GPIO 0
#endif 

#define PAD_TCON0 9999
#ifndef PAD_TCON0_IS_GPIO
#define PAD_TCON0_IS_GPIO 0
#endif 

#define PIN_130 PAD_UART_TX2
#define PAD_UART_TX2 76
#define GPIO_PAD_76 GPIO75
#ifndef PIN_130_IS_GPIO
#define PIN_130_IS_GPIO 0
#endif 
#ifndef PAD_UART_TX2_IS_GPIO
#define PAD_UART_TX2_IS_GPIO PIN_130_IS_GPIO
#endif 

#define PIN_131 PAD_UART_RX2
#define PAD_UART_RX2 75
#define GPIO_PAD_75 GPIO74
#ifndef PIN_131_IS_GPIO
#define PIN_131_IS_GPIO 0
#endif 
#ifndef PAD_UART_RX2_IS_GPIO
#define PAD_UART_RX2_IS_GPIO PIN_131_IS_GPIO
#endif 

#define PAD_I2S_IN_WS 9999
#ifndef PAD_I2S_IN_WS_IS_GPIO
#define PAD_I2S_IN_WS_IS_GPIO 0
#endif 

#define PAD_SPI2_DI 9999
#ifndef PAD_SPI2_DI_IS_GPIO
#define PAD_SPI2_DI_IS_GPIO 0
#endif 

#define PAD_GPIO26 9999
#ifndef PAD_GPIO26_IS_GPIO
#define PAD_GPIO26_IS_GPIO 0
#endif 

#define PAD_SPI2_CK 9999
#ifndef PAD_SPI2_CK_IS_GPIO
#define PAD_SPI2_CK_IS_GPIO 0
#endif 

#define PAD_PWM4 9999
#ifndef PAD_PWM4_IS_GPIO
#define PAD_PWM4_IS_GPIO 0
#endif 

#define PAD_SPI1_DI 9999
#ifndef PAD_SPI1_DI_IS_GPIO
#define PAD_SPI1_DI_IS_GPIO 0
#endif 

#define PAD_PWM3 9999
#ifndef PAD_PWM3_IS_GPIO
#define PAD_PWM3_IS_GPIO 0
#endif 

#define PAD_SPI1_CK 9999
#ifndef PAD_SPI1_CK_IS_GPIO
#define PAD_SPI1_CK_IS_GPIO 0
#endif 

#define PAD_PWM0 9999
#ifndef PAD_PWM0_IS_GPIO
#define PAD_PWM0_IS_GPIO 0
#endif 

#define PAD_PWM1 9999
#ifndef PAD_PWM1_IS_GPIO
#define PAD_PWM1_IS_GPIO 0
#endif 

#define PAD_GPIO15 9999
#ifndef PAD_GPIO15_IS_GPIO
#define PAD_GPIO15_IS_GPIO 0
#endif 

#define PAD_GPIO16 9999
#ifndef PAD_GPIO16_IS_GPIO
#define PAD_GPIO16_IS_GPIO 0
#endif 

#define PAD_GPIO17 9999
#ifndef PAD_GPIO17_IS_GPIO
#define PAD_GPIO17_IS_GPIO 0
#endif 

#define PAD_GPIO18 9999
#ifndef PAD_GPIO18_IS_GPIO
#define PAD_GPIO18_IS_GPIO 0
#endif 

#define PAD_I2S_OUT_SD1 9999
#ifndef PAD_I2S_OUT_SD1_IS_GPIO
#define PAD_I2S_OUT_SD1_IS_GPIO 0
#endif 

#define PAD_GPIO22 9999
#ifndef PAD_GPIO22_IS_GPIO
#define PAD_GPIO22_IS_GPIO 0
#endif 

#define PAD_I2S_OUT_SD2 9999
#ifndef PAD_I2S_OUT_SD2_IS_GPIO
#define PAD_I2S_OUT_SD2_IS_GPIO 0
#endif 

#define PAD_GPIO25 9999
#ifndef PAD_GPIO25_IS_GPIO
#define PAD_GPIO25_IS_GPIO 0
#endif 

#define PAD_I2S_OUT_SD3 9999
#ifndef PAD_I2S_OUT_SD3_IS_GPIO
#define PAD_I2S_OUT_SD3_IS_GPIO 0
#endif 

#define PAD_GPIO19 9999
#ifndef PAD_GPIO19_IS_GPIO
#define PAD_GPIO19_IS_GPIO 0
#endif 

#define PAD_SPDIF_IN 9999
#ifndef PAD_SPDIF_IN_IS_GPIO
#define PAD_SPDIF_IN_IS_GPIO 0
#endif 

#define PAD_GPIO14 9999
#ifndef PAD_GPIO14_IS_GPIO
#define PAD_GPIO14_IS_GPIO 0
#endif 

#define PAD_GPIO4 9999
#ifndef PAD_GPIO4_IS_GPIO
#define PAD_GPIO4_IS_GPIO 0
#endif 

#define PIN_133 PAD_GPIO0
#define PAD_GPIO0 47
#define GPIO_PAD_47 GPIO46
#ifndef PIN_133_IS_GPIO
#define PIN_133_IS_GPIO 0
#endif 
#ifndef PAD_GPIO0_IS_GPIO
#define PAD_GPIO0_IS_GPIO PIN_133_IS_GPIO
#endif 

#define PAD_GPIO5 9999
#ifndef PAD_GPIO5_IS_GPIO
#define PAD_GPIO5_IS_GPIO 0
#endif 

#define PIN_134 PAD_GPIO1
#define PAD_GPIO1 48
#define GPIO_PAD_48 GPIO47
#ifndef PIN_134_IS_GPIO
#define PIN_134_IS_GPIO 0
#endif 
#ifndef PAD_GPIO1_IS_GPIO
#define PAD_GPIO1_IS_GPIO PIN_134_IS_GPIO
#endif 

#define PAD_GPIO6 9999
#ifndef PAD_GPIO6_IS_GPIO
#define PAD_GPIO6_IS_GPIO 0
#endif 

#define PIN_135 PAD_GPIO2
#define PAD_GPIO2 49
#define GPIO_PAD_49 GPIO48
#ifndef PIN_135_IS_GPIO
#define PIN_135_IS_GPIO 0
#endif 
#ifndef PAD_GPIO2_IS_GPIO
#define PAD_GPIO2_IS_GPIO PIN_135_IS_GPIO
#endif 

#define PAD_GPIO7 9999
#ifndef PAD_GPIO7_IS_GPIO
#define PAD_GPIO7_IS_GPIO 0
#endif 

#define PAD_GPIO3 9999
#ifndef PAD_GPIO3_IS_GPIO
#define PAD_GPIO3_IS_GPIO 0
#endif 

#define PAD_GPIO8 9999
#ifndef PAD_GPIO8_IS_GPIO
#define PAD_GPIO8_IS_GPIO 0
#endif 

#define PIN_136 PAD_DDCR_DA
#define PAD_DDCR_DA 82
#define GPIO_PAD_82 GPIO81
#ifndef PIN_136_IS_GPIO
#define PIN_136_IS_GPIO 0
#endif 
#ifndef PAD_DDCR_DA_IS_GPIO
#define PAD_DDCR_DA_IS_GPIO PIN_136_IS_GPIO
#endif 

#define PAD_GPIO27 9999
#ifndef PAD_GPIO27_IS_GPIO
#define PAD_GPIO27_IS_GPIO 0
#endif 

#define PAD_GPIO20 9999
#ifndef PAD_GPIO20_IS_GPIO
#define PAD_GPIO20_IS_GPIO 0
#endif 

#define PIN_137 PAD_DDCR_CK
#define PAD_DDCR_CK 83
#define GPIO_PAD_83 GPIO82
#ifndef PIN_137_IS_GPIO
#define PIN_137_IS_GPIO 0
#endif 
#ifndef PAD_DDCR_CK_IS_GPIO
#define PAD_DDCR_CK_IS_GPIO PIN_137_IS_GPIO
#endif 

#define PAD_GPIO24 9999
#ifndef PAD_GPIO24_IS_GPIO
#define PAD_GPIO24_IS_GPIO 0
#endif 

#define PIN_138 PAD_I2S_OUT_MCK
#define PAD_I2S_OUT_MCK 171
#define GPIO_PAD_171 GPIO170
#ifndef PIN_138_IS_GPIO
#define PIN_138_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_MCK_IS_GPIO
#define PAD_I2S_OUT_MCK_IS_GPIO PIN_138_IS_GPIO
#endif 

#define PAD_GPIO21 9999
#ifndef PAD_GPIO21_IS_GPIO
#define PAD_GPIO21_IS_GPIO 0
#endif 

#define PIN_139 PAD_I2S_OUT_WS
#define PAD_I2S_OUT_WS 172
#define GPIO_PAD_172 GPIO171
#ifndef PIN_139_IS_GPIO
#define PIN_139_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_WS_IS_GPIO
#define PAD_I2S_OUT_WS_IS_GPIO PIN_139_IS_GPIO
#endif 

#define PAD_GPIO23 9999
#ifndef PAD_GPIO23_IS_GPIO
#define PAD_GPIO23_IS_GPIO 0
#endif 

#define PIN_140 PAD_I2S_OUT_BCK
#define PAD_I2S_OUT_BCK 173
#define GPIO_PAD_173 GPIO172
#ifndef PIN_140_IS_GPIO
#define PIN_140_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_BCK_IS_GPIO
#define PAD_I2S_OUT_BCK_IS_GPIO PIN_140_IS_GPIO
#endif 

#define PAD_GPIO12 9999
#ifndef PAD_GPIO12_IS_GPIO
#define PAD_GPIO12_IS_GPIO 0
#endif 

#define PIN_141 PAD_I2S_OUT_SD
#define PAD_I2S_OUT_SD 174
#define GPIO_PAD_174 GPIO173
#ifndef PIN_141_IS_GPIO
#define PIN_141_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_SD_IS_GPIO
#define PAD_I2S_OUT_SD_IS_GPIO PIN_141_IS_GPIO
#endif 

#define PAD_GPIO13 9999
#ifndef PAD_GPIO13_IS_GPIO
#define PAD_GPIO13_IS_GPIO 0
#endif 

#define PIN_142 PAD_SPDIF_OUT
#define PAD_SPDIF_OUT 170
#define GPIO_PAD_170 GPIO169
#ifndef PIN_142_IS_GPIO
#define PIN_142_IS_GPIO 0
#endif 
#ifndef PAD_SPDIF_OUT_IS_GPIO
#define PAD_SPDIF_OUT_IS_GPIO PIN_142_IS_GPIO
#endif 

#define PAD_PM_SPI_HOLDN 9999
#ifndef PAD_PM_SPI_HOLDN_IS_GPIO
#define PAD_PM_SPI_HOLDN_IS_GPIO 0
#endif 

#define PIN_162 PAD_PM_SPI_DI
#define PAD_PM_SPI_DI 3
#define GPIO_PAD_3 GPIO2
#ifndef PIN_162_IS_GPIO
#define PIN_162_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_DI_IS_GPIO
#define PAD_PM_SPI_DI_IS_GPIO PIN_162_IS_GPIO
#endif 

#define PAD_PM_SPI_CZ 9999
#ifndef PAD_PM_SPI_CZ_IS_GPIO
#define PAD_PM_SPI_CZ_IS_GPIO 0
#endif 

#define PAD_PM_SPI_CK 9999
#ifndef PAD_PM_SPI_CK_IS_GPIO
#define PAD_PM_SPI_CK_IS_GPIO 0
#endif 

#define PAD_GPIO_PM8 9999
#ifndef PAD_GPIO_PM8_IS_GPIO
#define PAD_GPIO_PM8_IS_GPIO 0
#endif 

#define PAD_PM_SPI_DO 9999
#ifndef PAD_PM_SPI_DO_IS_GPIO
#define PAD_PM_SPI_DO_IS_GPIO 0
#endif 

#define PAD_GPIO_PM3 9999
#ifndef PAD_GPIO_PM3_IS_GPIO
#define PAD_GPIO_PM3_IS_GPIO 0
#endif 

#define PIN_163 PAD_PM_SPI_WPN
#define PAD_PM_SPI_WPN 6
#define GPIO_PAD_6 GPIO5
#ifndef PIN_163_IS_GPIO
#define PIN_163_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_WPN_IS_GPIO
#define PAD_PM_SPI_WPN_IS_GPIO PIN_163_IS_GPIO
#endif 

#define PAD_GPIO_PM6 9999
#ifndef PAD_GPIO_PM6_IS_GPIO
#define PAD_GPIO_PM6_IS_GPIO 0
#endif 

#define PIN_164 PAD_HOTPLUGA
#define PAD_HOTPLUGA 27
#define GPIO_PAD_27 GPIO26
#ifndef PIN_164_IS_GPIO
#define PIN_164_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGA_IS_GPIO
#define PAD_HOTPLUGA_IS_GPIO PIN_164_IS_GPIO
#endif 

#define PIN_165 PAD_IRIN
#define PAD_IRIN 9
#define GPIO_PAD_9 GPIO8
#ifndef PIN_165_IS_GPIO
#define PIN_165_IS_GPIO 0
#endif 
#ifndef PAD_IRIN_IS_GPIO
#define PAD_IRIN_IS_GPIO PIN_165_IS_GPIO
#endif 

#define PAD_GPIO_PM7 9999
#ifndef PAD_GPIO_PM7_IS_GPIO
#define PAD_GPIO_PM7_IS_GPIO 0
#endif 

#define PIN_166 PAD_DDCDA_CK
#define PAD_DDCDA_CK 31
#define GPIO_PAD_31 GPIO30
#ifndef PIN_166_IS_GPIO
#define PIN_166_IS_GPIO 0
#endif 
#ifndef PAD_DDCDA_CK_IS_GPIO
#define PAD_DDCDA_CK_IS_GPIO PIN_166_IS_GPIO
#endif 

#define PAD_PWM_PM 9999
#ifndef PAD_PWM_PM_IS_GPIO
#define PAD_PWM_PM_IS_GPIO 0
#endif 

#define PIN_167 PAD_DDCDA_DA
#define PAD_DDCDA_DA 32
#define GPIO_PAD_32 GPIO31
#ifndef PIN_167_IS_GPIO
#define PIN_167_IS_GPIO 0
#endif 
#ifndef PAD_DDCDA_DA_IS_GPIO
#define PAD_DDCDA_DA_IS_GPIO PIN_167_IS_GPIO
#endif 

#define PAD_GPIO_PM9 9999
#ifndef PAD_GPIO_PM9_IS_GPIO
#define PAD_GPIO_PM9_IS_GPIO 0
#endif 

#define PIN_168 PAD_CEC
#define PAD_CEC 10
#define GPIO_PAD_10 GPIO9
#ifndef PIN_168_IS_GPIO
#define PIN_168_IS_GPIO 0
#endif 
#ifndef PAD_CEC_IS_GPIO
#define PAD_CEC_IS_GPIO PIN_168_IS_GPIO
#endif 

#define PAD_GPIO_PM0 9999
#ifndef PAD_GPIO_PM0_IS_GPIO
#define PAD_GPIO_PM0_IS_GPIO 0
#endif 

#define PIN_169 PAD_DDCA_CK
#define PAD_DDCA_CK 45
#define GPIO_PAD_45 GPIO44
#ifndef PIN_169_IS_GPIO
#define PIN_169_IS_GPIO 0
#endif 
#ifndef PAD_DDCA_CK_IS_GPIO
#define PAD_DDCA_CK_IS_GPIO PIN_169_IS_GPIO
#endif 

#define PAD_GPIO_PM15 9999
#ifndef PAD_GPIO_PM15_IS_GPIO
#define PAD_GPIO_PM15_IS_GPIO 0
#endif 

#define PIN_170 PAD_DDCA_DA
#define PAD_DDCA_DA 46
#define GPIO_PAD_46 GPIO45
#ifndef PIN_170_IS_GPIO
#define PIN_170_IS_GPIO 0
#endif 
#ifndef PAD_DDCA_DA_IS_GPIO
#define PAD_DDCA_DA_IS_GPIO PIN_170_IS_GPIO
#endif 

#define PAD_GPIO_PM2 9999
#ifndef PAD_GPIO_PM2_IS_GPIO
#define PAD_GPIO_PM2_IS_GPIO 0
#endif 

#define PAD_GPIO_PM4 9999
#ifndef PAD_GPIO_PM4_IS_GPIO
#define PAD_GPIO_PM4_IS_GPIO 0
#endif 

#define PIN_172 PAD_GPIO_PM13
#define PAD_GPIO_PM13 24
#define GPIO_PAD_24 GPIO23
#ifndef PIN_172_IS_GPIO
#define PIN_172_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM13_IS_GPIO
#define PAD_GPIO_PM13_IS_GPIO PIN_172_IS_GPIO
#endif 

#define PAD_GPIO_PM5 9999
#ifndef PAD_GPIO_PM5_IS_GPIO
#define PAD_GPIO_PM5_IS_GPIO 0
#endif 

#define PIN_173 PAD_SAR0
#define PAD_SAR0 39
#define GPIO_PAD_39 GPIO38
#ifndef PIN_173_IS_GPIO
#define PIN_173_IS_GPIO 0
#endif 
#ifndef PAD_SAR0_IS_GPIO
#define PAD_SAR0_IS_GPIO PIN_173_IS_GPIO
#endif 

#define PIN_174 PAD_SAR1
#define PAD_SAR1 40
#define GPIO_PAD_40 GPIO39
#ifndef PIN_174_IS_GPIO
#define PIN_174_IS_GPIO 0
#endif 
#ifndef PAD_SAR1_IS_GPIO
#define PAD_SAR1_IS_GPIO PIN_174_IS_GPIO
#endif 

#define PIN_175 PAD_SAR2
#define PAD_SAR2 41
#define GPIO_PAD_41 GPIO40
#ifndef PIN_175_IS_GPIO
#define PIN_175_IS_GPIO 0
#endif 
#ifndef PAD_SAR2_IS_GPIO
#define PAD_SAR2_IS_GPIO PIN_175_IS_GPIO
#endif 

#define PAD_SAR3 9999
#ifndef PAD_SAR3_IS_GPIO
#define PAD_SAR3_IS_GPIO 0
#endif 

#define PAD_SAR4 9999
#ifndef PAD_SAR4_IS_GPIO
#define PAD_SAR4_IS_GPIO 0
#endif 

#define PAD_DDCDB_DA 9999
#ifndef PAD_DDCDB_DA_IS_GPIO
#define PAD_DDCDB_DA_IS_GPIO 0
#endif 

#define PIN_176 PAD_GPIO_PM14
#define PAD_GPIO_PM14 25
#define GPIO_PAD_25 GPIO24
#ifndef PIN_176_IS_GPIO
#define PIN_176_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM14_IS_GPIO
#define PAD_GPIO_PM14_IS_GPIO PIN_176_IS_GPIO
#endif 


// PADS group name to index
#define PADS_DDCR           1223
#define PADS_DDCR2          1224
#define PADS_TS0            1225
#define PADS_TS1            1226
#define PADS_GPIO1_GPIO2    1227
#define PADS_LHSYNC2_LVSYNC2 1228
#define PADS_PCI_AD20_AD21  1229
#define PADS_PCI            1230
#define PADS_PCM            1231
#define PADS_SAR            1232
#define PADS_DOUT           1233
#define PADS_DIN            1234
#define PADS_I2S            1235
#define PADS_PF             1236
#define PADS_EMAC           1237
#define PADS_TCON           1238
#define PADS_UART1_MODE1    1239
#define PADS_UART1_MODE2    1240
#define PADS_UART1_MODE3    1241
#define PADS_UART2_MODE1    1242
#define PADS_UART2_MODE2    1243
#define PADS_UART2_MODE3    1244
#define PADS_ET_MODE0       1245
#define PADS_ET_MODE1       1246
#define PADS_ET_MODE2       1247
#define PADS_ET_MODE3       1248
#define PADS_MIIC           1249
#define PADS_PF_MODE1       1250
#define PADS_PF_MODE2       1251
#define PADS_PF_MODE3       1252
#define PADS_SPI_CZ1        1253
#define PADS_SPI_CZ2        1254
#define PADS_SPI_CZ3        1255
#define PADS_DDCR3          1256

// chip capbilities
#define CHIP_HAS_BT656_IN          0
#define CHIP_HAS_TS0               1
#define CHIP_HAS_TS1               0
#define CHIP_HAS_LVDS_10BIT_X2     1
#define CHIP_HAS_LVDS_8BIT_X2      1
#define CHIP_HAS_LVDS_8BIT_X1      1
#define CHIP_HAS_CIMAX             0
#define CHIP_HAS_USB_P0            1
#define CHIP_HAS_USB_P1            1
#define CHIP_HAS_USBVBUS0          0
#define CHIP_HAS_USBVBUS1          0
#define CHIP_HAS_UART1_MODE1       1
#define CHIP_HAS_UART1_MODE2       1
#define CHIP_HAS_UART1_MODE3       1
#define CHIP_HAS_PCMCIA1           0
#define CHIP_HAS_PCMCIA2           0
#define CHIP_HAS_PCMCIA            0
#define CHIP_HAS_UART2_MODE1       1
#define CHIP_HAS_UART2_MODE2       1
#define CHIP_HAS_UART2_MODE3       1
#define CHIP_HAS_RGB_A             1
#define CHIP_HAS_RGB_B             1
#define CHIP_HAS_RGB_C             1
#define CHIP_HAS_HDMI_A            1
#define CHIP_HAS_HDMI_B            1
#define CHIP_HAS_HDMI_C            1
#define CHIP_HAS_SPI_CZ1           1
#define CHIP_HAS_SPI_CZ2           0
#define CHIP_HAS_SPI_CZ3           0
#define CHIP_HAS_DDCR              1
#define CHIP_HAS_DDCR2             1
#define CHIP_HAS_TCON              1
#define CHIP_HAS_ET_MODE0_MII      1
#define CHIP_HAS_ET_MODE0_RMII     1
#define CHIP_HAS_ET_MODE1_MII      1
#define CHIP_HAS_ET_MODE1_RMII     1
#define CHIP_HAS_ET_MODE2_MII      1
#define CHIP_HAS_ET_MODE2_RMII     1
#define CHIP_HAS_I2S_IN            1
#define CHIP_HAS_I2S_OUT           1
#define CHIP_HAS_SPDIF_IN          0
#define CHIP_HAS_SPDIF_OUT         1
#define CHIP_HAS_DDR_A_CMD         1
#define CHIP_HAS_DDR_A_DATA        1
#define CHIP_HAS_DDR_B_CMD         1
#define CHIP_HAS_DDR_B_DATA        1
#define CHIP_USE_PCM_CDN_IN_PCM2   0
#define CHIP_USE_I2S_IN_IN_PCM     0
#define CHIP_USE_I2S_OUT_IN_PCM    0
#define CHIP_USE_SPDIF_IN_IN_PCM   0
#define CHIP_USE_SPDIF_OUT_IN_PCM  0
#define CHIP_USE_IIC_IN_DDCR2      0
#define CHIP_USE_PWM2_IN_GPIO14    0
#define CHIP_USE_PWM3_IN_GPIO15    0

// chip additional information
#define CHIP_FAMILY_TYPE           CHIP_FAMILY_MUNICH

#endif /* _MSD93F0JMX_H_*/
