/* SPDX-License-Identifier: GPL-2.0-only OR BSD-3-Clause */
/******************************************************************************
 *
 * This file is provided under a dual license.  When you use or
 * distribute this software, you may choose to be licensed under
 * version 2 of the GNU General Public License ("GPLv2 License")
 * or BSD License.
 *
 * GPLv2 License
 *
 * Copyright(C) 2019 MediaTek Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of version 2 of the GNU General Public License as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See http://www.gnu.org/licenses/gpl-2.0.html for more details.
 *
 * BSD LICENSE
 *
 * Copyright(C) 2019 MediaTek Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *****************************************************************************/

// This file is generated by script file, please do not edit it directly 
#ifndef _MSD94BX8_H_
#define _MSD94BX8_H_

#define PAD_NC   9999
#define PAD_GND  0

#define BALL_F4 PAD_VID0
#define PAD_VID0 1
#define GPIO_PAD_1 GPIO0
#ifndef BALL_F4_IS_GPIO
#define BALL_F4_IS_GPIO 0
#endif 
#ifndef PAD_VID0_IS_GPIO
#define PAD_VID0_IS_GPIO BALL_F4_IS_GPIO
#endif 

#define BALL_J4 PAD_ARC0
#define PAD_ARC0 50
#define GPIO_PAD_50 GPIO49
#ifndef BALL_J4_IS_GPIO
#define BALL_J4_IS_GPIO 0
#endif 
#ifndef PAD_ARC0_IS_GPIO
#define PAD_ARC0_IS_GPIO BALL_J4_IS_GPIO
#endif 

#define BALL_AD4 PAD_TGPIO0
#define PAD_TGPIO0 140
#define GPIO_PAD_140 GPIO139
#ifndef BALL_AD4_IS_GPIO
#define BALL_AD4_IS_GPIO 0
#endif 
#ifndef PAD_TGPIO0_IS_GPIO
#define PAD_TGPIO0_IS_GPIO BALL_AD4_IS_GPIO
#endif 

#define BALL_AC4 PAD_TGPIO1
#define PAD_TGPIO1 141
#define GPIO_PAD_141 GPIO140
#ifndef BALL_AC4_IS_GPIO
#define BALL_AC4_IS_GPIO 0
#endif 
#ifndef PAD_TGPIO1_IS_GPIO
#define PAD_TGPIO1_IS_GPIO BALL_AC4_IS_GPIO
#endif 

#define PAD_TGPIO2 9999
#ifndef PAD_TGPIO2_IS_GPIO
#define PAD_TGPIO2_IS_GPIO 0
#endif 

#define PAD_TGPIO3 9999
#ifndef PAD_TGPIO3_IS_GPIO
#define PAD_TGPIO3_IS_GPIO 0
#endif 

#define BALL_AB9 PAD_TS2_D0
#define PAD_TS2_D0 167
#define GPIO_PAD_167 GPIO166
#ifndef BALL_AB9_IS_GPIO
#define BALL_AB9_IS_GPIO 0
#endif 
#ifndef PAD_TS2_D0_IS_GPIO
#define PAD_TS2_D0_IS_GPIO BALL_AB9_IS_GPIO
#endif 

#define BALL_AA9 PAD_TS2_D1
#define PAD_TS2_D1 168
#define GPIO_PAD_168 GPIO167
#ifndef BALL_AA9_IS_GPIO
#define BALL_AA9_IS_GPIO 0
#endif 
#ifndef PAD_TS2_D1_IS_GPIO
#define PAD_TS2_D1_IS_GPIO BALL_AA9_IS_GPIO
#endif 

#define BALL_Y17 PAD_PCM_D3
#define PAD_PCM_D3 116
#define GPIO_PAD_116 GPIO115
#ifndef BALL_Y17_IS_GPIO
#define BALL_Y17_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D3_IS_GPIO
#define PAD_PCM_D3_IS_GPIO BALL_Y17_IS_GPIO
#endif 

#define BALL_AA17 PAD_PCM_D7
#define PAD_PCM_D7 120
#define GPIO_PAD_120 GPIO119
#ifndef BALL_AA17_IS_GPIO
#define BALL_AA17_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D7_IS_GPIO
#define PAD_PCM_D7_IS_GPIO BALL_AA17_IS_GPIO
#endif 

#define BALL_W19 PAD_PCM_IORD_N
#define PAD_PCM_IORD_N 121
#define GPIO_PAD_121 GPIO120
#ifndef BALL_W19_IS_GPIO
#define BALL_W19_IS_GPIO 0
#endif 
#ifndef PAD_PCM_IORD_N_IS_GPIO
#define PAD_PCM_IORD_N_IS_GPIO BALL_W19_IS_GPIO
#endif 

#define BALL_W20 PAD_PCM_WAIT_N
#define PAD_PCM_WAIT_N 127
#define GPIO_PAD_127 GPIO126
#ifndef BALL_W20_IS_GPIO
#define BALL_W20_IS_GPIO 0
#endif 
#ifndef PAD_PCM_WAIT_N_IS_GPIO
#define PAD_PCM_WAIT_N_IS_GPIO BALL_W20_IS_GPIO
#endif 

#define BALL_W21 PAD_PCM_A4
#define PAD_PCM_A4 100
#define GPIO_PAD_100 GPIO99
#ifndef BALL_W21_IS_GPIO
#define BALL_W21_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A4_IS_GPIO
#define PAD_PCM_A4_IS_GPIO BALL_W21_IS_GPIO
#endif 

#define BALL_AA10 PAD_PCM2_RESET
#define PAD_PCM2_RESET 94
#define GPIO_PAD_94 GPIO93
#ifndef BALL_AA10_IS_GPIO
#define BALL_AA10_IS_GPIO 0
#endif 
#ifndef PAD_PCM2_RESET_IS_GPIO
#define PAD_PCM2_RESET_IS_GPIO BALL_AA10_IS_GPIO
#endif 

#define BALL_AB19 PAD_PCM_A11
#define PAD_PCM_A11 107
#define GPIO_PAD_107 GPIO106
#ifndef BALL_AB19_IS_GPIO
#define BALL_AB19_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A11_IS_GPIO
#define PAD_PCM_A11_IS_GPIO BALL_AB19_IS_GPIO
#endif 

#define BALL_AB10 PAD_PCM2_IRQA_N
#define PAD_PCM2_IRQA_N 93
#define GPIO_PAD_93 GPIO92
#ifndef BALL_AB10_IS_GPIO
#define BALL_AB10_IS_GPIO 0
#endif 
#ifndef PAD_PCM2_IRQA_N_IS_GPIO
#define PAD_PCM2_IRQA_N_IS_GPIO BALL_AB10_IS_GPIO
#endif 

#define PAD_PCM2_CE_N 9999
#ifndef PAD_PCM2_CE_N_IS_GPIO
#define PAD_PCM2_CE_N_IS_GPIO 0
#endif 

#define BALL_Y18 PAD_PCM_A10
#define PAD_PCM_A10 106
#define GPIO_PAD_106 GPIO105
#ifndef BALL_Y18_IS_GPIO
#define BALL_Y18_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A10_IS_GPIO
#define PAD_PCM_A10_IS_GPIO BALL_Y18_IS_GPIO
#endif 

#define BALL_AA22 PAD_PCM_IRQA_N
#define PAD_PCM_IRQA_N 123
#define GPIO_PAD_123 GPIO122
#ifndef BALL_AA22_IS_GPIO
#define BALL_AA22_IS_GPIO 0
#endif 
#ifndef PAD_PCM_IRQA_N_IS_GPIO
#define PAD_PCM_IRQA_N_IS_GPIO BALL_AA22_IS_GPIO
#endif 

#define BALL_AA18 PAD_PCM_CE_N
#define PAD_PCM_CE_N 112
#define GPIO_PAD_112 GPIO111
#ifndef BALL_AA18_IS_GPIO
#define BALL_AA18_IS_GPIO 0
#endif 
#ifndef PAD_PCM_CE_N_IS_GPIO
#define PAD_PCM_CE_N_IS_GPIO BALL_AA18_IS_GPIO
#endif 

#define BALL_AA20 PAD_PCM_A8
#define PAD_PCM_A8 104
#define GPIO_PAD_104 GPIO103
#ifndef BALL_AA20_IS_GPIO
#define BALL_AA20_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A8_IS_GPIO
#define PAD_PCM_A8_IS_GPIO BALL_AA20_IS_GPIO
#endif 

#define BALL_Y20 PAD_PCM_A7
#define PAD_PCM_A7 103
#define GPIO_PAD_103 GPIO102
#ifndef BALL_Y20_IS_GPIO
#define BALL_Y20_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A7_IS_GPIO
#define PAD_PCM_A7_IS_GPIO BALL_Y20_IS_GPIO
#endif 

#define BALL_Y21 PAD_PCM_A5
#define PAD_PCM_A5 101
#define GPIO_PAD_101 GPIO100
#ifndef BALL_Y21_IS_GPIO
#define BALL_Y21_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A5_IS_GPIO
#define PAD_PCM_A5_IS_GPIO BALL_Y21_IS_GPIO
#endif 

#define BALL_Y19 PAD_PCM_OE_N
#define PAD_PCM_OE_N 124
#define GPIO_PAD_124 GPIO123
#ifndef BALL_Y19_IS_GPIO
#define BALL_Y19_IS_GPIO 0
#endif 
#ifndef PAD_PCM_OE_N_IS_GPIO
#define PAD_PCM_OE_N_IS_GPIO BALL_Y19_IS_GPIO
#endif 

#define BALL_AA21 PAD_PCM_A14
#define PAD_PCM_A14 110
#define GPIO_PAD_110 GPIO109
#ifndef BALL_AA21_IS_GPIO
#define BALL_AA21_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A14_IS_GPIO
#define PAD_PCM_A14_IS_GPIO BALL_AA21_IS_GPIO
#endif 

#define BALL_AA19 PAD_PCM_IOWR_N
#define PAD_PCM_IOWR_N 122
#define GPIO_PAD_122 GPIO121
#ifndef BALL_AA19_IS_GPIO
#define BALL_AA19_IS_GPIO 0
#endif 
#ifndef PAD_PCM_IOWR_N_IS_GPIO
#define PAD_PCM_IOWR_N_IS_GPIO BALL_AA19_IS_GPIO
#endif 

#define BALL_V21 PAD_PCM_REG_N
#define PAD_PCM_REG_N 125
#define GPIO_PAD_125 GPIO124
#ifndef BALL_V21_IS_GPIO
#define BALL_V21_IS_GPIO 0
#endif 
#ifndef PAD_PCM_REG_N_IS_GPIO
#define PAD_PCM_REG_N_IS_GPIO BALL_V21_IS_GPIO
#endif 

#define PAD_TS2_VLD 9999
#ifndef PAD_TS2_VLD_IS_GPIO
#define PAD_TS2_VLD_IS_GPIO 0
#endif 

#define PAD_TS2_SYNC 9999
#ifndef PAD_TS2_SYNC_IS_GPIO
#define PAD_TS2_SYNC_IS_GPIO 0
#endif 

#define PAD_TS2_CLK 9999
#ifndef PAD_TS2_CLK_IS_GPIO
#define PAD_TS2_CLK_IS_GPIO 0
#endif 

#define BALL_AC18 PAD_TS1_D5
#define PAD_TS1_D5 161
#define GPIO_PAD_161 GPIO160
#ifndef BALL_AC18_IS_GPIO
#define BALL_AC18_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D5_IS_GPIO
#define PAD_TS1_D5_IS_GPIO BALL_AC18_IS_GPIO
#endif 

#define BALL_Y10 PAD_TS2_D2
#define PAD_TS2_D2 169
#define GPIO_PAD_169 GPIO168
#ifndef BALL_Y10_IS_GPIO
#define BALL_Y10_IS_GPIO 0
#endif 
#ifndef PAD_TS2_D2_IS_GPIO
#define PAD_TS2_D2_IS_GPIO BALL_Y10_IS_GPIO
#endif 

#define BALL_AD18 PAD_TS1_D4
#define PAD_TS1_D4 160
#define GPIO_PAD_160 GPIO159
#ifndef BALL_AD18_IS_GPIO
#define BALL_AD18_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D4_IS_GPIO
#define PAD_TS1_D4_IS_GPIO BALL_AD18_IS_GPIO
#endif 

#define BALL_Y9 PAD_TS2_D3
#define PAD_TS2_D3 170
#define GPIO_PAD_170 GPIO169
#ifndef BALL_Y9_IS_GPIO
#define BALL_Y9_IS_GPIO 0
#endif 
#ifndef PAD_TS2_D3_IS_GPIO
#define PAD_TS2_D3_IS_GPIO BALL_Y9_IS_GPIO
#endif 

#define BALL_AC16 PAD_TS1_D0
#define PAD_TS1_D0 156
#define GPIO_PAD_156 GPIO155
#ifndef BALL_AC16_IS_GPIO
#define BALL_AC16_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D0_IS_GPIO
#define PAD_TS1_D0_IS_GPIO BALL_AC16_IS_GPIO
#endif 

#define BALL_AC15 PAD_TS1_VLD
#define PAD_TS1_VLD 165
#define GPIO_PAD_165 GPIO164
#ifndef BALL_AC15_IS_GPIO
#define BALL_AC15_IS_GPIO 0
#endif 
#ifndef PAD_TS1_VLD_IS_GPIO
#define PAD_TS1_VLD_IS_GPIO BALL_AC15_IS_GPIO
#endif 

#define BALL_U20 PAD_PCM_A1
#define PAD_PCM_A1 97
#define GPIO_PAD_97 GPIO96
#ifndef BALL_U20_IS_GPIO
#define BALL_U20_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A1_IS_GPIO
#define PAD_PCM_A1_IS_GPIO BALL_U20_IS_GPIO
#endif 

#define BALL_W22 PAD_PCM_RESET
#define PAD_PCM_RESET 126
#define GPIO_PAD_126 GPIO125
#ifndef BALL_W22_IS_GPIO
#define BALL_W22_IS_GPIO 0
#endif 
#ifndef PAD_PCM_RESET_IS_GPIO
#define PAD_PCM_RESET_IS_GPIO BALL_W22_IS_GPIO
#endif 

#define BALL_U21 PAD_PCM_A2
#define PAD_PCM_A2 98
#define GPIO_PAD_98 GPIO97
#ifndef BALL_U21_IS_GPIO
#define BALL_U21_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A2_IS_GPIO
#define PAD_PCM_A2_IS_GPIO BALL_U21_IS_GPIO
#endif 

#define BALL_T20 PAD_PCM_A0
#define PAD_PCM_A0 96
#define GPIO_PAD_96 GPIO95
#ifndef BALL_T20_IS_GPIO
#define BALL_T20_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A0_IS_GPIO
#define PAD_PCM_A0_IS_GPIO BALL_T20_IS_GPIO
#endif 

#define BALL_U22 PAD_PCM_A3
#define PAD_PCM_A3 99
#define GPIO_PAD_99 GPIO98
#ifndef BALL_U22_IS_GPIO
#define BALL_U22_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A3_IS_GPIO
#define PAD_PCM_A3_IS_GPIO BALL_U22_IS_GPIO
#endif 

#define BALL_AB20 PAD_PCM_A9
#define PAD_PCM_A9 105
#define GPIO_PAD_105 GPIO104
#ifndef BALL_AB20_IS_GPIO
#define BALL_AB20_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A9_IS_GPIO
#define PAD_PCM_A9_IS_GPIO BALL_AB20_IS_GPIO
#endif 

#define BALL_T21 PAD_PCM_D2
#define PAD_PCM_D2 115
#define GPIO_PAD_115 GPIO114
#ifndef BALL_T21_IS_GPIO
#define BALL_T21_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D2_IS_GPIO
#define PAD_PCM_D2_IS_GPIO BALL_T21_IS_GPIO
#endif 

#define BALL_AA16 PAD_PCM_D5
#define PAD_PCM_D5 118
#define GPIO_PAD_118 GPIO117
#ifndef BALL_AA16_IS_GPIO
#define BALL_AA16_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D5_IS_GPIO
#define PAD_PCM_D5_IS_GPIO BALL_AA16_IS_GPIO
#endif 

#define PAD_PCM2_CD_N 9999
#ifndef PAD_PCM2_CD_N_IS_GPIO
#define PAD_PCM2_CD_N_IS_GPIO 0
#endif 

#define BALL_AB17 PAD_PCM_D4
#define PAD_PCM_D4 117
#define GPIO_PAD_117 GPIO116
#ifndef BALL_AB17_IS_GPIO
#define BALL_AB17_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D4_IS_GPIO
#define PAD_PCM_D4_IS_GPIO BALL_AB17_IS_GPIO
#endif 

#define BALL_AB21 PAD_PCM_A13
#define PAD_PCM_A13 109
#define GPIO_PAD_109 GPIO108
#ifndef BALL_AB21_IS_GPIO
#define BALL_AB21_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A13_IS_GPIO
#define PAD_PCM_A13_IS_GPIO BALL_AB21_IS_GPIO
#endif 

#define BALL_Y22 PAD_PCM_A6
#define PAD_PCM_A6 102
#define GPIO_PAD_102 GPIO101
#ifndef BALL_Y22_IS_GPIO
#define BALL_Y22_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A6_IS_GPIO
#define PAD_PCM_A6_IS_GPIO BALL_Y22_IS_GPIO
#endif 

#define PAD_PCM2_WAIT_N 9999
#ifndef PAD_PCM2_WAIT_N_IS_GPIO
#define PAD_PCM2_WAIT_N_IS_GPIO 0
#endif 

#define BALL_AB22 PAD_PCM_WE_N
#define PAD_PCM_WE_N 128
#define GPIO_PAD_128 GPIO127
#ifndef BALL_AB22_IS_GPIO
#define BALL_AB22_IS_GPIO 0
#endif 
#ifndef PAD_PCM_WE_N_IS_GPIO
#define PAD_PCM_WE_N_IS_GPIO BALL_AB22_IS_GPIO
#endif 

#define BALL_P22 PAD_PCM_CD_N
#define PAD_PCM_CD_N 111
#define GPIO_PAD_111 GPIO110
#ifndef BALL_P22_IS_GPIO
#define BALL_P22_IS_GPIO 0
#endif 
#ifndef PAD_PCM_CD_N_IS_GPIO
#define PAD_PCM_CD_N_IS_GPIO BALL_P22_IS_GPIO
#endif 

#define BALL_AB23 PAD_PCM_A12
#define PAD_PCM_A12 108
#define GPIO_PAD_108 GPIO107
#ifndef BALL_AB23_IS_GPIO
#define BALL_AB23_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A12_IS_GPIO
#define PAD_PCM_A12_IS_GPIO BALL_AB23_IS_GPIO
#endif 

#define BALL_AC19 PAD_TS0_VLD
#define PAD_TS0_VLD 154
#define GPIO_PAD_154 GPIO153
#ifndef BALL_AC19_IS_GPIO
#define BALL_AC19_IS_GPIO 0
#endif 
#ifndef PAD_TS0_VLD_IS_GPIO
#define PAD_TS0_VLD_IS_GPIO BALL_AC19_IS_GPIO
#endif 

#define BALL_AC21 PAD_TS0_D2
#define PAD_TS0_D2 147
#define GPIO_PAD_147 GPIO146
#ifndef BALL_AC21_IS_GPIO
#define BALL_AC21_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D2_IS_GPIO
#define PAD_TS0_D2_IS_GPIO BALL_AC21_IS_GPIO
#endif 

#define BALL_AD20 PAD_TS0_SYNC
#define PAD_TS0_SYNC 153
#define GPIO_PAD_153 GPIO152
#ifndef BALL_AD20_IS_GPIO
#define BALL_AD20_IS_GPIO 0
#endif 
#ifndef PAD_TS0_SYNC_IS_GPIO
#define PAD_TS0_SYNC_IS_GPIO BALL_AD20_IS_GPIO
#endif 

#define BALL_AD21 PAD_TS0_D1
#define PAD_TS0_D1 146
#define GPIO_PAD_146 GPIO145
#ifndef BALL_AD21_IS_GPIO
#define BALL_AD21_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D1_IS_GPIO
#define PAD_TS0_D1_IS_GPIO BALL_AD21_IS_GPIO
#endif 

#define BALL_AE20 PAD_TS0_CLK
#define PAD_TS0_CLK 144
#define GPIO_PAD_144 GPIO143
#ifndef BALL_AE20_IS_GPIO
#define BALL_AE20_IS_GPIO 0
#endif 
#ifndef PAD_TS0_CLK_IS_GPIO
#define PAD_TS0_CLK_IS_GPIO BALL_AE20_IS_GPIO
#endif 

#define BALL_AE22 PAD_TS0_D4
#define PAD_TS0_D4 149
#define GPIO_PAD_149 GPIO148
#ifndef BALL_AE22_IS_GPIO
#define BALL_AE22_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D4_IS_GPIO
#define PAD_TS0_D4_IS_GPIO BALL_AE22_IS_GPIO
#endif 

#define BALL_AE23 PAD_TS0_D6
#define PAD_TS0_D6 151
#define GPIO_PAD_151 GPIO150
#ifndef BALL_AE23_IS_GPIO
#define BALL_AE23_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D6_IS_GPIO
#define PAD_TS0_D6_IS_GPIO BALL_AE23_IS_GPIO
#endif 

#define BALL_AC20 PAD_TS0_D0
#define PAD_TS0_D0 145
#define GPIO_PAD_145 GPIO144
#ifndef BALL_AC20_IS_GPIO
#define BALL_AC20_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D0_IS_GPIO
#define PAD_TS0_D0_IS_GPIO BALL_AC20_IS_GPIO
#endif 

#define BALL_AD22 PAD_TS0_D3
#define PAD_TS0_D3 148
#define GPIO_PAD_148 GPIO147
#ifndef BALL_AD22_IS_GPIO
#define BALL_AD22_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D3_IS_GPIO
#define PAD_TS0_D3_IS_GPIO BALL_AD22_IS_GPIO
#endif 

#define BALL_AD23 PAD_TS0_D7
#define PAD_TS0_D7 152
#define GPIO_PAD_152 GPIO151
#ifndef BALL_AD23_IS_GPIO
#define BALL_AD23_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D7_IS_GPIO
#define PAD_TS0_D7_IS_GPIO BALL_AD23_IS_GPIO
#endif 

#define BALL_AC22 PAD_TS0_D5
#define PAD_TS0_D5 150
#define GPIO_PAD_150 GPIO149
#ifndef BALL_AC22_IS_GPIO
#define BALL_AC22_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D5_IS_GPIO
#define PAD_TS0_D5_IS_GPIO BALL_AC22_IS_GPIO
#endif 

#define BALL_AE16 PAD_TS1_SYNC
#define PAD_TS1_SYNC 164
#define GPIO_PAD_164 GPIO163
#ifndef BALL_AE16_IS_GPIO
#define BALL_AE16_IS_GPIO 0
#endif 
#ifndef PAD_TS1_SYNC_IS_GPIO
#define PAD_TS1_SYNC_IS_GPIO BALL_AE16_IS_GPIO
#endif 

#define BALL_AD17 PAD_TS1_D2
#define PAD_TS1_D2 158
#define GPIO_PAD_158 GPIO157
#ifndef BALL_AD17_IS_GPIO
#define BALL_AD17_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D2_IS_GPIO
#define PAD_TS1_D2_IS_GPIO BALL_AD17_IS_GPIO
#endif 

#define BALL_AD16 PAD_TS1_CLK
#define PAD_TS1_CLK 155
#define GPIO_PAD_155 GPIO154
#ifndef BALL_AD16_IS_GPIO
#define BALL_AD16_IS_GPIO 0
#endif 
#ifndef PAD_TS1_CLK_IS_GPIO
#define PAD_TS1_CLK_IS_GPIO BALL_AD16_IS_GPIO
#endif 

#define BALL_AC17 PAD_TS1_D3
#define PAD_TS1_D3 159
#define GPIO_PAD_159 GPIO158
#ifndef BALL_AC17_IS_GPIO
#define BALL_AC17_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D3_IS_GPIO
#define PAD_TS1_D3_IS_GPIO BALL_AC17_IS_GPIO
#endif 

#define BALL_AE17 PAD_TS1_D1
#define PAD_TS1_D1 157
#define GPIO_PAD_157 GPIO156
#ifndef BALL_AE17_IS_GPIO
#define BALL_AE17_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D1_IS_GPIO
#define PAD_TS1_D1_IS_GPIO BALL_AE17_IS_GPIO
#endif 

#define BALL_P21 PAD_TS2_D7
#define PAD_TS2_D7 174
#define GPIO_PAD_174 GPIO173
#ifndef BALL_P21_IS_GPIO
#define BALL_P21_IS_GPIO 0
#endif 
#ifndef PAD_TS2_D7_IS_GPIO
#define PAD_TS2_D7_IS_GPIO BALL_P21_IS_GPIO
#endif 

#define BALL_N20 PAD_TS2_D4
#define PAD_TS2_D4 171
#define GPIO_PAD_171 GPIO170
#ifndef BALL_N20_IS_GPIO
#define BALL_N20_IS_GPIO 0
#endif 
#ifndef PAD_TS2_D4_IS_GPIO
#define PAD_TS2_D4_IS_GPIO BALL_N20_IS_GPIO
#endif 

#define BALL_R21 PAD_TS2_D5
#define PAD_TS2_D5 172
#define GPIO_PAD_172 GPIO171
#ifndef BALL_R21_IS_GPIO
#define BALL_R21_IS_GPIO 0
#endif 
#ifndef PAD_TS2_D5_IS_GPIO
#define PAD_TS2_D5_IS_GPIO BALL_R21_IS_GPIO
#endif 

#define BALL_P20 PAD_TS2_D6
#define PAD_TS2_D6 173
#define GPIO_PAD_173 GPIO172
#ifndef BALL_P20_IS_GPIO
#define BALL_P20_IS_GPIO 0
#endif 
#ifndef PAD_TS2_D6_IS_GPIO
#define PAD_TS2_D6_IS_GPIO BALL_P20_IS_GPIO
#endif 

#define BALL_AE19 PAD_TS1_D7
#define PAD_TS1_D7 163
#define GPIO_PAD_163 GPIO162
#ifndef BALL_AE19_IS_GPIO
#define BALL_AE19_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D7_IS_GPIO
#define PAD_TS1_D7_IS_GPIO BALL_AE19_IS_GPIO
#endif 

#define BALL_AD19 PAD_TS1_D6
#define PAD_TS1_D6 162
#define GPIO_PAD_162 GPIO161
#ifndef BALL_AD19_IS_GPIO
#define BALL_AD19_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D6_IS_GPIO
#define PAD_TS1_D6_IS_GPIO BALL_AD19_IS_GPIO
#endif 

#define BALL_R22 PAD_PCM_D1
#define PAD_PCM_D1 114
#define GPIO_PAD_114 GPIO113
#ifndef BALL_R22_IS_GPIO
#define BALL_R22_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D1_IS_GPIO
#define PAD_PCM_D1_IS_GPIO BALL_R22_IS_GPIO
#endif 

#define BALL_AB18 PAD_PCM_D6
#define PAD_PCM_D6 119
#define GPIO_PAD_119 GPIO118
#ifndef BALL_AB18_IS_GPIO
#define BALL_AB18_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D6_IS_GPIO
#define PAD_PCM_D6_IS_GPIO BALL_AB18_IS_GPIO
#endif 

#define BALL_R20 PAD_PCM_D0
#define PAD_PCM_D0 113
#define GPIO_PAD_113 GPIO112
#ifndef BALL_R20_IS_GPIO
#define BALL_R20_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D0_IS_GPIO
#define PAD_PCM_D0_IS_GPIO BALL_R20_IS_GPIO
#endif 

#define BALL_E8 PAD_I2S_OUT_SD
#define PAD_I2S_OUT_SD 86
#define GPIO_PAD_86 GPIO85
#ifndef BALL_E8_IS_GPIO
#define BALL_E8_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_SD_IS_GPIO
#define PAD_I2S_OUT_SD_IS_GPIO BALL_E8_IS_GPIO
#endif 

#define BALL_F8 PAD_I2S_OUT_MCK
#define PAD_I2S_OUT_MCK 85
#define GPIO_PAD_85 GPIO84
#ifndef BALL_F8_IS_GPIO
#define BALL_F8_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_MCK_IS_GPIO
#define PAD_I2S_OUT_MCK_IS_GPIO BALL_F8_IS_GPIO
#endif 

#define PAD_I2S_OUT_SD1 9999
#ifndef PAD_I2S_OUT_SD1_IS_GPIO
#define PAD_I2S_OUT_SD1_IS_GPIO 0
#endif 

#define BALL_D8 PAD_I2S_OUT_WS
#define PAD_I2S_OUT_WS 90
#define GPIO_PAD_90 GPIO89
#ifndef BALL_D8_IS_GPIO
#define BALL_D8_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_WS_IS_GPIO
#define PAD_I2S_OUT_WS_IS_GPIO BALL_D8_IS_GPIO
#endif 

#define PAD_I2S_OUT_SD2 9999
#ifndef PAD_I2S_OUT_SD2_IS_GPIO
#define PAD_I2S_OUT_SD2_IS_GPIO 0
#endif 

#define BALL_D9 PAD_I2S_OUT_BCK
#define PAD_I2S_OUT_BCK 84
#define GPIO_PAD_84 GPIO83
#ifndef BALL_D9_IS_GPIO
#define BALL_D9_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_BCK_IS_GPIO
#define PAD_I2S_OUT_BCK_IS_GPIO BALL_D9_IS_GPIO
#endif 

#define PAD_I2S_OUT_SD3 9999
#ifndef PAD_I2S_OUT_SD3_IS_GPIO
#define PAD_I2S_OUT_SD3_IS_GPIO 0
#endif 

#define BALL_D10 PAD_SPDIF_OUT
#define PAD_SPDIF_OUT 135
#define GPIO_PAD_135 GPIO134
#ifndef BALL_D10_IS_GPIO
#define BALL_D10_IS_GPIO 0
#endif 
#ifndef PAD_SPDIF_OUT_IS_GPIO
#define PAD_SPDIF_OUT_IS_GPIO BALL_D10_IS_GPIO
#endif 

#define PAD_GPIO15 9999
#ifndef PAD_GPIO15_IS_GPIO
#define PAD_GPIO15_IS_GPIO 0
#endif 

#define BALL_N21 PAD_PWM1
#define PAD_PWM1 130
#define GPIO_PAD_130 GPIO129
#ifndef BALL_N21_IS_GPIO
#define BALL_N21_IS_GPIO 0
#endif 
#ifndef PAD_PWM1_IS_GPIO
#define PAD_PWM1_IS_GPIO BALL_N21_IS_GPIO
#endif 

#define BALL_E10 PAD_SPDIF_IN
#define PAD_SPDIF_IN 134
#define GPIO_PAD_134 GPIO133
#ifndef BALL_E10_IS_GPIO
#define BALL_E10_IS_GPIO 0
#endif 
#ifndef PAD_SPDIF_IN_IS_GPIO
#define PAD_SPDIF_IN_IS_GPIO BALL_E10_IS_GPIO
#endif 

#define PAD_GPIO14 9999
#ifndef PAD_GPIO14_IS_GPIO
#define PAD_GPIO14_IS_GPIO 0
#endif 

#define PAD_GPIO18 9999
#ifndef PAD_GPIO18_IS_GPIO
#define PAD_GPIO18_IS_GPIO 0
#endif 

#define PAD_GPIO17 9999
#ifndef PAD_GPIO17_IS_GPIO
#define PAD_GPIO17_IS_GPIO 0
#endif 

#define PAD_UART_RX2 9999
#ifndef PAD_UART_RX2_IS_GPIO
#define PAD_UART_RX2_IS_GPIO 0
#endif 

#define PAD_UART_TX2 9999
#ifndef PAD_UART_TX2_IS_GPIO
#define PAD_UART_TX2_IS_GPIO 0
#endif 

#define PAD_GPIO1 9999
#ifndef PAD_GPIO1_IS_GPIO
#define PAD_GPIO1_IS_GPIO 0
#endif 

#define PAD_GPIO25 9999
#ifndef PAD_GPIO25_IS_GPIO
#define PAD_GPIO25_IS_GPIO 0
#endif 

#define BALL_N22 PAD_PWM0
#define PAD_PWM0 129
#define GPIO_PAD_129 GPIO128
#ifndef BALL_N22_IS_GPIO
#define BALL_N22_IS_GPIO 0
#endif 
#ifndef PAD_PWM0_IS_GPIO
#define PAD_PWM0_IS_GPIO BALL_N22_IS_GPIO
#endif 

#define PAD_GPIO6 9999
#ifndef PAD_GPIO6_IS_GPIO
#define PAD_GPIO6_IS_GPIO 0
#endif 

#define PAD_GPIO2 9999
#ifndef PAD_GPIO2_IS_GPIO
#define PAD_GPIO2_IS_GPIO 0
#endif 

#define PAD_PWM2 9999
#ifndef PAD_PWM2_IS_GPIO
#define PAD_PWM2_IS_GPIO 0
#endif 

#define BALL_F9 PAD_DDCR_DA
#define PAD_DDCR_DA 52
#define GPIO_PAD_52 GPIO51
#ifndef BALL_F9_IS_GPIO
#define BALL_F9_IS_GPIO 0
#endif 
#ifndef PAD_DDCR_DA_IS_GPIO
#define PAD_DDCR_DA_IS_GPIO BALL_F9_IS_GPIO
#endif 

#define BALL_E9 PAD_DDCR_CK
#define PAD_DDCR_CK 51
#define GPIO_PAD_51 GPIO50
#ifndef BALL_E9_IS_GPIO
#define BALL_E9_IS_GPIO 0
#endif 
#ifndef PAD_DDCR_CK_IS_GPIO
#define PAD_DDCR_CK_IS_GPIO BALL_E9_IS_GPIO
#endif 

#define PAD_GPIO26 9999
#ifndef PAD_GPIO26_IS_GPIO
#define PAD_GPIO26_IS_GPIO 0
#endif 

#define PAD_GPIO7 9999
#ifndef PAD_GPIO7_IS_GPIO
#define PAD_GPIO7_IS_GPIO 0
#endif 

#define PAD_GPIO16 9999
#ifndef PAD_GPIO16_IS_GPIO
#define PAD_GPIO16_IS_GPIO 0
#endif 

#define PAD_GPIO19 9999
#ifndef PAD_GPIO19_IS_GPIO
#define PAD_GPIO19_IS_GPIO 0
#endif 

#define PAD_I2S_IN_WS 9999
#ifndef PAD_I2S_IN_WS_IS_GPIO
#define PAD_I2S_IN_WS_IS_GPIO 0
#endif 

#define PAD_GPIO9 9999
#ifndef PAD_GPIO9_IS_GPIO
#define PAD_GPIO9_IS_GPIO 0
#endif 

#define PAD_GPIO0 9999
#ifndef PAD_GPIO0_IS_GPIO
#define PAD_GPIO0_IS_GPIO 0
#endif 

#define PAD_I2S_IN_SD 9999
#ifndef PAD_I2S_IN_SD_IS_GPIO
#define PAD_I2S_IN_SD_IS_GPIO 0
#endif 

#define PAD_I2S_IN_BCK 9999
#ifndef PAD_I2S_IN_BCK_IS_GPIO
#define PAD_I2S_IN_BCK_IS_GPIO 0
#endif 

#define PAD_VSYNC_LIKE 9999
#ifndef PAD_VSYNC_LIKE_IS_GPIO
#define PAD_VSYNC_LIKE_IS_GPIO 0
#endif 

#define PAD_PWM3 9999
#ifndef PAD_PWM3_IS_GPIO
#define PAD_PWM3_IS_GPIO 0
#endif 

#define PAD_GPIO10 9999
#ifndef PAD_GPIO10_IS_GPIO
#define PAD_GPIO10_IS_GPIO 0
#endif 

#define PAD_GPIO27 9999
#ifndef PAD_GPIO27_IS_GPIO
#define PAD_GPIO27_IS_GPIO 0
#endif 

#define PAD_PWM4 9999
#ifndef PAD_PWM4_IS_GPIO
#define PAD_PWM4_IS_GPIO 0
#endif 

#define PAD_GPIO5 9999
#ifndef PAD_GPIO5_IS_GPIO
#define PAD_GPIO5_IS_GPIO 0
#endif 

#define PAD_GPIO8 9999
#ifndef PAD_GPIO8_IS_GPIO
#define PAD_GPIO8_IS_GPIO 0
#endif 

#define PAD_GPIO20 9999
#ifndef PAD_GPIO20_IS_GPIO
#define PAD_GPIO20_IS_GPIO 0
#endif 

#define PAD_GPIO24 9999
#ifndef PAD_GPIO24_IS_GPIO
#define PAD_GPIO24_IS_GPIO 0
#endif 

#define PAD_GPIO21 9999
#ifndef PAD_GPIO21_IS_GPIO
#define PAD_GPIO21_IS_GPIO 0
#endif 

#define PAD_GPIO23 9999
#ifndef PAD_GPIO23_IS_GPIO
#define PAD_GPIO23_IS_GPIO 0
#endif 

#define PAD_GPIO22 9999
#ifndef PAD_GPIO22_IS_GPIO
#define PAD_GPIO22_IS_GPIO 0
#endif 

#define PAD_GPIO3 9999
#ifndef PAD_GPIO3_IS_GPIO
#define PAD_GPIO3_IS_GPIO 0
#endif 

#define BALL_AA1 PAD_GPIO13
#define PAD_GPIO13 66
#define GPIO_PAD_66 GPIO65
#ifndef BALL_AA1_IS_GPIO
#define BALL_AA1_IS_GPIO 0
#endif 
#ifndef PAD_GPIO13_IS_GPIO
#define PAD_GPIO13_IS_GPIO BALL_AA1_IS_GPIO
#endif 

#define PAD_GPIO12 9999
#ifndef PAD_GPIO12_IS_GPIO
#define PAD_GPIO12_IS_GPIO 0
#endif 

#define PAD_SPI1_CK 9999
#ifndef PAD_SPI1_CK_IS_GPIO
#define PAD_SPI1_CK_IS_GPIO 0
#endif 

#define PAD_SPI1_DI 9999
#ifndef PAD_SPI1_DI_IS_GPIO
#define PAD_SPI1_DI_IS_GPIO 0
#endif 

#define PAD_SPI2_CK 9999
#ifndef PAD_SPI2_CK_IS_GPIO
#define PAD_SPI2_CK_IS_GPIO 0
#endif 

#define PAD_SPI2_DI 9999
#ifndef PAD_SPI2_DI_IS_GPIO
#define PAD_SPI2_DI_IS_GPIO 0
#endif 

#define PAD_GPIO4 9999
#ifndef PAD_GPIO4_IS_GPIO
#define PAD_GPIO4_IS_GPIO 0
#endif 

#define PAD_GPIO11 9999
#ifndef PAD_GPIO11_IS_GPIO
#define PAD_GPIO11_IS_GPIO 0
#endif 

#define BALL_E4 PAD_SAR0
#define PAD_SAR0 44
#define GPIO_PAD_44 GPIO43
#ifndef BALL_E4_IS_GPIO
#define BALL_E4_IS_GPIO 0
#endif 
#ifndef PAD_SAR0_IS_GPIO
#define PAD_SAR0_IS_GPIO BALL_E4_IS_GPIO
#endif 

#define BALL_B7 PAD_SAR1
#define PAD_SAR1 45
#define GPIO_PAD_45 GPIO44
#ifndef BALL_B7_IS_GPIO
#define BALL_B7_IS_GPIO 0
#endif 
#ifndef PAD_SAR1_IS_GPIO
#define PAD_SAR1_IS_GPIO BALL_B7_IS_GPIO
#endif 

#define BALL_E5 PAD_SAR2
#define PAD_SAR2 46
#define GPIO_PAD_46 GPIO45
#ifndef BALL_E5_IS_GPIO
#define BALL_E5_IS_GPIO 0
#endif 
#ifndef PAD_SAR2_IS_GPIO
#define PAD_SAR2_IS_GPIO BALL_E5_IS_GPIO
#endif 

#define BALL_D4 PAD_SAR3
#define PAD_SAR3 47
#define GPIO_PAD_47 GPIO46
#ifndef BALL_D4_IS_GPIO
#define BALL_D4_IS_GPIO 0
#endif 
#ifndef PAD_SAR3_IS_GPIO
#define PAD_SAR3_IS_GPIO BALL_D4_IS_GPIO
#endif 

#define PAD_SAR4 9999
#ifndef PAD_SAR4_IS_GPIO
#define PAD_SAR4_IS_GPIO 0
#endif 

#define BALL_F6 PAD_SAR5
#define PAD_SAR5 49
#define GPIO_PAD_49 GPIO48
#ifndef BALL_F6_IS_GPIO
#define BALL_F6_IS_GPIO 0
#endif 
#ifndef PAD_SAR5_IS_GPIO
#define PAD_SAR5_IS_GPIO BALL_F6_IS_GPIO
#endif 

#define BALL_M6 PAD_HOTPLUGA
#define PAD_HOTPLUGA 30
#define GPIO_PAD_30 GPIO29
#ifndef BALL_M6_IS_GPIO
#define BALL_M6_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGA_IS_GPIO
#define PAD_HOTPLUGA_IS_GPIO BALL_M6_IS_GPIO
#endif 

#define PAD_PM_SPI_DI 9999
#ifndef PAD_PM_SPI_DI_IS_GPIO
#define PAD_PM_SPI_DI_IS_GPIO 0
#endif 

#define BALL_AA4 PAD_DDCA_DA
#define PAD_DDCA_DA 4
#define GPIO_PAD_4 GPIO3
#ifndef BALL_AA4_IS_GPIO
#define BALL_AA4_IS_GPIO 0
#endif 
#ifndef PAD_DDCA_DA_IS_GPIO
#define PAD_DDCA_DA_IS_GPIO BALL_AA4_IS_GPIO
#endif 

#define PAD_LED1 9999
#ifndef PAD_LED1_IS_GPIO
#define PAD_LED1_IS_GPIO 0
#endif 

#define BALL_H6 PAD_GPIO_PM1
#define PAD_GPIO_PM1 15
#define GPIO_PAD_15 GPIO14
#ifndef BALL_H6_IS_GPIO
#define BALL_H6_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM1_IS_GPIO
#define PAD_GPIO_PM1_IS_GPIO BALL_H6_IS_GPIO
#endif 

#define PAD_PM_SPI_CK 9999
#ifndef PAD_PM_SPI_CK_IS_GPIO
#define PAD_PM_SPI_CK_IS_GPIO 0
#endif 

#define PAD_WOL_INT_OUT 9999
#ifndef PAD_WOL_INT_OUT_IS_GPIO
#define PAD_WOL_INT_OUT_IS_GPIO 0
#endif 

#define BALL_G6 PAD_GPIO_PM5
#define PAD_GPIO_PM5 19
#define GPIO_PAD_19 GPIO18
#ifndef BALL_G6_IS_GPIO
#define BALL_G6_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM5_IS_GPIO
#define PAD_GPIO_PM5_IS_GPIO BALL_G6_IS_GPIO
#endif 

#define PAD_PM_SPI_DO 9999
#ifndef PAD_PM_SPI_DO_IS_GPIO
#define PAD_PM_SPI_DO_IS_GPIO 0
#endif 

#define BALL_L6 PAD_HOTPLUGB
#define PAD_HOTPLUGB 31
#define GPIO_PAD_31 GPIO30
#ifndef BALL_L6_IS_GPIO
#define BALL_L6_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGB_IS_GPIO
#define PAD_HOTPLUGB_IS_GPIO BALL_L6_IS_GPIO
#endif 

#define PAD_PM_SPI_WPN 9999
#ifndef PAD_PM_SPI_WPN_IS_GPIO
#define PAD_PM_SPI_WPN_IS_GPIO 0
#endif 

#define BALL_H5 PAD_DDCDC_DA
#define PAD_DDCDC_DA 38
#define GPIO_PAD_38 GPIO37
#ifndef BALL_H5_IS_GPIO
#define BALL_H5_IS_GPIO 0
#endif 
#ifndef PAD_DDCDC_DA_IS_GPIO
#define PAD_DDCDC_DA_IS_GPIO BALL_H5_IS_GPIO
#endif 

#define PAD_LED0 9999
#ifndef PAD_LED0_IS_GPIO
#define PAD_LED0_IS_GPIO 0
#endif 

#define BALL_F7 PAD_VID1
#define PAD_VID1 2
#define GPIO_PAD_2 GPIO1
#ifndef BALL_F7_IS_GPIO
#define BALL_F7_IS_GPIO 0
#endif 
#ifndef PAD_VID1_IS_GPIO
#define PAD_VID1_IS_GPIO BALL_F7_IS_GPIO
#endif 

#define BALL_AB4 PAD_DDCA_CK
#define PAD_DDCA_CK 3
#define GPIO_PAD_3 GPIO2
#ifndef BALL_AB4_IS_GPIO
#define BALL_AB4_IS_GPIO 0
#endif 
#ifndef PAD_DDCA_CK_IS_GPIO
#define PAD_DDCA_CK_IS_GPIO BALL_AB4_IS_GPIO
#endif 

#define BALL_P6 PAD_CEC
#define PAD_CEC 7
#define GPIO_PAD_7 GPIO6
#ifndef BALL_P6_IS_GPIO
#define BALL_P6_IS_GPIO 0
#endif 
#ifndef PAD_CEC_IS_GPIO
#define PAD_CEC_IS_GPIO BALL_P6_IS_GPIO
#endif 

#define BALL_AC2 PAD_GPIO_PM9
#define PAD_GPIO_PM9 23
#define GPIO_PAD_23 GPIO22
#ifndef BALL_AC2_IS_GPIO
#define BALL_AC2_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM9_IS_GPIO
#define PAD_GPIO_PM9_IS_GPIO BALL_AC2_IS_GPIO
#endif 

#define BALL_E6 PAD_GPIO_PM2
#define PAD_GPIO_PM2 16
#define GPIO_PAD_16 GPIO15
#ifndef BALL_E6_IS_GPIO
#define BALL_E6_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM2_IS_GPIO
#define PAD_GPIO_PM2_IS_GPIO BALL_E6_IS_GPIO
#endif 

#define BALL_AA8 PAD_GPIO_PM7
#define PAD_GPIO_PM7 21
#define GPIO_PAD_21 GPIO20
#ifndef BALL_AA8_IS_GPIO
#define BALL_AA8_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM7_IS_GPIO
#define PAD_GPIO_PM7_IS_GPIO BALL_AA8_IS_GPIO
#endif 

#define BALL_J6 PAD_HOTPLUGC
#define PAD_HOTPLUGC 32
#define GPIO_PAD_32 GPIO31
#ifndef BALL_J6_IS_GPIO
#define BALL_J6_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGC_IS_GPIO
#define PAD_HOTPLUGC_IS_GPIO BALL_J6_IS_GPIO
#endif 

#define BALL_Y2 PAD_GPIO_PM6
#define PAD_GPIO_PM6 20
#define GPIO_PAD_20 GPIO19
#ifndef BALL_Y2_IS_GPIO
#define BALL_Y2_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM6_IS_GPIO
#define PAD_GPIO_PM6_IS_GPIO BALL_Y2_IS_GPIO
#endif 

#define PAD_PM_SPI_HOLDN 9999
#ifndef PAD_PM_SPI_HOLDN_IS_GPIO
#define PAD_PM_SPI_HOLDN_IS_GPIO 0
#endif 

#define PAD_PM_SPI_CZ 9999
#ifndef PAD_PM_SPI_CZ_IS_GPIO
#define PAD_PM_SPI_CZ_IS_GPIO 0
#endif 

#define BALL_T3 PAD_GPIO_PM8
#define PAD_GPIO_PM8 22
#define GPIO_PAD_22 GPIO21
#ifndef BALL_T3_IS_GPIO
#define BALL_T3_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM8_IS_GPIO
#define PAD_GPIO_PM8_IS_GPIO BALL_T3_IS_GPIO
#endif 

#define BALL_G5 PAD_PWM_PM
#define PAD_PWM_PM 6
#define GPIO_PAD_6 GPIO5
#ifndef BALL_G5_IS_GPIO
#define BALL_G5_IS_GPIO 0
#endif 
#ifndef PAD_PWM_PM_IS_GPIO
#define PAD_PWM_PM_IS_GPIO BALL_G5_IS_GPIO
#endif 

#define PAD_GPIO_PM12 9999
#ifndef PAD_GPIO_PM12_IS_GPIO
#define PAD_GPIO_PM12_IS_GPIO 0
#endif 

#define PAD_GPIO_PM14 9999
#ifndef PAD_GPIO_PM14_IS_GPIO
#define PAD_GPIO_PM14_IS_GPIO 0
#endif 

#define BALL_T2 PAD_GPIO_PM3
#define PAD_GPIO_PM3 17
#define GPIO_PAD_17 GPIO16
#ifndef BALL_T2_IS_GPIO
#define BALL_T2_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM3_IS_GPIO
#define PAD_GPIO_PM3_IS_GPIO BALL_T2_IS_GPIO
#endif 

#define PAD_GPIO_PM13 9999
#ifndef PAD_GPIO_PM13_IS_GPIO
#define PAD_GPIO_PM13_IS_GPIO 0
#endif 

#define BALL_L5 PAD_DDCDA_CK
#define PAD_DDCDA_CK 33
#define GPIO_PAD_33 GPIO32
#ifndef BALL_L5_IS_GPIO
#define BALL_L5_IS_GPIO 0
#endif 
#ifndef PAD_DDCDA_CK_IS_GPIO
#define PAD_DDCDA_CK_IS_GPIO BALL_L5_IS_GPIO
#endif 

#define BALL_F5 PAD_IRIN
#define PAD_IRIN 5
#define GPIO_PAD_5 GPIO4
#ifndef BALL_F5_IS_GPIO
#define BALL_F5_IS_GPIO 0
#endif 
#ifndef PAD_IRIN_IS_GPIO
#define PAD_IRIN_IS_GPIO BALL_F5_IS_GPIO
#endif 

#define BALL_K5 PAD_DDCDB_DA
#define PAD_DDCDB_DA 36
#define GPIO_PAD_36 GPIO35
#ifndef BALL_K5_IS_GPIO
#define BALL_K5_IS_GPIO 0
#endif 
#ifndef PAD_DDCDB_DA_IS_GPIO
#define PAD_DDCDB_DA_IS_GPIO BALL_K5_IS_GPIO
#endif 

#define PAD_DDCDD_DA 9999
#ifndef PAD_DDCDD_DA_IS_GPIO
#define PAD_DDCDD_DA_IS_GPIO 0
#endif 

#define PAD_GPIO_PM15 9999
#ifndef PAD_GPIO_PM15_IS_GPIO
#define PAD_GPIO_PM15_IS_GPIO 0
#endif 

#define PAD_DDCDD_CK 9999
#ifndef PAD_DDCDD_CK_IS_GPIO
#define PAD_DDCDD_CK_IS_GPIO 0
#endif 

#define BALL_AC1 PAD_GPIO_PM10
#define PAD_GPIO_PM10 24
#define GPIO_PAD_24 GPIO23
#ifndef BALL_AC1_IS_GPIO
#define BALL_AC1_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM10_IS_GPIO
#define PAD_GPIO_PM10_IS_GPIO BALL_AC1_IS_GPIO
#endif 

#define BALL_J5 PAD_DDCDC_CK
#define PAD_DDCDC_CK 37
#define GPIO_PAD_37 GPIO36
#ifndef BALL_J5_IS_GPIO
#define BALL_J5_IS_GPIO 0
#endif 
#ifndef PAD_DDCDC_CK_IS_GPIO
#define PAD_DDCDC_CK_IS_GPIO BALL_J5_IS_GPIO
#endif 

#define BALL_F3 PAD_GPIO_PM0
#define PAD_GPIO_PM0 14
#define GPIO_PAD_14 GPIO13
#ifndef BALL_F3_IS_GPIO
#define BALL_F3_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM0_IS_GPIO
#define PAD_GPIO_PM0_IS_GPIO BALL_F3_IS_GPIO
#endif 

#define BALL_M5 PAD_DDCDA_DA
#define PAD_DDCDA_DA 34
#define GPIO_PAD_34 GPIO33
#ifndef BALL_M5_IS_GPIO
#define BALL_M5_IS_GPIO 0
#endif 
#ifndef PAD_DDCDA_DA_IS_GPIO
#define PAD_DDCDA_DA_IS_GPIO BALL_M5_IS_GPIO
#endif 

#define BALL_K4 PAD_DDCDB_CK
#define PAD_DDCDB_CK 35
#define GPIO_PAD_35 GPIO34
#ifndef BALL_K4_IS_GPIO
#define BALL_K4_IS_GPIO 0
#endif 
#ifndef PAD_DDCDB_CK_IS_GPIO
#define PAD_DDCDB_CK_IS_GPIO BALL_K4_IS_GPIO
#endif 

#define PAD_GPIO_PM11 9999
#ifndef PAD_GPIO_PM11_IS_GPIO
#define PAD_GPIO_PM11_IS_GPIO 0
#endif 

#define BALL_G4 PAD_GPIO_PM4
#define PAD_GPIO_PM4 18
#define GPIO_PAD_18 GPIO17
#ifndef BALL_G4_IS_GPIO
#define BALL_G4_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM4_IS_GPIO
#define PAD_GPIO_PM4_IS_GPIO BALL_G4_IS_GPIO
#endif 


// PADS group name to index
#define PADS_PCMCONFIG_MODE1        1223
#define PADS_PCMCONFIG_MODE2        1224
#define PADS_PCMCONFIG1_MODE1       1225
#define PADS_PCMCONFIG1_MODE2       1226
#define PADS_PCMCONFIG1_MODE3       1227
#define PADS_PCM2CONFIG_MODE1       1228
#define PADS_PCM2CONFIG_MODE2       1229
#define PADS_PCM2CONFIG_MODE3       1230
#define PADS_PCM2CONFIG1_MODE1      1231
#define PADS_PCM2CONFIG1_MODE2      1232
#define PADS_ET_MODE1               1233
#define PADS_ET_MODE2               1234
#define PADS_DDCR                   1235
#define PADS_DDCR2                  1236
#define PADS_PCM                    1237

// chip capbilities
#define CHIP_HAS_BT656_IN           0
#define CHIP_HAS_TS0                1
#define CHIP_HAS_TS1                0 
#define CHIP_HAS_LVDS_10BIT_X2      1
#define CHIP_HAS_LVDS_8BIT_X2       1
#define CHIP_HAS_LVDS_8BIT_X1       1
#define CHIP_HAS_CIMAX              0
#define CHIP_HAS_USB_P0             1
#define CHIP_HAS_USB_P1             1
#define CHIP_HAS_USBVBUS0           0
#define CHIP_HAS_USBVBUS1           0
#define CHIP_HAS_UART1_MODE1        1 
#define CHIP_HAS_UART1_MODE2        1
#define CHIP_HAS_UART1_MODE3        1 
#define CHIP_HAS_PCMCIA1            0
#define CHIP_HAS_PCMCIA2            0
#define CHIP_HAS_PCMCIA             0
#define CHIP_HAS_UART2_MODE1        1 
#define CHIP_HAS_UART2_MODE2        1 
#define CHIP_HAS_UART2_MODE3        1 
#define CHIP_HAS_RGB_A              1 
#define CHIP_HAS_RGB_B              1 
#define CHIP_HAS_RGB_C              1 
#define CHIP_HAS_HDMI_A             1 
#define CHIP_HAS_HDMI_B             1 
#define CHIP_HAS_HDMI_C             1 
#define CHIP_HAS_SPI_CZ1            1 
#define CHIP_HAS_SPI_CZ2            0 
#define CHIP_HAS_SPI_CZ3            0
#define CHIP_HAS_DDCR               1 
#define CHIP_HAS_DDCR2              1 
#define CHIP_HAS_TCON               1
#define CHIP_HAS_ET_MODE0_MII       1 
#define CHIP_HAS_ET_MODE0_RMII      1 
#define CHIP_HAS_ET_MODE1_MII       1 
#define CHIP_HAS_ET_MODE1_RMII      1 
#define CHIP_HAS_ET_MODE2_MII       1
#define CHIP_HAS_ET_MODE2_RMII      1
#define CHIP_HAS_I2S_IN             0 
#define CHIP_HAS_I2S_OUT            0
#define CHIP_HAS_SPDIF_IN           0 
#define CHIP_HAS_SPDIF_OUT          0
#define CHIP_HAS_DDR_A_CMD          1
#define CHIP_HAS_DDR_A_DATA         1
#define CHIP_HAS_DDR_B_CMD          1
#define CHIP_HAS_DDR_B_DATA         1
#define CHIP_USE_PCM_CDN_IN_PCM2    0
#define CHIP_USE_I2S_IN_IN_PCM      0
#define CHIP_USE_I2S_OUT_IN_PCM     0
#define CHIP_USE_SPDIF_IN_IN_PCM    0
#define CHIP_USE_SPDIF_OUT_IN_PCM   0
#define CHIP_USE_IIC_IN_DDCR2       0
#define CHIP_USE_PWM2_IN_GPIO14     0
#define CHIP_USE_PWM3_IN_GPIO15     0

// chip additional information
#define CHIP_FAMILY_TYPE            CHIP_FAMILY_M5621

#endif /* _MSD94BX8_H_*/
