/* SPDX-License-Identifier: GPL-2.0-only OR BSD-3-Clause */
/******************************************************************************
 *
 * This file is provided under a dual license.  When you use or
 * distribute this software, you may choose to be licensed under
 * version 2 of the GNU General Public License ("GPLv2 License")
 * or BSD License.
 *
 * GPLv2 License
 *
 * Copyright(C) 2019 MediaTek Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of version 2 of the GNU General Public License as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See http://www.gnu.org/licenses/gpl-2.0.html for more details.
 *
 * BSD LICENSE
 *
 * Copyright(C) 2019 MediaTek Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *****************************************************************************/

// This file is generated by script file, please do not edit it directly 
#ifndef _MSD96BUXM8_NANYA_H_
#define _MSD96BUXM8_NANYA_H_

#define PAD_NC   9999
#define PAD_GND  0

#define BALL_L6 PAD_DDCDC_CK
#define PAD_DDCDC_CK 28
#define GPIO_PAD_28 GPIO27
#ifndef BALL_L6_IS_GPIO
#define BALL_L6_IS_GPIO 0
#endif 
#ifndef PAD_DDCDC_CK_IS_GPIO
#define PAD_DDCDC_CK_IS_GPIO BALL_L6_IS_GPIO
#endif 

#define BALL_M6 PAD_DDCDC_DA
#define PAD_DDCDC_DA 29
#define GPIO_PAD_29 GPIO28
#ifndef BALL_M6_IS_GPIO
#define BALL_M6_IS_GPIO 0
#endif 
#ifndef PAD_DDCDC_DA_IS_GPIO
#define PAD_DDCDC_DA_IS_GPIO BALL_M6_IS_GPIO
#endif 

#define BALL_K7 PAD_DDCA_CK
#define PAD_DDCA_CK 4
#define GPIO_PAD_4 GPIO3
#ifndef BALL_K7_IS_GPIO
#define BALL_K7_IS_GPIO 0
#endif 
#ifndef PAD_DDCA_CK_IS_GPIO
#define PAD_DDCA_CK_IS_GPIO BALL_K7_IS_GPIO
#endif 

#define BALL_K6 PAD_DDCA_DA
#define PAD_DDCA_DA 5
#define GPIO_PAD_5 GPIO4
#ifndef BALL_K6_IS_GPIO
#define BALL_K6_IS_GPIO 0
#endif 
#ifndef PAD_DDCA_DA_IS_GPIO
#define PAD_DDCA_DA_IS_GPIO BALL_K6_IS_GPIO
#endif 

#define BALL_W5 PAD_GPIO1_PM
#define PAD_GPIO1_PM 7
#define GPIO_PAD_7 GPIO6
#ifndef BALL_W5_IS_GPIO
#define BALL_W5_IS_GPIO 0
#endif 
#ifndef PAD_GPIO1_PM_IS_GPIO
#define PAD_GPIO1_PM_IS_GPIO BALL_W5_IS_GPIO
#endif 

#define BALL_W4 PAD_GPIO5_PM
#define PAD_GPIO5_PM 10
#define GPIO_PAD_10 GPIO9
#ifndef BALL_W4_IS_GPIO
#define BALL_W4_IS_GPIO 0
#endif 
#ifndef PAD_GPIO5_PM_IS_GPIO
#define PAD_GPIO5_PM_IS_GPIO BALL_W4_IS_GPIO
#endif 

#define BALL_AC12 PAD_IRIN
#define PAD_IRIN 1
#define GPIO_PAD_1 GPIO0
#ifndef BALL_AC12_IS_GPIO
#define BALL_AC12_IS_GPIO 0
#endif 
#ifndef PAD_IRIN_IS_GPIO
#define PAD_IRIN_IS_GPIO BALL_AC12_IS_GPIO
#endif 

#define BALL_L5 PAD_CEC0
#define PAD_CEC0 2
#define GPIO_PAD_2 GPIO1
#ifndef BALL_L5_IS_GPIO
#define BALL_L5_IS_GPIO 0
#endif 
#ifndef PAD_CEC0_IS_GPIO
#define PAD_CEC0_IS_GPIO BALL_L5_IS_GPIO
#endif 

#define BALL_M5 PAD_HOTPLUGA
#define PAD_HOTPLUGA 18
#define GPIO_PAD_18 GPIO17
#ifndef BALL_M5_IS_GPIO
#define BALL_M5_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGA_IS_GPIO
#define PAD_HOTPLUGA_IS_GPIO BALL_M5_IS_GPIO
#endif 

#define BALL_K5 PAD_HOTPLUGA_HDMI20_5V
#define PAD_HOTPLUGA_HDMI20_5V 21
#define GPIO_PAD_21 GPIO20
#ifndef BALL_K5_IS_GPIO
#define BALL_K5_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGA_HDMI20_5V_IS_GPIO
#define PAD_HOTPLUGA_HDMI20_5V_IS_GPIO BALL_K5_IS_GPIO
#endif 

#define BALL_N4 PAD_HOTPLUGB
#define PAD_HOTPLUGB 19
#define GPIO_PAD_19 GPIO18
#ifndef BALL_N4_IS_GPIO
#define BALL_N4_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGB_IS_GPIO
#define PAD_HOTPLUGB_IS_GPIO BALL_N4_IS_GPIO
#endif 

#define BALL_L4 PAD_HOTPLUGB_HDMI20_5V
#define PAD_HOTPLUGB_HDMI20_5V 22
#define GPIO_PAD_22 GPIO21
#ifndef BALL_L4_IS_GPIO
#define BALL_L4_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGB_HDMI20_5V_IS_GPIO
#define PAD_HOTPLUGB_HDMI20_5V_IS_GPIO BALL_L4_IS_GPIO
#endif 

#define BALL_N5 PAD_HOTPLUGC
#define PAD_HOTPLUGC 20
#define GPIO_PAD_20 GPIO19
#ifndef BALL_N5_IS_GPIO
#define BALL_N5_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGC_IS_GPIO
#define PAD_HOTPLUGC_IS_GPIO BALL_N5_IS_GPIO
#endif 

#define BALL_K4 PAD_HOTPLUGC_HDMI20_5V
#define PAD_HOTPLUGC_HDMI20_5V 23
#define GPIO_PAD_23 GPIO22
#ifndef BALL_K4_IS_GPIO
#define BALL_K4_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGC_HDMI20_5V_IS_GPIO
#define PAD_HOTPLUGC_HDMI20_5V_IS_GPIO BALL_K4_IS_GPIO
#endif 

#define BALL_Y4 PAD_GPIO6_PM
#define PAD_GPIO6_PM 11
#define GPIO_PAD_11 GPIO10
#ifndef BALL_Y4_IS_GPIO
#define BALL_Y4_IS_GPIO 0
#endif 
#ifndef PAD_GPIO6_PM_IS_GPIO
#define PAD_GPIO6_PM_IS_GPIO BALL_Y4_IS_GPIO
#endif 

#define BALL_V6 PAD_GPIO9_PM
#define PAD_GPIO9_PM 14
#define GPIO_PAD_14 GPIO13
#ifndef BALL_V6_IS_GPIO
#define BALL_V6_IS_GPIO 0
#endif 
#ifndef PAD_GPIO9_PM_IS_GPIO
#define PAD_GPIO9_PM_IS_GPIO BALL_V6_IS_GPIO
#endif 

#define BALL_AA4 PAD_GPIO10_PM
#define PAD_GPIO10_PM 15
#define GPIO_PAD_15 GPIO14
#ifndef BALL_AA4_IS_GPIO
#define BALL_AA4_IS_GPIO 0
#endif 
#ifndef PAD_GPIO10_PM_IS_GPIO
#define PAD_GPIO10_PM_IS_GPIO BALL_AA4_IS_GPIO
#endif 

#define BALL_AB5 PAD_I2S_IN_SD1
#define PAD_I2S_IN_SD1 45
#define GPIO_PAD_45 GPIO44
#ifndef BALL_AB5_IS_GPIO
#define BALL_AB5_IS_GPIO 0
#endif 
#ifndef PAD_I2S_IN_SD1_IS_GPIO
#define PAD_I2S_IN_SD1_IS_GPIO BALL_AB5_IS_GPIO
#endif 

#define BALL_Y5 PAD_I2S_IN_SD0
#define PAD_I2S_IN_SD0 44
#define GPIO_PAD_44 GPIO43
#ifndef BALL_Y5_IS_GPIO
#define BALL_Y5_IS_GPIO 0
#endif 
#ifndef PAD_I2S_IN_SD0_IS_GPIO
#define PAD_I2S_IN_SD0_IS_GPIO BALL_Y5_IS_GPIO
#endif 

#define BALL_AA6 PAD_I2S_IN_MCK
#define PAD_I2S_IN_MCK 43
#define GPIO_PAD_43 GPIO42
#ifndef BALL_AA6_IS_GPIO
#define BALL_AA6_IS_GPIO 0
#endif 
#ifndef PAD_I2S_IN_MCK_IS_GPIO
#define PAD_I2S_IN_MCK_IS_GPIO BALL_AA6_IS_GPIO
#endif 

#define BALL_Y6 PAD_I2S_IN_BCK
#define PAD_I2S_IN_BCK 41
#define GPIO_PAD_41 GPIO40
#ifndef BALL_Y6_IS_GPIO
#define BALL_Y6_IS_GPIO 0
#endif 
#ifndef PAD_I2S_IN_BCK_IS_GPIO
#define PAD_I2S_IN_BCK_IS_GPIO BALL_Y6_IS_GPIO
#endif 

#define BALL_AE11 PAD_TGPIO0
#define PAD_TGPIO0 98
#define GPIO_PAD_98 GPIO97
#ifndef BALL_AE11_IS_GPIO
#define BALL_AE11_IS_GPIO 0
#endif 
#ifndef PAD_TGPIO0_IS_GPIO
#define PAD_TGPIO0_IS_GPIO BALL_AE11_IS_GPIO
#endif 

#define BALL_AD11 PAD_TGPIO1
#define PAD_TGPIO1 99
#define GPIO_PAD_99 GPIO98
#ifndef BALL_AD11_IS_GPIO
#define BALL_AD11_IS_GPIO 0
#endif 
#ifndef PAD_TGPIO1_IS_GPIO
#define PAD_TGPIO1_IS_GPIO BALL_AD11_IS_GPIO
#endif 

#define BALL_AB21 PAD_SD_D3
#define PAD_SD_D3 95
#define GPIO_PAD_95 GPIO94
#ifndef BALL_AB21_IS_GPIO
#define BALL_AB21_IS_GPIO 0
#endif 
#ifndef PAD_SD_D3_IS_GPIO
#define PAD_SD_D3_IS_GPIO BALL_AB21_IS_GPIO
#endif 

#define PAD_TGPIO2 9999
#ifndef PAD_TGPIO2_IS_GPIO
#define PAD_TGPIO2_IS_GPIO 0
#endif 

#define PAD_TGPIO3 9999
#ifndef PAD_TGPIO3_IS_GPIO
#define PAD_TGPIO3_IS_GPIO 0
#endif 

#define BALL_AC18 PAD_GPIO25
#define PAD_GPIO25 75
#define GPIO_PAD_75 GPIO74
#ifndef BALL_AC18_IS_GPIO
#define BALL_AC18_IS_GPIO 0
#endif 
#ifndef PAD_GPIO25_IS_GPIO
#define PAD_GPIO25_IS_GPIO BALL_AC18_IS_GPIO
#endif 

#define BALL_V21 PAD_GPIO26
#define PAD_GPIO26 76
#define GPIO_PAD_76 GPIO75
#ifndef BALL_V21_IS_GPIO
#define BALL_V21_IS_GPIO 0
#endif 
#ifndef PAD_GPIO26_IS_GPIO
#define PAD_GPIO26_IS_GPIO BALL_V21_IS_GPIO
#endif 

#define PAD_GPIO30 9999
#ifndef PAD_GPIO30_IS_GPIO
#define PAD_GPIO30_IS_GPIO 0
#endif 

#define PAD_GPIO31 9999
#ifndef PAD_GPIO31_IS_GPIO
#define PAD_GPIO31_IS_GPIO 0
#endif 

#define BALL_W20 PAD_SD_D2
#define PAD_SD_D2 94
#define GPIO_PAD_94 GPIO93
#ifndef BALL_W20_IS_GPIO
#define BALL_W20_IS_GPIO 0
#endif 
#ifndef PAD_SD_D2_IS_GPIO
#define PAD_SD_D2_IS_GPIO BALL_W20_IS_GPIO
#endif 

#define BALL_AB20 PAD_SD_D1
#define PAD_SD_D1 93
#define GPIO_PAD_93 GPIO92
#ifndef BALL_AB20_IS_GPIO
#define BALL_AB20_IS_GPIO 0
#endif 
#ifndef PAD_SD_D1_IS_GPIO
#define PAD_SD_D1_IS_GPIO BALL_AB20_IS_GPIO
#endif 

#define BALL_AA20 PAD_SD_D0
#define PAD_SD_D0 92
#define GPIO_PAD_92 GPIO91
#ifndef BALL_AA20_IS_GPIO
#define BALL_AA20_IS_GPIO 0
#endif 
#ifndef PAD_SD_D0_IS_GPIO
#define PAD_SD_D0_IS_GPIO BALL_AA20_IS_GPIO
#endif 

#define BALL_Y20 PAD_SD_CMD
#define PAD_SD_CMD 91
#define GPIO_PAD_91 GPIO90
#ifndef BALL_Y20_IS_GPIO
#define BALL_Y20_IS_GPIO 0
#endif 
#ifndef PAD_SD_CMD_IS_GPIO
#define PAD_SD_CMD_IS_GPIO BALL_Y20_IS_GPIO
#endif 

#define BALL_AA21 PAD_SD_CLK
#define PAD_SD_CLK 90
#define GPIO_PAD_90 GPIO89
#ifndef BALL_AA21_IS_GPIO
#define BALL_AA21_IS_GPIO 0
#endif 
#ifndef PAD_SD_CLK_IS_GPIO
#define PAD_SD_CLK_IS_GPIO BALL_AA21_IS_GPIO
#endif 

#define BALL_AD17 PAD_TS1_CLK
#define PAD_TS1_CLK 102
#define GPIO_PAD_102 GPIO101
#ifndef BALL_AD17_IS_GPIO
#define BALL_AD17_IS_GPIO 0
#endif 
#ifndef PAD_TS1_CLK_IS_GPIO
#define PAD_TS1_CLK_IS_GPIO BALL_AD17_IS_GPIO
#endif 

#define BALL_AE18 PAD_TS1_SYNC
#define PAD_TS1_SYNC 111
#define GPIO_PAD_111 GPIO110
#ifndef BALL_AE18_IS_GPIO
#define BALL_AE18_IS_GPIO 0
#endif 
#ifndef PAD_TS1_SYNC_IS_GPIO
#define PAD_TS1_SYNC_IS_GPIO BALL_AE18_IS_GPIO
#endif 

#define BALL_AD18 PAD_TS1_VLD
#define PAD_TS1_VLD 112
#define GPIO_PAD_112 GPIO111
#ifndef BALL_AD18_IS_GPIO
#define BALL_AD18_IS_GPIO 0
#endif 
#ifndef PAD_TS1_VLD_IS_GPIO
#define PAD_TS1_VLD_IS_GPIO BALL_AD18_IS_GPIO
#endif 

#define PAD_TS1_D7 9999
#ifndef PAD_TS1_D7_IS_GPIO
#define PAD_TS1_D7_IS_GPIO 0
#endif 

#define PAD_TS1_D6 9999
#ifndef PAD_TS1_D6_IS_GPIO
#define PAD_TS1_D6_IS_GPIO 0
#endif 

#define PAD_TS1_D5 9999
#ifndef PAD_TS1_D5_IS_GPIO
#define PAD_TS1_D5_IS_GPIO 0
#endif 

#define PAD_TS1_D4 9999
#ifndef PAD_TS1_D4_IS_GPIO
#define PAD_TS1_D4_IS_GPIO 0
#endif 

#define PAD_TS1_D3 9999
#ifndef PAD_TS1_D3_IS_GPIO
#define PAD_TS1_D3_IS_GPIO 0
#endif 

#define PAD_TS1_D2 9999
#ifndef PAD_TS1_D2_IS_GPIO
#define PAD_TS1_D2_IS_GPIO 0
#endif 

#define PAD_TS1_D1 9999
#ifndef PAD_TS1_D1_IS_GPIO
#define PAD_TS1_D1_IS_GPIO 0
#endif 

#define BALL_AC17 PAD_TS1_D0
#define PAD_TS1_D0 103
#define GPIO_PAD_103 GPIO102
#ifndef BALL_AC17_IS_GPIO
#define BALL_AC17_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D0_IS_GPIO
#define PAD_TS1_D0_IS_GPIO BALL_AC17_IS_GPIO
#endif 

#define PAD_TS2_CLK 9999
#ifndef PAD_TS2_CLK_IS_GPIO
#define PAD_TS2_CLK_IS_GPIO 0
#endif 

#define PAD_TS2_SYNC 9999
#ifndef PAD_TS2_SYNC_IS_GPIO
#define PAD_TS2_SYNC_IS_GPIO 0
#endif 

#define PAD_TS2_VLD 9999
#ifndef PAD_TS2_VLD_IS_GPIO
#define PAD_TS2_VLD_IS_GPIO 0
#endif 

#define PAD_TS2_D0 9999
#ifndef PAD_TS2_D0_IS_GPIO
#define PAD_TS2_D0_IS_GPIO 0
#endif 

#define BALL_AB22 PAD_GPIO9
#define PAD_GPIO9 69
#define GPIO_PAD_69 GPIO68
#ifndef BALL_AB22_IS_GPIO
#define BALL_AB22_IS_GPIO 0
#endif 
#ifndef PAD_GPIO9_IS_GPIO
#define PAD_GPIO9_IS_GPIO BALL_AB22_IS_GPIO
#endif 

#define BALL_AA22 PAD_GPIO10
#define PAD_GPIO10 70
#define GPIO_PAD_70 GPIO69
#ifndef BALL_AA22_IS_GPIO
#define BALL_AA22_IS_GPIO 0
#endif 
#ifndef PAD_GPIO10_IS_GPIO
#define PAD_GPIO10_IS_GPIO BALL_AA22_IS_GPIO
#endif 

#define BALL_Y22 PAD_GPIO11
#define PAD_GPIO11 71
#define GPIO_PAD_71 GPIO70
#ifndef BALL_Y22_IS_GPIO
#define BALL_Y22_IS_GPIO 0
#endif 
#ifndef PAD_GPIO11_IS_GPIO
#define PAD_GPIO11_IS_GPIO BALL_Y22_IS_GPIO
#endif 

#define BALL_Y21 PAD_GPIO12
#define PAD_GPIO12 72
#define GPIO_PAD_72 GPIO71
#ifndef BALL_Y21_IS_GPIO
#define BALL_Y21_IS_GPIO 0
#endif 
#ifndef PAD_GPIO12_IS_GPIO
#define PAD_GPIO12_IS_GPIO BALL_Y21_IS_GPIO
#endif 

#define PAD_PWM3 9999
#ifndef PAD_PWM3_IS_GPIO
#define PAD_PWM3_IS_GPIO 0
#endif 

#define BALL_W21 PAD_PWM2
#define PAD_PWM2 88
#define GPIO_PAD_88 GPIO87
#ifndef BALL_W21_IS_GPIO
#define BALL_W21_IS_GPIO 0
#endif 
#ifndef PAD_PWM2_IS_GPIO
#define PAD_PWM2_IS_GPIO BALL_W21_IS_GPIO
#endif 

#define BALL_W22 PAD_PWM1
#define PAD_PWM1 87
#define GPIO_PAD_87 GPIO86
#ifndef BALL_W22_IS_GPIO
#define BALL_W22_IS_GPIO 0
#endif 
#ifndef PAD_PWM1_IS_GPIO
#define PAD_PWM1_IS_GPIO BALL_W22_IS_GPIO
#endif 

#define BALL_V22 PAD_PWM0
#define PAD_PWM0 86
#define GPIO_PAD_86 GPIO85
#ifndef BALL_V22_IS_GPIO
#define BALL_V22_IS_GPIO 0
#endif 
#ifndef PAD_PWM0_IS_GPIO
#define PAD_PWM0_IS_GPIO BALL_V22_IS_GPIO
#endif 

#define BALL_AD16 PAD_GPIO19
#define PAD_GPIO19 73
#define GPIO_PAD_73 GPIO72
#ifndef BALL_AD16_IS_GPIO
#define BALL_AD16_IS_GPIO 0
#endif 
#ifndef PAD_GPIO19_IS_GPIO
#define PAD_GPIO19_IS_GPIO BALL_AD16_IS_GPIO
#endif 

#define BALL_AC16 PAD_GPIO20
#define PAD_GPIO20 74
#define GPIO_PAD_74 GPIO73
#ifndef BALL_AC16_IS_GPIO
#define BALL_AC16_IS_GPIO 0
#endif 
#ifndef PAD_GPIO20_IS_GPIO
#define PAD_GPIO20_IS_GPIO BALL_AC16_IS_GPIO
#endif 

#define BALL_U21 PAD_GPIO2
#define PAD_GPIO2 65
#define GPIO_PAD_65 GPIO64
#ifndef BALL_U21_IS_GPIO
#define BALL_U21_IS_GPIO 0
#endif 
#ifndef PAD_GPIO2_IS_GPIO
#define PAD_GPIO2_IS_GPIO BALL_U21_IS_GPIO
#endif 

#define BALL_U22 PAD_GPIO3
#define PAD_GPIO3 66
#define GPIO_PAD_66 GPIO65
#ifndef BALL_U22_IS_GPIO
#define BALL_U22_IS_GPIO 0
#endif 
#ifndef PAD_GPIO3_IS_GPIO
#define PAD_GPIO3_IS_GPIO BALL_U22_IS_GPIO
#endif 

#define BALL_U20 PAD_GPIO4
#define PAD_GPIO4 67
#define GPIO_PAD_67 GPIO66
#ifndef BALL_U20_IS_GPIO
#define BALL_U20_IS_GPIO 0
#endif 
#ifndef PAD_GPIO4_IS_GPIO
#define PAD_GPIO4_IS_GPIO BALL_U20_IS_GPIO
#endif 

#define BALL_V20 PAD_GPIO5
#define PAD_GPIO5 68
#define GPIO_PAD_68 GPIO67
#ifndef BALL_V20_IS_GPIO
#define BALL_V20_IS_GPIO 0
#endif 
#ifndef PAD_GPIO5_IS_GPIO
#define PAD_GPIO5_IS_GPIO BALL_V20_IS_GPIO
#endif 

#define BALL_AE19 PAD_CILINK_RX0_D1
#define PAD_CILINK_RX0_D1 50
#define GPIO_PAD_50 GPIO49
#ifndef BALL_AE19_IS_GPIO
#define BALL_AE19_IS_GPIO 0
#endif 
#ifndef PAD_CILINK_RX0_D1_IS_GPIO
#define PAD_CILINK_RX0_D1_IS_GPIO BALL_AE19_IS_GPIO
#endif 

#define BALL_AD19 PAD_CILINK_RX0_D0
#define PAD_CILINK_RX0_D0 49
#define GPIO_PAD_49 GPIO48
#ifndef BALL_AD19_IS_GPIO
#define BALL_AD19_IS_GPIO 0
#endif 
#ifndef PAD_CILINK_RX0_D0_IS_GPIO
#define PAD_CILINK_RX0_D0_IS_GPIO BALL_AD19_IS_GPIO
#endif 

#define BALL_AC19 PAD_CILINK_RX_CLK
#define PAD_CILINK_RX_CLK 53
#define GPIO_PAD_53 GPIO52
#ifndef BALL_AC19_IS_GPIO
#define BALL_AC19_IS_GPIO 0
#endif 
#ifndef PAD_CILINK_RX_CLK_IS_GPIO
#define PAD_CILINK_RX_CLK_IS_GPIO BALL_AC19_IS_GPIO
#endif 

#define BALL_AD20 PAD_CILINK_TX0_D1
#define PAD_CILINK_TX0_D1 59
#define GPIO_PAD_59 GPIO58
#ifndef BALL_AD20_IS_GPIO
#define BALL_AD20_IS_GPIO 0
#endif 
#ifndef PAD_CILINK_TX0_D1_IS_GPIO
#define PAD_CILINK_TX0_D1_IS_GPIO BALL_AD20_IS_GPIO
#endif 

#define BALL_AC20 PAD_CILINK_TX0_D0
#define PAD_CILINK_TX0_D0 58
#define GPIO_PAD_58 GPIO57
#ifndef BALL_AC20_IS_GPIO
#define BALL_AC20_IS_GPIO 0
#endif 
#ifndef PAD_CILINK_TX0_D0_IS_GPIO
#define PAD_CILINK_TX0_D0_IS_GPIO BALL_AC20_IS_GPIO
#endif 

#define BALL_AD21 PAD_CILINK_TX_CLK
#define PAD_CILINK_TX_CLK 62
#define GPIO_PAD_62 GPIO61
#ifndef BALL_AD21_IS_GPIO
#define BALL_AD21_IS_GPIO 0
#endif 
#ifndef PAD_CILINK_TX_CLK_IS_GPIO
#define PAD_CILINK_TX_CLK_IS_GPIO BALL_AD21_IS_GPIO
#endif 

#define BALL_AE21 PAD_CILINK_DEMOD0_CLK
#define PAD_CILINK_DEMOD0_CLK 46
#define GPIO_PAD_46 GPIO45
#ifndef BALL_AE21_IS_GPIO
#define BALL_AE21_IS_GPIO 0
#endif 
#ifndef PAD_CILINK_DEMOD0_CLK_IS_GPIO
#define PAD_CILINK_DEMOD0_CLK_IS_GPIO BALL_AE21_IS_GPIO
#endif 

#define BALL_AD22 PAD_CILINK_SPI_MOSI
#define PAD_CILINK_SPI_MOSI 57
#define GPIO_PAD_57 GPIO56
#ifndef BALL_AD22_IS_GPIO
#define BALL_AD22_IS_GPIO 0
#endif 
#ifndef PAD_CILINK_SPI_MOSI_IS_GPIO
#define PAD_CILINK_SPI_MOSI_IS_GPIO BALL_AD22_IS_GPIO
#endif 

#define BALL_AC22 PAD_CILINK_SPI_CLK
#define PAD_CILINK_SPI_CLK 54
#define GPIO_PAD_54 GPIO53
#ifndef BALL_AC22_IS_GPIO
#define BALL_AC22_IS_GPIO 0
#endif 
#ifndef PAD_CILINK_SPI_CLK_IS_GPIO
#define PAD_CILINK_SPI_CLK_IS_GPIO BALL_AC22_IS_GPIO
#endif 

#define BALL_AC21 PAD_CILINK_INT
#define PAD_CILINK_INT 48
#define GPIO_PAD_48 GPIO47
#ifndef BALL_AC21_IS_GPIO
#define BALL_AC21_IS_GPIO 0
#endif 
#ifndef PAD_CILINK_INT_IS_GPIO
#define PAD_CILINK_INT_IS_GPIO BALL_AC21_IS_GPIO
#endif 

#define BALL_AE22 PAD_CILINK_SPI_CS
#define PAD_CILINK_SPI_CS 55
#define GPIO_PAD_55 GPIO54
#ifndef BALL_AE22_IS_GPIO
#define BALL_AE22_IS_GPIO 0
#endif 
#ifndef PAD_CILINK_SPI_CS_IS_GPIO
#define PAD_CILINK_SPI_CS_IS_GPIO BALL_AE22_IS_GPIO
#endif 

#define BALL_AE23 PAD_CILINK_SPI_MISO
#define PAD_CILINK_SPI_MISO 56
#define GPIO_PAD_56 GPIO55
#ifndef BALL_AE23_IS_GPIO
#define BALL_AE23_IS_GPIO 0
#endif 
#ifndef PAD_CILINK_SPI_MISO_IS_GPIO
#define PAD_CILINK_SPI_MISO_IS_GPIO BALL_AE23_IS_GPIO
#endif 

#define PAD_CILINK_TX1_D0 9999
#ifndef PAD_CILINK_TX1_D0_IS_GPIO
#define PAD_CILINK_TX1_D0_IS_GPIO 0
#endif 

#define PAD_CILINK_DEMOD1_CLK 9999
#ifndef PAD_CILINK_DEMOD1_CLK_IS_GPIO
#define PAD_CILINK_DEMOD1_CLK_IS_GPIO 0
#endif 

#define PAD_CILINK_RX1_D0 9999
#ifndef PAD_CILINK_RX1_D0_IS_GPIO
#define PAD_CILINK_RX1_D0_IS_GPIO 0
#endif 

#define PAD_CILINK_TX1_D1 9999
#ifndef PAD_CILINK_TX1_D1_IS_GPIO
#define PAD_CILINK_TX1_D1_IS_GPIO 0
#endif 

#define PAD_CILINK_RX1_D1 9999
#ifndef PAD_CILINK_RX1_D1_IS_GPIO
#define PAD_CILINK_RX1_D1_IS_GPIO 0
#endif 

#define BALL_P6 PAD_HDMIRX_ARCTX
#define PAD_HDMIRX_ARCTX 79
#define GPIO_PAD_79 GPIO78
#ifndef BALL_P6_IS_GPIO
#define BALL_P6_IS_GPIO 0
#endif 
#ifndef PAD_HDMIRX_ARCTX_IS_GPIO
#define PAD_HDMIRX_ARCTX_IS_GPIO BALL_P6_IS_GPIO
#endif 

#define BALL_F6 PAD_DDCR_DA
#define PAD_DDCR_DA 64
#define GPIO_PAD_64 GPIO63
#ifndef BALL_F6_IS_GPIO
#define BALL_F6_IS_GPIO 0
#endif 
#ifndef PAD_DDCR_DA_IS_GPIO
#define PAD_DDCR_DA_IS_GPIO BALL_F6_IS_GPIO
#endif 

#define BALL_E6 PAD_DDCR_CK
#define PAD_DDCR_CK 63
#define GPIO_PAD_63 GPIO62
#ifndef BALL_E6_IS_GPIO
#define BALL_E6_IS_GPIO 0
#endif 
#ifndef PAD_DDCR_CK_IS_GPIO
#define PAD_DDCR_CK_IS_GPIO BALL_E6_IS_GPIO
#endif 

#define BALL_J7 PAD_SPDIF_OUT
#define PAD_SPDIF_OUT 97
#define GPIO_PAD_97 GPIO96
#ifndef BALL_J7_IS_GPIO
#define BALL_J7_IS_GPIO 0
#endif 
#ifndef PAD_SPDIF_OUT_IS_GPIO
#define PAD_SPDIF_OUT_IS_GPIO BALL_J7_IS_GPIO
#endif 

#define BALL_J8 PAD_SPDIF_IN
#define PAD_SPDIF_IN 96
#define GPIO_PAD_96 GPIO95
#ifndef BALL_J8_IS_GPIO
#define BALL_J8_IS_GPIO 0
#endif 
#ifndef PAD_SPDIF_IN_IS_GPIO
#define PAD_SPDIF_IN_IS_GPIO BALL_J8_IS_GPIO
#endif 

#define BALL_J6 PAD_I2S_OUT_SD1
#define PAD_I2S_OUT_SD1 83
#define GPIO_PAD_83 GPIO82
#ifndef BALL_J6_IS_GPIO
#define BALL_J6_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_SD1_IS_GPIO
#define PAD_I2S_OUT_SD1_IS_GPIO BALL_J6_IS_GPIO
#endif 

#define BALL_J5 PAD_I2S_OUT_SD2
#define PAD_I2S_OUT_SD2 84
#define GPIO_PAD_84 GPIO83
#ifndef BALL_J5_IS_GPIO
#define BALL_J5_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_SD2_IS_GPIO
#define PAD_I2S_OUT_SD2_IS_GPIO BALL_J5_IS_GPIO
#endif 

#define BALL_G4 PAD_I2S_OUT_SD
#define PAD_I2S_OUT_SD 82
#define GPIO_PAD_82 GPIO81
#ifndef BALL_G4_IS_GPIO
#define BALL_G4_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_SD_IS_GPIO
#define PAD_I2S_OUT_SD_IS_GPIO BALL_G4_IS_GPIO
#endif 

#define BALL_G6 PAD_I2S_OUT_MCK
#define PAD_I2S_OUT_MCK 81
#define GPIO_PAD_81 GPIO80
#ifndef BALL_G6_IS_GPIO
#define BALL_G6_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_MCK_IS_GPIO
#define PAD_I2S_OUT_MCK_IS_GPIO BALL_G6_IS_GPIO
#endif 

#define BALL_G5 PAD_I2S_OUT_WS
#define PAD_I2S_OUT_WS 85
#define GPIO_PAD_85 GPIO84
#ifndef BALL_G5_IS_GPIO
#define BALL_G5_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_WS_IS_GPIO
#define PAD_I2S_OUT_WS_IS_GPIO BALL_G5_IS_GPIO
#endif 

#define BALL_G7 PAD_I2S_OUT_BCK
#define PAD_I2S_OUT_BCK 80
#define GPIO_PAD_80 GPIO79
#ifndef BALL_G7_IS_GPIO
#define BALL_G7_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_BCK_IS_GPIO
#define PAD_I2S_OUT_BCK_IS_GPIO BALL_G7_IS_GPIO
#endif 

#define BALL_D4 PAD_SAR0
#define PAD_SAR0 30
#define GPIO_PAD_30 GPIO29
#ifndef BALL_D4_IS_GPIO
#define BALL_D4_IS_GPIO 0
#endif 
#ifndef PAD_SAR0_IS_GPIO
#define PAD_SAR0_IS_GPIO BALL_D4_IS_GPIO
#endif 

#define BALL_D5 PAD_SAR1
#define PAD_SAR1 31
#define GPIO_PAD_31 GPIO30
#ifndef BALL_D5_IS_GPIO
#define BALL_D5_IS_GPIO 0
#endif 
#ifndef PAD_SAR1_IS_GPIO
#define PAD_SAR1_IS_GPIO BALL_D5_IS_GPIO
#endif 

#define BALL_D2 PAD_SAR2
#define PAD_SAR2 32
#define GPIO_PAD_32 GPIO31
#ifndef BALL_D2_IS_GPIO
#define BALL_D2_IS_GPIO 0
#endif 
#ifndef PAD_SAR2_IS_GPIO
#define PAD_SAR2_IS_GPIO BALL_D2_IS_GPIO
#endif 

#define PAD_SAR3 9999
#ifndef PAD_SAR3_IS_GPIO
#define PAD_SAR3_IS_GPIO 0
#endif 

#define PAD_SAR4 9999
#ifndef PAD_SAR4_IS_GPIO
#define PAD_SAR4_IS_GPIO 0
#endif 

#define BALL_E5 PAD_VPLUGIN
#define PAD_VPLUGIN 35
#define GPIO_PAD_35 GPIO34
#ifndef BALL_E5_IS_GPIO
#define BALL_E5_IS_GPIO 0
#endif 
#ifndef PAD_VPLUGIN_IS_GPIO
#define PAD_VPLUGIN_IS_GPIO BALL_E5_IS_GPIO
#endif 

#define BALL_AA5 PAD_I2S_IN_WS
#define PAD_I2S_IN_WS 42
#define GPIO_PAD_42 GPIO41
#ifndef BALL_AA5_IS_GPIO
#define BALL_AA5_IS_GPIO 0
#endif 
#ifndef PAD_I2S_IN_WS_IS_GPIO
#define PAD_I2S_IN_WS_IS_GPIO BALL_AA5_IS_GPIO
#endif 

#define PAD_WOL_INT_OUT 9999
#ifndef PAD_WOL_INT_OUT_IS_GPIO
#define PAD_WOL_INT_OUT_IS_GPIO 0
#endif 

#define PAD_VID3 9999
#ifndef PAD_VID3_IS_GPIO
#define PAD_VID3_IS_GPIO 0
#endif 

#define PAD_VID2 9999
#ifndef PAD_VID2_IS_GPIO
#define PAD_VID2_IS_GPIO 0
#endif 

#define BALL_AB4 PAD_VID1
#define PAD_VID1 37
#define GPIO_PAD_37 GPIO36
#ifndef BALL_AB4_IS_GPIO
#define BALL_AB4_IS_GPIO 0
#endif 
#ifndef PAD_VID1_IS_GPIO
#define PAD_VID1_IS_GPIO BALL_AB4_IS_GPIO
#endif 

#define BALL_F4 PAD_VID0
#define PAD_VID0 36
#define GPIO_PAD_36 GPIO35
#ifndef BALL_F4_IS_GPIO
#define BALL_F4_IS_GPIO 0
#endif 
#ifndef PAD_VID0_IS_GPIO
#define PAD_VID0_IS_GPIO BALL_F4_IS_GPIO
#endif 

#define BALL_U3 PAD_GPIO12_PM
#define PAD_GPIO12_PM 17
#define GPIO_PAD_17 GPIO16
#ifndef BALL_U3_IS_GPIO
#define BALL_U3_IS_GPIO 0
#endif 
#ifndef PAD_GPIO12_PM_IS_GPIO
#define PAD_GPIO12_PM_IS_GPIO BALL_U3_IS_GPIO
#endif 

#define BALL_W6 PAD_GPIO11_PM
#define PAD_GPIO11_PM 16
#define GPIO_PAD_16 GPIO15
#ifndef BALL_W6_IS_GPIO
#define BALL_W6_IS_GPIO 0
#endif 
#ifndef PAD_GPIO11_PM_IS_GPIO
#define PAD_GPIO11_PM_IS_GPIO BALL_W6_IS_GPIO
#endif 

#define PAD_GPIO7_PM 9999
#ifndef PAD_GPIO7_PM_IS_GPIO
#define PAD_GPIO7_PM_IS_GPIO 0
#endif 

#define BALL_E4 PAD_GPIO0_PM
#define PAD_GPIO0_PM 6
#define GPIO_PAD_6 GPIO5
#ifndef BALL_E4_IS_GPIO
#define BALL_E4_IS_GPIO 0
#endif 
#ifndef PAD_GPIO0_PM_IS_GPIO
#define PAD_GPIO0_PM_IS_GPIO BALL_E4_IS_GPIO
#endif 

#define BALL_C1 PAD_GPIO2_PM
#define PAD_GPIO2_PM 8
#define GPIO_PAD_8 GPIO7
#ifndef BALL_C1_IS_GPIO
#define BALL_C1_IS_GPIO 0
#endif 
#ifndef PAD_GPIO2_PM_IS_GPIO
#define PAD_GPIO2_PM_IS_GPIO BALL_C1_IS_GPIO
#endif 

#define PAD_GPIO8_PM 9999
#ifndef PAD_GPIO8_PM_IS_GPIO
#define PAD_GPIO8_PM_IS_GPIO 0
#endif 

#define BALL_F5 PAD_USB_CTRL
#define PAD_USB_CTRL 9
#define GPIO_PAD_9 GPIO8
#ifndef BALL_F5_IS_GPIO
#define BALL_F5_IS_GPIO 0
#endif 
#ifndef PAD_USB_CTRL_IS_GPIO
#define PAD_USB_CTRL_IS_GPIO BALL_F5_IS_GPIO
#endif 

#define BALL_AB6 PAD_PWM_PM
#define PAD_PWM_PM 3
#define GPIO_PAD_3 GPIO2
#ifndef BALL_AB6_IS_GPIO
#define BALL_AB6_IS_GPIO 0
#endif 
#ifndef PAD_PWM_PM_IS_GPIO
#define PAD_PWM_PM_IS_GPIO BALL_AB6_IS_GPIO
#endif 

#define BALL_N6 PAD_DDCDA_CK
#define PAD_DDCDA_CK 24
#define GPIO_PAD_24 GPIO23
#ifndef BALL_N6_IS_GPIO
#define BALL_N6_IS_GPIO 0
#endif 
#ifndef PAD_DDCDA_CK_IS_GPIO
#define PAD_DDCDA_CK_IS_GPIO BALL_N6_IS_GPIO
#endif 

#define BALL_R5 PAD_DDCDA_DA
#define PAD_DDCDA_DA 25
#define GPIO_PAD_25 GPIO24
#ifndef BALL_R5_IS_GPIO
#define BALL_R5_IS_GPIO 0
#endif 
#ifndef PAD_DDCDA_DA_IS_GPIO
#define PAD_DDCDA_DA_IS_GPIO BALL_R5_IS_GPIO
#endif 

#define BALL_P5 PAD_DDCDB_CK
#define PAD_DDCDB_CK 26
#define GPIO_PAD_26 GPIO25
#ifndef BALL_P5_IS_GPIO
#define BALL_P5_IS_GPIO 0
#endif 
#ifndef PAD_DDCDB_CK_IS_GPIO
#define PAD_DDCDB_CK_IS_GPIO BALL_P5_IS_GPIO
#endif 

#define BALL_P4 PAD_DDCDB_DA
#define PAD_DDCDB_DA 27
#define GPIO_PAD_27 GPIO26
#ifndef BALL_P4_IS_GPIO
#define BALL_P4_IS_GPIO 0
#endif 
#ifndef PAD_DDCDB_DA_IS_GPIO
#define PAD_DDCDB_DA_IS_GPIO BALL_P4_IS_GPIO
#endif 


// PADS group name to index
#define PADS_PCMCONFIG_MODE1        1223
#define PADS_PCMCONFIG_MODE2        1224
#define PADS_PCMCONFIG1_MODE1       1225
#define PADS_PCMCONFIG1_MODE2       1226
#define PADS_PCMCONFIG1_MODE3       1227
#define PADS_PCM2CONFIG_MODE1       1228
#define PADS_PCM2CONFIG_MODE2       1229
#define PADS_PCM2CONFIG_MODE3       1230
#define PADS_PCM2CONFIG1_MODE1      1231
#define PADS_PCM2CONFIG1_MODE2      1232
#define PADS_ET_MODE1               1233
#define PADS_ET_MODE2               1234
#define PADS_DDCR                   1235
#define PADS_DDCR2                  1236
#define PADS_PCM                    1237

// chip capbilities
#define CHIP_HAS_BT656_IN           0
#define CHIP_HAS_TS0                1
#define CHIP_HAS_TS1                0
#define CHIP_HAS_LVDS_10BIT_X2      1
#define CHIP_HAS_LVDS_8BIT_X2       1
#define CHIP_HAS_LVDS_8BIT_X1       1
#define CHIP_HAS_CIMAX              0
#define CHIP_HAS_USB_P0             1
#define CHIP_HAS_USB_P1             1
#define CHIP_HAS_USBVBUS0           0
#define CHIP_HAS_USBVBUS1           0
#define CHIP_HAS_UART1_MODE1        1
#define CHIP_HAS_UART1_MODE2        1
#define CHIP_HAS_UART1_MODE3        1
#define CHIP_HAS_PCMCIA1            0
#define CHIP_HAS_PCMCIA2            0
#define CHIP_HAS_PCMCIA             0
#define CHIP_HAS_UART2_MODE1        1
#define CHIP_HAS_UART2_MODE2        1
#define CHIP_HAS_UART2_MODE3        1
#define CHIP_HAS_RGB_A              1
#define CHIP_HAS_RGB_B              1
#define CHIP_HAS_RGB_C              1
#define CHIP_HAS_HDMI_A             1
#define CHIP_HAS_HDMI_B             1
#define CHIP_HAS_HDMI_C             1
#define CHIP_HAS_SPI_CZ1            1
#define CHIP_HAS_SPI_CZ2            0
#define CHIP_HAS_SPI_CZ3            0
#define CHIP_HAS_DDCR               1
#define CHIP_HAS_DDCR2              1
#define CHIP_HAS_TCON               1
#define CHIP_HAS_ET_MODE0_MII       1
#define CHIP_HAS_ET_MODE0_RMII      1
#define CHIP_HAS_ET_MODE1_MII       1
#define CHIP_HAS_ET_MODE1_RMII      1
#define CHIP_HAS_ET_MODE2_MII       1
#define CHIP_HAS_ET_MODE2_RMII      1
#define CHIP_HAS_I2S_IN             0
#define CHIP_HAS_I2S_OUT            0
#define CHIP_HAS_SPDIF_IN           0
#define CHIP_HAS_SPDIF_OUT          0
#define CHIP_HAS_DDR_A_CMD          1
#define CHIP_HAS_DDR_A_DATA         1
#define CHIP_HAS_DDR_B_CMD          1
#define CHIP_HAS_DDR_B_DATA         1
#define CHIP_USE_PCM_CDN_IN_PCM2    0
#define CHIP_USE_I2S_IN_IN_PCM      0
#define CHIP_USE_I2S_OUT_IN_PCM     0
#define CHIP_USE_SPDIF_IN_IN_PCM    0
#define CHIP_USE_SPDIF_OUT_IN_PCM   0
#define CHIP_USE_IIC_IN_DDCR2       0
#define CHIP_USE_PWM2_IN_GPIO14     0
#define CHIP_USE_PWM3_IN_GPIO15     0

// chip additional information
#define CHIP_FAMILY_TYPE            CHIP_FAMILY_MURPHY

#endif /* _MSD96BUXM8_NANYA_H_*/
