/* SPDX-License-Identifier: GPL-2.0-only OR BSD-3-Clause */
/******************************************************************************
 *
 * This file is provided under a dual license.  When you use or
 * distribute this software, you may choose to be licensed under
 * version 2 of the GNU General Public License ("GPLv2 License")
 * or BSD License.
 *
 * GPLv2 License
 *
 * Copyright(C) 2019 MediaTek Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of version 2 of the GNU General Public License as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See http://www.gnu.org/licenses/gpl-2.0.html for more details.
 *
 * BSD LICENSE
 *
 * Copyright(C) 2019 MediaTek Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *****************************************************************************/

// This file is generated by script, please do not edit it directly 
#ifndef _MSD8320YN_H_
#define _MSD8320YN_H_

#define PAD_NC 9999
#define PAD_GND 0

#define BALL_V4 PAD_GPIO_PM7
#define PAD_GPIO_PM7 16
#define GPIO_PAD_16 GPIO15
#ifndef BALL_V4_IS_GPIO
#define BALL_V4_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM7_IS_GPIO
#define PAD_GPIO_PM7_IS_GPIO BALL_V4_IS_GPIO
#endif 

#define BALL_E5 PAD_HOTPLUGD
#define PAD_HOTPLUGD 28
#define GPIO_PAD_28 GPIO27
#ifndef BALL_E5_IS_GPIO
#define BALL_E5_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGD_IS_GPIO
#define PAD_HOTPLUGD_IS_GPIO BALL_E5_IS_GPIO
#endif 

#define BALL_B2 PAD_GPIO_PM6
#define PAD_GPIO_PM6 15
#define GPIO_PAD_15 GPIO14
#ifndef BALL_B2_IS_GPIO
#define BALL_B2_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM6_IS_GPIO
#define PAD_GPIO_PM6_IS_GPIO BALL_B2_IS_GPIO
#endif 

#define BALL_T6 PAD_GPIO_PM5
#define PAD_GPIO_PM5 14
#define GPIO_PAD_14 GPIO13
#ifndef BALL_T6_IS_GPIO
#define BALL_T6_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM5_IS_GPIO
#define PAD_GPIO_PM5_IS_GPIO BALL_T6_IS_GPIO
#endif 

#define BALL_G6 PAD_GPIO_PM4
#define PAD_GPIO_PM4 13
#define GPIO_PAD_13 GPIO12
#ifndef BALL_G6_IS_GPIO
#define BALL_G6_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM4_IS_GPIO
#define PAD_GPIO_PM4_IS_GPIO BALL_G6_IS_GPIO
#endif 

#define BALL_U3 PAD_LED0
#define PAD_LED0 44
#define GPIO_PAD_44 GPIO43
#ifndef BALL_U3_IS_GPIO
#define BALL_U3_IS_GPIO 0
#endif 
#ifndef PAD_LED0_IS_GPIO
#define PAD_LED0_IS_GPIO BALL_U3_IS_GPIO
#endif 

#define PAD_GPIO_PM3 9999
#ifndef PAD_GPIO_PM3_IS_GPIO
#define PAD_GPIO_PM3_IS_GPIO 0
#endif 

#define PAD_LED1 9999
#ifndef PAD_LED1_IS_GPIO
#define PAD_LED1_IS_GPIO 0
#endif 

#define PAD_GPIO_PM2 9999
#ifndef PAD_GPIO_PM2_IS_GPIO
#define PAD_GPIO_PM2_IS_GPIO 0
#endif 

#define BALL_L6 PAD_WOL_INT
#define PAD_WOL_INT 46
#define GPIO_PAD_46 GPIO45
#ifndef BALL_L6_IS_GPIO
#define BALL_L6_IS_GPIO 0
#endif 
#ifndef PAD_WOL_INT_IS_GPIO
#define PAD_WOL_INT_IS_GPIO BALL_L6_IS_GPIO
#endif 

#define BALL_U6 PAD_GPIO_PM1
#define PAD_GPIO_PM1 10
#define GPIO_PAD_10 GPIO9
#ifndef BALL_U6_IS_GPIO
#define BALL_U6_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM1_IS_GPIO
#define PAD_GPIO_PM1_IS_GPIO BALL_U6_IS_GPIO
#endif 

#define BALL_U2 PAD_GPIO_PM0
#define PAD_GPIO_PM0 9
#define GPIO_PAD_9 GPIO8
#ifndef BALL_U2_IS_GPIO
#define BALL_U2_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM0_IS_GPIO
#define PAD_GPIO_PM0_IS_GPIO BALL_U2_IS_GPIO
#endif 

#define BALL_G4 PAD_IRIN
#define PAD_IRIN 37
#define GPIO_PAD_37 GPIO36
#ifndef BALL_G4_IS_GPIO
#define BALL_G4_IS_GPIO 0
#endif 
#ifndef PAD_IRIN_IS_GPIO
#define PAD_IRIN_IS_GPIO BALL_G4_IS_GPIO
#endif 

#define PAD_DDCDB_DA 9999
#ifndef PAD_DDCDB_DA_IS_GPIO
#define PAD_DDCDB_DA_IS_GPIO 0
#endif 

#define BALL_F7 PAD_PWM_PM
#define PAD_PWM_PM 5
#define GPIO_PAD_5 GPIO4
#ifndef BALL_F7_IS_GPIO
#define BALL_F7_IS_GPIO 0
#endif 
#ifndef PAD_PWM_PM_IS_GPIO
#define PAD_PWM_PM_IS_GPIO BALL_F7_IS_GPIO
#endif 

#define PAD_DDCDB_CK 9999
#ifndef PAD_DDCDB_CK_IS_GPIO
#define PAD_DDCDB_CK_IS_GPIO 0
#endif 

#define BALL_C3 PAD_PM_SPI_CZ
#define PAD_PM_SPI_CZ 1
#define GPIO_PAD_1 GPIO0
#ifndef BALL_C3_IS_GPIO
#define BALL_C3_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_CZ_IS_GPIO
#define PAD_PM_SPI_CZ_IS_GPIO BALL_C3_IS_GPIO
#endif 

#define PAD_HOTPLUGB 9999
#ifndef PAD_HOTPLUGB_IS_GPIO
#define PAD_HOTPLUGB_IS_GPIO 0
#endif 

#define BALL_H7 PAD_DDCDA_DA
#define PAD_DDCDA_DA 30
#define GPIO_PAD_30 GPIO29
#ifndef BALL_H7_IS_GPIO
#define BALL_H7_IS_GPIO 0
#endif 
#ifndef PAD_DDCDA_DA_IS_GPIO
#define PAD_DDCDA_DA_IS_GPIO BALL_H7_IS_GPIO
#endif 

#define BALL_V6 PAD_HOTPLUGA
#define PAD_HOTPLUGA 25
#define GPIO_PAD_25 GPIO24
#ifndef BALL_V6_IS_GPIO
#define BALL_V6_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGA_IS_GPIO
#define PAD_HOTPLUGA_IS_GPIO BALL_V6_IS_GPIO
#endif 

#define BALL_H6 PAD_DDCDA_CK
#define PAD_DDCDA_CK 29
#define GPIO_PAD_29 GPIO28
#ifndef BALL_H6_IS_GPIO
#define BALL_H6_IS_GPIO 0
#endif 
#ifndef PAD_DDCDA_CK_IS_GPIO
#define PAD_DDCDA_CK_IS_GPIO BALL_H6_IS_GPIO
#endif 

#define BALL_V5 PAD_CEC
#define PAD_CEC 8
#define GPIO_PAD_8 GPIO7
#ifndef BALL_V5_IS_GPIO
#define BALL_V5_IS_GPIO 0
#endif 
#ifndef PAD_CEC_IS_GPIO
#define PAD_CEC_IS_GPIO BALL_V5_IS_GPIO
#endif 

#define BALL_B3 PAD_PM_SPI_DI
#define PAD_PM_SPI_DI 3
#define GPIO_PAD_3 GPIO2
#ifndef BALL_B3_IS_GPIO
#define BALL_B3_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_DI_IS_GPIO
#define PAD_PM_SPI_DI_IS_GPIO BALL_B3_IS_GPIO
#endif 

#define BALL_A3 PAD_PM_SPI_CK
#define PAD_PM_SPI_CK 2
#define GPIO_PAD_2 GPIO1
#ifndef BALL_A3_IS_GPIO
#define BALL_A3_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_CK_IS_GPIO
#define PAD_PM_SPI_CK_IS_GPIO BALL_A3_IS_GPIO
#endif 

#define BALL_A2 PAD_PM_SPI_DO
#define PAD_PM_SPI_DO 4
#define GPIO_PAD_4 GPIO3
#ifndef BALL_A2_IS_GPIO
#define BALL_A2_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_DO_IS_GPIO
#define PAD_PM_SPI_DO_IS_GPIO BALL_A2_IS_GPIO
#endif 

#define BALL_D5 PAD_DDCA_DA
#define PAD_DDCA_DA 7
#define GPIO_PAD_7 GPIO6
#ifndef BALL_D5_IS_GPIO
#define BALL_D5_IS_GPIO 0
#endif 
#ifndef PAD_DDCA_DA_IS_GPIO
#define PAD_DDCA_DA_IS_GPIO BALL_D5_IS_GPIO
#endif 

#define BALL_D4 PAD_DDCA_CK
#define PAD_DDCA_CK 6
#define GPIO_PAD_6 GPIO5
#ifndef BALL_D4_IS_GPIO
#define BALL_D4_IS_GPIO 0
#endif 
#ifndef PAD_DDCA_CK_IS_GPIO
#define PAD_DDCA_CK_IS_GPIO BALL_D4_IS_GPIO
#endif 

#define BALL_U7 PAD_ARC0
#define PAD_ARC0 47
#define GPIO_PAD_47 GPIO46
#ifndef BALL_U7_IS_GPIO
#define BALL_U7_IS_GPIO 0
#endif 
#ifndef PAD_ARC0_IS_GPIO
#define PAD_ARC0_IS_GPIO BALL_U7_IS_GPIO
#endif 

#define BALL_Y2 PAD_TGPIO0
#define PAD_TGPIO0 162
#define GPIO_PAD_162 GPIO161
#ifndef BALL_Y2_IS_GPIO
#define BALL_Y2_IS_GPIO 0
#endif 
#ifndef PAD_TGPIO0_IS_GPIO
#define PAD_TGPIO0_IS_GPIO BALL_Y2_IS_GPIO
#endif 

#define BALL_V7 PAD_TGPIO1
#define PAD_TGPIO1 163
#define GPIO_PAD_163 GPIO162
#ifndef BALL_V7_IS_GPIO
#define BALL_V7_IS_GPIO 0
#endif 
#ifndef PAD_TGPIO1_IS_GPIO
#define PAD_TGPIO1_IS_GPIO BALL_V7_IS_GPIO
#endif 

#define BALL_Y4 PAD_TGPIO2
#define PAD_TGPIO2 164
#define GPIO_PAD_164 GPIO163
#ifndef BALL_Y4_IS_GPIO
#define BALL_Y4_IS_GPIO 0
#endif 
#ifndef PAD_TGPIO2_IS_GPIO
#define PAD_TGPIO2_IS_GPIO BALL_Y4_IS_GPIO
#endif 

#define BALL_W3 PAD_TGPIO3
#define PAD_TGPIO3 165
#define GPIO_PAD_165 GPIO164
#ifndef BALL_W3_IS_GPIO
#define BALL_W3_IS_GPIO 0
#endif 
#ifndef PAD_TGPIO3_IS_GPIO
#define PAD_TGPIO3_IS_GPIO BALL_W3_IS_GPIO
#endif 

#define BALL_AA7 PAD_DDCDC_DA
#define PAD_DDCDC_DA 34
#define GPIO_PAD_34 GPIO33
#ifndef BALL_AA7_IS_GPIO
#define BALL_AA7_IS_GPIO 0
#endif 
#ifndef PAD_DDCDC_DA_IS_GPIO
#define PAD_DDCDC_DA_IS_GPIO BALL_AA7_IS_GPIO
#endif 

#define BALL_Y7 PAD_DDCDC_CK
#define PAD_DDCDC_CK 33
#define GPIO_PAD_33 GPIO32
#ifndef BALL_Y7_IS_GPIO
#define BALL_Y7_IS_GPIO 0
#endif 
#ifndef PAD_DDCDC_CK_IS_GPIO
#define PAD_DDCDC_CK_IS_GPIO BALL_Y7_IS_GPIO
#endif 

#define BALL_W10 PAD_HOTPLUGC
#define PAD_HOTPLUGC 27
#define GPIO_PAD_27 GPIO26
#ifndef BALL_W10_IS_GPIO
#define BALL_W10_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGC_IS_GPIO
#define PAD_HOTPLUGC_IS_GPIO BALL_W10_IS_GPIO
#endif 

#define PAD_NAND_AD7 9999
#ifndef PAD_NAND_AD7_IS_GPIO
#define PAD_NAND_AD7_IS_GPIO 0
#endif 

#define BALL_Y15 PAD_TS1_D0
#define PAD_TS1_D0 178
#define GPIO_PAD_178 GPIO177
#ifndef BALL_Y15_IS_GPIO
#define BALL_Y15_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D0_IS_GPIO
#define PAD_TS1_D0_IS_GPIO BALL_Y15_IS_GPIO
#endif 

#define PAD_NAND_AD6 9999
#ifndef PAD_NAND_AD6_IS_GPIO
#define PAD_NAND_AD6_IS_GPIO 0
#endif 

#define BALL_W14 PAD_TS1_D1
#define PAD_TS1_D1 179
#define GPIO_PAD_179 GPIO178
#ifndef BALL_W14_IS_GPIO
#define BALL_W14_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D1_IS_GPIO
#define PAD_TS1_D1_IS_GPIO BALL_W14_IS_GPIO
#endif 

#define PAD_NAND_AD5 9999
#ifndef PAD_NAND_AD5_IS_GPIO
#define PAD_NAND_AD5_IS_GPIO 0
#endif 

#define BALL_Y14 PAD_TS1_D2
#define PAD_TS1_D2 180
#define GPIO_PAD_180 GPIO179
#ifndef BALL_Y14_IS_GPIO
#define BALL_Y14_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D2_IS_GPIO
#define PAD_TS1_D2_IS_GPIO BALL_Y14_IS_GPIO
#endif 

#define PAD_NAND_AD4 9999
#ifndef PAD_NAND_AD4_IS_GPIO
#define PAD_NAND_AD4_IS_GPIO 0
#endif 

#define BALL_AA14 PAD_TS1_D3
#define PAD_TS1_D3 181
#define GPIO_PAD_181 GPIO180
#ifndef BALL_AA14_IS_GPIO
#define BALL_AA14_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D3_IS_GPIO
#define PAD_TS1_D3_IS_GPIO BALL_AA14_IS_GPIO
#endif 

#define PAD_NAND_AD3 9999
#ifndef PAD_NAND_AD3_IS_GPIO
#define PAD_NAND_AD3_IS_GPIO 0
#endif 

#define BALL_AA13 PAD_TS1_D4
#define PAD_TS1_D4 182
#define GPIO_PAD_182 GPIO181
#ifndef BALL_AA13_IS_GPIO
#define BALL_AA13_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D4_IS_GPIO
#define PAD_TS1_D4_IS_GPIO BALL_AA13_IS_GPIO
#endif 

#define PAD_NAND_AD2 9999
#ifndef PAD_NAND_AD2_IS_GPIO
#define PAD_NAND_AD2_IS_GPIO 0
#endif 

#define BALL_Y13 PAD_TS1_D5
#define PAD_TS1_D5 183
#define GPIO_PAD_183 GPIO182
#ifndef BALL_Y13_IS_GPIO
#define BALL_Y13_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D5_IS_GPIO
#define PAD_TS1_D5_IS_GPIO BALL_Y13_IS_GPIO
#endif 

#define PAD_NAND_AD1 9999
#ifndef PAD_NAND_AD1_IS_GPIO
#define PAD_NAND_AD1_IS_GPIO 0
#endif 

#define BALL_Y12 PAD_TS1_D6
#define PAD_TS1_D6 184
#define GPIO_PAD_184 GPIO183
#ifndef BALL_Y12_IS_GPIO
#define BALL_Y12_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D6_IS_GPIO
#define PAD_TS1_D6_IS_GPIO BALL_Y12_IS_GPIO
#endif 

#define PAD_NAND_AD0 9999
#ifndef PAD_NAND_AD0_IS_GPIO
#define PAD_NAND_AD0_IS_GPIO 0
#endif 

#define BALL_W11 PAD_TS1_D7
#define PAD_TS1_D7 185
#define GPIO_PAD_185 GPIO184
#ifndef BALL_W11_IS_GPIO
#define BALL_W11_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D7_IS_GPIO
#define PAD_TS1_D7_IS_GPIO BALL_W11_IS_GPIO
#endif 

#define PAD_NAND_DQS 9999
#ifndef PAD_NAND_DQS_IS_GPIO
#define PAD_NAND_DQS_IS_GPIO 0
#endif 

#define BALL_W12 PAD_TS1_CLK
#define PAD_TS1_CLK 177
#define GPIO_PAD_177 GPIO176
#ifndef BALL_W12_IS_GPIO
#define BALL_W12_IS_GPIO 0
#endif 
#ifndef PAD_TS1_CLK_IS_GPIO
#define PAD_TS1_CLK_IS_GPIO BALL_W12_IS_GPIO
#endif 

#define BALL_W15 PAD_TS1_SYNC
#define PAD_TS1_SYNC 186
#define GPIO_PAD_186 GPIO185
#ifndef BALL_W15_IS_GPIO
#define BALL_W15_IS_GPIO 0
#endif 
#ifndef PAD_TS1_SYNC_IS_GPIO
#define PAD_TS1_SYNC_IS_GPIO BALL_W15_IS_GPIO
#endif 

#define BALL_V12 PAD_NAND_REZ
#define PAD_NAND_REZ 102
#define GPIO_PAD_102 GPIO101
#ifndef BALL_V12_IS_GPIO
#define BALL_V12_IS_GPIO 0
#endif 
#ifndef PAD_NAND_REZ_IS_GPIO
#define PAD_NAND_REZ_IS_GPIO BALL_V12_IS_GPIO
#endif 

#define BALL_W13 PAD_TS1_VLD
#define PAD_TS1_VLD 187
#define GPIO_PAD_187 GPIO186
#ifndef BALL_W13_IS_GPIO
#define BALL_W13_IS_GPIO 0
#endif 
#ifndef PAD_TS1_VLD_IS_GPIO
#define PAD_TS1_VLD_IS_GPIO BALL_W13_IS_GPIO
#endif 

#define BALL_V11 PAD_NAND_CLE
#define PAD_NAND_CLE 99
#define GPIO_PAD_99 GPIO98
#ifndef BALL_V11_IS_GPIO
#define BALL_V11_IS_GPIO 0
#endif 
#ifndef PAD_NAND_CLE_IS_GPIO
#define PAD_NAND_CLE_IS_GPIO BALL_V11_IS_GPIO
#endif 

#define BALL_W20 PAD_PCM_D0
#define PAD_PCM_D0 122
#define GPIO_PAD_122 GPIO121
#ifndef BALL_W20_IS_GPIO
#define BALL_W20_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D0_IS_GPIO
#define PAD_PCM_D0_IS_GPIO BALL_W20_IS_GPIO
#endif 

#define BALL_T11 PAD_NAND_ALE
#define PAD_NAND_ALE 96
#define GPIO_PAD_96 GPIO95
#ifndef BALL_T11_IS_GPIO
#define BALL_T11_IS_GPIO 0
#endif 
#ifndef PAD_NAND_ALE_IS_GPIO
#define PAD_NAND_ALE_IS_GPIO BALL_T11_IS_GPIO
#endif 

#define BALL_W21 PAD_PCM_D1
#define PAD_PCM_D1 123
#define GPIO_PAD_123 GPIO122
#ifndef BALL_W21_IS_GPIO
#define BALL_W21_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D1_IS_GPIO
#define PAD_PCM_D1_IS_GPIO BALL_W21_IS_GPIO
#endif 

#define BALL_T12 PAD_NAND_CEZ
#define PAD_NAND_CEZ 97
#define GPIO_PAD_97 GPIO96
#ifndef BALL_T12_IS_GPIO
#define BALL_T12_IS_GPIO 0
#endif 
#ifndef PAD_NAND_CEZ_IS_GPIO
#define PAD_NAND_CEZ_IS_GPIO BALL_T12_IS_GPIO
#endif 

#define PAD_NAND_CEZ1 9999
#ifndef PAD_NAND_CEZ1_IS_GPIO
#define PAD_NAND_CEZ1_IS_GPIO 0
#endif 

#define BALL_U10 PAD_NAND_WPZ
#define PAD_NAND_WPZ 104
#define GPIO_PAD_104 GPIO103
#ifndef BALL_U10_IS_GPIO
#define BALL_U10_IS_GPIO 0
#endif 
#ifndef PAD_NAND_WPZ_IS_GPIO
#define PAD_NAND_WPZ_IS_GPIO BALL_U10_IS_GPIO
#endif 

#define BALL_V19 PAD_PCM_D2
#define PAD_PCM_D2 124
#define GPIO_PAD_124 GPIO123
#ifndef BALL_V19_IS_GPIO
#define BALL_V19_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D2_IS_GPIO
#define PAD_PCM_D2_IS_GPIO BALL_V19_IS_GPIO
#endif 

#define BALL_U11 PAD_NAND_WEZ
#define PAD_NAND_WEZ 103
#define GPIO_PAD_103 GPIO102
#ifndef BALL_U11_IS_GPIO
#define BALL_U11_IS_GPIO 0
#endif 
#ifndef PAD_NAND_WEZ_IS_GPIO
#define PAD_NAND_WEZ_IS_GPIO BALL_U11_IS_GPIO
#endif 

#define BALL_Y16 PAD_PCM_D3
#define PAD_PCM_D3 125
#define GPIO_PAD_125 GPIO124
#ifndef BALL_Y16_IS_GPIO
#define BALL_Y16_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D3_IS_GPIO
#define PAD_PCM_D3_IS_GPIO BALL_Y16_IS_GPIO
#endif 

#define BALL_U12 PAD_NAND_RBZ
#define PAD_NAND_RBZ 101
#define GPIO_PAD_101 GPIO100
#ifndef BALL_U12_IS_GPIO
#define BALL_U12_IS_GPIO 0
#endif 
#ifndef PAD_NAND_RBZ_IS_GPIO
#define PAD_NAND_RBZ_IS_GPIO BALL_U12_IS_GPIO
#endif 

#define BALL_AA16 PAD_PCM_D4
#define PAD_PCM_D4 126
#define GPIO_PAD_126 GPIO125
#ifndef BALL_AA16_IS_GPIO
#define BALL_AA16_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D4_IS_GPIO
#define PAD_PCM_D4_IS_GPIO BALL_AA16_IS_GPIO
#endif 

#define BALL_U16 PAD_TS0_D0
#define PAD_TS0_D0 167
#define GPIO_PAD_167 GPIO166
#ifndef BALL_U16_IS_GPIO
#define BALL_U16_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D0_IS_GPIO
#define PAD_TS0_D0_IS_GPIO BALL_U16_IS_GPIO
#endif 

#define BALL_W16 PAD_PCM_D5
#define PAD_PCM_D5 127
#define GPIO_PAD_127 GPIO126
#ifndef BALL_W16_IS_GPIO
#define BALL_W16_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D5_IS_GPIO
#define PAD_PCM_D5_IS_GPIO BALL_W16_IS_GPIO
#endif 

#define BALL_T14 PAD_TS0_D1
#define PAD_TS0_D1 168
#define GPIO_PAD_168 GPIO167
#ifndef BALL_T14_IS_GPIO
#define BALL_T14_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D1_IS_GPIO
#define PAD_TS0_D1_IS_GPIO BALL_T14_IS_GPIO
#endif 

#define BALL_AA17 PAD_PCM_D6
#define PAD_PCM_D6 128
#define GPIO_PAD_128 GPIO127
#ifndef BALL_AA17_IS_GPIO
#define BALL_AA17_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D6_IS_GPIO
#define PAD_PCM_D6_IS_GPIO BALL_AA17_IS_GPIO
#endif 

#define BALL_T15 PAD_TS0_D2
#define PAD_TS0_D2 169
#define GPIO_PAD_169 GPIO168
#ifndef BALL_T15_IS_GPIO
#define BALL_T15_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D2_IS_GPIO
#define PAD_TS0_D2_IS_GPIO BALL_T15_IS_GPIO
#endif 

#define BALL_V17 PAD_TS0_D3
#define PAD_TS0_D3 170
#define GPIO_PAD_170 GPIO169
#ifndef BALL_V17_IS_GPIO
#define BALL_V17_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D3_IS_GPIO
#define PAD_TS0_D3_IS_GPIO BALL_V17_IS_GPIO
#endif 

#define BALL_Y17 PAD_PCM_D7
#define PAD_PCM_D7 129
#define GPIO_PAD_129 GPIO128
#ifndef BALL_Y17_IS_GPIO
#define BALL_Y17_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D7_IS_GPIO
#define PAD_PCM_D7_IS_GPIO BALL_Y17_IS_GPIO
#endif 

#define BALL_U15 PAD_TS0_D4
#define PAD_TS0_D4 171
#define GPIO_PAD_171 GPIO170
#ifndef BALL_U15_IS_GPIO
#define BALL_U15_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D4_IS_GPIO
#define PAD_TS0_D4_IS_GPIO BALL_U15_IS_GPIO
#endif 

#define BALL_W19 PAD_PCM_WE_N
#define PAD_PCM_WE_N 137
#define GPIO_PAD_137 GPIO136
#ifndef BALL_W19_IS_GPIO
#define BALL_W19_IS_GPIO 0
#endif 
#ifndef PAD_PCM_WE_N_IS_GPIO
#define PAD_PCM_WE_N_IS_GPIO BALL_W19_IS_GPIO
#endif 

#define BALL_U14 PAD_TS0_D5
#define PAD_TS0_D5 172
#define GPIO_PAD_172 GPIO171
#ifndef BALL_U14_IS_GPIO
#define BALL_U14_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D5_IS_GPIO
#define PAD_TS0_D5_IS_GPIO BALL_U14_IS_GPIO
#endif 

#define BALL_Y21 PAD_PCM_REG_N
#define PAD_PCM_REG_N 134
#define GPIO_PAD_134 GPIO133
#ifndef BALL_Y21_IS_GPIO
#define BALL_Y21_IS_GPIO 0
#endif 
#ifndef PAD_PCM_REG_N_IS_GPIO
#define PAD_PCM_REG_N_IS_GPIO BALL_Y21_IS_GPIO
#endif 

#define BALL_V16 PAD_TS0_D6
#define PAD_TS0_D6 173
#define GPIO_PAD_173 GPIO172
#ifndef BALL_V16_IS_GPIO
#define BALL_V16_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D6_IS_GPIO
#define PAD_TS0_D6_IS_GPIO BALL_V16_IS_GPIO
#endif 

#define PAD_PCM2_IRQA_N 9999
#ifndef PAD_PCM2_IRQA_N_IS_GPIO
#define PAD_PCM2_IRQA_N_IS_GPIO 0
#endif 

#define BALL_U13 PAD_TS0_D7
#define PAD_TS0_D7 174
#define GPIO_PAD_174 GPIO173
#ifndef BALL_U13_IS_GPIO
#define BALL_U13_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D7_IS_GPIO
#define PAD_TS0_D7_IS_GPIO BALL_U13_IS_GPIO
#endif 

#define PAD_PCM2_WAIT_N 9999
#ifndef PAD_PCM2_WAIT_N_IS_GPIO
#define PAD_PCM2_WAIT_N_IS_GPIO 0
#endif 

#define BALL_V15 PAD_TS0_VLD
#define PAD_TS0_VLD 176
#define GPIO_PAD_176 GPIO175
#ifndef BALL_V15_IS_GPIO
#define BALL_V15_IS_GPIO 0
#endif 
#ifndef PAD_TS0_VLD_IS_GPIO
#define PAD_TS0_VLD_IS_GPIO BALL_V15_IS_GPIO
#endif 

#define PAD_PCM2_CE_N 9999
#ifndef PAD_PCM2_CE_N_IS_GPIO
#define PAD_PCM2_CE_N_IS_GPIO 0
#endif 

#define BALL_T13 PAD_TS0_CLK
#define PAD_TS0_CLK 166
#define GPIO_PAD_166 GPIO165
#ifndef BALL_T13_IS_GPIO
#define BALL_T13_IS_GPIO 0
#endif 
#ifndef PAD_TS0_CLK_IS_GPIO
#define PAD_TS0_CLK_IS_GPIO BALL_T13_IS_GPIO
#endif 

#define PAD_PCM2_CD_N 9999
#ifndef PAD_PCM2_CD_N_IS_GPIO
#define PAD_PCM2_CD_N_IS_GPIO 0
#endif 

#define BALL_V14 PAD_TS0_SYNC
#define PAD_TS0_SYNC 175
#define GPIO_PAD_175 GPIO174
#ifndef BALL_V14_IS_GPIO
#define BALL_V14_IS_GPIO 0
#endif 
#ifndef PAD_TS0_SYNC_IS_GPIO
#define PAD_TS0_SYNC_IS_GPIO BALL_V14_IS_GPIO
#endif 

#define BALL_Y18 PAD_PCM_IORD_N
#define PAD_PCM_IORD_N 130
#define GPIO_PAD_130 GPIO129
#ifndef BALL_Y18_IS_GPIO
#define BALL_Y18_IS_GPIO 0
#endif 
#ifndef PAD_PCM_IORD_N_IS_GPIO
#define PAD_PCM_IORD_N_IS_GPIO BALL_Y18_IS_GPIO
#endif 

#define BALL_U17 PAD_PCM_A0
#define PAD_PCM_A0 105
#define GPIO_PAD_105 GPIO104
#ifndef BALL_U17_IS_GPIO
#define BALL_U17_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A0_IS_GPIO
#define PAD_PCM_A0_IS_GPIO BALL_U17_IS_GPIO
#endif 

#define BALL_R19 PAD_PCM_A1
#define PAD_PCM_A1 106
#define GPIO_PAD_106 GPIO105
#ifndef BALL_R19_IS_GPIO
#define BALL_R19_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A1_IS_GPIO
#define PAD_PCM_A1_IS_GPIO BALL_R19_IS_GPIO
#endif 

#define BALL_W18 PAD_PCM_IOWR_N
#define PAD_PCM_IOWR_N 131
#define GPIO_PAD_131 GPIO130
#ifndef BALL_W18_IS_GPIO
#define BALL_W18_IS_GPIO 0
#endif 
#ifndef PAD_PCM_IOWR_N_IS_GPIO
#define PAD_PCM_IOWR_N_IS_GPIO BALL_W18_IS_GPIO
#endif 

#define BALL_T21 PAD_PCM_A2
#define PAD_PCM_A2 112
#define GPIO_PAD_112 GPIO111
#ifndef BALL_T21_IS_GPIO
#define BALL_T21_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A2_IS_GPIO
#define PAD_PCM_A2_IS_GPIO BALL_T21_IS_GPIO
#endif 

#define BALL_AA20 PAD_PCM_IRQA_N
#define PAD_PCM_IRQA_N 132
#define GPIO_PAD_132 GPIO131
#ifndef BALL_AA20_IS_GPIO
#define BALL_AA20_IS_GPIO 0
#endif 
#ifndef PAD_PCM_IRQA_N_IS_GPIO
#define PAD_PCM_IRQA_N_IS_GPIO BALL_AA20_IS_GPIO
#endif 

#define BALL_T20 PAD_PCM_A3
#define PAD_PCM_A3 113
#define GPIO_PAD_113 GPIO112
#ifndef BALL_T20_IS_GPIO
#define BALL_T20_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A3_IS_GPIO
#define PAD_PCM_A3_IS_GPIO BALL_T20_IS_GPIO
#endif 

#define PAD_PCM2_RESET 9999
#ifndef PAD_PCM2_RESET_IS_GPIO
#define PAD_PCM2_RESET_IS_GPIO 0
#endif 

#define BALL_T19 PAD_PCM_A4
#define PAD_PCM_A4 114
#define GPIO_PAD_114 GPIO113
#ifndef BALL_T19_IS_GPIO
#define BALL_T19_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A4_IS_GPIO
#define PAD_PCM_A4_IS_GPIO BALL_T19_IS_GPIO
#endif 

#define BALL_V21 PAD_PCM_CD_N
#define PAD_PCM_CD_N 120
#define GPIO_PAD_120 GPIO119
#ifndef BALL_V21_IS_GPIO
#define BALL_V21_IS_GPIO 0
#endif 
#ifndef PAD_PCM_CD_N_IS_GPIO
#define PAD_PCM_CD_N_IS_GPIO BALL_V21_IS_GPIO
#endif 

#define BALL_U20 PAD_PCM_A5
#define PAD_PCM_A5 115
#define GPIO_PAD_115 GPIO114
#ifndef BALL_U20_IS_GPIO
#define BALL_U20_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A5_IS_GPIO
#define PAD_PCM_A5_IS_GPIO BALL_U20_IS_GPIO
#endif 

#define BALL_R18 PAD_PCM_CE_N
#define PAD_PCM_CE_N 121
#define GPIO_PAD_121 GPIO120
#ifndef BALL_R18_IS_GPIO
#define BALL_R18_IS_GPIO 0
#endif 
#ifndef PAD_PCM_CE_N_IS_GPIO
#define PAD_PCM_CE_N_IS_GPIO BALL_R18_IS_GPIO
#endif 

#define BALL_U19 PAD_PCM_A6
#define PAD_PCM_A6 116
#define GPIO_PAD_116 GPIO115
#ifndef BALL_U19_IS_GPIO
#define BALL_U19_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A6_IS_GPIO
#define PAD_PCM_A6_IS_GPIO BALL_U19_IS_GPIO
#endif 

#define BALL_W17 PAD_PCM_OE_N
#define PAD_PCM_OE_N 133
#define GPIO_PAD_133 GPIO132
#ifndef BALL_W17_IS_GPIO
#define BALL_W17_IS_GPIO 0
#endif 
#ifndef PAD_PCM_OE_N_IS_GPIO
#define PAD_PCM_OE_N_IS_GPIO BALL_W17_IS_GPIO
#endif 

#define BALL_V20 PAD_PCM_A7
#define PAD_PCM_A7 117
#define GPIO_PAD_117 GPIO116
#ifndef BALL_V20_IS_GPIO
#define BALL_V20_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A7_IS_GPIO
#define PAD_PCM_A7_IS_GPIO BALL_V20_IS_GPIO
#endif 

#define BALL_T18 PAD_PCM_WAIT_N
#define PAD_PCM_WAIT_N 136
#define GPIO_PAD_136 GPIO135
#ifndef BALL_T18_IS_GPIO
#define BALL_T18_IS_GPIO 0
#endif 
#ifndef PAD_PCM_WAIT_N_IS_GPIO
#define PAD_PCM_WAIT_N_IS_GPIO BALL_T18_IS_GPIO
#endif 

#define BALL_Y19 PAD_PCM_A8
#define PAD_PCM_A8 118
#define GPIO_PAD_118 GPIO117
#ifndef BALL_Y19_IS_GPIO
#define BALL_Y19_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A8_IS_GPIO
#define PAD_PCM_A8_IS_GPIO BALL_Y19_IS_GPIO
#endif 

#define BALL_Y20 PAD_PCM_RESET
#define PAD_PCM_RESET 135
#define GPIO_PAD_135 GPIO134
#ifndef BALL_Y20_IS_GPIO
#define BALL_Y20_IS_GPIO 0
#endif 
#ifndef PAD_PCM_RESET_IS_GPIO
#define PAD_PCM_RESET_IS_GPIO BALL_Y20_IS_GPIO
#endif 

#define BALL_R17 PAD_PCM_A9
#define PAD_PCM_A9 119
#define GPIO_PAD_119 GPIO118
#ifndef BALL_R17_IS_GPIO
#define BALL_R17_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A9_IS_GPIO
#define PAD_PCM_A9_IS_GPIO BALL_R17_IS_GPIO
#endif 

#define BALL_U18 PAD_PCM_A13
#define PAD_PCM_A13 110
#define GPIO_PAD_110 GPIO109
#ifndef BALL_U18_IS_GPIO
#define BALL_U18_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A13_IS_GPIO
#define PAD_PCM_A13_IS_GPIO BALL_U18_IS_GPIO
#endif 

#define BALL_T17 PAD_PCM_A10
#define PAD_PCM_A10 107
#define GPIO_PAD_107 GPIO106
#ifndef BALL_T17_IS_GPIO
#define BALL_T17_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A10_IS_GPIO
#define PAD_PCM_A10_IS_GPIO BALL_T17_IS_GPIO
#endif 

#define BALL_AA19 PAD_PCM_A14
#define PAD_PCM_A14 111
#define GPIO_PAD_111 GPIO110
#ifndef BALL_AA19_IS_GPIO
#define BALL_AA19_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A14_IS_GPIO
#define PAD_PCM_A14_IS_GPIO BALL_AA19_IS_GPIO
#endif 

#define BALL_T16 PAD_PCM_A11
#define PAD_PCM_A11 108
#define GPIO_PAD_108 GPIO107
#ifndef BALL_T16_IS_GPIO
#define BALL_T16_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A11_IS_GPIO
#define PAD_PCM_A11_IS_GPIO BALL_T16_IS_GPIO
#endif 

#define BALL_V18 PAD_PCM_A12
#define PAD_PCM_A12 109
#define GPIO_PAD_109 GPIO108
#ifndef BALL_V18_IS_GPIO
#define BALL_V18_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A12_IS_GPIO
#define PAD_PCM_A12_IS_GPIO BALL_V18_IS_GPIO
#endif 

#define BALL_L17 PAD_DDCR_CK
#define PAD_DDCR_CK 48
#define GPIO_PAD_48 GPIO47
#ifndef BALL_L17_IS_GPIO
#define BALL_L17_IS_GPIO 0
#endif 
#ifndef PAD_DDCR_CK_IS_GPIO
#define PAD_DDCR_CK_IS_GPIO BALL_L17_IS_GPIO
#endif 

#define BALL_L18 PAD_DDCR_DA
#define PAD_DDCR_DA 49
#define GPIO_PAD_49 GPIO48
#ifndef BALL_L18_IS_GPIO
#define BALL_L18_IS_GPIO 0
#endif 
#ifndef PAD_DDCR_DA_IS_GPIO
#define PAD_DDCR_DA_IS_GPIO BALL_L18_IS_GPIO
#endif 

#define BALL_D20 PAD_UART_RX2
#define PAD_UART_RX2 188
#define GPIO_PAD_188 GPIO187
#ifndef BALL_D20_IS_GPIO
#define BALL_D20_IS_GPIO 0
#endif 
#ifndef PAD_UART_RX2_IS_GPIO
#define PAD_UART_RX2_IS_GPIO BALL_D20_IS_GPIO
#endif 

#define BALL_D19 PAD_UART_TX2
#define PAD_UART_TX2 189
#define GPIO_PAD_189 GPIO188
#ifndef BALL_D19_IS_GPIO
#define BALL_D19_IS_GPIO 0
#endif 
#ifndef PAD_UART_TX2_IS_GPIO
#define PAD_UART_TX2_IS_GPIO BALL_D19_IS_GPIO
#endif 

#define PAD_TCON3 9999
#ifndef PAD_TCON3_IS_GPIO
#define PAD_TCON3_IS_GPIO 0
#endif 

#define PAD_TCON7 9999
#ifndef PAD_TCON7_IS_GPIO
#define PAD_TCON7_IS_GPIO 0
#endif 

#define PAD_TCON2 9999
#ifndef PAD_TCON2_IS_GPIO
#define PAD_TCON2_IS_GPIO 0
#endif 

#define PAD_TCON6 9999
#ifndef PAD_TCON6_IS_GPIO
#define PAD_TCON6_IS_GPIO 0
#endif 

#define PAD_TCON1 9999
#ifndef PAD_TCON1_IS_GPIO
#define PAD_TCON1_IS_GPIO 0
#endif 

#define PAD_TCON5 9999
#ifndef PAD_TCON5_IS_GPIO
#define PAD_TCON5_IS_GPIO 0
#endif 

#define PAD_TCON0 9999
#ifndef PAD_TCON0_IS_GPIO
#define PAD_TCON0_IS_GPIO 0
#endif 

#define PAD_TCON4 9999
#ifndef PAD_TCON4_IS_GPIO
#define PAD_TCON4_IS_GPIO 0
#endif 

#define PAD_SPI2_CK 9999
#ifndef PAD_SPI2_CK_IS_GPIO
#define PAD_SPI2_CK_IS_GPIO 0
#endif 

#define BALL_R16 PAD_SPI1_DI
#define PAD_SPI1_DI 151
#define GPIO_PAD_151 GPIO150
#ifndef BALL_R16_IS_GPIO
#define BALL_R16_IS_GPIO 0
#endif 
#ifndef PAD_SPI1_DI_IS_GPIO
#define PAD_SPI1_DI_IS_GPIO BALL_R16_IS_GPIO
#endif 

#define BALL_P18 PAD_SPI1_CK
#define PAD_SPI1_CK 150
#define GPIO_PAD_150 GPIO149
#ifndef BALL_P18_IS_GPIO
#define BALL_P18_IS_GPIO 0
#endif 
#ifndef PAD_SPI1_CK_IS_GPIO
#define PAD_SPI1_CK_IS_GPIO BALL_P18_IS_GPIO
#endif 

#define BALL_M17 PAD_PWM0
#define PAD_PWM0 143
#define GPIO_PAD_143 GPIO142
#ifndef BALL_M17_IS_GPIO
#define BALL_M17_IS_GPIO 0
#endif 
#ifndef PAD_PWM0_IS_GPIO
#define PAD_PWM0_IS_GPIO BALL_M17_IS_GPIO
#endif 

#define BALL_N17 PAD_PWM1
#define PAD_PWM1 144
#define GPIO_PAD_144 GPIO143
#ifndef BALL_N17_IS_GPIO
#define BALL_N17_IS_GPIO 0
#endif 
#ifndef PAD_PWM1_IS_GPIO
#define PAD_PWM1_IS_GPIO BALL_N17_IS_GPIO
#endif 

#define BALL_N16 PAD_PWM2
#define PAD_PWM2 145
#define GPIO_PAD_145 GPIO144
#ifndef BALL_N16_IS_GPIO
#define BALL_N16_IS_GPIO 0
#endif 
#ifndef PAD_PWM2_IS_GPIO
#define PAD_PWM2_IS_GPIO BALL_N16_IS_GPIO
#endif 

#define BALL_N18 PAD_PWM3
#define PAD_PWM3 146
#define GPIO_PAD_146 GPIO145
#ifndef BALL_N18_IS_GPIO
#define BALL_N18_IS_GPIO 0
#endif 
#ifndef PAD_PWM3_IS_GPIO
#define PAD_PWM3_IS_GPIO BALL_N18_IS_GPIO
#endif 

#define BALL_P17 PAD_VSYNC_LIKE
#define PAD_VSYNC_LIKE 190
#define GPIO_PAD_190 GPIO189
#ifndef BALL_P17_IS_GPIO
#define BALL_P17_IS_GPIO 0
#endif 
#ifndef PAD_VSYNC_LIKE_IS_GPIO
#define PAD_VSYNC_LIKE_IS_GPIO BALL_P17_IS_GPIO
#endif 

#define BALL_M18 PAD_PWM4
#define PAD_PWM4 147
#define GPIO_PAD_147 GPIO146
#ifndef BALL_M18_IS_GPIO
#define BALL_M18_IS_GPIO 0
#endif 
#ifndef PAD_PWM4_IS_GPIO
#define PAD_PWM4_IS_GPIO BALL_M18_IS_GPIO
#endif 

#define PAD_SPI2_DI 9999
#ifndef PAD_SPI2_DI_IS_GPIO
#define PAD_SPI2_DI_IS_GPIO 0
#endif 

#define PAD_GPIO9 9999
#ifndef PAD_GPIO9_IS_GPIO
#define PAD_GPIO9_IS_GPIO 0
#endif 

#define PAD_GPIO10 9999
#ifndef PAD_GPIO10_IS_GPIO
#define PAD_GPIO10_IS_GPIO 0
#endif 

#define BALL_B13 PAD_I2S_IN_WS
#define PAD_I2S_IN_WS 80
#define GPIO_PAD_80 GPIO79
#ifndef BALL_B13_IS_GPIO
#define BALL_B13_IS_GPIO 0
#endif 
#ifndef PAD_I2S_IN_WS_IS_GPIO
#define PAD_I2S_IN_WS_IS_GPIO BALL_B13_IS_GPIO
#endif 

#define BALL_C11 PAD_GPIO11
#define PAD_GPIO11 53
#define GPIO_PAD_53 GPIO52
#ifndef BALL_C11_IS_GPIO
#define BALL_C11_IS_GPIO 0
#endif 
#ifndef PAD_GPIO11_IS_GPIO
#define PAD_GPIO11_IS_GPIO BALL_C11_IS_GPIO
#endif 

#define BALL_B14 PAD_I2S_IN_BCK
#define PAD_I2S_IN_BCK 78
#define GPIO_PAD_78 GPIO77
#ifndef BALL_B14_IS_GPIO
#define BALL_B14_IS_GPIO 0
#endif 
#ifndef PAD_I2S_IN_BCK_IS_GPIO
#define PAD_I2S_IN_BCK_IS_GPIO BALL_B14_IS_GPIO
#endif 

#define BALL_B10 PAD_GPIO12
#define PAD_GPIO12 54
#define GPIO_PAD_54 GPIO53
#ifndef BALL_B10_IS_GPIO
#define BALL_B10_IS_GPIO 0
#endif 
#ifndef PAD_GPIO12_IS_GPIO
#define PAD_GPIO12_IS_GPIO BALL_B10_IS_GPIO
#endif 

#define BALL_C14 PAD_I2S_IN_SD
#define PAD_I2S_IN_SD 79
#define GPIO_PAD_79 GPIO78
#ifndef BALL_C14_IS_GPIO
#define BALL_C14_IS_GPIO 0
#endif 
#ifndef PAD_I2S_IN_SD_IS_GPIO
#define PAD_I2S_IN_SD_IS_GPIO BALL_C14_IS_GPIO
#endif 

#define PAD_GPIO13 9999
#ifndef PAD_GPIO13_IS_GPIO
#define PAD_GPIO13_IS_GPIO 0
#endif 

#define BALL_C13 PAD_I2S_OUT_MCK
#define PAD_I2S_OUT_MCK 82
#define GPIO_PAD_82 GPIO81
#ifndef BALL_C13_IS_GPIO
#define BALL_C13_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_MCK_IS_GPIO
#define PAD_I2S_OUT_MCK_IS_GPIO BALL_C13_IS_GPIO
#endif 

#define BALL_F9 PAD_GPIO14
#define PAD_GPIO14 56
#define GPIO_PAD_56 GPIO55
#ifndef BALL_F9_IS_GPIO
#define BALL_F9_IS_GPIO 0
#endif 
#ifndef PAD_GPIO14_IS_GPIO
#define PAD_GPIO14_IS_GPIO BALL_F9_IS_GPIO
#endif 

#define BALL_A13 PAD_I2S_OUT_WS
#define PAD_I2S_OUT_WS 87
#define GPIO_PAD_87 GPIO86
#ifndef BALL_A13_IS_GPIO
#define BALL_A13_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_WS_IS_GPIO
#define PAD_I2S_OUT_WS_IS_GPIO BALL_A13_IS_GPIO
#endif 

#define BALL_F8 PAD_GPIO15
#define PAD_GPIO15 57
#define GPIO_PAD_57 GPIO56
#ifndef BALL_F8_IS_GPIO
#define BALL_F8_IS_GPIO 0
#endif 
#ifndef PAD_GPIO15_IS_GPIO
#define PAD_GPIO15_IS_GPIO BALL_F8_IS_GPIO
#endif 

#define PAD_I2S_OUT_SD1 9999
#ifndef PAD_I2S_OUT_SD1_IS_GPIO
#define PAD_I2S_OUT_SD1_IS_GPIO 0
#endif 

#define PAD_GPIO16 9999
#ifndef PAD_GPIO16_IS_GPIO
#define PAD_GPIO16_IS_GPIO 0
#endif 

#define BALL_A12 PAD_I2S_OUT_BCK
#define PAD_I2S_OUT_BCK 81
#define GPIO_PAD_81 GPIO80
#ifndef BALL_A12_IS_GPIO
#define BALL_A12_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_BCK_IS_GPIO
#define PAD_I2S_OUT_BCK_IS_GPIO BALL_A12_IS_GPIO
#endif 

#define BALL_E8 PAD_GPIO17
#define PAD_GPIO17 59
#define GPIO_PAD_59 GPIO58
#ifndef BALL_E8_IS_GPIO
#define BALL_E8_IS_GPIO 0
#endif 
#ifndef PAD_GPIO17_IS_GPIO
#define PAD_GPIO17_IS_GPIO BALL_E8_IS_GPIO
#endif 

#define BALL_B12 PAD_I2S_OUT_SD
#define PAD_I2S_OUT_SD 83
#define GPIO_PAD_83 GPIO82
#ifndef BALL_B12_IS_GPIO
#define BALL_B12_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_SD_IS_GPIO
#define PAD_I2S_OUT_SD_IS_GPIO BALL_B12_IS_GPIO
#endif 

#define BALL_D8 PAD_GPIO18
#define PAD_GPIO18 60
#define GPIO_PAD_60 GPIO59
#ifndef BALL_D8_IS_GPIO
#define BALL_D8_IS_GPIO 0
#endif 
#ifndef PAD_GPIO18_IS_GPIO
#define PAD_GPIO18_IS_GPIO BALL_D8_IS_GPIO
#endif 

#define PAD_I2S_OUT_SD2 9999
#ifndef PAD_I2S_OUT_SD2_IS_GPIO
#define PAD_I2S_OUT_SD2_IS_GPIO 0
#endif 

#define PAD_I2S_OUT_SD3 9999
#ifndef PAD_I2S_OUT_SD3_IS_GPIO
#define PAD_I2S_OUT_SD3_IS_GPIO 0
#endif 

#define BALL_E6 PAD_GPIO19
#define PAD_GPIO19 61
#define GPIO_PAD_61 GPIO60
#ifndef BALL_E6_IS_GPIO
#define BALL_E6_IS_GPIO 0
#endif 
#ifndef PAD_GPIO19_IS_GPIO
#define PAD_GPIO19_IS_GPIO BALL_E6_IS_GPIO
#endif 

#define BALL_B11 PAD_SPDIF_IN
#define PAD_SPDIF_IN 148
#define GPIO_PAD_148 GPIO147
#ifndef BALL_B11_IS_GPIO
#define BALL_B11_IS_GPIO 0
#endif 
#ifndef PAD_SPDIF_IN_IS_GPIO
#define PAD_SPDIF_IN_IS_GPIO BALL_B11_IS_GPIO
#endif 

#define BALL_C4 PAD_GPIO22
#define PAD_GPIO22 65
#define GPIO_PAD_65 GPIO64
#ifndef BALL_C4_IS_GPIO
#define BALL_C4_IS_GPIO 0
#endif 
#ifndef PAD_GPIO22_IS_GPIO
#define PAD_GPIO22_IS_GPIO BALL_C4_IS_GPIO
#endif 

#define BALL_C12 PAD_SPDIF_OUT
#define PAD_SPDIF_OUT 149
#define GPIO_PAD_149 GPIO148
#ifndef BALL_C12_IS_GPIO
#define BALL_C12_IS_GPIO 0
#endif 
#ifndef PAD_SPDIF_OUT_IS_GPIO
#define PAD_SPDIF_OUT_IS_GPIO BALL_C12_IS_GPIO
#endif 

#define BALL_A4 PAD_GPIO20
#define PAD_GPIO20 63
#define GPIO_PAD_63 GPIO62
#ifndef BALL_A4_IS_GPIO
#define BALL_A4_IS_GPIO 0
#endif 
#ifndef PAD_GPIO20_IS_GPIO
#define PAD_GPIO20_IS_GPIO BALL_A4_IS_GPIO
#endif 

#define PAD_GPIO0 9999
#ifndef PAD_GPIO0_IS_GPIO
#define PAD_GPIO0_IS_GPIO 0
#endif 

#define BALL_C6 PAD_GPIO24
#define PAD_GPIO24 67
#define GPIO_PAD_67 GPIO66
#ifndef BALL_C6_IS_GPIO
#define BALL_C6_IS_GPIO 0
#endif 
#ifndef PAD_GPIO24_IS_GPIO
#define PAD_GPIO24_IS_GPIO BALL_C6_IS_GPIO
#endif 

#define PAD_GPIO1 9999
#ifndef PAD_GPIO1_IS_GPIO
#define PAD_GPIO1_IS_GPIO 0
#endif 

#define BALL_B5 PAD_GPIO27
#define PAD_GPIO27 70
#define GPIO_PAD_70 GPIO69
#ifndef BALL_B5_IS_GPIO
#define BALL_B5_IS_GPIO 0
#endif 
#ifndef PAD_GPIO27_IS_GPIO
#define PAD_GPIO27_IS_GPIO BALL_B5_IS_GPIO
#endif 

#define PAD_GPIO2 9999
#ifndef PAD_GPIO2_IS_GPIO
#define PAD_GPIO2_IS_GPIO 0
#endif 

#define BALL_B4 PAD_GPIO21
#define PAD_GPIO21 64
#define GPIO_PAD_64 GPIO63
#ifndef BALL_B4_IS_GPIO
#define BALL_B4_IS_GPIO 0
#endif 
#ifndef PAD_GPIO21_IS_GPIO
#define PAD_GPIO21_IS_GPIO BALL_B4_IS_GPIO
#endif 

#define PAD_GPIO3 9999
#ifndef PAD_GPIO3_IS_GPIO
#define PAD_GPIO3_IS_GPIO 0
#endif 

#define BALL_C5 PAD_GPIO23
#define PAD_GPIO23 66
#define GPIO_PAD_66 GPIO65
#ifndef BALL_C5_IS_GPIO
#define BALL_C5_IS_GPIO 0
#endif 
#ifndef PAD_GPIO23_IS_GPIO
#define PAD_GPIO23_IS_GPIO BALL_C5_IS_GPIO
#endif 

#define PAD_GPIO4 9999
#ifndef PAD_GPIO4_IS_GPIO
#define PAD_GPIO4_IS_GPIO 0
#endif 

#define BALL_C10 PAD_GPIO5
#define PAD_GPIO5 73
#define GPIO_PAD_73 GPIO72
#ifndef BALL_C10_IS_GPIO
#define BALL_C10_IS_GPIO 0
#endif 
#ifndef PAD_GPIO5_IS_GPIO
#define PAD_GPIO5_IS_GPIO BALL_C10_IS_GPIO
#endif 

#define BALL_A10 PAD_GPIO6
#define PAD_GPIO6 74
#define GPIO_PAD_74 GPIO73
#ifndef BALL_A10_IS_GPIO
#define BALL_A10_IS_GPIO 0
#endif 
#ifndef PAD_GPIO6_IS_GPIO
#define PAD_GPIO6_IS_GPIO BALL_A10_IS_GPIO
#endif 

#define BALL_E7 PAD_GPIO26
#define PAD_GPIO26 69
#define GPIO_PAD_69 GPIO68
#ifndef BALL_E7_IS_GPIO
#define BALL_E7_IS_GPIO 0
#endif 
#ifndef PAD_GPIO26_IS_GPIO
#define PAD_GPIO26_IS_GPIO BALL_E7_IS_GPIO
#endif 

#define BALL_B8 PAD_GPIO7
#define PAD_GPIO7 75
#define GPIO_PAD_75 GPIO74
#ifndef BALL_B8_IS_GPIO
#define BALL_B8_IS_GPIO 0
#endif 
#ifndef PAD_GPIO7_IS_GPIO
#define PAD_GPIO7_IS_GPIO BALL_B8_IS_GPIO
#endif 

#define BALL_D7 PAD_GPIO25
#define PAD_GPIO25 68
#define GPIO_PAD_68 GPIO67
#ifndef BALL_D7_IS_GPIO
#define BALL_D7_IS_GPIO 0
#endif 
#ifndef PAD_GPIO25_IS_GPIO
#define PAD_GPIO25_IS_GPIO BALL_D7_IS_GPIO
#endif 

#define BALL_C8 PAD_GPIO8
#define PAD_GPIO8 76
#define GPIO_PAD_76 GPIO75
#ifndef BALL_C8_IS_GPIO
#define BALL_C8_IS_GPIO 0
#endif 
#ifndef PAD_GPIO8_IS_GPIO
#define PAD_GPIO8_IS_GPIO BALL_C8_IS_GPIO
#endif 

#define BALL_F6 PAD_SAR0
#define PAD_SAR0 38
#define GPIO_PAD_38 GPIO37
#ifndef BALL_F6_IS_GPIO
#define BALL_F6_IS_GPIO 0
#endif 
#ifndef PAD_SAR0_IS_GPIO
#define PAD_SAR0_IS_GPIO BALL_F6_IS_GPIO
#endif 

#define BALL_F4 PAD_SAR1
#define PAD_SAR1 39
#define GPIO_PAD_39 GPIO38
#ifndef BALL_F4_IS_GPIO
#define BALL_F4_IS_GPIO 0
#endif 
#ifndef PAD_SAR1_IS_GPIO
#define PAD_SAR1_IS_GPIO BALL_F4_IS_GPIO
#endif 

#define BALL_E4 PAD_SAR2
#define PAD_SAR2 40
#define GPIO_PAD_40 GPIO39
#ifndef BALL_E4_IS_GPIO
#define BALL_E4_IS_GPIO 0
#endif 
#ifndef PAD_SAR2_IS_GPIO
#define PAD_SAR2_IS_GPIO BALL_E4_IS_GPIO
#endif 

#define BALL_K5 PAD_SAR3
#define PAD_SAR3 41
#define GPIO_PAD_41 GPIO40
#ifndef BALL_K5_IS_GPIO
#define BALL_K5_IS_GPIO 0
#endif 
#ifndef PAD_SAR3_IS_GPIO
#define PAD_SAR3_IS_GPIO BALL_K5_IS_GPIO
#endif 

#define BALL_F5 PAD_SAR4
#define PAD_SAR4 42
#define GPIO_PAD_42 GPIO41
#ifndef BALL_F5_IS_GPIO
#define BALL_F5_IS_GPIO 0
#endif 
#ifndef PAD_SAR4_IS_GPIO
#define PAD_SAR4_IS_GPIO BALL_F5_IS_GPIO
#endif 

#define PAD_SAR5 9999
#ifndef PAD_SAR5_IS_GPIO
#define PAD_SAR5_IS_GPIO 0
#endif 

#define BALL_C2 PAD_DDCDD_CK
#define PAD_DDCDD_CK 35
#define GPIO_PAD_35 GPIO34
#ifndef BALL_C2_IS_GPIO
#define BALL_C2_IS_GPIO 0
#endif 
#ifndef PAD_DDCDD_CK_IS_GPIO
#define PAD_DDCDD_CK_IS_GPIO BALL_C2_IS_GPIO
#endif 

#define BALL_B1 PAD_DDCDD_DA
#define PAD_DDCDD_DA 36
#define GPIO_PAD_36 GPIO35
#ifndef BALL_B1_IS_GPIO
#define BALL_B1_IS_GPIO 0
#endif 
#ifndef PAD_DDCDD_DA_IS_GPIO
#define PAD_DDCDD_DA_IS_GPIO BALL_B1_IS_GPIO
#endif 

#define BALL_G5 PAD_GPIO_PM8
#define PAD_GPIO_PM8 17
#define GPIO_PAD_17 GPIO16
#ifndef BALL_G5_IS_GPIO
#define BALL_G5_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM8_IS_GPIO
#define PAD_GPIO_PM8_IS_GPIO BALL_G5_IS_GPIO
#endif 

#define PAD_GPIO_PM9 9999
#ifndef PAD_GPIO_PM9_IS_GPIO
#define PAD_GPIO_PM9_IS_GPIO 0
#endif 

#define BALL_D6 PAD_GPIO_PM10
#define PAD_GPIO_PM10 19
#define GPIO_PAD_19 GPIO18
#ifndef BALL_D6_IS_GPIO
#define BALL_D6_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM10_IS_GPIO
#define PAD_GPIO_PM10_IS_GPIO BALL_D6_IS_GPIO
#endif 

#define PAD_GPIO_PM11 9999
#ifndef PAD_GPIO_PM11_IS_GPIO
#define PAD_GPIO_PM11_IS_GPIO 0
#endif 

#define PAD_GPIO_PM12 9999
#ifndef PAD_GPIO_PM12_IS_GPIO
#define PAD_GPIO_PM12_IS_GPIO 0
#endif 

#define BALL_P2 PAD_GPIO_PM13
#define PAD_GPIO_PM13 22
#define GPIO_PAD_22 GPIO21
#ifndef BALL_P2_IS_GPIO
#define BALL_P2_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM13_IS_GPIO
#define PAD_GPIO_PM13_IS_GPIO BALL_P2_IS_GPIO
#endif 

#define BALL_P3 PAD_GPIO_PM14
#define PAD_GPIO_PM14 23
#define GPIO_PAD_23 GPIO22
#ifndef BALL_P3_IS_GPIO
#define BALL_P3_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM14_IS_GPIO
#define PAD_GPIO_PM14_IS_GPIO BALL_P3_IS_GPIO
#endif 

#define BALL_M4 PAD_GPIO_PM15
#define PAD_GPIO_PM15 24
#define GPIO_PAD_24 GPIO23
#ifndef BALL_M4_IS_GPIO
#define BALL_M4_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM15_IS_GPIO
#define PAD_GPIO_PM15_IS_GPIO BALL_M4_IS_GPIO
#endif 

// PADS group name to index
#define PADS_DDCR           1223
#define PADS_DDCR2          1224
#define PADS_TS0            1225
#define PADS_TS1            1226
#define PADS_GPIO1_GPIO2    1227
#define PADS_LHSYNC2_LVSYNC2 1228
#define PADS_PCI_AD20_AD21  1229
#define PADS_PCI            1230
#define PADS_PCM            1231
#define PADS_SAR            1232
#define PADS_DOUT           1233
#define PADS_DIN            1234
#define PADS_I2S            1235
#define PADS_PF             1236
#define PADS_EMAC           1237
#define PADS_TCON           1238
#define PADS_UART1_MODE1    1239
#define PADS_UART1_MODE2    1240
#define PADS_UART1_MODE3    1241
#define PADS_UART2_MODE1    1242
#define PADS_UART2_MODE2    1243
#define PADS_UART2_MODE3    1244
#define PADS_ET_MODE0       1245
#define PADS_ET_MODE1       1246
#define PADS_ET_MODE2       1247
#define PADS_ET_MODE3       1248
#define PADS_MIIC           1249
#define PADS_PF_MODE1       1250
#define PADS_PF_MODE2       1251
#define PADS_PF_MODE3       1252
#define PADS_SPI_CZ1        1253
#define PADS_SPI_CZ2        1254
#define PADS_SPI_CZ3        1255
#define PADS_DDCR3          1256

// chip capbilities
#define CHIP_HAS_BT656_IN          0
#define CHIP_HAS_TS0               1
#define CHIP_HAS_TS1               0 
#define CHIP_HAS_LVDS_10BIT_X2     1
#define CHIP_HAS_LVDS_8BIT_X2      1
#define CHIP_HAS_LVDS_8BIT_X1      1
#define CHIP_HAS_CIMAX             0
#define CHIP_HAS_USB_P0            1
#define CHIP_HAS_USB_P1            1
#define CHIP_HAS_USBVBUS0          0
#define CHIP_HAS_USBVBUS1          0
#define CHIP_HAS_UART1_MODE1       1 
#define CHIP_HAS_UART1_MODE2       1
#define CHIP_HAS_UART1_MODE3       1 
#define CHIP_HAS_PCMCIA1           0
#define CHIP_HAS_PCMCIA2           0
#define CHIP_HAS_PCMCIA            0
#define CHIP_HAS_UART2_MODE1       1 
#define CHIP_HAS_UART2_MODE2       1 
#define CHIP_HAS_UART2_MODE3       1 
#define CHIP_HAS_RGB_A             1 
#define CHIP_HAS_RGB_B             1 
#define CHIP_HAS_RGB_C             1 
#define CHIP_HAS_HDMI_A            1 
#define CHIP_HAS_HDMI_B            1 
#define CHIP_HAS_HDMI_C            1 
#define CHIP_HAS_SPI_CZ1           1 
#define CHIP_HAS_SPI_CZ2           0 
#define CHIP_HAS_SPI_CZ3           0
#define CHIP_HAS_DDCR              1 
#define CHIP_HAS_DDCR2             1 
#define CHIP_HAS_TCON              1
#define CHIP_HAS_ET_MODE0_MII      1 
#define CHIP_HAS_ET_MODE0_RMII     1 
#define CHIP_HAS_ET_MODE1_MII      1 
#define CHIP_HAS_ET_MODE1_RMII     1 
#define CHIP_HAS_ET_MODE2_MII      1
#define CHIP_HAS_ET_MODE2_RMII     1
#define CHIP_HAS_I2S_IN            1 
#define CHIP_HAS_I2S_OUT           1
#define CHIP_HAS_SPDIF_IN          0 
#define CHIP_HAS_SPDIF_OUT         1
#define CHIP_HAS_DDR_A_CMD         1
#define CHIP_HAS_DDR_A_DATA        1
#define CHIP_HAS_DDR_B_CMD         1
#define CHIP_HAS_DDR_B_DATA        1
#define CHIP_USE_PCM_CDN_IN_PCM2   0
#define CHIP_USE_I2S_IN_IN_PCM     0
#define CHIP_USE_I2S_OUT_IN_PCM    0
#define CHIP_USE_SPDIF_IN_IN_PCM   0
#define CHIP_USE_SPDIF_OUT_IN_PCM  0
#define CHIP_USE_IIC_IN_DDCR2      0
#define CHIP_USE_PWM2_IN_GPIO14    0
#define CHIP_USE_PWM3_IN_GPIO15    0

// chip additional information
#define CHIP_FAMILY_TYPE           CHIP_FAMILY_M5321

#endif /* _MSD8320YN_H_*/
