/* SPDX-License-Identifier: GPL-2.0-only OR BSD-3-Clause */
/******************************************************************************
 *
 * This file is provided under a dual license.  When you use or
 * distribute this software, you may choose to be licensed under
 * version 2 of the GNU General Public License ("GPLv2 License")
 * or BSD License.
 *
 * GPLv2 License
 *
 * Copyright(C) 2019 MediaTek Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of version 2 of the GNU General Public License as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See http://www.gnu.org/licenses/gpl-2.0.html for more details.
 *
 * BSD LICENSE
 *
 * Copyright(C) 2019 MediaTek Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *****************************************************************************/

// This file is generated by script, please do not edit it directly
#ifndef _MSD95VFDW_H_
#define _MSD95VFDW_H_

#define PAD_NC 9999
#define PAD_GND 0

#define BALL_AA6 PAD_DDCDD_CK
#define PAD_DDCDD_CK 40
#define GPIO_PAD_40 GPIO39
#ifndef BALL_AA6_IS_GPIO
#define BALL_AA6_IS_GPIO 0
#endif
#ifndef PAD_DDCDD_CK_IS_GPIO
#define PAD_DDCDD_CK_IS_GPIO BALL_AA6_IS_GPIO
#endif

#define BALL_AB6 PAD_DDCDD_DA
#define PAD_DDCDD_DA 41
#define GPIO_PAD_41 GPIO40
#ifndef BALL_AB6_IS_GPIO
#define BALL_AB6_IS_GPIO 0
#endif
#ifndef PAD_DDCDD_DA_IS_GPIO
#define PAD_DDCDD_DA_IS_GPIO BALL_AB6_IS_GPIO
#endif

#define PAD_DDCDC_CK 9999
#ifndef PAD_DDCDC_CK_IS_GPIO
#define PAD_DDCDC_CK_IS_GPIO 0
#endif

#define PAD_DDCDC_DA 9999
#ifndef PAD_DDCDC_DA_IS_GPIO
#define PAD_DDCDC_DA_IS_GPIO 0
#endif

#define BALL_AA5 PAD_DDCDA_CK
#define PAD_DDCDA_CK 34
#define GPIO_PAD_34 GPIO33
#ifndef BALL_AA5_IS_GPIO
#define BALL_AA5_IS_GPIO 0
#endif
#ifndef PAD_DDCDA_CK_IS_GPIO
#define PAD_DDCDA_CK_IS_GPIO BALL_AA5_IS_GPIO
#endif

#define BALL_AB5 PAD_DDCDA_DA
#define PAD_DDCDA_DA 35
#define GPIO_PAD_35 GPIO34
#ifndef BALL_AB5_IS_GPIO
#define BALL_AB5_IS_GPIO 0
#endif
#ifndef PAD_DDCDA_DA_IS_GPIO
#define PAD_DDCDA_DA_IS_GPIO BALL_AB5_IS_GPIO
#endif

#define BALL_AD6 PAD_DDCDB_CK
#define PAD_DDCDB_CK 36
#define GPIO_PAD_36 GPIO35
#ifndef BALL_AD6_IS_GPIO
#define BALL_AD6_IS_GPIO 0
#endif
#ifndef PAD_DDCDB_CK_IS_GPIO
#define PAD_DDCDB_CK_IS_GPIO BALL_AD6_IS_GPIO
#endif

#define BALL_AD5 PAD_DDCDB_DA
#define PAD_DDCDB_DA 37
#define GPIO_PAD_37 GPIO36
#ifndef BALL_AD5_IS_GPIO
#define BALL_AD5_IS_GPIO 0
#endif
#ifndef PAD_DDCDB_DA_IS_GPIO
#define PAD_DDCDB_DA_IS_GPIO BALL_AD5_IS_GPIO
#endif

#define BALL_L3 PAD_HOTPLUGB
#define PAD_HOTPLUGB 27
#define GPIO_PAD_27 GPIO26
#ifndef BALL_L3_IS_GPIO
#define BALL_L3_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGB_IS_GPIO
#define PAD_HOTPLUGB_IS_GPIO BALL_L3_IS_GPIO
#endif

#define PAD_HOTPLUGC 9999
#ifndef PAD_HOTPLUGC_IS_GPIO
#define PAD_HOTPLUGC_IS_GPIO 0
#endif

#define BALL_H3 PAD_HOTPLUGD
#define PAD_HOTPLUGD 29
#define GPIO_PAD_29 GPIO28
#ifndef BALL_H3_IS_GPIO
#define BALL_H3_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGD_IS_GPIO
#define PAD_HOTPLUGD_IS_GPIO BALL_H3_IS_GPIO
#endif

#define BALL_AC5 PAD_HOTPLUGA_HDMI20_5V
#define PAD_HOTPLUGA_HDMI20_5V 30
#define GPIO_PAD_30 GPIO29
#ifndef BALL_AC5_IS_GPIO
#define BALL_AC5_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGA_HDMI20_5V_IS_GPIO
#define PAD_HOTPLUGA_HDMI20_5V_IS_GPIO BALL_AC5_IS_GPIO
#endif

#define BALL_AD4 PAD_HOTPLUGB_HDMI20_5V
#define PAD_HOTPLUGB_HDMI20_5V 31
#define GPIO_PAD_31 GPIO30
#ifndef BALL_AD4_IS_GPIO
#define BALL_AD4_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGB_HDMI20_5V_IS_GPIO
#define PAD_HOTPLUGB_HDMI20_5V_IS_GPIO BALL_AD4_IS_GPIO
#endif

#define PAD_HOTPLUGC_HDMI20_5V 9999
#ifndef PAD_HOTPLUGC_HDMI20_5V_IS_GPIO
#define PAD_HOTPLUGC_HDMI20_5V_IS_GPIO 0
#endif

#define BALL_AC6 PAD_HOTPLUGD_HDMI20_5V
#define PAD_HOTPLUGD_HDMI20_5V 33
#define GPIO_PAD_33 GPIO32
#ifndef BALL_AC6_IS_GPIO
#define BALL_AC6_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGD_HDMI20_5V_IS_GPIO
#define PAD_HOTPLUGD_HDMI20_5V_IS_GPIO BALL_AC6_IS_GPIO
#endif

#define BALL_Y3 PAD_VID0
#define PAD_VID0 48
#define GPIO_PAD_48 GPIO47
#ifndef BALL_Y3_IS_GPIO
#define BALL_Y3_IS_GPIO 0
#endif
#ifndef PAD_VID0_IS_GPIO
#define PAD_VID0_IS_GPIO BALL_Y3_IS_GPIO
#endif

#define BALL_W2 PAD_VID1
#define PAD_VID1 49
#define GPIO_PAD_49 GPIO48
#ifndef BALL_W2_IS_GPIO
#define BALL_W2_IS_GPIO 0
#endif
#ifndef PAD_VID1_IS_GPIO
#define PAD_VID1_IS_GPIO BALL_W2_IS_GPIO
#endif

#define BALL_N3 PAD_HOTPLUGA
#define PAD_HOTPLUGA 219
#define GPIO_PAD_219 GPIO218
#ifndef BALL_N3_IS_GPIO
#define BALL_N3_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGA_IS_GPIO
#define PAD_HOTPLUGA_IS_GPIO BALL_N3_IS_GPIO
#endif

#define PAD_GPIO17 9999
#ifndef PAD_GPIO17_IS_GPIO
#define PAD_GPIO17_IS_GPIO 0
#endif

#define PAD_GPIO6 9999
#ifndef PAD_GPIO6_IS_GPIO
#define PAD_GPIO6_IS_GPIO 0
#endif

#define PAD_GPIO18 9999
#ifndef PAD_GPIO18_IS_GPIO
#define PAD_GPIO18_IS_GPIO 0
#endif

#define PAD_GPIO8 9999
#ifndef PAD_GPIO8_IS_GPIO
#define PAD_GPIO8_IS_GPIO 0
#endif

#define PAD_GPIO19 9999
#ifndef PAD_GPIO19_IS_GPIO
#define PAD_GPIO19_IS_GPIO 0
#endif

#define PAD_GPIO5 9999
#ifndef PAD_GPIO5_IS_GPIO
#define PAD_GPIO5_IS_GPIO 0
#endif

#define PAD_GPIO20 9999
#ifndef PAD_GPIO20_IS_GPIO
#define PAD_GPIO20_IS_GPIO 0
#endif

#define PAD_GPIO7 9999
#ifndef PAD_GPIO7_IS_GPIO
#define PAD_GPIO7_IS_GPIO 0
#endif

#define PAD_GPIO21 9999
#ifndef PAD_GPIO21_IS_GPIO
#define PAD_GPIO21_IS_GPIO 0
#endif

#define PAD_GPIO23 9999
#ifndef PAD_GPIO23_IS_GPIO
#define PAD_GPIO23_IS_GPIO 0
#endif

#define PAD_GPIO22 9999
#ifndef PAD_GPIO22_IS_GPIO
#define PAD_GPIO22_IS_GPIO 0
#endif

#define PAD_GPIO29 9999
#ifndef PAD_GPIO29_IS_GPIO
#define PAD_GPIO29_IS_GPIO 0
#endif

#define PAD_GPIO30 9999
#ifndef PAD_GPIO30_IS_GPIO
#define PAD_GPIO30_IS_GPIO 0
#endif

#define PAD_GPIO31 9999
#ifndef PAD_GPIO31_IS_GPIO
#define PAD_GPIO31_IS_GPIO 0
#endif

#define PAD_GPIO32 9999
#ifndef PAD_GPIO32_IS_GPIO
#define PAD_GPIO32_IS_GPIO 0
#endif

#define PAD_GPIO33 9999
#ifndef PAD_GPIO33_IS_GPIO
#define PAD_GPIO33_IS_GPIO 0
#endif

#define PAD_GPIO34 9999
#ifndef PAD_GPIO34_IS_GPIO
#define PAD_GPIO34_IS_GPIO 0
#endif

#define PAD_GPIO35 9999
#ifndef PAD_GPIO35_IS_GPIO
#define PAD_GPIO35_IS_GPIO 0
#endif

#define BALL_R6 PAD_ARC0
#define PAD_ARC0 218
#define GPIO_PAD_218 GPIO217
#ifndef BALL_R6_IS_GPIO
#define BALL_R6_IS_GPIO 0
#endif
#ifndef PAD_ARC0_IS_GPIO
#define PAD_ARC0_IS_GPIO BALL_R6_IS_GPIO
#endif

#define BALL_K5 PAD_GPIO_PM0
#define PAD_GPIO_PM0 10
#define GPIO_PAD_10 GPIO9
#ifndef BALL_K5_IS_GPIO
#define BALL_K5_IS_GPIO 0
#endif
#ifndef PAD_GPIO_PM0_IS_GPIO
#define PAD_GPIO_PM0_IS_GPIO BALL_K5_IS_GPIO
#endif

#define BALL_AA4 PAD_GPIO_PM2
#define PAD_GPIO_PM2 12
#define GPIO_PAD_12 GPIO11
#ifndef BALL_AA4_IS_GPIO
#define BALL_AA4_IS_GPIO 0
#endif
#ifndef PAD_GPIO_PM2_IS_GPIO
#define PAD_GPIO_PM2_IS_GPIO BALL_AA4_IS_GPIO
#endif

#define PAD_GPIO_PM3 9999
#ifndef PAD_GPIO_PM3_IS_GPIO
#define PAD_GPIO_PM3_IS_GPIO 0
#endif

#define BALL_AE4 PAD_GPIO_PM4
#define PAD_GPIO_PM4 14
#define GPIO_PAD_14 GPIO13
#ifndef BALL_AE4_IS_GPIO
#define BALL_AE4_IS_GPIO 0
#endif
#ifndef PAD_GPIO_PM4_IS_GPIO
#define PAD_GPIO_PM4_IS_GPIO BALL_AE4_IS_GPIO
#endif

#define PAD_VID4 9999
#ifndef PAD_VID4_IS_GPIO
#define PAD_VID4_IS_GPIO 0
#endif

#define BALL_AC10 PAD_VID5
#define PAD_VID5 53
#define GPIO_PAD_53 GPIO52
#ifndef BALL_AC10_IS_GPIO
#define BALL_AC10_IS_GPIO 0
#endif
#ifndef PAD_VID5_IS_GPIO
#define PAD_VID5_IS_GPIO BALL_AC10_IS_GPIO
#endif

#define PAD_GPIO_PM9 9999
#ifndef PAD_GPIO_PM9_IS_GPIO
#define PAD_GPIO_PM9_IS_GPIO 0
#endif

#define PAD_GPIO_PM13 9999
#ifndef PAD_GPIO_PM13_IS_GPIO
#define PAD_GPIO_PM13_IS_GPIO 0
#endif

#define BALL_AB4 PAD_GPIO_PM15
#define PAD_GPIO_PM15 23
#define GPIO_PAD_23 GPIO22
#ifndef BALL_AB4_IS_GPIO
#define BALL_AB4_IS_GPIO 0
#endif
#ifndef PAD_GPIO_PM15_IS_GPIO
#define PAD_GPIO_PM15_IS_GPIO BALL_AB4_IS_GPIO
#endif

#define PAD_GPIO_PM16 9999
#ifndef PAD_GPIO_PM16_IS_GPIO
#define PAD_GPIO_PM16_IS_GPIO 0
#endif

#define PAD_VID2 9999
#ifndef PAD_VID2_IS_GPIO
#define PAD_VID2_IS_GPIO 0
#endif

#define PAD_VID3 9999
#ifndef PAD_VID3_IS_GPIO
#define PAD_VID3_IS_GPIO 0
#endif

#define PAD_GPIO24 9999
#ifndef PAD_GPIO24_IS_GPIO
#define PAD_GPIO24_IS_GPIO 0
#endif

#define PAD_GPIO36 9999
#ifndef PAD_GPIO36_IS_GPIO
#define PAD_GPIO36_IS_GPIO 0
#endif

#define PAD_GPIO25 9999
#ifndef PAD_GPIO25_IS_GPIO
#define PAD_GPIO25_IS_GPIO 0
#endif

#define PAD_GPIO37 9999
#ifndef PAD_GPIO37_IS_GPIO
#define PAD_GPIO37_IS_GPIO 0
#endif

#define PAD_GPIO26 9999
#ifndef PAD_GPIO26_IS_GPIO
#define PAD_GPIO26_IS_GPIO 0
#endif

#define BALL_AF2 PAD_TGPIO0
#define PAD_TGPIO0 152
#define GPIO_PAD_152 GPIO151
#ifndef BALL_AF2_IS_GPIO
#define BALL_AF2_IS_GPIO 0
#endif
#ifndef PAD_TGPIO0_IS_GPIO
#define PAD_TGPIO0_IS_GPIO BALL_AF2_IS_GPIO
#endif

#define PAD_GPIO27 9999
#ifndef PAD_GPIO27_IS_GPIO
#define PAD_GPIO27_IS_GPIO 0
#endif

#define BALL_AF1 PAD_TGPIO1
#define PAD_TGPIO1 153
#define GPIO_PAD_153 GPIO152
#ifndef BALL_AF1_IS_GPIO
#define BALL_AF1_IS_GPIO 0
#endif
#ifndef PAD_TGPIO1_IS_GPIO
#define PAD_TGPIO1_IS_GPIO BALL_AF1_IS_GPIO
#endif

#define PAD_GPIO28 9999
#ifndef PAD_GPIO28_IS_GPIO
#define PAD_GPIO28_IS_GPIO 0
#endif

#define BALL_AE3 PAD_TGPIO2
#define PAD_TGPIO2 154
#define GPIO_PAD_154 GPIO153
#ifndef BALL_AE3_IS_GPIO
#define BALL_AE3_IS_GPIO 0
#endif
#ifndef PAD_TGPIO2_IS_GPIO
#define PAD_TGPIO2_IS_GPIO BALL_AE3_IS_GPIO
#endif

#define BALL_AE2 PAD_TGPIO3
#define PAD_TGPIO3 155
#define GPIO_PAD_155 GPIO154
#ifndef BALL_AE2_IS_GPIO
#define BALL_AE2_IS_GPIO 0
#endif
#ifndef PAD_TGPIO3_IS_GPIO
#define PAD_TGPIO3_IS_GPIO BALL_AE2_IS_GPIO
#endif

#define BALL_AK15 PAD_PCM2_CE_N
#define PAD_PCM2_CE_N 109
#define GPIO_PAD_109 GPIO108
#ifndef BALL_AK15_IS_GPIO
#define BALL_AK15_IS_GPIO 0
#endif
#ifndef PAD_PCM2_CE_N_IS_GPIO
#define PAD_PCM2_CE_N_IS_GPIO BALL_AK15_IS_GPIO
#endif

#define BALL_AF32 PAD_PCM2_RESET
#define PAD_PCM2_RESET 112
#define GPIO_PAD_112 GPIO111
#ifndef BALL_AF32_IS_GPIO
#define BALL_AF32_IS_GPIO 0
#endif
#ifndef PAD_PCM2_RESET_IS_GPIO
#define PAD_PCM2_RESET_IS_GPIO BALL_AF32_IS_GPIO
#endif

#define BALL_AM14 PAD_PCM2_IRQA_N
#define PAD_PCM2_IRQA_N 110
#define GPIO_PAD_110 GPIO109
#ifndef BALL_AM14_IS_GPIO
#define BALL_AM14_IS_GPIO 0
#endif
#ifndef PAD_PCM2_IRQA_N_IS_GPIO
#define PAD_PCM2_IRQA_N_IS_GPIO BALL_AM14_IS_GPIO
#endif

#define BALL_AF31 PAD_PCM2_WAIT_N
#define PAD_PCM2_WAIT_N 111
#define GPIO_PAD_111 GPIO110
#ifndef BALL_AF31_IS_GPIO
#define BALL_AF31_IS_GPIO 0
#endif
#ifndef PAD_PCM2_WAIT_N_IS_GPIO
#define PAD_PCM2_WAIT_N_IS_GPIO BALL_AF31_IS_GPIO
#endif

#define BALL_AG6 PAD_TS1_D7
#define PAD_TS1_D7 170
#define GPIO_PAD_170 GPIO169
#ifndef BALL_AG6_IS_GPIO
#define BALL_AG6_IS_GPIO 0
#endif
#ifndef PAD_TS1_D7_IS_GPIO
#define PAD_TS1_D7_IS_GPIO BALL_AG6_IS_GPIO
#endif

#define BALL_AG9 PAD_PCM_D2
#define PAD_PCM_D2 144
#define GPIO_PAD_144 GPIO143
#ifndef BALL_AG9_IS_GPIO
#define BALL_AG9_IS_GPIO 0
#endif
#ifndef PAD_PCM_D2_IS_GPIO
#define PAD_PCM_D2_IS_GPIO BALL_AG9_IS_GPIO
#endif

#define BALL_AJ4 PAD_TS1_D6
#define PAD_TS1_D6 171
#define GPIO_PAD_171 GPIO170
#ifndef BALL_AJ4_IS_GPIO
#define BALL_AJ4_IS_GPIO 0
#endif
#ifndef PAD_TS1_D6_IS_GPIO
#define PAD_TS1_D6_IS_GPIO BALL_AJ4_IS_GPIO
#endif

#define BALL_AH9 PAD_PCM_D1
#define PAD_PCM_D1 143
#define GPIO_PAD_143 GPIO142
#ifndef BALL_AH9_IS_GPIO
#define BALL_AH9_IS_GPIO 0
#endif
#ifndef PAD_PCM_D1_IS_GPIO
#define PAD_PCM_D1_IS_GPIO BALL_AH9_IS_GPIO
#endif

#define BALL_AJ5 PAD_TS1_CLK
#define PAD_TS1_CLK 167
#define GPIO_PAD_167 GPIO166
#ifndef BALL_AJ5_IS_GPIO
#define BALL_AJ5_IS_GPIO 0
#endif
#ifndef PAD_TS1_CLK_IS_GPIO
#define PAD_TS1_CLK_IS_GPIO BALL_AJ5_IS_GPIO
#endif

#define BALL_AH8 PAD_PCM_D0
#define PAD_PCM_D0 142
#define GPIO_PAD_142 GPIO141
#ifndef BALL_AH8_IS_GPIO
#define BALL_AH8_IS_GPIO 0
#endif
#ifndef PAD_PCM_D0_IS_GPIO
#define PAD_PCM_D0_IS_GPIO BALL_AH8_IS_GPIO
#endif

#define BALL_AK5 PAD_TS1_D4
#define PAD_TS1_D4 173
#define GPIO_PAD_173 GPIO172
#ifndef BALL_AK5_IS_GPIO
#define BALL_AK5_IS_GPIO 0
#endif
#ifndef PAD_TS1_D4_IS_GPIO
#define PAD_TS1_D4_IS_GPIO BALL_AK5_IS_GPIO
#endif

#define BALL_AJ9 PAD_PCM_A0
#define PAD_PCM_A0 141
#define GPIO_PAD_141 GPIO140
#ifndef BALL_AJ9_IS_GPIO
#define BALL_AJ9_IS_GPIO 0
#endif
#ifndef PAD_PCM_A0_IS_GPIO
#define PAD_PCM_A0_IS_GPIO BALL_AJ9_IS_GPIO
#endif

#define BALL_AK6 PAD_TS1_VLD
#define PAD_TS1_VLD 169
#define GPIO_PAD_169 GPIO168
#ifndef BALL_AK6_IS_GPIO
#define BALL_AK6_IS_GPIO 0
#endif
#ifndef PAD_TS1_VLD_IS_GPIO
#define PAD_TS1_VLD_IS_GPIO BALL_AK6_IS_GPIO
#endif

#define BALL_AJ8 PAD_PCM_REG_N
#define PAD_PCM_REG_N 139
#define GPIO_PAD_139 GPIO138
#ifndef BALL_AJ8_IS_GPIO
#define BALL_AJ8_IS_GPIO 0
#endif
#ifndef PAD_PCM_REG_N_IS_GPIO
#define PAD_PCM_REG_N_IS_GPIO BALL_AJ8_IS_GPIO
#endif

#define BALL_AH11 PAD_PCM_A2
#define PAD_PCM_A2 138
#define GPIO_PAD_138 GPIO137
#ifndef BALL_AH11_IS_GPIO
#define BALL_AH11_IS_GPIO 0
#endif
#ifndef PAD_PCM_A2_IS_GPIO
#define PAD_PCM_A2_IS_GPIO BALL_AH11_IS_GPIO
#endif

#define BALL_AH7 PAD_TS1_D3
#define PAD_TS1_D3 174
#define GPIO_PAD_174 GPIO173
#ifndef BALL_AH7_IS_GPIO
#define BALL_AH7_IS_GPIO 0
#endif
#ifndef PAD_TS1_D3_IS_GPIO
#define PAD_TS1_D3_IS_GPIO BALL_AH7_IS_GPIO
#endif

#define BALL_AG10 PAD_PCM_A3
#define PAD_PCM_A3 137
#define GPIO_PAD_137 GPIO136
#ifndef BALL_AG10_IS_GPIO
#define BALL_AG10_IS_GPIO 0
#endif
#ifndef PAD_PCM_A3_IS_GPIO
#define PAD_PCM_A3_IS_GPIO BALL_AG10_IS_GPIO
#endif

#define BALL_AJ6 PAD_TS1_D2
#define PAD_TS1_D2 175
#define GPIO_PAD_175 GPIO174
#ifndef BALL_AJ6_IS_GPIO
#define BALL_AJ6_IS_GPIO 0
#endif
#ifndef PAD_TS1_D2_IS_GPIO
#define PAD_TS1_D2_IS_GPIO BALL_AJ6_IS_GPIO
#endif

#define BALL_AH12 PAD_PCM_WAIT_N
#define PAD_PCM_WAIT_N 135
#define GPIO_PAD_135 GPIO134
#ifndef BALL_AH12_IS_GPIO
#define BALL_AH12_IS_GPIO 0
#endif
#ifndef PAD_PCM_WAIT_N_IS_GPIO
#define PAD_PCM_WAIT_N_IS_GPIO BALL_AH12_IS_GPIO
#endif

#define BALL_AH5 PAD_TS1_D1
#define PAD_TS1_D1 176
#define GPIO_PAD_176 GPIO175
#ifndef BALL_AH5_IS_GPIO
#define BALL_AH5_IS_GPIO 0
#endif
#ifndef PAD_TS1_D1_IS_GPIO
#define PAD_TS1_D1_IS_GPIO BALL_AH5_IS_GPIO
#endif

#define BALL_AJ12 PAD_PCM_A4
#define PAD_PCM_A4 136
#define GPIO_PAD_136 GPIO135
#ifndef BALL_AJ12_IS_GPIO
#define BALL_AJ12_IS_GPIO 0
#endif
#ifndef PAD_PCM_A4_IS_GPIO
#define PAD_PCM_A4_IS_GPIO BALL_AJ12_IS_GPIO
#endif

#define BALL_AH6 PAD_TS1_D5
#define PAD_TS1_D5 172
#define GPIO_PAD_172 GPIO171
#ifndef BALL_AH6_IS_GPIO
#define BALL_AH6_IS_GPIO 0
#endif
#ifndef PAD_TS1_D5_IS_GPIO
#define PAD_TS1_D5_IS_GPIO BALL_AH6_IS_GPIO
#endif

#define BALL_AG12 PAD_PCM_RESET
#define PAD_PCM_RESET 145
#define GPIO_PAD_145 GPIO144
#ifndef BALL_AG12_IS_GPIO
#define BALL_AG12_IS_GPIO 0
#endif
#ifndef PAD_PCM_RESET_IS_GPIO
#define PAD_PCM_RESET_IS_GPIO BALL_AG12_IS_GPIO
#endif

#define BALL_AH4 PAD_TS1_D0
#define PAD_TS1_D0 177
#define GPIO_PAD_177 GPIO176
#ifndef BALL_AH4_IS_GPIO
#define BALL_AH4_IS_GPIO 0
#endif
#ifndef PAD_TS1_D0_IS_GPIO
#define PAD_TS1_D0_IS_GPIO BALL_AH4_IS_GPIO
#endif

#define BALL_AH10 PAD_PCM_A5
#define PAD_PCM_A5 134
#define GPIO_PAD_134 GPIO133
#ifndef BALL_AH10_IS_GPIO
#define BALL_AH10_IS_GPIO 0
#endif
#ifndef PAD_PCM_A5_IS_GPIO
#define PAD_PCM_A5_IS_GPIO BALL_AH10_IS_GPIO
#endif

#define BALL_AG7 PAD_TS1_SYNC
#define PAD_TS1_SYNC 168
#define GPIO_PAD_168 GPIO167
#ifndef BALL_AG7_IS_GPIO
#define BALL_AG7_IS_GPIO 0
#endif
#ifndef PAD_TS1_SYNC_IS_GPIO
#define PAD_TS1_SYNC_IS_GPIO BALL_AG7_IS_GPIO
#endif

#define BALL_AH13 PAD_PCM_A6
#define PAD_PCM_A6 133
#define GPIO_PAD_133 GPIO132
#ifndef BALL_AH13_IS_GPIO
#define BALL_AH13_IS_GPIO 0
#endif
#ifndef PAD_PCM_A6_IS_GPIO
#define PAD_PCM_A6_IS_GPIO BALL_AH13_IS_GPIO
#endif

#define BALL_AJ10 PAD_TS0_D2
#define PAD_TS0_D2 158
#define GPIO_PAD_158 GPIO157
#ifndef BALL_AJ10_IS_GPIO
#define BALL_AJ10_IS_GPIO 0
#endif
#ifndef PAD_TS0_D2_IS_GPIO
#define PAD_TS0_D2_IS_GPIO BALL_AJ10_IS_GPIO
#endif

#define BALL_AG14 PAD_PCM_A7
#define PAD_PCM_A7 132
#define GPIO_PAD_132 GPIO131
#ifndef BALL_AG14_IS_GPIO
#define BALL_AG14_IS_GPIO 0
#endif
#ifndef PAD_PCM_A7_IS_GPIO
#define PAD_PCM_A7_IS_GPIO BALL_AG14_IS_GPIO
#endif

#define BALL_AG13 PAD_PCM_A12
#define PAD_PCM_A12 131
#define GPIO_PAD_131 GPIO130
#ifndef BALL_AG13_IS_GPIO
#define BALL_AG13_IS_GPIO 0
#endif
#ifndef PAD_PCM_A12_IS_GPIO
#define PAD_PCM_A12_IS_GPIO BALL_AG13_IS_GPIO
#endif

#define BALL_AJ11 PAD_TS0_D1
#define PAD_TS0_D1 157
#define GPIO_PAD_157 GPIO156
#ifndef BALL_AJ11_IS_GPIO
#define BALL_AJ11_IS_GPIO 0
#endif
#ifndef PAD_TS0_D1_IS_GPIO
#define PAD_TS0_D1_IS_GPIO BALL_AJ11_IS_GPIO
#endif

#define BALL_AH14 PAD_PCM_IRQA_N
#define PAD_PCM_IRQA_N 130
#define GPIO_PAD_130 GPIO129
#ifndef BALL_AH14_IS_GPIO
#define BALL_AH14_IS_GPIO 0
#endif
#ifndef PAD_PCM_IRQA_N_IS_GPIO
#define PAD_PCM_IRQA_N_IS_GPIO BALL_AH14_IS_GPIO
#endif

#define BALL_AK11 PAD_TS0_D0
#define PAD_TS0_D0 156
#define GPIO_PAD_156 GPIO155
#ifndef BALL_AK11_IS_GPIO
#define BALL_AK11_IS_GPIO 0
#endif
#ifndef PAD_TS0_D0_IS_GPIO
#define PAD_TS0_D0_IS_GPIO BALL_AK11_IS_GPIO
#endif

#define BALL_AJ14 PAD_PCM_WE_N
#define PAD_PCM_WE_N 129
#define GPIO_PAD_129 GPIO128
#ifndef BALL_AJ14_IS_GPIO
#define BALL_AJ14_IS_GPIO 0
#endif
#ifndef PAD_PCM_WE_N_IS_GPIO
#define PAD_PCM_WE_N_IS_GPIO BALL_AJ14_IS_GPIO
#endif

#define BALL_AK12 PAD_TS0_SYNC
#define PAD_TS0_SYNC 165
#define GPIO_PAD_165 GPIO164
#ifndef BALL_AK12_IS_GPIO
#define BALL_AK12_IS_GPIO 0
#endif
#ifndef PAD_TS0_SYNC_IS_GPIO
#define PAD_TS0_SYNC_IS_GPIO BALL_AK12_IS_GPIO
#endif

#define BALL_AM15 PAD_PCM_A14
#define PAD_PCM_A14 128
#define GPIO_PAD_128 GPIO127
#ifndef BALL_AM15_IS_GPIO
#define BALL_AM15_IS_GPIO 0
#endif
#ifndef PAD_PCM_A14_IS_GPIO
#define PAD_PCM_A14_IS_GPIO BALL_AM15_IS_GPIO
#endif

#define BALL_AM11 PAD_TS0_VLD
#define PAD_TS0_VLD 164
#define GPIO_PAD_164 GPIO163
#ifndef BALL_AM11_IS_GPIO
#define BALL_AM11_IS_GPIO 0
#endif
#ifndef PAD_TS0_VLD_IS_GPIO
#define PAD_TS0_VLD_IS_GPIO BALL_AM11_IS_GPIO
#endif

#define BALL_AL15 PAD_PCM_A13
#define PAD_PCM_A13 127
#define GPIO_PAD_127 GPIO126
#ifndef BALL_AL15_IS_GPIO
#define BALL_AL15_IS_GPIO 0
#endif
#ifndef PAD_PCM_A13_IS_GPIO
#define PAD_PCM_A13_IS_GPIO BALL_AL15_IS_GPIO
#endif

#define BALL_AL12 PAD_TS0_CLK
#define PAD_TS0_CLK 166
#define GPIO_PAD_166 GPIO165
#ifndef BALL_AL12_IS_GPIO
#define BALL_AL12_IS_GPIO 0
#endif
#ifndef PAD_TS0_CLK_IS_GPIO
#define PAD_TS0_CLK_IS_GPIO BALL_AL12_IS_GPIO
#endif

#define BALL_AH15 PAD_PCM_A8
#define PAD_PCM_A8 126
#define GPIO_PAD_126 GPIO125
#ifndef BALL_AH15_IS_GPIO
#define BALL_AH15_IS_GPIO 0
#endif
#ifndef PAD_PCM_A8_IS_GPIO
#define PAD_PCM_A8_IS_GPIO BALL_AH15_IS_GPIO
#endif

#define BALL_AM12 PAD_TS0_D3
#define PAD_TS0_D3 159
#define GPIO_PAD_159 GPIO158
#ifndef BALL_AM12_IS_GPIO
#define BALL_AM12_IS_GPIO 0
#endif
#ifndef PAD_TS0_D3_IS_GPIO
#define PAD_TS0_D3_IS_GPIO BALL_AM12_IS_GPIO
#endif

#define BALL_AL16 PAD_PCM_A9
#define PAD_PCM_A9 124
#define GPIO_PAD_124 GPIO123
#ifndef BALL_AL16_IS_GPIO
#define BALL_AL16_IS_GPIO 0
#endif
#ifndef PAD_PCM_A9_IS_GPIO
#define PAD_PCM_A9_IS_GPIO BALL_AL16_IS_GPIO
#endif

#define BALL_AK13 PAD_TS0_D7
#define PAD_TS0_D7 163
#define GPIO_PAD_163 GPIO162
#ifndef BALL_AK13_IS_GPIO
#define BALL_AK13_IS_GPIO 0
#endif
#ifndef PAD_TS0_D7_IS_GPIO
#define PAD_TS0_D7_IS_GPIO BALL_AK13_IS_GPIO
#endif

#define BALL_AG15 PAD_PCM_A1
#define PAD_PCM_A1 140
#define GPIO_PAD_140 GPIO139
#ifndef BALL_AG15_IS_GPIO
#define BALL_AG15_IS_GPIO 0
#endif
#ifndef PAD_PCM_A1_IS_GPIO
#define PAD_PCM_A1_IS_GPIO BALL_AG15_IS_GPIO
#endif

#define BALL_AL13 PAD_TS0_D6
#define PAD_TS0_D6 162
#define GPIO_PAD_162 GPIO161
#ifndef BALL_AL13_IS_GPIO
#define BALL_AL13_IS_GPIO 0
#endif
#ifndef PAD_TS0_D6_IS_GPIO
#define PAD_TS0_D6_IS_GPIO BALL_AL13_IS_GPIO
#endif

#define BALL_AK16 PAD_PCM_IOWR_N
#define PAD_PCM_IOWR_N 125
#define GPIO_PAD_125 GPIO124
#ifndef BALL_AK16_IS_GPIO
#define BALL_AK16_IS_GPIO 0
#endif
#ifndef PAD_PCM_IOWR_N_IS_GPIO
#define PAD_PCM_IOWR_N_IS_GPIO BALL_AK16_IS_GPIO
#endif

#define BALL_AL14 PAD_TS0_D5
#define PAD_TS0_D5 161
#define GPIO_PAD_161 GPIO160
#ifndef BALL_AL14_IS_GPIO
#define BALL_AL14_IS_GPIO 0
#endif
#ifndef PAD_TS0_D5_IS_GPIO
#define PAD_TS0_D5_IS_GPIO BALL_AL14_IS_GPIO
#endif

#define BALL_AH16 PAD_PCM_A11
#define PAD_PCM_A11 122
#define GPIO_PAD_122 GPIO121
#ifndef BALL_AH16_IS_GPIO
#define BALL_AH16_IS_GPIO 0
#endif
#ifndef PAD_PCM_A11_IS_GPIO
#define PAD_PCM_A11_IS_GPIO BALL_AH16_IS_GPIO
#endif

#define BALL_AJ15 PAD_PCM_OE_N
#define PAD_PCM_OE_N 121
#define GPIO_PAD_121 GPIO120
#ifndef BALL_AJ15_IS_GPIO
#define BALL_AJ15_IS_GPIO 0
#endif
#ifndef PAD_PCM_OE_N_IS_GPIO
#define PAD_PCM_OE_N_IS_GPIO BALL_AJ15_IS_GPIO
#endif

#define BALL_AG16 PAD_PCM_IORD_N
#define PAD_PCM_IORD_N 123
#define GPIO_PAD_123 GPIO122
#ifndef BALL_AG16_IS_GPIO
#define BALL_AG16_IS_GPIO 0
#endif
#ifndef PAD_PCM_IORD_N_IS_GPIO
#define PAD_PCM_IORD_N_IS_GPIO BALL_AG16_IS_GPIO
#endif

#define BALL_AJ17 PAD_PCM_A10
#define PAD_PCM_A10 120
#define GPIO_PAD_120 GPIO119
#ifndef BALL_AJ17_IS_GPIO
#define BALL_AJ17_IS_GPIO 0
#endif
#ifndef PAD_PCM_A10_IS_GPIO
#define PAD_PCM_A10_IS_GPIO BALL_AJ17_IS_GPIO
#endif

#define BALL_AK14 PAD_TS0_D4
#define PAD_TS0_D4 160
#define GPIO_PAD_160 GPIO159
#ifndef BALL_AK14_IS_GPIO
#define BALL_AK14_IS_GPIO 0
#endif
#ifndef PAD_TS0_D4_IS_GPIO
#define PAD_TS0_D4_IS_GPIO BALL_AK14_IS_GPIO
#endif

#define BALL_AK17 PAD_PCM_CE_N
#define PAD_PCM_CE_N 119
#define GPIO_PAD_119 GPIO118
#ifndef BALL_AK17_IS_GPIO
#define BALL_AK17_IS_GPIO 0
#endif
#ifndef PAD_PCM_CE_N_IS_GPIO
#define PAD_PCM_CE_N_IS_GPIO BALL_AK17_IS_GPIO
#endif

#define BALL_AF16 PAD_PCM_D5
#define PAD_PCM_D5 116
#define GPIO_PAD_116 GPIO115
#ifndef BALL_AF16_IS_GPIO
#define BALL_AF16_IS_GPIO 0
#endif
#ifndef PAD_PCM_D5_IS_GPIO
#define PAD_PCM_D5_IS_GPIO BALL_AF16_IS_GPIO
#endif

#define BALL_AH17 PAD_PCM_D7
#define PAD_PCM_D7 118
#define GPIO_PAD_118 GPIO117
#ifndef BALL_AH17_IS_GPIO
#define BALL_AH17_IS_GPIO 0
#endif
#ifndef PAD_PCM_D7_IS_GPIO
#define PAD_PCM_D7_IS_GPIO BALL_AH17_IS_GPIO
#endif

#define BALL_AG17 PAD_PCM_D4
#define PAD_PCM_D4 115
#define GPIO_PAD_115 GPIO114
#ifndef BALL_AG17_IS_GPIO
#define BALL_AG17_IS_GPIO 0
#endif
#ifndef PAD_PCM_D4_IS_GPIO
#define PAD_PCM_D4_IS_GPIO BALL_AG17_IS_GPIO
#endif

#define BALL_AJ18 PAD_PCM_D6
#define PAD_PCM_D6 117
#define GPIO_PAD_117 GPIO116
#ifndef BALL_AJ18_IS_GPIO
#define BALL_AJ18_IS_GPIO 0
#endif
#ifndef PAD_PCM_D6_IS_GPIO
#define PAD_PCM_D6_IS_GPIO BALL_AJ18_IS_GPIO
#endif

#define BALL_AH18 PAD_PCM_D3
#define PAD_PCM_D3 114
#define GPIO_PAD_114 GPIO113
#ifndef BALL_AH18_IS_GPIO
#define BALL_AH18_IS_GPIO 0
#endif
#ifndef PAD_PCM_D3_IS_GPIO
#define PAD_PCM_D3_IS_GPIO BALL_AH18_IS_GPIO
#endif

#define BALL_AH32 PAD_TS2_VLD
#define PAD_TS2_VLD 191
#define GPIO_PAD_191 GPIO190
#ifndef BALL_AH32_IS_GPIO
#define BALL_AH32_IS_GPIO 0
#endif
#ifndef PAD_TS2_VLD_IS_GPIO
#define PAD_TS2_VLD_IS_GPIO BALL_AH32_IS_GPIO
#endif

#define BALL_AG18 PAD_PCM_CD_N
#define PAD_PCM_CD_N 146
#define GPIO_PAD_146 GPIO145
#ifndef BALL_AG18_IS_GPIO
#define BALL_AG18_IS_GPIO 0
#endif
#ifndef PAD_PCM_CD_N_IS_GPIO
#define PAD_PCM_CD_N_IS_GPIO BALL_AG18_IS_GPIO
#endif

#define BALL_AH31 PAD_TS2_SYNC
#define PAD_TS2_SYNC 192
#define GPIO_PAD_192 GPIO191
#ifndef BALL_AH31_IS_GPIO
#define BALL_AH31_IS_GPIO 0
#endif
#ifndef PAD_TS2_SYNC_IS_GPIO
#define PAD_TS2_SYNC_IS_GPIO BALL_AH31_IS_GPIO
#endif

#define PAD_PCM2_CD_N 9999
#ifndef PAD_PCM2_CD_N_IS_GPIO
#define PAD_PCM2_CD_N_IS_GPIO 0
#endif

#define BALL_AG32 PAD_TS2_CLK
#define PAD_TS2_CLK 193
#define GPIO_PAD_193 GPIO192
#ifndef BALL_AG32_IS_GPIO
#define BALL_AG32_IS_GPIO 0
#endif
#ifndef PAD_TS2_CLK_IS_GPIO
#define PAD_TS2_CLK_IS_GPIO BALL_AG32_IS_GPIO
#endif

#define PAD_TS3_SYNC 9999
#ifndef PAD_TS3_SYNC_IS_GPIO
#define PAD_TS3_SYNC_IS_GPIO 0
#endif

#define BALL_AG31 PAD_TS2_D0
#define PAD_TS2_D0 190
#define GPIO_PAD_190 GPIO189
#ifndef BALL_AG31_IS_GPIO
#define BALL_AG31_IS_GPIO 0
#endif
#ifndef PAD_TS2_D0_IS_GPIO
#define PAD_TS2_D0_IS_GPIO BALL_AG31_IS_GPIO
#endif

#define PAD_TS3_VLD 9999
#ifndef PAD_TS3_VLD_IS_GPIO
#define PAD_TS3_VLD_IS_GPIO 0
#endif

#define PAD_TS2_D1 9999
#ifndef PAD_TS2_D1_IS_GPIO
#define PAD_TS2_D1_IS_GPIO 0
#endif

#define PAD_TS2_D2 9999
#ifndef PAD_TS2_D2_IS_GPIO
#define PAD_TS2_D2_IS_GPIO 0
#endif

#define PAD_TS3_CLK 9999
#ifndef PAD_TS3_CLK_IS_GPIO
#define PAD_TS3_CLK_IS_GPIO 0
#endif

#define PAD_TS2_D3 9999
#ifndef PAD_TS2_D3_IS_GPIO
#define PAD_TS2_D3_IS_GPIO 0
#endif

#define PAD_TS2_D4 9999
#ifndef PAD_TS2_D4_IS_GPIO
#define PAD_TS2_D4_IS_GPIO 0
#endif

#define PAD_TS3_D0 9999
#ifndef PAD_TS3_D0_IS_GPIO
#define PAD_TS3_D0_IS_GPIO 0
#endif

#define PAD_TS2_D5 9999
#ifndef PAD_TS2_D5_IS_GPIO
#define PAD_TS2_D5_IS_GPIO 0
#endif

#define PAD_TS3_D1 9999
#ifndef PAD_TS3_D1_IS_GPIO
#define PAD_TS3_D1_IS_GPIO 0
#endif

#define PAD_TS2_D6 9999
#ifndef PAD_TS2_D6_IS_GPIO
#define PAD_TS2_D6_IS_GPIO 0
#endif

#define PAD_TS3_D2 9999
#ifndef PAD_TS3_D2_IS_GPIO
#define PAD_TS3_D2_IS_GPIO 0
#endif

#define PAD_TS2_D7 9999
#ifndef PAD_TS2_D7_IS_GPIO
#define PAD_TS2_D7_IS_GPIO 0
#endif

#define PAD_TS3_D3 9999
#ifndef PAD_TS3_D3_IS_GPIO
#define PAD_TS3_D3_IS_GPIO 0
#endif

#define PAD_TS3_D6 9999
#ifndef PAD_TS3_D6_IS_GPIO
#define PAD_TS3_D6_IS_GPIO 0
#endif

#define PAD_TS3_D4 9999
#ifndef PAD_TS3_D4_IS_GPIO
#define PAD_TS3_D4_IS_GPIO 0
#endif

#define PAD_TS3_D7 9999
#ifndef PAD_TS3_D7_IS_GPIO
#define PAD_TS3_D7_IS_GPIO 0
#endif

#define PAD_TS3_D5 9999
#ifndef PAD_TS3_D5_IS_GPIO
#define PAD_TS3_D5_IS_GPIO 0
#endif

#define BALL_J4 PAD_SPDIF_OUT
#define PAD_SPDIF_OUT 92
#define GPIO_PAD_92 GPIO91
#ifndef BALL_J4_IS_GPIO
#define BALL_J4_IS_GPIO 0
#endif
#ifndef PAD_SPDIF_OUT_IS_GPIO
#define PAD_SPDIF_OUT_IS_GPIO BALL_J4_IS_GPIO
#endif

#define BALL_E5 PAD_I2S_OUT_SD2
#define PAD_I2S_OUT_SD2 98
#define GPIO_PAD_98 GPIO97
#ifndef BALL_E5_IS_GPIO
#define BALL_E5_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_SD2_IS_GPIO
#define PAD_I2S_OUT_SD2_IS_GPIO BALL_E5_IS_GPIO
#endif

#define BALL_G6 PAD_I2S_OUT_SD3
#define PAD_I2S_OUT_SD3 99
#define GPIO_PAD_99 GPIO98
#ifndef BALL_G6_IS_GPIO
#define BALL_G6_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_SD3_IS_GPIO
#define PAD_I2S_OUT_SD3_IS_GPIO BALL_G6_IS_GPIO
#endif

#define BALL_F5 PAD_I2S_OUT_SD1
#define PAD_I2S_OUT_SD1 97
#define GPIO_PAD_97 GPIO96
#ifndef BALL_F5_IS_GPIO
#define BALL_F5_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_SD1_IS_GPIO
#define PAD_I2S_OUT_SD1_IS_GPIO BALL_F5_IS_GPIO
#endif

#define BALL_F6 PAD_I2S_OUT_SD
#define PAD_I2S_OUT_SD 96
#define GPIO_PAD_96 GPIO95
#ifndef BALL_F6_IS_GPIO
#define BALL_F6_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_SD_IS_GPIO
#define PAD_I2S_OUT_SD_IS_GPIO BALL_F6_IS_GPIO
#endif

#define BALL_D5 PAD_I2S_OUT_BCK
#define PAD_I2S_OUT_BCK 95
#define GPIO_PAD_95 GPIO94
#ifndef BALL_D5_IS_GPIO
#define BALL_D5_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_BCK_IS_GPIO
#define PAD_I2S_OUT_BCK_IS_GPIO BALL_D5_IS_GPIO
#endif

#define PAD_DIM0 9999
#ifndef PAD_DIM0_IS_GPIO
#define PAD_DIM0_IS_GPIO 0
#endif

#define BALL_B11 PAD_SPI1_DI
#define PAD_SPI1_DI 102
#define GPIO_PAD_102 GPIO101
#ifndef BALL_B11_IS_GPIO
#define BALL_B11_IS_GPIO 0
#endif
#ifndef PAD_SPI1_DI_IS_GPIO
#define PAD_SPI1_DI_IS_GPIO BALL_B11_IS_GPIO
#endif

#define BALL_A11 PAD_SPI1_CK
#define PAD_SPI1_CK 101
#define GPIO_PAD_101 GPIO100
#ifndef BALL_A11_IS_GPIO
#define BALL_A11_IS_GPIO 0
#endif
#ifndef PAD_SPI1_CK_IS_GPIO
#define PAD_SPI1_CK_IS_GPIO BALL_A11_IS_GPIO
#endif

#define PAD_DIM1 9999
#ifndef PAD_DIM1_IS_GPIO
#define PAD_DIM1_IS_GPIO 0
#endif

#define PAD_DIM2 9999
#ifndef PAD_DIM2_IS_GPIO
#define PAD_DIM2_IS_GPIO 0
#endif

#define BALL_E6 PAD_I2S_OUT_MCK
#define PAD_I2S_OUT_MCK 94
#define GPIO_PAD_94 GPIO93
#ifndef BALL_E6_IS_GPIO
#define BALL_E6_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_MCK_IS_GPIO
#define PAD_I2S_OUT_MCK_IS_GPIO BALL_E6_IS_GPIO
#endif

#define BALL_D6 PAD_I2S_OUT_WS
#define PAD_I2S_OUT_WS 93
#define GPIO_PAD_93 GPIO92
#ifndef BALL_D6_IS_GPIO
#define BALL_D6_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_WS_IS_GPIO
#define PAD_I2S_OUT_WS_IS_GPIO BALL_D6_IS_GPIO
#endif

#define BALL_A12 PAD_DDCR_CK
#define PAD_DDCR_CK 56
#define GPIO_PAD_56 GPIO55
#ifndef BALL_A12_IS_GPIO
#define BALL_A12_IS_GPIO 0
#endif
#ifndef PAD_DDCR_CK_IS_GPIO
#define PAD_DDCR_CK_IS_GPIO BALL_A12_IS_GPIO
#endif

#define BALL_C12 PAD_DDCR_DA
#define PAD_DDCR_DA 55
#define GPIO_PAD_55 GPIO54
#ifndef BALL_C12_IS_GPIO
#define BALL_C12_IS_GPIO 0
#endif
#ifndef PAD_DDCR_DA_IS_GPIO
#define PAD_DDCR_DA_IS_GPIO BALL_C12_IS_GPIO
#endif

#define BALL_C9 PAD_PWM0
#define PAD_PWM0 147
#define GPIO_PAD_147 GPIO146
#ifndef BALL_C9_IS_GPIO
#define BALL_C9_IS_GPIO 0
#endif
#ifndef PAD_PWM0_IS_GPIO
#define PAD_PWM0_IS_GPIO BALL_C9_IS_GPIO
#endif

#define BALL_A9 PAD_PWM1
#define PAD_PWM1 148
#define GPIO_PAD_148 GPIO147
#ifndef BALL_A9_IS_GPIO
#define BALL_A9_IS_GPIO 0
#endif
#ifndef PAD_PWM1_IS_GPIO
#define PAD_PWM1_IS_GPIO BALL_A9_IS_GPIO
#endif

#define BALL_B9 PAD_PWM2
#define PAD_PWM2 149
#define GPIO_PAD_149 GPIO148
#ifndef BALL_B9_IS_GPIO
#define BALL_B9_IS_GPIO 0
#endif
#ifndef PAD_PWM2_IS_GPIO
#define PAD_PWM2_IS_GPIO BALL_B9_IS_GPIO
#endif

#define BALL_F11 PAD_PWM3
#define PAD_PWM3 150
#define GPIO_PAD_150 GPIO149
#ifndef BALL_F11_IS_GPIO
#define BALL_F11_IS_GPIO 0
#endif
#ifndef PAD_PWM3_IS_GPIO
#define PAD_PWM3_IS_GPIO BALL_F11_IS_GPIO
#endif

#define PAD_PWM4 9999
#ifndef PAD_PWM4_IS_GPIO
#define PAD_PWM4_IS_GPIO 0
#endif

#define BALL_D4 PAD_I2S_IN_WS
#define PAD_I2S_IN_WS 88
#define GPIO_PAD_88 GPIO87
#ifndef BALL_D4_IS_GPIO
#define BALL_D4_IS_GPIO 0
#endif
#ifndef PAD_I2S_IN_WS_IS_GPIO
#define PAD_I2S_IN_WS_IS_GPIO BALL_D4_IS_GPIO
#endif

#define BALL_E4 PAD_I2S_IN_SD
#define PAD_I2S_IN_SD 90
#define GPIO_PAD_90 GPIO89
#ifndef BALL_E4_IS_GPIO
#define BALL_E4_IS_GPIO 0
#endif
#ifndef PAD_I2S_IN_SD_IS_GPIO
#define PAD_I2S_IN_SD_IS_GPIO BALL_E4_IS_GPIO
#endif

#define BALL_F10 PAD_I2S_IN_BCK
#define PAD_I2S_IN_BCK 89
#define GPIO_PAD_89 GPIO88
#ifndef BALL_F10_IS_GPIO
#define BALL_F10_IS_GPIO 0
#endif
#ifndef PAD_I2S_IN_BCK_IS_GPIO
#define PAD_I2S_IN_BCK_IS_GPIO BALL_F10_IS_GPIO
#endif

#define BALL_C11 PAD_SPI2_DI
#define PAD_SPI2_DI 104
#define GPIO_PAD_104 GPIO103
#ifndef BALL_C11_IS_GPIO
#define BALL_C11_IS_GPIO 0
#endif
#ifndef PAD_SPI2_DI_IS_GPIO
#define PAD_SPI2_DI_IS_GPIO BALL_C11_IS_GPIO
#endif

#define BALL_B10 PAD_SPI2_CK
#define PAD_SPI2_CK 103
#define GPIO_PAD_103 GPIO102
#ifndef BALL_B10_IS_GPIO
#define BALL_B10_IS_GPIO 0
#endif
#ifndef PAD_SPI2_CK_IS_GPIO
#define PAD_SPI2_CK_IS_GPIO BALL_B10_IS_GPIO
#endif

#define PAD_DIM3 9999
#ifndef PAD_DIM3_IS_GPIO
#define PAD_DIM3_IS_GPIO 0
#endif

#define BALL_H4 PAD_SPDIF_IN
#define PAD_SPDIF_IN 91
#define GPIO_PAD_91 GPIO90
#ifndef BALL_H4_IS_GPIO
#define BALL_H4_IS_GPIO 0
#endif
#ifndef PAD_SPDIF_IN_IS_GPIO
#define PAD_SPDIF_IN_IS_GPIO BALL_H4_IS_GPIO
#endif

#define PAD_GPIO0 9999
#ifndef PAD_GPIO0_IS_GPIO
#define PAD_GPIO0_IS_GPIO 0
#endif

#define BALL_G5 PAD_GPIO2
#define PAD_GPIO2 59
#define GPIO_PAD_59 GPIO58
#ifndef BALL_G5_IS_GPIO
#define BALL_G5_IS_GPIO 0
#endif
#ifndef PAD_GPIO2_IS_GPIO
#define PAD_GPIO2_IS_GPIO BALL_G5_IS_GPIO
#endif

#define BALL_J6 PAD_GPIO4
#define PAD_GPIO4 61
#define GPIO_PAD_61 GPIO60
#ifndef BALL_J6_IS_GPIO
#define BALL_J6_IS_GPIO 0
#endif
#ifndef PAD_GPIO4_IS_GPIO
#define PAD_GPIO4_IS_GPIO BALL_J6_IS_GPIO
#endif

#define PAD_GPIO1 9999
#ifndef PAD_GPIO1_IS_GPIO
#define PAD_GPIO1_IS_GPIO 0
#endif

#define BALL_H6 PAD_GPIO3
#define PAD_GPIO3 60
#define GPIO_PAD_60 GPIO59
#ifndef BALL_H6_IS_GPIO
#define BALL_H6_IS_GPIO 0
#endif
#ifndef PAD_GPIO3_IS_GPIO
#define PAD_GPIO3_IS_GPIO BALL_H6_IS_GPIO
#endif

#define PAD_GPIO16 9999
#ifndef PAD_GPIO16_IS_GPIO
#define PAD_GPIO16_IS_GPIO 0
#endif

#define BALL_C10 PAD_PWM_PM
#define PAD_PWM_PM 7
#define GPIO_PAD_7 GPIO6
#ifndef BALL_C10_IS_GPIO
#define BALL_C10_IS_GPIO 0
#endif
#ifndef PAD_PWM_PM_IS_GPIO
#define PAD_PWM_PM_IS_GPIO BALL_C10_IS_GPIO
#endif

#define BALL_K6 PAD_GPIO_PM1
#define PAD_GPIO_PM1 11
#define GPIO_PAD_11 GPIO10
#ifndef BALL_K6_IS_GPIO
#define BALL_K6_IS_GPIO 0
#endif
#ifndef PAD_GPIO_PM1_IS_GPIO
#define PAD_GPIO_PM1_IS_GPIO BALL_K6_IS_GPIO
#endif

#define BALL_J5 PAD_GPIO_PM14
#define PAD_GPIO_PM14 22
#define GPIO_PAD_22 GPIO21
#ifndef BALL_J5_IS_GPIO
#define BALL_J5_IS_GPIO 0
#endif
#ifndef PAD_GPIO_PM14_IS_GPIO
#define PAD_GPIO_PM14_IS_GPIO BALL_J5_IS_GPIO
#endif

#define BALL_L6 PAD_GPIO_PM5
#define PAD_GPIO_PM5 15
#define GPIO_PAD_15 GPIO14
#ifndef BALL_L6_IS_GPIO
#define BALL_L6_IS_GPIO 0
#endif
#ifndef PAD_GPIO_PM5_IS_GPIO
#define PAD_GPIO_PM5_IS_GPIO BALL_L6_IS_GPIO
#endif

#define BALL_H5 PAD_WOL_INT_OUT
#define PAD_WOL_INT_OUT 54
#define GPIO_PAD_54 GPIO53
#ifndef BALL_H5_IS_GPIO
#define BALL_H5_IS_GPIO 0
#endif
#ifndef PAD_WOL_INT_OUT_IS_GPIO
#define PAD_WOL_INT_OUT_IS_GPIO BALL_H5_IS_GPIO
#endif

#define BALL_M6 PAD_LED1
#define PAD_LED1 26
#define GPIO_PAD_26 GPIO25
#ifndef BALL_M6_IS_GPIO
#define BALL_M6_IS_GPIO 0
#endif
#ifndef PAD_LED1_IS_GPIO
#define PAD_LED1_IS_GPIO BALL_M6_IS_GPIO
#endif

#define BALL_L5 PAD_LED0
#define PAD_LED0 25
#define GPIO_PAD_25 GPIO24
#ifndef BALL_L5_IS_GPIO
#define BALL_L5_IS_GPIO 0
#endif
#ifndef PAD_LED0_IS_GPIO
#define PAD_LED0_IS_GPIO BALL_L5_IS_GPIO
#endif

#define BALL_P5 PAD_DDCA_CK
#define PAD_DDCA_CK 8
#define GPIO_PAD_8 GPIO7
#ifndef BALL_P5_IS_GPIO
#define BALL_P5_IS_GPIO 0
#endif
#ifndef PAD_DDCA_CK_IS_GPIO
#define PAD_DDCA_CK_IS_GPIO BALL_P5_IS_GPIO
#endif

#define BALL_R5 PAD_DDCA_DA
#define PAD_DDCA_DA 9
#define GPIO_PAD_9 GPIO8
#ifndef BALL_R5_IS_GPIO
#define BALL_R5_IS_GPIO 0
#endif
#ifndef PAD_DDCA_DA_IS_GPIO
#define PAD_DDCA_DA_IS_GPIO BALL_R5_IS_GPIO
#endif

#define BALL_P6 PAD_IRIN
#define PAD_IRIN 5
#define GPIO_PAD_5 GPIO4
#ifndef BALL_P6_IS_GPIO
#define BALL_P6_IS_GPIO 0
#endif
#ifndef PAD_IRIN_IS_GPIO
#define PAD_IRIN_IS_GPIO BALL_P6_IS_GPIO
#endif

#define BALL_N6 PAD_CEC0
#define PAD_CEC0 6
#define GPIO_PAD_6 GPIO5
#ifndef BALL_N6_IS_GPIO
#define BALL_N6_IS_GPIO 0
#endif
#ifndef PAD_CEC0_IS_GPIO
#define PAD_CEC0_IS_GPIO BALL_N6_IS_GPIO
#endif

#define PAD_GPIO_PM10 9999
#ifndef PAD_GPIO_PM10_IS_GPIO
#define PAD_GPIO_PM10_IS_GPIO 0
#endif

#define BALL_AE6 PAD_GPIO_PM11
#define PAD_GPIO_PM11 19
#define GPIO_PAD_19 GPIO18
#ifndef BALL_AE6_IS_GPIO
#define BALL_AE6_IS_GPIO 0
#endif
#ifndef PAD_GPIO_PM11_IS_GPIO
#define PAD_GPIO_PM11_IS_GPIO BALL_AE6_IS_GPIO
#endif

#define PAD_GPIO_PM12 9999
#ifndef PAD_GPIO_PM12_IS_GPIO
#define PAD_GPIO_PM12_IS_GPIO 0
#endif

#define BALL_AE5 PAD_GPIO_PM6
#define PAD_GPIO_PM6 16
#define GPIO_PAD_16 GPIO15
#ifndef BALL_AE5_IS_GPIO
#define BALL_AE5_IS_GPIO 0
#endif
#ifndef PAD_GPIO_PM6_IS_GPIO
#define PAD_GPIO_PM6_IS_GPIO BALL_AE5_IS_GPIO
#endif

#define BALL_D8 PAD_PM_SPI_DI
#define PAD_PM_SPI_DI 3
#define GPIO_PAD_3 GPIO2
#ifndef BALL_D8_IS_GPIO
#define BALL_D8_IS_GPIO 0
#endif
#ifndef PAD_PM_SPI_DI_IS_GPIO
#define PAD_PM_SPI_DI_IS_GPIO BALL_D8_IS_GPIO
#endif

#define PAD_PM_SPI_CZ 9999
#ifndef PAD_PM_SPI_CZ_IS_GPIO
#define PAD_PM_SPI_CZ_IS_GPIO 0
#endif

#define PAD_PM_SPI_DO 9999
#ifndef PAD_PM_SPI_DO_IS_GPIO
#define PAD_PM_SPI_DO_IS_GPIO 0
#endif

#define PAD_PM_SPI_CK 9999
#ifndef PAD_PM_SPI_CK_IS_GPIO
#define PAD_PM_SPI_CK_IS_GPIO 0
#endif

#define BALL_H11 PAD_EMMC_IO17
#define PAD_EMMC_IO17 183
#define GPIO_PAD_183 GPIO182
#ifndef BALL_H11_IS_GPIO
#define BALL_H11_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO17_IS_GPIO
#define PAD_EMMC_IO17_IS_GPIO BALL_H11_IS_GPIO
#endif

#define BALL_C5 PAD_EMMC_IO1
#define PAD_EMMC_IO1 213
#define GPIO_PAD_213 GPIO212
#ifndef BALL_C5_IS_GPIO
#define BALL_C5_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO1_IS_GPIO
#define PAD_EMMC_IO1_IS_GPIO BALL_C5_IS_GPIO
#endif

#define BALL_H10 PAD_EMMC_IO16
#define PAD_EMMC_IO16 182
#define GPIO_PAD_182 GPIO181
#ifndef BALL_H10_IS_GPIO
#define BALL_H10_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO16_IS_GPIO
#define PAD_EMMC_IO16_IS_GPIO BALL_H10_IS_GPIO
#endif

#define BALL_C7 PAD_EMMC_IO3
#define PAD_EMMC_IO3 188
#define GPIO_PAD_188 GPIO187
#ifndef BALL_C7_IS_GPIO
#define BALL_C7_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO3_IS_GPIO
#define PAD_EMMC_IO3_IS_GPIO BALL_C7_IS_GPIO
#endif

#define BALL_F9 PAD_EMMC_IO15
#define PAD_EMMC_IO15 184
#define GPIO_PAD_184 GPIO183
#ifndef BALL_F9_IS_GPIO
#define BALL_F9_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO15_IS_GPIO
#define PAD_EMMC_IO15_IS_GPIO BALL_F9_IS_GPIO
#endif

#define BALL_B3 PAD_EMMC_IO2
#define PAD_EMMC_IO2 214
#define GPIO_PAD_214 GPIO213
#ifndef BALL_B3_IS_GPIO
#define BALL_B3_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO2_IS_GPIO
#define PAD_EMMC_IO2_IS_GPIO BALL_B3_IS_GPIO
#endif

#define BALL_G11 PAD_EMMC_IO14
#define PAD_EMMC_IO14 180
#define GPIO_PAD_180 GPIO179
#ifndef BALL_G11_IS_GPIO
#define BALL_G11_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO14_IS_GPIO
#define PAD_EMMC_IO14_IS_GPIO BALL_G11_IS_GPIO
#endif

#define BALL_C6 PAD_EMMC_IO0
#define PAD_EMMC_IO0 189
#define GPIO_PAD_189 GPIO188
#ifndef BALL_C6_IS_GPIO
#define BALL_C6_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO0_IS_GPIO
#define PAD_EMMC_IO0_IS_GPIO BALL_C6_IS_GPIO
#endif

#define BALL_G10 PAD_EMMC_IO13
#define PAD_EMMC_IO13 212
#define GPIO_PAD_212 GPIO211
#ifndef BALL_G10_IS_GPIO
#define BALL_G10_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO13_IS_GPIO
#define PAD_EMMC_IO13_IS_GPIO BALL_G10_IS_GPIO
#endif

#define BALL_G9 PAD_EMMC_IO12
#define PAD_EMMC_IO12 179
#define GPIO_PAD_179 GPIO178
#ifndef BALL_G9_IS_GPIO
#define BALL_G9_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO12_IS_GPIO
#define PAD_EMMC_IO12_IS_GPIO BALL_G9_IS_GPIO
#endif

#define BALL_B4 PAD_EMMC_IO6
#define PAD_EMMC_IO6 216
#define GPIO_PAD_216 GPIO215
#ifndef BALL_B4_IS_GPIO
#define BALL_B4_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO6_IS_GPIO
#define PAD_EMMC_IO6_IS_GPIO BALL_B4_IS_GPIO
#endif

#define BALL_A5 PAD_EMMC_IO5
#define PAD_EMMC_IO5 217
#define GPIO_PAD_217 GPIO216
#ifndef BALL_A5_IS_GPIO
#define BALL_A5_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO5_IS_GPIO
#define PAD_EMMC_IO5_IS_GPIO BALL_A5_IS_GPIO
#endif

#define BALL_C8 PAD_EMMC_IO11
#define PAD_EMMC_IO11 185
#define GPIO_PAD_185 GPIO184
#ifndef BALL_C8_IS_GPIO
#define BALL_C8_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO11_IS_GPIO
#define PAD_EMMC_IO11_IS_GPIO BALL_C8_IS_GPIO
#endif

#define BALL_A2 PAD_EMMC_IO8
#define PAD_EMMC_IO8 186
#define GPIO_PAD_186 GPIO185
#ifndef BALL_A2_IS_GPIO
#define BALL_A2_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO8_IS_GPIO
#define PAD_EMMC_IO8_IS_GPIO BALL_A2_IS_GPIO
#endif

#define BALL_A3 PAD_EMMC_IO7
#define PAD_EMMC_IO7 215
#define GPIO_PAD_215 GPIO214
#ifndef BALL_A3_IS_GPIO
#define BALL_A3_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO7_IS_GPIO
#define PAD_EMMC_IO7_IS_GPIO BALL_A3_IS_GPIO
#endif

#define BALL_B6 PAD_EMMC_IO4
#define PAD_EMMC_IO4 187
#define GPIO_PAD_187 GPIO186
#ifndef BALL_B6_IS_GPIO
#define BALL_B6_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO4_IS_GPIO
#define PAD_EMMC_IO4_IS_GPIO BALL_B6_IS_GPIO
#endif

#define BALL_B2 PAD_EMMC_IO10
#define PAD_EMMC_IO10 181
#define GPIO_PAD_181 GPIO180
#ifndef BALL_B2_IS_GPIO
#define BALL_B2_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO10_IS_GPIO
#define PAD_EMMC_IO10_IS_GPIO BALL_B2_IS_GPIO
#endif

#define BALL_B8 PAD_EMMC_IO9
#define PAD_EMMC_IO9 178
#define GPIO_PAD_178 GPIO177
#ifndef BALL_B8_IS_GPIO
#define BALL_B8_IS_GPIO 0
#endif
#ifndef PAD_EMMC_IO9_IS_GPIO
#define PAD_EMMC_IO9_IS_GPIO BALL_B8_IS_GPIO
#endif

#define BALL_R4 PAD_SAR0
#define PAD_SAR0 42
#define GPIO_PAD_42 GPIO41
#ifndef BALL_R4_IS_GPIO
#define BALL_R4_IS_GPIO 0
#endif
#ifndef PAD_SAR0_IS_GPIO
#define PAD_SAR0_IS_GPIO BALL_R4_IS_GPIO
#endif

#define BALL_P4 PAD_SAR1
#define PAD_SAR1 43
#define GPIO_PAD_43 GPIO42
#ifndef BALL_P4_IS_GPIO
#define BALL_P4_IS_GPIO 0
#endif
#ifndef PAD_SAR1_IS_GPIO
#define PAD_SAR1_IS_GPIO BALL_P4_IS_GPIO
#endif

#define BALL_N5 PAD_SAR2
#define PAD_SAR2 44
#define GPIO_PAD_44 GPIO43
#ifndef BALL_N5_IS_GPIO
#define BALL_N5_IS_GPIO 0
#endif
#ifndef PAD_SAR2_IS_GPIO
#define PAD_SAR2_IS_GPIO BALL_N5_IS_GPIO
#endif

#define BALL_M4 PAD_SAR3
#define PAD_SAR3 45
#define GPIO_PAD_45 GPIO44
#ifndef BALL_M4_IS_GPIO
#define BALL_M4_IS_GPIO 0
#endif
#ifndef PAD_SAR3_IS_GPIO
#define PAD_SAR3_IS_GPIO BALL_M4_IS_GPIO
#endif

#define PAD_SAR4 9999
#ifndef PAD_SAR4_IS_GPIO
#define PAD_SAR4_IS_GPIO 0
#endif


// PADS group name to index
#define PADS_DDCR           1223
#define PADS_DDCR2          1224
#define PADS_TS0            1225
#define PADS_TS1            1226
#define PADS_GPIO1_GPIO2    1227
#define PADS_LHSYNC2_LVSYNC2 1228
#define PADS_PCI_AD20_AD21  1229
#define PADS_PCI            1230
#define PADS_PCM            1231
#define PADS_SAR            1232
#define PADS_DOUT           1233
#define PADS_DIN            1234
#define PADS_I2S            1235
#define PADS_PF             1236
#define PADS_EMAC           1237
#define PADS_TCON           1238
#define PADS_UART1_MODE1    1239
#define PADS_UART1_MODE2    1240
#define PADS_UART1_MODE3    1241
#define PADS_UART2_MODE1    1242
#define PADS_UART2_MODE2    1243
#define PADS_UART2_MODE3    1244
#define PADS_ET_MODE0       1245
#define PADS_ET_MODE1       1246
#define PADS_ET_MODE2       1247
#define PADS_ET_MODE3       1248
#define PADS_MIIC           1249
#define PADS_PF_MODE1       1250
#define PADS_PF_MODE2       1251
#define PADS_PF_MODE3       1252
#define PADS_SPI_CZ1        1253
#define PADS_SPI_CZ2        1254
#define PADS_SPI_CZ3        1255
#define PADS_DDCR3          1256

// chip capbilities
#define CHIP_HAS_BT656_IN          0
#define CHIP_HAS_TS0               1
#define CHIP_HAS_TS1               0
#define CHIP_HAS_LVDS_10BIT_X2     1
#define CHIP_HAS_LVDS_8BIT_X2      1
#define CHIP_HAS_LVDS_8BIT_X1      1
#define CHIP_HAS_CIMAX             0
#define CHIP_HAS_USB_P0            1
#define CHIP_HAS_USB_P1            1
#define CHIP_HAS_USBVBUS0          0
#define CHIP_HAS_USBVBUS1          0
#define CHIP_HAS_UART1_MODE1       1
#define CHIP_HAS_UART1_MODE2       1
#define CHIP_HAS_UART1_MODE3       1
#define CHIP_HAS_PCMCIA1           0
#define CHIP_HAS_PCMCIA2           0
#define CHIP_HAS_PCMCIA            0
#define CHIP_HAS_UART2_MODE1       1
#define CHIP_HAS_UART2_MODE2       1
#define CHIP_HAS_UART2_MODE3       1
#define CHIP_HAS_RGB_A             1
#define CHIP_HAS_RGB_B             1
#define CHIP_HAS_RGB_C             1
#define CHIP_HAS_HDMI_A            1
#define CHIP_HAS_HDMI_B            1
#define CHIP_HAS_HDMI_C            1
#define CHIP_HAS_SPI_CZ1           1
#define CHIP_HAS_SPI_CZ2           0
#define CHIP_HAS_SPI_CZ3           0
#define CHIP_HAS_DDCR              1
#define CHIP_HAS_DDCR2             1
#define CHIP_HAS_TCON              1
#define CHIP_HAS_ET_MODE0_MII      1
#define CHIP_HAS_ET_MODE0_RMII     1
#define CHIP_HAS_ET_MODE1_MII      1
#define CHIP_HAS_ET_MODE1_RMII     1
#define CHIP_HAS_ET_MODE2_MII      1
#define CHIP_HAS_ET_MODE2_RMII     1
#define CHIP_HAS_I2S_IN            1
#define CHIP_HAS_I2S_OUT           1
#define CHIP_HAS_SPDIF_IN          0
#define CHIP_HAS_SPDIF_OUT         1
#define CHIP_HAS_DDR_A_CMD         1
#define CHIP_HAS_DDR_A_DATA        1
#define CHIP_HAS_DDR_B_CMD         1
#define CHIP_HAS_DDR_B_DATA        1
#define CHIP_USE_PCM_CDN_IN_PCM2   0
#define CHIP_USE_I2S_IN_IN_PCM     0
#define CHIP_USE_I2S_OUT_IN_PCM    0
#define CHIP_USE_SPDIF_IN_IN_PCM   0
#define CHIP_USE_SPDIF_OUT_IN_PCM  0
#define CHIP_USE_IIC_IN_DDCR2      0
#define CHIP_USE_PWM2_IN_GPIO14    0
#define CHIP_USE_PWM3_IN_GPIO15    0

// chip additional information
#define CHIP_FAMILY_TYPE           CHIP_FAMILY_MASERATI

#endif /* _MSD95VFDW_H_*/
