/* SPDX-License-Identifier: GPL-2.0-only OR BSD-3-Clause */
/******************************************************************************
 *
 * This file is provided under a dual license.  When you use or
 * distribute this software, you may choose to be licensed under
 * version 2 of the GNU General Public License ("GPLv2 License")
 * or BSD License.
 *
 * GPLv2 License
 *
 * Copyright(C) 2019 MediaTek Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of version 2 of the GNU General Public License as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See http://www.gnu.org/licenses/gpl-2.0.html for more details.
 *
 * BSD LICENSE
 *
 * Copyright(C) 2019 MediaTek Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *****************************************************************************/

// This file is generated by script file, please do not edit it directly
#ifndef _MSD92QEBW2_H_
#define _MSD92QEBW2_H_

#define PAD_NC   9999
#define PAD_GND  0

#define PIN_5 PAD_C_RX0N
#define PAD_C_RX0N 166
#define GPIO_PAD_166 GPIO165
#ifndef PIN_5_IS_GPIO
#define PIN_5_IS_GPIO 0
#endif
#ifndef PAD_C_RX0N_IS_GPIO
#define PAD_C_RX0N_IS_GPIO PIN_5_IS_GPIO
#endif

#define PIN_3 PAD_C_RXCN
#define PAD_C_RXCN 172
#define GPIO_PAD_172 GPIO171
#ifndef PIN_3_IS_GPIO
#define PIN_3_IS_GPIO 0
#endif
#ifndef PAD_C_RXCN_IS_GPIO
#define PAD_C_RXCN_IS_GPIO PIN_3_IS_GPIO
#endif

#define PIN_6 PAD_C_RX0P
#define PAD_C_RX0P 167
#define GPIO_PAD_167 GPIO166
#ifndef PIN_6_IS_GPIO
#define PIN_6_IS_GPIO 0
#endif
#ifndef PAD_C_RX0P_IS_GPIO
#define PAD_C_RX0P_IS_GPIO PIN_6_IS_GPIO
#endif

#define PIN_4 PAD_C_RXCP
#define PAD_C_RXCP 173
#define GPIO_PAD_173 GPIO172
#ifndef PIN_4_IS_GPIO
#define PIN_4_IS_GPIO 0
#endif
#ifndef PAD_C_RXCP_IS_GPIO
#define PAD_C_RXCP_IS_GPIO PIN_4_IS_GPIO
#endif

#define PIN_10 PAD_C_RX2N
#define PAD_C_RX2N 170
#define GPIO_PAD_170 GPIO169
#ifndef PIN_10_IS_GPIO
#define PIN_10_IS_GPIO 0
#endif
#ifndef PAD_C_RX2N_IS_GPIO
#define PAD_C_RX2N_IS_GPIO PIN_10_IS_GPIO
#endif

#define PIN_8 PAD_C_RX1N
#define PAD_C_RX1N 168
#define GPIO_PAD_168 GPIO167
#ifndef PIN_8_IS_GPIO
#define PIN_8_IS_GPIO 0
#endif
#ifndef PAD_C_RX1N_IS_GPIO
#define PAD_C_RX1N_IS_GPIO PIN_8_IS_GPIO
#endif

#define PIN_11 PAD_C_RX2P
#define PAD_C_RX2P 171
#define GPIO_PAD_171 GPIO170
#ifndef PIN_11_IS_GPIO
#define PIN_11_IS_GPIO 0
#endif
#ifndef PAD_C_RX2P_IS_GPIO
#define PAD_C_RX2P_IS_GPIO PIN_11_IS_GPIO
#endif

#define PIN_9 PAD_C_RX1P
#define PAD_C_RX1P 169
#define GPIO_PAD_169 GPIO168
#ifndef PIN_9_IS_GPIO
#define PIN_9_IS_GPIO 0
#endif
#ifndef PAD_C_RX1P_IS_GPIO
#define PAD_C_RX1P_IS_GPIO PIN_9_IS_GPIO
#endif

#define PIN_15 PAD_B_RX0N
#define PAD_B_RX0N 158
#define GPIO_PAD_158 GPIO157
#ifndef PIN_15_IS_GPIO
#define PIN_15_IS_GPIO 0
#endif
#ifndef PAD_B_RX0N_IS_GPIO
#define PAD_B_RX0N_IS_GPIO PIN_15_IS_GPIO
#endif

#define PIN_13 PAD_B_RXCN
#define PAD_B_RXCN 164
#define GPIO_PAD_164 GPIO163
#ifndef PIN_13_IS_GPIO
#define PIN_13_IS_GPIO 0
#endif
#ifndef PAD_B_RXCN_IS_GPIO
#define PAD_B_RXCN_IS_GPIO PIN_13_IS_GPIO
#endif

#define PIN_16 PAD_B_RX0P
#define PAD_B_RX0P 159
#define GPIO_PAD_159 GPIO158
#ifndef PIN_16_IS_GPIO
#define PIN_16_IS_GPIO 0
#endif
#ifndef PAD_B_RX0P_IS_GPIO
#define PAD_B_RX0P_IS_GPIO PIN_16_IS_GPIO
#endif

#define PIN_14 PAD_B_RXCP
#define PAD_B_RXCP 165
#define GPIO_PAD_165 GPIO164
#ifndef PIN_14_IS_GPIO
#define PIN_14_IS_GPIO 0
#endif
#ifndef PAD_B_RXCP_IS_GPIO
#define PAD_B_RXCP_IS_GPIO PIN_14_IS_GPIO
#endif

#define PIN_20 PAD_B_RX2N
#define PAD_B_RX2N 162
#define GPIO_PAD_162 GPIO161
#ifndef PIN_20_IS_GPIO
#define PIN_20_IS_GPIO 0
#endif
#ifndef PAD_B_RX2N_IS_GPIO
#define PAD_B_RX2N_IS_GPIO PIN_20_IS_GPIO
#endif

#define PIN_18 PAD_B_RX1N
#define PAD_B_RX1N 160
#define GPIO_PAD_160 GPIO159
#ifndef PIN_18_IS_GPIO
#define PIN_18_IS_GPIO 0
#endif
#ifndef PAD_B_RX1N_IS_GPIO
#define PAD_B_RX1N_IS_GPIO PIN_18_IS_GPIO
#endif

#define PIN_21 PAD_B_RX2P
#define PAD_B_RX2P 163
#define GPIO_PAD_163 GPIO162
#ifndef PIN_21_IS_GPIO
#define PIN_21_IS_GPIO 0
#endif
#ifndef PAD_B_RX2P_IS_GPIO
#define PAD_B_RX2P_IS_GPIO PIN_21_IS_GPIO
#endif

#define PIN_19 PAD_B_RX1P
#define PAD_B_RX1P 161
#define GPIO_PAD_161 GPIO160
#ifndef PIN_19_IS_GPIO
#define PIN_19_IS_GPIO 0
#endif
#ifndef PAD_B_RX1P_IS_GPIO
#define PAD_B_RX1P_IS_GPIO PIN_19_IS_GPIO
#endif

#define PIN_25 PAD_RX0N
#define PAD_RX0N 150
#define GPIO_PAD_150 GPIO149
#ifndef PIN_25_IS_GPIO
#define PIN_25_IS_GPIO 0
#endif
#ifndef PAD_RX0N_IS_GPIO
#define PAD_RX0N_IS_GPIO PIN_25_IS_GPIO
#endif

#define PIN_23 PAD_RXCN
#define PAD_RXCN 156
#define GPIO_PAD_156 GPIO155
#ifndef PIN_23_IS_GPIO
#define PIN_23_IS_GPIO 0
#endif
#ifndef PAD_RXCN_IS_GPIO
#define PAD_RXCN_IS_GPIO PIN_23_IS_GPIO
#endif

#define PIN_26 PAD_RX0P
#define PAD_RX0P 151
#define GPIO_PAD_151 GPIO150
#ifndef PIN_26_IS_GPIO
#define PIN_26_IS_GPIO 0
#endif
#ifndef PAD_RX0P_IS_GPIO
#define PAD_RX0P_IS_GPIO PIN_26_IS_GPIO
#endif

#define PIN_24 PAD_RXCP
#define PAD_RXCP 157
#define GPIO_PAD_157 GPIO156
#ifndef PIN_24_IS_GPIO
#define PIN_24_IS_GPIO 0
#endif
#ifndef PAD_RXCP_IS_GPIO
#define PAD_RXCP_IS_GPIO PIN_24_IS_GPIO
#endif

#define PIN_30 PAD_RX2N
#define PAD_RX2N 154
#define GPIO_PAD_154 GPIO153
#ifndef PIN_30_IS_GPIO
#define PIN_30_IS_GPIO 0
#endif
#ifndef PAD_RX2N_IS_GPIO
#define PAD_RX2N_IS_GPIO PIN_30_IS_GPIO
#endif

#define PIN_28 PAD_RX1N
#define PAD_RX1N 152
#define GPIO_PAD_152 GPIO151
#ifndef PIN_28_IS_GPIO
#define PIN_28_IS_GPIO 0
#endif
#ifndef PAD_RX1N_IS_GPIO
#define PAD_RX1N_IS_GPIO PIN_28_IS_GPIO
#endif

#define PIN_31 PAD_RX2P
#define PAD_RX2P 155
#define GPIO_PAD_155 GPIO154
#ifndef PIN_31_IS_GPIO
#define PIN_31_IS_GPIO 0
#endif
#ifndef PAD_RX2P_IS_GPIO
#define PAD_RX2P_IS_GPIO PIN_31_IS_GPIO
#endif

#define PIN_29 PAD_RX1P
#define PAD_RX1P 153
#define GPIO_PAD_153 GPIO152
#ifndef PIN_29_IS_GPIO
#define PIN_29_IS_GPIO 0
#endif
#ifndef PAD_RX1P_IS_GPIO
#define PAD_RX1P_IS_GPIO PIN_29_IS_GPIO
#endif

#define PIN_34 PADA_HSYNC0
#define PADA_HSYNC0 189
#define GPIO_PAD_189 GPIO188
#ifndef PIN_34_IS_GPIO
#define PIN_34_IS_GPIO 0
#endif
#ifndef PADA_HSYNC0_IS_GPIO
#define PADA_HSYNC0_IS_GPIO PIN_34_IS_GPIO
#endif

#define PIN_35 PADA_BIN0P
#define PADA_BIN0P 186
#define GPIO_PAD_186 GPIO185
#ifndef PIN_35_IS_GPIO
#define PIN_35_IS_GPIO 0
#endif
#ifndef PADA_BIN0P_IS_GPIO
#define PADA_BIN0P_IS_GPIO PIN_35_IS_GPIO
#endif

#define PIN_36 PADA_GIN0P
#define PADA_GIN0P 180
#define GPIO_PAD_180 GPIO179
#ifndef PIN_36_IS_GPIO
#define PIN_36_IS_GPIO 0
#endif
#ifndef PADA_GIN0P_IS_GPIO
#define PADA_GIN0P_IS_GPIO PIN_36_IS_GPIO
#endif

#define PIN_37 PADA_GIN0M
#define PADA_GIN0M 183
#define GPIO_PAD_183 GPIO182
#ifndef PIN_37_IS_GPIO
#define PIN_37_IS_GPIO 0
#endif
#ifndef PADA_GIN0M_IS_GPIO
#define PADA_GIN0M_IS_GPIO PIN_37_IS_GPIO
#endif

#define PIN_38 PADA_RIN0P
#define PADA_RIN0P 177
#define GPIO_PAD_177 GPIO176
#ifndef PIN_38_IS_GPIO
#define PIN_38_IS_GPIO 0
#endif
#ifndef PADA_RIN0P_IS_GPIO
#define PADA_RIN0P_IS_GPIO PIN_38_IS_GPIO
#endif

#define PIN_39 PADA_VSYNC0
#define PADA_VSYNC0 192
#define GPIO_PAD_192 GPIO191
#ifndef PIN_39_IS_GPIO
#define PIN_39_IS_GPIO 0
#endif
#ifndef PADA_VSYNC0_IS_GPIO
#define PADA_VSYNC0_IS_GPIO PIN_39_IS_GPIO
#endif

#define PADA_HSYNC1 9999
#ifndef PADA_HSYNC1_IS_GPIO
#define PADA_HSYNC1_IS_GPIO 0
#endif

#define PADA_BIN1P 9999
#ifndef PADA_BIN1P_IS_GPIO
#define PADA_BIN1P_IS_GPIO 0
#endif

#define PADA_GIN1P 9999
#ifndef PADA_GIN1P_IS_GPIO
#define PADA_GIN1P_IS_GPIO 0
#endif

#define PADA_GIN1M 9999
#ifndef PADA_GIN1M_IS_GPIO
#define PADA_GIN1M_IS_GPIO 0
#endif

#define PADA_RIN1P 9999
#ifndef PADA_RIN1P_IS_GPIO
#define PADA_RIN1P_IS_GPIO 0
#endif

#define PADA_VSYNC1 9999
#ifndef PADA_VSYNC1_IS_GPIO
#define PADA_VSYNC1_IS_GPIO 0
#endif

#define PADA_HSYNC2 9999
#ifndef PADA_HSYNC2_IS_GPIO
#define PADA_HSYNC2_IS_GPIO 0
#endif

#define PADA_BIN2P 9999
#ifndef PADA_BIN2P_IS_GPIO
#define PADA_BIN2P_IS_GPIO 0
#endif

#define PADA_GIN2P 9999
#ifndef PADA_GIN2P_IS_GPIO
#define PADA_GIN2P_IS_GPIO 0
#endif

#define PADA_GIN2M 9999
#ifndef PADA_GIN2M_IS_GPIO
#define PADA_GIN2M_IS_GPIO 0
#endif

#define PADA_RIN2P 9999
#ifndef PADA_RIN2P_IS_GPIO
#define PADA_RIN2P_IS_GPIO 0
#endif

#define PADA_VSYNC2 9999
#ifndef PADA_VSYNC2_IS_GPIO
#define PADA_VSYNC2_IS_GPIO 0
#endif

#define PIN_45 PAD_LINEIN_L0
#define PAD_LINEIN_L0 146
#define GPIO_PAD_146 GPIO145
#ifndef PIN_45_IS_GPIO
#define PIN_45_IS_GPIO 0
#endif
#ifndef PAD_LINEIN_L0_IS_GPIO
#define PAD_LINEIN_L0_IS_GPIO PIN_45_IS_GPIO
#endif

#define PIN_46 PAD_LINEIN_R0
#define PAD_LINEIN_R0 147
#define GPIO_PAD_147 GPIO146
#ifndef PIN_46_IS_GPIO
#define PIN_46_IS_GPIO 0
#endif
#ifndef PAD_LINEIN_R0_IS_GPIO
#define PAD_LINEIN_R0_IS_GPIO PIN_46_IS_GPIO
#endif

#define PAD_LINEIN_L1 9999
#ifndef PAD_LINEIN_L1_IS_GPIO
#define PAD_LINEIN_L1_IS_GPIO 0
#endif

#define PAD_LINEIN_R1 9999
#ifndef PAD_LINEIN_R1_IS_GPIO
#define PAD_LINEIN_R1_IS_GPIO 0
#endif

#define PIN_72 PAD_GPIO2
#define PAD_GPIO2 27
#define GPIO_PAD_27 GPIO26
#ifndef PIN_72_IS_GPIO
#define PIN_72_IS_GPIO 0
#endif
#ifndef PAD_GPIO2_IS_GPIO
#define PAD_GPIO2_IS_GPIO PIN_72_IS_GPIO
#endif

#define PIN_73 PAD_GPIO1
#define PAD_GPIO1 26
#define GPIO_PAD_26 GPIO25
#ifndef PIN_73_IS_GPIO
#define PIN_73_IS_GPIO 0
#endif
#ifndef PAD_GPIO1_IS_GPIO
#define PAD_GPIO1_IS_GPIO PIN_73_IS_GPIO
#endif

#define PAD_PCM_RESET 9999
#ifndef PAD_PCM_RESET_IS_GPIO
#define PAD_PCM_RESET_IS_GPIO 0
#endif

#define PAD_PCM_IRQA_N 9999
#ifndef PAD_PCM_IRQA_N_IS_GPIO
#define PAD_PCM_IRQA_N_IS_GPIO 0
#endif

#define PAD_PCM_CD_N 9999
#ifndef PAD_PCM_CD_N_IS_GPIO
#define PAD_PCM_CD_N_IS_GPIO 0
#endif

#define PAD_PCM_REG_N 9999
#ifndef PAD_PCM_REG_N_IS_GPIO
#define PAD_PCM_REG_N_IS_GPIO 0
#endif

#define PAD_PCM_CE_N 9999
#ifndef PAD_PCM_CE_N_IS_GPIO
#define PAD_PCM_CE_N_IS_GPIO 0
#endif

#define PAD_PCM_OE_N 9999
#ifndef PAD_PCM_OE_N_IS_GPIO
#define PAD_PCM_OE_N_IS_GPIO 0
#endif

#define PAD_PCM_WE_N 9999
#ifndef PAD_PCM_WE_N_IS_GPIO
#define PAD_PCM_WE_N_IS_GPIO 0
#endif

#define PAD_PCM_WAIT_N 9999
#ifndef PAD_PCM_WAIT_N_IS_GPIO
#define PAD_PCM_WAIT_N_IS_GPIO 0
#endif

#define PAD_PCM_IORD_N 9999
#ifndef PAD_PCM_IORD_N_IS_GPIO
#define PAD_PCM_IORD_N_IS_GPIO 0
#endif

#define PAD_PCM_IOWR_N 9999
#ifndef PAD_PCM_IOWR_N_IS_GPIO
#define PAD_PCM_IOWR_N_IS_GPIO 0
#endif

#define PIN_75 PAD_NAND_CEZ
#define PAD_NAND_CEZ 20
#define GPIO_PAD_20 GPIO19
#ifndef PIN_75_IS_GPIO
#define PIN_75_IS_GPIO 0
#endif
#ifndef PAD_NAND_CEZ_IS_GPIO
#define PAD_NAND_CEZ_IS_GPIO PIN_75_IS_GPIO
#endif

#define PIN_76 PAD_NAND_CLE
#define PAD_NAND_CLE 18
#define GPIO_PAD_18 GPIO17
#ifndef PIN_76_IS_GPIO
#define PIN_76_IS_GPIO 0
#endif
#ifndef PAD_NAND_CLE_IS_GPIO
#define PAD_NAND_CLE_IS_GPIO PIN_76_IS_GPIO
#endif

#define PIN_77 PAD_NAND_REZ
#define PAD_NAND_REZ 17
#define GPIO_PAD_17 GPIO16
#ifndef PIN_77_IS_GPIO
#define PIN_77_IS_GPIO 0
#endif
#ifndef PAD_NAND_REZ_IS_GPIO
#define PAD_NAND_REZ_IS_GPIO PIN_77_IS_GPIO
#endif

#define PIN_78 PAD_NAND_WEZ
#define PAD_NAND_WEZ 22
#define GPIO_PAD_22 GPIO21
#ifndef PIN_78_IS_GPIO
#define PIN_78_IS_GPIO 0
#endif
#ifndef PAD_NAND_WEZ_IS_GPIO
#define PAD_NAND_WEZ_IS_GPIO PIN_78_IS_GPIO
#endif

#define PIN_79 PAD_NAND_WPZ
#define PAD_NAND_WPZ 21
#define GPIO_PAD_21 GPIO20
#ifndef PIN_79_IS_GPIO
#define PIN_79_IS_GPIO 0
#endif
#ifndef PAD_NAND_WPZ_IS_GPIO
#define PAD_NAND_WPZ_IS_GPIO PIN_79_IS_GPIO
#endif

#define PIN_80 PAD_NAND_ALE
#define PAD_NAND_ALE 19
#define GPIO_PAD_19 GPIO18
#ifndef PIN_80_IS_GPIO
#define PIN_80_IS_GPIO 0
#endif
#ifndef PAD_NAND_ALE_IS_GPIO
#define PAD_NAND_ALE_IS_GPIO PIN_80_IS_GPIO
#endif

#define PAD_NAND_RBZ 9999
#ifndef PAD_NAND_RBZ_IS_GPIO
#define PAD_NAND_RBZ_IS_GPIO 0
#endif

#define PAD_TS0_D0 9999
#ifndef PAD_TS0_D0_IS_GPIO
#define PAD_TS0_D0_IS_GPIO 0
#endif

#define PAD_TS0_D1 9999
#ifndef PAD_TS0_D1_IS_GPIO
#define PAD_TS0_D1_IS_GPIO 0
#endif

#define PAD_TS0_D2 9999
#ifndef PAD_TS0_D2_IS_GPIO
#define PAD_TS0_D2_IS_GPIO 0
#endif

#define PAD_TS0_D3 9999
#ifndef PAD_TS0_D3_IS_GPIO
#define PAD_TS0_D3_IS_GPIO 0
#endif

#define PAD_TS0_D4 9999
#ifndef PAD_TS0_D4_IS_GPIO
#define PAD_TS0_D4_IS_GPIO 0
#endif

#define PAD_TS0_D5 9999
#ifndef PAD_TS0_D5_IS_GPIO
#define PAD_TS0_D5_IS_GPIO 0
#endif

#define PAD_TS0_D6 9999
#ifndef PAD_TS0_D6_IS_GPIO
#define PAD_TS0_D6_IS_GPIO 0
#endif

#define PAD_TS0_D7 9999
#ifndef PAD_TS0_D7_IS_GPIO
#define PAD_TS0_D7_IS_GPIO 0
#endif

#define PAD_TS0_VLD 9999
#ifndef PAD_TS0_VLD_IS_GPIO
#define PAD_TS0_VLD_IS_GPIO 0
#endif

#define PAD_TS0_SYNC 9999
#ifndef PAD_TS0_SYNC_IS_GPIO
#define PAD_TS0_SYNC_IS_GPIO 0
#endif

#define PAD_TS0_CLK 9999
#ifndef PAD_TS0_CLK_IS_GPIO
#define PAD_TS0_CLK_IS_GPIO 0
#endif

#define PAD_PCM_D0 9999
#ifndef PAD_PCM_D0_IS_GPIO
#define PAD_PCM_D0_IS_GPIO 0
#endif

#define PAD_PCM_D1 9999
#ifndef PAD_PCM_D1_IS_GPIO
#define PAD_PCM_D1_IS_GPIO 0
#endif

#define PAD_PCM_D2 9999
#ifndef PAD_PCM_D2_IS_GPIO
#define PAD_PCM_D2_IS_GPIO 0
#endif

#define PAD_PCM_D3 9999
#ifndef PAD_PCM_D3_IS_GPIO
#define PAD_PCM_D3_IS_GPIO 0
#endif

#define PAD_PCM_D6 9999
#ifndef PAD_PCM_D6_IS_GPIO
#define PAD_PCM_D6_IS_GPIO 0
#endif

#define PAD_PCM_D4 9999
#ifndef PAD_PCM_D4_IS_GPIO
#define PAD_PCM_D4_IS_GPIO 0
#endif

#define PAD_PCM_D7 9999
#ifndef PAD_PCM_D7_IS_GPIO
#define PAD_PCM_D7_IS_GPIO 0
#endif

#define PAD_PCM_D5 9999
#ifndef PAD_PCM_D5_IS_GPIO
#define PAD_PCM_D5_IS_GPIO 0
#endif

#define PAD_PCM_A14 9999
#ifndef PAD_PCM_A14_IS_GPIO
#define PAD_PCM_A14_IS_GPIO 0
#endif

#define PAD_TS1_VLD 9999
#ifndef PAD_TS1_VLD_IS_GPIO
#define PAD_TS1_VLD_IS_GPIO 0
#endif

#define PAD_PCM_A13 9999
#ifndef PAD_PCM_A13_IS_GPIO
#define PAD_PCM_A13_IS_GPIO 0
#endif

#define PAD_TS1_SYNC 9999
#ifndef PAD_TS1_SYNC_IS_GPIO
#define PAD_TS1_SYNC_IS_GPIO 0
#endif

#define PAD_PCM_A12 9999
#ifndef PAD_PCM_A12_IS_GPIO
#define PAD_PCM_A12_IS_GPIO 0
#endif

#define PAD_TS1_CLK 9999
#ifndef PAD_TS1_CLK_IS_GPIO
#define PAD_TS1_CLK_IS_GPIO 0
#endif

#define PAD_PCM_A11 9999
#ifndef PAD_PCM_A11_IS_GPIO
#define PAD_PCM_A11_IS_GPIO 0
#endif

#define PAD_PCM_A10 9999
#ifndef PAD_PCM_A10_IS_GPIO
#define PAD_PCM_A10_IS_GPIO 0
#endif

#define PAD_TS1_D7 9999
#ifndef PAD_TS1_D7_IS_GPIO
#define PAD_TS1_D7_IS_GPIO 0
#endif

#define PAD_PCM_A9 9999
#ifndef PAD_PCM_A9_IS_GPIO
#define PAD_PCM_A9_IS_GPIO 0
#endif

#define PAD_TS1_D6 9999
#ifndef PAD_TS1_D6_IS_GPIO
#define PAD_TS1_D6_IS_GPIO 0
#endif

#define PAD_PCM_A8 9999
#ifndef PAD_PCM_A8_IS_GPIO
#define PAD_PCM_A8_IS_GPIO 0
#endif

#define PAD_TS1_D5 9999
#ifndef PAD_TS1_D5_IS_GPIO
#define PAD_TS1_D5_IS_GPIO 0
#endif

#define PAD_PCM_A7 9999
#ifndef PAD_PCM_A7_IS_GPIO
#define PAD_PCM_A7_IS_GPIO 0
#endif

#define PAD_TS1_D4 9999
#ifndef PAD_TS1_D4_IS_GPIO
#define PAD_TS1_D4_IS_GPIO 0
#endif

#define PAD_PCM_A6 9999
#ifndef PAD_PCM_A6_IS_GPIO
#define PAD_PCM_A6_IS_GPIO 0
#endif

#define PAD_TS1_D3 9999
#ifndef PAD_TS1_D3_IS_GPIO
#define PAD_TS1_D3_IS_GPIO 0
#endif

#define PAD_PCM_A5 9999
#ifndef PAD_PCM_A5_IS_GPIO
#define PAD_PCM_A5_IS_GPIO 0
#endif

#define PAD_PCM_A4 9999
#ifndef PAD_PCM_A4_IS_GPIO
#define PAD_PCM_A4_IS_GPIO 0
#endif

#define PAD_TS1_D2 9999
#ifndef PAD_TS1_D2_IS_GPIO
#define PAD_TS1_D2_IS_GPIO 0
#endif

#define PAD_PCM_A3 9999
#ifndef PAD_PCM_A3_IS_GPIO
#define PAD_PCM_A3_IS_GPIO 0
#endif

#define PAD_TS1_D1 9999
#ifndef PAD_TS1_D1_IS_GPIO
#define PAD_TS1_D1_IS_GPIO 0
#endif

#define PAD_PCM_A2 9999
#ifndef PAD_PCM_A2_IS_GPIO
#define PAD_PCM_A2_IS_GPIO 0
#endif

#define PAD_TS1_D0 9999
#ifndef PAD_TS1_D0_IS_GPIO
#define PAD_TS1_D0_IS_GPIO 0
#endif

#define PAD_PCM_A1 9999
#ifndef PAD_PCM_A1_IS_GPIO
#define PAD_PCM_A1_IS_GPIO 0
#endif

#define PAD_PCM_A0 9999
#ifndef PAD_PCM_A0_IS_GPIO
#define PAD_PCM_A0_IS_GPIO 0
#endif

#define PAD_USB_DEBUG_GPIO 9999
#ifndef PAD_USB_DEBUG_GPIO_IS_GPIO
#define PAD_USB_DEBUG_GPIO_IS_GPIO 0
#endif

#define PIN_87 PAD_MOD_TX_N13
#define PAD_MOD_TX_N13 145
#define GPIO_PAD_145 GPIO144
#ifndef PIN_87_IS_GPIO
#define PIN_87_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_N13_IS_GPIO
#define PAD_MOD_TX_N13_IS_GPIO PIN_87_IS_GPIO
#endif

#define PIN_88 PAD_MOD_TX_P13
#define PAD_MOD_TX_P13 144
#define GPIO_PAD_144 GPIO143
#ifndef PIN_88_IS_GPIO
#define PIN_88_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_P13_IS_GPIO
#define PAD_MOD_TX_P13_IS_GPIO PIN_88_IS_GPIO
#endif

#define PIN_89 PAD_MOD_TX_N12
#define PAD_MOD_TX_N12 143
#define GPIO_PAD_143 GPIO142
#ifndef PIN_89_IS_GPIO
#define PIN_89_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_N12_IS_GPIO
#define PAD_MOD_TX_N12_IS_GPIO PIN_89_IS_GPIO
#endif

#define PIN_90 PAD_MOD_TX_P12
#define PAD_MOD_TX_P12 142
#define GPIO_PAD_142 GPIO141
#ifndef PIN_90_IS_GPIO
#define PIN_90_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_P12_IS_GPIO
#define PAD_MOD_TX_P12_IS_GPIO PIN_90_IS_GPIO
#endif

#define PIN_91 PAD_MOD_TX_N11
#define PAD_MOD_TX_N11 141
#define GPIO_PAD_141 GPIO140
#ifndef PIN_91_IS_GPIO
#define PIN_91_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_N11_IS_GPIO
#define PAD_MOD_TX_N11_IS_GPIO PIN_91_IS_GPIO
#endif

#define PIN_92 PAD_MOD_TX_P11
#define PAD_MOD_TX_P11 140
#define GPIO_PAD_140 GPIO139
#ifndef PIN_92_IS_GPIO
#define PIN_92_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_P11_IS_GPIO
#define PAD_MOD_TX_P11_IS_GPIO PIN_92_IS_GPIO
#endif

#define PIN_93 PAD_MOD_TX_N10
#define PAD_MOD_TX_N10 139
#define GPIO_PAD_139 GPIO138
#ifndef PIN_93_IS_GPIO
#define PIN_93_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_N10_IS_GPIO
#define PAD_MOD_TX_N10_IS_GPIO PIN_93_IS_GPIO
#endif

#define PIN_94 PAD_MOD_TX_P10
#define PAD_MOD_TX_P10 138
#define GPIO_PAD_138 GPIO137
#ifndef PIN_94_IS_GPIO
#define PIN_94_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_P10_IS_GPIO
#define PAD_MOD_TX_P10_IS_GPIO PIN_94_IS_GPIO
#endif

#define PIN_95 PAD_MOD_TX_N09
#define PAD_MOD_TX_N09 137
#define GPIO_PAD_137 GPIO136
#ifndef PIN_95_IS_GPIO
#define PIN_95_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_N09_IS_GPIO
#define PAD_MOD_TX_N09_IS_GPIO PIN_95_IS_GPIO
#endif

#define PIN_96 PAD_MOD_TX_P09
#define PAD_MOD_TX_P09 136
#define GPIO_PAD_136 GPIO135
#ifndef PIN_96_IS_GPIO
#define PIN_96_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_P09_IS_GPIO
#define PAD_MOD_TX_P09_IS_GPIO PIN_96_IS_GPIO
#endif

#define PIN_97 PAD_MOD_TX_N08
#define PAD_MOD_TX_N08 135
#define GPIO_PAD_135 GPIO134
#ifndef PIN_97_IS_GPIO
#define PIN_97_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_N08_IS_GPIO
#define PAD_MOD_TX_N08_IS_GPIO PIN_97_IS_GPIO
#endif

#define PIN_98 PAD_MOD_TX_P08
#define PAD_MOD_TX_P08 134
#define GPIO_PAD_134 GPIO133
#ifndef PIN_98_IS_GPIO
#define PIN_98_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_P08_IS_GPIO
#define PAD_MOD_TX_P08_IS_GPIO PIN_98_IS_GPIO
#endif

#define PIN_100 PAD_MOD_TX_N07
#define PAD_MOD_TX_N07 133
#define GPIO_PAD_133 GPIO132
#ifndef PIN_100_IS_GPIO
#define PIN_100_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_N07_IS_GPIO
#define PAD_MOD_TX_N07_IS_GPIO PIN_100_IS_GPIO
#endif

#define PIN_101 PAD_MOD_TX_P07
#define PAD_MOD_TX_P07 132
#define GPIO_PAD_132 GPIO131
#ifndef PIN_101_IS_GPIO
#define PIN_101_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_P07_IS_GPIO
#define PAD_MOD_TX_P07_IS_GPIO PIN_101_IS_GPIO
#endif

#define PIN_102 PAD_MOD_TX_N06
#define PAD_MOD_TX_N06 131
#define GPIO_PAD_131 GPIO130
#ifndef PIN_102_IS_GPIO
#define PIN_102_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_N06_IS_GPIO
#define PAD_MOD_TX_N06_IS_GPIO PIN_102_IS_GPIO
#endif

#define PIN_103 PAD_MOD_TX_P06
#define PAD_MOD_TX_P06 130
#define GPIO_PAD_130 GPIO129
#ifndef PIN_103_IS_GPIO
#define PIN_103_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_P06_IS_GPIO
#define PAD_MOD_TX_P06_IS_GPIO PIN_103_IS_GPIO
#endif

#define PIN_104 PAD_MOD_TX_N05
#define PAD_MOD_TX_N05 129
#define GPIO_PAD_129 GPIO128
#ifndef PIN_104_IS_GPIO
#define PIN_104_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_N05_IS_GPIO
#define PAD_MOD_TX_N05_IS_GPIO PIN_104_IS_GPIO
#endif

#define PIN_105 PAD_MOD_TX_P05
#define PAD_MOD_TX_P05 128
#define GPIO_PAD_128 GPIO127
#ifndef PIN_105_IS_GPIO
#define PIN_105_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_P05_IS_GPIO
#define PAD_MOD_TX_P05_IS_GPIO PIN_105_IS_GPIO
#endif

#define PIN_106 PAD_MOD_TX_N04
#define PAD_MOD_TX_N04 127
#define GPIO_PAD_127 GPIO126
#ifndef PIN_106_IS_GPIO
#define PIN_106_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_N04_IS_GPIO
#define PAD_MOD_TX_N04_IS_GPIO PIN_106_IS_GPIO
#endif

#define PIN_107 PAD_MOD_TX_P04
#define PAD_MOD_TX_P04 126
#define GPIO_PAD_126 GPIO125
#ifndef PIN_107_IS_GPIO
#define PIN_107_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_P04_IS_GPIO
#define PAD_MOD_TX_P04_IS_GPIO PIN_107_IS_GPIO
#endif

#define PIN_110 PAD_MOD_TX_N03
#define PAD_MOD_TX_N03 125
#define GPIO_PAD_125 GPIO124
#ifndef PIN_110_IS_GPIO
#define PIN_110_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_N03_IS_GPIO
#define PAD_MOD_TX_N03_IS_GPIO PIN_110_IS_GPIO
#endif

#define PIN_111 PAD_MOD_TX_P03
#define PAD_MOD_TX_P03 124
#define GPIO_PAD_124 GPIO123
#ifndef PIN_111_IS_GPIO
#define PIN_111_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_P03_IS_GPIO
#define PAD_MOD_TX_P03_IS_GPIO PIN_111_IS_GPIO
#endif

#define PIN_112 PAD_MOD_TX_N02
#define PAD_MOD_TX_N02 123
#define GPIO_PAD_123 GPIO122
#ifndef PIN_112_IS_GPIO
#define PIN_112_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_N02_IS_GPIO
#define PAD_MOD_TX_N02_IS_GPIO PIN_112_IS_GPIO
#endif

#define PIN_113 PAD_MOD_TX_P02
#define PAD_MOD_TX_P02 122
#define GPIO_PAD_122 GPIO121
#ifndef PIN_113_IS_GPIO
#define PIN_113_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_P02_IS_GPIO
#define PAD_MOD_TX_P02_IS_GPIO PIN_113_IS_GPIO
#endif

#define PIN_114 PAD_MOD_TX_N01
#define PAD_MOD_TX_N01 121
#define GPIO_PAD_121 GPIO120
#ifndef PIN_114_IS_GPIO
#define PIN_114_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_N01_IS_GPIO
#define PAD_MOD_TX_N01_IS_GPIO PIN_114_IS_GPIO
#endif

#define PIN_115 PAD_MOD_TX_P01
#define PAD_MOD_TX_P01 120
#define GPIO_PAD_120 GPIO119
#ifndef PIN_115_IS_GPIO
#define PIN_115_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_P01_IS_GPIO
#define PAD_MOD_TX_P01_IS_GPIO PIN_115_IS_GPIO
#endif

#define PIN_116 PAD_MOD_TX_N00
#define PAD_MOD_TX_N00 119
#define GPIO_PAD_119 GPIO118
#ifndef PIN_116_IS_GPIO
#define PIN_116_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_N00_IS_GPIO
#define PAD_MOD_TX_N00_IS_GPIO PIN_116_IS_GPIO
#endif

#define PIN_117 PAD_MOD_TX_P00
#define PAD_MOD_TX_P00 118
#define GPIO_PAD_118 GPIO117
#ifndef PIN_117_IS_GPIO
#define PIN_117_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_P00_IS_GPIO
#define PAD_MOD_TX_P00_IS_GPIO PIN_117_IS_GPIO
#endif

#define PAD_TS2_CLK 9999
#ifndef PAD_TS2_CLK_IS_GPIO
#define PAD_TS2_CLK_IS_GPIO 0
#endif

#define PAD_TS2_SYNC 9999
#ifndef PAD_TS2_SYNC_IS_GPIO
#define PAD_TS2_SYNC_IS_GPIO 0
#endif

#define PAD_TS2_VLD 9999
#ifndef PAD_TS2_VLD_IS_GPIO
#define PAD_TS2_VLD_IS_GPIO 0
#endif

#define PAD_TS2_D0 9999
#ifndef PAD_TS2_D0_IS_GPIO
#define PAD_TS2_D0_IS_GPIO 0
#endif

#define PIN_120 PAD_DDCR_DA
#define PAD_DDCR_DA 34
#define GPIO_PAD_34 GPIO33
#ifndef PIN_120_IS_GPIO
#define PIN_120_IS_GPIO 0
#endif
#ifndef PAD_DDCR_DA_IS_GPIO
#define PAD_DDCR_DA_IS_GPIO PIN_120_IS_GPIO
#endif

#define PIN_121 PAD_DDCR_CK
#define PAD_DDCR_CK 33
#define GPIO_PAD_33 GPIO32
#ifndef PIN_121_IS_GPIO
#define PIN_121_IS_GPIO 0
#endif
#ifndef PAD_DDCR_CK_IS_GPIO
#define PAD_DDCR_CK_IS_GPIO PIN_121_IS_GPIO
#endif

#define PIN_122 PAD_DDCA_DA
#define PAD_DDCA_DA 4
#define GPIO_PAD_4 GPIO03
#ifndef PIN_122_IS_GPIO
#define PIN_122_IS_GPIO 0
#endif
#ifndef PAD_DDCA_DA_IS_GPIO
#define PAD_DDCA_DA_IS_GPIO PIN_122_IS_GPIO
#endif

#define PIN_123 PAD_DDCA_CK
#define PAD_DDCA_CK 3
#define GPIO_PAD_3 GPIO02
#ifndef PIN_123_IS_GPIO
#define PIN_123_IS_GPIO 0
#endif
#ifndef PAD_DDCA_CK_IS_GPIO
#define PAD_DDCA_CK_IS_GPIO PIN_123_IS_GPIO
#endif

#define PAD_TGPIO0 9999
#ifndef PAD_TGPIO0_IS_GPIO
#define PAD_TGPIO0_IS_GPIO 0
#endif

#define PAD_TGPIO1 9999
#ifndef PAD_TGPIO1_IS_GPIO
#define PAD_TGPIO1_IS_GPIO 0
#endif

#define PAD_TGPIO2 9999
#ifndef PAD_TGPIO2_IS_GPIO
#define PAD_TGPIO2_IS_GPIO 0
#endif

#define PAD_TGPIO3 9999
#ifndef PAD_TGPIO3_IS_GPIO
#define PAD_TGPIO3_IS_GPIO 0
#endif

#define PAD_TCON0 9999
#ifndef PAD_TCON0_IS_GPIO
#define PAD_TCON0_IS_GPIO 0
#endif

#define PAD_TCON1 9999
#ifndef PAD_TCON1_IS_GPIO
#define PAD_TCON1_IS_GPIO 0
#endif

#define PAD_TCON2 9999
#ifndef PAD_TCON2_IS_GPIO
#define PAD_TCON2_IS_GPIO 0
#endif

#define PAD_TCON3 9999
#ifndef PAD_TCON3_IS_GPIO
#define PAD_TCON3_IS_GPIO 0
#endif

#define PAD_TCON4 9999
#ifndef PAD_TCON4_IS_GPIO
#define PAD_TCON4_IS_GPIO 0
#endif

#define PIN_124 PAD_PWM0
#define PAD_PWM0 79
#define GPIO_PAD_79 GPIO78
#ifndef PIN_124_IS_GPIO
#define PIN_124_IS_GPIO 0
#endif
#ifndef PAD_PWM0_IS_GPIO
#define PAD_PWM0_IS_GPIO PIN_124_IS_GPIO
#endif

#define PIN_125 PAD_PWM1
#define PAD_PWM1 80
#define GPIO_PAD_80 GPIO79
#ifndef PIN_125_IS_GPIO
#define PIN_125_IS_GPIO 0
#endif
#ifndef PAD_PWM1_IS_GPIO
#define PAD_PWM1_IS_GPIO PIN_125_IS_GPIO
#endif

#define PAD_PWM2 9999
#ifndef PAD_PWM2_IS_GPIO
#define PAD_PWM2_IS_GPIO 0
#endif

#define PAD_I2S_OUT_SD3 9999
#ifndef PAD_I2S_OUT_SD3_IS_GPIO
#define PAD_I2S_OUT_SD3_IS_GPIO 0
#endif

#define PAD_I2S_OUT_SD2 9999
#ifndef PAD_I2S_OUT_SD2_IS_GPIO
#define PAD_I2S_OUT_SD2_IS_GPIO 0
#endif

#define PAD_I2S_OUT_SD1 9999
#ifndef PAD_I2S_OUT_SD1_IS_GPIO
#define PAD_I2S_OUT_SD1_IS_GPIO 0
#endif

#define PIN_126 PAD_I2S_OUT_SD
#define PAD_I2S_OUT_SD 42
#define GPIO_PAD_42 GPIO41
#ifndef PIN_126_IS_GPIO
#define PIN_126_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_SD_IS_GPIO
#define PAD_I2S_OUT_SD_IS_GPIO PIN_126_IS_GPIO
#endif

#define PIN_127 PAD_I2S_OUT_BCK
#define PAD_I2S_OUT_BCK 41
#define GPIO_PAD_41 GPIO40
#ifndef PIN_127_IS_GPIO
#define PIN_127_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_BCK_IS_GPIO
#define PAD_I2S_OUT_BCK_IS_GPIO PIN_127_IS_GPIO
#endif

#define PIN_128 PAD_I2S_OUT_MCK
#define PAD_I2S_OUT_MCK 40
#define GPIO_PAD_40 GPIO39
#ifndef PIN_128_IS_GPIO
#define PIN_128_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_MCK_IS_GPIO
#define PAD_I2S_OUT_MCK_IS_GPIO PIN_128_IS_GPIO
#endif

#define PIN_129 PAD_I2S_OUT_WS
#define PAD_I2S_OUT_WS 39
#define GPIO_PAD_39 GPIO38
#ifndef PIN_129_IS_GPIO
#define PIN_129_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_WS_IS_GPIO
#define PAD_I2S_OUT_WS_IS_GPIO PIN_129_IS_GPIO
#endif

#define PIN_131 PAD_SPDIF_OUT
#define PAD_SPDIF_OUT 82
#define GPIO_PAD_82 GPIO81
#ifndef PIN_131_IS_GPIO
#define PIN_131_IS_GPIO 0
#endif
#ifndef PAD_SPDIF_OUT_IS_GPIO
#define PAD_SPDIF_OUT_IS_GPIO PIN_131_IS_GPIO
#endif

#define PIN_138 PAD_SAR0
#define PAD_SAR0 174
#define GPIO_PAD_174 GPIO173
#ifndef PIN_138_IS_GPIO
#define PIN_138_IS_GPIO 0
#endif
#ifndef PAD_SAR0_IS_GPIO
#define PAD_SAR0_IS_GPIO PIN_138_IS_GPIO
#endif

#define PIN_139 PAD_SAR1
#define PAD_SAR1 175
#define GPIO_PAD_175 GPIO174
#ifndef PIN_139_IS_GPIO
#define PIN_139_IS_GPIO 0
#endif
#ifndef PAD_SAR1_IS_GPIO
#define PAD_SAR1_IS_GPIO PIN_139_IS_GPIO
#endif

#define PAD_SAR2 9999
#ifndef PAD_SAR2_IS_GPIO
#define PAD_SAR2_IS_GPIO 0
#endif

#define PIN_140 PAD_GPIO0
#define PAD_GPIO0 25
#define GPIO_PAD_25 GPIO24
#ifndef PIN_140_IS_GPIO
#define PIN_140_IS_GPIO 0
#endif
#ifndef PAD_GPIO0_IS_GPIO
#define PAD_GPIO0_IS_GPIO PIN_140_IS_GPIO
#endif

#define PIN_141 PAD_GPIO3
#define PAD_GPIO3 28
#define GPIO_PAD_28 GPIO27
#ifndef PIN_141_IS_GPIO
#define PIN_141_IS_GPIO 0
#endif
#ifndef PAD_GPIO3_IS_GPIO
#define PAD_GPIO3_IS_GPIO PIN_141_IS_GPIO
#endif

#define PIN_142 PAD_GPIO4
#define PAD_GPIO4 29
#define GPIO_PAD_29 GPIO28
#ifndef PIN_142_IS_GPIO
#define PIN_142_IS_GPIO 0
#endif
#ifndef PAD_GPIO4_IS_GPIO
#define PAD_GPIO4_IS_GPIO PIN_142_IS_GPIO
#endif

#define PAD_GPIO5 9999
#ifndef PAD_GPIO5_IS_GPIO
#define PAD_GPIO5_IS_GPIO 0
#endif

#define PAD_GPIO6 9999
#ifndef PAD_GPIO6_IS_GPIO
#define PAD_GPIO6_IS_GPIO 0
#endif

#define PAD_LD_SPI_CS 9999
#ifndef PAD_LD_SPI_CS_IS_GPIO
#define PAD_LD_SPI_CS_IS_GPIO 0
#endif

#define PAD_LD_SPI_CK 9999
#ifndef PAD_LD_SPI_CK_IS_GPIO
#define PAD_LD_SPI_CK_IS_GPIO 0
#endif

#define PAD_LD_SPI_MOSI 9999
#ifndef PAD_LD_SPI_MOSI_IS_GPIO
#define PAD_LD_SPI_MOSI_IS_GPIO 0
#endif

#define PAD_LD_SPI_MISO 9999
#ifndef PAD_LD_SPI_MISO_IS_GPIO
#define PAD_LD_SPI_MISO_IS_GPIO 0
#endif

#define PAD_PWM_PM 9999
#ifndef PAD_PWM_PM_IS_GPIO
#define PAD_PWM_PM_IS_GPIO 0
#endif

#define PIN_145 PAD_IRIN
#define PAD_IRIN 5
#define GPIO_PAD_5 GPIO04
#ifndef PIN_145_IS_GPIO
#define PIN_145_IS_GPIO 0
#endif
#ifndef PAD_IRIN_IS_GPIO
#define PAD_IRIN_IS_GPIO PIN_145_IS_GPIO
#endif

#define PAD_VID0 9999
#ifndef PAD_VID0_IS_GPIO
#define PAD_VID0_IS_GPIO 0
#endif

#define PIN_146 PAD_HDMIRX_ARCTX
#define PAD_HDMIRX_ARCTX 24
#define GPIO_PAD_24 GPIO23
#ifndef PIN_146_IS_GPIO
#define PIN_146_IS_GPIO 0
#endif
#ifndef PAD_HDMIRX_ARCTX_IS_GPIO
#define PAD_HDMIRX_ARCTX_IS_GPIO PIN_146_IS_GPIO
#endif

#define PAD_VID1 9999
#ifndef PAD_VID1_IS_GPIO
#define PAD_VID1_IS_GPIO 0
#endif

#define PIN_148 PAD_CEC0
#define PAD_CEC0 7
#define GPIO_PAD_7 GPIO06
#ifndef PIN_148_IS_GPIO
#define PIN_148_IS_GPIO 0
#endif
#ifndef PAD_CEC0_IS_GPIO
#define PAD_CEC0_IS_GPIO PIN_148_IS_GPIO
#endif

#define PIN_149 PAD_DDCDC_DA
#define PAD_DDCDC_DA 13
#define GPIO_PAD_13 GPIO12
#ifndef PIN_149_IS_GPIO
#define PIN_149_IS_GPIO 0
#endif
#ifndef PAD_DDCDC_DA_IS_GPIO
#define PAD_DDCDC_DA_IS_GPIO PIN_149_IS_GPIO
#endif

#define PIN_150 PAD_DDCDC_CK
#define PAD_DDCDC_CK 12
#define GPIO_PAD_12 GPIO11
#ifndef PIN_150_IS_GPIO
#define PIN_150_IS_GPIO 0
#endif
#ifndef PAD_DDCDC_CK_IS_GPIO
#define PAD_DDCDC_CK_IS_GPIO PIN_150_IS_GPIO
#endif

#define PIN_151 PAD_DDCDB_DA
#define PAD_DDCDB_DA 11
#define GPIO_PAD_11 GPIO10
#ifndef PIN_151_IS_GPIO
#define PIN_151_IS_GPIO 0
#endif
#ifndef PAD_DDCDB_DA_IS_GPIO
#define PAD_DDCDB_DA_IS_GPIO PIN_151_IS_GPIO
#endif

#define PIN_152 PAD_DDCDB_CK
#define PAD_DDCDB_CK 10
#define GPIO_PAD_10 GPIO09
#ifndef PIN_152_IS_GPIO
#define PIN_152_IS_GPIO 0
#endif
#ifndef PAD_DDCDB_CK_IS_GPIO
#define PAD_DDCDB_CK_IS_GPIO PIN_152_IS_GPIO
#endif

#define PIN_153 PAD_DDCDA_DA
#define PAD_DDCDA_DA 9
#define GPIO_PAD_9 GPIO08
#ifndef PIN_153_IS_GPIO
#define PIN_153_IS_GPIO 0
#endif
#ifndef PAD_DDCDA_DA_IS_GPIO
#define PAD_DDCDA_DA_IS_GPIO PIN_153_IS_GPIO
#endif

#define PIN_154 PAD_DDCDA_CK
#define PAD_DDCDA_CK 8
#define GPIO_PAD_8 GPIO07
#ifndef PIN_154_IS_GPIO
#define PIN_154_IS_GPIO 0
#endif
#ifndef PAD_DDCDA_CK_IS_GPIO
#define PAD_DDCDA_CK_IS_GPIO PIN_154_IS_GPIO
#endif

#define PIN_155 PAD_HOTPLUGC_HDMI20_5V
#define PAD_HOTPLUGC_HDMI20_5V 16
#define GPIO_PAD_16 GPIO15
#ifndef PIN_155_IS_GPIO
#define PIN_155_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGC_HDMI20_5V_IS_GPIO
#define PAD_HOTPLUGC_HDMI20_5V_IS_GPIO PIN_155_IS_GPIO
#endif

#define PIN_156 PAD_HOTPLUGB_HDMI20_5V
#define PAD_HOTPLUGB_HDMI20_5V 15
#define GPIO_PAD_15 GPIO14
#ifndef PIN_156_IS_GPIO
#define PIN_156_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGB_HDMI20_5V_IS_GPIO
#define PAD_HOTPLUGB_HDMI20_5V_IS_GPIO PIN_156_IS_GPIO
#endif

#define PIN_1 PAD_HOTPLUGA_HDMI20_5V
#define PAD_HOTPLUGA_HDMI20_5V 14
#define GPIO_PAD_14 GPIO13
#ifndef PIN_1_IS_GPIO
#define PIN_1_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGA_HDMI20_5V_IS_GPIO
#define PAD_HOTPLUGA_HDMI20_5V_IS_GPIO PIN_1_IS_GPIO
#endif


// PADS group name to index
#define PADS_PCMCONFIG_MODE1        1223
#define PADS_PCMCONFIG_MODE2        1224
#define PADS_PCMCONFIG1_MODE1       1225
#define PADS_PCMCONFIG1_MODE2       1226
#define PADS_PCMCONFIG1_MODE3       1227
#define PADS_PCM2CONFIG_MODE1       1228
#define PADS_PCM2CONFIG_MODE2       1229
#define PADS_PCM2CONFIG_MODE3       1230
#define PADS_PCM2CONFIG1_MODE1      1231
#define PADS_PCM2CONFIG1_MODE2      1232
#define PADS_ET_MODE1               1233
#define PADS_ET_MODE2               1234
#define PADS_DDCR                   1235
#define PADS_DDCR2                  1236
#define PADS_PCM                    1237

// chip capbilities
#define CHIP_HAS_BT656_IN           0
#define CHIP_HAS_TS0                1
#define CHIP_HAS_TS1                0
#define CHIP_HAS_LVDS_10BIT_X2      1
#define CHIP_HAS_LVDS_8BIT_X2       1
#define CHIP_HAS_LVDS_8BIT_X1       1
#define CHIP_HAS_CIMAX              0
#define CHIP_HAS_USB_P0             1
#define CHIP_HAS_USB_P1             1
#define CHIP_HAS_USBVBUS0           0
#define CHIP_HAS_USBVBUS1           0
#define CHIP_HAS_UART1_MODE1        1
#define CHIP_HAS_UART1_MODE2        1
#define CHIP_HAS_UART1_MODE3        1
#define CHIP_HAS_PCMCIA1            0
#define CHIP_HAS_PCMCIA2            0
#define CHIP_HAS_PCMCIA             0
#define CHIP_HAS_UART2_MODE1        1
#define CHIP_HAS_UART2_MODE2        1
#define CHIP_HAS_UART2_MODE3        1
#define CHIP_HAS_RGB_A              1
#define CHIP_HAS_RGB_B              1
#define CHIP_HAS_RGB_C              1
#define CHIP_HAS_HDMI_A             1
#define CHIP_HAS_HDMI_B             1
#define CHIP_HAS_HDMI_C             1
#define CHIP_HAS_SPI_CZ1            1
#define CHIP_HAS_SPI_CZ2            0
#define CHIP_HAS_SPI_CZ3            0
#define CHIP_HAS_DDCR               1
#define CHIP_HAS_DDCR2              1
#define CHIP_HAS_TCON               1
#define CHIP_HAS_ET_MODE0_MII       1
#define CHIP_HAS_ET_MODE0_RMII      1
#define CHIP_HAS_ET_MODE1_MII       1
#define CHIP_HAS_ET_MODE1_RMII      1
#define CHIP_HAS_ET_MODE2_MII       1
#define CHIP_HAS_ET_MODE2_RMII      1
#define CHIP_HAS_I2S_IN             0
#define CHIP_HAS_I2S_OUT            0
#define CHIP_HAS_SPDIF_IN           0
#define CHIP_HAS_SPDIF_OUT          0
#define CHIP_HAS_DDR_A_CMD          1
#define CHIP_HAS_DDR_A_DATA         1
#define CHIP_HAS_DDR_B_CMD          1
#define CHIP_HAS_DDR_B_DATA         1
#define CHIP_USE_PCM_CDN_IN_PCM2    0
#define CHIP_USE_I2S_IN_IN_PCM      0
#define CHIP_USE_I2S_OUT_IN_PCM     0
#define CHIP_USE_SPDIF_IN_IN_PCM    0
#define CHIP_USE_SPDIF_OUT_IN_PCM   0
#define CHIP_USE_IIC_IN_DDCR2       0
#define CHIP_USE_PWM2_IN_GPIO14     0
#define CHIP_USE_PWM3_IN_GPIO15     0

// chip additional information
#define CHIP_FAMILY_TYPE            CHIP_FAMILY_M3822

#endif /* _MSD92QEBW2_H_*/
