/* SPDX-License-Identifier: GPL-2.0-only OR BSD-3-Clause */
/******************************************************************************
 *
 * This file is provided under a dual license.  When you use or
 * distribute this software, you may choose to be licensed under
 * version 2 of the GNU General Public License ("GPLv2 License")
 * or BSD License.
 *
 * GPLv2 License
 *
 * Copyright(C) 2019 MediaTek Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of version 2 of the GNU General Public License as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See http://www.gnu.org/licenses/gpl-2.0.html for more details.
 *
 * BSD LICENSE
 *
 * Copyright(C) 2019 MediaTek Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *****************************************************************************/

// This file is generated by script file, please do not edit it directly
#ifndef _MSD92QSTW4_H_
#define _MSD92QSTW4_H_

#define PAD_NC   9999
#define PAD_GND  0

#define BALL_A6 PAD_C_RX0N
#define PAD_C_RX0N 166
#define GPIO_PAD_166 GPIO165
#ifndef BALL_A6_IS_GPIO
#define BALL_A6_IS_GPIO 0
#endif
#ifndef PAD_C_RX0N_IS_GPIO
#define PAD_C_RX0N_IS_GPIO BALL_A6_IS_GPIO
#endif

#define BALL_B7 PAD_C_RXCN
#define PAD_C_RXCN 172
#define GPIO_PAD_172 GPIO171
#ifndef BALL_B7_IS_GPIO
#define BALL_B7_IS_GPIO 0
#endif
#ifndef PAD_C_RXCN_IS_GPIO
#define PAD_C_RXCN_IS_GPIO BALL_B7_IS_GPIO
#endif

#define BALL_B6 PAD_C_RX0P
#define PAD_C_RX0P 167
#define GPIO_PAD_167 GPIO166
#ifndef BALL_B6_IS_GPIO
#define BALL_B6_IS_GPIO 0
#endif
#ifndef PAD_C_RX0P_IS_GPIO
#define PAD_C_RX0P_IS_GPIO BALL_B6_IS_GPIO
#endif

#define BALL_C6 PAD_C_RXCP
#define PAD_C_RXCP 173
#define GPIO_PAD_173 GPIO172
#ifndef BALL_C6_IS_GPIO
#define BALL_C6_IS_GPIO 0
#endif
#ifndef PAD_C_RXCP_IS_GPIO
#define PAD_C_RXCP_IS_GPIO BALL_C6_IS_GPIO
#endif

#define BALL_C4 PAD_C_RX2N
#define PAD_C_RX2N 170
#define GPIO_PAD_170 GPIO169
#ifndef BALL_C4_IS_GPIO
#define BALL_C4_IS_GPIO 0
#endif
#ifndef PAD_C_RX2N_IS_GPIO
#define PAD_C_RX2N_IS_GPIO BALL_C4_IS_GPIO
#endif

#define BALL_A5 PAD_C_RX1N
#define PAD_C_RX1N 168
#define GPIO_PAD_168 GPIO167
#ifndef BALL_A5_IS_GPIO
#define BALL_A5_IS_GPIO 0
#endif
#ifndef PAD_C_RX1N_IS_GPIO
#define PAD_C_RX1N_IS_GPIO BALL_A5_IS_GPIO
#endif

#define BALL_B4 PAD_C_RX2P
#define PAD_C_RX2P 171
#define GPIO_PAD_171 GPIO170
#ifndef BALL_B4_IS_GPIO
#define BALL_B4_IS_GPIO 0
#endif
#ifndef PAD_C_RX2P_IS_GPIO
#define PAD_C_RX2P_IS_GPIO BALL_B4_IS_GPIO
#endif

#define BALL_B5 PAD_C_RX1P
#define PAD_C_RX1P 169
#define GPIO_PAD_169 GPIO168
#ifndef BALL_B5_IS_GPIO
#define BALL_B5_IS_GPIO 0
#endif
#ifndef PAD_C_RX1P_IS_GPIO
#define PAD_C_RX1P_IS_GPIO BALL_B5_IS_GPIO
#endif

#define BALL_A2 PAD_B_RX0N
#define PAD_B_RX0N 158
#define GPIO_PAD_158 GPIO157
#ifndef BALL_A2_IS_GPIO
#define BALL_A2_IS_GPIO 0
#endif
#ifndef PAD_B_RX0N_IS_GPIO
#define PAD_B_RX0N_IS_GPIO BALL_A2_IS_GPIO
#endif

#define BALL_B3 PAD_B_RXCN
#define PAD_B_RXCN 164
#define GPIO_PAD_164 GPIO163
#ifndef BALL_B3_IS_GPIO
#define BALL_B3_IS_GPIO 0
#endif
#ifndef PAD_B_RXCN_IS_GPIO
#define PAD_B_RXCN_IS_GPIO BALL_B3_IS_GPIO
#endif

#define BALL_B2 PAD_B_RX0P
#define PAD_B_RX0P 159
#define GPIO_PAD_159 GPIO158
#ifndef BALL_B2_IS_GPIO
#define BALL_B2_IS_GPIO 0
#endif
#ifndef PAD_B_RX0P_IS_GPIO
#define PAD_B_RX0P_IS_GPIO BALL_B2_IS_GPIO
#endif

#define BALL_A3 PAD_B_RXCP
#define PAD_B_RXCP 165
#define GPIO_PAD_165 GPIO164
#ifndef BALL_A3_IS_GPIO
#define BALL_A3_IS_GPIO 0
#endif
#ifndef PAD_B_RXCP_IS_GPIO
#define PAD_B_RXCP_IS_GPIO BALL_A3_IS_GPIO
#endif

#define BALL_C2 PAD_B_RX2N
#define PAD_B_RX2N 162
#define GPIO_PAD_162 GPIO161
#ifndef BALL_C2_IS_GPIO
#define BALL_C2_IS_GPIO 0
#endif
#ifndef PAD_B_RX2N_IS_GPIO
#define PAD_B_RX2N_IS_GPIO BALL_C2_IS_GPIO
#endif

#define BALL_B1 PAD_B_RX1N
#define PAD_B_RX1N 160
#define GPIO_PAD_160 GPIO159
#ifndef BALL_B1_IS_GPIO
#define BALL_B1_IS_GPIO 0
#endif
#ifndef PAD_B_RX1N_IS_GPIO
#define PAD_B_RX1N_IS_GPIO BALL_B1_IS_GPIO
#endif

#define BALL_D3 PAD_B_RX2P
#define PAD_B_RX2P 163
#define GPIO_PAD_163 GPIO162
#ifndef BALL_D3_IS_GPIO
#define BALL_D3_IS_GPIO 0
#endif
#ifndef PAD_B_RX2P_IS_GPIO
#define PAD_B_RX2P_IS_GPIO BALL_D3_IS_GPIO
#endif

#define BALL_C1 PAD_B_RX1P
#define PAD_B_RX1P 161
#define GPIO_PAD_161 GPIO160
#ifndef BALL_C1_IS_GPIO
#define BALL_C1_IS_GPIO 0
#endif
#ifndef PAD_B_RX1P_IS_GPIO
#define PAD_B_RX1P_IS_GPIO BALL_C1_IS_GPIO
#endif

#define BALL_E1 PAD_RX0N
#define PAD_RX0N 150
#define GPIO_PAD_150 GPIO149
#ifndef BALL_E1_IS_GPIO
#define BALL_E1_IS_GPIO 0
#endif
#ifndef PAD_RX0N_IS_GPIO
#define PAD_RX0N_IS_GPIO BALL_E1_IS_GPIO
#endif

#define BALL_E3 PAD_RXCN
#define PAD_RXCN 156
#define GPIO_PAD_156 GPIO155
#ifndef BALL_E3_IS_GPIO
#define BALL_E3_IS_GPIO 0
#endif
#ifndef PAD_RXCN_IS_GPIO
#define PAD_RXCN_IS_GPIO BALL_E3_IS_GPIO
#endif

#define BALL_F1 PAD_RX0P
#define PAD_RX0P 151
#define GPIO_PAD_151 GPIO150
#ifndef BALL_F1_IS_GPIO
#define BALL_F1_IS_GPIO 0
#endif
#ifndef PAD_RX0P_IS_GPIO
#define PAD_RX0P_IS_GPIO BALL_F1_IS_GPIO
#endif

#define BALL_E2 PAD_RXCP
#define PAD_RXCP 157
#define GPIO_PAD_157 GPIO156
#ifndef BALL_E2_IS_GPIO
#define BALL_E2_IS_GPIO 0
#endif
#ifndef PAD_RXCP_IS_GPIO
#define PAD_RXCP_IS_GPIO BALL_E2_IS_GPIO
#endif

#define BALL_G2 PAD_RX2N
#define PAD_RX2N 154
#define GPIO_PAD_154 GPIO153
#ifndef BALL_G2_IS_GPIO
#define BALL_G2_IS_GPIO 0
#endif
#ifndef PAD_RX2N_IS_GPIO
#define PAD_RX2N_IS_GPIO BALL_G2_IS_GPIO
#endif

#define BALL_F2 PAD_RX1N
#define PAD_RX1N 152
#define GPIO_PAD_152 GPIO151
#ifndef BALL_F2_IS_GPIO
#define BALL_F2_IS_GPIO 0
#endif
#ifndef PAD_RX1N_IS_GPIO
#define PAD_RX1N_IS_GPIO BALL_F2_IS_GPIO
#endif

#define BALL_G3 PAD_RX2P
#define PAD_RX2P 155
#define GPIO_PAD_155 GPIO154
#ifndef BALL_G3_IS_GPIO
#define BALL_G3_IS_GPIO 0
#endif
#ifndef PAD_RX2P_IS_GPIO
#define PAD_RX2P_IS_GPIO BALL_G3_IS_GPIO
#endif

#define BALL_F3 PAD_RX1P
#define PAD_RX1P 153
#define GPIO_PAD_153 GPIO152
#ifndef BALL_F3_IS_GPIO
#define BALL_F3_IS_GPIO 0
#endif
#ifndef PAD_RX1P_IS_GPIO
#define PAD_RX1P_IS_GPIO BALL_F3_IS_GPIO
#endif

#define BALL_L6 PADA_HSYNC0
#define PADA_HSYNC0 189
#define GPIO_PAD_189 GPIO188
#ifndef BALL_L6_IS_GPIO
#define BALL_L6_IS_GPIO 0
#endif
#ifndef PADA_HSYNC0_IS_GPIO
#define PADA_HSYNC0_IS_GPIO BALL_L6_IS_GPIO
#endif

#define BALL_J3 PADA_BIN0P
#define PADA_BIN0P 186
#define GPIO_PAD_186 GPIO185
#ifndef BALL_J3_IS_GPIO
#define BALL_J3_IS_GPIO 0
#endif
#ifndef PADA_BIN0P_IS_GPIO
#define PADA_BIN0P_IS_GPIO BALL_J3_IS_GPIO
#endif

#define BALL_J1 PADA_GIN0P
#define PADA_GIN0P 180
#define GPIO_PAD_180 GPIO179
#ifndef BALL_J1_IS_GPIO
#define BALL_J1_IS_GPIO 0
#endif
#ifndef PADA_GIN0P_IS_GPIO
#define PADA_GIN0P_IS_GPIO BALL_J1_IS_GPIO
#endif

#define BALL_J2 PADA_GIN0M
#define PADA_GIN0M 183
#define GPIO_PAD_183 GPIO182
#ifndef BALL_J2_IS_GPIO
#define BALL_J2_IS_GPIO 0
#endif
#ifndef PADA_GIN0M_IS_GPIO
#define PADA_GIN0M_IS_GPIO BALL_J2_IS_GPIO
#endif

#define BALL_K3 PADA_RIN0P
#define PADA_RIN0P 177
#define GPIO_PAD_177 GPIO176
#ifndef BALL_K3_IS_GPIO
#define BALL_K3_IS_GPIO 0
#endif
#ifndef PADA_RIN0P_IS_GPIO
#define PADA_RIN0P_IS_GPIO BALL_K3_IS_GPIO
#endif

#define BALL_M6 PADA_VSYNC0
#define PADA_VSYNC0 192
#define GPIO_PAD_192 GPIO191
#ifndef BALL_M6_IS_GPIO
#define BALL_M6_IS_GPIO 0
#endif
#ifndef PADA_VSYNC0_IS_GPIO
#define PADA_VSYNC0_IS_GPIO BALL_M6_IS_GPIO
#endif

#define BALL_L5 PADA_HSYNC1
#define PADA_HSYNC1 190
#define GPIO_PAD_190 GPIO189
#ifndef BALL_L5_IS_GPIO
#define BALL_L5_IS_GPIO 0
#endif
#ifndef PADA_HSYNC1_IS_GPIO
#define PADA_HSYNC1_IS_GPIO BALL_L5_IS_GPIO
#endif

#define BALL_K2 PADA_BIN1P
#define PADA_BIN1P 187
#define GPIO_PAD_187 GPIO186
#ifndef BALL_K2_IS_GPIO
#define BALL_K2_IS_GPIO 0
#endif
#ifndef PADA_BIN1P_IS_GPIO
#define PADA_BIN1P_IS_GPIO BALL_K2_IS_GPIO
#endif

#define BALL_L3 PADA_GIN1P
#define PADA_GIN1P 181
#define GPIO_PAD_181 GPIO180
#ifndef BALL_L3_IS_GPIO
#define BALL_L3_IS_GPIO 0
#endif
#ifndef PADA_GIN1P_IS_GPIO
#define PADA_GIN1P_IS_GPIO BALL_L3_IS_GPIO
#endif

#define BALL_L2 PADA_GIN1M
#define PADA_GIN1M 184
#define GPIO_PAD_184 GPIO183
#ifndef BALL_L2_IS_GPIO
#define BALL_L2_IS_GPIO 0
#endif
#ifndef PADA_GIN1M_IS_GPIO
#define PADA_GIN1M_IS_GPIO BALL_L2_IS_GPIO
#endif

#define BALL_L1 PADA_RIN1P
#define PADA_RIN1P 178
#define GPIO_PAD_178 GPIO177
#ifndef BALL_L1_IS_GPIO
#define BALL_L1_IS_GPIO 0
#endif
#ifndef PADA_RIN1P_IS_GPIO
#define PADA_RIN1P_IS_GPIO BALL_L1_IS_GPIO
#endif

#define BALL_M5 PADA_VSYNC1
#define PADA_VSYNC1 193
#define GPIO_PAD_193 GPIO192
#ifndef BALL_M5_IS_GPIO
#define BALL_M5_IS_GPIO 0
#endif
#ifndef PADA_VSYNC1_IS_GPIO
#define PADA_VSYNC1_IS_GPIO BALL_M5_IS_GPIO
#endif

#define PADA_HSYNC2 9999
#ifndef PADA_HSYNC2_IS_GPIO
#define PADA_HSYNC2_IS_GPIO 0
#endif

#define PADA_BIN2P 9999
#ifndef PADA_BIN2P_IS_GPIO
#define PADA_BIN2P_IS_GPIO 0
#endif

#define PADA_GIN2P 9999
#ifndef PADA_GIN2P_IS_GPIO
#define PADA_GIN2P_IS_GPIO 0
#endif

#define PADA_GIN2M 9999
#ifndef PADA_GIN2M_IS_GPIO
#define PADA_GIN2M_IS_GPIO 0
#endif

#define PADA_RIN2P 9999
#ifndef PADA_RIN2P_IS_GPIO
#define PADA_RIN2P_IS_GPIO 0
#endif

#define PADA_VSYNC2 9999
#ifndef PADA_VSYNC2_IS_GPIO
#define PADA_VSYNC2_IS_GPIO 0
#endif

#define BALL_P2 PAD_LINEIN_L0
#define PAD_LINEIN_L0 146
#define GPIO_PAD_146 GPIO145
#ifndef BALL_P2_IS_GPIO
#define BALL_P2_IS_GPIO 0
#endif
#ifndef PAD_LINEIN_L0_IS_GPIO
#define PAD_LINEIN_L0_IS_GPIO BALL_P2_IS_GPIO
#endif

#define BALL_P1 PAD_LINEIN_R0
#define PAD_LINEIN_R0 147
#define GPIO_PAD_147 GPIO146
#ifndef BALL_P1_IS_GPIO
#define BALL_P1_IS_GPIO 0
#endif
#ifndef PAD_LINEIN_R0_IS_GPIO
#define PAD_LINEIN_R0_IS_GPIO BALL_P1_IS_GPIO
#endif

#define BALL_R2 PAD_LINEIN_L1
#define PAD_LINEIN_L1 148
#define GPIO_PAD_148 GPIO147
#ifndef BALL_R2_IS_GPIO
#define BALL_R2_IS_GPIO 0
#endif
#ifndef PAD_LINEIN_L1_IS_GPIO
#define PAD_LINEIN_L1_IS_GPIO BALL_R2_IS_GPIO
#endif

#define BALL_T3 PAD_LINEIN_R1
#define PAD_LINEIN_R1 149
#define GPIO_PAD_149 GPIO148
#ifndef BALL_T3_IS_GPIO
#define BALL_T3_IS_GPIO 0
#endif
#ifndef PAD_LINEIN_R1_IS_GPIO
#define PAD_LINEIN_R1_IS_GPIO BALL_T3_IS_GPIO
#endif

#define BALL_V5 PAD_GPIO2
#define PAD_GPIO2 27
#define GPIO_PAD_27 GPIO26
#ifndef BALL_V5_IS_GPIO
#define BALL_V5_IS_GPIO 0
#endif
#ifndef PAD_GPIO2_IS_GPIO
#define PAD_GPIO2_IS_GPIO BALL_V5_IS_GPIO
#endif

#define BALL_U4 PAD_GPIO1
#define PAD_GPIO1 26
#define GPIO_PAD_26 GPIO25
#ifndef BALL_U4_IS_GPIO
#define BALL_U4_IS_GPIO 0
#endif
#ifndef PAD_GPIO1_IS_GPIO
#define PAD_GPIO1_IS_GPIO BALL_U4_IS_GPIO
#endif

#define BALL_P16 PAD_PCM_RESET
#define PAD_PCM_RESET 76
#define GPIO_PAD_76 GPIO75
#ifndef BALL_P16_IS_GPIO
#define BALL_P16_IS_GPIO 0
#endif
#ifndef PAD_PCM_RESET_IS_GPIO
#define PAD_PCM_RESET_IS_GPIO BALL_P16_IS_GPIO
#endif

#define BALL_N16 PAD_PCM_IRQA_N
#define PAD_PCM_IRQA_N 73
#define GPIO_PAD_73 GPIO72
#ifndef BALL_N16_IS_GPIO
#define BALL_N16_IS_GPIO 0
#endif
#ifndef PAD_PCM_IRQA_N_IS_GPIO
#define PAD_PCM_IRQA_N_IS_GPIO BALL_N16_IS_GPIO
#endif

#define BALL_R16 PAD_PCM_CD_N
#define PAD_PCM_CD_N 69
#define GPIO_PAD_69 GPIO68
#ifndef BALL_R16_IS_GPIO
#define BALL_R16_IS_GPIO 0
#endif
#ifndef PAD_PCM_CD_N_IS_GPIO
#define PAD_PCM_CD_N_IS_GPIO BALL_R16_IS_GPIO
#endif

#define BALL_M16 PAD_PCM_REG_N
#define PAD_PCM_REG_N 75
#define GPIO_PAD_75 GPIO74
#ifndef BALL_M16_IS_GPIO
#define BALL_M16_IS_GPIO 0
#endif
#ifndef PAD_PCM_REG_N_IS_GPIO
#define PAD_PCM_REG_N_IS_GPIO BALL_M16_IS_GPIO
#endif

#define BALL_T15 PAD_PCM_CE_N
#define PAD_PCM_CE_N 70
#define GPIO_PAD_70 GPIO69
#ifndef BALL_T15_IS_GPIO
#define BALL_T15_IS_GPIO 0
#endif
#ifndef PAD_PCM_CE_N_IS_GPIO
#define PAD_PCM_CE_N_IS_GPIO BALL_T15_IS_GPIO
#endif

#define BALL_K16 PAD_PCM_OE_N
#define PAD_PCM_OE_N 74
#define GPIO_PAD_74 GPIO73
#ifndef BALL_K16_IS_GPIO
#define BALL_K16_IS_GPIO 0
#endif
#ifndef PAD_PCM_OE_N_IS_GPIO
#define PAD_PCM_OE_N_IS_GPIO BALL_K16_IS_GPIO
#endif

#define BALL_T16 PAD_PCM_WE_N
#define PAD_PCM_WE_N 78
#define GPIO_PAD_78 GPIO77
#ifndef BALL_T16_IS_GPIO
#define BALL_T16_IS_GPIO 0
#endif
#ifndef PAD_PCM_WE_N_IS_GPIO
#define PAD_PCM_WE_N_IS_GPIO BALL_T16_IS_GPIO
#endif

#define BALL_P17 PAD_PCM_WAIT_N
#define PAD_PCM_WAIT_N 77
#define GPIO_PAD_77 GPIO76
#ifndef BALL_P17_IS_GPIO
#define BALL_P17_IS_GPIO 0
#endif
#ifndef PAD_PCM_WAIT_N_IS_GPIO
#define PAD_PCM_WAIT_N_IS_GPIO BALL_P17_IS_GPIO
#endif

#define BALL_R17 PAD_PCM_IORD_N
#define PAD_PCM_IORD_N 71
#define GPIO_PAD_71 GPIO70
#ifndef BALL_R17_IS_GPIO
#define BALL_R17_IS_GPIO 0
#endif
#ifndef PAD_PCM_IORD_N_IS_GPIO
#define PAD_PCM_IORD_N_IS_GPIO BALL_R17_IS_GPIO
#endif

#define BALL_L16 PAD_PCM_IOWR_N
#define PAD_PCM_IOWR_N 72
#define GPIO_PAD_72 GPIO71
#ifndef BALL_L16_IS_GPIO
#define BALL_L16_IS_GPIO 0
#endif
#ifndef PAD_PCM_IOWR_N_IS_GPIO
#define PAD_PCM_IOWR_N_IS_GPIO BALL_L16_IS_GPIO
#endif

#define BALL_W11 PAD_NAND_CEZ
#define PAD_NAND_CEZ 20
#define GPIO_PAD_20 GPIO19
#ifndef BALL_W11_IS_GPIO
#define BALL_W11_IS_GPIO 0
#endif
#ifndef PAD_NAND_CEZ_IS_GPIO
#define PAD_NAND_CEZ_IS_GPIO BALL_W11_IS_GPIO
#endif

#define BALL_AA10 PAD_NAND_CLE
#define PAD_NAND_CLE 18
#define GPIO_PAD_18 GPIO17
#ifndef BALL_AA10_IS_GPIO
#define BALL_AA10_IS_GPIO 0
#endif
#ifndef PAD_NAND_CLE_IS_GPIO
#define PAD_NAND_CLE_IS_GPIO BALL_AA10_IS_GPIO
#endif

#define BALL_AA11 PAD_NAND_REZ
#define PAD_NAND_REZ 17
#define GPIO_PAD_17 GPIO16
#ifndef BALL_AA11_IS_GPIO
#define BALL_AA11_IS_GPIO 0
#endif
#ifndef PAD_NAND_REZ_IS_GPIO
#define PAD_NAND_REZ_IS_GPIO BALL_AA11_IS_GPIO
#endif

#define BALL_W10 PAD_NAND_WEZ
#define PAD_NAND_WEZ 22
#define GPIO_PAD_22 GPIO21
#ifndef BALL_W10_IS_GPIO
#define BALL_W10_IS_GPIO 0
#endif
#ifndef PAD_NAND_WEZ_IS_GPIO
#define PAD_NAND_WEZ_IS_GPIO BALL_W10_IS_GPIO
#endif

#define BALL_Y12 PAD_NAND_WPZ
#define PAD_NAND_WPZ 21
#define GPIO_PAD_21 GPIO20
#ifndef BALL_Y12_IS_GPIO
#define BALL_Y12_IS_GPIO 0
#endif
#ifndef PAD_NAND_WPZ_IS_GPIO
#define PAD_NAND_WPZ_IS_GPIO BALL_Y12_IS_GPIO
#endif

#define BALL_Y10 PAD_NAND_ALE
#define PAD_NAND_ALE 19
#define GPIO_PAD_19 GPIO18
#ifndef BALL_Y10_IS_GPIO
#define BALL_Y10_IS_GPIO 0
#endif
#ifndef PAD_NAND_ALE_IS_GPIO
#define PAD_NAND_ALE_IS_GPIO BALL_Y10_IS_GPIO
#endif

#define BALL_W12 PAD_NAND_RBZ
#define PAD_NAND_RBZ 23
#define GPIO_PAD_23 GPIO22
#ifndef BALL_W12_IS_GPIO
#define BALL_W12_IS_GPIO 0
#endif
#ifndef PAD_NAND_RBZ_IS_GPIO
#define PAD_NAND_RBZ_IS_GPIO BALL_W12_IS_GPIO
#endif

#define BALL_W18 PAD_TS0_D0
#define PAD_TS0_D0 95
#define GPIO_PAD_95 GPIO94
#ifndef BALL_W18_IS_GPIO
#define BALL_W18_IS_GPIO 0
#endif
#ifndef PAD_TS0_D0_IS_GPIO
#define PAD_TS0_D0_IS_GPIO BALL_W18_IS_GPIO
#endif

#define BALL_Y17 PAD_TS0_D1
#define PAD_TS0_D1 96
#define GPIO_PAD_96 GPIO95
#ifndef BALL_Y17_IS_GPIO
#define BALL_Y17_IS_GPIO 0
#endif
#ifndef PAD_TS0_D1_IS_GPIO
#define PAD_TS0_D1_IS_GPIO BALL_Y17_IS_GPIO
#endif

#define BALL_W17 PAD_TS0_D2
#define PAD_TS0_D2 97
#define GPIO_PAD_97 GPIO96
#ifndef BALL_W17_IS_GPIO
#define BALL_W17_IS_GPIO 0
#endif
#ifndef PAD_TS0_D2_IS_GPIO
#define PAD_TS0_D2_IS_GPIO BALL_W17_IS_GPIO
#endif

#define BALL_Y18 PAD_TS0_D3
#define PAD_TS0_D3 98
#define GPIO_PAD_98 GPIO97
#ifndef BALL_Y18_IS_GPIO
#define BALL_Y18_IS_GPIO 0
#endif
#ifndef PAD_TS0_D3_IS_GPIO
#define PAD_TS0_D3_IS_GPIO BALL_Y18_IS_GPIO
#endif

#define BALL_AA19 PAD_TS0_D4
#define PAD_TS0_D4 99
#define GPIO_PAD_99 GPIO98
#ifndef BALL_AA19_IS_GPIO
#define BALL_AA19_IS_GPIO 0
#endif
#ifndef PAD_TS0_D4_IS_GPIO
#define PAD_TS0_D4_IS_GPIO BALL_AA19_IS_GPIO
#endif

#define BALL_AA17 PAD_TS0_D5
#define PAD_TS0_D5 100
#define GPIO_PAD_100 GPIO99
#ifndef BALL_AA17_IS_GPIO
#define BALL_AA17_IS_GPIO 0
#endif
#ifndef PAD_TS0_D5_IS_GPIO
#define PAD_TS0_D5_IS_GPIO BALL_AA17_IS_GPIO
#endif

#define BALL_Y16 PAD_TS0_D6
#define PAD_TS0_D6 101
#define GPIO_PAD_101 GPIO100
#ifndef BALL_Y16_IS_GPIO
#define BALL_Y16_IS_GPIO 0
#endif
#ifndef PAD_TS0_D6_IS_GPIO
#define PAD_TS0_D6_IS_GPIO BALL_Y16_IS_GPIO
#endif

#define BALL_AA16 PAD_TS0_D7
#define PAD_TS0_D7 102
#define GPIO_PAD_102 GPIO101
#ifndef BALL_AA16_IS_GPIO
#define BALL_AA16_IS_GPIO 0
#endif
#ifndef PAD_TS0_D7_IS_GPIO
#define PAD_TS0_D7_IS_GPIO BALL_AA16_IS_GPIO
#endif

#define BALL_W16 PAD_TS0_VLD
#define PAD_TS0_VLD 94
#define GPIO_PAD_94 GPIO93
#ifndef BALL_W16_IS_GPIO
#define BALL_W16_IS_GPIO 0
#endif
#ifndef PAD_TS0_VLD_IS_GPIO
#define PAD_TS0_VLD_IS_GPIO BALL_W16_IS_GPIO
#endif

#define BALL_AA20 PAD_TS0_SYNC
#define PAD_TS0_SYNC 93
#define GPIO_PAD_93 GPIO92
#ifndef BALL_AA20_IS_GPIO
#define BALL_AA20_IS_GPIO 0
#endif
#ifndef PAD_TS0_SYNC_IS_GPIO
#define PAD_TS0_SYNC_IS_GPIO BALL_AA20_IS_GPIO
#endif

#define BALL_Y19 PAD_TS0_CLK
#define PAD_TS0_CLK 92
#define GPIO_PAD_92 GPIO91
#ifndef BALL_Y19_IS_GPIO
#define BALL_Y19_IS_GPIO 0
#endif
#ifndef PAD_TS0_CLK_IS_GPIO
#define PAD_TS0_CLK_IS_GPIO BALL_Y19_IS_GPIO
#endif

#define BALL_N17 PAD_PCM_D0
#define PAD_PCM_D0 61
#define GPIO_PAD_61 GPIO60
#ifndef BALL_N17_IS_GPIO
#define BALL_N17_IS_GPIO 0
#endif
#ifndef PAD_PCM_D0_IS_GPIO
#define PAD_PCM_D0_IS_GPIO BALL_N17_IS_GPIO
#endif

#define BALL_L17 PAD_PCM_D1
#define PAD_PCM_D1 62
#define GPIO_PAD_62 GPIO61
#ifndef BALL_L17_IS_GPIO
#define BALL_L17_IS_GPIO 0
#endif
#ifndef PAD_PCM_D1_IS_GPIO
#define PAD_PCM_D1_IS_GPIO BALL_L17_IS_GPIO
#endif

#define BALL_M17 PAD_PCM_D2
#define PAD_PCM_D2 63
#define GPIO_PAD_63 GPIO62
#ifndef BALL_M17_IS_GPIO
#define BALL_M17_IS_GPIO 0
#endif
#ifndef PAD_PCM_D2_IS_GPIO
#define PAD_PCM_D2_IS_GPIO BALL_M17_IS_GPIO
#endif

#define BALL_K17 PAD_PCM_D3
#define PAD_PCM_D3 64
#define GPIO_PAD_64 GPIO63
#ifndef BALL_K17_IS_GPIO
#define BALL_K17_IS_GPIO 0
#endif
#ifndef PAD_PCM_D3_IS_GPIO
#define PAD_PCM_D3_IS_GPIO BALL_K17_IS_GPIO
#endif

#define BALL_U18 PAD_PCM_D6
#define PAD_PCM_D6 67
#define GPIO_PAD_67 GPIO66
#ifndef BALL_U18_IS_GPIO
#define BALL_U18_IS_GPIO 0
#endif
#ifndef PAD_PCM_D6_IS_GPIO
#define PAD_PCM_D6_IS_GPIO BALL_U18_IS_GPIO
#endif

#define BALL_M18 PAD_PCM_D4
#define PAD_PCM_D4 65
#define GPIO_PAD_65 GPIO64
#ifndef BALL_M18_IS_GPIO
#define BALL_M18_IS_GPIO 0
#endif
#ifndef PAD_PCM_D4_IS_GPIO
#define PAD_PCM_D4_IS_GPIO BALL_M18_IS_GPIO
#endif

#define BALL_V16 PAD_PCM_D7
#define PAD_PCM_D7 68
#define GPIO_PAD_68 GPIO67
#ifndef BALL_V16_IS_GPIO
#define BALL_V16_IS_GPIO 0
#endif
#ifndef PAD_PCM_D7_IS_GPIO
#define PAD_PCM_D7_IS_GPIO BALL_V16_IS_GPIO
#endif

#define BALL_L18 PAD_PCM_D5
#define PAD_PCM_D5 66
#define GPIO_PAD_66 GPIO65
#ifndef BALL_L18_IS_GPIO
#define BALL_L18_IS_GPIO 0
#endif
#ifndef PAD_PCM_D5_IS_GPIO
#define PAD_PCM_D5_IS_GPIO BALL_L18_IS_GPIO
#endif

#define BALL_V17 PAD_PCM_A14
#define PAD_PCM_A14 60
#define GPIO_PAD_60 GPIO59
#ifndef BALL_V17_IS_GPIO
#define BALL_V17_IS_GPIO 0
#endif
#ifndef PAD_PCM_A14_IS_GPIO
#define PAD_PCM_A14_IS_GPIO BALL_V17_IS_GPIO
#endif

#define BALL_J16 PAD_TS1_VLD
#define PAD_TS1_VLD 105
#define GPIO_PAD_105 GPIO104
#ifndef BALL_J16_IS_GPIO
#define BALL_J16_IS_GPIO 0
#endif
#ifndef PAD_TS1_VLD_IS_GPIO
#define PAD_TS1_VLD_IS_GPIO BALL_J16_IS_GPIO
#endif

#define BALL_U15 PAD_PCM_A13
#define PAD_PCM_A13 59
#define GPIO_PAD_59 GPIO58
#ifndef BALL_U15_IS_GPIO
#define BALL_U15_IS_GPIO 0
#endif
#ifndef PAD_PCM_A13_IS_GPIO
#define PAD_PCM_A13_IS_GPIO BALL_U15_IS_GPIO
#endif

#define BALL_H16 PAD_TS1_SYNC
#define PAD_TS1_SYNC 104
#define GPIO_PAD_104 GPIO103
#ifndef BALL_H16_IS_GPIO
#define BALL_H16_IS_GPIO 0
#endif
#ifndef PAD_TS1_SYNC_IS_GPIO
#define PAD_TS1_SYNC_IS_GPIO BALL_H16_IS_GPIO
#endif

#define BALL_U17 PAD_PCM_A12
#define PAD_PCM_A12 58
#define GPIO_PAD_58 GPIO57
#ifndef BALL_U17_IS_GPIO
#define BALL_U17_IS_GPIO 0
#endif
#ifndef PAD_PCM_A12_IS_GPIO
#define PAD_PCM_A12_IS_GPIO BALL_U17_IS_GPIO
#endif

#define BALL_H17 PAD_TS1_CLK
#define PAD_TS1_CLK 103
#define GPIO_PAD_103 GPIO102
#ifndef BALL_H17_IS_GPIO
#define BALL_H17_IS_GPIO 0
#endif
#ifndef PAD_TS1_CLK_IS_GPIO
#define PAD_TS1_CLK_IS_GPIO BALL_H17_IS_GPIO
#endif

#define BALL_R18 PAD_PCM_A11
#define PAD_PCM_A11 57
#define GPIO_PAD_57 GPIO56
#ifndef BALL_R18_IS_GPIO
#define BALL_R18_IS_GPIO 0
#endif
#ifndef PAD_PCM_A11_IS_GPIO
#define PAD_PCM_A11_IS_GPIO BALL_R18_IS_GPIO
#endif

#define BALL_U16 PAD_PCM_A10
#define PAD_PCM_A10 56
#define GPIO_PAD_56 GPIO55
#ifndef BALL_U16_IS_GPIO
#define BALL_U16_IS_GPIO 0
#endif
#ifndef PAD_PCM_A10_IS_GPIO
#define PAD_PCM_A10_IS_GPIO BALL_U16_IS_GPIO
#endif

#define BALL_H18 PAD_TS1_D7
#define PAD_TS1_D7 113
#define GPIO_PAD_113 GPIO112
#ifndef BALL_H18_IS_GPIO
#define BALL_H18_IS_GPIO 0
#endif
#ifndef PAD_TS1_D7_IS_GPIO
#define PAD_TS1_D7_IS_GPIO BALL_H18_IS_GPIO
#endif

#define BALL_P18 PAD_PCM_A9
#define PAD_PCM_A9 55
#define GPIO_PAD_55 GPIO54
#ifndef BALL_P18_IS_GPIO
#define BALL_P18_IS_GPIO 0
#endif
#ifndef PAD_PCM_A9_IS_GPIO
#define PAD_PCM_A9_IS_GPIO BALL_P18_IS_GPIO
#endif

#define BALL_J17 PAD_TS1_D6
#define PAD_TS1_D6 112
#define GPIO_PAD_112 GPIO111
#ifndef BALL_J17_IS_GPIO
#define BALL_J17_IS_GPIO 0
#endif
#ifndef PAD_TS1_D6_IS_GPIO
#define PAD_TS1_D6_IS_GPIO BALL_J17_IS_GPIO
#endif

#define BALL_T17 PAD_PCM_A8
#define PAD_PCM_A8 54
#define GPIO_PAD_54 GPIO53
#ifndef BALL_T17_IS_GPIO
#define BALL_T17_IS_GPIO 0
#endif
#ifndef PAD_PCM_A8_IS_GPIO
#define PAD_PCM_A8_IS_GPIO BALL_T17_IS_GPIO
#endif

#define BALL_J18 PAD_TS1_D5
#define PAD_TS1_D5 111
#define GPIO_PAD_111 GPIO110
#ifndef BALL_J18_IS_GPIO
#define BALL_J18_IS_GPIO 0
#endif
#ifndef PAD_TS1_D5_IS_GPIO
#define PAD_TS1_D5_IS_GPIO BALL_J18_IS_GPIO
#endif

#define BALL_W13 PAD_PCM_A7
#define PAD_PCM_A7 53
#define GPIO_PAD_53 GPIO52
#ifndef BALL_W13_IS_GPIO
#define BALL_W13_IS_GPIO 0
#endif
#ifndef PAD_PCM_A7_IS_GPIO
#define PAD_PCM_A7_IS_GPIO BALL_W13_IS_GPIO
#endif

#define BALL_G17 PAD_TS1_D4
#define PAD_TS1_D4 110
#define GPIO_PAD_110 GPIO109
#ifndef BALL_G17_IS_GPIO
#define BALL_G17_IS_GPIO 0
#endif
#ifndef PAD_TS1_D4_IS_GPIO
#define PAD_TS1_D4_IS_GPIO BALL_G17_IS_GPIO
#endif

#define BALL_Y13 PAD_PCM_A6
#define PAD_PCM_A6 52
#define GPIO_PAD_52 GPIO51
#ifndef BALL_Y13_IS_GPIO
#define BALL_Y13_IS_GPIO 0
#endif
#ifndef PAD_PCM_A6_IS_GPIO
#define PAD_PCM_A6_IS_GPIO BALL_Y13_IS_GPIO
#endif

#define BALL_F17 PAD_TS1_D3
#define PAD_TS1_D3 109
#define GPIO_PAD_109 GPIO108
#ifndef BALL_F17_IS_GPIO
#define BALL_F17_IS_GPIO 0
#endif
#ifndef PAD_TS1_D3_IS_GPIO
#define PAD_TS1_D3_IS_GPIO BALL_F17_IS_GPIO
#endif

#define BALL_AA13 PAD_PCM_A5
#define PAD_PCM_A5 51
#define GPIO_PAD_51 GPIO50
#ifndef BALL_AA13_IS_GPIO
#define BALL_AA13_IS_GPIO 0
#endif
#ifndef PAD_PCM_A5_IS_GPIO
#define PAD_PCM_A5_IS_GPIO BALL_AA13_IS_GPIO
#endif

#define BALL_W14 PAD_PCM_A4
#define PAD_PCM_A4 50
#define GPIO_PAD_50 GPIO49
#ifndef BALL_W14_IS_GPIO
#define BALL_W14_IS_GPIO 0
#endif
#ifndef PAD_PCM_A4_IS_GPIO
#define PAD_PCM_A4_IS_GPIO BALL_W14_IS_GPIO
#endif

#define BALL_G16 PAD_TS1_D2
#define PAD_TS1_D2 108
#define GPIO_PAD_108 GPIO107
#ifndef BALL_G16_IS_GPIO
#define BALL_G16_IS_GPIO 0
#endif
#ifndef PAD_TS1_D2_IS_GPIO
#define PAD_TS1_D2_IS_GPIO BALL_G16_IS_GPIO
#endif

#define BALL_AA14 PAD_PCM_A3
#define PAD_PCM_A3 49
#define GPIO_PAD_49 GPIO48
#ifndef BALL_AA14_IS_GPIO
#define BALL_AA14_IS_GPIO 0
#endif
#ifndef PAD_PCM_A3_IS_GPIO
#define PAD_PCM_A3_IS_GPIO BALL_AA14_IS_GPIO
#endif

#define BALL_F18 PAD_TS1_D1
#define PAD_TS1_D1 107
#define GPIO_PAD_107 GPIO106
#ifndef BALL_F18_IS_GPIO
#define BALL_F18_IS_GPIO 0
#endif
#ifndef PAD_TS1_D1_IS_GPIO
#define PAD_TS1_D1_IS_GPIO BALL_F18_IS_GPIO
#endif

#define BALL_Y14 PAD_PCM_A2
#define PAD_PCM_A2 48
#define GPIO_PAD_48 GPIO47
#ifndef BALL_Y14_IS_GPIO
#define BALL_Y14_IS_GPIO 0
#endif
#ifndef PAD_PCM_A2_IS_GPIO
#define PAD_PCM_A2_IS_GPIO BALL_Y14_IS_GPIO
#endif

#define BALL_F16 PAD_TS1_D0
#define PAD_TS1_D0 106
#define GPIO_PAD_106 GPIO105
#ifndef BALL_F16_IS_GPIO
#define BALL_F16_IS_GPIO 0
#endif
#ifndef PAD_TS1_D0_IS_GPIO
#define PAD_TS1_D0_IS_GPIO BALL_F16_IS_GPIO
#endif

#define BALL_W15 PAD_PCM_A1
#define PAD_PCM_A1 47
#define GPIO_PAD_47 GPIO46
#ifndef BALL_W15_IS_GPIO
#define BALL_W15_IS_GPIO 0
#endif
#ifndef PAD_PCM_A1_IS_GPIO
#define PAD_PCM_A1_IS_GPIO BALL_W15_IS_GPIO
#endif

#define BALL_Y15 PAD_PCM_A0
#define PAD_PCM_A0 46
#define GPIO_PAD_46 GPIO45
#ifndef BALL_Y15_IS_GPIO
#define BALL_Y15_IS_GPIO 0
#endif
#ifndef PAD_PCM_A0_IS_GPIO
#define PAD_PCM_A0_IS_GPIO BALL_Y15_IS_GPIO
#endif

#define BALL_V21 PAD_USB_DEBUG_GPIO
#define PAD_USB_DEBUG_GPIO 32
#define GPIO_PAD_32 GPIO31
#ifndef BALL_V21_IS_GPIO
#define BALL_V21_IS_GPIO 0
#endif
#ifndef PAD_USB_DEBUG_GPIO_IS_GPIO
#define PAD_USB_DEBUG_GPIO_IS_GPIO BALL_V21_IS_GPIO
#endif

#define BALL_T20 PAD_MOD_TX_N13
#define PAD_MOD_TX_N13 145
#define GPIO_PAD_145 GPIO144
#ifndef BALL_T20_IS_GPIO
#define BALL_T20_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_N13_IS_GPIO
#define PAD_MOD_TX_N13_IS_GPIO BALL_T20_IS_GPIO
#endif

#define BALL_R19 PAD_MOD_TX_P13
#define PAD_MOD_TX_P13 144
#define GPIO_PAD_144 GPIO143
#ifndef BALL_R19_IS_GPIO
#define BALL_R19_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_P13_IS_GPIO
#define PAD_MOD_TX_P13_IS_GPIO BALL_R19_IS_GPIO
#endif

#define BALL_R20 PAD_MOD_TX_N12
#define PAD_MOD_TX_N12 143
#define GPIO_PAD_143 GPIO142
#ifndef BALL_R20_IS_GPIO
#define BALL_R20_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_N12_IS_GPIO
#define PAD_MOD_TX_N12_IS_GPIO BALL_R20_IS_GPIO
#endif

#define BALL_R21 PAD_MOD_TX_P12
#define PAD_MOD_TX_P12 142
#define GPIO_PAD_142 GPIO141
#ifndef BALL_R21_IS_GPIO
#define BALL_R21_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_P12_IS_GPIO
#define PAD_MOD_TX_P12_IS_GPIO BALL_R21_IS_GPIO
#endif

#define BALL_P20 PAD_MOD_TX_N11
#define PAD_MOD_TX_N11 141
#define GPIO_PAD_141 GPIO140
#ifndef BALL_P20_IS_GPIO
#define BALL_P20_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_N11_IS_GPIO
#define PAD_MOD_TX_N11_IS_GPIO BALL_P20_IS_GPIO
#endif

#define BALL_N19 PAD_MOD_TX_P11
#define PAD_MOD_TX_P11 140
#define GPIO_PAD_140 GPIO139
#ifndef BALL_N19_IS_GPIO
#define BALL_N19_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_P11_IS_GPIO
#define PAD_MOD_TX_P11_IS_GPIO BALL_N19_IS_GPIO
#endif

#define BALL_N20 PAD_MOD_TX_N10
#define PAD_MOD_TX_N10 139
#define GPIO_PAD_139 GPIO138
#ifndef BALL_N20_IS_GPIO
#define BALL_N20_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_N10_IS_GPIO
#define PAD_MOD_TX_N10_IS_GPIO BALL_N20_IS_GPIO
#endif

#define BALL_M19 PAD_MOD_TX_P10
#define PAD_MOD_TX_P10 138
#define GPIO_PAD_138 GPIO137
#ifndef BALL_M19_IS_GPIO
#define BALL_M19_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_P10_IS_GPIO
#define PAD_MOD_TX_P10_IS_GPIO BALL_M19_IS_GPIO
#endif

#define BALL_M21 PAD_MOD_TX_N09
#define PAD_MOD_TX_N09 137
#define GPIO_PAD_137 GPIO136
#ifndef BALL_M21_IS_GPIO
#define BALL_M21_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_N09_IS_GPIO
#define PAD_MOD_TX_N09_IS_GPIO BALL_M21_IS_GPIO
#endif

#define BALL_L21 PAD_MOD_TX_P09
#define PAD_MOD_TX_P09 136
#define GPIO_PAD_136 GPIO135
#ifndef BALL_L21_IS_GPIO
#define BALL_L21_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_P09_IS_GPIO
#define PAD_MOD_TX_P09_IS_GPIO BALL_L21_IS_GPIO
#endif

#define BALL_L20 PAD_MOD_TX_N08
#define PAD_MOD_TX_N08 135
#define GPIO_PAD_135 GPIO134
#ifndef BALL_L20_IS_GPIO
#define BALL_L20_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_N08_IS_GPIO
#define PAD_MOD_TX_N08_IS_GPIO BALL_L20_IS_GPIO
#endif

#define BALL_L19 PAD_MOD_TX_P08
#define PAD_MOD_TX_P08 134
#define GPIO_PAD_134 GPIO133
#ifndef BALL_L19_IS_GPIO
#define BALL_L19_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_P08_IS_GPIO
#define PAD_MOD_TX_P08_IS_GPIO BALL_L19_IS_GPIO
#endif

#define BALL_J19 PAD_MOD_TX_N07
#define PAD_MOD_TX_N07 133
#define GPIO_PAD_133 GPIO132
#ifndef BALL_J19_IS_GPIO
#define BALL_J19_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_N07_IS_GPIO
#define PAD_MOD_TX_N07_IS_GPIO BALL_J19_IS_GPIO
#endif

#define BALL_J20 PAD_MOD_TX_P07
#define PAD_MOD_TX_P07 132
#define GPIO_PAD_132 GPIO131
#ifndef BALL_J20_IS_GPIO
#define BALL_J20_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_P07_IS_GPIO
#define PAD_MOD_TX_P07_IS_GPIO BALL_J20_IS_GPIO
#endif

#define BALL_J21 PAD_MOD_TX_N06
#define PAD_MOD_TX_N06 131
#define GPIO_PAD_131 GPIO130
#ifndef BALL_J21_IS_GPIO
#define BALL_J21_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_N06_IS_GPIO
#define PAD_MOD_TX_N06_IS_GPIO BALL_J21_IS_GPIO
#endif

#define BALL_H21 PAD_MOD_TX_P06
#define PAD_MOD_TX_P06 130
#define GPIO_PAD_130 GPIO129
#ifndef BALL_H21_IS_GPIO
#define BALL_H21_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_P06_IS_GPIO
#define PAD_MOD_TX_P06_IS_GPIO BALL_H21_IS_GPIO
#endif

#define BALL_G19 PAD_MOD_TX_N05
#define PAD_MOD_TX_N05 129
#define GPIO_PAD_129 GPIO128
#ifndef BALL_G19_IS_GPIO
#define BALL_G19_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_N05_IS_GPIO
#define PAD_MOD_TX_N05_IS_GPIO BALL_G19_IS_GPIO
#endif

#define BALL_G20 PAD_MOD_TX_P05
#define PAD_MOD_TX_P05 128
#define GPIO_PAD_128 GPIO127
#ifndef BALL_G20_IS_GPIO
#define BALL_G20_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_P05_IS_GPIO
#define PAD_MOD_TX_P05_IS_GPIO BALL_G20_IS_GPIO
#endif

#define BALL_F19 PAD_MOD_TX_N04
#define PAD_MOD_TX_N04 127
#define GPIO_PAD_127 GPIO126
#ifndef BALL_F19_IS_GPIO
#define BALL_F19_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_N04_IS_GPIO
#define PAD_MOD_TX_N04_IS_GPIO BALL_F19_IS_GPIO
#endif

#define BALL_F20 PAD_MOD_TX_P04
#define PAD_MOD_TX_P04 126
#define GPIO_PAD_126 GPIO125
#ifndef BALL_F20_IS_GPIO
#define BALL_F20_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_P04_IS_GPIO
#define PAD_MOD_TX_P04_IS_GPIO BALL_F20_IS_GPIO
#endif

#define BALL_E21 PAD_MOD_TX_N03
#define PAD_MOD_TX_N03 125
#define GPIO_PAD_125 GPIO124
#ifndef BALL_E21_IS_GPIO
#define BALL_E21_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_N03_IS_GPIO
#define PAD_MOD_TX_N03_IS_GPIO BALL_E21_IS_GPIO
#endif

#define BALL_E20 PAD_MOD_TX_P03
#define PAD_MOD_TX_P03 124
#define GPIO_PAD_124 GPIO123
#ifndef BALL_E20_IS_GPIO
#define BALL_E20_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_P03_IS_GPIO
#define PAD_MOD_TX_P03_IS_GPIO BALL_E20_IS_GPIO
#endif

#define BALL_E19 PAD_MOD_TX_N02
#define PAD_MOD_TX_N02 123
#define GPIO_PAD_123 GPIO122
#ifndef BALL_E19_IS_GPIO
#define BALL_E19_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_N02_IS_GPIO
#define PAD_MOD_TX_N02_IS_GPIO BALL_E19_IS_GPIO
#endif

#define BALL_D20 PAD_MOD_TX_P02
#define PAD_MOD_TX_P02 122
#define GPIO_PAD_122 GPIO121
#ifndef BALL_D20_IS_GPIO
#define BALL_D20_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_P02_IS_GPIO
#define PAD_MOD_TX_P02_IS_GPIO BALL_D20_IS_GPIO
#endif

#define BALL_C20 PAD_MOD_TX_N01
#define PAD_MOD_TX_N01 121
#define GPIO_PAD_121 GPIO120
#ifndef BALL_C20_IS_GPIO
#define BALL_C20_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_N01_IS_GPIO
#define PAD_MOD_TX_N01_IS_GPIO BALL_C20_IS_GPIO
#endif

#define BALL_C21 PAD_MOD_TX_P01
#define PAD_MOD_TX_P01 120
#define GPIO_PAD_120 GPIO119
#ifndef BALL_C21_IS_GPIO
#define BALL_C21_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_P01_IS_GPIO
#define PAD_MOD_TX_P01_IS_GPIO BALL_C21_IS_GPIO
#endif

#define BALL_B21 PAD_MOD_TX_N00
#define PAD_MOD_TX_N00 119
#define GPIO_PAD_119 GPIO118
#ifndef BALL_B21_IS_GPIO
#define BALL_B21_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_N00_IS_GPIO
#define PAD_MOD_TX_N00_IS_GPIO BALL_B21_IS_GPIO
#endif

#define BALL_B20 PAD_MOD_TX_P00
#define PAD_MOD_TX_P00 118
#define GPIO_PAD_118 GPIO117
#ifndef BALL_B20_IS_GPIO
#define BALL_B20_IS_GPIO 0
#endif
#ifndef PAD_MOD_TX_P00_IS_GPIO
#define PAD_MOD_TX_P00_IS_GPIO BALL_B20_IS_GPIO
#endif

#define BALL_A19 PAD_TS2_CLK
#define PAD_TS2_CLK 114
#define GPIO_PAD_114 GPIO113
#ifndef BALL_A19_IS_GPIO
#define BALL_A19_IS_GPIO 0
#endif
#ifndef PAD_TS2_CLK_IS_GPIO
#define PAD_TS2_CLK_IS_GPIO BALL_A19_IS_GPIO
#endif

#define BALL_B18 PAD_TS2_SYNC
#define PAD_TS2_SYNC 115
#define GPIO_PAD_115 GPIO114
#ifndef BALL_B18_IS_GPIO
#define BALL_B18_IS_GPIO 0
#endif
#ifndef PAD_TS2_SYNC_IS_GPIO
#define PAD_TS2_SYNC_IS_GPIO BALL_B18_IS_GPIO
#endif

#define BALL_A18 PAD_TS2_VLD
#define PAD_TS2_VLD 116
#define GPIO_PAD_116 GPIO115
#ifndef BALL_A18_IS_GPIO
#define BALL_A18_IS_GPIO 0
#endif
#ifndef PAD_TS2_VLD_IS_GPIO
#define PAD_TS2_VLD_IS_GPIO BALL_A18_IS_GPIO
#endif

#define BALL_C17 PAD_TS2_D0
#define PAD_TS2_D0 117
#define GPIO_PAD_117 GPIO116
#ifndef BALL_C17_IS_GPIO
#define BALL_C17_IS_GPIO 0
#endif
#ifndef PAD_TS2_D0_IS_GPIO
#define PAD_TS2_D0_IS_GPIO BALL_C17_IS_GPIO
#endif

#define BALL_B17 PAD_DDCR_DA
#define PAD_DDCR_DA 34
#define GPIO_PAD_34 GPIO33
#ifndef BALL_B17_IS_GPIO
#define BALL_B17_IS_GPIO 0
#endif
#ifndef PAD_DDCR_DA_IS_GPIO
#define PAD_DDCR_DA_IS_GPIO BALL_B17_IS_GPIO
#endif

#define BALL_A17 PAD_DDCR_CK
#define PAD_DDCR_CK 33
#define GPIO_PAD_33 GPIO32
#ifndef BALL_A17_IS_GPIO
#define BALL_A17_IS_GPIO 0
#endif
#ifndef PAD_DDCR_CK_IS_GPIO
#define PAD_DDCR_CK_IS_GPIO BALL_A17_IS_GPIO
#endif

#define BALL_D18 PAD_DDCA_DA
#define PAD_DDCA_DA 4
#define GPIO_PAD_4 GPIO03
#ifndef BALL_D18_IS_GPIO
#define BALL_D18_IS_GPIO 0
#endif
#ifndef PAD_DDCA_DA_IS_GPIO
#define PAD_DDCA_DA_IS_GPIO BALL_D18_IS_GPIO
#endif

#define BALL_D17 PAD_DDCA_CK
#define PAD_DDCA_CK 3
#define GPIO_PAD_3 GPIO02
#ifndef BALL_D17_IS_GPIO
#define BALL_D17_IS_GPIO 0
#endif
#ifndef PAD_DDCA_CK_IS_GPIO
#define PAD_DDCA_CK_IS_GPIO BALL_D17_IS_GPIO
#endif

#define PAD_TGPIO0 9999
#ifndef PAD_TGPIO0_IS_GPIO
#define PAD_TGPIO0_IS_GPIO 0
#endif

#define PAD_TGPIO1 9999
#ifndef PAD_TGPIO1_IS_GPIO
#define PAD_TGPIO1_IS_GPIO 0
#endif

#define BALL_E18 PAD_TGPIO2
#define PAD_TGPIO2 90
#define GPIO_PAD_90 GPIO89
#ifndef BALL_E18_IS_GPIO
#define BALL_E18_IS_GPIO 0
#endif
#ifndef PAD_TGPIO2_IS_GPIO
#define PAD_TGPIO2_IS_GPIO BALL_E18_IS_GPIO
#endif

#define BALL_E17 PAD_TGPIO3
#define PAD_TGPIO3 91
#define GPIO_PAD_91 GPIO90
#ifndef BALL_E17_IS_GPIO
#define BALL_E17_IS_GPIO 0
#endif
#ifndef PAD_TGPIO3_IS_GPIO
#define PAD_TGPIO3_IS_GPIO BALL_E17_IS_GPIO
#endif

#define BALL_C18 PAD_TCON0
#define PAD_TCON0 83
#define GPIO_PAD_83 GPIO82
#ifndef BALL_C18_IS_GPIO
#define BALL_C18_IS_GPIO 0
#endif
#ifndef PAD_TCON0_IS_GPIO
#define PAD_TCON0_IS_GPIO BALL_C18_IS_GPIO
#endif

#define BALL_E16 PAD_TCON1
#define PAD_TCON1 84
#define GPIO_PAD_84 GPIO83
#ifndef BALL_E16_IS_GPIO
#define BALL_E16_IS_GPIO 0
#endif
#ifndef PAD_TCON1_IS_GPIO
#define PAD_TCON1_IS_GPIO BALL_E16_IS_GPIO
#endif

#define BALL_D16 PAD_TCON2
#define PAD_TCON2 85
#define GPIO_PAD_85 GPIO84
#ifndef BALL_D16_IS_GPIO
#define BALL_D16_IS_GPIO 0
#endif
#ifndef PAD_TCON2_IS_GPIO
#define PAD_TCON2_IS_GPIO BALL_D16_IS_GPIO
#endif

#define BALL_E15 PAD_TCON3
#define PAD_TCON3 86
#define GPIO_PAD_86 GPIO85
#ifndef BALL_E15_IS_GPIO
#define BALL_E15_IS_GPIO 0
#endif
#ifndef PAD_TCON3_IS_GPIO
#define PAD_TCON3_IS_GPIO BALL_E15_IS_GPIO
#endif

#define BALL_D15 PAD_TCON4
#define PAD_TCON4 87
#define GPIO_PAD_87 GPIO86
#ifndef BALL_D15_IS_GPIO
#define BALL_D15_IS_GPIO 0
#endif
#ifndef PAD_TCON4_IS_GPIO
#define PAD_TCON4_IS_GPIO BALL_D15_IS_GPIO
#endif

#define BALL_C15 PAD_PWM0
#define PAD_PWM0 79
#define GPIO_PAD_79 GPIO78
#ifndef BALL_C15_IS_GPIO
#define BALL_C15_IS_GPIO 0
#endif
#ifndef PAD_PWM0_IS_GPIO
#define PAD_PWM0_IS_GPIO BALL_C15_IS_GPIO
#endif

#define BALL_B16 PAD_PWM1
#define PAD_PWM1 80
#define GPIO_PAD_80 GPIO79
#ifndef BALL_B16_IS_GPIO
#define BALL_B16_IS_GPIO 0
#endif
#ifndef PAD_PWM1_IS_GPIO
#define PAD_PWM1_IS_GPIO BALL_B16_IS_GPIO
#endif

#define BALL_D9 PAD_PWM2
#define PAD_PWM2 81
#define GPIO_PAD_81 GPIO80
#ifndef BALL_D9_IS_GPIO
#define BALL_D9_IS_GPIO 0
#endif
#ifndef PAD_PWM2_IS_GPIO
#define PAD_PWM2_IS_GPIO BALL_D9_IS_GPIO
#endif

#define BALL_B13 PAD_I2S_OUT_SD3
#define PAD_I2S_OUT_SD3 45
#define GPIO_PAD_45 GPIO44
#ifndef BALL_B13_IS_GPIO
#define BALL_B13_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_SD3_IS_GPIO
#define PAD_I2S_OUT_SD3_IS_GPIO BALL_B13_IS_GPIO
#endif

#define BALL_B14 PAD_I2S_OUT_SD2
#define PAD_I2S_OUT_SD2 44
#define GPIO_PAD_44 GPIO43
#ifndef BALL_B14_IS_GPIO
#define BALL_B14_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_SD2_IS_GPIO
#define PAD_I2S_OUT_SD2_IS_GPIO BALL_B14_IS_GPIO
#endif

#define BALL_C13 PAD_I2S_OUT_SD1
#define PAD_I2S_OUT_SD1 43
#define GPIO_PAD_43 GPIO42
#ifndef BALL_C13_IS_GPIO
#define BALL_C13_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_SD1_IS_GPIO
#define PAD_I2S_OUT_SD1_IS_GPIO BALL_C13_IS_GPIO
#endif

#define BALL_A14 PAD_I2S_OUT_SD
#define PAD_I2S_OUT_SD 42
#define GPIO_PAD_42 GPIO41
#ifndef BALL_A14_IS_GPIO
#define BALL_A14_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_SD_IS_GPIO
#define PAD_I2S_OUT_SD_IS_GPIO BALL_A14_IS_GPIO
#endif

#define BALL_A15 PAD_I2S_OUT_BCK
#define PAD_I2S_OUT_BCK 41
#define GPIO_PAD_41 GPIO40
#ifndef BALL_A15_IS_GPIO
#define BALL_A15_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_BCK_IS_GPIO
#define PAD_I2S_OUT_BCK_IS_GPIO BALL_A15_IS_GPIO
#endif

#define BALL_B15 PAD_I2S_OUT_MCK
#define PAD_I2S_OUT_MCK 40
#define GPIO_PAD_40 GPIO39
#ifndef BALL_B15_IS_GPIO
#define BALL_B15_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_MCK_IS_GPIO
#define PAD_I2S_OUT_MCK_IS_GPIO BALL_B15_IS_GPIO
#endif

#define BALL_C14 PAD_I2S_OUT_WS
#define PAD_I2S_OUT_WS 39
#define GPIO_PAD_39 GPIO38
#ifndef BALL_C14_IS_GPIO
#define BALL_C14_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_WS_IS_GPIO
#define PAD_I2S_OUT_WS_IS_GPIO BALL_C14_IS_GPIO
#endif

#define BALL_A12 PAD_SPDIF_OUT
#define PAD_SPDIF_OUT 82
#define GPIO_PAD_82 GPIO81
#ifndef BALL_A12_IS_GPIO
#define BALL_A12_IS_GPIO 0
#endif
#ifndef PAD_SPDIF_OUT_IS_GPIO
#define PAD_SPDIF_OUT_IS_GPIO BALL_A12_IS_GPIO
#endif

#define BALL_A8 PAD_SAR0
#define PAD_SAR0 174
#define GPIO_PAD_174 GPIO173
#ifndef BALL_A8_IS_GPIO
#define BALL_A8_IS_GPIO 0
#endif
#ifndef PAD_SAR0_IS_GPIO
#define PAD_SAR0_IS_GPIO BALL_A8_IS_GPIO
#endif

#define BALL_A9 PAD_SAR1
#define PAD_SAR1 175
#define GPIO_PAD_175 GPIO174
#ifndef BALL_A9_IS_GPIO
#define BALL_A9_IS_GPIO 0
#endif
#ifndef PAD_SAR1_IS_GPIO
#define PAD_SAR1_IS_GPIO BALL_A9_IS_GPIO
#endif

#define BALL_B9 PAD_SAR2
#define PAD_SAR2 176
#define GPIO_PAD_176 GPIO175
#ifndef BALL_B9_IS_GPIO
#define BALL_B9_IS_GPIO 0
#endif
#ifndef PAD_SAR2_IS_GPIO
#define PAD_SAR2_IS_GPIO BALL_B9_IS_GPIO
#endif

#define BALL_E10 PAD_GPIO0
#define PAD_GPIO0 25
#define GPIO_PAD_25 GPIO24
#ifndef BALL_E10_IS_GPIO
#define BALL_E10_IS_GPIO 0
#endif
#ifndef PAD_GPIO0_IS_GPIO
#define PAD_GPIO0_IS_GPIO BALL_E10_IS_GPIO
#endif

#define BALL_B8 PAD_GPIO3
#define PAD_GPIO3 28
#define GPIO_PAD_28 GPIO27
#ifndef BALL_B8_IS_GPIO
#define BALL_B8_IS_GPIO 0
#endif
#ifndef PAD_GPIO3_IS_GPIO
#define PAD_GPIO3_IS_GPIO BALL_B8_IS_GPIO
#endif

#define BALL_C8 PAD_GPIO4
#define PAD_GPIO4 29
#define GPIO_PAD_29 GPIO28
#ifndef BALL_C8_IS_GPIO
#define BALL_C8_IS_GPIO 0
#endif
#ifndef PAD_GPIO4_IS_GPIO
#define PAD_GPIO4_IS_GPIO BALL_C8_IS_GPIO
#endif

#define PAD_GPIO5 9999
#ifndef PAD_GPIO5_IS_GPIO
#define PAD_GPIO5_IS_GPIO 0
#endif

#define PAD_GPIO6 9999
#ifndef PAD_GPIO6_IS_GPIO
#define PAD_GPIO6_IS_GPIO 0
#endif

#define BALL_E9 PAD_LD_SPI_CS
#define PAD_LD_SPI_CS 35
#define GPIO_PAD_35 GPIO34
#ifndef BALL_E9_IS_GPIO
#define BALL_E9_IS_GPIO 0
#endif
#ifndef PAD_LD_SPI_CS_IS_GPIO
#define PAD_LD_SPI_CS_IS_GPIO BALL_E9_IS_GPIO
#endif

#define BALL_D8 PAD_LD_SPI_CK
#define PAD_LD_SPI_CK 36
#define GPIO_PAD_36 GPIO35
#ifndef BALL_D8_IS_GPIO
#define BALL_D8_IS_GPIO 0
#endif
#ifndef PAD_LD_SPI_CK_IS_GPIO
#define PAD_LD_SPI_CK_IS_GPIO BALL_D8_IS_GPIO
#endif

#define BALL_E8 PAD_LD_SPI_MOSI
#define PAD_LD_SPI_MOSI 37
#define GPIO_PAD_37 GPIO36
#ifndef BALL_E8_IS_GPIO
#define BALL_E8_IS_GPIO 0
#endif
#ifndef PAD_LD_SPI_MOSI_IS_GPIO
#define PAD_LD_SPI_MOSI_IS_GPIO BALL_E8_IS_GPIO
#endif

#define BALL_F9 PAD_LD_SPI_MISO
#define PAD_LD_SPI_MISO 38
#define GPIO_PAD_38 GPIO37
#ifndef BALL_F9_IS_GPIO
#define BALL_F9_IS_GPIO 0
#endif
#ifndef PAD_LD_SPI_MISO_IS_GPIO
#define PAD_LD_SPI_MISO_IS_GPIO BALL_F9_IS_GPIO
#endif

#define BALL_C16 PAD_PWM_PM
#define PAD_PWM_PM 6
#define GPIO_PAD_6 GPIO05
#ifndef BALL_C16_IS_GPIO
#define BALL_C16_IS_GPIO 0
#endif
#ifndef PAD_PWM_PM_IS_GPIO
#define PAD_PWM_PM_IS_GPIO BALL_C16_IS_GPIO
#endif

#define BALL_F7 PAD_IRIN
#define PAD_IRIN 5
#define GPIO_PAD_5 GPIO04
#ifndef BALL_F7_IS_GPIO
#define BALL_F7_IS_GPIO 0
#endif
#ifndef PAD_IRIN_IS_GPIO
#define PAD_IRIN_IS_GPIO BALL_F7_IS_GPIO
#endif

#define BALL_F8 PAD_VID0
#define PAD_VID0 1
#define GPIO_PAD_1 GPIO00
#ifndef BALL_F8_IS_GPIO
#define BALL_F8_IS_GPIO 0
#endif
#ifndef PAD_VID0_IS_GPIO
#define PAD_VID0_IS_GPIO BALL_F8_IS_GPIO
#endif

#define BALL_K6 PAD_HDMIRX_ARCTX
#define PAD_HDMIRX_ARCTX 24
#define GPIO_PAD_24 GPIO23
#ifndef BALL_K6_IS_GPIO
#define BALL_K6_IS_GPIO 0
#endif
#ifndef PAD_HDMIRX_ARCTX_IS_GPIO
#define PAD_HDMIRX_ARCTX_IS_GPIO BALL_K6_IS_GPIO
#endif

#define PAD_VID1 9999
#ifndef PAD_VID1_IS_GPIO
#define PAD_VID1_IS_GPIO 0
#endif

#define BALL_J6 PAD_CEC0
#define PAD_CEC0 7
#define GPIO_PAD_7 GPIO06
#ifndef BALL_J6_IS_GPIO
#define BALL_J6_IS_GPIO 0
#endif
#ifndef PAD_CEC0_IS_GPIO
#define PAD_CEC0_IS_GPIO BALL_J6_IS_GPIO
#endif

#define BALL_E6 PAD_DDCDC_DA
#define PAD_DDCDC_DA 13
#define GPIO_PAD_13 GPIO12
#ifndef BALL_E6_IS_GPIO
#define BALL_E6_IS_GPIO 0
#endif
#ifndef PAD_DDCDC_DA_IS_GPIO
#define PAD_DDCDC_DA_IS_GPIO BALL_E6_IS_GPIO
#endif

#define BALL_D6 PAD_DDCDC_CK
#define PAD_DDCDC_CK 12
#define GPIO_PAD_12 GPIO11
#ifndef BALL_D6_IS_GPIO
#define BALL_D6_IS_GPIO 0
#endif
#ifndef PAD_DDCDC_CK_IS_GPIO
#define PAD_DDCDC_CK_IS_GPIO BALL_D6_IS_GPIO
#endif

#define BALL_F5 PAD_DDCDB_DA
#define PAD_DDCDB_DA 11
#define GPIO_PAD_11 GPIO10
#ifndef BALL_F5_IS_GPIO
#define BALL_F5_IS_GPIO 0
#endif
#ifndef PAD_DDCDB_DA_IS_GPIO
#define PAD_DDCDB_DA_IS_GPIO BALL_F5_IS_GPIO
#endif

#define BALL_F6 PAD_DDCDB_CK
#define PAD_DDCDB_CK 10
#define GPIO_PAD_10 GPIO09
#ifndef BALL_F6_IS_GPIO
#define BALL_F6_IS_GPIO 0
#endif
#ifndef PAD_DDCDB_CK_IS_GPIO
#define PAD_DDCDB_CK_IS_GPIO BALL_F6_IS_GPIO
#endif

#define BALL_J5 PAD_DDCDA_DA
#define PAD_DDCDA_DA 9
#define GPIO_PAD_9 GPIO08
#ifndef BALL_J5_IS_GPIO
#define BALL_J5_IS_GPIO 0
#endif
#ifndef PAD_DDCDA_DA_IS_GPIO
#define PAD_DDCDA_DA_IS_GPIO BALL_J5_IS_GPIO
#endif

#define BALL_K5 PAD_DDCDA_CK
#define PAD_DDCDA_CK 8
#define GPIO_PAD_8 GPIO07
#ifndef BALL_K5_IS_GPIO
#define BALL_K5_IS_GPIO 0
#endif
#ifndef PAD_DDCDA_CK_IS_GPIO
#define PAD_DDCDA_CK_IS_GPIO BALL_K5_IS_GPIO
#endif

#define BALL_D5 PAD_HOTPLUGC_HDMI20_5V
#define PAD_HOTPLUGC_HDMI20_5V 16
#define GPIO_PAD_16 GPIO15
#ifndef BALL_D5_IS_GPIO
#define BALL_D5_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGC_HDMI20_5V_IS_GPIO
#define PAD_HOTPLUGC_HDMI20_5V_IS_GPIO BALL_D5_IS_GPIO
#endif

#define BALL_E4 PAD_HOTPLUGB_HDMI20_5V
#define PAD_HOTPLUGB_HDMI20_5V 15
#define GPIO_PAD_15 GPIO14
#ifndef BALL_E4_IS_GPIO
#define BALL_E4_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGB_HDMI20_5V_IS_GPIO
#define PAD_HOTPLUGB_HDMI20_5V_IS_GPIO BALL_E4_IS_GPIO
#endif

#define BALL_L4 PAD_HOTPLUGA_HDMI20_5V
#define PAD_HOTPLUGA_HDMI20_5V 14
#define GPIO_PAD_14 GPIO13
#ifndef BALL_L4_IS_GPIO
#define BALL_L4_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGA_HDMI20_5V_IS_GPIO
#define PAD_HOTPLUGA_HDMI20_5V_IS_GPIO BALL_L4_IS_GPIO
#endif


// PADS group name to index
#define PADS_PCMCONFIG_MODE1        1223
#define PADS_PCMCONFIG_MODE2        1224
#define PADS_PCMCONFIG1_MODE1       1225
#define PADS_PCMCONFIG1_MODE2       1226
#define PADS_PCMCONFIG1_MODE3       1227
#define PADS_PCM2CONFIG_MODE1       1228
#define PADS_PCM2CONFIG_MODE2       1229
#define PADS_PCM2CONFIG_MODE3       1230
#define PADS_PCM2CONFIG1_MODE1      1231
#define PADS_PCM2CONFIG1_MODE2      1232
#define PADS_ET_MODE1               1233
#define PADS_ET_MODE2               1234
#define PADS_DDCR                   1235
#define PADS_DDCR2                  1236
#define PADS_PCM                    1237

// chip capbilities
#define CHIP_HAS_BT656_IN           0
#define CHIP_HAS_TS0                1
#define CHIP_HAS_TS1                0
#define CHIP_HAS_LVDS_10BIT_X2      1
#define CHIP_HAS_LVDS_8BIT_X2       1
#define CHIP_HAS_LVDS_8BIT_X1       1
#define CHIP_HAS_CIMAX              0
#define CHIP_HAS_USB_P0             1
#define CHIP_HAS_USB_P1             1
#define CHIP_HAS_USBVBUS0           0
#define CHIP_HAS_USBVBUS1           0
#define CHIP_HAS_UART1_MODE1        1
#define CHIP_HAS_UART1_MODE2        1
#define CHIP_HAS_UART1_MODE3        1
#define CHIP_HAS_PCMCIA1            0
#define CHIP_HAS_PCMCIA2            0
#define CHIP_HAS_PCMCIA             0
#define CHIP_HAS_UART2_MODE1        1
#define CHIP_HAS_UART2_MODE2        1
#define CHIP_HAS_UART2_MODE3        1
#define CHIP_HAS_RGB_A              1
#define CHIP_HAS_RGB_B              1
#define CHIP_HAS_RGB_C              1
#define CHIP_HAS_HDMI_A             1
#define CHIP_HAS_HDMI_B             1
#define CHIP_HAS_HDMI_C             1
#define CHIP_HAS_SPI_CZ1            1
#define CHIP_HAS_SPI_CZ2            0
#define CHIP_HAS_SPI_CZ3            0
#define CHIP_HAS_DDCR               1
#define CHIP_HAS_DDCR2              1
#define CHIP_HAS_TCON               1
#define CHIP_HAS_ET_MODE0_MII       1
#define CHIP_HAS_ET_MODE0_RMII      1
#define CHIP_HAS_ET_MODE1_MII       1
#define CHIP_HAS_ET_MODE1_RMII      1
#define CHIP_HAS_ET_MODE2_MII       1
#define CHIP_HAS_ET_MODE2_RMII      1
#define CHIP_HAS_I2S_IN             0
#define CHIP_HAS_I2S_OUT            0
#define CHIP_HAS_SPDIF_IN           0
#define CHIP_HAS_SPDIF_OUT          0
#define CHIP_HAS_DDR_A_CMD          1
#define CHIP_HAS_DDR_A_DATA         1
#define CHIP_HAS_DDR_B_CMD          1
#define CHIP_HAS_DDR_B_DATA         1
#define CHIP_USE_PCM_CDN_IN_PCM2    0
#define CHIP_USE_I2S_IN_IN_PCM      0
#define CHIP_USE_I2S_OUT_IN_PCM     0
#define CHIP_USE_SPDIF_IN_IN_PCM    0
#define CHIP_USE_SPDIF_OUT_IN_PCM   0
#define CHIP_USE_IIC_IN_DDCR2       0
#define CHIP_USE_PWM2_IN_GPIO14     0
#define CHIP_USE_PWM3_IN_GPIO15     0

// chip additional information
#define CHIP_FAMILY_TYPE            CHIP_FAMILY_M3822

#endif /* _MSD92QSTW4_H_*/
