[INPUT]
# Path to Input TEE Loader (*.bin or *.aes)
TEE_LOADER = ./src/M7642/teeloader_bfe.bin.aes

[OUTPUT]
# Filename of MP Key encrypted TEE Loader
#ENCRYPTED_TEE_LOADER = tee_loader.aes
ENCRYPTED_TEE_LOADER = teeloader.bin.aes.cusid
# Filename of signature encrypted TEE Loader
ENCRYPTED_TEE_LOADER_SIG = teeloader.bin.sig.bin.aes.cusid
# Path  output folder
OUTPUT_PATH = ./src/M7642

[AES]
# (*.bin or *.txt, , leave blank if you don't want to exchange key)
# AES Key to decrypt TEE Image
TL_D_TI =
# AES Key to decrypt REE Loader
TL_D_REE =


[RSA]
# (*.pem or *.txt, leave blank if you don't want to exchange key)
# RSA private key to sign TEE Image; corresponding public key will be placed inside TEE Loader
TL_A_TI =
# RSA private key to sign REE Loader; corresponding public key will be placed inside TEE Loader
TL_A_REE =
# RSA private key to sign TEE Loader; corresponding public key must be in HASH0
RSAboot_Private = ./secure/RSAboot_priv.txt

# Control Data which will be inserted in TEE Loader header for anti-rollback
[VERSION]
# For anti-rollback usage
HASH2_VERSION =

# Additional option for TEE loader
[OPTIONS]
TL_OPTION = 0