/* SPDX-License-Identifier: GPL-2.0-only OR BSD-3-Clause */
/******************************************************************************
 *
 * This file is provided under a dual license.  When you use or
 * distribute this software, you may choose to be licensed under
 * version 2 of the GNU General Public License ("GPLv2 License")
 * or BSD License.
 *
 * GPLv2 License
 *
 * Copyright(C) 2019 MediaTek Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of version 2 of the GNU General Public License as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See http://www.gnu.org/licenses/gpl-2.0.html for more details.
 *
 * BSD LICENSE
 *
 * Copyright(C) 2019 MediaTek Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *****************************************************************************/

// This file is generated by script, please do not edit it directly
#ifndef _MSD23SQ_HDMI_TX_H_
#define _MSD23SQ_HDMI_TX_H_

#define PAD_NC 9999
#define PAD_GND 0

#define BALL_R4 PAD_HOTPLUGB
#define PAD_HOTPLUGB 30
#define GPIO_PAD_30 GPIO29
#ifndef BALL_R4_IS_GPIO
#define BALL_R4_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGB_IS_GPIO
#define PAD_HOTPLUGB_IS_GPIO BALL_R4_IS_GPIO
#endif

#define BALL_J4 PAD_HOTPLUGC
#define PAD_HOTPLUGC 31
#define GPIO_PAD_31 GPIO30
#ifndef BALL_J4_IS_GPIO
#define BALL_J4_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGC_IS_GPIO
#define PAD_HOTPLUGC_IS_GPIO BALL_J4_IS_GPIO
#endif

#define BALL_U3 PAD_HOTPLUGA_HDMI20_5V
#define PAD_HOTPLUGA_HDMI20_5V 33
#define GPIO_PAD_33 GPIO32
#ifndef BALL_U3_IS_GPIO
#define BALL_U3_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGA_HDMI20_5V_IS_GPIO
#define PAD_HOTPLUGA_HDMI20_5V_IS_GPIO BALL_U3_IS_GPIO
#endif

#define BALL_T2 PAD_HOTPLUGA
#define PAD_HOTPLUGA 29
#define GPIO_PAD_29 GPIO28
#ifndef BALL_T2_IS_GPIO
#define BALL_T2_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGA_IS_GPIO
#define PAD_HOTPLUGA_IS_GPIO BALL_T2_IS_GPIO
#endif

#define BALL_P4 PAD_HOTPLUGB_HDMI20_5V
#define PAD_HOTPLUGB_HDMI20_5V 34
#define GPIO_PAD_34 GPIO33
#ifndef BALL_P4_IS_GPIO
#define BALL_P4_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGB_HDMI20_5V_IS_GPIO
#define PAD_HOTPLUGB_HDMI20_5V_IS_GPIO BALL_P4_IS_GPIO
#endif

#define BALL_H4 PAD_HOTPLUGC_HDMI20_5V
#define PAD_HOTPLUGC_HDMI20_5V 35
#define GPIO_PAD_35 GPIO34
#ifndef BALL_H4_IS_GPIO
#define BALL_H4_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGC_HDMI20_5V_IS_GPIO
#define PAD_HOTPLUGC_HDMI20_5V_IS_GPIO BALL_H4_IS_GPIO
#endif

#define BALL_R2 PAD_DDCDA_CK
#define PAD_DDCDA_CK 37
#define GPIO_PAD_37 GPIO36
#ifndef BALL_R2_IS_GPIO
#define BALL_R2_IS_GPIO 0
#endif
#ifndef PAD_DDCDA_CK_IS_GPIO
#define PAD_DDCDA_CK_IS_GPIO BALL_R2_IS_GPIO
#endif

#define BALL_L4 PAD_HOTPLUGD_HDMI20_5V
#define PAD_HOTPLUGD_HDMI20_5V 36
#define GPIO_PAD_36 GPIO35
#ifndef BALL_L4_IS_GPIO
#define BALL_L4_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGD_HDMI20_5V_IS_GPIO
#define PAD_HOTPLUGD_HDMI20_5V_IS_GPIO BALL_L4_IS_GPIO
#endif

#define BALL_T3 PAD_DDCDA_DA
#define PAD_DDCDA_DA 38
#define GPIO_PAD_38 GPIO37
#ifndef BALL_T3_IS_GPIO
#define BALL_T3_IS_GPIO 0
#endif
#ifndef PAD_DDCDA_DA_IS_GPIO
#define PAD_DDCDA_DA_IS_GPIO BALL_T3_IS_GPIO
#endif

#define BALL_N5 PAD_DDCDB_CK
#define PAD_DDCDB_CK 39
#define GPIO_PAD_39 GPIO38
#ifndef BALL_N5_IS_GPIO
#define BALL_N5_IS_GPIO 0
#endif
#ifndef PAD_DDCDB_CK_IS_GPIO
#define PAD_DDCDB_CK_IS_GPIO BALL_N5_IS_GPIO
#endif

#define BALL_AE6 PAD_GPIO0_PM
#define PAD_GPIO0_PM 10
#define GPIO_PAD_10 GPIO9
#ifndef BALL_AE6_IS_GPIO
#define BALL_AE6_IS_GPIO 0
#endif
#ifndef PAD_GPIO0_PM_IS_GPIO
#define PAD_GPIO0_PM_IS_GPIO BALL_AE6_IS_GPIO
#endif

#define BALL_N6 PAD_DDCDB_DA
#define PAD_DDCDB_DA 40
#define GPIO_PAD_40 GPIO39
#ifndef BALL_N6_IS_GPIO
#define BALL_N6_IS_GPIO 0
#endif
#ifndef PAD_DDCDB_DA_IS_GPIO
#define PAD_DDCDB_DA_IS_GPIO BALL_N6_IS_GPIO
#endif

#define BALL_AH6 PAD_GPIO1_PM
#define PAD_GPIO1_PM 11
#define GPIO_PAD_11 GPIO10
#ifndef BALL_AH6_IS_GPIO
#define BALL_AH6_IS_GPIO 0
#endif
#ifndef PAD_GPIO1_PM_IS_GPIO
#define PAD_GPIO1_PM_IS_GPIO BALL_AH6_IS_GPIO
#endif

#define BALL_M5 PAD_DDCDC_CK
#define PAD_DDCDC_CK 41
#define GPIO_PAD_41 GPIO40
#ifndef BALL_M5_IS_GPIO
#define BALL_M5_IS_GPIO 0
#endif
#ifndef PAD_DDCDC_CK_IS_GPIO
#define PAD_DDCDC_CK_IS_GPIO BALL_M5_IS_GPIO
#endif

#define BALL_AG24 PAD_GPIO2_PM
#define PAD_GPIO2_PM 12
#define GPIO_PAD_12 GPIO11
#ifndef BALL_AG24_IS_GPIO
#define BALL_AG24_IS_GPIO 0
#endif
#ifndef PAD_GPIO2_PM_IS_GPIO
#define PAD_GPIO2_PM_IS_GPIO BALL_AG24_IS_GPIO
#endif

#define BALL_L6 PAD_DDCDC_DA
#define PAD_DDCDC_DA 42
#define GPIO_PAD_42 GPIO41
#ifndef BALL_L6_IS_GPIO
#define BALL_L6_IS_GPIO 0
#endif
#ifndef PAD_DDCDC_DA_IS_GPIO
#define PAD_DDCDC_DA_IS_GPIO BALL_L6_IS_GPIO
#endif

#define BALL_W2 PAD_GPIO3_PM
#define PAD_GPIO3_PM 13
#define GPIO_PAD_13 GPIO12
#ifndef BALL_W2_IS_GPIO
#define BALL_W2_IS_GPIO 0
#endif
#ifndef PAD_GPIO3_PM_IS_GPIO
#define PAD_GPIO3_PM_IS_GPIO BALL_W2_IS_GPIO
#endif

#define BALL_K5 PAD_DDCDD_CK
#define PAD_DDCDD_CK 43
#define GPIO_PAD_43 GPIO42
#ifndef BALL_K5_IS_GPIO
#define BALL_K5_IS_GPIO 0
#endif
#ifndef PAD_DDCDD_CK_IS_GPIO
#define PAD_DDCDD_CK_IS_GPIO BALL_K5_IS_GPIO
#endif

#define BALL_W3 PAD_GPIO4_PM
#define PAD_GPIO4_PM 14
#define GPIO_PAD_14 GPIO13
#ifndef BALL_W3_IS_GPIO
#define BALL_W3_IS_GPIO 0
#endif
#ifndef PAD_GPIO4_PM_IS_GPIO
#define PAD_GPIO4_PM_IS_GPIO BALL_W3_IS_GPIO
#endif

#define BALL_L5 PAD_DDCDD_DA
#define PAD_DDCDD_DA 44
#define GPIO_PAD_44 GPIO43
#ifndef BALL_L5_IS_GPIO
#define BALL_L5_IS_GPIO 0
#endif
#ifndef PAD_DDCDD_DA_IS_GPIO
#define PAD_DDCDD_DA_IS_GPIO BALL_L5_IS_GPIO
#endif

#define BALL_AH5 PAD_GPIO5_PM
#define PAD_GPIO5_PM 15
#define GPIO_PAD_15 GPIO14
#ifndef BALL_AH5_IS_GPIO
#define BALL_AH5_IS_GPIO 0
#endif
#ifndef PAD_GPIO5_PM_IS_GPIO
#define PAD_GPIO5_PM_IS_GPIO BALL_AH5_IS_GPIO
#endif

#define BALL_AD10 PAD_DDCA_CK
#define PAD_DDCA_CK 8
#define GPIO_PAD_8 GPIO7
#ifndef BALL_AD10_IS_GPIO
#define BALL_AD10_IS_GPIO 0
#endif
#ifndef PAD_DDCA_CK_IS_GPIO
#define PAD_DDCA_CK_IS_GPIO BALL_AD10_IS_GPIO
#endif

#define BALL_J6 PAD_GPIO6_PM
#define PAD_GPIO6_PM 16
#define GPIO_PAD_16 GPIO15
#ifndef BALL_J6_IS_GPIO
#define BALL_J6_IS_GPIO 0
#endif
#ifndef PAD_GPIO6_PM_IS_GPIO
#define PAD_GPIO6_PM_IS_GPIO BALL_J6_IS_GPIO
#endif

#define BALL_AC10 PAD_DDCA_DA
#define PAD_DDCA_DA 9
#define GPIO_PAD_9 GPIO8
#ifndef BALL_AC10_IS_GPIO
#define BALL_AC10_IS_GPIO 0
#endif
#ifndef PAD_DDCA_DA_IS_GPIO
#define PAD_DDCA_DA_IS_GPIO BALL_AC10_IS_GPIO
#endif

#define BALL_AA5 PAD_GPIO7_PM
#define PAD_GPIO7_PM 17
#define GPIO_PAD_17 GPIO16
#ifndef BALL_AA5_IS_GPIO
#define BALL_AA5_IS_GPIO 0
#endif
#ifndef PAD_GPIO7_PM_IS_GPIO
#define PAD_GPIO7_PM_IS_GPIO BALL_AA5_IS_GPIO
#endif

#define BALL_H6 PAD_PM_SPI_DI
#define PAD_PM_SPI_DI 3
#define GPIO_PAD_3 GPIO2
#ifndef BALL_H6_IS_GPIO
#define BALL_H6_IS_GPIO 0
#endif
#ifndef PAD_PM_SPI_DI_IS_GPIO
#define PAD_PM_SPI_DI_IS_GPIO BALL_H6_IS_GPIO
#endif

#define BALL_AA6 PAD_GPIO8_PM
#define PAD_GPIO8_PM 18
#define GPIO_PAD_18 GPIO17
#ifndef BALL_AA6_IS_GPIO
#define BALL_AA6_IS_GPIO 0
#endif
#ifndef PAD_GPIO8_PM_IS_GPIO
#define PAD_GPIO8_PM_IS_GPIO BALL_AA6_IS_GPIO
#endif

#define PAD_GPIO9_PM 9999
#ifndef PAD_GPIO9_PM_IS_GPIO
#define PAD_GPIO9_PM_IS_GPIO 0
#endif

#define BALL_H5 PAD_PM_SPI_DO
#define PAD_PM_SPI_DO 4
#define GPIO_PAD_4 GPIO3
#ifndef BALL_H5_IS_GPIO
#define BALL_H5_IS_GPIO 0
#endif
#ifndef PAD_PM_SPI_DO_IS_GPIO
#define PAD_PM_SPI_DO_IS_GPIO BALL_H5_IS_GPIO
#endif

#define PAD_GPIO10_PM 9999
#ifndef PAD_GPIO10_PM_IS_GPIO
#define PAD_GPIO10_PM_IS_GPIO 0
#endif

#define BALL_G6 PAD_PM_SPI_CK
#define PAD_PM_SPI_CK 2
#define GPIO_PAD_2 GPIO1
#ifndef BALL_G6_IS_GPIO
#define BALL_G6_IS_GPIO 0
#endif
#ifndef PAD_PM_SPI_CK_IS_GPIO
#define PAD_PM_SPI_CK_IS_GPIO BALL_G6_IS_GPIO
#endif

#define PAD_GPIO11_PM 9999
#ifndef PAD_GPIO11_PM_IS_GPIO
#define PAD_GPIO11_PM_IS_GPIO 0
#endif

#define BALL_AF6 PAD_PWM_PM
#define PAD_PWM_PM 7
#define GPIO_PAD_7 GPIO6
#ifndef BALL_AF6_IS_GPIO
#define BALL_AF6_IS_GPIO 0
#endif
#ifndef PAD_PWM_PM_IS_GPIO
#define PAD_PWM_PM_IS_GPIO BALL_AF6_IS_GPIO
#endif

#define PAD_GPIO12_PM 9999
#ifndef PAD_GPIO12_PM_IS_GPIO
#define PAD_GPIO12_PM_IS_GPIO 0
#endif

#define BALL_AE5 PAD_IRIN
#define PAD_IRIN 5
#define GPIO_PAD_5 GPIO4
#ifndef BALL_AE5_IS_GPIO
#define BALL_AE5_IS_GPIO 0
#endif
#ifndef PAD_IRIN_IS_GPIO
#define PAD_IRIN_IS_GPIO BALL_AE5_IS_GPIO
#endif

#define PAD_GPIO13_PM 9999
#ifndef PAD_GPIO13_PM_IS_GPIO
#define PAD_GPIO13_PM_IS_GPIO 0
#endif

#define BALL_P5 PAD_CEC0
#define PAD_CEC0 6
#define GPIO_PAD_6 GPIO5
#ifndef BALL_P5_IS_GPIO
#define BALL_P5_IS_GPIO 0
#endif
#ifndef PAD_CEC0_IS_GPIO
#define PAD_CEC0_IS_GPIO BALL_P5_IS_GPIO
#endif

#define PAD_GPIO14_PM 9999
#ifndef PAD_GPIO14_PM_IS_GPIO
#define PAD_GPIO14_PM_IS_GPIO 0
#endif

#define BALL_AE11 PAD_WOL_INT_OUT
#define PAD_WOL_INT_OUT 55
#define GPIO_PAD_55 GPIO54
#ifndef BALL_AE11_IS_GPIO
#define BALL_AE11_IS_GPIO 0
#endif
#ifndef PAD_WOL_INT_OUT_IS_GPIO
#define PAD_WOL_INT_OUT_IS_GPIO BALL_AE11_IS_GPIO
#endif

#define PAD_GPIO16_PM 9999
#ifndef PAD_GPIO16_PM_IS_GPIO
#define PAD_GPIO16_PM_IS_GPIO 0
#endif

#define BALL_AD4 PAD_LED0
#define PAD_LED0 27
#define GPIO_PAD_27 GPIO26
#ifndef BALL_AD4_IS_GPIO
#define BALL_AD4_IS_GPIO 0
#endif
#ifndef PAD_LED0_IS_GPIO
#define PAD_LED0_IS_GPIO BALL_AD4_IS_GPIO
#endif

#define BALL_AC4 PAD_LED1
#define PAD_LED1 28
#define GPIO_PAD_28 GPIO27
#ifndef BALL_AC4_IS_GPIO
#define BALL_AC4_IS_GPIO 0
#endif
#ifndef PAD_LED1_IS_GPIO
#define PAD_LED1_IS_GPIO BALL_AC4_IS_GPIO
#endif

#define BALL_AB2 PAD_VID0
#define PAD_VID0 51
#define GPIO_PAD_51 GPIO50
#ifndef BALL_AB2_IS_GPIO
#define BALL_AB2_IS_GPIO 0
#endif
#ifndef PAD_VID0_IS_GPIO
#define PAD_VID0_IS_GPIO BALL_AB2_IS_GPIO
#endif

#define BALL_AB3 PAD_VID1
#define PAD_VID1 52
#define GPIO_PAD_52 GPIO51
#ifndef BALL_AB3_IS_GPIO
#define BALL_AB3_IS_GPIO 0
#endif
#ifndef PAD_VID1_IS_GPIO
#define PAD_VID1_IS_GPIO BALL_AB3_IS_GPIO
#endif

#define BALL_AA4 PAD_VID2
#define PAD_VID2 53
#define GPIO_PAD_53 GPIO52
#ifndef BALL_AA4_IS_GPIO
#define BALL_AA4_IS_GPIO 0
#endif
#ifndef PAD_VID2_IS_GPIO
#define PAD_VID2_IS_GPIO BALL_AA4_IS_GPIO
#endif

#define BALL_Y4 PAD_VID3
#define PAD_VID3 54
#define GPIO_PAD_54 GPIO53
#ifndef BALL_Y4_IS_GPIO
#define BALL_Y4_IS_GPIO 0
#endif
#ifndef PAD_VID3_IS_GPIO
#define PAD_VID3_IS_GPIO BALL_Y4_IS_GPIO
#endif

#define PAD_GPIO15_PM 9999
#ifndef PAD_GPIO15_PM_IS_GPIO
#define PAD_GPIO15_PM_IS_GPIO 0
#endif

#define BALL_M4 PAD_ARC0
#define PAD_ARC0 56
#define GPIO_PAD_56 GPIO55
#ifndef BALL_M4_IS_GPIO
#define BALL_M4_IS_GPIO 0
#endif
#ifndef PAD_ARC0_IS_GPIO
#define PAD_ARC0_IS_GPIO BALL_M4_IS_GPIO
#endif

#define PAD_GPIO17 9999
#ifndef PAD_GPIO17_IS_GPIO
#define PAD_GPIO17_IS_GPIO 0
#endif

#define PAD_GPIO18 9999
#ifndef PAD_GPIO18_IS_GPIO
#define PAD_GPIO18_IS_GPIO 0
#endif

#define BALL_R27 PAD_GPIO19
#define PAD_GPIO19 82
#define GPIO_PAD_82 GPIO81
#ifndef BALL_R27_IS_GPIO
#define BALL_R27_IS_GPIO 0
#endif
#ifndef PAD_GPIO19_IS_GPIO
#define PAD_GPIO19_IS_GPIO BALL_R27_IS_GPIO
#endif

#define BALL_R26 PAD_GPIO20
#define PAD_GPIO20 83
#define GPIO_PAD_83 GPIO82
#ifndef BALL_R26_IS_GPIO
#define BALL_R26_IS_GPIO 0
#endif
#ifndef PAD_GPIO20_IS_GPIO
#define PAD_GPIO20_IS_GPIO BALL_R26_IS_GPIO
#endif

#define PAD_GPIO21 9999
#ifndef PAD_GPIO21_IS_GPIO
#define PAD_GPIO21_IS_GPIO 0
#endif

#define PAD_GPIO22 9999
#ifndef PAD_GPIO22_IS_GPIO
#define PAD_GPIO22_IS_GPIO 0
#endif

#define PAD_GPIO23 9999
#ifndef PAD_GPIO23_IS_GPIO
#define PAD_GPIO23_IS_GPIO 0
#endif

#define PAD_GPIO24 9999
#ifndef PAD_GPIO24_IS_GPIO
#define PAD_GPIO24_IS_GPIO 0
#endif

#define BALL_AF5 PAD_GPIO25
#define PAD_GPIO25 88
#define GPIO_PAD_88 GPIO87
#ifndef BALL_AF5_IS_GPIO
#define BALL_AF5_IS_GPIO 0
#endif
#ifndef PAD_GPIO25_IS_GPIO
#define PAD_GPIO25_IS_GPIO BALL_AF5_IS_GPIO
#endif

#define BALL_AG5 PAD_GPIO26
#define PAD_GPIO26 89
#define GPIO_PAD_89 GPIO88
#ifndef BALL_AG5_IS_GPIO
#define BALL_AG5_IS_GPIO 0
#endif
#ifndef PAD_GPIO26_IS_GPIO
#define PAD_GPIO26_IS_GPIO BALL_AG5_IS_GPIO
#endif

#define PAD_GPIO27 9999
#ifndef PAD_GPIO27_IS_GPIO
#define PAD_GPIO27_IS_GPIO 0
#endif

#define PAD_GPIO28 9999
#ifndef PAD_GPIO28_IS_GPIO
#define PAD_GPIO28_IS_GPIO 0
#endif

#define PAD_GPIO29 9999
#ifndef PAD_GPIO29_IS_GPIO
#define PAD_GPIO29_IS_GPIO 0
#endif

#define BALL_AC11 PAD_GPIO30
#define PAD_GPIO30 93
#define GPIO_PAD_93 GPIO92
#ifndef BALL_AC11_IS_GPIO
#define BALL_AC11_IS_GPIO 0
#endif
#ifndef PAD_GPIO30_IS_GPIO
#define PAD_GPIO30_IS_GPIO BALL_AC11_IS_GPIO
#endif

#define BALL_AD11 PAD_GPIO31
#define PAD_GPIO31 94
#define GPIO_PAD_94 GPIO93
#ifndef BALL_AD11_IS_GPIO
#define BALL_AD11_IS_GPIO 0
#endif
#ifndef PAD_GPIO31_IS_GPIO
#define PAD_GPIO31_IS_GPIO BALL_AD11_IS_GPIO
#endif

#define PAD_GPIO32 9999
#ifndef PAD_GPIO32_IS_GPIO
#define PAD_GPIO32_IS_GPIO 0
#endif

#define PAD_GPIO33 9999
#ifndef PAD_GPIO33_IS_GPIO
#define PAD_GPIO33_IS_GPIO 0
#endif

#define PAD_GPIO34 9999
#ifndef PAD_GPIO34_IS_GPIO
#define PAD_GPIO34_IS_GPIO 0
#endif

#define PAD_GPIO35 9999
#ifndef PAD_GPIO35_IS_GPIO
#define PAD_GPIO35_IS_GPIO 0
#endif

#define BALL_AF25 PAD_GPIO36
#define PAD_GPIO36 99
#define GPIO_PAD_99 GPIO98
#ifndef BALL_AF25_IS_GPIO
#define BALL_AF25_IS_GPIO 0
#endif
#ifndef PAD_GPIO36_IS_GPIO
#define PAD_GPIO36_IS_GPIO BALL_AF25_IS_GPIO
#endif

#define BALL_AG25 PAD_GPIO37
#define PAD_GPIO37 100
#define GPIO_PAD_100 GPIO99
#ifndef BALL_AG25_IS_GPIO
#define BALL_AG25_IS_GPIO 0
#endif
#ifndef PAD_GPIO37_IS_GPIO
#define PAD_GPIO37_IS_GPIO BALL_AG25_IS_GPIO
#endif

#define BALL_AD3 PAD_TGPIO0
#define PAD_TGPIO0 160
#define GPIO_PAD_160 GPIO159
#ifndef BALL_AD3_IS_GPIO
#define BALL_AD3_IS_GPIO 0
#endif
#ifndef PAD_TGPIO0_IS_GPIO
#define PAD_TGPIO0_IS_GPIO BALL_AD3_IS_GPIO
#endif

#define BALL_AE2 PAD_TGPIO1
#define PAD_TGPIO1 161
#define GPIO_PAD_161 GPIO160
#ifndef BALL_AE2_IS_GPIO
#define BALL_AE2_IS_GPIO 0
#endif
#ifndef PAD_TGPIO1_IS_GPIO
#define PAD_TGPIO1_IS_GPIO BALL_AE2_IS_GPIO
#endif

#define BALL_AF3 PAD_TGPIO2
#define PAD_TGPIO2 162
#define GPIO_PAD_162 GPIO161
#ifndef BALL_AF3_IS_GPIO
#define BALL_AF3_IS_GPIO 0
#endif
#ifndef PAD_TGPIO2_IS_GPIO
#define PAD_TGPIO2_IS_GPIO BALL_AF3_IS_GPIO
#endif

#define BALL_AE4 PAD_TGPIO3
#define PAD_TGPIO3 163
#define GPIO_PAD_163 GPIO162
#ifndef BALL_AE4_IS_GPIO
#define BALL_AE4_IS_GPIO 0
#endif
#ifndef PAD_TGPIO3_IS_GPIO
#define PAD_TGPIO3_IS_GPIO BALL_AE4_IS_GPIO
#endif

#define PAD_PCM2_RESET 9999
#ifndef PAD_PCM2_RESET_IS_GPIO
#define PAD_PCM2_RESET_IS_GPIO 0
#endif

#define PAD_PCM2_WAIT_N 9999
#ifndef PAD_PCM2_WAIT_N_IS_GPIO
#define PAD_PCM2_WAIT_N_IS_GPIO 0
#endif

#define PAD_PCM2_CD_N 9999
#ifndef PAD_PCM2_CD_N_IS_GPIO
#define PAD_PCM2_CD_N_IS_GPIO 0
#endif

#define PAD_TS2_D1 9999
#ifndef PAD_TS2_D1_IS_GPIO
#define PAD_TS2_D1_IS_GPIO 0
#endif

#define PAD_TS2_D2 9999
#ifndef PAD_TS2_D2_IS_GPIO
#define PAD_TS2_D2_IS_GPIO 0
#endif

#define PAD_TS2_D3 9999
#ifndef PAD_TS2_D3_IS_GPIO
#define PAD_TS2_D3_IS_GPIO 0
#endif

#define PAD_TS2_D4 9999
#ifndef PAD_TS2_D4_IS_GPIO
#define PAD_TS2_D4_IS_GPIO 0
#endif

#define PAD_TS2_D5 9999
#ifndef PAD_TS2_D5_IS_GPIO
#define PAD_TS2_D5_IS_GPIO 0
#endif

#define PAD_TS2_D6 9999
#ifndef PAD_TS2_D6_IS_GPIO
#define PAD_TS2_D6_IS_GPIO 0
#endif

#define PAD_TS2_D7 9999
#ifndef PAD_TS2_D7_IS_GPIO
#define PAD_TS2_D7_IS_GPIO 0
#endif

#define BALL_AG16 PAD_GPIO12
#define PAD_GPIO12 75
#define GPIO_PAD_75 GPIO74
#ifndef BALL_AG16_IS_GPIO
#define BALL_AG16_IS_GPIO 0
#endif
#ifndef PAD_GPIO12_IS_GPIO
#define PAD_GPIO12_IS_GPIO BALL_AG16_IS_GPIO
#endif

#define BALL_AF16 PAD_GPIO11
#define PAD_GPIO11 74
#define GPIO_PAD_74 GPIO73
#ifndef BALL_AF16_IS_GPIO
#define BALL_AF16_IS_GPIO 0
#endif
#ifndef PAD_GPIO11_IS_GPIO
#define PAD_GPIO11_IS_GPIO BALL_AF16_IS_GPIO
#endif

#define BALL_AD15 PAD_GPIO10
#define PAD_GPIO10 73
#define GPIO_PAD_73 GPIO72
#ifndef BALL_AD15_IS_GPIO
#define BALL_AD15_IS_GPIO 0
#endif
#ifndef PAD_GPIO10_IS_GPIO
#define PAD_GPIO10_IS_GPIO BALL_AD15_IS_GPIO
#endif

#define BALL_AC15 PAD_GPIO9
#define PAD_GPIO9 72
#define GPIO_PAD_72 GPIO71
#ifndef BALL_AC15_IS_GPIO
#define BALL_AC15_IS_GPIO 0
#endif
#ifndef PAD_GPIO9_IS_GPIO
#define PAD_GPIO9_IS_GPIO BALL_AC15_IS_GPIO
#endif

#define PAD_TS3_SYNC 9999
#ifndef PAD_TS3_SYNC_IS_GPIO
#define PAD_TS3_SYNC_IS_GPIO 0
#endif

#define PAD_TS3_VLD 9999
#ifndef PAD_TS3_VLD_IS_GPIO
#define PAD_TS3_VLD_IS_GPIO 0
#endif

#define PAD_TS3_CLK 9999
#ifndef PAD_TS3_CLK_IS_GPIO
#define PAD_TS3_CLK_IS_GPIO 0
#endif

#define PAD_TS3_D0 9999
#ifndef PAD_TS3_D0_IS_GPIO
#define PAD_TS3_D0_IS_GPIO 0
#endif

#define PAD_TS3_D1 9999
#ifndef PAD_TS3_D1_IS_GPIO
#define PAD_TS3_D1_IS_GPIO 0
#endif

#define PAD_TS3_D2 9999
#ifndef PAD_TS3_D2_IS_GPIO
#define PAD_TS3_D2_IS_GPIO 0
#endif

#define PAD_TS3_D3 9999
#ifndef PAD_TS3_D3_IS_GPIO
#define PAD_TS3_D3_IS_GPIO 0
#endif

#define PAD_TS3_D4 9999
#ifndef PAD_TS3_D4_IS_GPIO
#define PAD_TS3_D4_IS_GPIO 0
#endif

#define PAD_TS3_D5 9999
#ifndef PAD_TS3_D5_IS_GPIO
#define PAD_TS3_D5_IS_GPIO 0
#endif

#define PAD_TS3_D6 9999
#ifndef PAD_TS3_D6_IS_GPIO
#define PAD_TS3_D6_IS_GPIO 0
#endif

#define PAD_TS3_D7 9999
#ifndef PAD_TS3_D7_IS_GPIO
#define PAD_TS3_D7_IS_GPIO 0
#endif

#define BALL_AD16 PAD_PCM_WAIT_N
#define PAD_PCM_WAIT_N 147
#define GPIO_PAD_147 GPIO146
#ifndef BALL_AD16_IS_GPIO
#define BALL_AD16_IS_GPIO 0
#endif
#ifndef PAD_PCM_WAIT_N_IS_GPIO
#define PAD_PCM_WAIT_N_IS_GPIO BALL_AD16_IS_GPIO
#endif

#define BALL_AC16 PAD_PCM_RESET
#define PAD_PCM_RESET 146
#define GPIO_PAD_146 GPIO145
#ifndef BALL_AC16_IS_GPIO
#define BALL_AC16_IS_GPIO 0
#endif
#ifndef PAD_PCM_RESET_IS_GPIO
#define PAD_PCM_RESET_IS_GPIO BALL_AC16_IS_GPIO
#endif

#define BALL_AD17 PAD_PCM_WE_N
#define PAD_PCM_WE_N 148
#define GPIO_PAD_148 GPIO147
#ifndef BALL_AD17_IS_GPIO
#define BALL_AD17_IS_GPIO 0
#endif
#ifndef PAD_PCM_WE_N_IS_GPIO
#define PAD_PCM_WE_N_IS_GPIO BALL_AD17_IS_GPIO
#endif

#define BALL_AC17 PAD_PCM_IOWR_N
#define PAD_PCM_IOWR_N 142
#define GPIO_PAD_142 GPIO141
#ifndef BALL_AC17_IS_GPIO
#define BALL_AC17_IS_GPIO 0
#endif
#ifndef PAD_PCM_IOWR_N_IS_GPIO
#define PAD_PCM_IOWR_N_IS_GPIO BALL_AC17_IS_GPIO
#endif

#define BALL_AC18 PAD_PCM_CE_N
#define PAD_PCM_CE_N 132
#define GPIO_PAD_132 GPIO131
#ifndef BALL_AC18_IS_GPIO
#define BALL_AC18_IS_GPIO 0
#endif
#ifndef PAD_PCM_CE_N_IS_GPIO
#define PAD_PCM_CE_N_IS_GPIO BALL_AC18_IS_GPIO
#endif

#define PAD_GPIO15 9999
#ifndef PAD_GPIO15_IS_GPIO
#define PAD_GPIO15_IS_GPIO 0
#endif

#define BALL_AH21 PAD_PCM_CD_N
#define PAD_PCM_CD_N 131
#define GPIO_PAD_131 GPIO130
#ifndef BALL_AH21_IS_GPIO
#define BALL_AH21_IS_GPIO 0
#endif
#ifndef PAD_PCM_CD_N_IS_GPIO
#define PAD_PCM_CD_N_IS_GPIO BALL_AH21_IS_GPIO
#endif

#define BALL_AF21 PAD_PCM_A9
#define PAD_PCM_A9 125
#define GPIO_PAD_125 GPIO124
#ifndef BALL_AF21_IS_GPIO
#define BALL_AF21_IS_GPIO 0
#endif
#ifndef PAD_PCM_A9_IS_GPIO
#define PAD_PCM_A9_IS_GPIO BALL_AF21_IS_GPIO
#endif

#define BALL_AF22 PAD_PCM_REG_N
#define PAD_PCM_REG_N 145
#define GPIO_PAD_145 GPIO144
#ifndef BALL_AF22_IS_GPIO
#define BALL_AF22_IS_GPIO 0
#endif
#ifndef PAD_PCM_REG_N_IS_GPIO
#define PAD_PCM_REG_N_IS_GPIO BALL_AF22_IS_GPIO
#endif

#define BALL_AD23 PAD_PCM_D7
#define PAD_PCM_D7 140
#define GPIO_PAD_140 GPIO139
#ifndef BALL_AD23_IS_GPIO
#define BALL_AD23_IS_GPIO 0
#endif
#ifndef PAD_PCM_D7_IS_GPIO
#define PAD_PCM_D7_IS_GPIO BALL_AD23_IS_GPIO
#endif

#define BALL_AG18 PAD_TS0_D6
#define PAD_TS0_D6 171
#define GPIO_PAD_171 GPIO170
#ifndef BALL_AG18_IS_GPIO
#define BALL_AG18_IS_GPIO 0
#endif
#ifndef PAD_TS0_D6_IS_GPIO
#define PAD_TS0_D6_IS_GPIO BALL_AG18_IS_GPIO
#endif

#define BALL_AH17 PAD_TS0_VLD
#define PAD_TS0_VLD 174
#define GPIO_PAD_174 GPIO173
#ifndef BALL_AH17_IS_GPIO
#define BALL_AH17_IS_GPIO 0
#endif
#ifndef PAD_TS0_VLD_IS_GPIO
#define PAD_TS0_VLD_IS_GPIO BALL_AH17_IS_GPIO
#endif

#define BALL_AH18 PAD_TS0_D3
#define PAD_TS0_D3 168
#define GPIO_PAD_168 GPIO167
#ifndef BALL_AH18_IS_GPIO
#define BALL_AH18_IS_GPIO 0
#endif
#ifndef PAD_TS0_D3_IS_GPIO
#define PAD_TS0_D3_IS_GPIO BALL_AH18_IS_GPIO
#endif

#define BALL_AF20 PAD_TS0_D5
#define PAD_TS0_D5 170
#define GPIO_PAD_170 GPIO169
#ifndef BALL_AF20_IS_GPIO
#define BALL_AF20_IS_GPIO 0
#endif
#ifndef PAD_TS0_D5_IS_GPIO
#define PAD_TS0_D5_IS_GPIO BALL_AF20_IS_GPIO
#endif

#define BALL_AG17 PAD_TS0_D4
#define PAD_TS0_D4 169
#define GPIO_PAD_169 GPIO168
#ifndef BALL_AG17_IS_GPIO
#define BALL_AG17_IS_GPIO 0
#endif
#ifndef PAD_TS0_D4_IS_GPIO
#define PAD_TS0_D4_IS_GPIO BALL_AG17_IS_GPIO
#endif

#define BALL_AF19 PAD_TS0_CLK
#define PAD_TS0_CLK 164
#define GPIO_PAD_164 GPIO163
#ifndef BALL_AF19_IS_GPIO
#define BALL_AF19_IS_GPIO 0
#endif
#ifndef PAD_TS0_CLK_IS_GPIO
#define PAD_TS0_CLK_IS_GPIO BALL_AF19_IS_GPIO
#endif

#define BALL_AG23 PAD_PCM_D1
#define PAD_PCM_D1 134
#define GPIO_PAD_134 GPIO133
#ifndef BALL_AG23_IS_GPIO
#define BALL_AG23_IS_GPIO 0
#endif
#ifndef PAD_PCM_D1_IS_GPIO
#define PAD_PCM_D1_IS_GPIO BALL_AG23_IS_GPIO
#endif

#define BALL_AG19 PAD_TS0_SYNC
#define PAD_TS0_SYNC 173
#define GPIO_PAD_173 GPIO172
#ifndef BALL_AG19_IS_GPIO
#define BALL_AG19_IS_GPIO 0
#endif
#ifndef PAD_TS0_SYNC_IS_GPIO
#define PAD_TS0_SYNC_IS_GPIO BALL_AG19_IS_GPIO
#endif

#define BALL_AE23 PAD_PCM_A1
#define PAD_PCM_A1 117
#define GPIO_PAD_117 GPIO116
#ifndef BALL_AE23_IS_GPIO
#define BALL_AE23_IS_GPIO 0
#endif
#ifndef PAD_PCM_A1_IS_GPIO
#define PAD_PCM_A1_IS_GPIO BALL_AE23_IS_GPIO
#endif

#define BALL_AH20 PAD_TS0_D0
#define PAD_TS0_D0 165
#define GPIO_PAD_165 GPIO164
#ifndef BALL_AH20_IS_GPIO
#define BALL_AH20_IS_GPIO 0
#endif
#ifndef PAD_TS0_D0_IS_GPIO
#define PAD_TS0_D0_IS_GPIO BALL_AH20_IS_GPIO
#endif

#define BALL_AE24 PAD_PCM_A0
#define PAD_PCM_A0 116
#define GPIO_PAD_116 GPIO115
#ifndef BALL_AE24_IS_GPIO
#define BALL_AE24_IS_GPIO 0
#endif
#ifndef PAD_PCM_A0_IS_GPIO
#define PAD_PCM_A0_IS_GPIO BALL_AE24_IS_GPIO
#endif

#define BALL_AG22 PAD_PCM_A5
#define PAD_PCM_A5 121
#define GPIO_PAD_121 GPIO120
#ifndef BALL_AG22_IS_GPIO
#define BALL_AG22_IS_GPIO 0
#endif
#ifndef PAD_PCM_A5_IS_GPIO
#define PAD_PCM_A5_IS_GPIO BALL_AG22_IS_GPIO
#endif

#define BALL_AG20 PAD_TS0_D1
#define PAD_TS0_D1 166
#define GPIO_PAD_166 GPIO165
#ifndef BALL_AG20_IS_GPIO
#define BALL_AG20_IS_GPIO 0
#endif
#ifndef PAD_TS0_D1_IS_GPIO
#define PAD_TS0_D1_IS_GPIO BALL_AG20_IS_GPIO
#endif

#define BALL_AF18 PAD_TS0_D7
#define PAD_TS0_D7 172
#define GPIO_PAD_172 GPIO171
#ifndef BALL_AF18_IS_GPIO
#define BALL_AF18_IS_GPIO 0
#endif
#ifndef PAD_TS0_D7_IS_GPIO
#define PAD_TS0_D7_IS_GPIO BALL_AF18_IS_GPIO
#endif

#define BALL_AD22 PAD_PCM_A3
#define PAD_PCM_A3 119
#define GPIO_PAD_119 GPIO118
#ifndef BALL_AD22_IS_GPIO
#define BALL_AD22_IS_GPIO 0
#endif
#ifndef PAD_PCM_A3_IS_GPIO
#define PAD_PCM_A3_IS_GPIO BALL_AD22_IS_GPIO
#endif

#define BALL_AG21 PAD_PCM_IORD_N
#define PAD_PCM_IORD_N 141
#define GPIO_PAD_141 GPIO140
#ifndef BALL_AG21_IS_GPIO
#define BALL_AG21_IS_GPIO 0
#endif
#ifndef PAD_PCM_IORD_N_IS_GPIO
#define PAD_PCM_IORD_N_IS_GPIO BALL_AG21_IS_GPIO
#endif

#define BALL_AF17 PAD_TS0_D2
#define PAD_TS0_D2 167
#define GPIO_PAD_167 GPIO166
#ifndef BALL_AF17_IS_GPIO
#define BALL_AF17_IS_GPIO 0
#endif
#ifndef PAD_TS0_D2_IS_GPIO
#define PAD_TS0_D2_IS_GPIO BALL_AF17_IS_GPIO
#endif

#define BALL_AE20 PAD_PCM_A14
#define PAD_PCM_A14 130
#define GPIO_PAD_130 GPIO129
#ifndef BALL_AE20_IS_GPIO
#define BALL_AE20_IS_GPIO 0
#endif
#ifndef PAD_PCM_A14_IS_GPIO
#define PAD_PCM_A14_IS_GPIO BALL_AE20_IS_GPIO
#endif

#define BALL_AD24 PAD_PCM_D6
#define PAD_PCM_D6 139
#define GPIO_PAD_139 GPIO138
#ifndef BALL_AD24_IS_GPIO
#define BALL_AD24_IS_GPIO 0
#endif
#ifndef PAD_PCM_D6_IS_GPIO
#define PAD_PCM_D6_IS_GPIO BALL_AD24_IS_GPIO
#endif

#define BALL_AE21 PAD_PCM_OE_N
#define PAD_PCM_OE_N 144
#define GPIO_PAD_144 GPIO143
#ifndef BALL_AE21_IS_GPIO
#define BALL_AE21_IS_GPIO 0
#endif
#ifndef PAD_PCM_OE_N_IS_GPIO
#define PAD_PCM_OE_N_IS_GPIO BALL_AE21_IS_GPIO
#endif

#define BALL_AD25 PAD_PCM_D3
#define PAD_PCM_D3 136
#define GPIO_PAD_136 GPIO135
#ifndef BALL_AD25_IS_GPIO
#define BALL_AD25_IS_GPIO 0
#endif
#ifndef PAD_PCM_D3_IS_GPIO
#define PAD_PCM_D3_IS_GPIO BALL_AD25_IS_GPIO
#endif

#define BALL_AE17 PAD_PCM_IRQA_N
#define PAD_PCM_IRQA_N 143
#define GPIO_PAD_143 GPIO142
#ifndef BALL_AE17_IS_GPIO
#define BALL_AE17_IS_GPIO 0
#endif
#ifndef PAD_PCM_IRQA_N_IS_GPIO
#define PAD_PCM_IRQA_N_IS_GPIO BALL_AE17_IS_GPIO
#endif

#define BALL_AC23 PAD_PCM_D5
#define PAD_PCM_D5 138
#define GPIO_PAD_138 GPIO137
#ifndef BALL_AC23_IS_GPIO
#define BALL_AC23_IS_GPIO 0
#endif
#ifndef PAD_PCM_D5_IS_GPIO
#define PAD_PCM_D5_IS_GPIO BALL_AC23_IS_GPIO
#endif

#define BALL_AD18 PAD_PCM_A12
#define PAD_PCM_A12 128
#define GPIO_PAD_128 GPIO127
#ifndef BALL_AD18_IS_GPIO
#define BALL_AD18_IS_GPIO 0
#endif
#ifndef PAD_PCM_A12_IS_GPIO
#define PAD_PCM_A12_IS_GPIO BALL_AD18_IS_GPIO
#endif

#define BALL_AC24 PAD_PCM_D4
#define PAD_PCM_D4 137
#define GPIO_PAD_137 GPIO136
#ifndef BALL_AC24_IS_GPIO
#define BALL_AC24_IS_GPIO 0
#endif
#ifndef PAD_PCM_D4_IS_GPIO
#define PAD_PCM_D4_IS_GPIO BALL_AC24_IS_GPIO
#endif

#define BALL_AE18 PAD_PCM_A13
#define PAD_PCM_A13 129
#define GPIO_PAD_129 GPIO128
#ifndef BALL_AE18_IS_GPIO
#define BALL_AE18_IS_GPIO 0
#endif
#ifndef PAD_PCM_A13_IS_GPIO
#define PAD_PCM_A13_IS_GPIO BALL_AE18_IS_GPIO
#endif

#define BALL_AC25 PAD_PCM_D0
#define PAD_PCM_D0 133
#define GPIO_PAD_133 GPIO132
#ifndef BALL_AC25_IS_GPIO
#define BALL_AC25_IS_GPIO 0
#endif
#ifndef PAD_PCM_D0_IS_GPIO
#define PAD_PCM_D0_IS_GPIO BALL_AC25_IS_GPIO
#endif

#define BALL_AC19 PAD_PCM_A8
#define PAD_PCM_A8 124
#define GPIO_PAD_124 GPIO123
#ifndef BALL_AC19_IS_GPIO
#define BALL_AC19_IS_GPIO 0
#endif
#ifndef PAD_PCM_A8_IS_GPIO
#define PAD_PCM_A8_IS_GPIO BALL_AC19_IS_GPIO
#endif

#define BALL_AB25 PAD_PCM_D2
#define PAD_PCM_D2 135
#define GPIO_PAD_135 GPIO134
#ifndef BALL_AB25_IS_GPIO
#define BALL_AB25_IS_GPIO 0
#endif
#ifndef PAD_PCM_D2_IS_GPIO
#define PAD_PCM_D2_IS_GPIO BALL_AB25_IS_GPIO
#endif

#define BALL_AD19 PAD_PCM_A11
#define PAD_PCM_A11 127
#define GPIO_PAD_127 GPIO126
#ifndef BALL_AD19_IS_GPIO
#define BALL_AD19_IS_GPIO 0
#endif
#ifndef PAD_PCM_A11_IS_GPIO
#define PAD_PCM_A11_IS_GPIO BALL_AD19_IS_GPIO
#endif

#define BALL_AB23 PAD_PCM2_IRQA_N
#define PAD_PCM2_IRQA_N 113
#define GPIO_PAD_113 GPIO112
#ifndef BALL_AB23_IS_GPIO
#define BALL_AB23_IS_GPIO 0
#endif
#ifndef PAD_PCM2_IRQA_N_IS_GPIO
#define PAD_PCM2_IRQA_N_IS_GPIO BALL_AB23_IS_GPIO
#endif

#define BALL_AB24 PAD_PCM2_CE_N
#define PAD_PCM2_CE_N 112
#define GPIO_PAD_112 GPIO111
#ifndef BALL_AB24_IS_GPIO
#define BALL_AB24_IS_GPIO 0
#endif
#ifndef PAD_PCM2_CE_N_IS_GPIO
#define PAD_PCM2_CE_N_IS_GPIO BALL_AB24_IS_GPIO
#endif

#define BALL_AD20 PAD_PCM_A10
#define PAD_PCM_A10 126
#define GPIO_PAD_126 GPIO125
#ifndef BALL_AD20_IS_GPIO
#define BALL_AD20_IS_GPIO 0
#endif
#ifndef PAD_PCM_A10_IS_GPIO
#define PAD_PCM_A10_IS_GPIO BALL_AD20_IS_GPIO
#endif

#define BALL_AC20 PAD_PCM_A7
#define PAD_PCM_A7 123
#define GPIO_PAD_123 GPIO122
#ifndef BALL_AC20_IS_GPIO
#define BALL_AC20_IS_GPIO 0
#endif
#ifndef PAD_PCM_A7_IS_GPIO
#define PAD_PCM_A7_IS_GPIO BALL_AC20_IS_GPIO
#endif

#define BALL_N25 PAD_TS2_VLD
#define PAD_TS2_VLD 196
#define GPIO_PAD_196 GPIO195
#ifndef BALL_N25_IS_GPIO
#define BALL_N25_IS_GPIO 0
#endif
#ifndef PAD_TS2_VLD_IS_GPIO
#define PAD_TS2_VLD_IS_GPIO BALL_N25_IS_GPIO
#endif

#define BALL_AD21 PAD_PCM_A6
#define PAD_PCM_A6 122
#define GPIO_PAD_122 GPIO121
#ifndef BALL_AD21_IS_GPIO
#define BALL_AD21_IS_GPIO 0
#endif
#ifndef PAD_PCM_A6_IS_GPIO
#define PAD_PCM_A6_IS_GPIO BALL_AD21_IS_GPIO
#endif

#define BALL_N24 PAD_TS2_CLK
#define PAD_TS2_CLK 186
#define GPIO_PAD_186 GPIO185
#ifndef BALL_N24_IS_GPIO
#define BALL_N24_IS_GPIO 0
#endif
#ifndef PAD_TS2_CLK_IS_GPIO
#define PAD_TS2_CLK_IS_GPIO BALL_N24_IS_GPIO
#endif

#define BALL_AC21 PAD_PCM_A4
#define PAD_PCM_A4 120
#define GPIO_PAD_120 GPIO119
#ifndef BALL_AC21_IS_GPIO
#define BALL_AC21_IS_GPIO 0
#endif
#ifndef PAD_PCM_A4_IS_GPIO
#define PAD_PCM_A4_IS_GPIO BALL_AC21_IS_GPIO
#endif

#define BALL_M24 PAD_TS2_D0
#define PAD_TS2_D0 187
#define GPIO_PAD_187 GPIO186
#ifndef BALL_M24_IS_GPIO
#define BALL_M24_IS_GPIO 0
#endif
#ifndef PAD_TS2_D0_IS_GPIO
#define PAD_TS2_D0_IS_GPIO BALL_M24_IS_GPIO
#endif

#define BALL_AC22 PAD_PCM_A2
#define PAD_PCM_A2 118
#define GPIO_PAD_118 GPIO117
#ifndef BALL_AC22_IS_GPIO
#define BALL_AC22_IS_GPIO 0
#endif
#ifndef PAD_PCM_A2_IS_GPIO
#define PAD_PCM_A2_IS_GPIO BALL_AC22_IS_GPIO
#endif

#define BALL_P25 PAD_TS2_SYNC
#define PAD_TS2_SYNC 195
#define GPIO_PAD_195 GPIO194
#ifndef BALL_P25_IS_GPIO
#define BALL_P25_IS_GPIO 0
#endif
#ifndef PAD_TS2_SYNC_IS_GPIO
#define PAD_TS2_SYNC_IS_GPIO BALL_P25_IS_GPIO
#endif

#define BALL_N23 PAD_TS1_D2
#define PAD_TS1_D2 178
#define GPIO_PAD_178 GPIO177
#ifndef BALL_N23_IS_GPIO
#define BALL_N23_IS_GPIO 0
#endif
#ifndef PAD_TS1_D2_IS_GPIO
#define PAD_TS1_D2_IS_GPIO BALL_N23_IS_GPIO
#endif

#define BALL_P23 PAD_TS1_D3
#define PAD_TS1_D3 179
#define GPIO_PAD_179 GPIO178
#ifndef BALL_P23_IS_GPIO
#define BALL_P23_IS_GPIO 0
#endif
#ifndef PAD_TS1_D3_IS_GPIO
#define PAD_TS1_D3_IS_GPIO BALL_P23_IS_GPIO
#endif

#define BALL_P24 PAD_TS1_VLD
#define PAD_TS1_VLD 185
#define GPIO_PAD_185 GPIO184
#ifndef BALL_P24_IS_GPIO
#define BALL_P24_IS_GPIO 0
#endif
#ifndef PAD_TS1_VLD_IS_GPIO
#define PAD_TS1_VLD_IS_GPIO BALL_P24_IS_GPIO
#endif

#define BALL_R24 PAD_TS1_D7
#define PAD_TS1_D7 183
#define GPIO_PAD_183 GPIO182
#ifndef BALL_R24_IS_GPIO
#define BALL_R24_IS_GPIO 0
#endif
#ifndef PAD_TS1_D7_IS_GPIO
#define PAD_TS1_D7_IS_GPIO BALL_R24_IS_GPIO
#endif

#define BALL_R25 PAD_TS1_D6
#define PAD_TS1_D6 182
#define GPIO_PAD_182 GPIO181
#ifndef BALL_R25_IS_GPIO
#define BALL_R25_IS_GPIO 0
#endif
#ifndef PAD_TS1_D6_IS_GPIO
#define PAD_TS1_D6_IS_GPIO BALL_R25_IS_GPIO
#endif

#define BALL_T25 PAD_TS1_D1
#define PAD_TS1_D1 177
#define GPIO_PAD_177 GPIO176
#ifndef BALL_T25_IS_GPIO
#define BALL_T25_IS_GPIO 0
#endif
#ifndef PAD_TS1_D1_IS_GPIO
#define PAD_TS1_D1_IS_GPIO BALL_T25_IS_GPIO
#endif

#define BALL_T24 PAD_TS1_SYNC
#define PAD_TS1_SYNC 184
#define GPIO_PAD_184 GPIO183
#ifndef BALL_T24_IS_GPIO
#define BALL_T24_IS_GPIO 0
#endif
#ifndef PAD_TS1_SYNC_IS_GPIO
#define PAD_TS1_SYNC_IS_GPIO BALL_T24_IS_GPIO
#endif

#define BALL_R23 PAD_TS1_CLK
#define PAD_TS1_CLK 175
#define GPIO_PAD_175 GPIO174
#ifndef BALL_R23_IS_GPIO
#define BALL_R23_IS_GPIO 0
#endif
#ifndef PAD_TS1_CLK_IS_GPIO
#define PAD_TS1_CLK_IS_GPIO BALL_R23_IS_GPIO
#endif

#define BALL_U24 PAD_TS1_D4
#define PAD_TS1_D4 180
#define GPIO_PAD_180 GPIO179
#ifndef BALL_U24_IS_GPIO
#define BALL_U24_IS_GPIO 0
#endif
#ifndef PAD_TS1_D4_IS_GPIO
#define PAD_TS1_D4_IS_GPIO BALL_U24_IS_GPIO
#endif

#define BALL_U23 PAD_TS1_D0
#define PAD_TS1_D0 176
#define GPIO_PAD_176 GPIO175
#ifndef BALL_U23_IS_GPIO
#define BALL_U23_IS_GPIO 0
#endif
#ifndef PAD_TS1_D0_IS_GPIO
#define PAD_TS1_D0_IS_GPIO BALL_U23_IS_GPIO
#endif

#define BALL_T23 PAD_TS1_D5
#define PAD_TS1_D5 181
#define GPIO_PAD_181 GPIO180
#ifndef BALL_T23_IS_GPIO
#define BALL_T23_IS_GPIO 0
#endif
#ifndef PAD_TS1_D5_IS_GPIO
#define PAD_TS1_D5_IS_GPIO BALL_T23_IS_GPIO
#endif

#define PAD_DIM0 9999
#ifndef PAD_DIM0_IS_GPIO
#define PAD_DIM0_IS_GPIO 0
#endif

#define PAD_DIM1 9999
#ifndef PAD_DIM1_IS_GPIO
#define PAD_DIM1_IS_GPIO 0
#endif

#define PAD_DIM2 9999
#ifndef PAD_DIM2_IS_GPIO
#define PAD_DIM2_IS_GPIO 0
#endif

#define PAD_DIM3 9999
#ifndef PAD_DIM3_IS_GPIO
#define PAD_DIM3_IS_GPIO 0
#endif

#define BALL_F6 PAD_I2S_OUT_SD
#define PAD_I2S_OUT_SD 106
#define GPIO_PAD_106 GPIO105
#ifndef BALL_F6_IS_GPIO
#define BALL_F6_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_SD_IS_GPIO
#define PAD_I2S_OUT_SD_IS_GPIO BALL_F6_IS_GPIO
#endif

#define BALL_F5 PAD_I2S_OUT_SD1
#define PAD_I2S_OUT_SD1 107
#define GPIO_PAD_107 GPIO106
#ifndef BALL_F5_IS_GPIO
#define BALL_F5_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_SD1_IS_GPIO
#define PAD_I2S_OUT_SD1_IS_GPIO BALL_F5_IS_GPIO
#endif

#define BALL_P26 PAD_DDCR_CK
#define PAD_DDCR_CK 57
#define GPIO_PAD_57 GPIO56
#ifndef BALL_P26_IS_GPIO
#define BALL_P26_IS_GPIO 0
#endif
#ifndef PAD_DDCR_CK_IS_GPIO
#define PAD_DDCR_CK_IS_GPIO BALL_P26_IS_GPIO
#endif

#define BALL_N26 PAD_DDCR_DA
#define PAD_DDCR_DA 58
#define GPIO_PAD_58 GPIO57
#ifndef BALL_N26_IS_GPIO
#define BALL_N26_IS_GPIO 0
#endif
#ifndef PAD_DDCR_DA_IS_GPIO
#define PAD_DDCR_DA_IS_GPIO BALL_N26_IS_GPIO
#endif

#define BALL_P27 PAD_PWM0
#define PAD_PWM0 149
#define GPIO_PAD_149 GPIO148
#ifndef BALL_P27_IS_GPIO
#define BALL_P27_IS_GPIO 0
#endif
#ifndef PAD_PWM0_IS_GPIO
#define PAD_PWM0_IS_GPIO BALL_P27_IS_GPIO
#endif

#define BALL_R28 PAD_PWM1
#define PAD_PWM1 150
#define GPIO_PAD_150 GPIO149
#ifndef BALL_R28_IS_GPIO
#define BALL_R28_IS_GPIO 0
#endif
#ifndef PAD_PWM1_IS_GPIO
#define PAD_PWM1_IS_GPIO BALL_R28_IS_GPIO
#endif

#define BALL_N28 PAD_PWM2
#define PAD_PWM2 151
#define GPIO_PAD_151 GPIO150
#ifndef BALL_N28_IS_GPIO
#define BALL_N28_IS_GPIO 0
#endif
#ifndef PAD_PWM2_IS_GPIO
#define PAD_PWM2_IS_GPIO BALL_N28_IS_GPIO
#endif

#define BALL_T22 PAD_PWM3
#define PAD_PWM3 152
#define GPIO_PAD_152 GPIO151
#ifndef BALL_T22_IS_GPIO
#define BALL_T22_IS_GPIO 0
#endif
#ifndef PAD_PWM3_IS_GPIO
#define PAD_PWM3_IS_GPIO BALL_T22_IS_GPIO
#endif

#define PAD_SPI1_DI 9999
#ifndef PAD_SPI1_DI_IS_GPIO
#define PAD_SPI1_DI_IS_GPIO 0
#endif

#define PAD_SPI1_CK 9999
#ifndef PAD_SPI1_CK_IS_GPIO
#define PAD_SPI1_CK_IS_GPIO 0
#endif

#define PAD_VSYNC_Like 9999
#ifndef PAD_VSYNC_Like_IS_GPIO
#define PAD_VSYNC_Like_IS_GPIO 0
#endif

#define PAD_SPI2_DI 9999
#ifndef PAD_SPI2_DI_IS_GPIO
#define PAD_SPI2_DI_IS_GPIO 0
#endif

#define PAD_SPI2_CK 9999
#ifndef PAD_SPI2_CK_IS_GPIO
#define PAD_SPI2_CK_IS_GPIO 0
#endif

#define BALL_G5 PAD_I2S_OUT_SD2
#define PAD_I2S_OUT_SD2 108
#define GPIO_PAD_108 GPIO107
#ifndef BALL_G5_IS_GPIO
#define BALL_G5_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_SD2_IS_GPIO
#define PAD_I2S_OUT_SD2_IS_GPIO BALL_G5_IS_GPIO
#endif

#define PAD_I2S_OUT_SD3 9999
#ifndef PAD_I2S_OUT_SD3_IS_GPIO
#define PAD_I2S_OUT_SD3_IS_GPIO 0
#endif

#define BALL_E6 PAD_I2S_OUT_BCK
#define PAD_I2S_OUT_BCK 104
#define GPIO_PAD_104 GPIO103
#ifndef BALL_E6_IS_GPIO
#define BALL_E6_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_BCK_IS_GPIO
#define PAD_I2S_OUT_BCK_IS_GPIO BALL_E6_IS_GPIO
#endif

#define BALL_E5 PAD_I2S_OUT_MCK
#define PAD_I2S_OUT_MCK 105
#define GPIO_PAD_105 GPIO104
#ifndef BALL_E5_IS_GPIO
#define BALL_E5_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_MCK_IS_GPIO
#define PAD_I2S_OUT_MCK_IS_GPIO BALL_E5_IS_GPIO
#endif

#define BALL_F4 PAD_I2S_OUT_WS
#define PAD_I2S_OUT_WS 110
#define GPIO_PAD_110 GPIO109
#ifndef BALL_F4_IS_GPIO
#define BALL_F4_IS_GPIO 0
#endif
#ifndef PAD_I2S_OUT_WS_IS_GPIO
#define PAD_I2S_OUT_WS_IS_GPIO BALL_F4_IS_GPIO
#endif

#define BALL_J5 PAD_SPDIF_OUT
#define PAD_SPDIF_OUT 155
#define GPIO_PAD_155 GPIO154
#ifndef BALL_J5_IS_GPIO
#define BALL_J5_IS_GPIO 0
#endif
#ifndef PAD_SPDIF_OUT_IS_GPIO
#define PAD_SPDIF_OUT_IS_GPIO BALL_J5_IS_GPIO
#endif

#define PAD_PWM4 9999
#ifndef PAD_PWM4_IS_GPIO
#define PAD_PWM4_IS_GPIO 0
#endif

#define BALL_R21 PAD_I2S_IN_WS
#define PAD_I2S_IN_WS 103
#define GPIO_PAD_103 GPIO102
#ifndef BALL_R21_IS_GPIO
#define BALL_R21_IS_GPIO 0
#endif
#ifndef PAD_I2S_IN_WS_IS_GPIO
#define PAD_I2S_IN_WS_IS_GPIO BALL_R21_IS_GPIO
#endif

#define BALL_R20 PAD_I2S_IN_SD
#define PAD_I2S_IN_SD 102
#define GPIO_PAD_102 GPIO101
#ifndef BALL_R20_IS_GPIO
#define BALL_R20_IS_GPIO 0
#endif
#ifndef PAD_I2S_IN_SD_IS_GPIO
#define PAD_I2S_IN_SD_IS_GPIO BALL_R20_IS_GPIO
#endif

#define BALL_T21 PAD_I2S_IN_BCK
#define PAD_I2S_IN_BCK 101
#define GPIO_PAD_101 GPIO100
#ifndef BALL_T21_IS_GPIO
#define BALL_T21_IS_GPIO 0
#endif
#ifndef PAD_I2S_IN_BCK_IS_GPIO
#define PAD_I2S_IN_BCK_IS_GPIO BALL_T21_IS_GPIO
#endif

#define BALL_K6 PAD_SPDIF_IN
#define PAD_SPDIF_IN 154
#define GPIO_PAD_154 GPIO153
#ifndef BALL_K6_IS_GPIO
#define BALL_K6_IS_GPIO 0
#endif
#ifndef PAD_SPDIF_IN_IS_GPIO
#define PAD_SPDIF_IN_IS_GPIO BALL_K6_IS_GPIO
#endif

#define PAD_GPIO16 9999
#ifndef PAD_GPIO16_IS_GPIO
#define PAD_GPIO16_IS_GPIO 0
#endif

#define PAD_GPIO14 9999
#ifndef PAD_GPIO14_IS_GPIO
#define PAD_GPIO14_IS_GPIO 0
#endif

#define PAD_GPIO13 9999
#ifndef PAD_GPIO13_IS_GPIO
#define PAD_GPIO13_IS_GPIO 0
#endif

#define PAD_GPIO8 9999
#ifndef PAD_GPIO8_IS_GPIO
#define PAD_GPIO8_IS_GPIO 0
#endif

#define PAD_GPIO7 9999
#ifndef PAD_GPIO7_IS_GPIO
#define PAD_GPIO7_IS_GPIO 0
#endif

#define PAD_GPIO6 9999
#ifndef PAD_GPIO6_IS_GPIO
#define PAD_GPIO6_IS_GPIO 0
#endif

#define BALL_M28 PAD_GPIO5
#define PAD_GPIO5 68
#define GPIO_PAD_68 GPIO67
#ifndef BALL_M28_IS_GPIO
#define BALL_M28_IS_GPIO 0
#endif
#ifndef PAD_GPIO5_IS_GPIO
#define PAD_GPIO5_IS_GPIO BALL_M28_IS_GPIO
#endif

#define BALL_M27 PAD_GPIO4
#define PAD_GPIO4 67
#define GPIO_PAD_67 GPIO66
#ifndef BALL_M27_IS_GPIO
#define BALL_M27_IS_GPIO 0
#endif
#ifndef PAD_GPIO4_IS_GPIO
#define PAD_GPIO4_IS_GPIO BALL_M27_IS_GPIO
#endif

#define BALL_M26 PAD_GPIO3
#define PAD_GPIO3 66
#define GPIO_PAD_66 GPIO65
#ifndef BALL_M26_IS_GPIO
#define BALL_M26_IS_GPIO 0
#endif
#ifndef PAD_GPIO3_IS_GPIO
#define PAD_GPIO3_IS_GPIO BALL_M26_IS_GPIO
#endif

#define BALL_N27 PAD_GPIO2
#define PAD_GPIO2 65
#define GPIO_PAD_65 GPIO64
#ifndef BALL_N27_IS_GPIO
#define BALL_N27_IS_GPIO 0
#endif
#ifndef PAD_GPIO2_IS_GPIO
#define PAD_GPIO2_IS_GPIO BALL_N27_IS_GPIO
#endif

#define PAD_GPIO1 9999
#ifndef PAD_GPIO1_IS_GPIO
#define PAD_GPIO1_IS_GPIO 0
#endif

#define PAD_GPIO0 9999
#ifndef PAD_GPIO0_IS_GPIO
#define PAD_GPIO0_IS_GPIO 0
#endif

#define BALL_D4 PAD_SAR0
#define PAD_SAR0 45
#define GPIO_PAD_45 GPIO44
#ifndef BALL_D4_IS_GPIO
#define BALL_D4_IS_GPIO 0
#endif
#ifndef PAD_SAR0_IS_GPIO
#define PAD_SAR0_IS_GPIO BALL_D4_IS_GPIO
#endif

#define BALL_D5 PAD_SAR1
#define PAD_SAR1 46
#define GPIO_PAD_46 GPIO45
#ifndef BALL_D5_IS_GPIO
#define BALL_D5_IS_GPIO 0
#endif
#ifndef PAD_SAR1_IS_GPIO
#define PAD_SAR1_IS_GPIO BALL_D5_IS_GPIO
#endif

#define BALL_C5 PAD_SAR2
#define PAD_SAR2 47
#define GPIO_PAD_47 GPIO46
#ifndef BALL_C5_IS_GPIO
#define BALL_C5_IS_GPIO 0
#endif
#ifndef PAD_SAR2_IS_GPIO
#define PAD_SAR2_IS_GPIO BALL_C5_IS_GPIO
#endif

#define BALL_B5 PAD_SAR3
#define PAD_SAR3 48
#define GPIO_PAD_48 GPIO47
#ifndef BALL_B5_IS_GPIO
#define BALL_B5_IS_GPIO 0
#endif
#ifndef PAD_SAR3_IS_GPIO
#define PAD_SAR3_IS_GPIO BALL_B5_IS_GPIO
#endif

#define PAD_SAR4 9999
#ifndef PAD_SAR4_IS_GPIO
#define PAD_SAR4_IS_GPIO 0
#endif

#define BALL_M6 PAD_HOTPLUGD
#define PAD_HOTPLUGD 32
#define GPIO_PAD_32 GPIO31
#ifndef BALL_M6_IS_GPIO
#define BALL_M6_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGD_IS_GPIO
#define PAD_HOTPLUGD_IS_GPIO BALL_M6_IS_GPIO
#endif

#define BALL_E4 PAD_VPLUGIN
#define PAD_VPLUGIN 50
#define GPIO_PAD_50 GPIO49
#ifndef BALL_E4_IS_GPIO
#define BALL_E4_IS_GPIO 0
#endif
#ifndef PAD_VPLUGIN_IS_GPIO
#define PAD_VPLUGIN_IS_GPIO BALL_E4_IS_GPIO
#endif


// PADS group name to index
#define PADS_DDCR           1223
#define PADS_DDCR2          1224
#define PADS_TS0            1225
#define PADS_TS1            1226
#define PADS_GPIO1_GPIO2    1227
#define PADS_LHSYNC2_LVSYNC2 1228
#define PADS_PCI_AD20_AD21  1229
#define PADS_PCI            1230
#define PADS_PCM            1231
#define PADS_SAR            1232
#define PADS_DOUT           1233
#define PADS_DIN            1234
#define PADS_I2S            1235
#define PADS_PF             1236
#define PADS_EMAC           1237
#define PADS_TCON           1238
#define PADS_UART1_MODE1    1239
#define PADS_UART1_MODE2    1240
#define PADS_UART1_MODE3    1241
#define PADS_UART2_MODE1    1242
#define PADS_UART2_MODE2    1243
#define PADS_UART2_MODE3    1244
#define PADS_ET_MODE0       1245
#define PADS_ET_MODE1       1246
#define PADS_ET_MODE2       1247
#define PADS_ET_MODE3       1248
#define PADS_MIIC           1249
#define PADS_PF_MODE1       1250
#define PADS_PF_MODE2       1251
#define PADS_PF_MODE3       1252
#define PADS_SPI_CZ1        1253
#define PADS_SPI_CZ2        1254
#define PADS_SPI_CZ3        1255
#define PADS_DDCR3          1256

// chip capbilities
#define CHIP_HAS_BT656_IN          0
#define CHIP_HAS_TS0               1
#define CHIP_HAS_TS1               0
#define CHIP_HAS_LVDS_10BIT_X2     1
#define CHIP_HAS_LVDS_8BIT_X2      1
#define CHIP_HAS_LVDS_8BIT_X1      1
#define CHIP_HAS_CIMAX             0
#define CHIP_HAS_USB_P0            1
#define CHIP_HAS_USB_P1            1
#define CHIP_HAS_USBVBUS0          0
#define CHIP_HAS_USBVBUS1          0
#define CHIP_HAS_UART1_MODE1       1
#define CHIP_HAS_UART1_MODE2       1
#define CHIP_HAS_UART1_MODE3       1
#define CHIP_HAS_PCMCIA1           0
#define CHIP_HAS_PCMCIA2           0
#define CHIP_HAS_PCMCIA            0
#define CHIP_HAS_UART2_MODE1       1
#define CHIP_HAS_UART2_MODE2       1
#define CHIP_HAS_UART2_MODE3       1
#define CHIP_HAS_RGB_A             1
#define CHIP_HAS_RGB_B             1
#define CHIP_HAS_RGB_C             1
#define CHIP_HAS_HDMI_A            1
#define CHIP_HAS_HDMI_B            1
#define CHIP_HAS_HDMI_C            1
#define CHIP_HAS_SPI_CZ1           1
#define CHIP_HAS_SPI_CZ2           0
#define CHIP_HAS_SPI_CZ3           0
#define CHIP_HAS_DDCR              1
#define CHIP_HAS_DDCR2             1
#define CHIP_HAS_TCON              1
#define CHIP_HAS_ET_MODE0_MII      1
#define CHIP_HAS_ET_MODE0_RMII     1
#define CHIP_HAS_ET_MODE1_MII      1
#define CHIP_HAS_ET_MODE1_RMII     1
#define CHIP_HAS_ET_MODE2_MII      1
#define CHIP_HAS_ET_MODE2_RMII     1
#define CHIP_HAS_I2S_IN            1
#define CHIP_HAS_I2S_OUT           1
#define CHIP_HAS_SPDIF_IN          0
#define CHIP_HAS_SPDIF_OUT         1
#define CHIP_HAS_DDR_A_CMD         1
#define CHIP_HAS_DDR_A_DATA        1
#define CHIP_HAS_DDR_B_CMD         1
#define CHIP_HAS_DDR_B_DATA        1
#define CHIP_USE_PCM_CDN_IN_PCM2   0
#define CHIP_USE_I2S_IN_IN_PCM     0
#define CHIP_USE_I2S_OUT_IN_PCM    0
#define CHIP_USE_SPDIF_IN_IN_PCM   0
#define CHIP_USE_SPDIF_OUT_IN_PCM  0
#define CHIP_USE_IIC_IN_DDCR2      0
#define CHIP_USE_PWM2_IN_GPIO14    0
#define CHIP_USE_PWM3_IN_GPIO15    0

// chip additional information
#define CHIP_FAMILY_TYPE           CHIP_FAMILY_S7J

#endif /* _MSD23SQ_HDMI_TX_H_*/
