/* SPDX-License-Identifier: GPL-2.0-only OR BSD-3-Clause */
/******************************************************************************
 *
 * This file is provided under a dual license.  When you use or
 * distribute this software, you may choose to be licensed under
 * version 2 of the GNU General Public License ("GPLv2 License")
 * or BSD License.
 *
 * GPLv2 License
 *
 * Copyright(C) 2019 MediaTek Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of version 2 of the GNU General Public License as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See http://www.gnu.org/licenses/gpl-2.0.html for more details.
 *
 * BSD LICENSE
 *
 * Copyright(C) 2019 MediaTek Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *****************************************************************************/

// This file is generated by script, please do not edit it directly 
#ifndef _MSD93F1TX_H_
#define _MSD93F1TX_H_

#define PAD_NC 9999
#define PAD_GND 0

#define PAD_HOTPLUGB 9999
#ifndef PAD_HOTPLUGB_IS_GPIO
#define PAD_HOTPLUGB_IS_GPIO 0
#endif 

#define BALL_E5 PAD_DDCDD_DA
#define PAD_DDCDD_DA 38
#define GPIO_PAD_38 GPIO37
#ifndef BALL_E5_IS_GPIO
#define BALL_E5_IS_GPIO 0
#endif 
#ifndef PAD_DDCDD_DA_IS_GPIO
#define PAD_DDCDD_DA_IS_GPIO BALL_E5_IS_GPIO
#endif 

#define PAD_DDCDB_CK 9999
#ifndef PAD_DDCDB_CK_IS_GPIO
#define PAD_DDCDB_CK_IS_GPIO 0
#endif 

#define BALL_E4 PAD_DDCDD_CK
#define PAD_DDCDD_CK 37
#define GPIO_PAD_37 GPIO36
#ifndef BALL_E4_IS_GPIO
#define BALL_E4_IS_GPIO 0
#endif 
#ifndef PAD_DDCDD_CK_IS_GPIO
#define PAD_DDCDD_CK_IS_GPIO BALL_E4_IS_GPIO
#endif 

#define PAD_GPIO_PM11 9999
#ifndef PAD_GPIO_PM11_IS_GPIO
#define PAD_GPIO_PM11_IS_GPIO 0
#endif 

#define BALL_B3 PAD_GPIO_PM1
#define PAD_GPIO_PM1 12
#define GPIO_PAD_12 GPIO11
#ifndef BALL_B3_IS_GPIO
#define BALL_B3_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM1_IS_GPIO
#define PAD_GPIO_PM1_IS_GPIO BALL_B3_IS_GPIO
#endif 

#define PAD_GPIO_PM12 9999
#ifndef PAD_GPIO_PM12_IS_GPIO
#define PAD_GPIO_PM12_IS_GPIO 0
#endif 

#define BALL_D4 PAD_HOTPLUGD
#define PAD_HOTPLUGD 30
#define GPIO_PAD_30 GPIO29
#ifndef BALL_D4_IS_GPIO
#define BALL_D4_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGD_IS_GPIO
#define PAD_HOTPLUGD_IS_GPIO BALL_D4_IS_GPIO
#endif 

#define BALL_D7 PAD_GPIO_PM10
#define PAD_GPIO_PM10 21
#define GPIO_PAD_21 GPIO20
#ifndef BALL_D7_IS_GPIO
#define BALL_D7_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM10_IS_GPIO
#define PAD_GPIO_PM10_IS_GPIO BALL_D7_IS_GPIO
#endif 

#define BALL_B7 PAD_VID0
#define PAD_VID0 7
#define GPIO_PAD_7 GPIO6
#ifndef BALL_B7_IS_GPIO
#define BALL_B7_IS_GPIO 0
#endif 
#ifndef PAD_VID0_IS_GPIO
#define PAD_VID0_IS_GPIO BALL_B7_IS_GPIO
#endif 

#define BALL_E6 PAD_ARC0
#define PAD_ARC0 254
#define GPIO_PAD_254 GPIO253
#ifndef BALL_E6_IS_GPIO
#define BALL_E6_IS_GPIO 0
#endif 
#ifndef PAD_ARC0_IS_GPIO
#define PAD_ARC0_IS_GPIO BALL_E6_IS_GPIO
#endif 

#define BALL_A7 PAD_VID1
#define PAD_VID1 8
#define GPIO_PAD_8 GPIO7
#ifndef BALL_A7_IS_GPIO
#define BALL_A7_IS_GPIO 0
#endif 
#ifndef PAD_VID1_IS_GPIO
#define PAD_VID1_IS_GPIO BALL_A7_IS_GPIO
#endif 

#define BALL_G5 PADA_HSYNC0
#define PADA_HSYNC0 240
#define GPIO_PAD_240 GPIO239
#ifndef BALL_G5_IS_GPIO
#define BALL_G5_IS_GPIO 0
#endif 
#ifndef PADA_HSYNC0_IS_GPIO
#define PADA_HSYNC0_IS_GPIO BALL_G5_IS_GPIO
#endif 

#define BALL_J1 PADA_BIN0P
#define PADA_BIN0P 250
#define GPIO_PAD_250 GPIO249
#ifndef BALL_J1_IS_GPIO
#define BALL_J1_IS_GPIO 0
#endif 
#ifndef PADA_BIN0P_IS_GPIO
#define PADA_BIN0P_IS_GPIO BALL_J1_IS_GPIO
#endif 

#define BALL_K3 PADA_GIN0P
#define PADA_GIN0P 248
#define GPIO_PAD_248 GPIO247
#ifndef BALL_K3_IS_GPIO
#define BALL_K3_IS_GPIO 0
#endif 
#ifndef PADA_GIN0P_IS_GPIO
#define PADA_GIN0P_IS_GPIO BALL_K3_IS_GPIO
#endif 

#define BALL_K1 PADA_GIN0M
#define PADA_GIN0M 252
#define GPIO_PAD_252 GPIO251
#ifndef BALL_K1_IS_GPIO
#define BALL_K1_IS_GPIO 0
#endif 
#ifndef PADA_GIN0M_IS_GPIO
#define PADA_GIN0M_IS_GPIO BALL_K1_IS_GPIO
#endif 

#define BALL_K2 PADA_RIN0P
#define PADA_RIN0P 246
#define GPIO_PAD_246 GPIO245
#ifndef BALL_K2_IS_GPIO
#define BALL_K2_IS_GPIO 0
#endif 
#ifndef PADA_RIN0P_IS_GPIO
#define PADA_RIN0P_IS_GPIO BALL_K2_IS_GPIO
#endif 

#define BALL_G6 PADA_VSYNC0
#define PADA_VSYNC0 241
#define GPIO_PAD_241 GPIO240
#ifndef BALL_G6_IS_GPIO
#define BALL_G6_IS_GPIO 0
#endif 
#ifndef PADA_VSYNC0_IS_GPIO
#define PADA_VSYNC0_IS_GPIO BALL_G6_IS_GPIO
#endif 

#define PADA_HSYNC1 9999
#ifndef PADA_HSYNC1_IS_GPIO
#define PADA_HSYNC1_IS_GPIO 0
#endif 

#define BALL_L3 PADA_BIN1P
#define PADA_BIN1P 251
#define GPIO_PAD_251 GPIO250
#ifndef BALL_L3_IS_GPIO
#define BALL_L3_IS_GPIO 0
#endif 
#ifndef PADA_BIN1P_IS_GPIO
#define PADA_BIN1P_IS_GPIO BALL_L3_IS_GPIO
#endif 

#define BALL_L2 PADA_GIN1P
#define PADA_GIN1P 249
#define GPIO_PAD_249 GPIO248
#ifndef BALL_L2_IS_GPIO
#define BALL_L2_IS_GPIO 0
#endif 
#ifndef PADA_GIN1P_IS_GPIO
#define PADA_GIN1P_IS_GPIO BALL_L2_IS_GPIO
#endif 

#define BALL_M3 PADA_GIN1M
#define PADA_GIN1M 253
#define GPIO_PAD_253 GPIO252
#ifndef BALL_M3_IS_GPIO
#define BALL_M3_IS_GPIO 0
#endif 
#ifndef PADA_GIN1M_IS_GPIO
#define PADA_GIN1M_IS_GPIO BALL_M3_IS_GPIO
#endif 

#define BALL_M2 PADA_RIN1P
#define PADA_RIN1P 247
#define GPIO_PAD_247 GPIO246
#ifndef BALL_M2_IS_GPIO
#define BALL_M2_IS_GPIO 0
#endif 
#ifndef PADA_RIN1P_IS_GPIO
#define PADA_RIN1P_IS_GPIO BALL_M2_IS_GPIO
#endif 

#define PADA_VSYNC1 9999
#ifndef PADA_VSYNC1_IS_GPIO
#define PADA_VSYNC1_IS_GPIO 0
#endif 

#define PADA_HSYNC2 9999
#ifndef PADA_HSYNC2_IS_GPIO
#define PADA_HSYNC2_IS_GPIO 0
#endif 

#define BALL_G7 PADA_VSYNC2
#define PADA_VSYNC2 245
#define GPIO_PAD_245 GPIO244
#ifndef BALL_G7_IS_GPIO
#define BALL_G7_IS_GPIO 0
#endif 
#ifndef PADA_VSYNC2_IS_GPIO
#define PADA_VSYNC2_IS_GPIO BALL_G7_IS_GPIO
#endif 

#define BALL_R6 PAD_LINEIN_L1
#define PAD_LINEIN_L1 230
#define GPIO_PAD_230 GPIO229
#ifndef BALL_R6_IS_GPIO
#define BALL_R6_IS_GPIO 0
#endif 
#ifndef PAD_LINEIN_L1_IS_GPIO
#define PAD_LINEIN_L1_IS_GPIO BALL_R6_IS_GPIO
#endif 

#define BALL_R4 PAD_LINEIN_R1
#define PAD_LINEIN_R1 231
#define GPIO_PAD_231 GPIO230
#ifndef BALL_R4_IS_GPIO
#define BALL_R4_IS_GPIO 0
#endif 
#ifndef PAD_LINEIN_R1_IS_GPIO
#define PAD_LINEIN_R1_IS_GPIO BALL_R4_IS_GPIO
#endif 

#define BALL_P2 PAD_LINEIN_R2
#define PAD_LINEIN_R2 233
#define GPIO_PAD_233 GPIO232
#ifndef BALL_P2_IS_GPIO
#define BALL_P2_IS_GPIO 0
#endif 
#ifndef PAD_LINEIN_R2_IS_GPIO
#define PAD_LINEIN_R2_IS_GPIO BALL_P2_IS_GPIO
#endif 

#define BALL_R3 PAD_LINEIN_L2
#define PAD_LINEIN_L2 232
#define GPIO_PAD_232 GPIO231
#ifndef BALL_R3_IS_GPIO
#define BALL_R3_IS_GPIO 0
#endif 
#ifndef PAD_LINEIN_L2_IS_GPIO
#define PAD_LINEIN_L2_IS_GPIO BALL_R3_IS_GPIO
#endif 

#define BALL_N7 PAD_LINEIN_R3
#define PAD_LINEIN_R3 235
#define GPIO_PAD_235 GPIO234
#ifndef BALL_N7_IS_GPIO
#define BALL_N7_IS_GPIO 0
#endif 
#ifndef PAD_LINEIN_R3_IS_GPIO
#define PAD_LINEIN_R3_IS_GPIO BALL_N7_IS_GPIO
#endif 

#define BALL_N6 PAD_LINEIN_L3
#define PAD_LINEIN_L3 234
#define GPIO_PAD_234 GPIO233
#ifndef BALL_N6_IS_GPIO
#define BALL_N6_IS_GPIO 0
#endif 
#ifndef PAD_LINEIN_L3_IS_GPIO
#define PAD_LINEIN_L3_IS_GPIO BALL_N6_IS_GPIO
#endif 

#define PAD_LINEIN_R4 9999
#ifndef PAD_LINEIN_R4_IS_GPIO
#define PAD_LINEIN_R4_IS_GPIO 0
#endif 

#define PAD_LINEIN_L4 9999
#ifndef PAD_LINEIN_L4_IS_GPIO
#define PAD_LINEIN_L4_IS_GPIO 0
#endif 

#define PAD_LINEIN_R5 9999
#ifndef PAD_LINEIN_R5_IS_GPIO
#define PAD_LINEIN_R5_IS_GPIO 0
#endif 

#define PAD_LINEIN_L5 9999
#ifndef PAD_LINEIN_L5_IS_GPIO
#define PAD_LINEIN_L5_IS_GPIO 0
#endif 

#define BALL_Y4 PAD_DDCDC_DA
#define PAD_DDCDC_DA 36
#define GPIO_PAD_36 GPIO35
#ifndef BALL_Y4_IS_GPIO
#define BALL_Y4_IS_GPIO 0
#endif 
#ifndef PAD_DDCDC_DA_IS_GPIO
#define PAD_DDCDC_DA_IS_GPIO BALL_Y4_IS_GPIO
#endif 

#define BALL_W4 PAD_DDCDC_CK
#define PAD_DDCDC_CK 35
#define GPIO_PAD_35 GPIO34
#ifndef BALL_W4_IS_GPIO
#define BALL_W4_IS_GPIO 0
#endif 
#ifndef PAD_DDCDC_CK_IS_GPIO
#define PAD_DDCDC_CK_IS_GPIO BALL_W4_IS_GPIO
#endif 

#define BALL_AA4 PAD_HOTPLUGC
#define PAD_HOTPLUGC 29
#define GPIO_PAD_29 GPIO28
#ifndef BALL_AA4_IS_GPIO
#define BALL_AA4_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGC_IS_GPIO
#define PAD_HOTPLUGC_IS_GPIO BALL_AA4_IS_GPIO
#endif 

#define BALL_Y3 PAD_TGPIO0
#define PAD_TGPIO0 84
#define GPIO_PAD_84 GPIO83
#ifndef BALL_Y3_IS_GPIO
#define BALL_Y3_IS_GPIO 0
#endif 
#ifndef PAD_TGPIO0_IS_GPIO
#define PAD_TGPIO0_IS_GPIO BALL_Y3_IS_GPIO
#endif 

#define BALL_T4 PAD_TGPIO1
#define PAD_TGPIO1 85
#define GPIO_PAD_85 GPIO84
#ifndef BALL_T4_IS_GPIO
#define BALL_T4_IS_GPIO 0
#endif 
#ifndef PAD_TGPIO1_IS_GPIO
#define PAD_TGPIO1_IS_GPIO BALL_T4_IS_GPIO
#endif 

#define BALL_W3 PAD_TGPIO2
#define PAD_TGPIO2 86
#define GPIO_PAD_86 GPIO85
#ifndef BALL_W3_IS_GPIO
#define BALL_W3_IS_GPIO 0
#endif 
#ifndef PAD_TGPIO2_IS_GPIO
#define PAD_TGPIO2_IS_GPIO BALL_W3_IS_GPIO
#endif 

#define BALL_Y1 PAD_TGPIO3
#define PAD_TGPIO3 87
#define GPIO_PAD_87 GPIO86
#ifndef BALL_Y1_IS_GPIO
#define BALL_Y1_IS_GPIO 0
#endif 
#ifndef PAD_TGPIO3_IS_GPIO
#define PAD_TGPIO3_IS_GPIO BALL_Y1_IS_GPIO
#endif 

#define BALL_W18 PAD_EMMC_IO0
#define PAD_EMMC_IO0 147
#define GPIO_PAD_147 GPIO146
#ifndef BALL_W18_IS_GPIO
#define BALL_W18_IS_GPIO 0
#endif 
#ifndef PAD_EMMC_IO0_IS_GPIO
#define PAD_EMMC_IO0_IS_GPIO BALL_W18_IS_GPIO
#endif 

#define BALL_AA19 PAD_EMMC_IO1
#define PAD_EMMC_IO1 148
#define GPIO_PAD_148 GPIO147
#ifndef BALL_AA19_IS_GPIO
#define BALL_AA19_IS_GPIO 0
#endif 
#ifndef PAD_EMMC_IO1_IS_GPIO
#define PAD_EMMC_IO1_IS_GPIO BALL_AA19_IS_GPIO
#endif 

#define BALL_Y19 PAD_EMMC_IO2
#define PAD_EMMC_IO2 149
#define GPIO_PAD_149 GPIO148
#ifndef BALL_Y19_IS_GPIO
#define BALL_Y19_IS_GPIO 0
#endif 
#ifndef PAD_EMMC_IO2_IS_GPIO
#define PAD_EMMC_IO2_IS_GPIO BALL_Y19_IS_GPIO
#endif 

#define BALL_AA18 PAD_EMMC_IO3
#define PAD_EMMC_IO3 150
#define GPIO_PAD_150 GPIO149
#ifndef BALL_AA18_IS_GPIO
#define BALL_AA18_IS_GPIO 0
#endif 
#ifndef PAD_EMMC_IO3_IS_GPIO
#define PAD_EMMC_IO3_IS_GPIO BALL_AA18_IS_GPIO
#endif 

#define BALL_Y18 PAD_EMMC_IO4
#define PAD_EMMC_IO4 151
#define GPIO_PAD_151 GPIO150
#ifndef BALL_Y18_IS_GPIO
#define BALL_Y18_IS_GPIO 0
#endif 
#ifndef PAD_EMMC_IO4_IS_GPIO
#define PAD_EMMC_IO4_IS_GPIO BALL_Y18_IS_GPIO
#endif 

#define BALL_W17 PAD_EMMC_IO5
#define PAD_EMMC_IO5 152
#define GPIO_PAD_152 GPIO151
#ifndef BALL_W17_IS_GPIO
#define BALL_W17_IS_GPIO 0
#endif 
#ifndef PAD_EMMC_IO5_IS_GPIO
#define PAD_EMMC_IO5_IS_GPIO BALL_W17_IS_GPIO
#endif 

#define BALL_V18 PAD_EMMC_IO6
#define PAD_EMMC_IO6 153
#define GPIO_PAD_153 GPIO152
#ifndef BALL_V18_IS_GPIO
#define BALL_V18_IS_GPIO 0
#endif 
#ifndef PAD_EMMC_IO6_IS_GPIO
#define PAD_EMMC_IO6_IS_GPIO BALL_V18_IS_GPIO
#endif 

#define BALL_Y20 PAD_EMMC_IO7
#define PAD_EMMC_IO7 154
#define GPIO_PAD_154 GPIO153
#ifndef BALL_Y20_IS_GPIO
#define BALL_Y20_IS_GPIO 0
#endif 
#ifndef PAD_EMMC_IO7_IS_GPIO
#define PAD_EMMC_IO7_IS_GPIO BALL_Y20_IS_GPIO
#endif 

#define PAD_EMMC_IO12 9999
#ifndef PAD_EMMC_IO12_IS_GPIO
#define PAD_EMMC_IO12_IS_GPIO 0
#endif 

#define PAD_EMMC_IO13 9999
#ifndef PAD_EMMC_IO13_IS_GPIO
#define PAD_EMMC_IO13_IS_GPIO 0
#endif 

#define BALL_Y17 PAD_EMMC_IO8
#define PAD_EMMC_IO8 155
#define GPIO_PAD_155 GPIO154
#ifndef BALL_Y17_IS_GPIO
#define BALL_Y17_IS_GPIO 0
#endif 
#ifndef PAD_EMMC_IO8_IS_GPIO
#define PAD_EMMC_IO8_IS_GPIO BALL_Y17_IS_GPIO
#endif 

#define PAD_EMMC_IO14 9999
#ifndef PAD_EMMC_IO14_IS_GPIO
#define PAD_EMMC_IO14_IS_GPIO 0
#endif 

#define BALL_W21 PAD_EMMC_IO9
#define PAD_EMMC_IO9 156
#define GPIO_PAD_156 GPIO155
#ifndef BALL_W21_IS_GPIO
#define BALL_W21_IS_GPIO 0
#endif 
#ifndef PAD_EMMC_IO9_IS_GPIO
#define PAD_EMMC_IO9_IS_GPIO BALL_W21_IS_GPIO
#endif 

#define PAD_EMMC_IO15 9999
#ifndef PAD_EMMC_IO15_IS_GPIO
#define PAD_EMMC_IO15_IS_GPIO 0
#endif 

#define BALL_W20 PAD_EMMC_IO10
#define PAD_EMMC_IO10 157
#define GPIO_PAD_157 GPIO156
#ifndef BALL_W20_IS_GPIO
#define BALL_W20_IS_GPIO 0
#endif 
#ifndef PAD_EMMC_IO10_IS_GPIO
#define PAD_EMMC_IO10_IS_GPIO BALL_W20_IS_GPIO
#endif 

#define PAD_EMMC_IO16 9999
#ifndef PAD_EMMC_IO16_IS_GPIO
#define PAD_EMMC_IO16_IS_GPIO 0
#endif 

#define BALL_Y21 PAD_EMMC_IO11
#define PAD_EMMC_IO11 158
#define GPIO_PAD_158 GPIO157
#ifndef BALL_Y21_IS_GPIO
#define BALL_Y21_IS_GPIO 0
#endif 
#ifndef PAD_EMMC_IO11_IS_GPIO
#define PAD_EMMC_IO11_IS_GPIO BALL_Y21_IS_GPIO
#endif 

#define PAD_EMMC_IO17 9999
#ifndef PAD_EMMC_IO17_IS_GPIO
#define PAD_EMMC_IO17_IS_GPIO 0
#endif 

#define PAD_TS2_VLD 9999
#ifndef PAD_TS2_VLD_IS_GPIO
#define PAD_TS2_VLD_IS_GPIO 0
#endif 

#define PAD_TS2_SYNC 9999
#ifndef PAD_TS2_SYNC_IS_GPIO
#define PAD_TS2_SYNC_IS_GPIO 0
#endif 

#define PAD_TS2_D0 9999
#ifndef PAD_TS2_D0_IS_GPIO
#define PAD_TS2_D0_IS_GPIO 0
#endif 

#define PAD_TS2_D1 9999
#ifndef PAD_TS2_D1_IS_GPIO
#define PAD_TS2_D1_IS_GPIO 0
#endif 

#define PAD_TS2_D2 9999
#ifndef PAD_TS2_D2_IS_GPIO
#define PAD_TS2_D2_IS_GPIO 0
#endif 

#define PAD_TS2_D5 9999
#ifndef PAD_TS2_D5_IS_GPIO
#define PAD_TS2_D5_IS_GPIO 0
#endif 

#define PAD_TS2_D3 9999
#ifndef PAD_TS2_D3_IS_GPIO
#define PAD_TS2_D3_IS_GPIO 0
#endif 

#define PAD_TS2_D6 9999
#ifndef PAD_TS2_D6_IS_GPIO
#define PAD_TS2_D6_IS_GPIO 0
#endif 

#define PAD_TS2_D4 9999
#ifndef PAD_TS2_D4_IS_GPIO
#define PAD_TS2_D4_IS_GPIO 0
#endif 

#define PAD_TS2_D7 9999
#ifndef PAD_TS2_D7_IS_GPIO
#define PAD_TS2_D7_IS_GPIO 0
#endif 

#define PAD_TS2_CLK 9999
#ifndef PAD_TS2_CLK_IS_GPIO
#define PAD_TS2_CLK_IS_GPIO 0
#endif 

#define BALL_W10 PAD_TS0_D6
#define PAD_TS0_D6 94
#define GPIO_PAD_94 GPIO93
#ifndef BALL_W10_IS_GPIO
#define BALL_W10_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D6_IS_GPIO
#define PAD_TS0_D6_IS_GPIO BALL_W10_IS_GPIO
#endif 

#define BALL_V10 PAD_TS0_D7
#define PAD_TS0_D7 95
#define GPIO_PAD_95 GPIO94
#ifndef BALL_V10_IS_GPIO
#define BALL_V10_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D7_IS_GPIO
#define PAD_TS0_D7_IS_GPIO BALL_V10_IS_GPIO
#endif 

#define BALL_Y11 PAD_TS0_SYNC
#define PAD_TS0_SYNC 97
#define GPIO_PAD_97 GPIO96
#ifndef BALL_Y11_IS_GPIO
#define BALL_Y11_IS_GPIO 0
#endif 
#ifndef PAD_TS0_SYNC_IS_GPIO
#define PAD_TS0_SYNC_IS_GPIO BALL_Y11_IS_GPIO
#endif 

#define BALL_U8 PAD_TS1_CLK
#define PAD_TS1_CLK 109
#define GPIO_PAD_109 GPIO108
#ifndef BALL_U8_IS_GPIO
#define BALL_U8_IS_GPIO 0
#endif 
#ifndef PAD_TS1_CLK_IS_GPIO
#define PAD_TS1_CLK_IS_GPIO BALL_U8_IS_GPIO
#endif 

#define BALL_W11 PAD_TS0_D0
#define PAD_TS0_D0 88
#define GPIO_PAD_88 GPIO87
#ifndef BALL_W11_IS_GPIO
#define BALL_W11_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D0_IS_GPIO
#define PAD_TS0_D0_IS_GPIO BALL_W11_IS_GPIO
#endif 

#define BALL_T10 PAD_TS1_SYNC
#define PAD_TS1_SYNC 108
#define GPIO_PAD_108 GPIO107
#ifndef BALL_T10_IS_GPIO
#define BALL_T10_IS_GPIO 0
#endif 
#ifndef PAD_TS1_SYNC_IS_GPIO
#define PAD_TS1_SYNC_IS_GPIO BALL_T10_IS_GPIO
#endif 

#define BALL_Y10 PAD_TS0_D1
#define PAD_TS0_D1 89
#define GPIO_PAD_89 GPIO88
#ifndef BALL_Y10_IS_GPIO
#define BALL_Y10_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D1_IS_GPIO
#define PAD_TS0_D1_IS_GPIO BALL_Y10_IS_GPIO
#endif 

#define BALL_R10 PAD_TS1_VLD
#define PAD_TS1_VLD 107
#define GPIO_PAD_107 GPIO106
#ifndef BALL_R10_IS_GPIO
#define BALL_R10_IS_GPIO 0
#endif 
#ifndef PAD_TS1_VLD_IS_GPIO
#define PAD_TS1_VLD_IS_GPIO BALL_R10_IS_GPIO
#endif 

#define BALL_W13 PAD_TS0_D2
#define PAD_TS0_D2 90
#define GPIO_PAD_90 GPIO89
#ifndef BALL_W13_IS_GPIO
#define BALL_W13_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D2_IS_GPIO
#define PAD_TS0_D2_IS_GPIO BALL_W13_IS_GPIO
#endif 

#define BALL_T9 PAD_TS1_D0
#define PAD_TS1_D0 99
#define GPIO_PAD_99 GPIO98
#ifndef BALL_T9_IS_GPIO
#define BALL_T9_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D0_IS_GPIO
#define PAD_TS1_D0_IS_GPIO BALL_T9_IS_GPIO
#endif 

#define BALL_Y12 PAD_TS0_D3
#define PAD_TS0_D3 91
#define GPIO_PAD_91 GPIO90
#ifndef BALL_Y12_IS_GPIO
#define BALL_Y12_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D3_IS_GPIO
#define PAD_TS0_D3_IS_GPIO BALL_Y12_IS_GPIO
#endif 

#define BALL_T8 PAD_TS1_D1
#define PAD_TS1_D1 100
#define GPIO_PAD_100 GPIO99
#ifndef BALL_T8_IS_GPIO
#define BALL_T8_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D1_IS_GPIO
#define PAD_TS1_D1_IS_GPIO BALL_T8_IS_GPIO
#endif 

#define BALL_W12 PAD_TS0_D4
#define PAD_TS0_D4 92
#define GPIO_PAD_92 GPIO91
#ifndef BALL_W12_IS_GPIO
#define BALL_W12_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D4_IS_GPIO
#define PAD_TS0_D4_IS_GPIO BALL_W12_IS_GPIO
#endif 

#define BALL_V9 PAD_TS1_D2
#define PAD_TS1_D2 101
#define GPIO_PAD_101 GPIO100
#ifndef BALL_V9_IS_GPIO
#define BALL_V9_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D2_IS_GPIO
#define PAD_TS1_D2_IS_GPIO BALL_V9_IS_GPIO
#endif 

#define BALL_Y13 PAD_TS0_D5
#define PAD_TS0_D5 93
#define GPIO_PAD_93 GPIO92
#ifndef BALL_Y13_IS_GPIO
#define BALL_Y13_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D5_IS_GPIO
#define PAD_TS0_D5_IS_GPIO BALL_Y13_IS_GPIO
#endif 

#define BALL_U7 PAD_TS1_D3
#define PAD_TS1_D3 102
#define GPIO_PAD_102 GPIO101
#ifndef BALL_U7_IS_GPIO
#define BALL_U7_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D3_IS_GPIO
#define PAD_TS1_D3_IS_GPIO BALL_U7_IS_GPIO
#endif 

#define BALL_AA12 PAD_TS0_CLK
#define PAD_TS0_CLK 98
#define GPIO_PAD_98 GPIO97
#ifndef BALL_AA12_IS_GPIO
#define BALL_AA12_IS_GPIO 0
#endif 
#ifndef PAD_TS0_CLK_IS_GPIO
#define PAD_TS0_CLK_IS_GPIO BALL_AA12_IS_GPIO
#endif 

#define BALL_U9 PAD_TS1_D4
#define PAD_TS1_D4 103
#define GPIO_PAD_103 GPIO102
#ifndef BALL_U9_IS_GPIO
#define BALL_U9_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D4_IS_GPIO
#define PAD_TS1_D4_IS_GPIO BALL_U9_IS_GPIO
#endif 

#define BALL_AA13 PAD_TS0_VLD
#define PAD_TS0_VLD 96
#define GPIO_PAD_96 GPIO95
#ifndef BALL_AA13_IS_GPIO
#define BALL_AA13_IS_GPIO 0
#endif 
#ifndef PAD_TS0_VLD_IS_GPIO
#define PAD_TS0_VLD_IS_GPIO BALL_AA13_IS_GPIO
#endif 

#define BALL_V7 PAD_TS1_D5
#define PAD_TS1_D5 104
#define GPIO_PAD_104 GPIO103
#ifndef BALL_V7_IS_GPIO
#define BALL_V7_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D5_IS_GPIO
#define PAD_TS1_D5_IS_GPIO BALL_V7_IS_GPIO
#endif 

#define BALL_U10 PAD_TS1_D6
#define PAD_TS1_D6 105
#define GPIO_PAD_105 GPIO104
#ifndef BALL_U10_IS_GPIO
#define BALL_U10_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D6_IS_GPIO
#define PAD_TS1_D6_IS_GPIO BALL_U10_IS_GPIO
#endif 

#define BALL_V8 PAD_TS1_D7
#define PAD_TS1_D7 106
#define GPIO_PAD_106 GPIO105
#ifndef BALL_V8_IS_GPIO
#define BALL_V8_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D7_IS_GPIO
#define PAD_TS1_D7_IS_GPIO BALL_V8_IS_GPIO
#endif 

#define BALL_V12 PAD_PCM_A0
#define PAD_PCM_A0 136
#define GPIO_PAD_136 GPIO135
#ifndef BALL_V12_IS_GPIO
#define BALL_V12_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A0_IS_GPIO
#define PAD_PCM_A0_IS_GPIO BALL_V12_IS_GPIO
#endif 

#define BALL_U11 PAD_PCM_WAIT_N
#define PAD_PCM_WAIT_N 111
#define GPIO_PAD_111 GPIO110
#ifndef BALL_U11_IS_GPIO
#define BALL_U11_IS_GPIO 0
#endif 
#ifndef PAD_PCM_WAIT_N_IS_GPIO
#define PAD_PCM_WAIT_N_IS_GPIO BALL_U11_IS_GPIO
#endif 

#define BALL_T17 PAD_PCM_A1
#define PAD_PCM_A1 135
#define GPIO_PAD_135 GPIO134
#ifndef BALL_T17_IS_GPIO
#define BALL_T17_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A1_IS_GPIO
#define PAD_PCM_A1_IS_GPIO BALL_T17_IS_GPIO
#endif 

#define BALL_U12 PAD_PCM_IRQA_N
#define PAD_PCM_IRQA_N 116
#define GPIO_PAD_116 GPIO115
#ifndef BALL_U12_IS_GPIO
#define BALL_U12_IS_GPIO 0
#endif 
#ifndef PAD_PCM_IRQA_N_IS_GPIO
#define PAD_PCM_IRQA_N_IS_GPIO BALL_U12_IS_GPIO
#endif 

#define BALL_AA16 PAD_PCM_A2
#define PAD_PCM_A2 133
#define GPIO_PAD_133 GPIO132
#ifndef BALL_AA16_IS_GPIO
#define BALL_AA16_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A2_IS_GPIO
#define PAD_PCM_A2_IS_GPIO BALL_AA16_IS_GPIO
#endif 

#define BALL_V17 PAD_PCM_D3
#define PAD_PCM_D3 131
#define GPIO_PAD_131 GPIO130
#ifndef BALL_V17_IS_GPIO
#define BALL_V17_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D3_IS_GPIO
#define PAD_PCM_D3_IS_GPIO BALL_V17_IS_GPIO
#endif 

#define BALL_V13 PAD_PCM_A12
#define PAD_PCM_A12 115
#define GPIO_PAD_115 GPIO114
#ifndef BALL_V13_IS_GPIO
#define BALL_V13_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A12_IS_GPIO
#define PAD_PCM_A12_IS_GPIO BALL_V13_IS_GPIO
#endif 

#define BALL_U17 PAD_PCM_D4
#define PAD_PCM_D4 130
#define GPIO_PAD_130 GPIO129
#ifndef BALL_U17_IS_GPIO
#define BALL_U17_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D4_IS_GPIO
#define PAD_PCM_D4_IS_GPIO BALL_U17_IS_GPIO
#endif 

#define BALL_T16 PAD_PCM_A3
#define PAD_PCM_A3 132
#define GPIO_PAD_132 GPIO131
#ifndef BALL_T16_IS_GPIO
#define BALL_T16_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A3_IS_GPIO
#define PAD_PCM_A3_IS_GPIO BALL_T16_IS_GPIO
#endif 

#define BALL_U18 PAD_PCM_D6
#define PAD_PCM_D6 128
#define GPIO_PAD_128 GPIO127
#ifndef BALL_U18_IS_GPIO
#define BALL_U18_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D6_IS_GPIO
#define PAD_PCM_D6_IS_GPIO BALL_U18_IS_GPIO
#endif 

#define BALL_R15 PAD_PCM_A4
#define PAD_PCM_A4 110
#define GPIO_PAD_110 GPIO109
#ifndef BALL_R15_IS_GPIO
#define BALL_R15_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A4_IS_GPIO
#define PAD_PCM_A4_IS_GPIO BALL_R15_IS_GPIO
#endif 

#define BALL_U16 PAD_PCM_A10
#define PAD_PCM_A10 125
#define GPIO_PAD_125 GPIO124
#ifndef BALL_U16_IS_GPIO
#define BALL_U16_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A10_IS_GPIO
#define PAD_PCM_A10_IS_GPIO BALL_U16_IS_GPIO
#endif 

#define PAD_PCM2_CD_N 9999
#ifndef PAD_PCM2_CD_N_IS_GPIO
#define PAD_PCM2_CD_N_IS_GPIO 0
#endif 

#define BALL_W14 PAD_PCM_IOWR_N
#define PAD_PCM_IOWR_N 120
#define GPIO_PAD_120 GPIO119
#ifndef BALL_W14_IS_GPIO
#define BALL_W14_IS_GPIO 0
#endif 
#ifndef PAD_PCM_IOWR_N_IS_GPIO
#define PAD_PCM_IOWR_N_IS_GPIO BALL_W14_IS_GPIO
#endif 

#define BALL_U13 PAD_PCM_A5
#define PAD_PCM_A5 112
#define GPIO_PAD_112 GPIO111
#ifndef BALL_U13_IS_GPIO
#define BALL_U13_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A5_IS_GPIO
#define PAD_PCM_A5_IS_GPIO BALL_U13_IS_GPIO
#endif 

#define BALL_T15 PAD_PCM_OE_N
#define PAD_PCM_OE_N 124
#define GPIO_PAD_124 GPIO123
#ifndef BALL_T15_IS_GPIO
#define BALL_T15_IS_GPIO 0
#endif 
#ifndef PAD_PCM_OE_N_IS_GPIO
#define PAD_PCM_OE_N_IS_GPIO BALL_T15_IS_GPIO
#endif 

#define BALL_Y16 PAD_PCM_CD_N
#define PAD_PCM_CD_N 141
#define GPIO_PAD_141 GPIO140
#ifndef BALL_Y16_IS_GPIO
#define BALL_Y16_IS_GPIO 0
#endif 
#ifndef PAD_PCM_CD_N_IS_GPIO
#define PAD_PCM_CD_N_IS_GPIO BALL_Y16_IS_GPIO
#endif 

#define BALL_R16 PAD_PCM_D2
#define PAD_PCM_D2 139
#define GPIO_PAD_139 GPIO138
#ifndef BALL_R16_IS_GPIO
#define BALL_R16_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D2_IS_GPIO
#define PAD_PCM_D2_IS_GPIO BALL_R16_IS_GPIO
#endif 

#define BALL_R17 PAD_PCM_A6
#define PAD_PCM_A6 113
#define GPIO_PAD_113 GPIO112
#ifndef BALL_R17_IS_GPIO
#define BALL_R17_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A6_IS_GPIO
#define PAD_PCM_A6_IS_GPIO BALL_R17_IS_GPIO
#endif 

#define BALL_AA15 PAD_PCM_D5
#define PAD_PCM_D5 129
#define GPIO_PAD_129 GPIO128
#ifndef BALL_AA15_IS_GPIO
#define BALL_AA15_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D5_IS_GPIO
#define PAD_PCM_D5_IS_GPIO BALL_AA15_IS_GPIO
#endif 

#define PAD_PCM2_WAIT_N 9999
#ifndef PAD_PCM2_WAIT_N_IS_GPIO
#define PAD_PCM2_WAIT_N_IS_GPIO 0
#endif 

#define BALL_T11 PAD_PCM_A7
#define PAD_PCM_A7 114
#define GPIO_PAD_114 GPIO113
#ifndef BALL_T11_IS_GPIO
#define BALL_T11_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A7_IS_GPIO
#define PAD_PCM_A7_IS_GPIO BALL_T11_IS_GPIO
#endif 

#define BALL_T12 PAD_PCM_D7
#define PAD_PCM_D7 127
#define GPIO_PAD_127 GPIO126
#ifndef BALL_T12_IS_GPIO
#define BALL_T12_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D7_IS_GPIO
#define PAD_PCM_D7_IS_GPIO BALL_T12_IS_GPIO
#endif 

#define BALL_T13 PAD_PCM_A8
#define PAD_PCM_A8 119
#define GPIO_PAD_119 GPIO118
#ifndef BALL_T13_IS_GPIO
#define BALL_T13_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A8_IS_GPIO
#define PAD_PCM_A8_IS_GPIO BALL_T13_IS_GPIO
#endif 

#define BALL_T18 PAD_PCM_CE_N
#define PAD_PCM_CE_N 126
#define GPIO_PAD_126 GPIO125
#ifndef BALL_T18_IS_GPIO
#define BALL_T18_IS_GPIO 0
#endif 
#ifndef PAD_PCM_CE_N_IS_GPIO
#define PAD_PCM_CE_N_IS_GPIO BALL_T18_IS_GPIO
#endif 

#define BALL_T14 PAD_PCM_A9
#define PAD_PCM_A9 121
#define GPIO_PAD_121 GPIO120
#ifndef BALL_T14_IS_GPIO
#define BALL_T14_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A9_IS_GPIO
#define PAD_PCM_A9_IS_GPIO BALL_T14_IS_GPIO
#endif 

#define BALL_Y14 PAD_PCM_A11
#define PAD_PCM_A11 123
#define GPIO_PAD_123 GPIO122
#ifndef BALL_Y14_IS_GPIO
#define BALL_Y14_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A11_IS_GPIO
#define PAD_PCM_A11_IS_GPIO BALL_Y14_IS_GPIO
#endif 

#define BALL_U14 PAD_PCM_REG_N
#define PAD_PCM_REG_N 134
#define GPIO_PAD_134 GPIO133
#ifndef BALL_U14_IS_GPIO
#define BALL_U14_IS_GPIO 0
#endif 
#ifndef PAD_PCM_REG_N_IS_GPIO
#define PAD_PCM_REG_N_IS_GPIO BALL_U14_IS_GPIO
#endif 

#define BALL_W16 PAD_PCM_IORD_N
#define PAD_PCM_IORD_N 122
#define GPIO_PAD_122 GPIO121
#ifndef BALL_W16_IS_GPIO
#define BALL_W16_IS_GPIO 0
#endif 
#ifndef PAD_PCM_IORD_N_IS_GPIO
#define PAD_PCM_IORD_N_IS_GPIO BALL_W16_IS_GPIO
#endif 

#define BALL_U15 PAD_PCM_WE_N
#define PAD_PCM_WE_N 206
#define GPIO_PAD_206 GPIO205
#ifndef BALL_U15_IS_GPIO
#define BALL_U15_IS_GPIO 0
#endif 
#ifndef PAD_PCM_WE_N_IS_GPIO
#define PAD_PCM_WE_N_IS_GPIO BALL_U15_IS_GPIO
#endif 

#define PAD_PCM2_IRQA_N 9999
#ifndef PAD_PCM2_IRQA_N_IS_GPIO
#define PAD_PCM2_IRQA_N_IS_GPIO 0
#endif 

#define BALL_Y15 PAD_PCM_RESET
#define PAD_PCM_RESET 140
#define GPIO_PAD_140 GPIO139
#ifndef BALL_Y15_IS_GPIO
#define BALL_Y15_IS_GPIO 0
#endif 
#ifndef PAD_PCM_RESET_IS_GPIO
#define PAD_PCM_RESET_IS_GPIO BALL_Y15_IS_GPIO
#endif 

#define PAD_PCM2_RESET 9999
#ifndef PAD_PCM2_RESET_IS_GPIO
#define PAD_PCM2_RESET_IS_GPIO 0
#endif 

#define BALL_V15 PAD_PCM_D0
#define PAD_PCM_D0 137
#define GPIO_PAD_137 GPIO136
#ifndef BALL_V15_IS_GPIO
#define BALL_V15_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D0_IS_GPIO
#define PAD_PCM_D0_IS_GPIO BALL_V15_IS_GPIO
#endif 

#define BALL_W15 PAD_PCM_A13
#define PAD_PCM_A13 118
#define GPIO_PAD_118 GPIO117
#ifndef BALL_W15_IS_GPIO
#define BALL_W15_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A13_IS_GPIO
#define PAD_PCM_A13_IS_GPIO BALL_W15_IS_GPIO
#endif 

#define BALL_V16 PAD_PCM_D1
#define PAD_PCM_D1 138
#define GPIO_PAD_138 GPIO137
#ifndef BALL_V16_IS_GPIO
#define BALL_V16_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D1_IS_GPIO
#define PAD_PCM_D1_IS_GPIO BALL_V16_IS_GPIO
#endif 

#define BALL_R14 PAD_PCM_A14
#define PAD_PCM_A14 117
#define GPIO_PAD_117 GPIO116
#ifndef BALL_R14_IS_GPIO
#define BALL_R14_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A14_IS_GPIO
#define PAD_PCM_A14_IS_GPIO BALL_R14_IS_GPIO
#endif 

#define PAD_PCM2_CE_N 9999
#ifndef PAD_PCM2_CE_N_IS_GPIO
#define PAD_PCM2_CE_N_IS_GPIO 0
#endif 

#define BALL_V21 PAD_B_ODD0
#define PAD_B_ODD0 178
#define GPIO_PAD_178 GPIO177
#ifndef BALL_V21_IS_GPIO
#define BALL_V21_IS_GPIO 0
#endif 
#ifndef PAD_B_ODD0_IS_GPIO
#define PAD_B_ODD0_IS_GPIO BALL_V21_IS_GPIO
#endif 

#define BALL_W19 PAD_B_ODD1
#define PAD_B_ODD1 179
#define GPIO_PAD_179 GPIO178
#ifndef BALL_W19_IS_GPIO
#define BALL_W19_IS_GPIO 0
#endif 
#ifndef PAD_B_ODD1_IS_GPIO
#define PAD_B_ODD1_IS_GPIO BALL_W19_IS_GPIO
#endif 

#define BALL_V19 PAD_B_ODD2
#define PAD_B_ODD2 180
#define GPIO_PAD_180 GPIO179
#ifndef BALL_V19_IS_GPIO
#define BALL_V19_IS_GPIO 0
#endif 
#ifndef PAD_B_ODD2_IS_GPIO
#define PAD_B_ODD2_IS_GPIO BALL_V19_IS_GPIO
#endif 

#define BALL_V20 PAD_B_ODD3
#define PAD_B_ODD3 181
#define GPIO_PAD_181 GPIO180
#ifndef BALL_V20_IS_GPIO
#define BALL_V20_IS_GPIO 0
#endif 
#ifndef PAD_B_ODD3_IS_GPIO
#define PAD_B_ODD3_IS_GPIO BALL_V20_IS_GPIO
#endif 

#define BALL_U19 PAD_B_ODD4
#define PAD_B_ODD4 182
#define GPIO_PAD_182 GPIO181
#ifndef BALL_U19_IS_GPIO
#define BALL_U19_IS_GPIO 0
#endif 
#ifndef PAD_B_ODD4_IS_GPIO
#define PAD_B_ODD4_IS_GPIO BALL_U19_IS_GPIO
#endif 

#define BALL_U20 PAD_B_ODD5
#define PAD_B_ODD5 183
#define GPIO_PAD_183 GPIO182
#ifndef BALL_U20_IS_GPIO
#define BALL_U20_IS_GPIO 0
#endif 
#ifndef PAD_B_ODD5_IS_GPIO
#define PAD_B_ODD5_IS_GPIO BALL_U20_IS_GPIO
#endif 

#define BALL_T21 PAD_B_ODD6
#define PAD_B_ODD6 184
#define GPIO_PAD_184 GPIO183
#ifndef BALL_T21_IS_GPIO
#define BALL_T21_IS_GPIO 0
#endif 
#ifndef PAD_B_ODD6_IS_GPIO
#define PAD_B_ODD6_IS_GPIO BALL_T21_IS_GPIO
#endif 

#define BALL_T20 PAD_B_ODD7
#define PAD_B_ODD7 185
#define GPIO_PAD_185 GPIO184
#ifndef BALL_T20_IS_GPIO
#define BALL_T20_IS_GPIO 0
#endif 
#ifndef PAD_B_ODD7_IS_GPIO
#define PAD_B_ODD7_IS_GPIO BALL_T20_IS_GPIO
#endif 

#define BALL_R21 PAD_G_ODD0
#define PAD_G_ODD0 186
#define GPIO_PAD_186 GPIO185
#ifndef BALL_R21_IS_GPIO
#define BALL_R21_IS_GPIO 0
#endif 
#ifndef PAD_G_ODD0_IS_GPIO
#define PAD_G_ODD0_IS_GPIO BALL_R21_IS_GPIO
#endif 

#define BALL_T19 PAD_G_ODD1
#define PAD_G_ODD1 187
#define GPIO_PAD_187 GPIO186
#ifndef BALL_T19_IS_GPIO
#define BALL_T19_IS_GPIO 0
#endif 
#ifndef PAD_G_ODD1_IS_GPIO
#define PAD_G_ODD1_IS_GPIO BALL_T19_IS_GPIO
#endif 

#define BALL_R19 PAD_G_ODD2
#define PAD_G_ODD2 188
#define GPIO_PAD_188 GPIO187
#ifndef BALL_R19_IS_GPIO
#define BALL_R19_IS_GPIO 0
#endif 
#ifndef PAD_G_ODD2_IS_GPIO
#define PAD_G_ODD2_IS_GPIO BALL_R19_IS_GPIO
#endif 

#define BALL_R20 PAD_G_ODD3
#define PAD_G_ODD3 189
#define GPIO_PAD_189 GPIO188
#ifndef BALL_R20_IS_GPIO
#define BALL_R20_IS_GPIO 0
#endif 
#ifndef PAD_G_ODD3_IS_GPIO
#define PAD_G_ODD3_IS_GPIO BALL_R20_IS_GPIO
#endif 

#define BALL_P19 PAD_G_ODD4
#define PAD_G_ODD4 190
#define GPIO_PAD_190 GPIO189
#ifndef BALL_P19_IS_GPIO
#define BALL_P19_IS_GPIO 0
#endif 
#ifndef PAD_G_ODD4_IS_GPIO
#define PAD_G_ODD4_IS_GPIO BALL_P19_IS_GPIO
#endif 

#define BALL_P20 PAD_G_ODD5
#define PAD_G_ODD5 191
#define GPIO_PAD_191 GPIO190
#ifndef BALL_P20_IS_GPIO
#define BALL_P20_IS_GPIO 0
#endif 
#ifndef PAD_G_ODD5_IS_GPIO
#define PAD_G_ODD5_IS_GPIO BALL_P20_IS_GPIO
#endif 

#define BALL_N21 PAD_G_ODD6
#define PAD_G_ODD6 192
#define GPIO_PAD_192 GPIO191
#ifndef BALL_N21_IS_GPIO
#define BALL_N21_IS_GPIO 0
#endif 
#ifndef PAD_G_ODD6_IS_GPIO
#define PAD_G_ODD6_IS_GPIO BALL_N21_IS_GPIO
#endif 

#define BALL_N20 PAD_G_ODD7
#define PAD_G_ODD7 193
#define GPIO_PAD_193 GPIO192
#ifndef BALL_N20_IS_GPIO
#define BALL_N20_IS_GPIO 0
#endif 
#ifndef PAD_G_ODD7_IS_GPIO
#define PAD_G_ODD7_IS_GPIO BALL_N20_IS_GPIO
#endif 

#define BALL_M21 PAD_R_ODD0
#define PAD_R_ODD0 194
#define GPIO_PAD_194 GPIO193
#ifndef BALL_M21_IS_GPIO
#define BALL_M21_IS_GPIO 0
#endif 
#ifndef PAD_R_ODD0_IS_GPIO
#define PAD_R_ODD0_IS_GPIO BALL_M21_IS_GPIO
#endif 

#define BALL_N19 PAD_R_ODD1
#define PAD_R_ODD1 195
#define GPIO_PAD_195 GPIO194
#ifndef BALL_N19_IS_GPIO
#define BALL_N19_IS_GPIO 0
#endif 
#ifndef PAD_R_ODD1_IS_GPIO
#define PAD_R_ODD1_IS_GPIO BALL_N19_IS_GPIO
#endif 

#define BALL_M19 PAD_R_ODD2
#define PAD_R_ODD2 196
#define GPIO_PAD_196 GPIO195
#ifndef BALL_M19_IS_GPIO
#define BALL_M19_IS_GPIO 0
#endif 
#ifndef PAD_R_ODD2_IS_GPIO
#define PAD_R_ODD2_IS_GPIO BALL_M19_IS_GPIO
#endif 

#define BALL_M20 PAD_R_ODD3
#define PAD_R_ODD3 197
#define GPIO_PAD_197 GPIO196
#ifndef BALL_M20_IS_GPIO
#define BALL_M20_IS_GPIO 0
#endif 
#ifndef PAD_R_ODD3_IS_GPIO
#define PAD_R_ODD3_IS_GPIO BALL_M20_IS_GPIO
#endif 

#define BALL_L19 PAD_R_ODD4
#define PAD_R_ODD4 198
#define GPIO_PAD_198 GPIO197
#ifndef BALL_L19_IS_GPIO
#define BALL_L19_IS_GPIO 0
#endif 
#ifndef PAD_R_ODD4_IS_GPIO
#define PAD_R_ODD4_IS_GPIO BALL_L19_IS_GPIO
#endif 

#define BALL_L20 PAD_R_ODD5
#define PAD_R_ODD5 199
#define GPIO_PAD_199 GPIO198
#ifndef BALL_L20_IS_GPIO
#define BALL_L20_IS_GPIO 0
#endif 
#ifndef PAD_R_ODD5_IS_GPIO
#define PAD_R_ODD5_IS_GPIO BALL_L20_IS_GPIO
#endif 

#define BALL_K21 PAD_R_ODD6
#define PAD_R_ODD6 200
#define GPIO_PAD_200 GPIO199
#ifndef BALL_K21_IS_GPIO
#define BALL_K21_IS_GPIO 0
#endif 
#ifndef PAD_R_ODD6_IS_GPIO
#define PAD_R_ODD6_IS_GPIO BALL_K21_IS_GPIO
#endif 

#define BALL_K20 PAD_R_ODD7
#define PAD_R_ODD7 201
#define GPIO_PAD_201 GPIO200
#ifndef BALL_K20_IS_GPIO
#define BALL_K20_IS_GPIO 0
#endif 
#ifndef PAD_R_ODD7_IS_GPIO
#define PAD_R_ODD7_IS_GPIO BALL_K20_IS_GPIO
#endif 

#define PAD_LCK 9999
#ifndef PAD_LCK_IS_GPIO
#define PAD_LCK_IS_GPIO 0
#endif 

#define PAD_LDE 9999
#ifndef PAD_LDE_IS_GPIO
#define PAD_LDE_IS_GPIO 0
#endif 

#define PAD_LHSYNC 9999
#ifndef PAD_LHSYNC_IS_GPIO
#define PAD_LHSYNC_IS_GPIO 0
#endif 

#define PAD_LVSYNC 9999
#ifndef PAD_LVSYNC_IS_GPIO
#define PAD_LVSYNC_IS_GPIO 0
#endif 

#define PAD_GPIO11 9999
#ifndef PAD_GPIO11_IS_GPIO
#define PAD_GPIO11_IS_GPIO 0
#endif 

#define PAD_TCON7 9999
#ifndef PAD_TCON7_IS_GPIO
#define PAD_TCON7_IS_GPIO 0
#endif 

#define PAD_GPIO10 9999
#ifndef PAD_GPIO10_IS_GPIO
#define PAD_GPIO10_IS_GPIO 0
#endif 

#define PAD_TCON6 9999
#ifndef PAD_TCON6_IS_GPIO
#define PAD_TCON6_IS_GPIO 0
#endif 

#define PAD_GPIO9 9999
#ifndef PAD_GPIO9_IS_GPIO
#define PAD_GPIO9_IS_GPIO 0
#endif 

#define BALL_T1 PAD_TCON5
#define PAD_TCON5 216
#define GPIO_PAD_216 GPIO215
#ifndef BALL_T1_IS_GPIO
#define BALL_T1_IS_GPIO 0
#endif 
#ifndef PAD_TCON5_IS_GPIO
#define PAD_TCON5_IS_GPIO BALL_T1_IS_GPIO
#endif 

#define PAD_I2S_IN_SD 9999
#ifndef PAD_I2S_IN_SD_IS_GPIO
#define PAD_I2S_IN_SD_IS_GPIO 0
#endif 

#define BALL_T3 PAD_TCON4
#define PAD_TCON4 215
#define GPIO_PAD_215 GPIO214
#ifndef BALL_T3_IS_GPIO
#define BALL_T3_IS_GPIO 0
#endif 
#ifndef PAD_TCON4_IS_GPIO
#define PAD_TCON4_IS_GPIO BALL_T3_IS_GPIO
#endif 

#define PAD_TCON3 9999
#ifndef PAD_TCON3_IS_GPIO
#define PAD_TCON3_IS_GPIO 0
#endif 

#define PAD_I2S_IN_BCK 9999
#ifndef PAD_I2S_IN_BCK_IS_GPIO
#define PAD_I2S_IN_BCK_IS_GPIO 0
#endif 

#define PAD_TCON2 9999
#ifndef PAD_TCON2_IS_GPIO
#define PAD_TCON2_IS_GPIO 0
#endif 

#define PAD_VSYNC_LIKE 9999
#ifndef PAD_VSYNC_LIKE_IS_GPIO
#define PAD_VSYNC_LIKE_IS_GPIO 0
#endif 

#define PAD_TCON1 9999
#ifndef PAD_TCON1_IS_GPIO
#define PAD_TCON1_IS_GPIO 0
#endif 

#define BALL_G20 PAD_PWM2
#define PAD_PWM2 79
#define GPIO_PAD_79 GPIO78
#ifndef BALL_G20_IS_GPIO
#define BALL_G20_IS_GPIO 0
#endif 
#ifndef PAD_PWM2_IS_GPIO
#define PAD_PWM2_IS_GPIO BALL_G20_IS_GPIO
#endif 

#define PAD_TCON0 9999
#ifndef PAD_TCON0_IS_GPIO
#define PAD_TCON0_IS_GPIO 0
#endif 

#define BALL_H16 PAD_UART_TX2
#define PAD_UART_TX2 76
#define GPIO_PAD_76 GPIO75
#ifndef BALL_H16_IS_GPIO
#define BALL_H16_IS_GPIO 0
#endif 
#ifndef PAD_UART_TX2_IS_GPIO
#define PAD_UART_TX2_IS_GPIO BALL_H16_IS_GPIO
#endif 

#define BALL_H17 PAD_UART_RX2
#define PAD_UART_RX2 75
#define GPIO_PAD_75 GPIO74
#ifndef BALL_H17_IS_GPIO
#define BALL_H17_IS_GPIO 0
#endif 
#ifndef PAD_UART_RX2_IS_GPIO
#define PAD_UART_RX2_IS_GPIO BALL_H17_IS_GPIO
#endif 

#define BALL_J7 PAD_I2S_IN_WS
#define PAD_I2S_IN_WS 166
#define GPIO_PAD_166 GPIO165
#ifndef BALL_J7_IS_GPIO
#define BALL_J7_IS_GPIO 0
#endif 
#ifndef PAD_I2S_IN_WS_IS_GPIO
#define PAD_I2S_IN_WS_IS_GPIO BALL_J7_IS_GPIO
#endif 

#define BALL_N8 PAD_SPI2_DI
#define PAD_SPI2_DI 210
#define GPIO_PAD_210 GPIO209
#ifndef BALL_N8_IS_GPIO
#define BALL_N8_IS_GPIO 0
#endif 
#ifndef PAD_SPI2_DI_IS_GPIO
#define PAD_SPI2_DI_IS_GPIO BALL_N8_IS_GPIO
#endif 

#define PAD_GPIO26 9999
#ifndef PAD_GPIO26_IS_GPIO
#define PAD_GPIO26_IS_GPIO 0
#endif 

#define BALL_M4 PAD_SPI2_CK
#define PAD_SPI2_CK 209
#define GPIO_PAD_209 GPIO208
#ifndef BALL_M4_IS_GPIO
#define BALL_M4_IS_GPIO 0
#endif 
#ifndef PAD_SPI2_CK_IS_GPIO
#define PAD_SPI2_CK_IS_GPIO BALL_M4_IS_GPIO
#endif 

#define PAD_PWM4 9999
#ifndef PAD_PWM4_IS_GPIO
#define PAD_PWM4_IS_GPIO 0
#endif 

#define BALL_N4 PAD_SPI1_DI
#define PAD_SPI1_DI 208
#define GPIO_PAD_208 GPIO207
#ifndef BALL_N4_IS_GPIO
#define BALL_N4_IS_GPIO 0
#endif 
#ifndef PAD_SPI1_DI_IS_GPIO
#define PAD_SPI1_DI_IS_GPIO BALL_N4_IS_GPIO
#endif 

#define PAD_PWM3 9999
#ifndef PAD_PWM3_IS_GPIO
#define PAD_PWM3_IS_GPIO 0
#endif 

#define BALL_M8 PAD_SPI1_CK
#define PAD_SPI1_CK 207
#define GPIO_PAD_207 GPIO206
#ifndef BALL_M8_IS_GPIO
#define BALL_M8_IS_GPIO 0
#endif 
#ifndef PAD_SPI1_CK_IS_GPIO
#define PAD_SPI1_CK_IS_GPIO BALL_M8_IS_GPIO
#endif 

#define BALL_G21 PAD_PWM0
#define PAD_PWM0 77
#define GPIO_PAD_77 GPIO76
#ifndef BALL_G21_IS_GPIO
#define BALL_G21_IS_GPIO 0
#endif 
#ifndef PAD_PWM0_IS_GPIO
#define PAD_PWM0_IS_GPIO BALL_G21_IS_GPIO
#endif 

#define BALL_G19 PAD_PWM1
#define PAD_PWM1 78
#define GPIO_PAD_78 GPIO77
#ifndef BALL_G19_IS_GPIO
#define BALL_G19_IS_GPIO 0
#endif 
#ifndef PAD_PWM1_IS_GPIO
#define PAD_PWM1_IS_GPIO BALL_G19_IS_GPIO
#endif 

#define PAD_GPIO15 9999
#ifndef PAD_GPIO15_IS_GPIO
#define PAD_GPIO15_IS_GPIO 0
#endif 

#define PAD_GPIO16 9999
#ifndef PAD_GPIO16_IS_GPIO
#define PAD_GPIO16_IS_GPIO 0
#endif 

#define PAD_GPIO17 9999
#ifndef PAD_GPIO17_IS_GPIO
#define PAD_GPIO17_IS_GPIO 0
#endif 

#define PAD_GPIO18 9999
#ifndef PAD_GPIO18_IS_GPIO
#define PAD_GPIO18_IS_GPIO 0
#endif 

#define PAD_I2S_OUT_SD1 9999
#ifndef PAD_I2S_OUT_SD1_IS_GPIO
#define PAD_I2S_OUT_SD1_IS_GPIO 0
#endif 

#define PAD_GPIO22 9999
#ifndef PAD_GPIO22_IS_GPIO
#define PAD_GPIO22_IS_GPIO 0
#endif 

#define PAD_I2S_OUT_SD2 9999
#ifndef PAD_I2S_OUT_SD2_IS_GPIO
#define PAD_I2S_OUT_SD2_IS_GPIO 0
#endif 

#define PAD_GPIO25 9999
#ifndef PAD_GPIO25_IS_GPIO
#define PAD_GPIO25_IS_GPIO 0
#endif 

#define PAD_I2S_OUT_SD3 9999
#ifndef PAD_I2S_OUT_SD3_IS_GPIO
#define PAD_I2S_OUT_SD3_IS_GPIO 0
#endif 

#define BALL_C7 PAD_GPIO19
#define PAD_GPIO19 66
#define GPIO_PAD_66 GPIO65
#ifndef BALL_C7_IS_GPIO
#define BALL_C7_IS_GPIO 0
#endif 
#ifndef PAD_GPIO19_IS_GPIO
#define PAD_GPIO19_IS_GPIO BALL_C7_IS_GPIO
#endif 

#define BALL_P18 PAD_SPDIF_IN
#define PAD_SPDIF_IN 169
#define GPIO_PAD_169 GPIO168
#ifndef BALL_P18_IS_GPIO
#define BALL_P18_IS_GPIO 0
#endif 
#ifndef PAD_SPDIF_IN_IS_GPIO
#define PAD_SPDIF_IN_IS_GPIO BALL_P18_IS_GPIO
#endif 

#define PAD_GPIO14 9999
#ifndef PAD_GPIO14_IS_GPIO
#define PAD_GPIO14_IS_GPIO 0
#endif 

#define PAD_GPIO4 9999
#ifndef PAD_GPIO4_IS_GPIO
#define PAD_GPIO4_IS_GPIO 0
#endif 

#define PAD_GPIO0 9999
#ifndef PAD_GPIO0_IS_GPIO
#define PAD_GPIO0_IS_GPIO 0
#endif 

#define PAD_GPIO5 9999
#ifndef PAD_GPIO5_IS_GPIO
#define PAD_GPIO5_IS_GPIO 0
#endif 

#define PAD_GPIO1 9999
#ifndef PAD_GPIO1_IS_GPIO
#define PAD_GPIO1_IS_GPIO 0
#endif 

#define PAD_GPIO6 9999
#ifndef PAD_GPIO6_IS_GPIO
#define PAD_GPIO6_IS_GPIO 0
#endif 

#define PAD_GPIO2 9999
#ifndef PAD_GPIO2_IS_GPIO
#define PAD_GPIO2_IS_GPIO 0
#endif 

#define PAD_GPIO7 9999
#ifndef PAD_GPIO7_IS_GPIO
#define PAD_GPIO7_IS_GPIO 0
#endif 

#define PAD_GPIO3 9999
#ifndef PAD_GPIO3_IS_GPIO
#define PAD_GPIO3_IS_GPIO 0
#endif 

#define PAD_GPIO8 9999
#ifndef PAD_GPIO8_IS_GPIO
#define PAD_GPIO8_IS_GPIO 0
#endif 

#define BALL_P16 PAD_DDCR_DA
#define PAD_DDCR_DA 82
#define GPIO_PAD_82 GPIO81
#ifndef BALL_P16_IS_GPIO
#define BALL_P16_IS_GPIO 0
#endif 
#ifndef PAD_DDCR_DA_IS_GPIO
#define PAD_DDCR_DA_IS_GPIO BALL_P16_IS_GPIO
#endif 

#define PAD_GPIO27 9999
#ifndef PAD_GPIO27_IS_GPIO
#define PAD_GPIO27_IS_GPIO 0
#endif 

#define BALL_C5 PAD_GPIO20
#define PAD_GPIO20 67
#define GPIO_PAD_67 GPIO66
#ifndef BALL_C5_IS_GPIO
#define BALL_C5_IS_GPIO 0
#endif 
#ifndef PAD_GPIO20_IS_GPIO
#define PAD_GPIO20_IS_GPIO BALL_C5_IS_GPIO
#endif 

#define BALL_P17 PAD_DDCR_CK
#define PAD_DDCR_CK 83
#define GPIO_PAD_83 GPIO82
#ifndef BALL_P17_IS_GPIO
#define BALL_P17_IS_GPIO 0
#endif 
#ifndef PAD_DDCR_CK_IS_GPIO
#define PAD_DDCR_CK_IS_GPIO BALL_P17_IS_GPIO
#endif 

#define PAD_GPIO24 9999
#ifndef PAD_GPIO24_IS_GPIO
#define PAD_GPIO24_IS_GPIO 0
#endif 

#define BALL_K19 PAD_I2S_OUT_MCK
#define PAD_I2S_OUT_MCK 171
#define GPIO_PAD_171 GPIO170
#ifndef BALL_K19_IS_GPIO
#define BALL_K19_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_MCK_IS_GPIO
#define PAD_I2S_OUT_MCK_IS_GPIO BALL_K19_IS_GPIO
#endif 

#define PAD_GPIO21 9999
#ifndef PAD_GPIO21_IS_GPIO
#define PAD_GPIO21_IS_GPIO 0
#endif 

#define BALL_J20 PAD_I2S_OUT_WS
#define PAD_I2S_OUT_WS 172
#define GPIO_PAD_172 GPIO171
#ifndef BALL_J20_IS_GPIO
#define BALL_J20_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_WS_IS_GPIO
#define PAD_I2S_OUT_WS_IS_GPIO BALL_J20_IS_GPIO
#endif 

#define PAD_GPIO23 9999
#ifndef PAD_GPIO23_IS_GPIO
#define PAD_GPIO23_IS_GPIO 0
#endif 

#define BALL_J21 PAD_I2S_OUT_BCK
#define PAD_I2S_OUT_BCK 173
#define GPIO_PAD_173 GPIO172
#ifndef BALL_J21_IS_GPIO
#define BALL_J21_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_BCK_IS_GPIO
#define PAD_I2S_OUT_BCK_IS_GPIO BALL_J21_IS_GPIO
#endif 

#define PAD_GPIO12 9999
#ifndef PAD_GPIO12_IS_GPIO
#define PAD_GPIO12_IS_GPIO 0
#endif 

#define BALL_J19 PAD_I2S_OUT_SD
#define PAD_I2S_OUT_SD 174
#define GPIO_PAD_174 GPIO173
#ifndef BALL_J19_IS_GPIO
#define BALL_J19_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_SD_IS_GPIO
#define PAD_I2S_OUT_SD_IS_GPIO BALL_J19_IS_GPIO
#endif 

#define PAD_GPIO13 9999
#ifndef PAD_GPIO13_IS_GPIO
#define PAD_GPIO13_IS_GPIO 0
#endif 

#define BALL_R18 PAD_SPDIF_OUT
#define PAD_SPDIF_OUT 170
#define GPIO_PAD_170 GPIO169
#ifndef BALL_R18_IS_GPIO
#define BALL_R18_IS_GPIO 0
#endif 
#ifndef PAD_SPDIF_OUT_IS_GPIO
#define PAD_SPDIF_OUT_IS_GPIO BALL_R18_IS_GPIO
#endif 

#define PAD_PM_SPI_HOLDN 9999
#ifndef PAD_PM_SPI_HOLDN_IS_GPIO
#define PAD_PM_SPI_HOLDN_IS_GPIO 0
#endif 

#define BALL_A2 PAD_PM_SPI_DI
#define PAD_PM_SPI_DI 3
#define GPIO_PAD_3 GPIO2
#ifndef BALL_A2_IS_GPIO
#define BALL_A2_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_DI_IS_GPIO
#define PAD_PM_SPI_DI_IS_GPIO BALL_A2_IS_GPIO
#endif 

#define PAD_PM_SPI_CZ 9999
#ifndef PAD_PM_SPI_CZ_IS_GPIO
#define PAD_PM_SPI_CZ_IS_GPIO 0
#endif 

#define PAD_PM_SPI_CK 9999
#ifndef PAD_PM_SPI_CK_IS_GPIO
#define PAD_PM_SPI_CK_IS_GPIO 0
#endif 

#define PAD_GPIO_PM8 9999
#ifndef PAD_GPIO_PM8_IS_GPIO
#define PAD_GPIO_PM8_IS_GPIO 0
#endif 

#define PAD_PM_SPI_DO 9999
#ifndef PAD_PM_SPI_DO_IS_GPIO
#define PAD_PM_SPI_DO_IS_GPIO 0
#endif 

#define PAD_GPIO_PM3 9999
#ifndef PAD_GPIO_PM3_IS_GPIO
#define PAD_GPIO_PM3_IS_GPIO 0
#endif 

#define PAD_PM_SPI_WPN 9999
#ifndef PAD_PM_SPI_WPN_IS_GPIO
#define PAD_PM_SPI_WPN_IS_GPIO 0
#endif 

#define PAD_GPIO_PM6 9999
#ifndef PAD_GPIO_PM6_IS_GPIO
#define PAD_GPIO_PM6_IS_GPIO 0
#endif 

#define BALL_D5 PAD_HOTPLUGA
#define PAD_HOTPLUGA 27
#define GPIO_PAD_27 GPIO26
#ifndef BALL_D5_IS_GPIO
#define BALL_D5_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGA_IS_GPIO
#define PAD_HOTPLUGA_IS_GPIO BALL_D5_IS_GPIO
#endif 

#define BALL_A3 PAD_IRIN
#define PAD_IRIN 9
#define GPIO_PAD_9 GPIO8
#ifndef BALL_A3_IS_GPIO
#define BALL_A3_IS_GPIO 0
#endif 
#ifndef PAD_IRIN_IS_GPIO
#define PAD_IRIN_IS_GPIO BALL_A3_IS_GPIO
#endif 

#define BALL_D8 PAD_GPIO_PM7
#define PAD_GPIO_PM7 18
#define GPIO_PAD_18 GPIO17
#ifndef BALL_D8_IS_GPIO
#define BALL_D8_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM7_IS_GPIO
#define PAD_GPIO_PM7_IS_GPIO BALL_D8_IS_GPIO
#endif 

#define BALL_F5 PAD_DDCDA_CK
#define PAD_DDCDA_CK 31
#define GPIO_PAD_31 GPIO30
#ifndef BALL_F5_IS_GPIO
#define BALL_F5_IS_GPIO 0
#endif 
#ifndef PAD_DDCDA_CK_IS_GPIO
#define PAD_DDCDA_CK_IS_GPIO BALL_F5_IS_GPIO
#endif 

#define BALL_E9 PAD_PWM_PM
#define PAD_PWM_PM 44
#define GPIO_PAD_44 GPIO43
#ifndef BALL_E9_IS_GPIO
#define BALL_E9_IS_GPIO 0
#endif 
#ifndef PAD_PWM_PM_IS_GPIO
#define PAD_PWM_PM_IS_GPIO BALL_E9_IS_GPIO
#endif 

#define BALL_F6 PAD_DDCDA_DA
#define PAD_DDCDA_DA 32
#define GPIO_PAD_32 GPIO31
#ifndef BALL_F6_IS_GPIO
#define BALL_F6_IS_GPIO 0
#endif 
#ifndef PAD_DDCDA_DA_IS_GPIO
#define PAD_DDCDA_DA_IS_GPIO BALL_F6_IS_GPIO
#endif 

#define PAD_GPIO_PM9 9999
#ifndef PAD_GPIO_PM9_IS_GPIO
#define PAD_GPIO_PM9_IS_GPIO 0
#endif 

#define BALL_F4 PAD_CEC
#define PAD_CEC 10
#define GPIO_PAD_10 GPIO9
#ifndef BALL_F4_IS_GPIO
#define BALL_F4_IS_GPIO 0
#endif 
#ifndef PAD_CEC_IS_GPIO
#define PAD_CEC_IS_GPIO BALL_F4_IS_GPIO
#endif 

#define BALL_G4 PAD_GPIO_PM0
#define PAD_GPIO_PM0 11
#define GPIO_PAD_11 GPIO10
#ifndef BALL_G4_IS_GPIO
#define BALL_G4_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM0_IS_GPIO
#define PAD_GPIO_PM0_IS_GPIO BALL_G4_IS_GPIO
#endif 

#define BALL_E7 PAD_DDCA_CK
#define PAD_DDCA_CK 45
#define GPIO_PAD_45 GPIO44
#ifndef BALL_E7_IS_GPIO
#define BALL_E7_IS_GPIO 0
#endif 
#ifndef PAD_DDCA_CK_IS_GPIO
#define PAD_DDCA_CK_IS_GPIO BALL_E7_IS_GPIO
#endif 

#define PAD_GPIO_PM15 9999
#ifndef PAD_GPIO_PM15_IS_GPIO
#define PAD_GPIO_PM15_IS_GPIO 0
#endif 

#define BALL_E8 PAD_DDCA_DA
#define PAD_DDCA_DA 46
#define GPIO_PAD_46 GPIO45
#ifndef BALL_E8_IS_GPIO
#define BALL_E8_IS_GPIO 0
#endif 
#ifndef PAD_DDCA_DA_IS_GPIO
#define PAD_DDCA_DA_IS_GPIO BALL_E8_IS_GPIO
#endif 

#define PAD_GPIO_PM2 9999
#ifndef PAD_GPIO_PM2_IS_GPIO
#define PAD_GPIO_PM2_IS_GPIO 0
#endif 

#define BALL_B1 PAD_GPIO_PM4
#define PAD_GPIO_PM4 15
#define GPIO_PAD_15 GPIO14
#ifndef BALL_B1_IS_GPIO
#define BALL_B1_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM4_IS_GPIO
#define PAD_GPIO_PM4_IS_GPIO BALL_B1_IS_GPIO
#endif 

#define BALL_C3 PAD_GPIO_PM13
#define PAD_GPIO_PM13 24
#define GPIO_PAD_24 GPIO23
#ifndef BALL_C3_IS_GPIO
#define BALL_C3_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM13_IS_GPIO
#define PAD_GPIO_PM13_IS_GPIO BALL_C3_IS_GPIO
#endif 

#define BALL_B2 PAD_GPIO_PM5
#define PAD_GPIO_PM5 16
#define GPIO_PAD_16 GPIO15
#ifndef BALL_B2_IS_GPIO
#define BALL_B2_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM5_IS_GPIO
#define PAD_GPIO_PM5_IS_GPIO BALL_B2_IS_GPIO
#endif 

#define BALL_C4 PAD_SAR0
#define PAD_SAR0 39
#define GPIO_PAD_39 GPIO38
#ifndef BALL_C4_IS_GPIO
#define BALL_C4_IS_GPIO 0
#endif 
#ifndef PAD_SAR0_IS_GPIO
#define PAD_SAR0_IS_GPIO BALL_C4_IS_GPIO
#endif 

#define BALL_A4 PAD_SAR1
#define PAD_SAR1 40
#define GPIO_PAD_40 GPIO39
#ifndef BALL_A4_IS_GPIO
#define BALL_A4_IS_GPIO 0
#endif 
#ifndef PAD_SAR1_IS_GPIO
#define PAD_SAR1_IS_GPIO BALL_A4_IS_GPIO
#endif 

#define BALL_B4 PAD_SAR2
#define PAD_SAR2 41
#define GPIO_PAD_41 GPIO40
#ifndef BALL_B4_IS_GPIO
#define BALL_B4_IS_GPIO 0
#endif 
#ifndef PAD_SAR2_IS_GPIO
#define PAD_SAR2_IS_GPIO BALL_B4_IS_GPIO
#endif 

#define BALL_F8 PAD_SAR3
#define PAD_SAR3 42
#define GPIO_PAD_42 GPIO41
#ifndef BALL_F8_IS_GPIO
#define BALL_F8_IS_GPIO 0
#endif 
#ifndef PAD_SAR3_IS_GPIO
#define PAD_SAR3_IS_GPIO BALL_F8_IS_GPIO
#endif 

#define PAD_SAR4 9999
#ifndef PAD_SAR4_IS_GPIO
#define PAD_SAR4_IS_GPIO 0
#endif 

#define PAD_DDCDB_DA 9999
#ifndef PAD_DDCDB_DA_IS_GPIO
#define PAD_DDCDB_DA_IS_GPIO 0
#endif 

#define BALL_C2 PAD_GPIO_PM14
#define PAD_GPIO_PM14 25
#define GPIO_PAD_25 GPIO24
#ifndef BALL_C2_IS_GPIO
#define BALL_C2_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM14_IS_GPIO
#define PAD_GPIO_PM14_IS_GPIO BALL_C2_IS_GPIO
#endif 


// PADS group name to index
#define PADS_DDCR           1223
#define PADS_DDCR2          1224
#define PADS_TS0            1225
#define PADS_TS1            1226
#define PADS_GPIO1_GPIO2    1227
#define PADS_LHSYNC2_LVSYNC2 1228
#define PADS_PCI_AD20_AD21  1229
#define PADS_PCI            1230
#define PADS_PCM            1231
#define PADS_SAR            1232
#define PADS_DOUT           1233
#define PADS_DIN            1234
#define PADS_I2S            1235
#define PADS_PF             1236
#define PADS_EMAC           1237
#define PADS_TCON           1238
#define PADS_UART1_MODE1    1239
#define PADS_UART1_MODE2    1240
#define PADS_UART1_MODE3    1241
#define PADS_UART2_MODE1    1242
#define PADS_UART2_MODE2    1243
#define PADS_UART2_MODE3    1244
#define PADS_ET_MODE0       1245
#define PADS_ET_MODE1       1246
#define PADS_ET_MODE2       1247
#define PADS_ET_MODE3       1248
#define PADS_MIIC           1249
#define PADS_PF_MODE1       1250
#define PADS_PF_MODE2       1251
#define PADS_PF_MODE3       1252
#define PADS_SPI_CZ1        1253
#define PADS_SPI_CZ2        1254
#define PADS_SPI_CZ3        1255
#define PADS_DDCR3          1256

// chip capbilities
#define CHIP_HAS_BT656_IN          0
#define CHIP_HAS_TS0               1
#define CHIP_HAS_TS1               0
#define CHIP_HAS_LVDS_10BIT_X2     1
#define CHIP_HAS_LVDS_8BIT_X2      1
#define CHIP_HAS_LVDS_8BIT_X1      1
#define CHIP_HAS_CIMAX             0
#define CHIP_HAS_USB_P0            1
#define CHIP_HAS_USB_P1            1
#define CHIP_HAS_USBVBUS0          0
#define CHIP_HAS_USBVBUS1          0
#define CHIP_HAS_UART1_MODE1       1
#define CHIP_HAS_UART1_MODE2       1
#define CHIP_HAS_UART1_MODE3       1
#define CHIP_HAS_PCMCIA1           0
#define CHIP_HAS_PCMCIA2           0
#define CHIP_HAS_PCMCIA            0
#define CHIP_HAS_UART2_MODE1       1
#define CHIP_HAS_UART2_MODE2       1
#define CHIP_HAS_UART2_MODE3       1
#define CHIP_HAS_RGB_A             1
#define CHIP_HAS_RGB_B             1
#define CHIP_HAS_RGB_C             1
#define CHIP_HAS_HDMI_A            1
#define CHIP_HAS_HDMI_B            1
#define CHIP_HAS_HDMI_C            1
#define CHIP_HAS_SPI_CZ1           1
#define CHIP_HAS_SPI_CZ2           0
#define CHIP_HAS_SPI_CZ3           0
#define CHIP_HAS_DDCR              1
#define CHIP_HAS_DDCR2             1
#define CHIP_HAS_TCON              1
#define CHIP_HAS_ET_MODE0_MII      1
#define CHIP_HAS_ET_MODE0_RMII     1
#define CHIP_HAS_ET_MODE1_MII      1
#define CHIP_HAS_ET_MODE1_RMII     1
#define CHIP_HAS_ET_MODE2_MII      1
#define CHIP_HAS_ET_MODE2_RMII     1
#define CHIP_HAS_I2S_IN            1
#define CHIP_HAS_I2S_OUT           1
#define CHIP_HAS_SPDIF_IN          0
#define CHIP_HAS_SPDIF_OUT         1
#define CHIP_HAS_DDR_A_CMD         1
#define CHIP_HAS_DDR_A_DATA        1
#define CHIP_HAS_DDR_B_CMD         1
#define CHIP_HAS_DDR_B_DATA        1
#define CHIP_USE_PCM_CDN_IN_PCM2   0
#define CHIP_USE_I2S_IN_IN_PCM     0
#define CHIP_USE_I2S_OUT_IN_PCM    0
#define CHIP_USE_SPDIF_IN_IN_PCM   0
#define CHIP_USE_SPDIF_OUT_IN_PCM  0
#define CHIP_USE_IIC_IN_DDCR2      0
#define CHIP_USE_PWM2_IN_GPIO14    0
#define CHIP_USE_PWM3_IN_GPIO15    0

// chip additional information
#define CHIP_FAMILY_TYPE           CHIP_FAMILY_MUNICH

#endif /* _MSD93F1TX_H_*/
