/* SPDX-License-Identifier: GPL-2.0-only OR BSD-3-Clause */
/******************************************************************************
 *
 * This file is provided under a dual license.  When you use or
 * distribute this software, you may choose to be licensed under
 * version 2 of the GNU General Public License ("GPLv2 License")
 * or BSD License.
 *
 * GPLv2 License
 *
 * Copyright(C) 2019 MediaTek Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of version 2 of the GNU General Public License as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See http://www.gnu.org/licenses/gpl-2.0.html for more details.
 *
 * BSD LICENSE
 *
 * Copyright(C) 2019 MediaTek Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *****************************************************************************/

// This file is generated by script file, please do not edit it directly 
#ifndef _MSD95WPM8_SEC_H_
#define _MSD95WPM8_SEC_H_

#define PAD_NC   9999
#define PAD_GND  0

#define BALL_D10 PAD_CEC0
#define PAD_CEC0 2
#define GPIO_PAD_2 GPIO1
#ifndef BALL_D10_IS_GPIO
#define BALL_D10_IS_GPIO 0
#endif 
#ifndef PAD_CEC0_IS_GPIO
#define PAD_CEC0_IS_GPIO BALL_D10_IS_GPIO
#endif 

#define BALL_F9 PAD_HOTPLUGA_HDMI20_5V
#define PAD_HOTPLUGA_HDMI20_5V 22
#define GPIO_PAD_22 GPIO21
#ifndef BALL_F9_IS_GPIO
#define BALL_F9_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGA_HDMI20_5V_IS_GPIO
#define PAD_HOTPLUGA_HDMI20_5V_IS_GPIO BALL_F9_IS_GPIO
#endif 

#define BALL_F6 PAD_HOTPLUGB_HDMI20_5V
#define PAD_HOTPLUGB_HDMI20_5V 23
#define GPIO_PAD_23 GPIO22
#ifndef BALL_F6_IS_GPIO
#define BALL_F6_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGB_HDMI20_5V_IS_GPIO
#define PAD_HOTPLUGB_HDMI20_5V_IS_GPIO BALL_F6_IS_GPIO
#endif 

#define BALL_E6 PAD_HOTPLUGC_HDMI20_5V
#define PAD_HOTPLUGC_HDMI20_5V 24
#define GPIO_PAD_24 GPIO23
#ifndef BALL_E6_IS_GPIO
#define BALL_E6_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGC_HDMI20_5V_IS_GPIO
#define PAD_HOTPLUGC_HDMI20_5V_IS_GPIO BALL_E6_IS_GPIO
#endif 

#define BALL_N2 PAD_GPIO6_PM
#define PAD_GPIO6_PM 12
#define GPIO_PAD_12 GPIO11
#ifndef BALL_N2_IS_GPIO
#define BALL_N2_IS_GPIO 0
#endif 
#ifndef PAD_GPIO6_PM_IS_GPIO
#define PAD_GPIO6_PM_IS_GPIO BALL_N2_IS_GPIO
#endif 

#define BALL_R3 PAD_GPIO9_PM
#define PAD_GPIO9_PM 15
#define GPIO_PAD_15 GPIO14
#ifndef BALL_R3_IS_GPIO
#define BALL_R3_IS_GPIO 0
#endif 
#ifndef PAD_GPIO9_PM_IS_GPIO
#define PAD_GPIO9_PM_IS_GPIO BALL_R3_IS_GPIO
#endif 

#define BALL_AA3 PAD_GPIO10_PM
#define PAD_GPIO10_PM 16
#define GPIO_PAD_16 GPIO15
#ifndef BALL_AA3_IS_GPIO
#define BALL_AA3_IS_GPIO 0
#endif 
#ifndef PAD_GPIO10_PM_IS_GPIO
#define PAD_GPIO10_PM_IS_GPIO BALL_AA3_IS_GPIO
#endif 

#define BALL_AF2 PAD_TGPIO0
#define PAD_TGPIO0 77
#define GPIO_PAD_77 GPIO76
#ifndef BALL_AF2_IS_GPIO
#define BALL_AF2_IS_GPIO 0
#endif 
#ifndef PAD_TGPIO0_IS_GPIO
#define PAD_TGPIO0_IS_GPIO BALL_AF2_IS_GPIO
#endif 

#define BALL_AA2 PAD_TGPIO1
#define PAD_TGPIO1 78
#define GPIO_PAD_78 GPIO77
#ifndef BALL_AA2_IS_GPIO
#define BALL_AA2_IS_GPIO 0
#endif 
#ifndef PAD_TGPIO1_IS_GPIO
#define PAD_TGPIO1_IS_GPIO BALL_AA2_IS_GPIO
#endif 

#define BALL_AB5 PAD_TGPIO2
#define PAD_TGPIO2 79
#define GPIO_PAD_79 GPIO78
#ifndef BALL_AB5_IS_GPIO
#define BALL_AB5_IS_GPIO 0
#endif 
#ifndef PAD_TGPIO2_IS_GPIO
#define PAD_TGPIO2_IS_GPIO BALL_AB5_IS_GPIO
#endif 

#define BALL_AB6 PAD_TGPIO3
#define PAD_TGPIO3 80
#define GPIO_PAD_80 GPIO79
#ifndef BALL_AB6_IS_GPIO
#define BALL_AB6_IS_GPIO 0
#endif 
#ifndef PAD_TGPIO3_IS_GPIO
#define PAD_TGPIO3_IS_GPIO BALL_AB6_IS_GPIO
#endif 

#define PAD_GPIO25 9999
#ifndef PAD_GPIO25_IS_GPIO
#define PAD_GPIO25_IS_GPIO 0
#endif 

#define PAD_GPIO26 9999
#ifndef PAD_GPIO26_IS_GPIO
#define PAD_GPIO26_IS_GPIO 0
#endif 

#define PAD_GPIO30 9999
#ifndef PAD_GPIO30_IS_GPIO
#define PAD_GPIO30_IS_GPIO 0
#endif 

#define PAD_GPIO31 9999
#ifndef PAD_GPIO31_IS_GPIO
#define PAD_GPIO31_IS_GPIO 0
#endif 

#define BALL_M22 PAD_SD_D3
#define PAD_SD_D3 74
#define GPIO_PAD_74 GPIO73
#ifndef BALL_M22_IS_GPIO
#define BALL_M22_IS_GPIO 0
#endif 
#ifndef PAD_SD_D3_IS_GPIO
#define PAD_SD_D3_IS_GPIO BALL_M22_IS_GPIO
#endif 

#define BALL_N22 PAD_SD_D2
#define PAD_SD_D2 73
#define GPIO_PAD_73 GPIO72
#ifndef BALL_N22_IS_GPIO
#define BALL_N22_IS_GPIO 0
#endif 
#ifndef PAD_SD_D2_IS_GPIO
#define PAD_SD_D2_IS_GPIO BALL_N22_IS_GPIO
#endif 

#define BALL_P22 PAD_SD_D1
#define PAD_SD_D1 72
#define GPIO_PAD_72 GPIO71
#ifndef BALL_P22_IS_GPIO
#define BALL_P22_IS_GPIO 0
#endif 
#ifndef PAD_SD_D1_IS_GPIO
#define PAD_SD_D1_IS_GPIO BALL_P22_IS_GPIO
#endif 

#define BALL_P23 PAD_SD_D0
#define PAD_SD_D0 71
#define GPIO_PAD_71 GPIO70
#ifndef BALL_P23_IS_GPIO
#define BALL_P23_IS_GPIO 0
#endif 
#ifndef PAD_SD_D0_IS_GPIO
#define PAD_SD_D0_IS_GPIO BALL_P23_IS_GPIO
#endif 

#define BALL_R22 PAD_SD_CMD
#define PAD_SD_CMD 70
#define GPIO_PAD_70 GPIO69
#ifndef BALL_R22_IS_GPIO
#define BALL_R22_IS_GPIO 0
#endif 
#ifndef PAD_SD_CMD_IS_GPIO
#define PAD_SD_CMD_IS_GPIO BALL_R22_IS_GPIO
#endif 

#define BALL_T22 PAD_SD_CLK
#define PAD_SD_CLK 69
#define GPIO_PAD_69 GPIO68
#ifndef BALL_T22_IS_GPIO
#define BALL_T22_IS_GPIO 0
#endif 
#ifndef PAD_SD_CLK_IS_GPIO
#define PAD_SD_CLK_IS_GPIO BALL_T22_IS_GPIO
#endif 

#define BALL_J21 PAD_TS1_CLK
#define PAD_TS1_CLK 81
#define GPIO_PAD_81 GPIO80
#ifndef BALL_J21_IS_GPIO
#define BALL_J21_IS_GPIO 0
#endif 
#ifndef PAD_TS1_CLK_IS_GPIO
#define PAD_TS1_CLK_IS_GPIO BALL_J21_IS_GPIO
#endif 

#define BALL_L21 PAD_TS1_SYNC
#define PAD_TS1_SYNC 90
#define GPIO_PAD_90 GPIO89
#ifndef BALL_L21_IS_GPIO
#define BALL_L21_IS_GPIO 0
#endif 
#ifndef PAD_TS1_SYNC_IS_GPIO
#define PAD_TS1_SYNC_IS_GPIO BALL_L21_IS_GPIO
#endif 

#define BALL_K21 PAD_TS1_VLD
#define PAD_TS1_VLD 91
#define GPIO_PAD_91 GPIO90
#ifndef BALL_K21_IS_GPIO
#define BALL_K21_IS_GPIO 0
#endif 
#ifndef PAD_TS1_VLD_IS_GPIO
#define PAD_TS1_VLD_IS_GPIO BALL_K21_IS_GPIO
#endif 

#define BALL_K19 PAD_TS1_D7
#define PAD_TS1_D7 89
#define GPIO_PAD_89 GPIO88
#ifndef BALL_K19_IS_GPIO
#define BALL_K19_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D7_IS_GPIO
#define PAD_TS1_D7_IS_GPIO BALL_K19_IS_GPIO
#endif 

#define BALL_K20 PAD_TS1_D6
#define PAD_TS1_D6 88
#define GPIO_PAD_88 GPIO87
#ifndef BALL_K20_IS_GPIO
#define BALL_K20_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D6_IS_GPIO
#define PAD_TS1_D6_IS_GPIO BALL_K20_IS_GPIO
#endif 

#define BALL_J19 PAD_TS1_D5
#define PAD_TS1_D5 87
#define GPIO_PAD_87 GPIO86
#ifndef BALL_J19_IS_GPIO
#define BALL_J19_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D5_IS_GPIO
#define PAD_TS1_D5_IS_GPIO BALL_J19_IS_GPIO
#endif 

#define BALL_J20 PAD_TS1_D4
#define PAD_TS1_D4 86
#define GPIO_PAD_86 GPIO85
#ifndef BALL_J20_IS_GPIO
#define BALL_J20_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D4_IS_GPIO
#define PAD_TS1_D4_IS_GPIO BALL_J20_IS_GPIO
#endif 

#define BALL_L22 PAD_TS1_D3
#define PAD_TS1_D3 85
#define GPIO_PAD_85 GPIO84
#ifndef BALL_L22_IS_GPIO
#define BALL_L22_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D3_IS_GPIO
#define PAD_TS1_D3_IS_GPIO BALL_L22_IS_GPIO
#endif 

#define BALL_L23 PAD_TS1_D2
#define PAD_TS1_D2 84
#define GPIO_PAD_84 GPIO83
#ifndef BALL_L23_IS_GPIO
#define BALL_L23_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D2_IS_GPIO
#define PAD_TS1_D2_IS_GPIO BALL_L23_IS_GPIO
#endif 

#define BALL_J22 PAD_TS1_D1
#define PAD_TS1_D1 83
#define GPIO_PAD_83 GPIO82
#ifndef BALL_J22_IS_GPIO
#define BALL_J22_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D1_IS_GPIO
#define PAD_TS1_D1_IS_GPIO BALL_J22_IS_GPIO
#endif 

#define BALL_J23 PAD_TS1_D0
#define PAD_TS1_D0 82
#define GPIO_PAD_82 GPIO81
#ifndef BALL_J23_IS_GPIO
#define BALL_J23_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D0_IS_GPIO
#define PAD_TS1_D0_IS_GPIO BALL_J23_IS_GPIO
#endif 

#define PAD_TS2_CLK 9999
#ifndef PAD_TS2_CLK_IS_GPIO
#define PAD_TS2_CLK_IS_GPIO 0
#endif 

#define PAD_TS2_SYNC 9999
#ifndef PAD_TS2_SYNC_IS_GPIO
#define PAD_TS2_SYNC_IS_GPIO 0
#endif 

#define PAD_TS2_VLD 9999
#ifndef PAD_TS2_VLD_IS_GPIO
#define PAD_TS2_VLD_IS_GPIO 0
#endif 

#define PAD_TS2_D0 9999
#ifndef PAD_TS2_D0_IS_GPIO
#define PAD_TS2_D0_IS_GPIO 0
#endif 

#define BALL_R23 PAD_GPIO9
#define PAD_GPIO9 49
#define GPIO_PAD_49 GPIO48
#ifndef BALL_R23_IS_GPIO
#define BALL_R23_IS_GPIO 0
#endif 
#ifndef PAD_GPIO9_IS_GPIO
#define PAD_GPIO9_IS_GPIO BALL_R23_IS_GPIO
#endif 

#define BALL_T23 PAD_GPIO10
#define PAD_GPIO10 50
#define GPIO_PAD_50 GPIO49
#ifndef BALL_T23_IS_GPIO
#define BALL_T23_IS_GPIO 0
#endif 
#ifndef PAD_GPIO10_IS_GPIO
#define PAD_GPIO10_IS_GPIO BALL_T23_IS_GPIO
#endif 

#define PAD_GPIO11 9999
#ifndef PAD_GPIO11_IS_GPIO
#define PAD_GPIO11_IS_GPIO 0
#endif 

#define PAD_GPIO12 9999
#ifndef PAD_GPIO12_IS_GPIO
#define PAD_GPIO12_IS_GPIO 0
#endif 

#define PAD_PWM3 9999
#ifndef PAD_PWM3_IS_GPIO
#define PAD_PWM3_IS_GPIO 0
#endif 

#define BALL_V24 PAD_PWM2
#define PAD_PWM2 67
#define GPIO_PAD_67 GPIO66
#ifndef BALL_V24_IS_GPIO
#define BALL_V24_IS_GPIO 0
#endif 
#ifndef PAD_PWM2_IS_GPIO
#define PAD_PWM2_IS_GPIO BALL_V24_IS_GPIO
#endif 

#define BALL_W25 PAD_PWM1
#define PAD_PWM1 66
#define GPIO_PAD_66 GPIO65
#ifndef BALL_W25_IS_GPIO
#define BALL_W25_IS_GPIO 0
#endif 
#ifndef PAD_PWM1_IS_GPIO
#define PAD_PWM1_IS_GPIO BALL_W25_IS_GPIO
#endif 

#define BALL_V25 PAD_PWM0
#define PAD_PWM0 65
#define GPIO_PAD_65 GPIO64
#ifndef BALL_V25_IS_GPIO
#define BALL_V25_IS_GPIO 0
#endif 
#ifndef PAD_PWM0_IS_GPIO
#define PAD_PWM0_IS_GPIO BALL_V25_IS_GPIO
#endif 

#define BALL_U24 PAD_GPIO19
#define PAD_GPIO19 53
#define GPIO_PAD_53 GPIO52
#ifndef BALL_U24_IS_GPIO
#define BALL_U24_IS_GPIO 0
#endif 
#ifndef PAD_GPIO19_IS_GPIO
#define PAD_GPIO19_IS_GPIO BALL_U24_IS_GPIO
#endif 

#define BALL_U25 PAD_GPIO20
#define PAD_GPIO20 54
#define GPIO_PAD_54 GPIO53
#ifndef BALL_U25_IS_GPIO
#define BALL_U25_IS_GPIO 0
#endif 
#ifndef PAD_GPIO20_IS_GPIO
#define PAD_GPIO20_IS_GPIO BALL_U25_IS_GPIO
#endif 

#define BALL_Y24 PAD_GPIO2
#define PAD_GPIO2 45
#define GPIO_PAD_45 GPIO44
#ifndef BALL_Y24_IS_GPIO
#define BALL_Y24_IS_GPIO 0
#endif 
#ifndef PAD_GPIO2_IS_GPIO
#define PAD_GPIO2_IS_GPIO BALL_Y24_IS_GPIO
#endif 

#define BALL_Y26 PAD_GPIO3
#define PAD_GPIO3 46
#define GPIO_PAD_46 GPIO45
#ifndef BALL_Y26_IS_GPIO
#define BALL_Y26_IS_GPIO 0
#endif 
#ifndef PAD_GPIO3_IS_GPIO
#define PAD_GPIO3_IS_GPIO BALL_Y26_IS_GPIO
#endif 

#define BALL_W24 PAD_GPIO4
#define PAD_GPIO4 47
#define GPIO_PAD_47 GPIO46
#ifndef BALL_W24_IS_GPIO
#define BALL_W24_IS_GPIO 0
#endif 
#ifndef PAD_GPIO4_IS_GPIO
#define PAD_GPIO4_IS_GPIO BALL_W24_IS_GPIO
#endif 

#define BALL_Y25 PAD_GPIO5
#define PAD_GPIO5 48
#define GPIO_PAD_48 GPIO47
#ifndef BALL_Y25_IS_GPIO
#define BALL_Y25_IS_GPIO 0
#endif 
#ifndef PAD_GPIO5_IS_GPIO
#define PAD_GPIO5_IS_GPIO BALL_Y25_IS_GPIO
#endif 

#define BALL_C13 PAD_DDCR_DA
#define PAD_DDCR_DA 44
#define GPIO_PAD_44 GPIO43
#ifndef BALL_C13_IS_GPIO
#define BALL_C13_IS_GPIO 0
#endif 
#ifndef PAD_DDCR_DA_IS_GPIO
#define PAD_DDCR_DA_IS_GPIO BALL_C13_IS_GPIO
#endif 

#define BALL_B13 PAD_DDCR_CK
#define PAD_DDCR_CK 43
#define GPIO_PAD_43 GPIO42
#ifndef BALL_B13_IS_GPIO
#define BALL_B13_IS_GPIO 0
#endif 
#ifndef PAD_DDCR_CK_IS_GPIO
#define PAD_DDCR_CK_IS_GPIO BALL_B13_IS_GPIO
#endif 

#define BALL_F10 PAD_ARC0
#define PAD_ARC0 42
#define GPIO_PAD_42 GPIO41
#ifndef BALL_F10_IS_GPIO
#define BALL_F10_IS_GPIO 0
#endif 
#ifndef PAD_ARC0_IS_GPIO
#define PAD_ARC0_IS_GPIO BALL_F10_IS_GPIO
#endif 

#define BALL_C9 PAD_SPDIF_OUT
#define PAD_SPDIF_OUT 76
#define GPIO_PAD_76 GPIO75
#ifndef BALL_C9_IS_GPIO
#define BALL_C9_IS_GPIO 0
#endif 
#ifndef PAD_SPDIF_OUT_IS_GPIO
#define PAD_SPDIF_OUT_IS_GPIO BALL_C9_IS_GPIO
#endif 

#define PAD_SPDIF_IN 9999
#ifndef PAD_SPDIF_IN_IS_GPIO
#define PAD_SPDIF_IN_IS_GPIO 0
#endif 

#define PAD_I2S_OUT_SD1 9999
#ifndef PAD_I2S_OUT_SD1_IS_GPIO
#define PAD_I2S_OUT_SD1_IS_GPIO 0
#endif 

#define PAD_I2S_OUT_SD2 9999
#ifndef PAD_I2S_OUT_SD2_IS_GPIO
#define PAD_I2S_OUT_SD2_IS_GPIO 0
#endif 

#define BALL_F12 PAD_I2S_OUT_SD
#define PAD_I2S_OUT_SD 61
#define GPIO_PAD_61 GPIO60
#ifndef BALL_F12_IS_GPIO
#define BALL_F12_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_SD_IS_GPIO
#define PAD_I2S_OUT_SD_IS_GPIO BALL_F12_IS_GPIO
#endif 

#define BALL_F14 PAD_I2S_OUT_MCK
#define PAD_I2S_OUT_MCK 60
#define GPIO_PAD_60 GPIO59
#ifndef BALL_F14_IS_GPIO
#define BALL_F14_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_MCK_IS_GPIO
#define PAD_I2S_OUT_MCK_IS_GPIO BALL_F14_IS_GPIO
#endif 

#define BALL_E13 PAD_I2S_OUT_WS
#define PAD_I2S_OUT_WS 64
#define GPIO_PAD_64 GPIO63
#ifndef BALL_E13_IS_GPIO
#define BALL_E13_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_WS_IS_GPIO
#define PAD_I2S_OUT_WS_IS_GPIO BALL_E13_IS_GPIO
#endif 

#define BALL_F13 PAD_I2S_OUT_BCK
#define PAD_I2S_OUT_BCK 59
#define GPIO_PAD_59 GPIO58
#ifndef BALL_F13_IS_GPIO
#define BALL_F13_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_BCK_IS_GPIO
#define PAD_I2S_OUT_BCK_IS_GPIO BALL_F13_IS_GPIO
#endif 

#define BALL_B5 PAD_SAR0
#define PAD_SAR0 31
#define GPIO_PAD_31 GPIO30
#ifndef BALL_B5_IS_GPIO
#define BALL_B5_IS_GPIO 0
#endif 
#ifndef PAD_SAR0_IS_GPIO
#define PAD_SAR0_IS_GPIO BALL_B5_IS_GPIO
#endif 

#define BALL_C6 PAD_SAR1
#define PAD_SAR1 32
#define GPIO_PAD_32 GPIO31
#ifndef BALL_C6_IS_GPIO
#define BALL_C6_IS_GPIO 0
#endif 
#ifndef PAD_SAR1_IS_GPIO
#define PAD_SAR1_IS_GPIO BALL_C6_IS_GPIO
#endif 

#define BALL_A6 PAD_SAR2
#define PAD_SAR2 33
#define GPIO_PAD_33 GPIO32
#ifndef BALL_A6_IS_GPIO
#define BALL_A6_IS_GPIO 0
#endif 
#ifndef PAD_SAR2_IS_GPIO
#define PAD_SAR2_IS_GPIO BALL_A6_IS_GPIO
#endif 

#define BALL_B6 PAD_SAR3
#define PAD_SAR3 34
#define GPIO_PAD_34 GPIO33
#ifndef BALL_B6_IS_GPIO
#define BALL_B6_IS_GPIO 0
#endif 
#ifndef PAD_SAR3_IS_GPIO
#define PAD_SAR3_IS_GPIO BALL_B6_IS_GPIO
#endif 

#define PAD_SAR4 9999
#ifndef PAD_SAR4_IS_GPIO
#define PAD_SAR4_IS_GPIO 0
#endif 

#define BALL_C5 PAD_VPLUGIN
#define PAD_VPLUGIN 36
#define GPIO_PAD_36 GPIO35
#ifndef BALL_C5_IS_GPIO
#define BALL_C5_IS_GPIO 0
#endif 
#ifndef PAD_VPLUGIN_IS_GPIO
#define PAD_VPLUGIN_IS_GPIO BALL_C5_IS_GPIO
#endif 

#define BALL_A13 PAD_WOL_INT_OUT
#define PAD_WOL_INT_OUT 41
#define GPIO_PAD_41 GPIO40
#ifndef BALL_A13_IS_GPIO
#define BALL_A13_IS_GPIO 0
#endif 
#ifndef PAD_WOL_INT_OUT_IS_GPIO
#define PAD_WOL_INT_OUT_IS_GPIO BALL_A13_IS_GPIO
#endif 

#define PAD_VID3 9999
#ifndef PAD_VID3_IS_GPIO
#define PAD_VID3_IS_GPIO 0
#endif 

#define PAD_VID2 9999
#ifndef PAD_VID2_IS_GPIO
#define PAD_VID2_IS_GPIO 0
#endif 

#define BALL_E11 PAD_VID1
#define PAD_VID1 38
#define GPIO_PAD_38 GPIO37
#ifndef BALL_E11_IS_GPIO
#define BALL_E11_IS_GPIO 0
#endif 
#ifndef PAD_VID1_IS_GPIO
#define PAD_VID1_IS_GPIO BALL_E11_IS_GPIO
#endif 

#define BALL_D13 PAD_VID0
#define PAD_VID0 37
#define GPIO_PAD_37 GPIO36
#ifndef BALL_D13_IS_GPIO
#define BALL_D13_IS_GPIO 0
#endif 
#ifndef PAD_VID0_IS_GPIO
#define PAD_VID0_IS_GPIO BALL_D13_IS_GPIO
#endif 

#define BALL_T3 PAD_GPIO12_PM
#define PAD_GPIO12_PM 18
#define GPIO_PAD_18 GPIO17
#ifndef BALL_T3_IS_GPIO
#define BALL_T3_IS_GPIO 0
#endif 
#ifndef PAD_GPIO12_PM_IS_GPIO
#define PAD_GPIO12_PM_IS_GPIO BALL_T3_IS_GPIO
#endif 

#define BALL_R2 PAD_GPIO11_PM
#define PAD_GPIO11_PM 17
#define GPIO_PAD_17 GPIO16
#ifndef BALL_R2_IS_GPIO
#define BALL_R2_IS_GPIO 0
#endif 
#ifndef PAD_GPIO11_PM_IS_GPIO
#define PAD_GPIO11_PM_IS_GPIO BALL_R2_IS_GPIO
#endif 

#define BALL_M4 PAD_GPIO7_PM
#define PAD_GPIO7_PM 13
#define GPIO_PAD_13 GPIO12
#ifndef BALL_M4_IS_GPIO
#define BALL_M4_IS_GPIO 0
#endif 
#ifndef PAD_GPIO7_PM_IS_GPIO
#define PAD_GPIO7_PM_IS_GPIO BALL_M4_IS_GPIO
#endif 

#define BALL_D11 PAD_GPIO0_PM
#define PAD_GPIO0_PM 6
#define GPIO_PAD_6 GPIO5
#ifndef BALL_D11_IS_GPIO
#define BALL_D11_IS_GPIO 0
#endif 
#ifndef PAD_GPIO0_PM_IS_GPIO
#define PAD_GPIO0_PM_IS_GPIO BALL_D11_IS_GPIO
#endif 

#define BALL_F11 PAD_GPIO2_PM
#define PAD_GPIO2_PM 8
#define GPIO_PAD_8 GPIO7
#ifndef BALL_F11_IS_GPIO
#define BALL_F11_IS_GPIO 0
#endif 
#ifndef PAD_GPIO2_PM_IS_GPIO
#define PAD_GPIO2_PM_IS_GPIO BALL_F11_IS_GPIO
#endif 

#define BALL_U3 PAD_GPIO4_PM
#define PAD_GPIO4_PM 10
#define GPIO_PAD_10 GPIO9
#ifndef BALL_U3_IS_GPIO
#define BALL_U3_IS_GPIO 0
#endif 
#ifndef PAD_GPIO4_PM_IS_GPIO
#define PAD_GPIO4_PM_IS_GPIO BALL_U3_IS_GPIO
#endif 

#define PAD_GPIO8_PM 9999
#ifndef PAD_GPIO8_PM_IS_GPIO
#define PAD_GPIO8_PM_IS_GPIO 0
#endif 

#define PAD_GPIO3_PM 9999
#ifndef PAD_GPIO3_PM_IS_GPIO
#define PAD_GPIO3_PM_IS_GPIO 0
#endif 

#define BALL_R1 PAD_PWM_PM
#define PAD_PWM_PM 3
#define GPIO_PAD_3 GPIO2
#ifndef BALL_R1_IS_GPIO
#define BALL_R1_IS_GPIO 0
#endif 
#ifndef PAD_PWM_PM_IS_GPIO
#define PAD_PWM_PM_IS_GPIO BALL_R1_IS_GPIO
#endif 

#define BALL_E8 PAD_DDCDA_CK
#define PAD_DDCDA_CK 25
#define GPIO_PAD_25 GPIO24
#ifndef BALL_E8_IS_GPIO
#define BALL_E8_IS_GPIO 0
#endif 
#ifndef PAD_DDCDA_CK_IS_GPIO
#define PAD_DDCDA_CK_IS_GPIO BALL_E8_IS_GPIO
#endif 

#define BALL_F8 PAD_DDCDA_DA
#define PAD_DDCDA_DA 26
#define GPIO_PAD_26 GPIO25
#ifndef BALL_F8_IS_GPIO
#define BALL_F8_IS_GPIO 0
#endif 
#ifndef PAD_DDCDA_DA_IS_GPIO
#define PAD_DDCDA_DA_IS_GPIO BALL_F8_IS_GPIO
#endif 

#define BALL_E7 PAD_DDCDB_CK
#define PAD_DDCDB_CK 27
#define GPIO_PAD_27 GPIO26
#ifndef BALL_E7_IS_GPIO
#define BALL_E7_IS_GPIO 0
#endif 
#ifndef PAD_DDCDB_CK_IS_GPIO
#define PAD_DDCDB_CK_IS_GPIO BALL_E7_IS_GPIO
#endif 

#define BALL_D7 PAD_DDCDB_DA
#define PAD_DDCDB_DA 28
#define GPIO_PAD_28 GPIO27
#ifndef BALL_D7_IS_GPIO
#define BALL_D7_IS_GPIO 0
#endif 
#ifndef PAD_DDCDB_DA_IS_GPIO
#define PAD_DDCDB_DA_IS_GPIO BALL_D7_IS_GPIO
#endif 

#define BALL_E5 PAD_DDCDC_CK
#define PAD_DDCDC_CK 29
#define GPIO_PAD_29 GPIO28
#ifndef BALL_E5_IS_GPIO
#define BALL_E5_IS_GPIO 0
#endif 
#ifndef PAD_DDCDC_CK_IS_GPIO
#define PAD_DDCDC_CK_IS_GPIO BALL_E5_IS_GPIO
#endif 

#define BALL_F5 PAD_DDCDC_DA
#define PAD_DDCDC_DA 30
#define GPIO_PAD_30 GPIO29
#ifndef BALL_F5_IS_GPIO
#define BALL_F5_IS_GPIO 0
#endif 
#ifndef PAD_DDCDC_DA_IS_GPIO
#define PAD_DDCDC_DA_IS_GPIO BALL_F5_IS_GPIO
#endif 

#define BALL_E10 PAD_HOTPLUGA
#define PAD_HOTPLUGA 19
#define GPIO_PAD_19 GPIO18
#ifndef BALL_E10_IS_GPIO
#define BALL_E10_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGA_IS_GPIO
#define PAD_HOTPLUGA_IS_GPIO BALL_E10_IS_GPIO
#endif 

#define BALL_F7 PAD_HOTPLUGB
#define PAD_HOTPLUGB 20
#define GPIO_PAD_20 GPIO19
#ifndef BALL_F7_IS_GPIO
#define BALL_F7_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGB_IS_GPIO
#define PAD_HOTPLUGB_IS_GPIO BALL_F7_IS_GPIO
#endif 

#define BALL_D5 PAD_HOTPLUGC
#define PAD_HOTPLUGC 21
#define GPIO_PAD_21 GPIO20
#ifndef BALL_D5_IS_GPIO
#define BALL_D5_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGC_IS_GPIO
#define PAD_HOTPLUGC_IS_GPIO BALL_D5_IS_GPIO
#endif 

#define BALL_L4 PAD_DDCA_CK
#define PAD_DDCA_CK 4
#define GPIO_PAD_4 GPIO3
#ifndef BALL_L4_IS_GPIO
#define BALL_L4_IS_GPIO 0
#endif 
#ifndef PAD_DDCA_CK_IS_GPIO
#define PAD_DDCA_CK_IS_GPIO BALL_L4_IS_GPIO
#endif 

#define BALL_M5 PAD_DDCA_DA
#define PAD_DDCA_DA 5
#define GPIO_PAD_5 GPIO4
#ifndef BALL_M5_IS_GPIO
#define BALL_M5_IS_GPIO 0
#endif 
#ifndef PAD_DDCA_DA_IS_GPIO
#define PAD_DDCA_DA_IS_GPIO BALL_M5_IS_GPIO
#endif 

#define BALL_Y6 PAD_GPIO1_PM
#define PAD_GPIO1_PM 7
#define GPIO_PAD_7 GPIO6
#ifndef BALL_Y6_IS_GPIO
#define BALL_Y6_IS_GPIO 0
#endif 
#ifndef PAD_GPIO1_PM_IS_GPIO
#define PAD_GPIO1_PM_IS_GPIO BALL_Y6_IS_GPIO
#endif 

#define BALL_AA6 PAD_GPIO5_PM
#define PAD_GPIO5_PM 11
#define GPIO_PAD_11 GPIO10
#ifndef BALL_AA6_IS_GPIO
#define BALL_AA6_IS_GPIO 0
#endif 
#ifndef PAD_GPIO5_PM_IS_GPIO
#define PAD_GPIO5_PM_IS_GPIO BALL_AA6_IS_GPIO
#endif 

#define BALL_T2 PAD_IRIN
#define PAD_IRIN 1
#define GPIO_PAD_1 GPIO0
#ifndef BALL_T2_IS_GPIO
#define BALL_T2_IS_GPIO 0
#endif 
#ifndef PAD_IRIN_IS_GPIO
#define PAD_IRIN_IS_GPIO BALL_T2_IS_GPIO
#endif 


// PADS group name to index
#define PADS_PCMCONFIG_MODE1        1223
#define PADS_PCMCONFIG_MODE2        1224
#define PADS_PCMCONFIG1_MODE1       1225
#define PADS_PCMCONFIG1_MODE2       1226
#define PADS_PCMCONFIG1_MODE3       1227
#define PADS_PCM2CONFIG_MODE1       1228
#define PADS_PCM2CONFIG_MODE2       1229
#define PADS_PCM2CONFIG_MODE3       1230
#define PADS_PCM2CONFIG1_MODE1      1231
#define PADS_PCM2CONFIG1_MODE2      1232
#define PADS_ET_MODE1               1233
#define PADS_ET_MODE2               1234
#define PADS_DDCR                   1235
#define PADS_DDCR2                  1236
#define PADS_PCM                    1237

// chip capbilities
#define CHIP_HAS_BT656_IN           0
#define CHIP_HAS_TS0                1
#define CHIP_HAS_TS1                0
#define CHIP_HAS_LVDS_10BIT_X2      1
#define CHIP_HAS_LVDS_8BIT_X2       1
#define CHIP_HAS_LVDS_8BIT_X1       1
#define CHIP_HAS_CIMAX              0
#define CHIP_HAS_USB_P0             1
#define CHIP_HAS_USB_P1             1
#define CHIP_HAS_USBVBUS0           0
#define CHIP_HAS_USBVBUS1           0
#define CHIP_HAS_UART1_MODE1        1
#define CHIP_HAS_UART1_MODE2        1
#define CHIP_HAS_UART1_MODE3        1
#define CHIP_HAS_PCMCIA1            0
#define CHIP_HAS_PCMCIA2            0
#define CHIP_HAS_PCMCIA             0
#define CHIP_HAS_UART2_MODE1        1
#define CHIP_HAS_UART2_MODE2        1
#define CHIP_HAS_UART2_MODE3        1
#define CHIP_HAS_RGB_A              1
#define CHIP_HAS_RGB_B              1
#define CHIP_HAS_RGB_C              1
#define CHIP_HAS_HDMI_A             1
#define CHIP_HAS_HDMI_B             1
#define CHIP_HAS_HDMI_C             1
#define CHIP_HAS_SPI_CZ1            1
#define CHIP_HAS_SPI_CZ2            0
#define CHIP_HAS_SPI_CZ3            0
#define CHIP_HAS_DDCR               1
#define CHIP_HAS_DDCR2              1
#define CHIP_HAS_TCON               1
#define CHIP_HAS_ET_MODE0_MII       1
#define CHIP_HAS_ET_MODE0_RMII      1
#define CHIP_HAS_ET_MODE1_MII       1
#define CHIP_HAS_ET_MODE1_RMII      1
#define CHIP_HAS_ET_MODE2_MII       1
#define CHIP_HAS_ET_MODE2_RMII      1
#define CHIP_HAS_I2S_IN             0
#define CHIP_HAS_I2S_OUT            0
#define CHIP_HAS_SPDIF_IN           0
#define CHIP_HAS_SPDIF_OUT          0
#define CHIP_HAS_DDR_A_CMD          1
#define CHIP_HAS_DDR_A_DATA         1
#define CHIP_HAS_DDR_B_CMD          1
#define CHIP_HAS_DDR_B_DATA         1
#define CHIP_USE_PCM_CDN_IN_PCM2    0
#define CHIP_USE_I2S_IN_IN_PCM      0
#define CHIP_USE_I2S_OUT_IN_PCM     0
#define CHIP_USE_SPDIF_IN_IN_PCM    0
#define CHIP_USE_SPDIF_OUT_IN_PCM   0
#define CHIP_USE_IIC_IN_DDCR2       0
#define CHIP_USE_PWM2_IN_GPIO14     0
#define CHIP_USE_PWM3_IN_GPIO15     0

// chip additional information
#define CHIP_FAMILY_TYPE            CHIP_FAMILY_MOONEY

#endif /* _MSD95WPM8_SEC_H_*/
